### ISSUE TITLE
Native Animated Event issues

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#10021]
I've found some issues with the `Native Animated Event`
1. If I hold a touchable view in the scrollview, then stop scrolling, when I release the touch, the `onPress` of the touchable view is fired, that makes `Native Animated Event` almost unavailable in real use case.
2. 'Native Animated Event' will made `onScroll` related events such as `onEndReached` unavailable in `ListView`, because the `onScroll` won't be called at all when turn on `useNativeDriver`, that breaks the common use case of `ListView` too.

I'm wondering is there any workaround for those issues, as I really need this `Native Animated Event` feature to improve the performance of my app. @janicduplessis

**Comment by leeight** [comment]
+1

**Comment by ramilushev** [comment]
I'm experiencing this on 0.36. Native animation works fine, but onEndReached is never called.

@nihgwu Did you manage to find a fix or a workaround?

@janicduplessis This is a big deal I think ..

**Comment by nihgwu** [comment]
@ramilushev This issue should be on both platforms and I don't know how to fix it, still waiting for @janicduplessis 😔

**Comment by janicduplessis** [comment]
The problem is that we don't send the event to JS if it is handled natively. I suggest removing this and always send the event.

See https://github.com/facebook/react-native/blob/master/React/Base/RCTEventDispatcher.m#L149 and https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcher.java#L117

We should also change the EventListener interfaces so they don't return a bool anymore. Let me know if one of you would like to send a PR, if not I'll try to work on this soon.

**Comment by AlbertBrand** [comment]
This is solved in RN 0.40 by https://github.com/facebook/react-native/pull/10981 right?

**Comment by nihgwu** [comment]
@AlbertBrand thanks for reminding, closing it.

**Comment by ramilushev** [comment]
This is still an issue for me, I am using RN v0.43.2

I pass the `renderScrollComponent` prop to `ListView` and render an `Animated.ScrollView` as a scroll component which has an `Animated.event()` for `onScroll`

The onScroll event is still not propagated and events such as `onEndReached` are never called.

@nihgwu could you share an example of how you got it to work? Thanks.

**Comment by lezin** [comment]
I have the same problem, @nihgwu could you share an example?

**Comment by nihgwu** [comment]
`const AnimatedListView = Animated.createAnimatedComponent(ListView)`
no need to define `renderScrollComponent `
