### ISSUE TITLE
touchableWithoutFeedback onPress and onPressOut not firing on Android

### ISSUE THREAD

**Issue by larryranches** [facebook/react-native#10180]
### Issue Description

touchableWithoutFeedback onPress and onPressOut function are not firing on Android specifically the Samsung Galaxy.

This is working perfectly fine on IOS10.
### Steps to Reproduce / Code Snippets

Code snippet of using the onPressOut function

`<TouchableWithoutFeedback onPressOut={ this.onStopRecording }>`
#### Expected Results

function should fire on Android. Is working for IOS!
### Additional Information
- React Native version: 0.33
- Platform(s) (iOS, Android, or both?): ANDROID
  Operating System (macOS, Linux, or Windows?): OSX

**Comment by larryranches** [comment]
Also not working on Nexus 5x. Any ideas? Seems to be only android related.

**Comment by marcshilling** [comment]
I've been having similar issues with `<TouchableWithoutFeedback>` on iOS as well. RN 0.34.1

**Comment by AndrewHenderson** [comment]
I found the following did not work with `TouchableWithoutFeedback` but is working with `TouchableOpacity` on React Native 0.37.0:

```jsx
return (
  <View style={styles.sceneContent}>
    <ScrollView>
      <TouchableOpacity
        onPress={this.handlePersonPress.bind(this)}
      >
        <PersonHeading
          photoUrl={this.state.person.photoUrl}
          name={this.state.person.firstName}
        />
      </TouchableOpacity>
      <Image
        style={{height: 250}}
        source={{uri: this.props.photoUrl}}
      />
      <View style={styles.eventContent}>
        <Text style={[styles.h2, styles.centerText]}>{this.props.description}</Text>
        <Text style={[styles.h3, styles.centerText]}>{this.props.location}</Text>
        <Text style={[styles.centerText]}>{renderTime(this.props.startTime)}</Text>
        <Text style={[styles.centerText]}>{renderTime(this.props.endTime)}</Text>
      </View>
      <View style={styles.scenePad}>
        <Button
          style={[styles.button, styles.backgroundBlue]}
        >
          Request to Join
        </Button>
      </View>
    </ScrollView>
  </View>
);
```
I wonder if it has something to do with being nested within the `ScrollView`, since I have it working fine in another component that is not the direct descendent of a `ScrollView`.

I'll upgrade to the latest version and update this comment with the results.

**Comment by coreoas** [comment]
It is working for me today, maybe it was solved in more recent versions (tested on 0.41).

**Comment by nouveller** [comment]
I've ran into this today, `TouchableWithoutFeedback` was working perfectly fine until it wasn’t. RN 0.41 and running in the up to date iOS simulator. Very bizarre.

**Comment by larryranches** [comment]
Any ideas on this? The onPressOut is still not firing only for Android. Working perfect on ios still. I'm now on RN 0.43

**Comment by koenpunt** [comment]
I found that it always needs to have child `View` component. So a component that composes a `View` isn't enough.

So instead of 

```jsx
< TouchableWithoutFeedback onPressIn={...} onPressOut={...} onPress={...}>
  <MyCustomComponent />
</TouchableWithoutFeedback>
```

I now use:

```jsx
< TouchableWithoutFeedback onPressIn={...} onPressOut={...} onPress={...}>
  <View>
    <MyCustomComponent />
  </View>
</TouchableWithoutFeedback>

**Comment by oliverbenns** [comment]
Fixed my issue thanks @koenpunt .

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/touchablewithoutfeedback-onpress-and-onpressout-not-firing-on-android

**Comment by mgagnon555** [comment]
It is not fixed (RN 0.50), unless "having to add a <View> and then it works" is considered fixed. The only child my TouchableWithoutFeedback had is a custom Header extending Component. Adding a View works but ... why?

**Comment by spearmootz** [comment]
yep. im having this issue right now. adding the view works but it messes up everything

**Comment by nicolasconnault** [comment]
Problem is still there, solution still works.

**Comment by Elijen** [comment]
@hramos Reopen so issues can actually get fixed?

**Comment by bala-compassites** [comment]
Its not working. Problem is still there.

**Comment by rafaelgrilli92** [comment]
@koenpunt approach worked for me.

**Comment by robhung** [comment]
It's strange because I've made a component that renders a `<View>` with pre-configured styles and even then, it doesn't work. It needs a completely new `<View` component for this to work.

RN 0.49.5

**Comment by katerynkas** [comment]
Not working for me too even with a View component inside.

**Comment by TheDutchCoder** [comment]
Still not working on RN 0.53.0

**Comment by Elijen** [comment]
I am sure any contributors already muted this issue so bumping it is pointless. Just use `<View>` component inside as @koenpunt suggested. If it's not working even with it, open a new issue.

**Comment by TheDutchCoder** [comment]
Okay I figured out the issue, it's that the component itself does not support proper styling and collapses around its child view.

Not sure if that's by design or not (all other touchables are properly stylable), so I'll open an issue for it.

**Comment by jayasme** [comment]
You must put something into it to make it work, just put a `<View>` and wrap your JSX into it is the first step, the next is making it flex=1

**Comment by TheDutchCoder** [comment]
Yeah it's wildly inconsistent right now, it should be fixed so it behaves like other Touchables.

**Comment by rmacqueen** [comment]
Also ran into this - it's quite frustrating to have to include the additional gratuitous `View`. I opened #18611 as a follow-up since this one was prematurely closed.

**Comment by pintocarlos** [comment]
I have this issue also, using 0.54
I had to add the extra View which is a shame.

**Comment by dazweeja** [comment]
For the record, it's not necessary to add an extra view, you just need to ensure that the props that TouchableWithoutFeedback injects into it's child component are passed down to the View inside your custom component. For example, your custom component might be something like this:

```
<View {...this.props}>
  ... etc
</View>
```

It's explained in https://github.com/facebook/react-native/issues/1352
