### ISSUE TITLE
[IOS] Crash in [RCTImageLoader _loadImageOrDataWithURLRequest]

### ISSUE THREAD

**Issue by sooth-sayer** [facebook/react-native#10274]
Hi!
I have a ListView with a lot of Image whose sources are located remotely. When I quickly scroll down the application fails with EXC_BAD_ACCESS in https://github.com/facebook/react-native/blob/0.34-stable/Libraries/Image/RCTImageLoader.m#L383.

**Comment by sattaman** [comment]
I think I may be hitting the same bug http://pastebin.com/3Zp5E157 

Although I have not recreated myself, I have 50+ crashes due to this _loadImageOrDataWithURLRequest reported on crashlytics.

**Comment by sooth-sayer** [comment]
My stacktrace (http://pastebin.com/7n6h7KL7)

![2016-10-07 14 45 49](https://cloud.githubusercontent.com/assets/5451697/19187482/c7918164-8c9c-11e6-9a27-d3eaee0670fe.png)

**Comment by jmcginty** [comment]
I am getting this same crash while scrolling a page of images too. 
Crashes at the same line number.

**Comment by sjmueller** [comment]
Same crash, although it is quite random. Have yet to figure out reproducable steps.

**Comment by javache** [comment]
Hopefully fixed in https://github.com/facebook/react-native/commit/26be005b0a8349afc7f00d8eb0bfe92be85021af

**Comment by ide** [comment]
Looks like this is still happening, https://github.com/facebook/react-native/issues/10433 is designated as the new issue to Subscribe to.

**Comment by clovs** [comment]
Yeah still this Bad Access..
