### ISSUE TITLE
Multiline TextInput Does Not Respect Line-Height

### ISSUE THREAD

**Issue by geirman** [facebook/react-native#10614]
### Description

Related to #4977

TextInput with `multiline={true}` and line-height set on the value text should respect the line height value, but does not. 

``` javascript
import React from 'react';
import {
  registerComponent,
} from 'react-native-playground';
import {
  StatusBar,
  StyleSheet,
  Text,
  View,
  TextInput,
} from 'react-native';

class App extends React.Component {
  render() {
    const loremText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis lacinia sapien, in bibendum est. "
    return (
      <View style={styles.container}>
        <Text style={styles.lorem}>
          {loremText}
        </Text>
    <TextInput style={[styles.lorem,styles.input]} multiline={true} value={loremText} />
        <StatusBar barStyle="default" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#d3c012',
  },
  lorem: {
    textAlign: 'left',
    color: '#000',
    fontSize: 19,
    marginBottom: 5,
    lineHeight: 50,
  },
  input: {
   marginTop: 50,
   padding: 5,
   height: 150, 
   width: 300,
   borderColor: 'purple', 
   borderWidth: 2,
  }
});
```

This issue can be seen here: https://rnplay.org/apps/TYBoBw
<img width="599" alt="2016-10-28_1356" src="https://cloud.githubusercontent.com/assets/1640318/19823705/fd7c7e7c-9d1e-11e6-9c26-a686fe7a3249.png">
### Additional Information
- React Native version: 0.36
- Platform: both iOS, Android
- Operating System: MacOS

**Comment by leeight** [comment]
![image](https://cloud.githubusercontent.com/assets/104052/19825753/e6248f12-9daf-11e6-8538-3a163af10c32.png)

**Comment by geirman** [comment]
@leeight was that the same code as above, or did you make changes?

**Comment by leeight** [comment]
Nothing change

**Comment by brentvatne** [comment]
React Native Playground is using an older version of React Native at the moment, I believe it's on 0.33. Seems like this is resolved in 0.36?

**Comment by aleclarson** [comment]
@brentvatne `style: { lineHeight }` seems to have no effect on 0.37.0

**Comment by atdrago** [comment]
Just ran into this issue in 0.39.0.

**Comment by aleclarson** [comment]
For iOS, it looks like `RCTTextView` does not use `RCTShadowText`, which is what implements some style attributes (including `lineHeight` and `textShadowColor`).

@brentvatne Do you know if there are plans to use `RCTShadowText` within `RCTTextView`? Or should we use custom solutions involving `UITextView`?

**Comment by aleclarson** [comment]
Fork `react-native` and cherry-pick [this commit](https://github.com/aleclarson/react-native/commit/b756b7bd9c9d49c1261c68b4d17389aacb4a421a).

It provides `props.style` support for the following keys: `lineHeight`, `letterSpacing`, `textShadowOffset`, `textShadowRadius`, and `textShadowColor`.

It moves some `RCTShadowText` logic into the new `RCTTextAttributes` file. It looks like `RCTTextView` already has an `RCTText` internal property, but I could not get it working (via setting `props.children` to a `Text` component).

If anyone's looking for a working solution, this commit should help you.

**Comment by holyxiaoxin** [comment]
@aleclarson why was this broken again? Did they revert this commit? Read that it was fixed in 0.33.

**Comment by dmr07** [comment]
Any updates on this? on 0.46.0 running on iOS. still having issues.

**Comment by SeanChenU** [comment]
For temp solution, I wrap `<Text/>` in `<TextInput/>`.  Make sure the `<TextInput/>` doesn't specify `value` props.

```
<TextInput
  onChangeText={(text) => {this.setState({content: text});}} 
  style={{lineHeight: 28}}>
  <Text>{this.state.text}</Text>
</TextInput>
```

**Comment by archansel** [comment]
Running 0.47.1 still having this issue in iOS, android works just fine

@SeanChenU solution doesnt work for me

**Comment by Vetalyo** [comment]
0.47.1 still same problem

**Comment by Inlesco** [comment]
@SeanChenU hacks like that are so painful to watch, but nevermind... it seems that RN team doesn't see a problem here.

same thing for a non-multiline input not being able to have a border styled through style props and only specifying `multiline` as a workaround works...

**Comment by statelo** [comment]
issue still exist...

**Comment by cporawat** [comment]
+1

**Comment by shergin** [comment]
I fixed this recently.
