### ISSUE TITLE
I18n.forceRTL is forcing rtl layout only on second app launch

### ISSUE THREAD

**Issue by grmmph** [facebook/react-native#11475]
### Description

I have an App in hebrew that should force RTL layout even for LTR devices (curenty our interface is only in hebrew)

Using I18nManager.forceRTL(true) does the trick, but only after the scond app launch by the user.

So now when the akp is in production the user gets the following:
User download app from store -> user open app and get LTR Layout. -> user close app and remove from background -> user open app again and get desired RTL layout.

### Solution

My guess would be that somehow we should run force RTL method before appRegistery, but not sure how to do it.
Alternativle and more desirable solution is to make forceRTL more dymanic, so user can switch layouts direxction without the need to relaunch app.

**Comment by lacker** [comment]
Well you could call `forceRTL` before you call the app registry. Does that work?

Alternatively you could try calling whatever forceRTL calls from native code.

**Comment by bluetec** [comment]
@lacker I call forceRTL method before appRegistery, but in first run everything will be rendered  Left to Right.
Android only

how should I call  forceRTL in native code?

**Comment by eldadcaspi** [comment]
Hi @grmmph, did you get to solve this? I'm having the exact same issue and am trying to avoid changes to the native projects since i'm using Expo. thanks

**Comment by yasicmd** [comment]
Any solution yet? @lacker

**Comment by I-ad** [comment]
if you are not using expo so you can use [react-native-restart](https://github.com/avishayil/react-native-restart),
you can make a condition at the first like if !isRTL then make true and then restart.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by iddan** [comment]
This issue still occurs on RN 0.48

**Comment by papmodern** [comment]
"expo": "^22.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4",

Still occurs

**Comment by miladnit** [comment]
Hi,
exact same  issue

**Comment by MortezaAghili** [comment]
exact same issue

**Comment by MortezaAghili** [comment]
After a week finally i found a logicly way to solve this issue with using  **`Redux`  & `react-native-restart`** plugin. If you are interested you can check it on [Stackoverflow](https://stackoverflow.com/questions/48638652/i18nmanager-forcertl-doesnt-applies-changes-in-first-app-load)

**Comment by ShacharAngel** [comment]
Still occurs

**Comment by sergey-korchagin** [comment]
Had same problem, in android mainApplication:
 @Override
  public void onCreate() {
    super.onCreate();
    I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
    sharedI18nUtilInstance.forceRTL(this,true);
    sharedI18nUtilInstance.allowRTL(this, true);
  }

The problem solved

**Comment by sergey-korchagin** [comment]
Also solved in IOS
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  [[RCTI18nUtil sharedInstance] allowRTL:YES];
  [[RCTI18nUtil sharedInstance] forceRTL:YES];

**Comment by iamsoorena** [comment]
Still occurs on 0.55

**Comment by karimkhamwani** [comment]
any updates?

**Comment by HosamZewain** [comment]
Editing native code is not a solution. It may work for RTL only apps but any app uses tow languages can't force RTL in native code.
The only solution I found is to use  react-native-restart, But It's very bad UX.

**Comment by FakhruddinAbdi** [comment]
Where do you use `react-native-restart` code @HosamZewain ?
Because as you know the problem appear just in the first lunch and in the rest , the app works fine

**Comment by azzozhsn** [comment]
I have two languages application (rtl, ltr). When I switch the language, the layout doesn't update after restart app. I have to click on the language again to flip the UI. This is annoying,
