### ISSUE TITLE
[Android 0.37] AppState.currentState incorrectly returns "active" when app is launched in background

### ISSUE THREAD

**Issue by vikeri** [facebook/react-native#11561]
### Description

When the app is started in the background (Headless JS) from for example a JobScheduler the AppState.currentState is initially "active" even though it should return "background". When called later on it gives "uninitialized" which is not documented.

This probably stems from AppState not taking into account how HeadlessJS is run.

The default value defined [here](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/AppState/AppState.js#L88) is what is causing this issue since [this callback](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/AppState/AppState.js#L105) is not called before one tries to access the `currentState` property.

### Reproduction

1. Fork the example folder of `react-native-background-job` : https://github.com/vikeri/react-native-background-job/tree/master/example
2. Log AppState.currentState in the beginning of the `index.android.js` file.
3. Schedule the job
4. Kill the app
5. Watch the job run and see the output of AppState.currentState

### Solution

A solution could be to deprecate `currentState` and expose the `getCurrentState` method as suggested [here](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/AppState/AppState.js#L90-L93) and [here](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/AppState/AppState.js#L101-L103).

### Additional Information

* React Native version: 0.37
* Platform: Android
* Operating System: MacOS

**Comment by tnortman** [comment]
Ditto, happens on 0.39.2 as well.

**Comment by JonoH** [comment]
Same issue my side.

**Comment by JulioOrellana** [comment]
So, by React Native side there is not way to bypass this? The only solution is to add some native code directly to Android code. So bad. AppState works correctly on iOS.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by olegwn** [comment]
can't believe this is still an issue :( 

RN 0.53.3
Android 8

**Comment by stevenpal** [comment]
Noticed that this is still an issue as well on RN 0.55.4.  The `AppState.currentState` always seems to return `active` no matter what state the app is in on Android.  Although `AppState.currentState` isn't updated, the event listeners do seem to be working.  So a workaround is to track the state yourself as they do in the example code using an event listener: https://facebook.github.io/react-native/docs/appstate.html.  Seems to be working so far for me.
