### ISSUE TITLE
react-native run-android --variant=release does not work currently.

### ISSUE THREAD

**Issue by the-simian** [facebook/react-native#11586]
### Description
cannot test release variant on android.

### Reproduction

in console at root of project run

`react-native run-android --variant=release`

JS server already running.
Running /usr/local/opt/android-sdk/platform-tools/adb -s 192.168.56.101:5555 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installReleaseDebug)...
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installReleaseDebug' not found in root project 'mysupercoolapp'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

### Solution
I can get it to work doing `cd android && ./gradlew installRelease`. Maybe the react-native command needs to  be remapped to a different gradle command? 

### Additional Information
Someone else got this 7 hours ago on SO as well:
[http://stackoverflow.com/questions/41263330/error-running-react-native-run-android-variant-release-task-installreleasede](http://stackoverflow.com/questions/41263330/error-running-react-native-run-android-variant-release-task-installreleasede)

* React Native version:  0.39.x
* Platform: Android
* Operating System: MacOS

**Comment by Ehesp** [comment]
Yeah so this was a problem I had. Turns out there was a PR created which changed this but the documentation was also not updated. I'll try and find the PRs for the change and docs (which hasn't merged).

For now run:

```
react-native run-android --configuration=release
```

**Comment by the-simian** [comment]
Thanks I appreciate it. As long as there's something to run that works, i'm perfectly happy

**Comment by arthur31416** [comment]
This is now fixed in v0.41.0-rc.0 and `react-native run-android --variant=release` works as expected.

**Comment by flyingbuddha** [comment]
FYI @arthur31416, this appears to have broken again with v0.41.0-rc.2. I used `react-native-git-upgrade v0.41.0-rc.0` to get back to a working state.

**Comment by jpaas** [comment]
This problem has been around since 0.41 and still exists on 0.43.0-rc.4. Should this PR be reopened, or should we create a new one? This issue has prevented me from ever being able to create an android release build for my project.

**Comment by trubin** [comment]
Still having this issue in react-native version 0.43.0.

**Comment by trubin** [comment]
So it seems to be because I forgot to include "signingConfig signingConfigs.release" in the "release" property of the "buildTypes" property of the app\build.gradle.

**Comment by Snorlock** [comment]
Are there any way to test release builds on your simulator now? Im experiencing the same problems as above, running 0.43.0-rc.4

**Comment by jpaas** [comment]
@trubin seems to be right. As soon as I configured my Android build for signing the release build, this problem went away. Its basically just a really bad error message.

**Comment by johndanek** [comment]
It would be nice if there were a way to install an APK which didn't require a signing config. I am just working with a sandbox app, and I wanted to see what the real performance would be like (since __DEV__ is very slow).

**Comment by Ethan0007** [comment]
Hey Guys, can you please try my fix below:

react-native bundle --platform android --dev false --entry-file index.android.js  --bundle-output android/app/src/main/assets/index.android.bundle  --assets-dest android/app/src/main/res/

**Comment by scarlac** [comment]
@Ethan0007 It makes no difference for me. The 'bundle' command runs fine but the run-android still fails.

**Comment by Ethan0007** [comment]
@scarlac  sir, can you please paste the said error.

**Comment by scarlac** [comment]
@Ethan0007 It was the exact error reported in this issue. For future reference, I solved it by following the [signing configuration guide](http://facebook.github.io/react-native/docs/signed-apk-android.html). The task `installRelease` won't be available unless the signing is set up properly. I followed the guide exactly, and then it worked.

**Comment by Ethan0007** [comment]
@scarlac  Good to hear that.

**Comment by dorthwein** [comment]
See @scarlac response - helpful link on how to sign using configure in Android Studio 
https://developer.android.com/studio/publish/app-signing.html

Scroll to the **Configure the build process to automatically sign your APK** section

**Comment by eduplus** [comment]
@Ethan0007 Your bundle command did the trick for me. Otherwise the build worked and it installs on the phone, but would crash complaining:

UncaughtException: java.lang.RuntimeException: Error calling AppRegistry.runApplication
..Could not get BatchedBridge, make sure your bundle is packaged correctly

Now I am just confused why that is and why that is not done automatically? Do I need to run that everytime?

**Comment by Ethan0007** [comment]
Sir, please try to cd android then try to & ./gradlew clean. then & ./gradlew assembleRelease

**Comment by raldred** [comment]
RN 0.45
error: unknown option `--configuration'

**Comment by rrichardson** [comment]
Is there a way to just build and run in release mode with --dev=false without having to go through the signing step?  I just want to do performance testing without creating a release-able APK.

**Comment by bobosdaniel** [comment]
try this.
https://www.codelink.io/2016/10/25/multiple-android-build-types-react-native.html

**Comment by pstanton** [comment]
I had this error because i hadn't included the keystore passwords! as someone mentioned earlier, just a horribly misleading message! should be re-opened.

**Comment by lcd11001** [comment]
I run react-native run-android --variant=release but the apk can not run on devices.
It has stopped at lauch.
I configed signed apk as facebook tutorial.
Pls help me, thank you so much

**Comment by lcd11001** [comment]
@Ethan0007 Hello, here is my log on Samsung Android 4.4.2


C:\Users\dan.luongcong>adb logcat
--------- beginning of /dev/log/main
I/AudioService(  908): getStreamVolume 3 index 140
--------- beginning of /dev/log/system
V/AlarmManager(  908): waitForAlarm result :4
V/AlarmManager(  908): trigger ELAPSED_REALTIME_WAKEUP or RTC_WAKEUP
D/BatteryService(  908): level:27, scale:100, status:2, health:2, present:true, voltage: 3917, temperature: 291, technology: Li-ion, AC powered:false, USB powered:true, Wireless powered:false, icon:17303678, invalid charger:0, online:4, current avg:450, charge type:1, power sharing:false
D/BatteryService(  908): Sending ACTION_BATTERY_CHANGED.
D/UiModeManager(  908): mCoverManager.getCoverState() : true
D/KeyguardUpdateMonitor( 1197): received broadcast android.intent.action.BATTERY_CHANGED
D/KeyguardUpdateMonitor( 1197): handleBatteryUpdate
D/CoverBroadcastManager( 1653): onReceive : action = android.intent.action.BATTERY_CHANGED
D/ClientService( 1809): Battery State Change,  status: 2
D/ClientService( 1809): Battery State Change,  Plugged: 2
D/ClientService( 1809): Battery State Change,  level: 27
D/ClientService( 1809): Battery State Change,  scale: 100
D/STATUSBAR-PhoneStatusBar( 1197):  mBrightnessEnablebySettings = true mBrightnessEnablebyBattery = true mBrightnessEnablebyDisableFlag = true mPmsBrightnessEnablebySettings = true
D/STATUSBAR-IconMerger( 1197): checkOverflow(648), More:false, Req:false Child:5
D/BatteryMeterView( 1197): ACTION_BATTERY_CHANGED : level:27 status:2 health:2
I/ThermalEngine(  293): Mitigation:CPU[3]:2265600 Khz
I/ThermalEngine(  293): Mitigation:CPU[2]:2265600 Khz
I/AudioService(  908): getStreamVolume 3 index 140
I/dalvikvm(21197): Total arena pages for JIT: 11
I/dalvikvm(21197): Total arena pages for JIT: 12
I/dalvikvm(21197): Total arena pages for JIT: 13
I/dalvikvm(21197): Total arena pages for JIT: 14
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/Finsky  (21197): [1174] com.google.android.finsky.k.c.a(23): Completed 0 account content syncs with 0 successful.
I/Finsky  (21197): [1] com.google.android.finsky.services.e.a(5): Installation state replication succeeded.
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
E/SMD     (  262): DCD ON
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
D/InputReader(  908): Input event: value=1
I/InputReader(  908): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.727 ] when=7359934525000
I/InputDispatcher(  908): Delivering touch to: action: 0x4, toolType: 1
I/InputDispatcher(  908): Delivering touch to: action: 0x4, toolType: 1
I/InputDispatcher(  908): Delivering touch to: action: 0x0, toolType: 1
I/InputDispatcher(  908): Delivering touch to: action: 0x0, toolType: 1
D/AutoHideHelper( 2164): ###check Single invalid
I/AudioService(  908): getStreamVolume 3 index 140
D/InputReader(  908): Input event: value=0
I/InputReader(  908): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=7360059876000
I/InputDispatcher(  908): Delivering touch to: action: 0x1, toolType: 1
I/InputDispatcher(  908): Delivering touch to: action: 0x1, toolType: 1
I/AudioPolicyManagerBase(  271): getSituationVolume: isBTConnected:0 isHeadConnected:0
V/AudioPolicyManagerBase(  271): getParamFromPolicy  deviceInt = 0, situationInt = 1, situationVolume = 0.500000
V/AudioPolicyManagerBase(  271): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
V/AudioPolicyManagerBase(  271): getOutputsForDevice device 0002 -> 0002
V/AudioPolicyManagerBase(  271): getOutput() returns output 2
V/AudioPolicyManagerBase(  271): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
V/AudioPolicyManagerBase(  271): getOutputsForDevice device 0002 -> 0002
V/AudioPolicyManagerBase(  271): getOutput() returns output 2
V/AudioPolicyManagerBase(  271): getOutput() device 2, stream 1, samplingRate 48000, format 1, channelMask 1, flags 4
V/AudioPolicyManagerBase(  271): getOutputsForDevice device 0002 -> 0002
V/AudioPolicyManagerBase(  271): getOutput() returns output 2
V/AudioPolicyManagerBase(  271): startOutput() output 2, stream 1, session 108
V/AudioPolicyManagerBase(  271): changeRefCount() stream 1, count 1
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
V/AudioPolicyManagerBase(  271): getNewDevice() selected device 2
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
V/AudioPolicyManagerBase(  271): setOutputDevice() output 2 device 0002 force 0 delayMs 0
V/AudioPolicyManagerBase(  271): setOutputDevice() prevDevice (0002)
V/AudioPolicyManagerBase(  271): setOutputDevice() setting same device 0002 or null device for output 2
V/audio_hw_primary(  271): start_output_stream: enter: usecase(0: deep-buffer-playback) devices(0x2)
V/audio_hw_primary(  271): select_devices: ENTER
V/audio_hw_primary(  271): select_devices: usecase(normal)
V/audio_hw_primary(  271): select_devices: usecase(PCM_PLAYBACK)
V/msm8974_platform(  271): platform_get_output_snd_device: enter: output devices(0x2)
V/msm8974_platform(  271): get_OUTPUT_snd_device: for Normal Playback
V/msm8974_platform(  271): platform_get_output_snd_device: exit: snd_device(speaker)
D/audio_hw_primary(  271): select_devices: out_snd_device(2: speaker)
D/audio_hw_primary(  271): select_devices: in_snd_device(0: dummy)
V/audio_hw_primary(  271): enable_snd_device: snd_device(2: speaker)
D/ACDB-LOADER(  271): ACDB -> send_audio_cal, acdb_id = 15, path =  0
D/ACDB-LOADER(  271): ACDB -> send_adm_topology
D/ACDB-LOADER(  271): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(  271): ACDB -> send_audtable
D/ACDB-LOADER(  271): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/        (  271): ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
D/ACDB-LOADER(  271): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(  271): ACDB -> send_audvoltable
D/ACDB-LOADER(  271): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
D/        (  271): ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
D/ACDB-LOADER(  271): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(  271): ACDB -> send_afe_cal
D/ACDB-LOADER(  271): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
D/        (  271): ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
D/ACDB-LOADER(  271): ACDB -> AUDIO_SET_AFE_CAL
V/audio_hw_primary(  271): enable_snd_device: snd_device(2: speaker)
D/audio_route(  271): ++++ audio_route_update_mixer ==============
D/audio_route(  271): Setting mixer control: SPK DRV Volume, value: 8
V/AudioPolicyManagerBase(  271): releaseOutput() 2
D/audio_route(  271): Setting mixer control: RX7 Digital Volume, value: 81
D/audio_route(  271): Setting mixer control: COMP0 Switch, value: 1
D/audio_route(  271): Setting mixer control: RX7 MIX1 INP1, value: 5
D/audio_route(  271): Setting mixer control: DAC1 Switch, value: 1
D/audio_route(  271): ------ audio_route_update_mixer ==============
V/audio_hw_primary(  271): enable_audio_route: enter: usecase(0)
V/audio_hw_primary(  271): enable_audio_route: apply mixer path: deep-buffer-playback
D/audio_route(  271): ++++ audio_route_update_mixer ==============
D/audio_route(  271): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
D/audio_route(  271): ------ audio_route_update_mixer ==============
V/audio_hw_primary(  271): enable_audio_route: exit
V/audio_hw_primary(  271): start_output_stream: Opening PCM device card_id(0) device_id(0)
V/audio_hw_primary(  271): start_output_stream: exit
I/ThermalEngine(  293): Mitigation:CPU[3]:2265600 Khz
I/ThermalEngine(  293): Mitigation:CPU[2]:2265600 Khz
D/EnterpriseDeviceManager(  908): ContainerId: 0
I/ThermalEngine(  293): Mitigation:CPU[1]:2265600 Khz
V/ApplicationPolicy(  908): isApplicationStateBlocked userId 0 pkgname com.newyorktimes
I/SurfaceFlinger(  268): id=126 createSurf (16x16),-1 flag=20004, EimLayer
I/SurfaceFlinger(  268): id=127 createSurf (16x16),-1 flag=20004, EimLayer
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/ActivityManager(  908): mDVFSHelper.acquire()
D/PhoneStatusBar( 1197): setTransGradationMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false
D/StatusBarManagerService(  908): tr p:908,o:f
I/SurfaceFlinger(  268): id=128 createSurf (1x1),1 flag=404, oewyorktime
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
V/SmartFaceService - 3rd party pause(  908): onReceive [android.intent.action.ACTIVITY_STATE/com.sec.android.app.launcher/pause]
D/Launcher.HomeView( 1432): onPause
V/TaskCloserActivity(21868): TaskCloserActivity onReceive() - com.sec.android.intent.action.HOME_PAUSE
D/PointerIcon(  908): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon(  908): setMouseCustomIcon IconType is same.101
D/PointerIcon(  908): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon(  908): setHoveringSpenCustomIcon IconType is same.1
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SELinux (21946): Function: selinux_android_load_priority [0], There is no sepolicy file.
I/SELinux (21946):
I/SELinux (21946): Function: selinux_android_load_priority [1], There is no sepolicy version file.
I/SELinux (21946):
I/SELinux (21946): Function: selinux_android_load_priority , priority version is VE=SEPF_SC-02F_4.4.2_0016
I/SELinux (21946):
I/SELinux (21946):
**E/dalvikvm(21946): >>>>> Normal User
E/dalvikvm(21946): >>>>> com.newyorktimes [ userId:0 | appId:10255 ]**
D/ActivityThread(21946): Unable to add TimaKesytore provider
**W/System.err(21946): java.lang.ClassNotFoundException: com.sec.tima.TimaKeyStoreProvider**
W/System.err(21946):    at java.lang.Class.classForName(Native Method)
W/System.err(21946):    at java.lang.Class.forName(Class.java:251)
W/System.err(21946):    at java.lang.Class.forName(Class.java:216)
W/System.err(21946):    at android.app.ActivityThread.main(ActivityThread.java:5562)
W/System.err(21946):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(21946):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(21946):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
W/System.err(21946):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
W/System.err(21946):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(21946): Caused by: java.lang.NoClassDefFoundError: com/sec/tima/TimaKeyStoreProvider
I/AudioService(  908): getStreamVolume 3 index 140
W/System.err(21946):    ... 9 more
**W/System.err(21946): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sec.tima.TimaKeyStoreProvider" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]**
W/System.err(21946):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
W/System.err(21946):    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
W/System.err(21946):    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
W/System.err(21946):    ... 9 more
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, mbResultFaceDectection: false
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, Rotation: -1
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, mbResultFaceDectection: false
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, Rotation: -1
D/Launcher.HomeView( 1432): onStop
V/WindowManager(  908): rotationForOrientationLw(orient=-1, last=0); user=0 USER_ROTATION_LOCKED sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false mAccelerometerDefault=false gripRotationLock=false
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/EnterpriseDeviceManager(  908): ContainerId: 0
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/STATUSBAR-StatusBarManagerService(  908): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
V/SmartFaceService - 3rd party pause(  908): onReceive [android.intent.action.ACTIVITY_STATE/com.newyorktimes/create]
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
V/fb-UnpackingSoSource(21946): locked dso store /data/data/com.newyorktimes/lib-main
I/fb-UnpackingSoSource(21946): dso store is up-to-date: /data/data/com.newyorktimes/lib-main
V/fb-UnpackingSoSource(21946): releasing dso store lock for /data/data/com.newyorktimes/lib-main
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/Launcher( 1432): onTrimMemory. Level: 20
I/dalvikvm(21946): Could not find method android.provider.Settings.canDrawOverlays, referenced from method com.facebook.react.ReactActivityDelegate.onActivityResult
W/dalvikvm(21946): VFY: unable to resolve static method 684: Landroid/provider/Settings;.canDrawOverlays (Landroid/content/Context;)Z
D/dalvikvm(21946): VFY: replacing opcode 0x71 at 0x0028
I/dalvikvm(21946): Could not find method android.provider.Settings.canDrawOverlays, referenced from method com.facebook.react.ReactActivityDelegate.onCreate
W/dalvikvm(21946): VFY: unable to resolve static method 684: Landroid/provider/Settings;.canDrawOverlays (Landroid/content/Context;)Z
D/dalvikvm(21946): VFY: replacing opcode 0x71 at 0x0015
I/dalvikvm(21946): Could not find method android.app.Activity.requestPermissions, referenced from method com.facebook.react.ReactActivityDelegate.requestPermissions
**W/dalvikvm(21946): VFY: unable to resolve virtual method 26: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0006
I/PersonaManager(21946): getPersonaService() name persona_policy**
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/ReactNative(21946): ReactInstanceManager.ctor()
D/ReactNative(21946): ReactInstanceManager.createReactContextInBackground()
D/ReactNative(21946): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative(21946): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative(21946): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative(21946): ReactInstanceManager.runCreateReactContextOnNewThread()
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/dalvikvm(21946): Trying to load lib /data/app-lib/com.newyorktimes-22/libreactnativejni.so 0x42a7cdd0
D/StatusBarManagerService(  908): tr p:21946,o:f
D/StatusBarManagerService(  908): semi p:21946,o:f
D/dalvikvm(21946): Added shared lib /data/app-lib/com.newyorktimes-22/libreactnativejni.so 0x42a7cdd0
D/dalvikvm(21946): DexOpt: couldn't find field Landroid/view/ViewRootImpl;.mFlipControllerFallbackKeys
W/dalvikvm(21946): VFY: unable to resolve instance field 15318
D/dalvikvm(21946): VFY: replacing opcode 0x55 at 0x000e
D/dalvikvm(21946): DexOpt: couldn't find field Landroid/view/ViewRootImpl;.mFlipControllerFallbackKeys
D/PhoneStatusBar( 1197): setTransGradationMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false
W/dalvikvm(21946): VFY: unable to resolve instance field 15318
D/dalvikvm(21946): VFY: replacing opcode 0x55 at 0x0048
D/PhoneStatusBar( 1197): setSemiTransparentMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false
D/dalvikvm(21946): Trying to load lib /data/app-lib/com.newyorktimes-22/libfb.so 0x42a7cdd0
D/dalvikvm(21946): Added shared lib /data/app-lib/com.newyorktimes-22/libfb.so 0x42a7cdd0
D/dalvikvm(21946): Trying to load lib /data/app-lib/com.newyorktimes-22/libfb.so 0x42a7cdd0
D/dalvikvm(21946): Shared lib '/data/app-lib/com.newyorktimes-22/libfb.so' already loaded in same CL 0x42a7cdd0
I/dalvikvm(21946): threadid=10: recursive native library load attempt (/data/app-lib/com.newyorktimes-22/libfb.so)
D/ReactNative(21946): ReactInstanceManager.createReactContext()
I/dalvikvm(21946): Could not find method android.view.View.setElevation, referenced from method com.facebook.react.uimanager.BaseViewManager.setElevation
W/dalvikvm(21946): VFY: unable to resolve virtual method 5959: Landroid/view/View;.setElevation (F)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x000a
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
I/SurfaceFlinger(  268): id=129 createSurf (1080x1920),1 flag=404, NainActivit
I/SpenGestureManager(  908): setFocusWindow21040
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
**I/dalvikvm(21946): Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method com.facebook.react.views.webview.ReactWebViewManager.setMixedContentMode**
W/dalvikvm(21946): VFY: unable to resolve virtual method 6219: Landroid/webkit/WebSettings;.setMixedContentMode (I)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0015
I/dalvikvm(21946): Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method com.facebook.react.views.webview.ReactWebViewManager.setMixedContentMode
W/dalvikvm(21946): VFY: unable to resolve virtual method 6219: Landroid/webkit/WebSettings;.setMixedContentMode (I)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0026
I/dalvikvm(21946): Could not find method android.webkit.WebSettings.setMixedContentMode, referenced from method com.facebook.react.views.webview.ReactWebViewManager.setMixedContentMode
W/dalvikvm(21946): VFY: unable to resolve virtual method 6219: Landroid/webkit/WebSettings;.setMixedContentMode (I)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0037
I/dalvikvm(21946): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method com.facebook.react.views.webview.ReactWebViewManager.setThirdPartyCookiesEnabled
W/dalvikvm(21946): VFY: unable to resolve virtual method 6202: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x000a
D/PointerIcon(  908): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon(  908): setMouseCustomIcon IconType is same.101
D/PointerIcon(  908): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon(  908): setHoveringSpenCustomIcon IconType is same.1
I/Adreno-EGL(21946): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL(21946): OpenGL ES Shader Compiler Version: E031.24.00.08+13
I/Adreno-EGL(21946): Build Date: 03/28/14 Fri
I/Adreno-EGL(21946): Local Branch: 0328_AU200_patches
I/Adreno-EGL(21946): Remote Branch:
I/Adreno-EGL(21946): Local Patches:
I/Adreno-EGL(21946): Reconstruct Branch:
**I/dalvikvm(21946): Could not find method com.facebook.react.views.view.ReactViewGroup.drawableHotspotChanged, referenced from method com.facebook.react.views.view.ReactViewManager.receiveCommand**
W/dalvikvm(21946): VFY: unable to resolve virtual method 15362: Lcom/facebook/react/views/view/ReactViewGroup;.drawableHotspotChanged (FF)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x002d
I/dalvikvm(21946): Could not find method com.facebook.react.views.view.ReactViewGroup.setForeground, referenced from method com.facebook.react.views.view.ReactViewManager.setNativeForeground
W/dalvikvm(21946): VFY: unable to resolve virtual method 15408: Lcom/facebook/react/views/view/ReactViewGroup;.setForeground (Landroid/graphics/drawable/Drawable;)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0003
**W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager**
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
I/AudioService(  908): getStreamVolume 3 index 140
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
D/OpenGLRenderer(21946): Enabling debug mode 0
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/ContextImpl(  908): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1491 com.android.server.InputMethodManagerService$4.run:2827 java.lang.Thread.run:841 <bottom of call stack> <bottom of call stack>
D/PackageManager(  908): [MSG] MCS_UNBIND
I/PackageManager(  908): calling disconnectService()
D/PackageManager(  908): Trying to unbind to DefaultContainerService
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
I/ActivityManager(  908): Killing 21280:com.sec.android.provider.badge/u0a108 (adj 15): empty #31
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
I/SurfaceFlinger(  268): id=125 Removed Mauncher (14/20)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  268): id=125 Removed Mauncher (-2/20)
W/ActivityManager(  908): mDVFSHelper.release()
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater(21946): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
I/AudioService(  908): getStreamVolume 3 index 140
E/cutils  (  247): Failed to mkdirat(/storage/extSdCard/Android): Read-only file system
W/ContextImpl(21946): Failed to ensure directory: /storage/extSdCard/Android/data/com.newyorktimes/cache
W/Vold    (  247): Returning OperationFailed - no handler for errno 30
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  268): id=128 Removed oewyorktime (16/19)
I/SurfaceFlinger(  268): id=128 Removed oewyorktime (-2/19)
I/dalvikvm(21946): Could not find method android.webkit.CookieManager.setCookie, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler.addCookieAsync
W/dalvikvm(21946): VFY: unable to resolve virtual method 6204: Landroid/webkit/CookieManager;.setCookie (Ljava/lang/String;Ljava/lang/String;Landroid/webkit/ValueCallback;)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0005
I/dalvikvm(21946): Could not find method android.webkit.CookieManager.removeAllCookies, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler.clearCookiesAsync
W/dalvikvm(21946): VFY: unable to resolve virtual method 6200: Landroid/webkit/CookieManager;.removeAllCookies (Landroid/webkit/ValueCallback;)V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0009
I/dalvikvm(21946): Could not find method android.webkit.CookieManager.flush, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler$CookieSaver.flush
W/dalvikvm(21946): VFY: unable to resolve virtual method 6196: Landroid/webkit/CookieManager;.flush ()V
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm(21946): Could not find method android.content.Context.checkSelfPermission, referenced from method com.facebook.react.modules.permissions.PermissionsModule.checkPermission
W/dalvikvm(21946): VFY: unable to resolve virtual method 104: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0028
I/dalvikvm(21946): Could not find method android.content.Context.checkSelfPermission, referenced from method com.facebook.react.modules.permissions.PermissionsModule.requestMultiplePermissions
W/dalvikvm(21946): VFY: unable to resolve virtual method 104: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x003f
I/dalvikvm(21946): Could not find method android.content.Context.checkSelfPermission, referenced from method com.facebook.react.modules.permissions.PermissionsModule.requestPermission
W/dalvikvm(21946): VFY: unable to resolve virtual method 104: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0028
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/ReactNative(21946): Initializing React Xplat Bridge.
D/ReactNative(21946): Initializing React Xplat Bridge before initializeBridge
D/ReactNative(21946): Initializing React Xplat Bridge after initializeBridge
D/ReactNative(21946): CatalystInstanceImpl.runJSBundle()
D/ReactNative(21946): ReactInstanceManager.setupReactContext()
D/ReactNative(21946): CatalystInstanceImpl.initialize()
D/ReactNative(21946): ReactInstanceManager.attachRootViewToInstance()
D/dalvikvm(21946): Trying to load lib /data/app-lib/com.newyorktimes-22/libyoga.so 0x42a7cdd0
D/dalvikvm(21946): Added shared lib /data/app-lib/com.newyorktimes-22/libyoga.so 0x42a7cdd0
I/dalvikvm(21946): Could not find method com.facebook.drawee.view.DraweeView.getImageTintList, referenced from method com.facebook.drawee.view.DraweeView.init
W/dalvikvm(21946): VFY: unable to resolve virtual method 8088: Lcom/facebook/drawee/view/DraweeView;.getImageTintList ()Landroid/content/res/ColorStateList;
D/dalvikvm(21946): VFY: replacing opcode 0x6e at 0x0015
I/AudioService(  908): getStreamVolume 3 index 140
E/SMD     (  262): DCD ON
I/AudioService(  908): getStreamVolume 3 index 140
E/ReactNativeJS(21946): undefined is not an object (evaluating 's.View.propTypes.style')
E/ReactNativeJS(21946): Module AppRegistry is not a registered callable module (calling runApplication)
W/dalvikvm(21946): threadid=14: thread exiting with uncaught exception (group=0x4180eda0)
E/AndroidRuntime(21946): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime(21946): Process: com.newyorktimes, PID: 21946
E/AndroidRuntime(21946): com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 's.View.propTypes.style'), stack:
E/AndroidRuntime(21946): <unknown>@303:1064
E/AndroidRuntime(21946): t@2:633
E/AndroidRuntime(21946): <unknown>@2:224
E/AndroidRuntime(21946): e@2:231
E/AndroidRuntime(21946): <unknown>@299:282
E/AndroidRuntime(21946): t@2:633
E/AndroidRuntime(21946): <unknown>@2:224
E/AndroidRuntime(21946): e@2:231
E/AndroidRuntime(21946): <unknown>@297:234
E/AndroidRuntime(21946): t@2:633
E/AndroidRuntime(21946): <unknown>@2:224
E/AndroidRuntime(21946): e@2:231
E/AndroidRuntime(21946): <unknown>@296:135
E/AndroidRuntime(21946): t@2:633
E/AndroidRuntime(21946): <unknown>@2:224
E/AndroidRuntime(21946): e@2:231
E/AndroidRuntime(21946): <unknown>@12:38
E/AndroidRuntime(21946): t@2:633
E/AndroidRuntime(21946): <unknown>@2:154
E/AndroidRuntime(21946): e@2:231
E/AndroidRuntime(21946): global code@306:9
E/AndroidRuntime(21946):
**E/AndroidRuntime(21946):        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)**
E/AndroidRuntime(21946):        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
E/AndroidRuntime(21946):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(21946):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(21946):        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
E/AndroidRuntime(21946):        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
E/AndroidRuntime(21946):        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime(21946):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(21946):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(21946):        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(21946):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(21946):        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
E/AndroidRuntime(21946):        at java.lang.Thread.run(Thread.java:841)
W/Settings(  908): Setting dropbox_age_seconds has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
W/ActivityManager(  908):   Force finishing activity com.newyorktimes/.MainActivity
D/CrashAnrDetector(  908): processName: com.newyorktimes
D/CrashAnrDetector(  908): broadcastEvent : com.newyorktimes data_app_crash
I/SecureStorage( 3056): [INFO]: SPID(0x00000000)Checking if this device supports Secure Storage
I/SecureStorage( 3056): [INFO]: SPID(0x00000000)This device does not support Secure Storage
V/SmartFaceService - 3rd party pause(  908): onReceive [android.intent.action.ACTIVITY_STATE/com.newyorktimes/pause]
W/ContextImpl(  908): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1505 com.android.server.analytics.data.collection.application.CrashAnrDetector.broadcastEvent:296 com.android.server.analytics.data.collection.application.CrashAnrDetector.processDropBoxEntry:254 com.android.server.analytics.data.collection.application.CrashAnrDetector.access$100:60 com.android.server.analytics.data.collection.application.CrashAnrDetector$1.onReceive:102
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, mbResultFaceDectection: false
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, Rotation: -1
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, mbResultFaceDectection: false
V/WindowOrientationListener(  908): mSContextAutoRotationListener.getProposedRotation, Rotation: -1
I/dumpstate(21974): begin
W/ActivityManager(  908): mDVFSHelper.acquire()
V/WindowManager(  908): rotationForOrientationLw(orient=2, last=0); user=0 USER_ROTATION_LOCKED sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false mAccelerometerDefault=false gripRotationLock=false
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
V/AudioPolicyManagerBase(  271): stopOutput() output 2, stream 1, session 108
V/AudioPolicyManagerBase(  271): changeRefCount() stream 1, count 0
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
V/AudioPolicyManagerBase(  271): getNewDevice() selected device 0
V/AudioPolicyManagerBase(  271): setOutputDevice() output 2 device 0000 force 0 delayMs 160
V/AudioPolicyManagerBase(  271): setOutputDevice() prevDevice (0002)
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
V/AudioPolicyManagerBase(  271): setOutputDevice() setting same device 0000 or null device for output 2
I/SpenGestureManager(  908): setFocusWindow0
D/EnterpriseDeviceManager(  908): ContainerId: 0
D/STATUSBAR-StatusBarManagerService(  908): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/PointerIcon(  908): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon(  908): setMouseCustomIcon IconType is same.101
D/PointerIcon(  908): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon(  908): setHoveringSpenCustomIcon IconType is same.1
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/Launcher( 1432): onRestart, Launcher: 1118601256
D/Launcher( 1432): onStart, Launcher: 1118601256
D/Launcher.HomeView( 1432): onStart
D/Launcher( 1432): onResume, Launcher: 1118601256
D/Launcher.HomeView( 1432): onResume
D/PhoneStatusBar( 1197): setSemiTransparentMode=false, mTransparentMode=false, mSemiTransparentMode=false, mMultiWindowMode=false
D/StatusBarManagerService(  908): semi p:1432,o:f
V/SmartFaceService - 3rd party pause(  908): onReceive [android.intent.action.ACTIVITY_STATE/com.sec.android.app.launcher/resume]
D/MenuAppsGridFragment( 1432): onResume
I/SurfaceFlinger(  268): id=130 createSurf (1x1),1 flag=4, oewyorktime
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/GalleryCacheReady(19806): Receive : home resume
D/Mms/UIEventReceiver(21399): ui event
I/AudioService(  908): getStreamVolume 3 index 140
V/TaskCloserActivity(21868): TaskCloserActivity onReceive() - com.sec.android.intent.action.HOME_RESUME
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  268): id=131 createSurf (1080x1920),1 flag=4, Mauncher
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/EnterpriseDeviceManager(  908): ContainerId: 0
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/STATUSBAR-StatusBarManagerService(  908): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/AudioService(  908): getStreamVolume 3 index 140
E/android.os.Debug(  908): !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/AudioService(  908): getStreamVolume 3 index 140
W/ActivityManager(  908): mDVFSHelper.release()
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  268): id=129 Removed NainActivit (16/20)
I/SurfaceFlinger(  268): id=129 Removed NainActivit (-2/20)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/ReactNative(21946): ReactInstanceManager.detachViewFromInstance()
I/ActivityManager(  908): Killing 21332:com.google.android.partnersetup/u0a21 (adj 15): empty #31
E/ReactNativeJS(21946): Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  268): id=127 Removed EimLayer (11/19)
I/SurfaceFlinger(  268): id=127 Removed EimLayer (-2/19)
I/SurfaceFlinger(  268): id=126 Removed EimLayer (10/18)
I/SurfaceFlinger(  268): id=126 Removed EimLayer (-2/18)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
I/ThermalEngine(  293): Mitigation:CPU[3]:2265600 Khz
I/ThermalEngine(  293): Mitigation:CPU[2]:2265600 Khz
I/ThermalEngine(  293): Mitigation:CPU[1]:2265600 Khz
I/AudioService(  908): getStreamVolume 3 index 140
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140
D/InputReader(  908): Input event: value=1
I/InputReader(  908): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.728 ] when=7363264575000
I/InputDispatcher(  908): Delivering touch to: action: 0x4, toolType: 1
I/InputDispatcher(  908): Delivering touch to: action: 0x0, toolType: 1
D/InputReader(  908): Input event: value=0
I/InputReader(  908): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=7363307462000
I/InputDispatcher(  908): Delivering touch to: action: 0x1, toolType: 1
I/AudioPolicyManagerBase(  271): getSituationVolume: isBTConnected:0 isHeadConnected:0
V/AudioPolicyManagerBase(  271): getParamFromPolicy  deviceInt = 0, situationInt = 1, situationVolume = 0.500000
I/Process (21946): Sending signal. PID: 21946 SIG: 9
V/AudioPolicyManagerBase(  271): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
V/AudioPolicyManagerBase(  271): getOutputsForDevice device 0002 -> 0002
V/AudioPolicyManagerBase(  271): getOutput() returns output 2
I/SpenGestureManager(  908): setFocusWindow21035
V/AudioPolicyManagerBase(  271): getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
V/AudioPolicyManagerBase(  271): getOutputsForDevice device 0002 -> 0002
V/AudioPolicyManagerBase(  271): getOutput() returns output 2
V/AudioPolicyManagerBase(  271): getOutput() device 2, stream 1, samplingRate 48000, format 1, channelMask 1, flags 4
V/AudioPolicyManagerBase(  271): getOutputsForDevice device 0002 -> 0002
V/AudioPolicyManagerBase(  271): getOutput() returns output 2
D/EnterpriseDeviceManager(  908): ContainerId: 0
V/AudioPolicyManagerBase(  271): startOutput() output 2, stream 1, session 109
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
V/AudioPolicyManagerBase(  271): changeRefCount() stream 1, count 1
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
V/AudioPolicyManagerBase(  271): getNewDevice() selected device 2
W/AudioPolicyManagerBase(  271): stream type [13], return media strategy
V/AudioPolicyManagerBase(  271): setOutputDevice() output 2 device 0002 force 0 delayMs 0
V/AudioPolicyManagerBase(  271): setOutputDevice() prevDevice (0002)
V/AudioPolicyManagerBase(  271): setOutputDevice() setting same device 0002 or null device for output 2
V/AudioPolicyManagerBase(  271): releaseOutput() 2
D/STATUSBAR-StatusBarManagerService(  908): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/PointerIcon(  908): setMouseIconStyle1 pointerType: 1001iconType:101 flag:0
D/PointerIcon(  908): setMouseCustomIcon IconType is same.101
E/ViewRootImpl(  908): sendUserActionEvent() mView == null
D/PointerIcon(  908): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon(  908): setHoveringSpenCustomIcon IconType is same.1
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
W/ContextImpl(  908): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1491 com.android.server.InputMethodManagerService$4.run:2827 java.lang.Thread.run:841 <bottom of call stack> <bottom of call stack>
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/AudioService(  908): getStreamVolume 3 index 140
I/ActivityManager(  908): Process com.newyorktimes (pid 21946) (adj 9) has died.
D/SSRMv2:SIOP(  908): SIOP:: AP = 380, PST = 370, Delta = 4
I/AudioService(  908): getStreamVolume 3 index 140
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  268): id=130 Removed oewyorktime (16/17)
I/SurfaceFlinger(  268): id=130 Removed oewyorktime (-2/17)
D/KeyguardUpdateMonitor( 1197): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1197): handleKeyguardVisibilityChanged(1)
D/LocationManagerService(  908): getLastLocation: Request[POWER_NONE passive fastest=0 num=1]
I/AudioService(  908): getStreamVolume 3 index 140
E/SMD     (  262): DCD ON
I/AudioService(  908): getStreamVolume 3 index 140
I/AudioService(  908): getStreamVolume 3 index 140

**Comment by lcd11001** [comment]
Hello, 
    I found the solution. This issue happens due to old React Native syntax
    In Android log cat , there is an error line:

**com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 's.View.propTypes.style'), stack:**

   => my solution  is: 

import {
    SytleSheet,
    View,
    **ViewPropTypes,**
} from 'react-native';

NewsFeed.propTypes = {
    news: PropTypes.arrayOf(PropTypes.object),
    // instead of listStyles: View.propTypes.style
    **listStyles: ViewPropTypes.style **
};
