### ISSUE TITLE
Add callback to ScrollView scrollTo method after animation

### ISSUE THREAD

**Issue by teodors** [facebook/react-native#11657]
This is just a suggestion. I am not a native developer, but it seems a good idea to add a callback for scrollTo method if it is possible.

For example, if a user presses on a "scroll me somewhere button" multiple times, it would be nice to disable this button until scroll animation finishes. It seems this might be a useful callback in some cases.

**Comment by teodors** [comment]
It also seems, that invoking multiple scrollTo with animation makes subsequent calls do it without animation.

**Comment by ptomasroos** [comment]
Give it a try to use ```onMomentumScrollEnd```

**Comment by teodors** [comment]
@ptomasroos Couldn't find any documentatin about `onMomentumScrollEnd`. I tried it and it only works if user manually scrolls. Not when you call a `scrollTo` with animation.

**Comment by bd-arc** [comment]
Hi there! This one is also an issue for us. Let me give you a concrete use case.
We've created our own [swiper plugin](https://github.com/archriss/react-native-snap-carousel) on top of the ScrollView component, but we aren't able to provide a reliable callback when swiping because `scrollTo()` doesn't offer one.

As suggested by @ptomasroos, we've tried using `onMomentumScrollEnd`. But, as stated by @teodors, the event is fired only when there is a user interaction (e.g. it won't work if we scroll programmatically). Moreover, as explained [in ScrollView's source code](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java#L76), enabling momentum events on Android can be expensive.

Another lead was to specify a duration for the scroll animation, and then to defer the firing of the callback according to it, but `scrollTo()` doesn't accept a custom duration either. [A PR was made](https://github.com/facebook/react-native/pull/1334), but it hasn't been active for a while.

That's why adding a callback to `scrollTo()` would be really helpful.

**Comment by sakulstra** [comment]
we've currently a usecase where we want to synchronize multiple scrollViews... a scrollView callback would be pretty neat to handle unbouncing

**Comment by ABleas** [comment]
I have a similar use case to make updates based on where a scrollView ends up, with or without gesture input. Can use `setTimeout()` to approximate, but it's not ideal.

**Comment by Skahrz** [comment]
Any new informations concerning this issue ?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ro-savage** [comment]
@hramos - This is still an issue, and I am running into the same thing. Would be a nice feature to have.

**Comment by hramos** [comment]
As it happens, we're using GitHub to track bugs in React Native. If you'd like to submit this as a feature request, please go ahead and create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets a good amount of votes, it will have a greater chance of being implemented by the community.

**Comment by Jasbir23** [comment]
+1 Much needed

**Comment by askday** [comment]
+1
