### ISSUE TITLE
[Android] ScrollView events are not triggered when manually calling scrollTo

### ISSUE THREAD

**Issue by dzautner** [facebook/react-native#11693]
### Description

When having a ScrollView with `onMomentumX` events, these event will not be triggered on Android if the scroll was triggered by a manual `scrollTo` call.

I expected the events to be triggered on both platforms, but they were only triggered on iOS.  

### Reproduction

Here is a small demo app to reproduce the issue on rnplay:
https://rnplay.org/apps/aPVzIg

The app has a state change (in this case, the width of the container) triggered by the ScrollView's `onMomentumScrollEnd` event, and a timeout to manually call `scrollTo` after 2,000ms. 

When running the sample on iOS, the state change will be triggered automatically after 2 seconds due to the `onMomentumScrollEnd`event being triggered post scrollTo.

When running the sample on Android, the state change will not be triggered automatically after 2 seconds (even though the `scrollTo` call could be seen to have been executed as the offset of the ScrollView changes).

When manually scrolling the view on Android, the event is being called as expected. 

### Additional Information

* React Native version: 0.33
* Platform: Android

**Comment by lzbSun** [comment]
I have a problem like yours. Do you solve it?

**Comment by lesniakania** [comment]
I have `react-native` in `0.40.0` version and I even don't get `onMomentumScrollEnd` when I normally scroll... But only in Android, iOS works

**Comment by windhost** [comment]
+1

**Comment by scottbrassfield** [comment]
This still seems to be the case on React v0.44. Would be really nice to have this same onMomentumScrollEnd hook for programmatic scrolls on Android. Is there any inherent reason why this behavior can't be implemented for Android?

**Comment by windhost** [comment]
Because the scroll position you want to scroll is not rendered yet, you have to wait for all rows to be rendered before you scroll to that position.

**Comment by uandco** [comment]
I'm on the same boat with onMomentumScrollEnd being triggered on manual scroll only on Android, whereas it's triggered after scrollTo too on iOS. An acceptable workaround would be a scrollTo callback function I guess.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by tbarsbay** [comment]
Any chance we could re-open this? I'm still experiencing it on RN 0.48, Android 7.1 on a Nexus 6.

In particular, I'm using a FlatList which triggers `onMomentumScrollEnd` when I swipe between items but not when I call `scrollToIndex` on Android. But if I call `scrollToIndex` on iOS, it correctly calls `onMomentumScrollEnd`.

**Comment by AugustoAleGon** [comment]
It should be open it!

**Comment by asgvard** [comment]
+1, seems hacky to manually trigger "onScrollEnd" when you manually scroll to an item, with an "expected" offset.

**Comment by tdekoning** [comment]
This is still an issue in RN 0.51

**Comment by lfkwtz** [comment]
https://react-native.canny.io/feature-requests/p/scrollview-add-completion-callback-to-scrollto

**Comment by superandrew213** [comment]
The issue is that `onScroll` or `onMomentumScrollEnd` does not trigger if scroll is triggered manually using `scrollTo` on Android.

For some reason setting `animated: true` in `scrollTo` seems to fix it.

**Comment by ledbetterljoshua** [comment]
This issue is showing up for RN 0.55.4. 
@superandrew213 had it right; `onMomentumScrollEnd` does not trigger on android if you use `scrollTo` but, setting `animated: true` does not seem to make a difference for me.

**Comment by superandrew213** [comment]
@ledbetterljoshua both `onScroll` or `onMomentumScrollEnd` don't trigger?

**Comment by liukaixin01** [comment]
This is still an issue in RN 0.55.3

**Comment by yashojha19** [comment]
Android ScrollView scrollTo doesn't do anything.  :(
```this.scrView.scrollTo({x:contentOffset.x-8,animated:true})```
