### ISSUE TITLE
[iOS] 'react-native link ...' command issue in react-native v0.40.0

### ISSUE THREAD

**Issue by sergey-akhalkov** [facebook/react-native#11747]
Hello!

### Description

I've got xcode `CodePush.h file not found` issue when I've tried to build my react-native app after using `react-native link react-native-code-push` command. The issue reproduces only with `react-native` having `v0.40.0` version and works well with version `v0.39.2`. After investigation I've found that issue reproduces not only for `react-native-code-push` - I've got build issues while trying to build `react-native` app with linked `react-native-maps`. The build issue with linked `react-native-maps` also reproduces only with react-native having `v0.40.0` version and works well with version `v0.39.2`.

### Reproduction

1. Execute `react-native init myapp` command to install sample `react-native` project
2. Execute `npm install --save react-native-code-push@1.16.1-beta` command to install `react-native-code-push` package
3. Execute `react-native link react-native-code-push` to link installed package
4. Build myapp using xcode

### Solution

Need to fix `react-native link ...` command issue in react-native v0.40.0.

### Additional Information

* React Native version: v0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by grabbou** [comment]
I think this is now fixed in 0.41-rc. I need to cherry-pick a fix and release 0.40.1 version. If you could help me by checking whether release candidate works for you, that'd be great. Otherwise, I'll just try to release a new version later this weekend.

**Comment by BretJohnson** [comment]
@grabbou What was changed in 0.41? Using v0.41.0-rc.0 I still see that $(SRCROOT)/../node_modules/react-native-code-push/ios/CodePush is no longer added to the include paths with react-native link (unlike in 0.39) so CodePush.h is still not found. Is that the expected behavior?

**Comment by yutin1987** [comment]
Because v0.40 https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d#diff-04eb2bf6fa605cab3b1f90ecfd65cc9cL1801 remove "$(SRCROOT)/../../React/**" on HEADER_SEARCH_PATHS

Need that keyword at shouldVisitBuildSettings variable, so `react-native link` will not work.
https://github.com/facebook/react-native/blob/master/local-cli/link/ios/mapHeaderSearchPaths.js#L29

maybe, we need change to `"$(BUILT_PRODUCTS_DIR)/usr/local/include";` and then fix it.

**Comment by jy1989** [comment]
so What's right way to use codepush in RN0.4 now?

**Comment by axemclion** [comment]
@jy1989 For now, here is the PR that fixes it - https://github.com/Microsoft/react-native-code-push/pull/665.

It basically does a couple of things.

1. Changes the include in `AppDelegate.h` to use `#import <CodePush/CodePush.h>`
2. In your project tree in XCode, under Libraries > CodePush > Build Phases, it adds a step to copy `CodePush.h` to the public headers location

Based on the decision on this thread, we will either merge the change, or leave it as is.

**Comment by jy1989** [comment]
@axemclion  hi thank you very much.
Although I dont know how exactly do in step 2. I'm newbie in ios.  so I just copy the `project.pbxproj`  from PR  to my `CodePush.xcodeproj`.
 it build success now.

**Comment by BretJohnson** [comment]
@jy1989 Yes, that should work.

**Comment by BretJohnson** [comment]
@grabbou You guys will want to decide if you want all react native link'ed libraries to now use "copy headers" to expose their own header files or will want to continue to allow things to work the old way, adding their directory under node_modules to the include path.

**Comment by jy1989** [comment]
@axemclion @BretJohnson @sergey-akhalkov 
hi guys. 
Now my project working fine with configuration `Release`
but build failed with `Staging`

![image](https://cloud.githubusercontent.com/assets/1291756/21842820/66ec01a4-d823-11e6-9837-9f845f714dae.png)

So how to make it works?

**Comment by axemclion** [comment]
@jy1989 Lets take this issue on the codepush repo. I have answered it at https://github.com/Microsoft/react-native-code-push/issues/668

**Comment by grabbou** [comment]
We have to change this function https://github.com/facebook/react-native/blob/master/local-cli/link/ios/mapHeaderSearchPaths.js#L29 as now there's no `React` in header search path anymore. 

We need another way to detect whether current `buildSettings` are from React target. I will follow up with a quick fix tomorrow. For now, it's going to cause a small problem.

**Comment by grabbou** [comment]
Also note this has nothing to do with the way Codepush defines headers.

**Comment by grabbou** [comment]
@axemclion @BretJohnson it depends. 

If you migrate over to a new system, we need to factor that change in the `react-native link`, that is - if project defines copy headers section, do not link header search paths).

For now, I suggest we stick with the current one and release a fix tomorrow (fastest). We can continue working on the former in the meantime.

**Comment by grabbou** [comment]
Fixed in https://github.com/facebook/react-native/commit/545072b02d94e264a66987a5cebc15629a16f188

**Comment by grabbou** [comment]
Second part is pending as a separate issue. Will land in a next release.
