### ISSUE TITLE
TextInput within parent View does not obey alignItems style of parent in iOS

### ISSUE THREAD

**Issue by kusumaw** [facebook/react-native#11892]
### Description

A TextInput within a parent View does not obey alignItems style of parent in iOS (assuming flexDirection: 'column'). The TextInput will just stay left aligned

### Reproduction

Run the following on iOS
```
import React, { Component } from 'react';
import { AppRegistry, View, TextInput } from 'react-native';

class AlignItemsBasics extends Component {
  render() {
    return (
      // Try setting `alignItems` to 'flex-start'
      // Try setting `justifyContent` to `flex-end`.
      // Try setting `flexDirection` to `row`.
      <View style={{
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
      }}>
        <View style={{width: 50, height: 50, backgroundColor: 'powderblue'}} />
        <View style={{width: 50, height: 50, backgroundColor: 'skyblue'}} />
        <View style={{width: 50, height: 50, backgroundColor: 'steelblue'}} />
        <TextInput placeholder="Username" style={{borderWidth: 1, borderRadius: 5, padding: 10, width: 100}}/>
      </View>
    );
  }
};

AppRegistry.registerComponent('AwesomeProject', () => AlignItemsBasics);
```
### Solution

1. Should be consistent with other components and follow the flexBox rules of parent
2. WORKAROUND: Add 'alignSelf: 'center'" to TextInput to center it

### Additional Information

* React Native version: 0.40
* Platform: iOS
* Operating System: MacOS

**Comment by shergin** [comment]
https://sketch.expo.io/rJvd4wDjg

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/textinput-within-parent-view-does-not-obey-alignitems-style-of-parent-in-ios

**Comment by shergin** [comment]
Actually it was fixed.

**Comment by danieljvdm** [comment]
This is not fixed - it only works if your TextInput is not multiline. There's no way to vertically center align a multiline TextInput (or apply vertical padding).

**Comment by shergin** [comment]
@danieljvdm Could you please provide a Snack?

**Comment by danieljvdm** [comment]
@shergin certainly. 

https://snack.expo.io/SJeQqcq6b

If you change `multiline={true}` to `false` the text is perfectly aligned.

**Comment by shergin** [comment]
@danieljvdm Do I understand right, you expect that flex-box props/styles will affect text layout inside <TextInput>? So, specifying `align-items: center` should aligh the text inside <TextInput>?
