### ISSUE TITLE
Android "Could not get BatchedBridge, make sure your bundle is packaged properly" - with fix

### ISSUE THREAD

**Issue by psam44** [facebook/react-native#12344]
### Description
I just followed the instructions on docs/getting-started.html (with a real device).
Got a RedBox with:

> Android error “Could not get BatchedBridge, make sure your bundle is packaged properly” on start of app

`react-native run-android`
There is a failed try to perform an adb command, revealed on the console with (French ouput):
> 'adb' n'est pas reconnu en tant que commande interne ou externe, un programme executable ou un fichier de commandes.

This prevents the script to run the regular `adb reverse tcp:8081 tcp:8081` and a fallback is engaged without this necessary setting.

### Solution

The fix is to help `local-cli\runAndroid\adb.js` to find adb.exe, the same way as local-cli\runAndroid\runAndroid.js:
Replace:
`const devicesResult = child_process.execSync('adb devices');`
By:
`const devicesResult = child_process.execSync( (process.env.ANDROID_HOME ? process.env.ANDROID_HOME + '/platform-tools/' : '') + 'adb devices');`

This should fix issue #9336 as well, unless there are another causes.

### Additional Information

* React Native version: react-native@0.41.2
* Platform: Android
* Operating System: Windows 10

**Comment by ShoaibKhazer** [comment]
thanks psam44
complete Path is:
 [yourProjectFolder]\node_modules\react-native\local-cli\runAndroid

**Comment by helloworldtang** [comment]
Solution:
under "react-native" directory:
after run command "./gradlew :Examples:UIExplorer:android:app:installDebug" successfully,
run commnad "./packager/packager.sh" successfuly.
then click "UIExplorer App“ in the emulator or the device

**Comment by zeeshanhanif** [comment]
I faced the same problem, it is because adb in not in your path.
Add adb in your path and it will work fine.
adb will be in <root/sdk/platform-tools>

**Comment by esilverberg** [comment]
I am hitting this issue when I am attempting to integrate in an existing app, when I say 

```
setUseDeveloperSupport(false)
```

However, if I call

```
setUseDeveloperSupport(true)
```

it works.

**Comment by siddhant91** [comment]
Hello, I am trying to run my react native app but i am not able to resolve the issue  "Android error “Could not get BatchedBridge, make sure your bundle is packaged properly” on start of app" , is there any fix for it , i cannot find any solution web either.

**Comment by siddhant91** [comment]
Hi , I also get the below error Execution failed for task ':app:processDebugResources'.
> java.io.IOException: Could not delete path

Does anyone has a solution on how can i run the app on emulator ???

**Comment by Slapbox** [comment]
Also having this issue with the emulator.

**Comment by eliprodigy** [comment]
Work for me 
http://stackoverflow.com/questions/17901692/set-up-adb-on-mac-os-x

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by psam44** [comment]
@hramos
This bug is still current with:
React Native version: react-native@0.47.1
And the one-line fix is still the one given in the description.

(these automatic closings, without reading, are discouraging for me to contribute)
