### ISSUE TITLE
Native animation driver animates opacity to wrong value

### ISSUE THREAD

**Issue by scarlac** [facebook/react-native#12453]
The issue seems to be with `Animated.Text` and `opacity`: Enabling useNativeDriver for Animated may prevent some text from fading in:
```javascript
accountSelectorAnim = new Animated.Value(0)
// ...
Animated.parallel([
  Animated.timing(this.accountSelectorAnim, {
    toValue: 1,
    duration: 515,
    easing: Easing.easeOut,
    useNativeDriver: true,
  }),
  // ...  
]);
// ...
const textOpacity = animation.interpolate({
  inputRange: [0, 0.5, 1], outputRange: [0, 0.5, 1]
});
```
In render:
```jsx
<Animated.Text style={{opacity: textOpacity, color: 'white', marginBottom: 5}}>
Hello
</Animated.Text>
```
Only the first value in the interpolation will be applied (in this case 0, which means text will never appear). The rest of the values have no visible effect.
If I change the first value to something larger than 0, I can faintly see some kind of animation back and forth in opacity values before it quickly lands on the first outputRange value, but I'm not sure what it's doing.
Technically, the interpolation is unncessary in this case (since it animates from 0 to 1 already) but the issue remains if I remove the interpolation (ie. `const textOpacity = animation`)
If I set `useNativeDriver: false` then it works exactly as expected.

### Solution

The text should animate exactly as it does when `useNativeDriver: false` is set. The fact that the text fades in and out very quickly may be a clue to the origin of the error. Perhaps it's just that the animation timing and end values are not aligned somehow.

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: macOS 10.12.3

**Comment by janicduplessis** [comment]
Have you tried getting rid of Animated.parallel and running only that one animations to see if it works, looks like a pretty simple animations so I'm having trouble seeing what could go wrong.

**Comment by janicduplessis** [comment]
Also do you know if it happens on Android too? (Would help me know if the bug is in the native implementation or not).

**Comment by scarlac** [comment]
Sorry, no Android setup here, but I'll try to remove `Animated.parallel` and see where that takes me. Currently, my workaround is to simply wrap the text in an `Animated.View` and move the opacity animation to that. No animation code change, but it still fixes the issue.

**Comment by janicduplessis** [comment]
I see, the issue is probably related to Animated.Text in that case.

**Comment by scarlac** [comment]
I tried removing the parallel, so the animation is triggered by itself. Same result.
[Here's a quick video of the issue](https://dl.dropboxusercontent.com/u/4361479/animated-text-opacity.mp4).

Also, I tried adding:
`const textTop = animation.interpolate({inputRange: [0, 1], outputRange: [10, 0]});`
and then using it
```jsx
<Animated.Text style={{transform: [{translateY: textTop}], color: 'white', marginBottom: 5}}>
```
Which works. So it's only opacity that has an issue. TranslateY works fine.

**Comment by janicduplessis** [comment]
Ok, I'll try to figure out why this happens, in the meantime using an extra view seems like an ok workaround.

**Comment by orenklein** [comment]
I just experienced similar issue with Animated.View on android. However, translateX/translateY did not work also. I found that setting backgroundColor: 'transparent' is solving this issue. @scarlac Maybe it will work for you too.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by Mtnt** [comment]
This issue is still actual.
RN: 0.50.3
OS: iPhone 6s (11.1) / High Sierra 10.13.1 (17B48) - emulator

### Is this a bug report?

Yes, it is a bug

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

Target Platform: iOS (11.1)

### Steps to Reproduce

1. create an `Animated.Text` node with `opacity: opacityValue` style; `opacityValue = new Animated.Value(0.4)`;
2. launch animations with following code:
```
setInterval(() => {
    Animated.timing(opacityValue, {
        toValue: 1,
        duration: 150,
        useNativeDriver: true,
    }).start(() => {
        Animated.timing(opacityValue, {
            toValue: 0,
            duration: 150,
            useNativeDriver: true,
        }).start();
    });
}, 2000);
```

### Expected Behavior

Blinking text from `0.4` opacity to absolutely visible, to absolutely invisible, visible, invisible and so on.

### Actual Behavior

Starts from `0.4` opacity, go to about `0.8` opacity (not `1`), to zero, to `0.8` and so on.

On the screenshots a little different situation: it`s a red text (#ff0000) above a white text (#ffffff), only the red text is animated.
![iphone 6s - ios 11 1 2017-11-21 16-44-05](https://user-images.githubusercontent.com/1556235/33077918-271bd6d8-cee2-11e7-9931-040b469a90f9.png)
![iphone 6s - ios 11 1 2017-11-21 16-44-37](https://user-images.githubusercontent.com/1556235/33077980-58effb12-cee2-11e7-9fd6-8845c3901676.png)
![iphone 6s - ios 11 1 2017-11-21 16-44-43](https://user-images.githubusercontent.com/1556235/33077985-5b5ec4c8-cee2-11e7-9b06-adf5ce58c125.png)
![iphone 6s - ios 11 1 2017-11-21 16-44-56](https://user-images.githubusercontent.com/1556235/33077987-5d95c1f6-cee2-11e7-883f-3f820e49c011.png)

**Comment by wcandillon** [comment]
I'm experiencing the same issue as well.
