### ISSUE TITLE
AsyncStorage Couldn't read row 0, col 0 from CursorWindow

### ISSUE THREAD

**Issue by JAStanton** [facebook/react-native#12529]
### Description

When reading values that are too large using AsyncStorage on Android I run into this error:

I wrote a large value with AsyncStorage and later tried to read it, but it crashed.

```
BaseError: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
  at e (/node_modules/react-native/Libraries/Storage/AsyncStorage.js:423:22)
  at None (/node_modules/react-native/Libraries/Storage/AsyncStorage.js:416:71)
  at map ([native code])
  at errors (/node_modules/react-native/Libraries/Storage/AsyncStorage.js:416:51)
  at slicedToArray (/node_modules/react-native/Libraries/Storage/AsyncStorage.js:54:33)
```

### Reproduction

It looks like on iOS we write to disk when the value is above a threshold and on Android we write to sqllite always. 

```js
let x = 'x';
while (x.length <= 3194304) {
  x = `${x}${x}`;
}
await AsyncStorage.setItem('@@GARBAGE@@', x); // works
const garbage = await AsyncStorage.getItem('@@GARBAGE@@'); // throws
```

### Solution

In order for me to fix this I'll need to re-write AsyncStorage to write to disk instead of writing to sql. https://github.com/mvayngrib/react-native-safe-async-storage <--- this guys has the right idea but his code is super old and broken. 

### Additional Information

* React Native version: 0.39.2
* Platform: Android
* Operating System: Samsung Galaxy S4

**Comment by brentvatne** [comment]
Hello! The react-native 0.29 is very out of date, can you try to repro this in the latest version?

**Comment by JAStanton** [comment]
Oh I'm sorry I meant to say `0.39.2`

**Comment by davidck** [comment]
Did you find a solution?  I've ran into this today as well.  Storing base64 encoded images in AsyncStorage... on RN 0.41

Same error returned from Android.  Solution might have to start writing to disk instead.

**Comment by JAStanton** [comment]
Yeah, I rewrote the library completely to use file storage instead of async
storage that uses sql. You should probably do the same. Check out
react-native-fs. Also base64 images is a pretty expensive operation,
consider writing image on disk directly, also using react-native-fs


On Fri, Mar 10, 2017 at 6:37 PM David Chan <notifications@github.com> wrote:

Did you find a solution? I've ran into this today as well. Storing base64
encoded images in AsyncStorage... on RN 0.41

Same error returned from Android. Solution might have to start writing to
disk instead.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/react-native/issues/12529#issuecomment-285835546>,
or mute the thread

**Comment by agrass** [comment]
Any recommended solution for this?? use react-native-fs?

**Comment by JAStanton** [comment]
@agrass react-native-fs is a step in the right direction but it's quite slow. https://github.com/mvayngrib/react-native-safe-async-storage  has the right idea but it just needs to be re-written. Another option is to try to read from disk, if you fail catch the failure, dump your state, (full or partial) and keep moving on. I do both approaches in my app. Garbage collect, catch the failure, as well as I using react-native-fs and an approach like  `react-native-safe-async-storage`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ThaJay** [comment]
It's still an issue when trying to read something large from AsyncStorage.
Please consider an error on write instead.

**Comment by skv-headless** [comment]
@hramos It is not fixed for sure. Here is a small a explanation
https://stackoverflow.com/a/21432966/1410905.
Maybe it worth mentioning in the docs that max size for sqlite cursor is 2mb?

In docs said
`On Android, AsyncStorage will use either RocksDB or SQLite based on what is available` 
would be great to know how to switch to RocksDB?

**Comment by agrass** [comment]
that limit of 2mb is for only one key/value document of the whole database?

**Comment by nevir** [comment]
per key/value

**Comment by agrass** [comment]
this still happening in newer versions right? I'm using RN 41

**Comment by nevir** [comment]
This is still a problem in the latest RN, AFAIK

**Comment by kelset** [comment]
Can confirm that this is still an issue on 0.53 - basically is still valid what @skv-headless linked and the solution proposed by @ThaJay is prob the best 'workaround' at the moment.

Only side-issue with using [`redux-persist-filesystem-storage`](https://github.com/robwalkerco/redux-persist-filesystem-storage) is that it's a bit 'massive', meaning that it would reset all the saved data if deployed as an update on an existing app (as is in our scenario). Any ideas on how to implement it in a non-destructive way? (writing a migration or something?)

**Comment by eassymo** [comment]
Still happening, ussing 

    "react": "16.4.0",
    "react-native": "0.55.4",

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-async-storage#10.
