### ISSUE TITLE
overflow visible on ListView on Android

### ISSUE THREAD

**Issue by marcoacierno** [facebook/react-native#12604]
### Description

I want to show the current item of a ListView at the center and show the prev and next item (if available) to the left and right. I use the pagination feature (`pagingEnabled={true}`) so the user can snap between the items.

On iOS it works fine, I can see the prev and next items but on Android they don't appear

### Reproduction

- Create a ListView, and set the width the ListView as the width of the elements inside it, enable pagingEnabled too.
- The prev and next items are in overflow outside the ScrollView

On iOS it looks fine (I can see the prev/next items in overflow) but on Android they are not visible even if I enable the new FlatUI / Nodes mode

It's roughly the code to reproduce the problem https://rnplay.org/apps/CyiVcQ, I will link a project with the Android FlatUI mode enabled as soon as I can.

P.S In the example the width are not correct so it doesn't look well (because the listview should have at the center the active item)

I hope it's clear enough

### Solution

The overflow should be visible on Android when using the new Flat UI mode, I tried adding setClipChildren/padding etc using a custom scroll view but without luck (they still don't appear)

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Operating System: MacOS

**Comment by RichardLindhout** [comment]
There is a new ListView implementation. https://hackernoon.com/react-native-new-flatlist-component-30db558c7a5b. Maybe it will work.

**Comment by marcoacierno** [comment]
Tried it now, the same issue :(

Current result http://i.imgur.com/7Hxy3ZB.png (Android)

Correct result: http://i.imgur.com/0OXZtW0.png (iOS, the other items are in overflow visible)

If I open the layout inspector in Android Studio I can see the other is correctly rendered, but the HorizontalScrollView fails to show the children outside his bounds ( http://i.imgur.com/HcBLFCj.png )

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.

**Comment by bsonntag** [comment]
@hramos didn't @marcoacierno say in his last comment that he tried FlatList and had the same issue?

@marcoacierno can you confirm that you're having the same issue with FlatList?

**Comment by hramos** [comment]
@bsonntag in that case I recommend opening a new FlatList issue, or having @marcoacierno 
 update the original post to be specific to FlatList.

**Comment by marcoacierno** [comment]
Hi @bsonntag @hramos , I need to test again with the new version of React Native, but it didn't worked when I tried the last time (overflow was not visible even with flatlist). Anyway I fixed my issue by manually disabling the clip children/etc using Java.

I will test again when I have a bit of free time and, if I encounter the same issue with FlatList again, I will open a new issue

**Comment by lsps9150414** [comment]
Confirmed problem still exist on SectionList.

New issue created https://github.com/facebook/react-native/issues/14416
