### ISSUE TITLE
ViewPager nest View nest ViewPager

### ISSUE THREAD

**Issue by zxwxw** [facebook/react-native#12845]
### Description

react native android 0.42

View nest ViewPager,ok
ViewPager nest ViewPager,ok
ViewPager nest View nest ViewPager, second ViewPager child view not render

debug react native android code, second ViewPager onLayout has no child,but PagerAdapter has views 

```
      <ViewPagerAndroid>
        <View>
          <ViewPagerAndroid>
            <Text>Hello World</Text>
          </ViewPagerAndroid>
        </View>
      </ViewPagerAndroid>
```

second ViewPager getWindowToken is null

**Comment by Ehesp** [comment]
Nested `ViewPagerAndroid` don't work without a "workaround", I believe there's another issue made somewhere but I can't find it yet.

Workaround: From memory, you need to update state when the the nested ViewPagerAndroid has rendered. I did something like:

```
const HEIGHT = 600;

...

constructor() {
    super();
    this.state = { height: HEIGHT - 0.01 };
}

componentDidMount() {
    this.setState({ height: HEIGHT });
}

render() {
    return (
        <ViewPagerAndroid style={{ height: this.state.height }}
            ...
    );
}
```

**Comment by zxwxw** [comment]
@Ehesp I already try, but not work, you can try ViewPager nest View nest ViewPage.

It is a react native android native code bug, second ViewPager not attach to window(android framework), ViewPager init child, will judge getWindowToken is null, getWindowToken is null, will return nothing.

run on react native android 0.42
Thinks

**Comment by kunkun12** [comment]
I  try 
`componentDidMount() {
 setTimeout(()=>{
             this.setState({
                height:this.height
             })
        },0)
}`  can work ，But It's not a good solution

**Comment by kunkun12** [comment]
@zxwxw 
I try
`componentDidMount() { 
           setTimeout(()=>{ this.setState({ height:this.height }) },0) 
  }` 
this can work ，But It's not a good solution

**Comment by zxwxw** [comment]
@kunkun12 I already try setTimeout, but also not work
before I create this issues, I already see https://github.com/facebook/react-native/issues/8348, and try all, but not work.

@Ehesp @kunkun12  you try on React Native Android **0.42**？

see follow code, background should be gray, but is black.

```
import React, {Component} from 'react';
import {AppRegistry, View, ViewPagerAndroid} from 'react-native';

const HEIGHT = 600;

export default class demo extends Component {

  constructor() {
    super();
    this.state = {height: HEIGHT - 0.01};
  }

  componentDidMount() {
    setTimeout(()=>{
      this.setState({ height: HEIGHT});
    })
  }

  render() {
    return (
      <ViewPagerAndroid style={{flex: 1, backgroundColor: 'white'}}>
        <View style={{height: this.state.height}}>   
           <ViewPagerAndroid style={{flex: 1, backgroundColor: 'black'}}>
            <View style={{flex: 1, backgroundColor: 'gray'}}/>
          </ViewPagerAndroid>  
        </View>
      </ViewPagerAndroid>
    );
  }
}

AppRegistry.registerComponent('demo', () => demo);
```

finally, I override ViewPager getWindowToken, work
```
    @Override
    public IBinder getWindowToken() {
        if (super.getWindowToken() == null) {
            return new IBinder() {
                @Override
                public String getInterfaceDescriptor() throws RemoteException {
                    return null;
                }

                @Override
                public boolean pingBinder() {
                    return false;
                }

                @Override
                public boolean isBinderAlive() {
                    return false;
                }

                @Override
                public IInterface queryLocalInterface(String descriptor) {
                    return null;
                }

                @Override
                public void dump(FileDescriptor fd, String[] args) throws RemoteException {

                }

                @Override
                public void dumpAsync(FileDescriptor fd, String[] args) throws RemoteException {

                }

                @Override
                public boolean transact(int code, Parcel data, Parcel reply, int flags) throws RemoteException {
                    return false;
                }

                @Override
                public void linkToDeath(DeathRecipient recipient, int flags) throws RemoteException {

                }

                @Override
                public boolean unlinkToDeath(DeathRecipient recipient, int flags) {
                    return false;
                }
            };
        }
        return super.getWindowToken();
    }
```

**Comment by congsuboya** [comment]
only override ViewPager getWindowToken?

**Comment by congsuboya** [comment]
@zxwxw

**Comment by zxwxw** [comment]
@congsuboya 

ViewPagerAndroid(JS) -> ReactViewPager -> ViewPager (getWindowToken is null cause child view not draw)

so override ViewPagerAndroid(JS) -> CustomReactViewPager(getWindowToken)

**Comment by Zhu-Arthur** [comment]
when i use 0.40, it's ok. But i update to 0.44, the inner viewpager's chidlren didn't render.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by adhambadr** [comment]
still a problem in 0.51.0, workaround with setState with timer works but is a huge performance drain if using complex views and data requests on children's mount.

**Comment by c0d3blooded** [comment]
This is still a problem for me in 0.51.0 as well. ViewPager views render fine on their own but don't when inside another ViewPager.
