### ISSUE TITLE
TextInput should have intrinsic size based on `placeholder`

### ISSUE THREAD

**Issue by bryanjclark** [facebook/react-native#12904]
### Description
I'm trying to make a `UISearchField` using RN components, and I'm unable to create a center-aligned text-and-icon layout for the placeholder ("empty state") of the text field. 

I've added some borders and background colors to highlight what's going on - notice how the light-blue area (where the `TextInput` is) is collapsed to near-zero width:
![pasted image at 2017_03_13 10_20 am](https://cloud.githubusercontent.com/assets/868389/23867270/98cf0ad8-07d8-11e7-9166-3fbac4ed7d9a.png)

However, if I replace the `TextInput` with a `Text` component, the layout works as expected with `flexGrow` and `flexShrink`:
![simulator screen shot mar 13 2017 10 36 05 am](https://cloud.githubusercontent.com/assets/868389/23867629/c38fa7b8-07d9-11e7-87f7-3a45f8f991ac.png)

### Reproduction

I've created a sample project here that demonstrates the issue: https://sketch.expo.io/Sk5b_uEox

### Solution
Adjust TextInput's implementation so its `value` and `placeholder` work with `flexGrow` and `flexShrink`.

### Additional Information
* React Native version: RN v43
* Platform: iOS, haven't tried Android
* Dev tools: iOS 10.2

**Comment by shergin** [comment]
Do you want to see `<TextInput>` with same size that `<Text>` with "Search" has?
So, in other words, do you expect from <TextInput> to have intrinsic content size which respects `placeholder` and `value`?

**Comment by shergin** [comment]
@bryanjclark Ta-da! ea9d6746df8edab5d685614d6086c51f282f8056 (At least for iOS.)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by JaEdmuva** [comment]
Hi, I'm using 0.54.1 and this works perfectly in iOS, but the issue persists in android. Is this being o has been reviewed by any android developer?

**Comment by hramos** [comment]
If this happens in 0.54.1 can you open a new issue?
