### ISSUE TITLE
Toggling secureTextEntry between true and false cause text to disappear on iOS

### ISSUE THREAD

**Issue by phil714** [facebook/react-native#12939]
### Description

I'm trying to create a custom password input where you can toggle if you can see the password or not. The bug is that when you change between true and false on textInput, the content of the input disappear. 

### Reproduction

First, you need to have a textInput with secureTextEntry. Then you enter a string in the textinput. After that you set the secureTextEntry to false and then back to true and you enter another character. The field should be set empty and then the new character appear.

On android, the cursor is set to the beginning of the field you do the same steps.

### Solution

I found that the onChangeText props of the TextInput return an empty string when you set secureTextEntry to true. 

### Additional Information

React Native version : 0.41
Platform: iOS and Android
OS : MacOS

Here's a simple example of what I'm trying to do : 

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableOpacity
} from 'react-native';

export default class test_secureTextEntry extends Component {
  constructor(props) {
        super(props);
        this.state = {
          hidden: true
        };
    }

  render() {
    return (
      <View style={styles.container}>
        <TextInput
          secureTextEntry={this.state.hidden}
          style={{ width: 100, height: 40, backgroundColor: 'grey' }}
        />
        <TouchableOpacity
          onPress={ () => this.setState({ hidden: !this.state.hidden })}
        >
          <Text>Go</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});

AppRegistry.registerComponent('test_secureTextEntry', () => test_secureTextEntry);

```

**Comment by urska19** [comment]
Workaround that is working for me, is removing focus from TextInput, when user clicks show/hide password. One way to do this, is to add ref (for example ref="password") to your TextInput and then call this.refs.password.blur()

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by ryanab** [comment]
I just came across this issue today in React Native 44 so it still exists in some capacity I believe. 

I am using the work around for the time being, perhaps I will create a new project with the latest release candidate and see if I can reproduce, and if so take a look at source and submit a PR.

**Comment by lchapoy** [comment]
I am using react-native 49.5 and the issue is still there.

**Comment by ryanab** [comment]
@lchapoy does the issue exist on both IOS and Android?

**Comment by lchapoy** [comment]
I haven't tested on Android. I am implementing the password visibility behavior and I notice that it is clearing the input when the user tries to write on it after the secureTextEntry property change from false to true.

So far I have only tested on IOS 11.2 iPhone 6 emulator.

**Comment by GitHubTracey** [comment]
Hey, 

I'm a little late to the party, but I can confirm the behaviour is both in Android as well as iOS, regardless if I am doing a development or production build - and it is still present in 0.51.0. 

Though I'm thinking this behaviour is also intentional for those that do not have a show/hide option for the password. (Go look at your local banking app where they don't have the option to view password).

Seeing as I am in need of the show/hide option - especially for android as if you have a custom onChangeText event, then it doesn't show the characters with a delay... I added an icon at the end and then I handle the loss of data by saving the existing text in local state at the beginning of the onChangeText event like this:

```
onChangeText={(text) => {
    this.setState({ text, savedText: this.state.text });
        if (this.props.onChangeText) {
            if(!this.state.text) {
                text = this.state.savedText + text;
            }
        this.props.onChangeText(text);
    }
}}
```

Hope that helps set someone in the right direction!

**Comment by ryanab** [comment]
Thanks Tracey, I tried something similar but the issue I came across is handling certain edge cases.  For example, when the toggle is pressed IIRC a delete char is sent through.  So, we can just tell it to ignore that and use setNativeProps to set the previously saved text.  But then, what if the user's first intention is to delete/backspace, now the text is not displaying what the user has typed/intended due to our hijacking the input text?  

I am sure there is a work around, but it feels like there are edge cases we have not thought of and we should not be doing so much manipulation to the native behavior.

However, I am wondering if this is like you said, and is an intended behavior.  The AirBNB App I noticed has the same "bug" (try it yourself type a password then hit the show/hide toggle).  I know they use React Native for some portions of their app, and I was wondering if this was the same issue or if again, this is an intended behavior.  Maybe someone from FB / AirBNB can chime in if they come across this!

Thanks,
Ryan

**Comment by GitHubTracey** [comment]
Hey Ryan, 

Ooh... yes, the only time that I see this potentially being a problem is if the user decides to "select all" text and then delete, and type a character... then it reloads it all...hm. I'm going to have to think about it a little more. Definitely an edge case for me, but still important for the user experience!

Thanks for the catch!

Tracey

**Comment by nateReiners** [comment]
+ 1 this is still an issue for me (RN 0.50.3) and this should be re-opened

**Comment by ryanab** [comment]
If you have the airbnb app logout and give it a try, its the same issue. I
know they use react native for some portions (so don’t know if this portion
is), but I am wondering if this is expected behavior? Maybe for some reason
this is done for security? Curious to see others thoughts.

**Comment by nateReiners** [comment]
@ryanab  I have an Samsung Android phone, and the AirBnB app's password field works perfectly (does not clear on backspace after toggling the hide password prop).  However, when I tried their iOS app on my iPhone6, the password field clears just like you said. Interesting. I blame Apple.

**Comment by Astarta0** [comment]
Hello everyone! 
Please, can you help me?
I user RN 0.52.2,
I have TextInput for users password:
```
<TextInput
                                ref={(input) => {this.passwordInput = input}}
                                value={this.props.userPassword}
                                returnKeyType={'go'}
                                secureTextEntry={this.state.hidePassword}
                                autoCorrect={false}
                                autoCapitalize={'none'}
                                placeholder={'Пароль'}
                                placeholderTextColor={THEMES.blue.gray}
                                style={styles.textInput}
                                onChangeText={this.props.updateUserPasswordFromSignUp}
                                underlineColorAndroid="transparent"
                                autoComplete={false}
 />
```
**And when  secureTextEntry is false , I will see suggestions on the keyboard**, but I want avoid suggestions - it takes place of screen)

**Comment by Draccan** [comment]
It could be possible that the error is in the secureTextEntry implementation? I've seen that the input is cleared on iOS even if I focus another input and then come back to the secureTextEntry input.

So it could be possible that secureTextEntry blurs and focus again input changing secureTextEntry prop value?

**Comment by ryanab** [comment]
I was looking into this again and was looking at IOS Secure Text Entry and actually think this may be the default/desired behavior by Apple for said component.

**Comment by altaf933** [comment]
I have same issue on react-native version _react-native: 0.55.3_
