### ISSUE TITLE
ios update to 0.43.0-rc.2,  None of your spec sources contain a spec satisfying the dependency: `Yoga (= 0.43.0-rc.2.React)`

### ISSUE THREAD

**Issue by cky113999742** [facebook/react-native#12992]
// the profile 
pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    ]

Fetching external sources
-> Fetching podspec for `React` from `./node_modules/react-native`

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `Yoga (= 0.43.0-rc.2.React)` required by `React/Core (0.43.0-rc.2)`

None of your spec sources contain a spec satisfying the dependency: `Yoga (= 0.43.0-rc.2.React)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by ptomasroos** [comment]
As the error is trying to tell you. You need to include the dependency Yoga.

```
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```

**Comment by cky113999742** [comment]
![2017-03-17 9 07 22](https://cloud.githubusercontent.com/assets/14501851/24044323/c3a94c7a-0b55-11e7-89cc-447db549d485.png)

I do it,but  the "Yoga.h" file not found.  React and Yoga in the same level, could import Yoga.h from React.h? @ptomasroos

**Comment by jeanregisser** [comment]
Thanks @ptomasroos I added the explicit dependency with RN 0.43.0-rc3 and didn't get any error 👍

**Comment by sibelius** [comment]
@cky113999742 can we close this?

**Comment by hovox** [comment]
Not fixed in latest releases or `master` branch

**Comment by keshavkaul** [comment]
This issue is there in 0.42.3 as well

**Comment by ide** [comment]
You need to include the Yoga reference in your Podfile too: https://facebook.github.io/react-native/releases/next/docs/integration-with-existing-apps.html#podfile

```rb
pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
```

**Comment by keshavkaul** [comment]
If I may ask, What is this Yoga dependency? Also, could anyone explain the difference between a React.xcodeproj and ReactCxx.xcodeproj ? These are something new in 0.42 version.

**Comment by hovox** [comment]
I think this should be fixed in master branch so newcomers will not have this issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by nschurmann** [comment]
Im still reproducing this!, i added Yoga to my pod file but still cannot find it
