### ISSUE TITLE
Application and Package naming in manifest

### ISSUE THREAD

**Issue by AliakseiRusetski** [facebook/react-native#13236]
### Description
Using command 
`react-native init MyApp --package="com.mycompany.myapp"`
or
`react-native init MyApp --package com.mycompany.myapp`
or
`react-native init MyApp --package=com.mycompany.myapp`
does not give properly created package in _AndroidManifest.xml_.
(I've come from this link [stackoverflow](http://stackoverflow.com/questions/40281569/use-specific-package-name-when-setting-up-a-react-native-project))

### Reproduction Steps and Sample Code
Use commands described above and look in _AndroidManifest.xml_ or _Info.plist_. 
There is wrong _package_ attribute.

### Solution
Perhaps should be fixed _package_ option for `react-native init` command.
Or added option which allows to rename application and package.

### Additional Information

* React Native version: 0.42.3
* Platform: both
* Development Operating System: MacOS
* Dev tools: react-native-cli

**Comment by jeebus3000** [comment]
#12721

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by emin93** [comment]
Is there a chance to reopen the issue since it's still missing? Also i couldn't find a reason why it got removed from the CLI. Thanks in common.

**Comment by jmc420** [comment]
any chance this could be reinstated in react-native-cli?

https://github.com/facebook/react-native/blob/890342ed881f27d19a77e518c2c59ea56c162668/local-cli/generator-android/index.js#L27
