### ISSUE TITLE
[FlatList] Sometimes FlatList rows are rendered, but not displayed until scroll. RN 0.43

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#13316]
### Description

When using FlatList, rows are not displayed though `renderItem` is called.
Rows appear immediately when scroll is triggered on the list.

### Reproduction Steps and Sample Code

```javascript
export default class List extends Component {
  renderItem({item}) {
    return (
      <Text>{item}</Text>
    );
  }

  render() {
    return (
      <FlatList
        style={{
          flex: 1,
          backgroundColor: 'white',
        }}
        data={[1, 2]}
        renderItem={this.renderItem}
      />
    );
  }
}
```

### Solution

FlatList should always display its rendered items.

### Additional Information

* React Native version: 0.43.0
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by joonhocho** [comment]
Related https://github.com/facebook/react-native/issues/13202

**Comment by joshyhargreaves** [comment]
@joonhocho could you create a gif of this in action? I can't reproduce with your example.

**Comment by joshyhargreaves** [comment]
Are you experiencing this issue in a standalone project and/or are you able to reproduce in a standalone project if not?

**Comment by Thomas101** [comment]
We're also seeing this issue. Looks like it could be something to do with the FlatList being in a navigator on iOS. Managed to reproduce it in a standalone project. You'll have to excuse the code it's a bit rough.

react-native init and add the following code as your index.ios.js. Once launched, tap on A. Tap remove. Tap back. Then you'll need to scroll to get FlatList to re-render.

We found this on RN0.43.1 iOS simulator, iPad but not android. Seems to work as expected on android


```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View, FlatList, TouchableOpacity, Navigator } from 'react-native';

let data = [ { id: 'a' }, { id: 'b' }, { id: 'c' } ]
let listeners = []

class List extends Component {
  constructor (props) {
    super(props)
    this.state = { data: Array.from(data) }
  }

  componentDidMount () {
    listeners.push(() => { this.setState({ data: data }) })
  }

  render () {
    return (
      <FlatList
        data={this.state.data}
        keyExtractor={(item) => item.id}
        renderItem={({item}) => (
          <TouchableOpacity onPress={() => this.props.navigator.push({ id: 'r2', item: item })}>
            <View>
              <Text>{item.id}</Text>
              <Text>{item.id}</Text>
              <Text>{item.id}</Text>
              <Text>{item.id}</Text>
            </View>
          </TouchableOpacity>
        )}
      />
    )
  }
}

export default class AwesomeProject extends Component {

  renderScene (route, navigator) {
    if (route.id === 'r1') {
      return (<List navigator={navigator} />)
    } else if (route.id === 'r2') {
      return (
        <View>
          <Text>{route.item.id}</Text>
          <TouchableOpacity onPress={() => {
            data = [data[0], data[2]]
            listeners.forEach((l) => { l() })
          }}>
            <Text>Remove</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => navigator.pop()}>
            <Text>Back</Text>
          </TouchableOpacity>
        </View>
      )
    }
  }

  render() {
    return (
      <View style={[StyleSheet.absoluteFill, { paddingTop: 50 }]}>
        <Navigator initialRoute={{ id: 'r1' }} renderScene={this.renderScene.bind(this)} />
      </View>
    );
  }
}

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

**Comment by sahrens** [comment]
Does setting removeClippedSubviews={false} fix the issue? Sounds like the issue might be related to the navigator which would explain why we don't see this problem at Facebook. cc @shergin

**Comment by joonhocho** [comment]
@Thomas101 @sahrens I am using `react-navigation` for your information.

**Comment by raffij** [comment]
@sahrens removeClippedSubviews={false} works for us for now.

We are using Navigator for a tab based app.

1. Navigate to the flatlist scene. List shows.
2. Navigate to another tab.
3. Make a change which affects the flatlist scene.
4. Navigate to the already mounted flatlist scene.
5. Flatlist shows as empty.
6. Touch component and the items are made visible.

**Comment by joonhocho** [comment]
@raffij @sahrens It also fixed the issue for me as well.

**Comment by Thomas101** [comment]
`removeClippedSubviews={false}` works for us too. I noticed in the VirtualizedList docs there's some discussion around setting this as the default, could I +1 that as I imagine quite a few people will come up against this?

**Comment by sahrens** [comment]
I'm running an experiment in production soon to see the effect on scroll perf. If the hit isn't too bad, we'll turn it off by default.

**Comment by huyanhh** [comment]
Running into a similar problem here. It isn't exactly scrolling that's my problem though. What I have is a horizontal FlatList with paging enabled. I have a function that adjusts each item of the list to the width of the screen. What I'm doing right now is using redux and async storage to persist all my items, but the items do not render until I hit a button in my view to add another item in the list. When I set `removeClippedSubviews={false}` the view renders, but only part of it. I suspect it has something to do with the `render` prop, because when I render just a TextView I see the display, but not my full custom component. I'll post my code and a video tomorrow.

**Comment by joenoon** [comment]
I had a possibly related issue with a ListView (RN 0.43.2) that seems to be solved by the `removeClippedSubviews={false}` suggestion.

In my case this ListView was inside an Animated.View with a translateY style (sliding down).  When the animation ended the ListView would have variable space above the first row (as if there was some contentInset padding).  Just barely scrolling the list would snap everything back to normal and the first row would be correctly at the top.

Just noting it here in case it might provide a hint.

**Comment by sahrens** [comment]
I'm putting in a diff to disable `removeClippedSubviews` by default in `VirtualizedList`, so it will be opt-in and hopefully won't bite people like this in the future.

**Comment by joonhocho** [comment]
@sahrens Could you explain why `removeClippedSubviews` fixes the issue? Is setting `removeClippedSubviews` as `false` an optimal solution or is it just a temporary quick fix?

**Comment by Noitidart** [comment]
> Could you explain why removeClippedSubviews fixes the issue? 

I am wodering this question as well. I am using react-navigation as well. Setting `removeClippedSubviews` to false also fixed this for me. I'm not sure of it's implications (reduced perf?).

**Comment by npomfret** [comment]
I'm getting this too in RN 0.43.3. Why is this closed?

**Comment by joshyhargreaves** [comment]
I think the conclusion is that setting removeClippedSubviews={false} seems to fix these issues? Have you tried this yet?

**Comment by npomfret** [comment]
Yeah, i just figured that out, cheers.  Much better.  But it's still a bug, no?

**Comment by sahrens** [comment]
removeClippedSubviews is now off by default in master.

**Comment by vjeranc** [comment]
This also breaks components like react-native-maps (the map gets frozen on some area until swipe or some other gesture event).

**Comment by vjeranc** [comment]
This also breaks components like MapView in react-native-maps (the map gets frozen on some area until swipe or some other gesture event). So, this is not just an issue with react-native components.

I also believe MapView uses clipped subviews (markers I believe are clipped), so would this remove markers?

**Comment by vjeranc** [comment]
This also breaks components like MapView in react-native-maps (the map gets frozen on some area until swipe or some other gesture event). So, this is not just an issue with react-native components.

**Comment by huyanhh** [comment]
Got something really weird.

I'm trying to scroll to the end of my horizontal pager I made out of the Flatlist with this

```
componentDidMount() {
    this._listRef.scrollToEnd({ animated: false });
  }
```

Here's my Flatlist:
```
<FlatList
          ref={(flatList) => { this._listRef = flatList; }}
          data={this.props.log}
          onLayout={this.adjustPageSize}
          renderItem={this.renderPage}
          showsHorizontalScrollIndicator={false}
          getItemLayout={(data, index) => {
            const width = Dimensions.get('window').width;
            return { length: width, offset: width * index, index };
          }}
          removeClippedSubviews
          horizontal
          pagingEnabled
          directionalLockEnabled
        />
```
When I make it like this, my list does not render until I scroll, but when I change `getItemLayout` to this:

```
 getItemLayout={(data, index) => {
            const width = Dimensions.get('window').width;
            return { length: 0, offset: width * index, index };
          }}
```

with the length attribute as 0, my list renders perfectly fine, and it scrolls to the end correctly in `componentDidMount`

**Comment by sahrens** [comment]
@huyanhh: that is indeed quite weird. Does it work without the length hack and without removeClippedSubviews?

**Comment by huyanhh** [comment]
@sahrens The list renders fine no matter what removeClippedSubviews is, as long as length is 0. Once I change back length to the screen width, regardless if removeClippedSubviews is turned off or not my list goes back to being blank until scroll.

**Comment by dzuncoi** [comment]
`removeClippedSubviews` does not work for me, although I'm using a very common FlatList, as below:

```javascript
<FlatList
   scrollEventThrottle={200}
   onScroll={e => true}
   ref={ref => this.listRef = ref}
   data={this.state.messageList}
   keyExtractor={item => item.messageId}
   removeClippedSubviews={false}
   renderItem={({item, index}) => {
      return (
          <MessageItem item={item}/>
      )
}}/>
```

Currently, my solution is after retrieving list data, I have to manually scroll down 1px `this.listRef.scrollToOffset({offset: 1})`

But it's still a bug, I think it should only be closed after fixed by a new release.

**Comment by huyanhh** [comment]
@facebook-github-bot reopen

**Comment by joshyhargreaves** [comment]
@dzuncoi, do you think you might be able to put together an example project?

**Comment by dzuncoi** [comment]
@joshyhargreaves will try asap

**Comment by sahrens** [comment]
Why are you setting a useless onScroll property and changing the scroll event throttle? I don't *think* either of those should break anything, but can you double check removing those?

**Comment by dzuncoi** [comment]
@sahrens 
I just minimized `onScroll` property in my comment. Remove those properties does not affect anything. 
After investigating more, `removeClippedSubviews={false}` works for me only if I add `initialNumToRender={myInitialData.length}` either. So my list does not render all items because my initial data size is more than the default number (10) of how many items to render in the initial batch. 

Does it worth to emphasize this in FlatList docs?

**Comment by sahrens** [comment]
That shouldn't be a problem - FlatListExample has an initialNumToRender much smaller than the data size with no issue.

**Comment by dantman** [comment]
@dzuncoi @sahrens Yes, using `initialNumToRender={myInitialData.length}` should never be done and is just hiding the issue by breaking FlatList and turning it essentially into a ScrollView.

That line basically disables all of FlatList's optimization intended to only render a portion of the items that are on screen and forces it to just render every single item in your list at once.

**Comment by dzuncoi** [comment]
@dantman 

> optimization intended to only render a portion of the items that are on screen

So how do FlatList determine how many items will be rendered to fit screen, so that users don't see remaining-not-rendered items, or it just renders 10 items (by default)?
Maybe my problem is now out of this issue's scope.

**Comment by dantman** [comment]
@dzuncoi AFAICT FlatList uses the normal algorithm for this: Render `initialNumToRender` items (10), make sure the screen is full of items, if not render `initialNumToRender` (10) more items until it is, if the user has scrolled do this again to show the newly visible items. Not sure if FlatList does it, but maybe also unmount things that are no longer visible after scroll.

**Comment by dzuncoi** [comment]
@dantman 
I'm quite sure that:
- On Android: I have to use both `initialNumToRender` and `removeClippedSubviews` to get all initial items rendered.
- On iOS: if I use `removeClippedSubviews` only, I must scroll down 1px after retrieving my initial data to get it worked.

**Comment by sahrens** [comment]
@dzuncoi : that is unfortunate, and I have not seen that before. An full repro case would be really helpful.

@dantman: almost, except `maxToRenderPerBatch` is used to fill the screen after `initialNumToRender`. And yes, items outside the render window are unmounted, which is the visible area + buffer, except for the initial items which are never unmounted unless you provide `initialScrollIndex`.

**Comment by huyanhh** [comment]
@joshyhargreaves Here's a GH gist for what I was talking about:

[Trying to scroll to the end on load bug](https://gist.github.com/huyanhh/82fc6df0ffeceb68d538c351651a2748)

**Comment by rcorrie** [comment]
Here is a gif of the behavior. 

![may-25-2017 10-54-41](https://cloud.githubusercontent.com/assets/6488063/26455580/a8d7fe5a-4138-11e7-8002-651a0dbc3bd8.gif)

**Comment by rcorrie** [comment]
Here is a gif
![may-25-2017 10-57-37](https://cloud.githubusercontent.com/assets/6488063/26455720/09856300-4139-11e7-8a4d-42949e216a1e.gif)

**Comment by rogerkerse** [comment]
`initialNumToRender` & `removeClippedSubviews` doesn't seem like a viable answer here, because it removes all the optimisations when you have a huge list full of pictures.

**Comment by tomasfrancisco** [comment]
I'm still experiencing this issue. `removeClippedSubviews={false}` solved the problem for now.

**Comment by xilonxiao** [comment]
I've experienced this too on RN 0.44.2 and it was solved with removeClippedSubviews={false}. Although, as @rogerkerse mentioned, it is not a optimal solution as it seems to remove some important optimisations.

**Comment by Kiarash-Z** [comment]
Hi mine fixed by giving style={{ backgroundColor: 'white' }} to flat list

**Comment by pmcguane** [comment]
this is still happening in 44 with removeClippedSubviews={false} set

**Comment by askarhu** [comment]
I don't think it's baked into the latest FlatList, I still has to force removeClippedSubviews={false}. Don't mind forcing it but would be nice to not have these hacks all around.

**Comment by bensheldon** [comment]
I have been fighting the problem of a FlatList with `horizontal={true}` and `initialScrollIndex` momentarily rendering the content, then blanking out until the view is scrolled again. The FlatList is rendered within a react-navigation StackNavigator.

I found the following combination to work for me:

- calculating `itemLayout` in which `length` is equal to the window width
- explicitly defining a `width` attribute on the top-level component within the `renderitem`.

This is my working component; I hope it's helpful:

```
export default class DetailList extends PureComponent {
  render() {
    return (
      <FlatList
        contentContainerStyle={styles.list}
        data={this.props.shirts}
        getItemLayout={this._itemLayout.bind(this)}
        horizontal={true}
        initialScrollIndex={this.props.showIndex}
        keyExtractor={this._keyExtractor}
        pagingEnabled={true}
        renderItem={this._renderItem.bind(this)}
        showsHorizontalScrollIndicator={false}
      />
    );
  }

  _itemLayout(data, index) {
    const width = this._itemWidth()

    return {
      length: width,
      offset: width * index,
      index,
    };
  }

  _itemWidth() {
    const { width } = Dimensions.get("window");
    return width;
  }

  _keyExtractor(item, index) {
    return item.id;
  }

  _renderItem({index, item: rowData}) {
    return (
      <DetailItem
        index={index}
        shirt={rowData}
        width={this._itemWidth()}
      />
    );
  }
}
```

**Comment by askarhu** [comment]
In my case, it turned out that I had a bunch of container views in the hierarchy that emitted this behavior. Once I cleared all the unnecessary container views it started to behave the way it is supposed to.

**Comment by dotansimha** [comment]
For me, adding `removeClippedSubviews={false}` with rn 0.46 works.
But make sure that you don't have two items with the same id, I had one of those and it caused the issue - fixing it and adding `removeClippedSubviews` works.

**Comment by rudyryk** [comment]
Why the issue is closed?! :) Why `removeClippedSubviews={false}` is considered as working solution?

When you set `removeClippedSubviews={false}` it renders ALL cells even those are out of screen. Now imagine feed with 50-100 images. It will just blow up Android and probably any iOS app.

**Comment by douglasjunior** [comment]
@rudyryk +1

**Comment by douglasjunior** [comment]
@rudyryk +1

Unfortunately they considered it as a solution, see https://github.com/facebook/react-native/commit/3bf7856700ca2b7c20dd358b16a58ef8874f074a

**Comment by YasirPanjsheri** [comment]
Hi, should we limit the fetched list items to be displayed? meaning should I have paginated lists (so we utilize inifiniteScroll) ? are there performance issues (when scrolling for example) when fetching long lists (or all of them (e.g. list of users)) of data and render them.

**Comment by douglasjunior** [comment]
In my case, I do infinite scrolling loading 100 records per time, so I changed the values of `initialNumToRender`, `maxToRenderPerBatch` and `windowSize` to 50.

```jsx
<FlatList
    ...
    initialNumToRender={50}
    maxToRenderPerBatch={50}
    windowSize={50}
/>
```

After loading more than 600 items, if I scroll up quickly, some items appear blank and are quickly loaded again. That was satisfactory to me.

![flatlist](https://user-images.githubusercontent.com/1512341/32145276-ba782c8a-bcac-11e7-9da6-f4b8313966b2.gif)

**Comment by michelalbers** [comment]
@Kiarash-Z fix works ... but why the f*** ? :D

**Comment by jslok** [comment]
This is still an issue in RN 0.49.3 if removeClippedSubviews=true.

**Comment by abeddow91** [comment]
I am having this issue still even with removeClippedSubviews={false}. Any additional solutions here?

**Comment by TasneemBohra** [comment]
I am still having this issue with `removeClippedSubviews = {false}` but then setting it `false` also reducing my rendering performance. 
However, @douglasjunior solution worked perfectly fine for me without compromising performance.
Thanks @douglasjunior  👍

**Comment by jslok** [comment]
https://github.com/facebook/react-native/issues/1831
According to that, the fix was merged in and available for RN 0.50. If you do not want to or cannot upgrade RN yet, you can just change the line as shown in the file.
https://github.com/facebook/react-native/commit/03ae65bc25185fe6d7f62e66f5575ced5c3e8378

On my app, this fix solves the issue and I can still use removeClippedSubviews={true}.

**Comment by FacuAcosta** [comment]
@douglasjunior Sorry to bother, but how did you implement the Activity Indicator while scrolling the FlatList?

**Comment by douglasjunior** [comment]
When fetching the data, render an `ActivityIndicator` as `ListFooterComponent`.  [Example here](https://medium.com/react-native-development/how-to-use-the-flatlist-component-react-native-basics-92c482816fe6).

**Comment by itchingpixels** [comment]
This is still a problem with 0.50.3. removeClippedSubviews don't seem to have any effect. Can we reopen this please?

**Comment by BlakeSimpson** [comment]
Inspired by the comments in this thread from [Kiarash-Z](https://github.com/facebook/react-native/issues/13316#issuecomment-308574176) and [douglasjunior](https://github.com/facebook/react-native/issues/13316#issuecomment-349670990), my fix to this solution was basically:

```jsx
ListFooterComponent={() => {
  return <View style={{backgroundColor: 'transparent', height: 1}} />
}}
```

I could not use a `ActivityIndicator` but it seems RN needs new content to be rendered, even an "invisible" view (Note, with height of zero the bug still existed).

**Comment by yifengwu2018** [comment]
React Native FlatList shows some blank in the quickly sliding. What is the solution?

**Comment by itchingpixels** [comment]
we've migrated over to use https://github.com/Flipkart/recyclerlistview

**Comment by rogerkerse** [comment]
@BlakeSimpson this is good, but again it is not viable solution in the long run because it is basically a hack.

Why is this closed again, if this is not resolved 👎

**Comment by BlakeSimpson** [comment]
@rogerkerse I totally agree. This is a hack and a real solution would be preferable. 

We've recently upgraded to RN 0.52 though and the issue seems to be resolved, so I am removing my hack. Perhaps you can upgrade your React Native version also or just use the hack temporarily until you can?

**Comment by Laurensdc** [comment]
Super weird, when I edited `getItemLayout` to _not_ match my actual item component, it rendered immediately again for me...

``` js
getItemLayout={(data, index) => (
    {
        length: itemWidth - 1, // why does this work
        offset: itemWidth * index,
        index
    }
)}
```

**Comment by Laurensdc** [comment]
I might have resolved it by only passing `initialScrollIndex` if the items would actually go off screen.

```
initialScrollIndex={sortedEntries.length > 5 ? sortedEntries.length - 1 : 0}
```

Feels like this kind of logic should not be necessary.

**Comment by DOHere** [comment]
@bensheldon that solved it for me, thanks!
setting length in getItemLayout to window width worked for me
I had set it before to item length

**Comment by esutton** [comment]
After refactoring to use **FlatList** I must go back to **ListView**.  

None of these solutions work for me.

**ListView** just works.

````
		"react": "^16.2.0",
		"react-native": "^0.53.3",
		"react-native-router-flux": "4.0.0-beta.27",
````

**Comment by DOHere** [comment]
@esutton can you show your FlatList, getItemLayout and css used in the FlatList?

**Comment by esutton** [comment]
@DOHere I am not using the getItemLayout option.

````
  renderRow = ({ item, index }) => {
    const menuItem = item;
    return (
      <MenuItemRow
        menuItem={menuItem}
        onPressMenuItem={this.onPressMenuItem}
        {...this.props}
      />
    );
  }

  render() {
    const { themeStyle } = this.props.state;
    const connecting = (this.state.animating || this.state.connecting)
      ? (<View style={[styles.row, themeStyle.view]}>
        <Text style={[themeStyle.textPrimary, { fontWeight: 'bold' }]}>
          {this.state.progressMessage}
        </Text>
        <ActivityIndicator
          animating={this.state.animating}
          style={[
            styles.centering,
            {
              backgroundColor: themeStyle.textPrimary.backgroundColor,
            },
          ]}
          color={themeStyle.textPrimary.color}
          size="large"
        />
      </View>)
      : null;

    return (
      <View style={styles.listContainer}>
        {connecting}
        <FlatList
          ref={(ref) => { this.listView = ref; }}
          style={themeStyle.view}
          ItemSeparatorComponent={this.renderSeparator}
          data={this.state.dataSource}
          renderItem={this.renderRow}
          refreshing={this.state.animating}
          onRefresh={this.onTrackerScan}
          automaticallyAdjustContentInsets={false}
          keyboardDismissMode="on-drag"
          keyboardShouldPersistTaps="always"
          enableEmptySections
          keyExtractor={this._keyExtractor}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  centering: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  listContainer: {
    flex: 1,
  },
  list: {
    marginTop: 0,
    backgroundColor: '#eeeeee',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderWidth: 0,
    borderColor: '#DDDDDD',
    justifyContent: 'space-between',
  },
  rowSeparator: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    height: 1,
    marginLeft: 4,
  },
  rowSeparatorHide: {
    opacity: 0.0,
  },
  separator: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    height: StyleSheet.hairlineWidth,
    marginVertical: 10,
  },
  separatorHorizontal: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    height: StyleSheet.hairlineWidth,
    marginHorizontal: 10,
  },
});

````

**Comment by DOHere** [comment]
@esutton I suggest you set the height of rows somewhere in css
and also use getItemLayout. Try this:
    ```
  import { Dimensions } from "react-native";
  screenHeight = Dimensions.get("window").height;

  getItemLayout={(data, index) => ({
          length: screenHeight,
          offset: index * <row-height> + ( <row-height> - screenHeight ) / 2,
          index,
        })}
```

**Comment by esutton** [comment]
@DOHere Thank you very much for the tip.

I plan to stay with **ListView** as long as I can.  **FlatList** has wasted *way* too much of my time.

After my experience of migrating multiple components to **FlatList**,  I have had to roll back to **ListView** several times because of rendering not working properly as **ListView** did.

I will keep your advice in mind when I am forced to upgrade to FlatList.

**Comment by roshangm1** [comment]
Still with the FlatList in React Native 0.54. It started happening all of a sudden and it's actually annoying.

**Comment by vdlindenmark** [comment]
Please reopen, same issue in RN 0.54 for me...

**Comment by ArturGr** [comment]
Found a working Hack for this. 
`render() {
        setTimeout(() => {
            this.sectionList && this.sectionList.recordInteraction(); 
        }, 50);
        return (
            <SectionList ref={(view) => { this.sectionList = view }} />
        )
}`

**Comment by wmonecke** [comment]
I dont encounter this error when I install in debugMode. However once I do  `react-native run-android --variant=release` I get this bug. In my case the rows do render but kind of "not fully". The color of the items are sluggish and blend with the background color. 

I have no clue on what to do to fix this. It is really frustrating.

**Comment by wenkangzhou** [comment]
Finally，the only way for me is back to ListView.

**Comment by pyaesone17** [comment]
<Flatlist style={{ flex: 1 }}/> 
This trick work for me without switching to ListView.

**Comment by wenkangzhou** [comment]
Adding` removeClippedSubviews = {false}`works, but it reducing your rendering performance,if you hava a largelist of image,maybe 500 items can lead to crash.

**Comment by milankamilya** [comment]
FlatList is not efficiently maintaining cells of a ListView, instead, you may use Flipkart developed [RecyclerListView]. (https://github.com/Flipkart/recyclerlistview)

Demo: With lots of images, https://snack.expo.io/@naqvitalha/rlv-demo

**Comment by machester4** [comment]
had the same problem, the problem is that the data source is a JSON and therefore will be passed to the reference and not as a value, by modifying that object from any of its references automatically 'Flatlist' will have these new data and for more if we use setState to try to update the flatList, we will not see the changes until we move because Flatlist will already have that data. It's a bit confusing but here I give you a little 'solution'.


```
   // We break the reference by making it immutable 
   let playlistInitial =  JSON.stringify(store.getState().playlist);

    if (playlistInitial != "") {
      this.setState({ playlistInitial });
      AudioController.init(JSON.parse(playlistInitial), 0, this.onChangeStatus);
    }

 <FlatList
     data={this.state.playlist}
     initialNumToRender={5}
     style={{ flex: 1 }}
     horizontal={true}
     showsHorizontalScrollIndicator={false}
     keyExtractor={item => item["key"]}
     renderItem={({ item }) => <RowStationHome data={item} />}
 />
```
