### ISSUE TITLE
[TouchableHighlight + borderRadius] does not respect parent's overflow property/borderRadius?

### ISSUE THREAD

**Issue by josebalius** [facebook/react-native#1342]
Hey guys, 

Ever since I upgraded to 0.4.4, my rounded buttons have a bug in them. I have the following code

```
 <View  style={styles.button}>
       <TouchableHighlight style={{alignSelf: 'stretch', flex: 1}}>
               <Text>My Button</Text>
       </TouchableHighlight>
</View>

var styles = Stylesheet.create({
  button: {
       height: this.props.height,
       flexDirection: 'row',
       backgroundColor: this.props.backgroundColor,
       borderRadius: this.props.borderRadius,
       alignSelf: 'stretch',
       overflow: 'hidden',
       borderWidth: 1,
       borderColor: this.props.borderColor || this.props.backgroundColor,
       flex: 1
  }
});
```

The button looks great on its own but whenever you touch it, and the highlight comes in, it shows with square corners going outside of the buttons boundaries (hard to take a screenshot of).

This was working fine in 0.4.2. I have also tried matching the borderRadius style property on the TouchableHighlight component and it seems to have no effect, again in 0.4.2 it did.

Any ideas?

**Comment by DaZzz** [comment]
Try setting the same borderRadius property to TouchableHighlight.

**Comment by josebalius** [comment]
@DaZzz I did and no luck, it still renders with square corners. Any other ideas?

**Comment by brentvatne** [comment]
@josebalius - thanks for the report!

@a2 - here's a [runnable demo of the bug](https://rnplay.org/plays/OHmCJQ?autoplay=true)

**Comment by txixyo** [comment]
Any update on this? :) I'm still having this problem.

**Comment by josebalius** [comment]
@txixyo I am seeing this fixed with 0.6.0 which version of RN are you using?

**Comment by brentvatne** [comment]
Looks fixed to me!

**Comment by shahankit** [comment]
@brentvatne I'm still facing this issue even for normal View and suspect that the issue is because of `alignSelf: 'stretch'`. Any solutions to this?

**Comment by flavordaaave** [comment]
@shahankit I solved this by adding `underlayColor={ 'transparent' }` to the TouchableHighlight. So my full example:

```
const styles = StyleSheet.create({
  touchableHightlight: {
    borderRadius: 20,
  },
  button: {
    textAlign: 'center',
    padding: 10,
    borderRadius: 20,
    fontSize: 14,
  },
  buttonLight: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    color: '#FFFFFF',
  },
})

...

<TouchableHighlight onPress={ () => { onPress } } style={ styles.touchableHightlight } underlayColor={ 'transparent' } >
  <Text style={[ styles.button, styles.buttonLight ]}>{ label }</Text>
</TouchableHighlight>

...

```

**Comment by RohanGada** [comment]
@flavordaaave I tried, didn't work for me. I am on react-native ver. 0.50.4

**Comment by BuilderX** [comment]
Awesome, just using underlayColor worked for me, it removed the black square that would appear whenever I pressed my button, thank you@flavordaaave .

**Comment by digitaltoad** [comment]
This still seems to be a bug. Setting `underlayColor: 'transparent'` isn't really a fix because its removing part of the reason for using this type of view. The problem can be partially remedied by wrapping the `TouchableHighlight` in a `View` which has a `borderRadius` and `overflow: 'hidden'`.

```jsx
<View style={{borderRadius: 5, overflow: 'hidden'}}>
    <TouchableHighlight onPress={() => console.warn('Pressed!')}>
        <View style={{height: 48, alignSelf: 'stretch', justifyContent: 'center', backgroundColor: '#2196F3'}}>
            <Text>Click me!</Text>
        </View>
    </TouchableHighlight>
</View>

**Comment by raymondchooi** [comment]
Still seems like a bug to me on RN `v0.52.2`. If a `FlatList` has rounded borders with a `TouchableHighlight` as an Item, the border radius is not respected.

The solutions above do not quite work here as any middle items would also have rounded borders when they are meant to be rectangular.

For a workaround, I've edited the styles for only the first and last elements of the list.
