### ISSUE TITLE
Elements laid out in flex sometimes have blank pixel separating them

### ISSUE THREAD

**Issue by kpink224** [facebook/react-native#13492]
### Description

If multiple elements are created - each of which flex to parent width - and the parent is provided with a width that doesn't divide evenly among the children, there will be gaps between the children.

![screenshot_20170413-132932](https://cloud.githubusercontent.com/assets/9455356/25016614/c95cf42e-204e-11e7-9a5a-6ded6d7886e3.png)

### Reproduction Steps and Sample Code

Create a parent view with odd width and render even number of children (flex = 1 each) inside of it. 
 - This is easier to see on lower resolution screens.
 - We reproduced this using element background in addition to using borderTop

https://snack.expo.io/Sy6HJDT6e

### Solution

The extra pixels should be distributed to some of the children evenly.

### Additional Information

* React Native version: 0.43.3
* Platform: Android and iOS
* Development Operating System: MacOS

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by kpink224** [comment]
@hramos This shouldn't be closed. It is still an issue on 0.46.1 and has been attempted a few times with no luck.

There were two commits attempting to fix this that I could remember (one of which I can't find the link to but it was after this one):
https://github.com/facebook/react-native/commit/a8fa90417931a24308875a617bd5fe96606f8261
