### ISSUE TITLE
VirtualizedList populated with getItem() only displaying the first 10 items

### ISSUE THREAD

**Issue by agmathew** [facebook/react-native#13509]
### Description

When populating a `VirtualizedList` using `getItem()` (i.e. not using `data`), the list only shows the first 10 items even if `getItemCount()` returns a number more than 10. This seems to happen irrespective of the setting of `initialNumberToRender` and `windowSize`.  I'd expect that you would be able to see all items in the list.

### Reproduction Steps and Sample Code

```
export default class ListTest extends Component {
  render() {
    return (
      <View>
        <VirtualizedList
          initialNumberToRender={20}
          windowSize={21}
          getItemCount={(data) => 365}
          getItem={(data, index) => {
            return { key: index };
          }}
          keyExtractor={(item, index) => {
            return item.key;
          }}
          renderItem={({ item, index }) => {
            return (
              <View style={{height:50}}>
                <Text>{item.key}</Text>
              </View>
            );
          }}
        />
      </View>
    );
  }
}
```

### Solution

I peeked at the source code, but couldn't find a clear fix.

### Additional Information

* React Native version: 0.43.3
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: XCode 8.2.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by gastonmorixe** [comment]
+1

**Comment by gastonmorixe** [comment]
The property is called `initialNumToRender` not `initialNumberToRender` this is the first thing I have noticed that affects this issue. Still not resolved yet.

**Comment by MohamedOsman1998** [comment]
+1 this issue should be reopened

**Comment by gastonmorixe** [comment]
guys, you need to pass a `data` prop , either an array or your custom class and use it accordingly. `data` is mandatory.

**Comment by rmarimon** [comment]
Adding `data={[]}` to the example seems to solve the problem.
