### ISSUE TITLE
KeyboardShouldPersistTaps cannot dismiss while letting children handle tap

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#13875]
I'm trying to set up a comment section in my app and I need to be able to dismiss the keyboard and post the comment with one tap. Currently there is no way that keyboardShouldPersistTaps can do this. Would be great if we could get a fourth option to keyboardShouldPersistTaps that can dismiss the keyboard while still letting the children handle the tap, that way I can press one time on my submit button and have the app get rid of the keyboard and submit my comment.

React-Native 0.41.0

**Comment by guigrpa** [comment]
Have you tried with `keyboardShouldPersistTaps: 'handled'` and letting the button's `onPress` handler call `Keyboard.dismiss()`?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by lanjinglingxx** [comment]
I hope that this issue will remain open. I have encountered the same problem and I still cannot solve it.

**Comment by cr21** [comment]
same problem   facing this issue again
