### ISSUE TITLE
border radius makes outline

### ISSUE THREAD

**Issue by lucduong** [facebook/react-native#13884]
### Description

I tried to make the circle with white border:

Style:

```
circle: {
    position: 'absolute',
    borderWidth: 10,
    borderColor: '#fff',
    top: 20,
    left: 30,
    width: 150,
    height: 150,
    borderRadius: 150 / 2,
    backgroundColor: '#ED1D27',
  }
```

View:

`<View style={styles.circle}></View>`

The result is:

![White border](https://i.stack.imgur.com/nB832.png)

There is and outline rounded the circle.

I don't want that outline. I checked by remove the border radius and it has no outline like below:

![Border without outline](https://i.stack.imgur.com/TkFEw.png)

My stack overflow question here:
http://stackoverflow.com/questions/43756623/react-native-border-radius-makes-outline/43839327#43839327

### Additional Information

* React Native version: latest
* Platform: iOS
* Development Operating System: macOS
* Dev tools: VSCode

**Comment by adrianlemess** [comment]
I had the same issue too! 
![image](https://user-images.githubusercontent.com/12432777/27046158-bf03bf08-4f79-11e7-8b41-5d411203fdea.png)

I don't want the bottom line! 

Additional Information

React Native version: latest RC
Platform: Android
Development Operating System: Windows
Dev tools: VSCode

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by jdmunro** [comment]
This is still occurring on React Native 0.51 (tested natively on device).

I've created a repro of @lucduong's original example above using Expo: https://snack.expo.io/r1DFEvbGf

Here's a screenshot of the issue on device. It's easier to see on an actual device screen because the aliasing in the Appetize preview smooths out the real issue:

![img_6943](https://user-images.githubusercontent.com/17656/34047842-820645f4-e1a9-11e7-9e69-e8e737f12675.PNG)

Possibly related to sub-pixel alignment or maybe a rounding error in the layout code?
