### ISSUE TITLE
allowFontScaling is not working for android

### ISSUE THREAD

**Issue by tatva-nisarg** [facebook/react-native#13944]
`allowFontScaling `is not working for android

RN version: 0.39.0

**Comment by parkerdan** [comment]
That's because it wasn't a part of react-native .39 for Android...it was iOS only on that version

**Comment by tatva-nisarg** [comment]
Any alternative?

**Comment by tatva-nisarg** [comment]
Ok can you please suggest which version i need to be Upgrade?

**Comment by andyscraven** [comment]
I am interested in this issue also.  I am running RN 0.40.0 and it still has the issue.  Which version has the fix?  Thanks.

**Comment by parkerdan** [comment]
You can change the version in the docs on the top left and find this easily...

<img width="923" alt="screen shot 2017-06-29 at 7 26 05 am" src="https://user-images.githubusercontent.com/12119980/27687382-486bd5f8-5c9c-11e7-8196-dcb9c4986d41.png">

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by llamaluvr** [comment]
This is still a problem as of RN 52 / Expo 25.

I have created a Snack demonstrating the issue here: https://snack.expo.io/@llamaluvr/android-textinput-allowfontscaling-not-respected

Reproduction steps:
1. Place a TextInput
2. Set placeholder prop
3. Set allowFontScaling=false
4. On Android, go to Settings-> Accessibility and turn on "Large Text".
5. Run the app on Android. Look at the placeholder and type something in the TextInput.

Expected behavior:
The TextInput's text and placeholder should be the same size when "Large Text" is turned on and when it is turned off.

Actual behavior:
The TextInput's text and placeholder is larger when "Large Text" is turned on, despite allowFontScaling=false.
