### ISSUE TITLE
[FlatList] Item remain grey after pressed on it on android

### ISSUE THREAD

**Issue by dbertella** [facebook/react-native#14048]
### Description

I have a FlatList with TouchableHighlight as items, when press on them they remain dark grey until the next refresh

### Reproduction Steps and Sample Code

```
<FlatList
  data={[{key: 'a'}, {key: 'b'}]}
  renderItem={({item}) => <TouchableHighlight><Text>{item.key}</Text></TouchableHighlight>}
/>
```
On iOS seems to work correctly.

### Possible solution
More a workaround then a solution, switched to TouchableOpacity seems to work ok.

### Additional Information

* React Native version: 0.44.4
* Platform: Android
* Development Operating System:  macOS

**Comment by kevinfez** [comment]
In their FlatList example they use the [extraData](https://facebook.github.io/react-native/docs/flatlist.html#extradata) prop to pass in selection state, and when that state mutates then the table will also refresh, perhaps that's the intended way to do this? Although I can confirm that TouchableOpacity will animate on press down and on press up.

**Comment by dobrienlzd** [comment]
Is item coming from an Array stored as state?  I think maybe no updates on property changes vs. state changes? Might have something to do with it ...

**Comment by dbertella** [comment]
In my case the array comes from store, not local state involved

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by mateen-hussain** [comment]
I still see this issue.

I have a toucableHighlight within a FlatList and when I select the TouchableHighlight Item, it navigates to the next screen. But when I go back, the item remains pressed/selected. 

This seems to happen recently.
