### ISSUE TITLE
Image.getSize() cannot detect portrait image

### ISSUE THREAD

**Issue by louiscenter** [facebook/react-native#14097]
### Description

Passed uri of newly captured portrait photo (960 x 1280) from iOS camera roll into Image.getSize(). Expected to receive `width: 960, height: 1280` from the callback, but instead received `with: 1280, 960`. 

Image.getSize() does not take into account any orientation data stored in the image file.

### Reproduction Steps and Sample Code

```js
// data.uri portrait photo taken with iOS Camera
Image.getSize(data.uri, (width, height) => {
  // width === 1280 (should be 960)
  // height === 960 (should be 1280)
})
```

### Solution

Image.getSize() should take into account whether the image has any orientation metadata before assigning values to width & height variables. Unsure how to do a PR for this.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Xcode

**Comment by stobe1** [comment]
i had this same problem using `react-image-picker` package.
The problem was that photo taken with this plugin would have a somewhat `rotate` param. And it is rotated correctly while displaying in <image />, but when i tried to get a .imageSize from it, it would have swapped width and height.
I found a workaround tho: you can include this `originalRotation` value in response that you get after taking a photo and than work with that.
hope that helps
https://github.com/react-community/react-native-image-picker/pull/388/files#diff-e2ac0feb8ce151bd872a7c4ab6b4801d

**Comment by mlg87** [comment]
@louiscenter have you found a solution for this? im experiencing the same behavior with remote images stored in cloudinary originally taken using `react-native-camera`

**Comment by shergin** [comment]
@doochik Did we fix that?

**Comment by doochik** [comment]
Yes, this bug is fixed in https://github.com/facebook/react-native/pull/15060 and will be shipped in September 2017, I suppose.

**Comment by shergin** [comment]
@mlg87 @louiscenter Could you please verify that the problem was fixed in master?

**Comment by AntiPaste** [comment]
@shergin It seems this did not fix the problem. The attached image returns `600, 338` as width and height respectively when using `Image.getSize()` even though the image actually has `338, 600` as width and height respectively.

On Android the width and height are calculated correctly.

Tested on React Native 0.48.0-rc.1 / iOS / macOS / Xcode.

![preview](https://user-images.githubusercontent.com/4379220/29709882-d2d7adee-8996-11e7-903b-a596c1ce8b6c.jpg)

**Comment by mlg87** [comment]
@shergin sorry for not responding sooner. we ended up forking RN bc we needed to deliver what we were working on, but we went into `RCTImageLoader.m` and changed the `getImageSizeForURLRequest` method to this:
```
- (RCTImageLoaderCancellationBlock)getImageSizeForURLRequest:(NSURLRequest *)imageURLRequest
                                                       block:(void(^)(NSError *error, CGSize size))callback
{
  void (^completion)(NSError *, id, BOOL, NSString *) = ^(NSError *error, id imageOrData, BOOL cacheResult, NSString *fetchDate) {
    CGSize size;
    if ([imageOrData isKindOfClass:[NSData class]]) {
      NSDictionary *meta = RCTGetImageMetadata(imageOrData);
      double orientation = [meta[(id)kCGImagePropertyOrientation] doubleValue];
      if (orientation == 1) {
        size = (CGSize){
          [meta[(id)kCGImagePropertyPixelWidth] doubleValue],
          [meta[(id)kCGImagePropertyPixelHeight] doubleValue],
        };
      } else {
        size = (CGSize){
          [meta[(id)kCGImagePropertyPixelHeight] doubleValue],
          [meta[(id)kCGImagePropertyPixelWidth] doubleValue],
        };
      }
    } else {
      UIImage *image = imageOrData;
      size = (CGSize){
        image.size.width * image.scale,
        image.size.height * image.scale,
      };
    }
    callback(error, size);
  };

  return [self _loadImageOrDataWithURLRequest:imageURLRequest
                                         size:CGSizeZero
                                        scale:1
                                   resizeMode:RCTResizeModeStretch
                                progressBlock:NULL
                             partialLoadBlock:NULL
                              completionBlock:completion];
}
```

**Comment by shergin** [comment]
We actually have to swap `height` and `weight` for `orientationValue >= 5`... but we have to use constants from `kCGImagePropertyOrientationUp` family though.
@mlg87 @doochik PR is welcome! 😄

**Comment by doochik** [comment]
You're welcome :)
https://github.com/facebook/react-native/pull/15690

**Comment by rijk** [comment]
So.. was this merged? In which RN version is/will this fix be released?

**Comment by shergin** [comment]
@rijk Yes, it was merged/fixed. I am not sure about the version.
