### ISSUE TITLE
lineHeight styling doesn't impact multiline TextInput

### ISSUE THREAD

**Issue by florianpnn** [facebook/react-native#14232]
### Description
lineHeight styling doesn't impact TextInput when multiline is set to `true`

### Reproduction Steps and Sample Code
![kapture 2017-05-28 at 1 48 28](https://cloud.githubusercontent.com/assets/2725387/26525009/eba6d6fe-4348-11e7-9270-45a3c754e111.gif)

```javascript
<TextInput
    multiline={true}
    style={{
        lineHeight: fontLineHeight,
    }}
/>
```

### Additional Information
* React Native version: 0.44.0
* Platform: iOS (didn't test on Android)

**Comment by florianpnn** [comment]
@shergin thanks for taking care of that 👍

**Comment by Amaros90** [comment]
I'm encountering this issue on iOS, but not on Android

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by shergin** [comment]
I still plan to fix this. 😄

**Comment by pie6k** [comment]
Any update? I'm writing kind of WYSIWYG editor, and my approach is that I'm creating 'fake' elements that imitate whats inside text edit with styles. Thats why I need very solid control over line height.

**Comment by statelo** [comment]
Still having this issue though :(((

**Comment by steobrien** [comment]
In advance of a real fix here, any suggestions to work around?

**Comment by drpiou** [comment]
Same here with RN 0.51.

**Comment by shergin** [comment]
It should be fixed in master now! Can anybody confirm?

**Comment by crystalloo** [comment]
@shergin Still seems not fixed for 0.53, correct me if I'm using it wrong

screenshot:
![simulator screen shot - iphone 6 - 2018-02-08 at 16 43 38](https://user-images.githubusercontent.com/18043110/35963319-53477b5e-0cef-11e8-8f58-635b2d3fe2ee.png)

code:
```
      <View style={styles.container}>
        <Text
          style={{
            lineHeight: 40,
            borderWidth: 1,
            marginBottom: 10
          }}
        >Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!</Text>
        <TextInput multiline placeholder='placeholder'
          style={{
            lineHeight: 40,
            borderWidth: 1,
            width: width - 10,
            backgroundColor: 'pink'
          }}
        />
      </View>
```

**Comment by steobrien** [comment]
@shergin Yes! I've tested my app out on latest React Native master, and I can confirm this is fixed. Thank you 🙌

Note to others: not fixed in any React Native releases yet including 0.53.

**Comment by hramos** [comment]
Fixed in master.

**Comment by ArsenyYankovsky** [comment]
Are you sure this is fixed? I'm getting this using 0.57 on iOS.

![photo_2018-11-18_02-38-24](https://user-images.githubusercontent.com/1508345/48667624-0f494e80-eadb-11e8-8952-5c2b0e3600cd.jpg)

```
        <TextInput
          style={styles.storyText}
          multiline={true}
          keyboardType="default"
          placeholder="Your Message"
        />
```

```
  storyText: {
    fontSize: 18,
    marginTop: 18,
    fontFamily: 'noto-sans',
    color: '#444',
    lineHeight: 25.2,
    textAlign: 'left',
    backgroundColor: '#fff',
  },
```

**Comment by ArsenyYankovsky** [comment]
Are you sure this is fixed? Getting this using 0.57 and iOS:

![photo_2018-11-18_02-38-24](https://user-images.githubusercontent.com/1508345/48667633-520b2680-eadb-11e8-9f7b-4b22c9ce107f.jpg)

```
  storyText: {
    fontSize: 18,
    marginTop: 18,
    fontFamily: 'noto-sans',
    color: '#444',
    lineHeight: 1000,
    textAlign: 'left',
    backgroundColor: '#fff',
  },
```

```
        <TextInput
          style={styles.storyText}
          multiline={true}
          keyboardType="default"
          placeholder="Your Message"
        />
```

**Comment by hramos** [comment]
@ArsenyYankovsky can you verify 0.58.0-rc and open a new issue if it's reproducing there?

**Comment by martinchristov** [comment]
Issue persists on RN 0.57.7

**Comment by leiz-me** [comment]
@hramos @shergin 
Just updated to RN 0.58.0-rc.3, and confirmed that issue is still here.

```
        <TextInput
          underlineColorAndroid={'transparent'}
          style={styles.contentInput}
          autoCapitalize='none'
          autoCorrect={false}
          placeholder={'placeholder'}
          multiline={true}
          ref={input => { this.textInput = input }}
          onChangeText={this._onChangeText}
          inputAccessoryViewID={inputAccessoryViewID}
          onSelectionChange={this._onSelectionChange}
          value={this.state.content}
        />

  contentInput: {
    flex: 1,
    margin: 5,
    fontSize: ITEM_CONTENT_FONT_SIZE,
    textAlignVertical: 'top',
    // lineHeight: ITEM_CONTENT_FONT_SIZE * 1.5
    lineHeight: 60
  },
```

Please correct me if I am using it wrong.

**Comment by hramos** [comment]
@martinchristov can you verify 0.58-rc and open a new issue if it's not resolved in the RC?
