### ISSUE TITLE
Scrollview doesn't scroll enough when content changes

### ISSUE THREAD

**Issue by xght** [facebook/react-native#14233]
### Description

On IOS, I've got a ScrollView in which the content can change.
When I scroll to the end and the size of the content decreases, the scrollview doesn't scroll enought up. (see the example bellow). 

### Reproduction Steps and Sample Code
Sample code:
```
import React, { Component } from 'react';
import { ScrollView, View, TouchableOpacity } from 'react-native';

export default class Demo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      draw: true,
    };
  }
  render() {
    return (
      <ScrollView style={{ flex: 1 }}>
        <View style={{ height: 800, backgroundColor: 'blue' }} />
        {this.state.draw &&
          <TouchableOpacity
            style={{ height: 300, backgroundColor: 'red' }}
            onPress={() => this.setState({ draw: false })}
          />
        }
      </ScrollView>
    );
  }
}
```

And the snack:
[Snack example](https://snack.expo.io/H1-7smOb-)

On IOS, when you scroll to the end and click on the red touchable, the result is:
<img width="276" alt="screen shot 2017-05-28 at 12 51 38" src="https://cloud.githubusercontent.com/assets/16802551/26528143/482b0908-43a4-11e7-8963-9a080db4ad16.png">

The expected behaviour is (like on android):
<img width="346" alt="screen shot 2017-05-28 at 12 52 21" src="https://cloud.githubusercontent.com/assets/16802551/26528145/5919cf06-43a4-11e7-961d-0354998c2ebf.png">

### Solution

As a workaround, I keep the last scrollPosition, and I use onContentSizeChange to scroll up if needed.

The size of the scroll error is approximately the size of the IOS status bar. Maybe it's linked.

### Additional Information

* React Native version: 0.44.2
* Platform: Only IOS, works great on Android

**Comment by shergin** [comment]
Probably related to https://github.com/facebook/react-native/issues/13566.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by xght** [comment]
@shergin 
Just to let you know that the issue is still present on master, whereas #13566 is apparently corrected.

**Comment by shergin** [comment]
I will fix it.
