### ISSUE TITLE
[0.44] share on iOS does not utilize title

### ISSUE THREAD

**Issue by dmackinn** [facebook/react-native#14607]
The subject line for e-mail share on iOS does not populate. Message populates correctly
```
import { Share } from 'react-native';
import TextWithEntities from '../Transforms/TextWithHTMLEntities';

const shareWithOptions = (message, url, blurb) => {
  let deviceMessage = TextWithEntities(blurb);

  Share.share({
    message: deviceMessage,
    title: message,
    url: url
  });
};

export { shareWithOptions };
```

* React Native version: 0.44
* Platform: iOS 10.3.2
* Development Operating System: macOS
* Build tools: Xcode 8.3.3

Expected behavior: subject line should populate using title from share()

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by WaldoJeffers** [comment]
This issue is still happening, tested on React Native v0.47.2.

**Comment by dmackinn** [comment]
@hramos can we get this re-opened?

**Comment by WaldoJeffers** [comment]
@hramos This should be re-opened. This is clearly a bug, and it's very easy to reproduce it.

**Comment by hramos** [comment]
I won't be reopening this issue as it does not contain sufficient information as required by the template. You may open a new one.

**Comment by WaldoJeffers** [comment]
Yup, I'd be happy to continue this discussion [here](https://github.com/facebook/react-native/issues/16002) @hramos :)
