### ISSUE TITLE
Infinite loop when passing {} as data for FlatList

### ISSUE THREAD

**Issue by JulioC** [facebook/react-native#14707]
### Description

If you pass a non-array object to `FlatList` `data` property, ReactNative javascript thread gets stuck in a infinite loop, due to `FlatList._getItemCount` returning `NaN`.

### Reproduction Steps

Pass any object that doesn't has `length` property to `FlatList`. 

#### Sample Code

https://snack.expo.io/BJrFCR9QZ

Simply: `<FlatList data={{}} />`

### Solution

Change `FlatList._getItemCount` to test for the `data.length`:

```js
_getItemCount = (data: ?Array<ItemT>): number => {
  return (data && data.length) ? Math.ceil(data.length / this.props.numColumns) : 0;
};
```

https://github.com/facebook/react-native/blob/master/Libraries/Lists/FlatList.js#L470

### Additional Information

* React Native version: "0.44.0",
* Platform: any

**Comment by hramos** [comment]
@facebook-github-bot label icebox

**Comment by strindhaug** [comment]
This but is certainly not fixed yet in 0.52.0

I noticed this bug because the unreliable API our customer had built randomly returned objects instead of arrays for some lists (probably because in PHP arrays are really what we'd call objects in javascript). And this froze the app completely each time a flatlist was fed an object.

Either the flatlist should tolerate objects and behave as if fed an empty array possibly logging a warning; or it should throw an exception so that the app can crash properly. Making the app unresponsive without an error message is not good.

And it's really annoying to have to safeguard every usage of a FlatList with a length check something like this:
```jsx
  {uglyApiResponse.listOfSomething.length > 0 ? (
    <FlatList
      data={uglyApiResponse.listOfSomething}
      keyExtractor={item => item.id}
      renderItem={({ item }) => (
        <SomethingLine data={item} />
      )}
    />
  ) : (
    <Text>
      ERROR: Invalid format of uglyApiResponse.listOfSomething expected array
    </Text>
  )}
```
just to avoid an unresponsive app when the API serves garbage

**Comment by strindhaug** [comment]
Weird, i tried to make a synthetic test to force the problem now that the API is fixed, and it seems there is some kind of check when you try to supply a literal object like in the description here or a variable assigned to an object. (Mabe because it's somehow optimized away by the js engine when written like this?):
```jsx
// This seems to work ok:
const ExampleScreen = props => {
  return <FlatList data={{}} />;
};
```

```jsx
// This seems to work ok as well:
const ExampleScreen = props => {
  const somedata = {};
  return <FlatList data={somedata} />;
};
```

But it still goes into an infinite loop if you use an attribute that happens to be an object:
```jsx
// This causes infinite loop and 100% cpu usage:
const ExampleScreen = props => {
  const somedata = {
    someattribute: {},
  };
  return <FlatList data={somedata.someattribute} />;
};
```

**Comment by hramos** [comment]
Please submit a new issue if this is still happening in v53.

**Comment by Benzer1406** [comment]
The issue still exists. It enters into an infinite loop:

` var pendingList = [
   {id: 'estudiar', status: false},
   {id: 'leer1', status: false},
   {id: 'jugar', status: false},
   {id: 'netflix', status: false},
 ];
 const extractKey = ({id}) => id;

export default class FlatList extends Component {

  render () {
    return (
      <View>
        <Text>HELLO</Text>
         <FlatList>
          style={style.container}
          data={pendingList}
          renderItem={({item}) => <Text> Each item is: {item.id}</Text>}
          keyExtractor = {extractKey}
        </FlatList> 
      </View>
    );
  }
}`

react-native-cli: 2.0.1
react-native: 0.53.3

If there is a new issue opened please tell me which one.

**Comment by strindhaug** [comment]
@Benzer1406 No, I haven't bothered to create a new issue, yet. I started looking at the source myself and try to see if I could fix it myself.

Unfortunately the tests run by `npm test` doesn't seem to be testing the actual execution of the code, and the flow tests `npm run flow` seems to be testing type information code that seems to be ignored when the actual code is executed.

The tests for the List library seems to mock (too) much of the actual execution; and it seems to be content if the `FlatList` tag is somehow translated into a `RCTScrollView` and this conversion by `ReactTestRenderer.create` does not seem to invoke the infinite loop bug.

The flow tests seem to cause errors about bad datatype when the data property is not an array; while in production code you can put all sort of junk in that property and it will either work (if it's a valid array) or either an empty list or infinite loop if it's not; no warnings is ever produced as long as it's not `null`. 

I have to  somehow figure out a way to write a test that actually causes the infinite loop (that I know is still there) so that I can verify that any fix actually fixes the problem.

**Comment by Benzer1406** [comment]
@strindhaug  Thanks for your detailed answer. Yes, I was figuring out and pondering about the fact that the problem was indeed an issue of a bad datatype. I could just figure out up to that point and reiterate the loop, but have no idea what it causes or what needs to be done to get out of the loop. 
Meanwhile I changed to the classic `<ListView>` even though it is deprecated, but at least it works.
