### ISSUE TITLE
[Android] TouchableNativeFeedback's ripples aren't affected by borderRadius when useForeground is true

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#14798]
Related issue: https://github.com/facebook/react-native/issues/6480 -- this was resolved with `useForeground={false}`, but borderRadius of parent is not respected when `useForeground={true}`.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yup!

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: 7.9.0
3. `npm -v`: 4.6.1
4. `yarn --version` (if you use Yarn): 0.24.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Unrelated

### Steps to Reproduce

See the demo / description below.

### Expected Behavior

When using `TouchableNativeFeedback` with `useForeground`, I expect the ripple to be clipped when there are rounded corners on the parent container. This is how it works if `useForeground={false}`.

### Actual Behavior

The ripple is not clipped when `useForeground` is enabled and the parent has a borderRadius.

![screenshots](https://user-images.githubusercontent.com/90494/27764689-42ef3eda-5e54-11e7-8c8f-34bf5d115ed7.png)

### Reproducible Demo

https://snack.expo.io/BkLe1uSEZ

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by rumax** [comment]
+1 The issue is still actual. Can be reproduced with 

> "react-native": "^0.47.1"

Meantime the `useForeground={false}` works as expected.

**Comment by luiseduardobrito** [comment]
Although this is clearly not a priority, it's still relevant. Don't think it should be Stale.

**Comment by waquidvp** [comment]
There is a work around in React Native v 0.51 and v 0.50/ Expo v 24.0 and v 23.0, you can set `overflow: 'hidden'` on the parent view of the `<TouchableNativeFeedback >`. You can see the example here: https://snack.expo.io/H17_STXXz
