### ISSUE TITLE
Inconsistent text behavior in TextInput between iOS and Android

### ISSUE THREAD

**Issue by davidlongest** [facebook/react-native#14845]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.45.1
```
(edit: it reproduces in 0.54.2 according to the comments -@hramos)

2. `node -v`: `v7.7.2`
3. `npm -v`: `4.1.2`
4. `yarn --version` (if you use Yarn): `N/A`

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra 10.12.5
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android Studio 2.3.2. Compile SDK 23. Build tools 23.0.1

### Steps to Reproduce

1. Create a TextInput that fits 100% width of the screen
2. Set the TextInput's `value` to a string that will render larger than the width of the text view
3. Run in Android and note which part of the string renders
4. Run in iOS and note which part of the string renders

### Expected Behavior

Both iOS and Android should exhibit the same behavior and display the beginning of the text when unfocused.

Ideally, the ellipsis should also be an optional parameter to display when unfocused on both Android and iOS.

### Actual Behavior

iOS displays the beginning of the text, ellipsizing the remaining text before truncating.

<img width="355" alt="screen shot 2017-07-05 at 5 51 34 pm" src="https://user-images.githubusercontent.com/5114282/27887291-05e786a2-61ae-11e7-9642-0327d6f4df24.png">

Android displays the end of the text with no ellipsis at the beginning.

<img width="400" alt="screen shot 2017-07-05 at 5 51 11 pm" src="https://user-images.githubusercontent.com/5114282/27887302-0fab685c-61ae-11e7-8eb2-88a59488afae.png">

### Reproducible Demo

Example project: https://snack.expo.io/S1Lty1oN-
To view the issue, launch the example project and preview in Android. Then preview in iOS. Note the differences between where ellipsis show and which part of the sentence displays.

**Comment by davidlongest** [comment]
This seemed similar to #12322 but I felt this was different since this is about ellipsizing and the difference between iOS and Android in which part of the text displays as opposed to two different TextInputs on Android displaying differently.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by scottmas** [comment]
Yes, I can confirm this is still happening on the latest version of React Native.

**Comment by hramos** [comment]
v0.53 or v0.54?

**Comment by scottmas** [comment]
Oh, my mistake. It is happening in v0.52

**Comment by scottmas** [comment]
I can't confirm whether it is or isn't happening in v0.53 or v0.54

**Comment by chunshien** [comment]
0.54.2 still having the same issue

**Comment by hramos** [comment]
@

**Comment by ashwanipayal** [comment]
I am facing this issue too.

**Comment by peterdoboz** [comment]
Is there any updates for this issue ?

**Comment by quadsurf** [comment]
I can confirm that this is happening on both RN52 and RN54. In Android, this essentially forces the user to read from right to left. Note to Google, in English, we start reading from left to right. In English, we don't start at the end of a sentence and then work our way backwards. This isn't Arabic or Hebrew. I'm baffled why Android would have this as their default... this shouldn't be something the RN team should have to override. I get that Android serves an international audience, but the default should support the more/most common languages' settings.
@andhie @XinyueZ @tiembo

**Comment by andhie** [comment]
Hi @quadsurf,
not sure why you would tag me as i'm not part of Google or Android team.
but to answer your question. i could not reproduce the issue you mentioned. Thus i can only conclude its React Native issue.

```xml```
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:ellipsize="end"
    android:maxLines="1"
    android:text="@string/text"
    android:textAppearance="?android:textAppearanceLarge"
    tools:context=".MainActivity" />
```

![screenshot_1534611032](https://user-images.githubusercontent.com/3997169/44301477-2cd71280-a34a-11e8-8646-b3f46f01f4d8.jpg)

**Comment by MickaelNeves** [comment]
0.57.1 still having this issue. Very sad behavior if we have a long text in Android.

**Comment by MickaelNeves** [comment]
Any update on this?

**Comment by celineotter** [comment]
0.56.1 still having this issue.

**Comment by hramos** [comment]
@celineotter 0.56.1 is pretty old - did you try the 0.58 RC?

**Comment by FRizzonelli** [comment]
@hramos @cpojer This is still happening on latest 0.59 and 0.60. I see that you moved it to Triage Group but it's marked as closed.

Is there any ETA on this fix? Or at least a workaround we can use. _numberOfLines_ isn't helping, and also _selection_ property isn't perfect and you can't add ellipsis.

**Comment by barakoles** [comment]
This is quite bad.. no solution so far

**Comment by felire** [comment]
Why did you close the issue? It's still happening

**Comment by acoutts** [comment]
Still an issue in 0.61.2 as well.

**Comment by MaxInMoon** [comment]
On RN 61.5, setting this prop:

```js
selection={{
  start: 0,
}}
```

will do the good display (if not focused), but on focus, the cursor will be at start instead of at end.
A possible solution would be to control the [selection](https://facebook.github.io/react-native/docs/textinput#selection) object with [onSelectionChange](https://facebook.github.io/react-native/docs/textinput#onselectionchange) and the onFocus event.

Not so sexy but it could maybe work.

**Comment by NelsonBrandao** [comment]
Any news on this?

**Comment by Sargnec** [comment]
Dont we have solution for this yet?

**Comment by IlinIgor** [comment]
This is still an issue in 0.61.5, is any news on this?

**Comment by prios-paul-burt** [comment]
I am having this issue as well on "react-native": "0.61.5"

**Comment by fabriziobertoglio1987** [comment]
> th

```java
  @Override
  public void setSelection(int start, int end) {
    super.setSelection(start, end);
  }
```
by settings the cursor position, you automatically scroll the `TextInput`, but this is not a good solution to this problem.

I know how to solve this and I have a pr ready for it, but I want to quickly look in the root issue of this problem.

Why are we scrolling to the end of the `EditText` onLoad ?? Did we override some default functioanlities included in [AppCompatTextView](https://developer.android.com/reference/android/support/v7/widget/AppCompatTextView) or we missed something?

I am working on this issue

**Comment by N1ghtly** [comment]
Still running into this issue on 0.63.3, can this be re-opened?

**Comment by sungsong88** [comment]
```javascript
selection={{
  start: 0,
}}
```

This works, but still no ellipsis...

**Comment by Nualiian** [comment]
This issue is still going strong in `0.63.4`

**Comment by thanhluantl2304** [comment]
still stuck on this in 2021! Any update on this???

**Comment by ortonomy** [comment]
Not sure there is any development going on in core react native these days. Does Facebook even use it internally?

**Comment by smartcris** [comment]
See on their  [Documentation](https://reactnative.dev/docs/textinput ) the IOS version is still messed up

**Comment by jatin8877** [comment]
Use textAlign:'auto', it should work for you

**Comment by PrOsToIOpA** [comment]
Same issue RN v0.70.6.

**Comment by SwikarBhattarai** [comment]
Why this issue hasn't been solved yet ??? Its been more than 6 years

**Comment by ritathesaver** [comment]
> Why this issue hasn't been solved yet ??? Its been more than 6 years

it's been 7 already..

**Comment by ankitgupta-unthinkable** [comment]
This issue is still happening, then why ticket is closed??

**Comment by HannahCarney** [comment]
@hramos can you reopen this, it's been years and should be at least open.

**Comment by Karthik-B-06** [comment]
the issue is still there :( 

![Image](https://github.com/user-attachments/assets/c45955b7-c5fd-40b9-bf6b-24aeb6108b9f)

**Comment by KJ-GM** [comment]
issue is still valid. any solution or workaround ?

**Comment by mathbalduino** [comment]
Hey, we're still having this issue with the latest React Native version
