### ISSUE TITLE
[0.46][Android]can not scroll in multiline - diseditable mode of TextInput

### ISSUE THREAD

**Issue by bingfj2008** [facebook/react-native#14856]
### Is this a bug report?

Yes

### Environment

1. `react-native -v`: 0.46

Then, specify:

1. Target Platform (e.g. iOS, Android):  Android 
2. Development Operating System (e.g. macOS Sierra, Windows 10): Windows 7
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): SDK 25

### Steps to Reproduce

1. Set a part Props of "TextInput" as follows.

`multiline={true}`
`editable={false}`

2、Set more lines text contents in this "TextInput" while

For example, if this "TextInput" can display up to max 5 lines in one times, Set 6 or more lines text in it.

### Expected Behavior

I think that contents of contents should be able to be displayed by scrolling, 
regardless of whether it can be input to "TextInput" or not.

### Actual Behavior

At present, contents can be displayed by scrolling when this "TextInput" can not to edit in only IOS. 
In ANDROID, contents can not be displayed by scrolling.

### Reproducible Demo

example project is here -> https://snack.expo.io/BJ9j8OsVW

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by durgarao150** [comment]
The issue still persists on android and there is no solution to it yet

**Comment by nickgrealy** [comment]
I'm getting same issue on IOS: `react-native: 0.47.2`. Can we get this issue reopened? @hramos
