### ISSUE TITLE
[0.46.3] fails to run on device

### ISSUE THREAD

**Issue by ivpusic** [facebook/react-native#14912]
### Is this a bug report?

yes

### Environment

```
react-native-cli: 2.0.1
react-native: 0.46.3
node: v8.1.0
```

Target Platform: iOS

### Steps to Reproduce

Build iOS app for release, and try to run it on the actual iOS device.

The app will crash with error:

```
Error reading bundle /var/containers/Bundle/Application/62A1S7F9-6795-4S7E-93B3-A2F17FC5BFCF/MyApp.app/main.jsbundle
```

On the simulator, the app runs fine.
After downgrading to 0.45.1 everything worked on the device as well again.

**Comment by hramos** [comment]
That seems strange. Is this something you can reliably reproduce? For example, does it occur on a plain new project created with 0.46.1?

**Comment by ivpusic** [comment]
@hramos any updated here? RN 0.46.3 has the same issue. 0.46.x is basically unusable because of this issue. As I said it happens on a new project when trying to run it on the device using "Release" config. It should be very simple to reproduce.

**Comment by hramos** [comment]
I don't have any updates, I haven't seen any PR that addresses this specifically. If one is submitted and merged in, I can look into another point release.

**Comment by ivpusic** [comment]
Solved it. It seems that packager is trying to figure out node version installed on my system. The problem was that I am using nvm and default nvm node version was `v5.7.1`, and this was too old to build the app. However in my zsh config, I have `nvm use v8.1.0` which is good, but it wasn't picking up `v8.1.0` while building the app. The solution was to mark `v8.1.0` as nvm default.

**Comment by scgough** [comment]
@ivpusic Hi, I too have this problem. When I deploy my app to a device when compiled for `Release` I see:

`Error reading bundle /var/containers/Bundle/Application.../MyApp.app/main.jsbundle` 

I'm not using nvm - is there an alternative for brew? Node version is v8.2.0

**Comment by ivpusic** [comment]
resolving node version is done here https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L54. Try to put some debug logs to see what is resolved.

**Comment by DaveCole** [comment]
@ivpusic @scgough Did either of you guys find any solution out there?  Tried this with the very latest node/npm and still getting the problem.

**Comment by dzjin** [comment]
having this issue as well. can it be reopened?

**Comment by avz** [comment]
if you ever installed `nvm`, and then deleted it (like me), then you can try `rm -r ~/.nvm`

https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L58

```
if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  . "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
  . "$(brew --prefix nvm)/nvm.sh"
fi
```

**Comment by JakeRawr** [comment]
Hi, All

I'm having this problem after upgrade from 0.41 -> 0.50.4
I'm running with latest nvm/npm, and I can't run release mode on both simulator and real device.
it just says it can't load main.jsbundle. 

I've tried above solutions, nothing worked
Any update on this issue?
