### ISSUE TITLE
labelFor: TextInput accessibility on Android

### ISSUE THREAD

**Issue by dantman** [facebook/react-native#14989]
Right now there's no way to associate a label with a `<TextInput />` for accessibility. Looking information up I see that `android:contentDescription` (accessibilityText) is not recommended for EditText because it stops being announced after the field is filled and `android:hint` (placeholder?) is only announced when empty.

The proper way to label an EditText seems to be to create a text node and use `android:labelFor` to make it the label of the input.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by dantman** [comment]
The issue is still present in react-native.

And it needs a discussion on how to implement it because labelFor is an ID prop, not one you can easily assign.

This is an accessibility bug so naturally it doesn't "affect" a lot of people who would make bug reports. A lot of developers don't bother with handling accessibility correctly. And the people affected by accessibility bugs are naturally a minority group.

**Comment by dantman** [comment]
Actually, someone who understands the native code may need to chime in. But `createView` may be setting an id already.
https://github.com/facebook/react-native/blob/4ca617211b23754ffecf23c1ddc8772bc32420f0/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java#L228-L231

However, I have no clue if this is an actual reliable id we can use or an abuse that makes views of the same type share ids.
