### ISSUE TITLE
onSubmitEditing is no longer called when blurOnSubmit is false

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#15299]
The use case where this causes an issue is to focus the next text input with the keyboard "next" button. To detect that the "next" button was pressed I use onSubmitEditing but it is not called anymore when blurOnSubmit is false. Right now I have to set blurOnSubmit to true but causes the keyboard to close a bit then reopen which is bad instead of just staying opened.

Looks like the logic changed in the recent refactors:

Old delegate implementation

https://github.com/facebook/react-native/blob/9afb71fde8199156ed683dca6aa59826f9fb9279/Libraries/Text/RCTTextField.m#L267
and https://github.com/facebook/react-native/blob/9afb71fde8199156ed683dca6aa59826f9fb9279/Libraries/Text/RCTTextField.m#L267

New implementation

https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTTextInput.m#L118

### Repro ###

It works on snack because it doesn't have the text input changes yet, the same code doesn't work currently on master.

https://snack.expo.io/HJMHiNaI-

cc @shergin

**Comment by shergin** [comment]
Fixed in b06672e6cf7eee1f94e535aef2c49d8f6d7e8e16.

**Comment by joncursi** [comment]
@shergin this is still an issue on Android. See https://github.com/facebook/react-native/issues/16038
