### ISSUE TITLE
ItemSeparatorComponent isn't properly working with horizontal FlatList

### ISSUE THREAD

**Issue by yozel** [facebook/react-native#15777]
### Environment

- react-native-cli 2.0.1
- react-native 0.47.2
- node 7.10.0
- npm 4.6.1
- Target Platform: iOS and Android
- Development Operating System: macOS Sierra Version 10.12.6

### Steps to Reproduce

Try to use ItemSeparatorComponent with horizontal FlatList.

### Expected Behavior and Actual Behavior

![bug](https://user-images.githubusercontent.com/1916237/30007156-2a778566-9111-11e7-9bb9-d4b4c6ca92ab.png)

### Reproducible Demo

https://snack.expo.io/HJuc--5Kb

**Comment by VahidBo** [comment]
This issue is fixed now by this #15865

**Comment by VahidBo** [comment]
@yozel This issue is fixed now by #15865. you can close this issue now.

**Comment by GioLogist** [comment]
I am also getting this issue, which is the same as this https://github.com/facebook/react-native/issues/14680

The first comment by @yozel here https://github.com/facebook/react-native/issues/15777#issue-254905437 perfectly outlines the expected / actual behavior.

The separator is getting based below and not next to the item, in horizontal lists.

**Comment by GioLogist** [comment]
This issue still exists, here's another duplicate here https://github.com/facebook/react-native/issues/14680

However, the first post in this thread by @yozel here https://github.com/facebook/react-native/issues/15777 perfectly outlines the expected / actual result.
