### ISSUE TITLE
[RN 0.49-rc.5] Fishhook error

### ISSUE THREAD

**Issue by mobinni** [facebook/react-native#16039]
### Is this a bug report?
No.

I tried to manually upgrade from 0.48.3 to 0.49-rc.5 due to the `BLOB_URL` error that happens in sed version. 

https://github.com/facebook/jest/issues/4433
https://github.com/facebook/react-native/issues/15810

When upgrading everything went well until the following error occurred:
![](https://i.imgur.com/PLmFz7Y.png)

I tried adding:
```  
pod "React", :path => react_native_path, :subspecs => ['DevSupport', 'fishhook']
```

However this did nothing for me, there is currently no documentation on how to integrate fishhook when manually upgrading. Can anyone help?

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.4
    Node:  7.8.0
    Yarn:  0.24.6
    npm:  5.4.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b

  Packages: (installed)
    react-native: 0.49-rc.5 
    react: 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Expected Behavior

Build succeeds

### Actual Behavior
Build fails because it cannot find fishhook files

**Comment by mobinni** [comment]
@here update I figured it out to be a mis-import in reconnecting websocket, it links to
```
#import "<fishhook/fishhook.h>"
```
while it should link to 
```
#import "fishhook.h"
```

**Comment by johannth** [comment]
This is a similar issue to https://github.com/facebook/react-native/issues/13198

I think this stems from Cocoapods not defining subspecs as modules/frameworks so there is no `fishhook` module and we can't do `<fishhook/fishhook.h>`. I've asked on the [Cocoapods mailing list](https://groups.google.com/forum/#!topic/cocoapods/65WdPX8OH6g) to confirm but I agree that the import is probably wrong and should either be:

`#import <React/fishhook.h>`

or

`#import "fishhook.h"`

An alternative in this case would be to depend on the `fishhook` Cocoapod instead of the embedded subspec. Then the import could stay as it is.

**Comment by ide** [comment]
I believe this is addressed in https://github.com/facebook/react-native/pull/16192 so I'm going to close this. That commit should go out with 0.49.1 in an hour or so.

**Comment by rob-keepsafe** [comment]
@johannth You can add a postinstall script to fix that issue into your package.json like

```
"scripts": {
        "postinstall": "sed -i '' 's#<fishhook/fishhook.h>#\"fishhook.h\"#g' ./node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m",
        // any other scripts here
},
```

**Comment by mobinni** [comment]
@rob-keepsafe It is fixed in 0.49.1, the issue doesn't occur on a lower version, so it should be good

**Comment by rob-keepsafe** [comment]
@mobinni Unfortunately we're using `0.49.1` and still getting that as an issue

**Comment by rob-keepsafe** [comment]
@mobinni @ide This still appears broken in `0.49.1` :\ The script above works fine for now

**Comment by mobinni** [comment]
@rob-keepsafe are you using pods, in which case you would need to pod update for it to take full effect.

I updated from 0.48 to 0.49.1 and it worked just fine after clearing my workspace (cmd shift alt k, cmd shift k), running a clean install, then pod updating

**Comment by rob-keepsafe** [comment]
I just installed React today for the first time, so it's been using `0.49.1` by default. The pods just point to the local podspecs in the `node_modules` directory as well 

<img width="276" alt="screen shot 2017-10-05 at 4 16 27 pm" src="https://user-images.githubusercontent.com/30269720/31256625-ad8e5836-a9e8-11e7-8ae8-9be7a3ea4de7.png">

Deleting the `node_modules/` and `Pods/` directories, derived data, etc. doesn't work on my end

**Comment by macdoum1** [comment]
@mobinni Also installed React for the first time using cocoapods and followed the guide here: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html Also seeing the missing fishhook import

**Comment by ide** [comment]
Reopening since people seem to be having issues still but am not working on it / don't know that anyone is, just to set expectations.

**Comment by macdoum1** [comment]
Anyone have any idea which older version does not have this issue?

- Michael MacDougall

**Comment by rob-keepsafe** [comment]
@macdoum1 No, but you can work around it for now via https://github.com/facebook/react-native/issues/16039#issuecomment-334593899

**Comment by macdoum1** [comment]
Fairly new to react, but opened a PR here addressing the import: https://github.com/facebook/react-native/pull/16271/files

**Comment by shuhaodo** [comment]
having the same issue too in 0.49.3.

Also, there was a similar issue, still happening in 0.49.3:

`import <RCTAnimation/RCTValueAnimatedNode.h>`

**Comment by bithavoc** [comment]
this is still happening in 0.49.3

**Comment by karpov3** [comment]
the same problem in 0.50.0-rc.1

**Comment by AtomicCactus** [comment]
+1 still happening in 0.49.3

**Comment by jgsamudio** [comment]
This happened to me when creating a new react native project. I found out that removing  `use_frameworks!` in the podfile worked resolve the fishhook import error

**Comment by rodrigoelp** [comment]
Hi guys,

Today I came across with the [integration to an existing platform](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html) using swift and I ran into several issues...

Reduced my podfile to this:

```ruby
target 'sampleApp' do
    use_frameworks!
  
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTText',
      'RCTImage',
      'RCTNetwork',
      'RCTSettings',
      'RCTWebSocket', # needed for debugging
    ]
  end
```

Once all the pods are installed, build does not work as `RCTReconnectingWebSocket.m` can't find the import

```objC
#import <fishhook/fishhook.h>
```

Checking the source code I have managed to get it to work at the moment by changing that line to 

```objc
#import "fishhook.h"
```
I can see this issue is closed and merged... but it seems quite unstable to me...

these are my dependencies.
```json
		"react": "^16.1.0",
		"react-native": "^0.50.3"
```

**Comment by bithavoc** [comment]
@rodrigoelp I went for not using react native modules from cocoapods, only use cocoapods for non-RN dependenfies that RN modules being linked with “react-native link”.

**Comment by tirrorex** [comment]
@bithavoc can't find any ressources on how to integrate react-native into an existing app without cocoapods.

Modifying the source-code works for now but it is a ugly fix, would be great to have a real pr on this.

**Comment by rodrigoelp** [comment]
Hi @tirrorex, unfortunately, it is not a "fix" is a hack.

The change provided will not work for my CI as we do not tend to check in `node_modules` or pods as the matter of fact. The CI agent will be downloading its own copy and work from there.

It would be nice to follow the documentation and actually get it to work without issues nor guessing what's wrong this time.

**Comment by jiangqqlmj** [comment]
Thank you~, i am fixed!

**Comment by tirrorex** [comment]
@rodrigoelp i know :/ a solution for you would be to fork the repo imo.

**Comment by guykogus** [comment]
We're adding something like this to our `packages.json` file:
```
"scripts": {
    "postinstall": "sed -i '' 's/#import <fishhook\\/fishhook.h>/#import <React\\/fishhook.h>/' ./node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m"
}
```

**Comment by rodrigoelp** [comment]
@guykogus thanks for sharing that. I honestly did not think on using `sed` to replace the lines giving us issues. I like your workaround.

@tirrorex I would like to avoid as much as possible forking the repo for a single line of code that can be fixed directly in the source code. There is no implication to that line for ObjC and it needs to be taken into consideration given more and more people are switching to Swift.

**Comment by tirrorex** [comment]
@guykogus thanks a lot ! Did not think of that either, changing the code by hand was a pain :D

**Comment by salutis** [comment]
+1 still happening in 0.52-RC

**Comment by joyeer** [comment]
+ still happening in 0.52

**Comment by Titozzz** [comment]
Can we get this fixed ? having a sed in postinstall is not the cleanest way to do that ^^'

**Comment by rodrigoelp** [comment]
@Titozzz given this has been going for a while, I don't think they are paying attention to cocoapods at all.

**Comment by amardeepranu** [comment]
Still happening in 0.53

**Comment by nomadplanet** [comment]
+1

**Comment by localredhead** [comment]
+1

**Comment by FlyOrDie** [comment]
+1

**Comment by ptomasroos** [comment]
This is not happening to us and we're running cocoapods and has done since 2015.  We're currently at the 0.51.0 release

**Comment by MoOx** [comment]
@ptomasroos are you using `use_framework!`? I didn't have this issue until I enabled it (in order to integrate a new rn module that use swift)

**Comment by ptomasroos** [comment]
Nope not using use_framework @MoOx

**Comment by MoOx** [comment]
That's what is creating this problem. So there is a major issue that make it impossible to use RN with use_frameworks! currently.

**Comment by msand** [comment]
Try the patches from here: https://github.com/facebook/react-native/pull/17764#issuecomment-367943213

**Comment by msand** [comment]
This should probably be solved using this approach: https://github.com/facebook/react-native/issues/13198#issuecomment-371749528

**Comment by matteocollina** [comment]
This is my gist for RN 0.51.0 and React 16.0.0 (it works)
https://gist.github.com/matteocollina/fe2a9c3e2a96061ac1a15c0fcf2cbded

**Comment by chrisballinger** [comment]
This issue is not resolved in RN 0.56.0-rc.2.

**Comment by rodrigoelp** [comment]
This has not been fixed. Here is the line that is causing the issue when you are using cocoapods with frameworks: 

https://github.com/facebook/react-
native/blob/master/Libraries/WebSocket/RCTReconnectingWebSocket.m#L12

**Comment by keshavkaul** [comment]
@MoOx I am using Swift and have `use_frameworks!` enabled. This issue still persists in RN 0.56.0-rc.4
