### ISSUE TITLE
Dimensions window support for Split View and Slide Over on iPad

### ISSUE THREAD

**Issue by Freddy03h** [facebook/react-native#16152]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.2.1
  Yarn:  0.24.6
  npm:  3.10.10
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

### Steps to Reproduce

On on iPad, with the app on "Split View" or "Slide Over".
```
console.log(Dimensions.get('screen')) // {fontScale: 1, width: 768, height: 1024, scale: 2}
console.log(Dimensions.get('window')) // {fontScale: 1, width: 768, height: 1024, scale: 2}
```
_(example of console log on iPad Pro 9.7 inch)_

### Expected Behavior

On iOS `Dimensions.get('screen')` and `Dimensions.get('window')` always return the same data. It assuming that the app is always in fullscreen. But on iPad the screen can be share with an other app (Split View), and since iOS, can "float" in a little window over an other app (Slide Over).

`Dimensions.get('window')` shouldn't always return `Dimensions.get('screen')` `width` and `height` but the real size of the window.

### Actual Behavior

`Dimensions.get('window')` always return `Dimensions.get('screen')`, even on "Split View" or "Slide Over"

#### Slide Over example
<img width="568" alt="capture d ecran 2017-10-01 a 01 32 22" src="https://user-images.githubusercontent.com/1412159/31050369-da3c4be8-a648-11e7-8532-a5169a4df227.png">

`console.log(Dimensions.get('window')) // {fontScale: 1, width: 768, height: 1024, scale: 2}`

#### Split View example 1
<img width="568" alt="capture d ecran 2017-10-01 a 01 32 31" src="https://user-images.githubusercontent.com/1412159/31050375-f7482df6-a648-11e7-9409-f5b496f4a2c7.png">

`console.log(Dimensions.get('window')) // {fontScale: 1, width: 768, height: 1024, scale: 2}`

#### Split View example 2
<img width="568" alt="capture d ecran 2017-10-01 a 01 33 00" src="https://user-images.githubusercontent.com/1412159/31050376-fa7a2f88-a648-11e7-8374-731b5efba527.png">

`console.log(Dimensions.get('window')) // {fontScale: 1, width: 768, height: 1024, scale: 2}`

### Reproducible Demo

It can be easily tested on iPad by adding `console.log(Dimensions.get('window'))` anywhere in an existing app or in a fresh create-react-native-app.
And using Split View and Slide Over features of iOS on iPad.

Snack Expo is here : https://snack.expo.io/ryIHToaiW but it need to be tested on an iPad Device or Simulator.

**Comment by Freddy03h** [comment]
I find a way to send correct `width` and `height` for the window.
In [RCTDeviceInfo.m](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/React/Modules/RCTDeviceInfo.m) I change `RCTExportedDimensions` :
```
static NSDictionary *RCTExportedDimensions(RCTBridge *bridge)
{
  RCTAssertMainQueue();

  // Don't use RCTScreenSize since it the interface orientation doesn't apply to it
  CGRect screenSize = [[UIScreen mainScreen] bounds];
  NSDictionary *dimsScreen = @{
                         @"width": @(screenSize.size.width),
                         @"height": @(screenSize.size.height),
                         @"scale": @(RCTScreenScale()),
                         @"fontScale": @(bridge.accessibilityManager.multiplier)
                         };
  CGRect windowSize = [RCTKeyWindow() bounds];
  NSDictionary *dimsWindow = @{
                         @"width": @(windowSize.size.width),
                         @"height": @(windowSize.size.height),
                         @"scale": @(RCTScreenScale()),
                         @"fontScale": @(bridge.accessibilityManager.multiplier)
                         };

  return @{
           @"window": dimsWindow,
           @"screen": dimsScreen
           };
}
```

It send the correct value but it didn't trigger a `change` event on `Dimensions` when resizing the app window in a Split-View mode.

Currently, two fonctions in Obj-C can trigger this event : `didReceiveNewContentSizeMultiplier` and `interfaceOrientationDidChange`. I think we need to create a new observer for the event, but I'm not an iOS dev, and I don't understand all the code in this file. Also, I don't get why it use `NotificationCenter` stuffs or why they use the _status bar_ orientation to get the orientation change of all the screen…

**Comment by variantf** [comment]
Waiting for this feature!!! Thanks a lot

**Comment by Freddy03h** [comment]
No one target the iPad ? :(

**Comment by jamsch** [comment]
I'm having the same issue. Using a FlatList set to horizontal where every item is set to the current dimensions. As a result, the items are now too wide because the window dimensions aren't correct.

One of my components listens for dimension changes and the view is updated to reflect those changes. while it works fine when not in split screen.

```javascript
  componentDidMount() {
    Dimensions.addEventListener('change', this._handleScreenDimensionsChange);
  }
_handleScreenDimensionsChange = (dimensions: DimensionsChangeEvent) => {
  this.props.dispatch(dimensionsChange(dimensions.window));
};
```


[image](https://i.imgur.com/X2nIvHb.png)

**Comment by rogerkerse** [comment]
We have the same issue

**Comment by Axlle** [comment]
+1

**Comment by neiker** [comment]
Absolutely! 

I solved this measuring the root component onLayout and sending the size to the store.

**Comment by mrtnzlml** [comment]
This is still a valid issue (latest RN release ^0.55.4). We have to use [very nasty workarounds](https://github.com/kiwicom/mobile/blob/1acde0180bfba959b0412ca12d6d6bd0c0622867/app/shared/src/view/AdaptableLayout.js) to make it really work (inspired by comments in this issue) and it's considered one of [the biggest pains](https://github.com/kiwicom/mobile/issues/466) in our codebase.

**Comment by Freddy03h** [comment]
The issue is still valid !

**Comment by neiker** [comment]
Still valid

**Comment by RoyalKingMomo** [comment]
PR Pending!!! Any updates on the admin side? When is thing being pulled into master?

**Comment by manoj2166** [comment]
Hi,
you can use "onLayout" function on the root view of the component to calculate its dimensions. I have used and working fine here is sample code:

<View style={{flex:1}} onLayout={this.onLayoutScreen}>
....//inner codes    
</View>

onLayoutScreen = (e) => {
        let width = e.nativeEvent.layout.width;
        if(width != this.state.layoutWidth) {
            this.setState({
                layoutWidth: width
            })
        }

    }

**Comment by rdonnelly** [comment]
I've had a PR open for a few months now and am not sure how to proceed. So far, I'm not getting any traction on getting it merged. If anyone has an idea, please feel free to chime in. 

For me, this issue is still valid.

**Comment by Freddy03h** [comment]
For information, it's fixed in `0.59.5`, thank's all!

**Comment by m4ttheweric** [comment]
I am still seeing that when I run ``Dimensions.get('window')`` while the app is in multitasking mode (either floating over an app, or splitting the screen), the Dimensions reported seem to be for the entire device width, not the current width of the window that app is running in.

Using expo latest version in the expo app.

**Comment by rdonnelly** [comment]
@m4ttheweric This is working fine for me:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/563418/71865298-5247f600-30d0-11ea-832d-dcd093519c21.png">

On a fresh Expo (36.0.0) project, my App.js looks like this:
```javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Dimensions } from 'react-native';

export default function App() {
  const windowWidth = Math.round(Dimensions.get('window').width);
  const windowHeight = Math.round(Dimensions.get('window').height);

  const screenWidth = Math.round(Dimensions.get('screen').width);
  const screenHeight = Math.round(Dimensions.get('screen').height);

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Text>WINDOW Width: {windowWidth}</Text>
      <Text>WINDOW Height: {windowHeight}</Text>
      <Text>SCREEN Width: {screenWidth}</Text>
      <Text>SCREEN Height: {screenHeight}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
Mind you, you need to refresh after you enter multitasking. A better example would use an event listener for screen/window size changes.
