### ISSUE TITLE
[Android] Scroll appears in TextInput with custom fonts and multiline=true

### ISSUE THREAD

**Issue by mxck** [facebook/react-native#18132]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

### Steps to Reproduce

1. Add custom font to project (added to rnpm and ```react-native link```).
2. Use this font in TextInput with multiline={true}

### Expected Behavior

Get multiline input without scroll

### Actual Behavior

Multiline input with scroll.
![screnshot](https://user-images.githubusercontent.com/2190443/36772726-f2fb477c-1c88-11e8-9570-d3de5b07da7d.jpg)
(1. Stardart font, 2-4. Custom fonts)

### Reproducible Demo

```
import React from "react";
import { View, TextInput } from "react-native";

const LOREM =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco";

export default function App() {
  return (
    <View>
      <TextInput value={LOREM} multiline />
      <TextInput
        style={{ fontFamily: "OpenSans-Bold" }}
        value={LOREM}
        multiline
      />
      <TextInput
        style={{ fontFamily: "Nunito-Regular" }}
        value={LOREM}
        multiline
      />
      <TextInput
        style={{ fontFamily: "DK Sugary Pancake" }}
        value={LOREM}
        multiline
      />
    </View>
  );
}
```
I also tried to set autoGrow={true} but resultis the same

Full code with fonts (fonts from google fonts, so they are free).
https://github.com/mxck/react-native-TextInput-multiline-bug

**Comment by hramos** [comment]
@facebook-github-bot label Android

**Comment by rikur** [comment]
+1

**Comment by bsbechtel** [comment]
I had this same issue. Eventually, I figured out a work around by setting `height` larger or reducing `font-size` on the `TextInput` component.

**Comment by rikur** [comment]
What makes it even worse is that `scrollEnabled={false}` doesn't remove the scroll either.

**Comment by mloureiro** [comment]
@rikur `scrollEnabled` is iOS setting only.

**Comment by vicnicius** [comment]
Also had the same issue. It looks like there's something wrong with the `TextInput` height calculation when mounting it with content and a custom font. The workaround in my case was to first render it empty and then set it's content.

**Comment by xhirazi** [comment]
+1

**Comment by workray** [comment]
Here is my solutions
onContentSizeChange = (event: Object) => {
        this.setState({ inputHeight: event.nativeEvent.contentSize.height })
    }
...
<TextInput
                                                ref={ref => (this.textInputRef = ref)}
                                                multiline
                                                onContentSizeChange={this.onContentSizeChange}
                                                onChangeText={this.onChangeText}
                                                onSelectionChange={this.onSelectionChange}
                                                value={textFromInput}
                                                autoCorrect
                                                placeholder='Share something...'
                                                underlineColorAndroid='transparent'
                                                placeholderTextColor={colors.black}
                                                style={[
                                                    styles.textInput,
                                                    { height: Math.max(44, inputHeight) },
                                                ]}
                                                onBlur={this.onBlur}
                                                onFocus={this.onFocus}
                                                scrollEnabled={false}
                                            />

**Comment by rikur** [comment]
Nope, still an issue

**Comment by rikur** [comment]
Still an issue.

**Comment by vyashole** [comment]
+1

**Comment by rikur** [comment]
Still a bug

**Comment by rikur** [comment]
AFAIK, still a bug in latest RN.

**Comment by vyashole** [comment]
Still a bug

**Comment by safaiyeh** [comment]
@fabriziobertoglio1987 did you gave a PR that addressed this?

**Comment by fabriziobertoglio1987** [comment]
thanks @safaiyeh , I think you refer to my pr https://github.com/facebook/react-native/pull/29025 

>fixes a bug causing ScrollView to not detect scroll gesture when including a TextInput with textAlign center.

while here I don't see a ScrollView, the issue should be investigated in the TextInput.js functionalities and ReactAndroid TextInput API

Hopefully I'll have time in this days to take a look.. Thanks a lot!

**Comment by Asadi123** [comment]
I faced the similar problem but my problem was I accentially set the height of textinput. So, it becomes scrollable with extra spaces, the problem was solved once I removed the height.

**Comment by jacdx** [comment]
Still broken on React Native 0.64. This is a pretty big issue. No solution worked for me other than removing the custom font.

**Comment by MarwaKhaledMohamed** [comment]
I'm still facing the same problem( I'm using a custom font ). the issue happening when the text input has font size style when I removed the font size the scroll disappeared so I think the problem is related to the text input height which affected by the font size. I hope you can fix this issue soon.

**Comment by KyawSoeHein** [comment]
as for me, if I get rid of height, scrolling disappear

**Comment by Captn-Nemo** [comment]
I guess its due to the default Vertical padding present in the component . I just manually added a padding Vertical and it solved my issue !!

**Comment by MuhammadRafeh** [comment]
I am facing same exact issue

**Comment by Reykjavik151** [comment]
still the same - RN hasn't an opportunity to disable visibility for TextInput multiline scroll

**Comment by TommysG** [comment]
Any solution for this? This also creates a problem. If you have several textinput with custom font inside a scrollview, you can't scroll on the screen by touching on them (due to the internal TextInput scroll). Any workaround? The only thing that worked was removing custom font from TextInput.

**Comment by galaxykhh** [comment]
still a bug on RN 0.72.6

**Comment by ng-ha** [comment]
style={{includeFontPadding: false}} works for me
