### ISSUE TITLE
Border radius on android 4.4.2

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#18224]
On android 4.4.2 `borderRadius` and `borderWidth` is not render correctly

### Environment

```
OS: Windows 10

Node: 8.5.0

Yarn: 1.2.1

npm: 5.3.0

Watchman: Not Found

Xcode: N/A

Android Studio: Version 2.3.0.0 AI-162.4069837


Packages: (wanted => installed)

react: 16.2.0 => 16.2.0

react-native: 0.53.0 => 0.53.0
```

### Expected Behavior

A rounded rectangle must be rendered

### Actual Behavior

Screen shot on android 4.4.2
![image](https://user-images.githubusercontent.com/19644997/37028966-12294808-214b-11e8-898b-61057929f85c.png)

### Steps to Reproduce

Correct demo : https://snack.expo.io/BJuR6khOM

Run the following code on android 4.4.2
```js
import React, { Component } from 'react';
import { Text, StyleSheet, TextInput} from 'react-native';


export default class App extends Component {
  render() {
    return (
      <TextInput style={styles.container}/>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    borderWidth: 1,
    borderColor: '#00ff00',
    borderRadius:10,
    backgroundColor: '#ff0000',
    color: '#252525',
    paddingLeft: 15,
    paddingRight: 15,
    marginTop:50,
  },
});
```

**Comment by sm2017** [comment]
@react-native-bot it reproduced in last stable version too

**Comment by arma7x** [comment]
Have you test with borderTopRightRadius ? I'm on RN0.54 and using TopRight, TopLeft, BottomRight, BottomLeft to get radius render properly.

**Comment by martjoao** [comment]
I'm having this issue as well. Have you found any workarounds for this, @sm2017 ?  Border-width works OK, border radius too. When both are together I'm getting the same results you are.

**Comment by sm2017** [comment]
@martjoao I think it is a react native bug and must be fixed in native side
I have no workaround

**Comment by himabindugadupudi** [comment]
Fixed with commit c5ca26a which is now in Master. Please test with Master build.

**Comment by AkilLis** [comment]
It is working without borderWidth. With borderWidth issue still exists. Tested on latest release rn: 55.3 @himabindugadupudi
