### ISSUE TITLE
React Native 0.55.0 CFBundleIdentifier error after fixing metro port

### ISSUE THREAD

**Issue by Rob117** [facebook/react-native#18687]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

React native gives the classic CFBundleIdentifier Does Not Exist error on new project in 0.55.0

```
The following build commands failed:

	CompileC /Users/rob/projects/newproto/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBundleURLProvider.o Base/RCTBundleURLProvider.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing Build/Products/Debug-iphonesimulator/newproto.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier Build/Products/Debug-iphonesimulator/newproto.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.0-alpha.0 => 16.3.1
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce
react-native init prototype
cd prototype
ref #18681 - perform this edit to the runIOS file so you can start metro bundler.
react-native run-ios

## Expected Behavior
Sim starts, app is displayed

## Actual Behavior
I get the above error.

Note that downgrading to react-native 0.52.0 and running the above commands gives no problems at all.

**Comment by tevatahiti** [comment]
Same issue here...

**Comment by zicat** [comment]
I meat the same error, I try to use react-native 0.54.0, it run well.

**Comment by Harryyan** [comment]
same issue

**Comment by mo-esmp** [comment]
Same issue here

**Comment by wellyshen** [comment]
Same issue

**Comment by hiepnm** [comment]
Same issue

**Comment by NgocVan9x** [comment]
same issue

**Comment by kelset** [comment]
First off, **PLEASE** don't pollute the issue with useless 'same issue' comments.

There are the reactions for indicating that this issue is present.

That said, please don't use 0.55.0 because [it ships with the wrong version of React](https://github.com/react-native-community/react-native-releases/issues/2#issuecomment-378351125). We are going to release soon a new version.

Aside from all of this, also consider cleaning up your XCode Build and Derived Data and pod cache.

**Comment by angly-cat** [comment]
> Now I am still unable to launch the simulator (Metro is launching fine)... don't know why

Yeah, that's another issue, @tevatahiti. However, you can work around it by launching simulator once via Xcode. At least it's something.

**Comment by grabbou** [comment]
Okies, this ended up being a real issue! Anyway, PR is in progress and I got this fixed in 0.55.1 which is coming out in a second :)

**Comment by wouterds** [comment]
@grabbou: I just upgraded to `0.55.1` but the issue is still present for me.

```Installing build/Build/Products/Debug-iphonesimulator/Delta.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Delta.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by kelset** [comment]
Try cleaning the Xcode project, then the build folder, then the DerivedData folder, then the pod cache, then run again pod install.

**Comment by saranshjain1** [comment]
I am getting this error on both 0.55.2 and 0.54.4 version of react-native.

The following build commands failed:
	CompileC /Users/livspace/saransh/mobile/newproject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTFont.o Views/RCTFont.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/newproject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/newproject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

I have tried changing path in xcode from default build/* to build/Build/* and verified info.plist. Can you please tell me what could be wrong?

**Comment by Rob117** [comment]
@saranshjain1 I'm not sure if you fixed it yet, but it looks like you need to make sure that your metro bundler is starting properly?

If you run `npm start`, does your bundler start without errors? If so, what happens when you run `react-native run-ios` after?

**Comment by dbnex14** [comment]
Same issue here

** BUILD FAILED **


The following build commands failed:

```
	CompileC /Users/dinob/reactnativework/MapExample/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTShadowView+Internal.o Views/RCTShadowView+Internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/MapExample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/MapExample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


dinob@dbmac:~/reactnativework/MapExample $ ls -l
total 704
-rw-r--r--    1 dinob  staff    1184  3 May 15:48 App.js
drwxr-xr-x   10 dinob  staff     340  3 May 15:48 android
-rw-r--r--    1 dinob  staff      57  3 May 15:48 app.json
-rw-r--r--    1 dinob  staff     126  3 May 15:48 index.js
drwxr-xr-x    8 dinob  staff     272  3 May 15:48 ios
drwxr-xr-x  638 dinob  staff   21692  3 May 15:48 node_modules
-rw-r--r--    1 dinob  staff  340982  3 May 15:48 package-lock.json
-rw-r--r--    1 dinob  staff     455  3 May 15:48 package.json
dinob@dbmac:~/reactnativework/MapExample $ react-native -v
react-native-cli: 2.0.1
react-native: 0.55.3
dinob@dbmac:~/reactnativework/MapExample $ node -v
v8.9.1
dinob@dbmac:~/reactnativework/MapExample $ npm -v
5.5.1
dinob@dbmac:~/reactnativework/MapExample $ watchman -v
4.9.0
dinob@dbmac:~/reactnativework/MapExample $ 
```

**Comment by ChaseWPDEV** [comment]
Experiencing an identical issue to @dbnex14 with .4 patch:
react-native-cli: 2.0.1
react-native: 0.55.4 
node: 10.0.1
nom: 5.6
iOS: 10.13

**Comment by ChaseWPDEV** [comment]
Since this is a new version/ compilation error I've moved to new issue #19218

**Comment by billtlee** [comment]
So, has this issue been closed or under another issue?  I am also having the same exact problem with 0.55.4.

**Comment by gorjuspixels** [comment]
We added `main.jsbundle` reference to `project.pbxproj`. When running on simulator, the file was not being generated, so we had to run the bundler ourselves. However, that `main.jsbundle` is needed to run the app on a real device. It should be generated as part of the `Build Phases`. I added the following to a new build phase `Bundle React Native code and images`:

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by RusinovAnton** [comment]
`react-native upgrade` worked for me

**Comment by augustbjornberg** [comment]
+1

**Comment by dbnex14** [comment]
Absolutely not, that's first thing I tried
No that will not solve this issue

**Comment by MaheshNandam** [comment]
![image](https://user-images.githubusercontent.com/13198616/43247260-cc35fea8-90d1-11e8-8782-c414cf8595e4.png)

Deleting the following folders from the above mentioned screen works for me:
~/Library/Developer/Xcode/DerivedData/Build/Products
~/Library/Developer/Xcode/DerivedData/Index/DataStore
~/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex

**Comment by ChaoTzuJung** [comment]
I buy new iMac and set up the environment for RN and I create new project and it fail such as the title 
<img width="1991" alt="screen shot 2018-08-11 at 12 02 33 am" src="https://user-images.githubusercontent.com/22141289/43970130-1e2532b8-9cff-11e8-835d-0199b86debcb.png">
My version is:
    "react": "16.4.1",
    "react-native": "0.56.0"

XCode is 8.2.1

<img width="742" alt="screen shot 2018-08-10 at 11 47 07 pm" src="https://user-images.githubusercontent.com/22141289/43970142-249ab456-9cff-11e8-920a-e608fc53229c.png">

**Comment by wouterds** [comment]
Could you try the following and try again?

```bash
rm -rf ios android
react-native eject
git checkout ios android
```

**Comment by Ahmed-Fayyaz** [comment]
Hi Guys, any luck with this. I have been struggling for last four days and none of the solutions worked for me :(. 


**Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.

** BUILD SUCCEEDED **


Installing build/Build/Products/Debug-iphonesimulator/brooklynz.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.**

version:
react-native-cli: 2.0.1
react-native: 0.55.4
xCode v10.0

**Comment by devapro** [comment]
![image](https://user-images.githubusercontent.com/2677592/51604597-4fcfa900-1f1e-11e9-9b5b-9f4cfb09d990.png)

I have the same issue on latest version RN. I fixed it by opening File->Xworcspace settings ->Advanced and set Default (see my image)
