### ISSUE TITLE
Fetching specific JSON causes massive memory leak

### ISSUE THREAD

**Issue by Ashoat** [facebook/react-native#20352]
## Environment
```
React Native Environment Info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 6.28 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    Android SDK:
      Build Tools: 23.0.1, 25.0.0, 26.0.1, 26.0.2, 26.0.3, 28.0.1
      API Levels: 23, 26, 28
  IDEs:
    Android Studio: 3.1 AI-173.4819257
    Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.4.1 => 16.4.1
    react-native: ^0.56.0 => 0.56.0
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```

## Description
Downloading [this <1 KiB JSON file](http://ashoat.com/rnleak.json) once a second, parsing the JSON, and appending the resultant JSON to an array, causes the demo app below to hit 500MiB of memory usage in less than 15 seconds. Each request permanently allocates ~35MiB of memory.

## Reproducible Demo
I have created a [repo](https://github.com/Ashoat/react-native-leak) to reproduce the issue.

**Comment by corpsemxq** [comment]
Will this be fixed by https://github.com/facebook/react-native/pull/19333?

**Comment by Ashoat** [comment]
Unfortunately, no. I just updated the test repo to 0.57 and the issue is still occurring. After downloading the tiny JSON file one a second for sixty seconds, memory usage of the Release build of the test project climbs to over 2 GiB.

**Comment by dlajarretie** [comment]
We're also experiencing the huge memory allocation when fetching JSON. We're fetching a much bigger resource than the example provided here, and I wonder if the memory allocation is proportional because our app gets killed by iOS for memory consumption (spike from 150mb to over 700mb), even before the fetch call completes.

**Comment by alainib** [comment]
i get a similar problem. i fetch a 15mo Json file. often the app get killed or get stuck in loading it. 

	console.log(url); // curl this url take less than 5s to download it
    try {
      let response = await fetch(url);

      console.log("response", response); // log ok 
      let statusCode = response.status;

      console.log(statusCode);   // log 200    
      if (statusCode == 200) {
        let data = await response.json();
        // data = _.cloneDeep(data); // doesn't change anything

        console.log("json", data);  // never reach this log ( fast wifi connection ) !!!!!!!!!
	  }
	}

**Comment by zhongwuzw** [comment]
Seems memory is fine in Release mode but bad in debug mode.

**Comment by dlajarretie** [comment]
Yes, in our case the memory consumption graph looks extremely different in debug mode compared to release.

**Comment by gablorquet** [comment]
Could it be related to [this](https://github.com/react-native-community/react-native-netinfo/issues/10) ?

**Comment by matt-oakes** [comment]
@gablorquet Looking at the reproduction code, it doesn't look like NetInfo is involved.

**Comment by TheSavior** [comment]
Does this repro on 0.59? Also, it isn't clear from the issue if this is iOS or Android. If it is Android I could imagine that this might be fixed by the latest JSC.

**Comment by zhongwuzw** [comment]
@TheSavior Yes, I confirmed on iOS, it has leaks, I checked both iOS and Android implementations, they share the same handle logic, so I assume Android may also has this issue. One leak we find is blob not removed, besides this, seems still has other leaks.

**Comment by Ashoat** [comment]
If I recall correctly, this issue is iOS-only. My bad on not making that clear initially. The repro I made above is iOS-only.

I have updated the repro repo to RN 0.59.1 and unfortunately the issue remains.

**Comment by TheSavior** [comment]
Got it. Thanks for giving it a try. Do you have any sense on whether this is the same problem as #23801? If so, as there is more conversation happening there than I'd like to close this as a duplicate.

**Comment by Ashoat** [comment]
Hmm... I took a quick look at the code to the repro in #23801, and on first glance I think they are different. But it's very possible they are caused by some of the same underlying issues.

Pulling from my comment above:

> There are two issues going on here, in my judgement:
> 1. The bigger issue, which is that a network request for a tiny JSON file is taking so much RAM.
> 2. Network requests aren't being garbage collected if the resultant JSON isn't. If I let the resultant JSON get garbage collected, the memory leak doesn't occur. But the network request still needs to allocate a whole bunch of memory.

The first issue doesn't seem to apply in #23801, as the size of their downloaded file is pretty substantial (5 MiB) in contrast with the tiny file here (<1 KiB).

The second issue doesn't seem to apply either. In the repro for #23801, the author actually lets the JSON get garbage collected, whereas I was only able to demonstrate a memory leak by keeping the JSON and appending it to an array.

It appears that there are two distinct memory leak issues: one that none of the native resources for the network request are cleaned up unless the resultant JSON blob is garbage-collected, and the other that some of the native resources aren't cleaned up even if a "resultant JSON blob" is never allocated.

**Comment by harleenarora** [comment]
@Ashoat Can you solve this problem?

**Comment by janicduplessis** [comment]
Fixed in 9ef5107 for ios and I just opened a pr with a fix for android.

**Comment by crobinson42** [comment]
Should this be re-opened? It's still an issue and as far as I understand the PR was pulled

**Comment by Ashoat** [comment]
I can't find evidence that the PR was pulled, but if you could  demonstrate that the issue is still extant in 0.60 (which should include the PR) I think it would make sense to reopen. I can't seem to get `react-native upgrade 0.60.0-rc.1` to work on the [repo](https://github.com/Ashoat/react-native-leak) above, but maybe once 0.60 is released we can try upgrading it.

**Comment by jgreen210** [comment]
The fix on android is working for us with 0.61.5 (and presumably some earlier versions too, though we've not tried them). Only for the default JavaScriptCore/jsc engine though, not hermes or v8 (see the above two issues).
