### ISSUE TITLE
Cannot resolve module when running Flow on Windows

### ISSUE THREAD

**Issue by zenz** [facebook/react-native#21311]
## Environment
Run `react-native info` in your terminal and paste its contents here.
react-native info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 2.09 GB / 7.91 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD

## Description
using flow not working and got error with "Cannot resolve module XXXXXX". but same action under macOS works well.

## Reproducible Demo
react-native init testapp
cd testapp
yarn add flow-bin@0.78.0 --dev
yarn flow

under windows will get errors.

**Comment by zenz** [comment]
with
```
"@babel/runtime": "^7.1.2",
 "metro-react-native-babel-preset": "0.48.0",
```
The issue seems had been fixed. So I close this now.

**Comment by zenz** [comment]
Sorry, While create a new project with init, the issue shows up again.

**Comment by zenz** [comment]
No other one using flow under windows or don't have any problem on this?

**Comment by jlkalberer** [comment]
I had the issue but I just added more ignores to the flowconfig

**Comment by zenz** [comment]
@gengjiawen Thank you!

**Comment by gengjiawen** [comment]
@TheSavior Looks like a flow issue, can you find some people work on this ?
```cmd
$ flow check --flowconfig-name .flowconfig.android
Error --------------------------------------------------------------- IntegrationTests/AccessibilityManagerTest.js:16:39

Cannot resolve module `RCTDeviceEventEmitter`.

   16| const RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');
                                             ^^^^^^^^^^^^^^^^^^^^^^^


Error -------------------------------------------------------------------------- IntegrationTests/AppEventsTest.js:18:28

Cannot resolve module `deepDiffer`.

   18| const deepDiffer = require('deepDiffer');
```

**Comment by gengjiawen** [comment]
I have reported to flow team too, https://github.com/facebook/flow/issues/7138.

**Comment by gengjiawen** [comment]
Update: fb look into this, hopefully we can fix this soon.

**Comment by jamesisaac** [comment]
I believe this should fix it: https://github.com/facebook/flow/pull/7419

**Comment by zenz** [comment]
@jamesisaac Thank you for the information. It's not yet apply to release package yet. So I will just wait because I don't want to compile it by myself.

**Comment by gengjiawen** [comment]
@jamesisaac Looks like still not working, see windows build on this pr: https://github.com/facebook/react-native/pull/21401.

**Comment by jamesisaac** [comment]
@gengjiawen Unrelated error?  Or am I looking in the wrong place?  [Here](https://ci.appveyor.com/project/Facebook/react-native/builds/22485188/job/q6idnkgi2bousw22) all I see is:

```
C:\projects\react-native\node_modules\flow-bin\cli.js:17
  throw new Error('Platform not supported.');
  ^
```

I.e. Flow is not even starting correctly on AppVeyor.  Whereas this issue is about the "Cannot resolve module" error once Flow does run.

Had a quick look at `cli.js` but I'm not really familiar with the pattern they're trying to use there, so not sure why it's not working on AppVeyor.

**Comment by gengjiawen** [comment]
Is it because the flow server won't start on windows ?

**Comment by gengjiawen** [comment]
Also on my windows 10 it still failed with
```console
npm ERR! code ELIFECYCLE
npm ERR! errno 110
npm ERR! react-native@1000.0.0 flow-check-android: `flow check --flowconfig-name .flowconfig.android`
npm ERR! Exit status 110
npm ERR! 
npm ERR! Failed at the react-native@1000.0.0 flow-check-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Flow seems pretty much unusable in windows.

**Comment by jamesisaac** [comment]
On my Win10 machine this works fine in Git Bash and PowerShell:

```bash
$ git clone https://github.com/facebook/react-native
$ cd react-native
$ yarn install

$ yarn flow
# Flow check finishes, 2 errors about `unclear-type` (`any` usage).
# Prior to fix it would have come back with hundreds of "Cannot resolve module" errors.

$ yarn run flow-check-android
# Again, flow check finishes with 2 `unclear-type` errors.
```

Try running `yarn flow` instead of `yarn run flow-check-android` as it gives more interactive output.  But I do think this is an unrelated issue to the one in this topic / my PR.

**Comment by zenz** [comment]
with react-native@0.59.0-rc3 and flow-bin@0.93.0(not 0.92.0), this issue gone.

**Comment by gengjiawen** [comment]
Glad it works. But still need to do work on this repo since there is another issue on windows. I will close this issue for now.
