### ISSUE TITLE
Fix StrictMode warnings

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#22186]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 33.30 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.10.1 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        API Levels: 19, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
When wrapping the app with `<StrictMode>`, there are warnings coming from internal react native components.

It seems to be the use of legacy context api on [VirtualizedList](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L468)/[CellRenderer](https://github.com/facebook/react-native/blob/41eb2da33bafc450d5fcf03990d4dbeac5d5a5e6/Libraries/Lists/VirtualizedList.js#L1647) and [UNSAFE_componentWillReceiveProps](https://github.com/facebook/react-native/search?q=UNSAFE_componentWillReceiveProps&unscoped_q=UNSAFE_componentWillReceiveProps) on multiple other files.

<div>
<img width="300" src="https://user-images.githubusercontent.com/619186/48099194-f486f800-e205-11e8-97da-a45ef2f25cb4.png" />
<img width="300" src="https://user-images.githubusercontent.com/619186/48099196-f486f800-e205-11e8-9277-d3cc15d1b9b4.png" />
</div>

**Comment by Jyrno42** [comment]
Will be working on this over the weekend.

**Comment by Jyrno42** [comment]
Opened two PRs for ScrollView and AnimatedComponents/Touchables:

- https://github.com/facebook/react-native/pull/24214
- https://github.com/facebook/react-native/pull/24218

**Comment by ConnorSBrady** [comment]
@Jyrno42 I see this is marked as help wanted. A few friends and I, Computer Science students, would love to help with this issue. Please let us know!

**Comment by Jyrno42** [comment]
@ConnorSBrady Feel free to grab the ScrollView/VirtualizedList - I am currently only working on createAnimatedComponent.

**Comment by renchap** [comment]
This is still valid, at least those 2 internal components are using unsafe hooks:
- `AnimatedComponent`
- `ScrollViewStickyHeader`

It looks like `ScrollViewStickyHeader` was converted to a function component at some point, but [this has been reverted](https://github.com/facebook/react-native/commit/4384c32aad6a6b815504da710d19288954af190e) and I am not sure why.

**Comment by obasille** [comment]
Found another one:
> findHostInstance_DEPRECATED was passed an instance of TouchableNativeFeedback

Indeeded `findHostInstance_DEPRECATED` is imported and used in `TouchableNativeFeedback.js`

**Comment by sammy-SC** [comment]
`AnimatedComponent` and `ScrollViewStickyHeader` are now StrictMode compatible.

`AnimatedComponent` resolved by https://github.com/facebook/react-native/commit/5e863fc42c8a2b27f4a785766eb643de9a243b2d
`ScrollViewStickyHeader` resolved by https://github.com/facebook/react-native/commit/925e81ab86c9807b66d405d914e857b978b194fd

**Comment by AdityaVandan** [comment]
@sammy-SC I am still getting warnings while using animated component in my react-native app while in StrictMode
react-native: 0.70.7
react: 18.1.0
![Simulator Screenshot - Rippling iPhone 14 - 2023-07-05 at 20 00 16](https://github.com/facebook/react-native/assets/35309453/ca164f2a-ceff-40ac-9c5d-2d30e70cd891)

**Comment by mateoguzmana** [comment]
I exhaustively checked all examples we have in the RNTester app by wrapping it with `StrictMode` and only found one component that was still non-strict mode compatible. It might be fixed in #48522, if that lands, I think we can close this issue until it gets reported again with specific cases as there seem to be none left.

**Comment by cortinico** [comment]
Those 2 PRs from @mateoguzmana 

- https://github.com/facebook/react-native/pull/48619
- https://github.com/facebook/react-native/pull/48620

Should fix most of the violations. Closing
