### ISSUE TITLE
Image onLoad and onLoadEnd do not fire on iOS

### ISSUE THREAD

**Issue by shaneosullivan** [facebook/react-native#2289]
The onLoad and onLoadEnd functions never fire for me on iOS.  The onLoadStart fires, and the image shows up correctly, but the other two functions never fire.  This is when using a remote image, e.g.
```
<Image
  source={{uri: 'http://chofter.com/random/arrow.gif'}}
  onLoadStart={() => {console.log('load start');}}
  onLoadEnd={() => {console.log('load end');}}
  onLoad={() => {console.log('load');}}
/>
```

**Comment by nicklockwood** [comment]
You seem to have onLoadEnd registered twice - I don't know if that's related.

**Comment by shaneosullivan** [comment]
No, just a typo in the example.  onProgress doesn't fire either

**Comment by nicklockwood** [comment]
There was a big refactor of the network implementation recently, so this has probably been fixed in https://github.com/facebook/react-native/pull/2287

**Comment by shaneosullivan** [comment]
Thanks - I just pulled master and it's broken there.  Worth testing to be sure

**Comment by shaneosullivan** [comment]
I pulled master again, so I should have #2287 , but onLoad still does not fire for me.

**Comment by shaneosullivan** [comment]
OK, pulled again and it's working. Will close this.

**Comment by simonas88** [comment]
This should be reopened. None of the onLoad callbacks are being called when the image uri is local to the iOS device. (affects versions 0.47.0 and 0.50.4).

**Comment by monkingame** [comment]
same issue +1
