### ISSUE TITLE
Can't modify text in TextInput onChangeText callback on Android

### ISSUE THREAD

**Issue by rogerbright** [facebook/react-native#23578]
## 🐛 Bug Report
On Android, modifying the text within the onChange (or onChangeText) callback causes corruption of the text in the TextInput. (Not tested on iOS.)

For example, I'm trying to force all caps in my TextInput field. (This is to work around the react native autoCapitalize issue described here: https://github.com/facebook/react-native/issues/8932). So if a lowercase letter is entered, I change it to uppercase in the callback. Unfortunately, *alternate* keystrokes cause the entire previous text to be duplicated, but only if the entered keystroke was lowercase.

So, when forcing all caps, entering `1234` results in `1234` showing up; entering `ABCD` results in `ABCD` showing up; but entering `abcd` results in `AABCAABCD`.

This issue disappears if assigning a Math.random() key to the TextInput; but then of course so does the keyboard focus, making this an unacceptable workaround.

## To Reproduce
See "Bug Report" and "Code Example" sections.

## Expected Behavior
One should be able to modify the value inside TextInput's change callbacks, without the text becoming corrupted on the subsequent redisplay.

## Code Example
    export default class TestScr extends Component
    {
	  constructor(props)
	  {
		super(props);
		this.state = { s6: '' };
	  }
	  textchg(event)
	  {
		const {eventCount, target, text} = event.nativeEvent;
                // one would expect the contents of s6 to display after the redraw
		this.setState({ s6: text.toUpperCase() }); 
  	  }
	  render()
	  {
                // [same behavior if using onChangeText instead of onChange]
		let jsx0 = <View style={{ flexDirection: 'row' }} key={ 'hi' }>
			<TextInput placeholder={ 'hello' } value={ this.state.s6 }
				onChange={ (evt) => this.textchg(evt) }
				keyboardType={ 'default' } />
			</View>;
			
		return (<View style={{ backgroundColor: '#ffffff', padding: 10, }}>
			<ScrollView style={{ backgroundColor: '#ffffff', }}>
				{ jsx0 }
			</ScrollView>
		</View>);
	  }
    }

## Environment
  React Native Environment Info:
    System:
      OS: Linux 3.19 Ubuntu 14.04.3 LTS, Trusty Tahr
      CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 2.53 GB / 15.38 GB
      Shell: 6.18.01 - /bin/tcsh
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      npm: 5.6.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 26.0.3, 27.0.3, 28.0.2
        API Levels: 10, 16, 23, 26, 27, 28
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by rogerbright** [comment]
Shouting into the wind! Hope the next person can use this as a basis for reporting the issue.

**Comment by hramos** [comment]
Sorry about that, but it's really important to make sure the issue is present in the latest release. We've had plenty of issues reported for bugs that have been fixed already.

**Comment by CatapultJesse** [comment]
Unable to replicate: https://snack.expo.io/@jkcooper/rn-issue-#23578---textinput-on-change

**Comment by rogerbright** [comment]
Still happening on latest release. I've updated the `react-native info` text in the description.

**Comment by ericlewis** [comment]
@rogerbright is this happening in emulator, or on device?

**Comment by rogerbright** [comment]
Tested just now on both an emulator (Nexus 5X API 28) and an actual device (Galaxy Tab A SM-T580). Same results on both.

**Comment by ericlewis** [comment]
Would you be able to setup a snack demonstrating this issue?

**Comment by rogerbright** [comment]
Sure.

https://snack.expo.io/By1LO7uUV

In the snack interface, the bug appears only on Android. Works correctly on iOS.

**Comment by ericlewis** [comment]
@rogerbright ty I will take a look at this!

**Comment by umair-khanzada** [comment]
I am facing the same issue.
I have explain the isuue here https://github.com/facebook/react-native/issues/23663#issuecomment-471537331

**Comment by rogerbright** [comment]
@umair-khanzada your issue seems different. In my case, the callbacks are being called just fine... it's what happens when I modify the text that makes things screwy.

**Comment by grabbou** [comment]
Thanks @ericlewis for volunteering to fix it! I think this is really annoying and severe issue, but fortunately, it's not affecting many of our developers. 

I am going to label this "mid-pri" while we are waiting for the PR.

**Comment by brentvatne** [comment]
this happens with setNativeProps directly as well: https://github.com/facebook/react-native/issues/24409

**Comment by thymikee** [comment]
Can confirm this also happens on RN 0.59 as well. Looks like I didn't need to modify controlled text input in a while, but when I did I remember using an overlay over transparent uncontrolled text input that would display the transformed text. I'd say it's pretty serious bug (and pretty old, happens at least since 0.57).

**Comment by brentvatne** [comment]
here's a video of a repro: https://streamable.com/j4s4r

and the code (i tested this on 0.57 and 0.59):

```jsx
import * as React from 'react';
import { Text, TextInput, View, StyleSheet } from 'react-native';

class ControlledInput extends React.Component {
  state = {
    value: '',
  };

  _handleChangeText = ({ nativeEvent: { text } }) => {
    this.setState({ value: text.toUpperCase() });
  };

  render() {
    return (
      <TextInput
        style={{
          width: 300,
          height: 50,
          padding: 10,
          backgroundColor: '#fff',
          borderWidth: 1,
          borderColor: '#eee',
          borderRadius: 2,
        }}
        onChange={this._handleChangeText}
        value={this.state.value}
      />
    );
  }
}

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <ControlledInput />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});
```

and a snack: https://snack.expo.io/@notbrent/ranting-sandwich

**Comment by slavikdenis** [comment]
Any ideas for a workaround?

**Comment by rogerbright** [comment]
You could mess around with a Math.random() key for the input field. This blurs the focus after each keystroke though, so you'd have to write code to re-focus and move the cursor to the end. Personally, I no longer modify the input at all on Android, and instead just do the all-caps (or whatever) on the back end before saving to the DB. Not the best user experience. It's too bad the RN team seems uninterested in fixing pretty major issues like this one, and instead seems to spend their time making breaking changes to APIs, moving things arbitrarily out of the core APIs, etc.

**Comment by AnOptimistSeePessimist** [comment]
method: `<TextInput  autoCorrect={false} />`

**Comment by 509dave16** [comment]
@slavikdenis @rogerbright @thymikee @umair-khanzada 
I have two different solutions. They aren't exactly adequate for all scenarios. Text selection being one of them. But hopefully they will be of some use:
https://snack.expo.io/@509dave16/android-text-input-out-of-sync-solutions

A text input component that displays a mask over the actual text input.
And a text input that extracts the correct value from the onChangeText.

**Comment by 509dave16** [comment]
@hramos I have created a new more up to date issue on this. If you would like for de-duplication purposes, I could move all of the content from this #26017 over here to a comment. Let me know what you think.

**Comment by 509dave16** [comment]
## My report of this bug
### Summary
When attempting to ignore certain characters by controlling the state value that's passed to the TextInput, the TextInput's natively held value get's out of sync. This makes it impossible to enforce a particular text pattern at the time of a user entering the text. This exact issue was occurring before React Native 57.1 on iOS, as noted here in this now closed issue #18874 .
  
### React Native version: 0.59.8(based on Expo SDK 34)

### Steps To Reproduce
1. Implement an `onChangeText` event handler that will selectively choose to not update the state value(which control's the TextInput's natively stored value). For example, let's say uppercase letters like 'A', 'B', 'C', etc...
2. Enter characters other than the ones to be ignored
3. Enter at least 1 or more of the ignored characters
4. Go back to entering characters other than the ones to be ignored

### Describe what you expected to happen:
1. Enter 'abc', resulting in 'a', 'ab', and 'abc' being passed to onChangeText handler each of which are valid and are set on the state value that controls the TextInput.
2. Enter 'A' which should be ignored, thus 'abcA' will not be set on the state value that controls the TextInput. Meaning only 'abc' is still displayed in the TextInput.
3. Enter 'd', which should result in onChangeText handler receiving 'abcd' which is valid and will be set on the state value that controls the TextInput.

### Snack, code example, screenshot, or link to a repository
1. **Snack** [here](https://snack.expo.io/@509dave16/testing-textinput-ignore-characters)
2. **Screenshots** that follow the steps outlined in the **Describe what you expected to happen** section above. Notice after entering 'A' that a pattern emerges in the natively held text value. It concatenates the characters that have been entered to the state controlled value that has remained at 'abc' since the character 'A' was entered. 
    - Enter 'a'
    - <img src="https://user-images.githubusercontent.com/2925882/62826582-fb66e080-bb72-11e9-859d-3b302b88edff.png"  width="200" height="400" />
    - Enter 'b'
    - <img src="https://user-images.githubusercontent.com/2925882/62826654-e179cd80-bb73-11e9-842f-79ee752a69e9.png"  width="200" height="400" />
    - Enter 'c'
    - <img src="https://user-images.githubusercontent.com/2925882/62826663-0110f600-bb74-11e9-81c0-31e98e84d22e.png"  width="200" height="400" />
    - Enter 'A'
    - <img src="https://user-images.githubusercontent.com/2925882/62826667-184fe380-bb74-11e9-91dc-9401ddcb0c58.png"  width="200" height="400" />
    - Enter 'b'
    - <img src="https://user-images.githubusercontent.com/2925882/62826672-42a1a100-bb74-11e9-8d63-b03b7ea3f735.png"  width="200" height="400" />

**Comment by anees-syook** [comment]
Exists in `react-native 0.59.10` too.

**Comment by lgenzelis** [comment]
I am not sure if this would also work on IOS, but it solved the problem for me on Android. The answer is quite simple: **NEVER** use value when rendering a `TextInput`. Use `defaultValue` instead. 

If this turns out to really fix the issue for every platform, maybe we could just issue a warning every time someone uses `value` as a prop to `TextInput`.

**Comment by moshfeu** [comment]
@lgenzelis, thanks! So what `value` is good for again?

**Comment by Aetf** [comment]
This is still affecting me.

**Comment by brentvatne** [comment]
yeah this is still an issue as far as i know

**Comment by thozh** [comment]
> I am not sure if this would also work on IOS, but it solved the problem for me on Android. The answer is quite simple: **NEVER** use value when rendering a `TextInput`. Use `defaultValue` instead.
> 
> If this turns out to really fix the issue for every platform, maybe we could just issue a warning every time someone uses `value` as a prop to `TextInput`.
> 
> UPDATE: I've tried this in iOS, and it also works.

Thanks  😃, using defaultValue instead of value indeed solved the problem

**Comment by taeingyu** [comment]
`defaultValue` doesn't solve the problem. If you want to mask user inputs and show user masked inputs, still have to use value prop.

**Comment by saulojoab** [comment]
Still an issue.

**Comment by tolypash** [comment]
I can confirm this is still an issue. Need to control input to be in MM/YY form. Sadly no way to do this since by binding the value to a state and updating the state onChangeText does not seem to work.

**Comment by dphurley** [comment]
Still seeing this over here as well.

**Comment by Kartikeya18153** [comment]
This issue still persists. This is a pretty serious issue for inputting text and there is no special workaround except make a specific event triggering component (like a button) to ensure the textchange happens correctly. Using onEndEditing and oneSubmitHandler also doesn't do anything. Please correct this soon.

**Comment by jafar-jabr** [comment]
Still present in "v0.63.2" which was released couple days ago.
@hramos

**Comment by vyshakh** [comment]
Came across the same issue.  I wanted to replace the Arabic numerals with English numerals.  As @rogerbright mentioned, I ended up using Math.random() key to TextInput (unacceptable workaround though). In my case users rarely types Arabic numerals. 
The below code replaces ٠ with 0 and ١ with 2  and so on. 

```
import React, { useState, memo, useRef } from 'react';
import { TextInput } from 'react-native';

//TEST
const mapping = {
    '0': 'A',
    '1': 'B',
    '2': 'C',
};

 const mapping = {
     '٠': '0',
     '١': '1',
 }

const updateValue = (val) => {
    if (!val) return val;
    const keys = Object.keys(mapping);
    const regexExpr = new RegExp(keys.join('|'), 'gi');
    if (val.match(regexExpr)) return val.replace(regexExpr, (matched) => mapping[matched]);
    return val;
};

export default memo((props) => {
    const [key, setNewKey] = useState(null);
    const refContainer = useRef(null);
    const onChangeText = (val) => {
        if (props.onChangeText) {
            let newVal = updateValue(val);
            if (newVal != val) {
                setNewKey(`key_${Math.random()}`);
                setTimeout(() => {
                    refContainer.current.focus();
                }, 50);
            }
            props.onChangeText(newVal);
        }
    };
    let randKeys = {};
    if (key) randKeys = { key };
    return <TextInput {...randKeys} {...props} ref={refContainer} value={props.value} onChangeText={onChangeText} />;
});

```

**Comment by anchi20** [comment]
Here, before it becomes stale.

https://snack.expo.io/@anchi/8017c6

PS: run this on a real device.

**Comment by AndriiChubariev** [comment]
Experience the same bug right now. Basically there is no way to implement something as simple as masked input.

**Comment by JaapWeijland** [comment]
Same here. Experiencing this with `react-native-masked-input`.

**Comment by mdccg** [comment]
(｡•́︿•̀｡)

**Comment by AhmedKhattak** [comment]
same here on version "v0.63.2"

**Comment by rashidmakki** [comment]
This problem was happening with my react-native App too. What I did is that I created an individual components outside the main component( where we will place this component) keeping TextInput as a whole(i.e according to our requirement that means what field do we need) in one single component. Passing the value as props to this component(if required) and changing it whenever we require using onChangeText. .The problem was solved in my App.

**Comment by fabriziobertoglio1987** [comment]
Hello ReactNative Developers! :smiley: 

I just prepared Pull Request https://github.com/facebook/react-native/pull/29070 that seems to solve this issue

**<details><summary>PREVIEWS OF THE BUGFIX</summary>**
<p>

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/83887390-a7079f80-a748-11ea-847e-bd9ee3065982.gif" width="200" height="" /> | <img src="https://user-images.githubusercontent.com/24992535/83886853-eda8ca00-a747-11ea-96eb-dc179fbd9f92.gif"  width="200" height="" /> |

</p>
</details>

You can contact me by email at fabrizio.developer@gmail.com

Please head over to the Pull Request https://github.com/facebook/react-native/pull/29070 and thumbs up if you like it.
If you want to get this fix you can follow the instructions for [building ReactAndroid](https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native) or checkout my [video introduction on forking react-native](https://youtu.be/9RQ2GiApkzU?t=420) (patch-package does not work).

If you don't like the pr please feel free to leave a code review or comment, I'll be happy to add improvements and changes.

Thanks a lot :pray: :peace_symbol: :beach_umbrella:

**Comment by RigoTheDev** [comment]
@fabriziobertoglio1987 You are awesome! Thank you so much.

**Comment by joncardasis** [comment]
What I got to work on Android while @fabriziobertoglio1987's PR is open. I want text input to be uppercased. `autoCapitalize='characters'` works on iOS but there needs to be some additional properties so android doesn't jumble keystrokes
```JS
<TextInput
                autoCorrect={false}
                autoCapitalize={Platform.OS === 'ios' ? 'characters' : undefined}
                secureTextEntry={Platform.OS === 'ios' ? false : true}   // Add this for android to prevent duplicate keystrokes
                keyboardType={Platform.OS === 'ios' ? undefined : 'visible-password'}  // Add this for android to prevent duplicate keystrokes
                defaultValue={code}  // Use `defaultValue` instead of `value`
                onChangeText={(text) => setCode(text.toUpperCase()) }
                style={styles.textInputLarge}
                placeholder="enter code"
                returnKeyType="send"
                textContentType="oneTimeCode"
                maxLength={6}
              />
```

**Comment by gbalduzzi** [comment]
I'm having the same issue having to "format" the user input into an uppercase format. In my case the problem was solved using `autoCorrect={false}`.

It was indeed a very weird problem, very hard to debug and hard to search for (I found this thread after quite some researching - probably I need to work on my google ability).

Thank you @fabriziobertoglio1987 for working on a fix.

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29070 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by aJieBai** [comment]
same here on version "v0.66.4" God!!

**Comment by thomazcapra** [comment]
Same here on version "v0.68.1"

**Comment by thomazcapra** [comment]
> FWIW, I did end up solving this issue and many others. The solution starts with an "F" and rhymes with "butter." I realize that's not an option for everyone.
Flutter doens't have this issue, right?

**Comment by rogerbright** [comment]
Correct. I'm only six months in but so far my impression is that Flutter/Dart is mature, well thought-out, concise, and free of sanctimony.

**Comment by fabriziobertoglio1987** [comment]
I look again into this when I have more free time. I need to update my PR with the improvements included in https://github.com/facebook/react-native/pull/33468. For this reason https://github.com/facebook/react-native/pull/29070 is back to draft. We can not trigger setText in a ReactEditText. `replace` is used on purpose. Sorry for the delay in the development of this fix.

**Comment by mathbalduino** [comment]
Hey guys, any news on this one?

**Comment by danielcrk** [comment]
I guess not.

**Comment by hieucd04** [comment]
+1

**Comment by chancegraff** [comment]
I haven't read through the entire comment history here, but the title of this issue does not match the description of the iOS issue that was "closed as duplicate": https://github.com/facebook/react-native/issues/24585 The older issue should be reopened.

**Comment by chancegraff** [comment]
I'm seeing this on iOS but I suspect it's because of one of the packages I have installed.

```
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.3",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/native-stack": "^6.9.8",
    "api-interface": "*",
    "expo": "^47.0.13",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "^1.4.2",
    "firebase": "^9.15.0",
    "immer": "^9.0.17",
    "jest": "^29.3.1",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-dotenv": "^3.4.7",
    "react-native-paper": "^5.1.3",
    "react-native-plaid-link-sdk": "^8.0.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-text-input-mask": "^3.1.4",
    "react-native-web": "^0.18.10",
    "workspace-config": "*",
    "zustand": "^4.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.12",
    "@types/react": "^18.0.26",
    "@types/react-native": "^0.71.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-plugin-root-import": "^6.6.0",
    "expo-cli": "^6.1.0",
    "typescript": "^4.9.4"
  },
```

**Comment by saschagehlich** [comment]
@chancegraff I have the same issue on iOS, were you able to fix this?

**Comment by jcubic** [comment]
The same issue on Android in Emulator. It works fine for the Expo playground so don't use it to test.

Simple reproduction:

```jsx
const ControlledComponent = () => {
  const [state, setState] = useState('0.00');
  const cursor = 1;
  return (
    <TextInput
      ref={ref}
      autoFocus
      onKeyPress={() => { /* empty */ }}
      selection={{start: cursor, end: cursor}}
      value={state}
      keyboardType="numeric"
    />
  );
};
```
There is no way to prevent default behavior, `event.preventDefault()` also doesn't work. The input is always updated even if the component is controlled.

**Comment by cihangir-mercan** [comment]
The issue still persists on both IOS and Android

I try to limit decimal points to 8 length. The user sees 9th character shortly before removal. It causes flickery.

https://snack.expo.dev/N5IcDRFWc

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? 

I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+). 

If you still experience this issue, I will prepare a patched release with the fix.

Thanks a lot

**Comment by DanielO199** [comment]
Yes, this bug still occurs. Please take care of it

**Comment by yuki384** [comment]
@fabOnReact 
Yes, the issue still persists (on iOS). If you could tackle this, it would be incredibly appreciated!

**Comment by mkhoussid** [comment]
> Do you still experience this issue?
> 
> I have four years of experience maintaining facebook/react-native and I specialize in the Text and TextInput components. I currently have 58 [facebook/react-native PRs](https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+).
> 
> If you still experience this issue, I will prepare a patched release with the fix.
> 
> Thanks a lot

Kind of a hacky work around (and doesn't always work quite as expected):

```
const onChange = (e: string) => {
    if (isValidInput(e)) {
        ref.current?.setNativeProps({ text: e });
    }
}
```

**Comment by yuki384** [comment]
> Kind of a hacky work around (and doesn't always work quite as expected):
> 
> ```ts
> const onChange = (e: string) => {
>     if (isValidInput(e)) {
>         textInputRef.current?.setNativeProps({ text: e });
>     }
> }
> ```


Thank you!  I already tried that, but It's still flickering on device... It works fine on Simulator. 
Incidentally, I would like to prevent type new lines.

**Comment by mkhoussid** [comment]
> > Kind of a hacky work around (and doesn't always work quite as expected):
> > ```ts
> > const onChange = (e: string) => {
> >     if (isValidInput(e)) {
> >         textInputRef.current?.setNativeProps({ text: e });
> >     }
> > }
> > ```
> 
> Thank you! I already tried that, but It's still flickering on device... It works fine on Simulator. Incidentally, I would like to prevent type new lines.

Can you try something like this?

```
. . .
const previousValueRef = React.useRef('');
. . .
const onChange = (e: string) => {
    if (textInputRef.current) {
        const textInput = textInputRef.current;
        textInput.setNativeProps({ text: previousValueRef.current });
        if (isValidInput(e)) {
            textInput.setNativeProps({ text: e });
            previousValueRef.current = e;
        }
    }
}
. . .
```

**Comment by fabOnReact** [comment]
This PR is included in the [react-native-improved](https://github.com/fabriziobertoglio1987/react-native-improved) library:

# react-native-improved

- **Supports ONLY react-native 0.73**.
- Supports only old architechture (new architechture is WIP)

## Set-up

In package.json

```diff
 "scripts": {
+  "postinstall": "yarn run react-native-patch"
 }
```

Then

## npm

```sh
npm install react-native-improved --save-dev
```

## yarn v1

```sh
yarn add react-native-improved --dev
```

**Comment by yuki384** [comment]
> Can you try something like this?

Thank you! 
This did not work out well either. However, it might have been due to me including a Text component as a child of TextInput to finely control the style :
```
<TextInput ... >
  <Text>Some</Text>
  <Text style={{ ... }}>String</Text>
</TextInput>
```
For my case, I've decided to use a custom Native Module, but I'll give your solution a try another time.

**Comment by jcubic** [comment]
A PR was created a year ago, I don't know what else I can do.

**Comment by cortinico** [comment]
> A PR with a fix was created a year ago, I don't know what else I can do.

What's the PR?

**Comment by jcubic** [comment]
It was linked:

https://github.com/facebook/react-native/issues/38155

**Comment by cortinico** [comment]
> It was linked:
> 
> #38155

That's an issue, not a PR

**Comment by jcubic** [comment]
> That's an issue, not a PR

Ah sorry my mistake, I thought it was the issue where I created a PR for.

**Comment by DmitriySosnovskiy** [comment]
Still reproduces

**Comment by Reeywhaar** [comment]
Reproduces with on-screen keyboard. With hardware one (laptop keyboard and simulator) it doesn't

**Comment by mathbalduino** [comment]
No, it is still happening...

**Comment by veliseev93** [comment]
You can try this library: https://github.com/RonasIT/react-native-controlled-input
