### ISSUE TITLE
[TextInput] using autoComplete prop on Android API < 26 crashes app

### ISSUE THREAD

**Issue by cherniavskii** [facebook/react-native#23934]
## 🐛 Bug Report

When using `autoComplete` prop on Android API < 26, app crashes.

![Screenshot_1552584737](https://user-images.githubusercontent.com/13808724/54380468-d9346980-468b-11e9-9312-5c96ad1d7c9a.png)

## To Reproduce

1. Create `<TextInput autoComplete="off" />`
2. Run app on Android API < 26

## Expected Behavior

App doesn't crash

## Code Example

https://github.com/cherniavskii/react-native-autocomplete-issue

## Environment

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz
      Memory: 4.10 GB / 15.91 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

## Additional info
This bug is reproducible in react-native@0.59.1, in react-native@0.58.6 it works as expected.
I think it was introduced in https://github.com/facebook/react-native/commit/36957dceddbf47e78d20557f40f50bbf12068d9f

Also, it is reproducible for every `autoComplete` value, not only `off`.

I've discovered it while using Downshift, which [adds `autoComplete="true"` by default](https://github.com/downshift-js/downshift/blob/5b721a13c496662402c16c5c0cb52fb2f96946b7/src/downshift.js#L797), so potentially a lot of people will encounter same issue.

**Comment by hey99xx** [comment]
From what I see https://github.com/facebook/react-native/commit/36957dceddbf47e78d20557f40f50bbf12068d9f is fixing the issue for next version, not causing it. 

The original commit https://github.com/facebook/react-native/commit/f15145639dab1e8d7a1c79a127b7d45c91d025a8 that added `autoComplete` forgot checking API versions, after the fix the API version is checked.

**Comment by dulmandakh** [comment]
It's fixed with https://github.com/facebook/react-native/commit/d4aa1e7a52b51fa5d7fc9ded132b7b50170f2190, maybe will be cherry picked for 0.59.2. Thank you

**Comment by cherniavskii** [comment]
@dulmandakh Thanks!

**Comment by tonmanayo** [comment]
Hi I am still getting this crash with 0.59.5. Crashlytics has reported over 50 users crashing with this version

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'autoComplete' of a view managed by: AndroidTextInput
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:95)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

```
Caused by com.facebook.react.bridge.JSApplicationIllegalArgumentException: Invalid autocomplete option: 
       at com.facebook.react.views.textinput.ReactTextInputManager.setTextContentType(ReactTextInputManager.java:610)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by shenjin** [comment]
I believe the correct prop is autoCompleteType

**Comment by hery** [comment]
What's the state of things here? I have an Android release running 0.59.8 that's still reporting this crash.

**Comment by hey99xx** [comment]
open a new github issue with your stacktrace, this one's already closed.

**Comment by jamesmcn1** [comment]
Thanks @shenjin :) It appears autoComplete prop has been removed from textfield components in favor of autoCompleteType. See docs: https://facebook.github.io/react-native/docs/textinput.html#props
