### ISSUE TITLE
NativeModule call performance reduced since RN58

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#25057]
We at Discord just upgraded from RN57 to RN59 and immediately noticed a slow down while doing certain actions in our app. Since our chat view is actually a native component we ship it large arrays of messages and emojis. It became clear the bottleneck was coming from this. After doing some research of what changed since RN57 it was clear the JSExecutor has been refactored and seems to have changed how it handles arguments of native module methods. Large arrays or dictionaries are up to 10x slower to serialize in method calls. 

We tried the most obvious solution and changed our native modules to take a JSON blob that we manually `JSON.stringify` and then we deserialize manually in the native module. For an average channel on Discord the call time went down from 40ms to 4ms and for our emoji picker it went from 400ms to 30ms. 

We solved this problem for ourselves with a workaround, but generally wanted to ask here if this was an intended side effect of the refactor (which I assume was done to enable the coming TurboModules)? 

If this is intended feel free to close this issue.

## React Native version
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 3.35 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: discordapp/react-native#0.59.8-discord => 0.59.8-discord 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Create a basic native module that receives an array as an argument.
2. Create an array of 1000 small dictionaries.
3. Invoke `NativeModules.MyNativeModule.myTestMethod(array)` 
4. Try again on RN57 and notice the performance is much better.

**Comment by kelset** [comment]
Hey 👋

We just released the first RC for 0.60, would you mind creating a small repro using that version?

**Comment by vishnevskiy** [comment]
@kelset Just tried it out and looks like it is behaving the same as 0.59.8, so unfortunately not fixed.

Anecdotally even with our fix for our specific call sites the whole app feels slower than on 0.57 and not sure the best way to measure the delta. If true that means this is probably affecting other things like React's diffs being sent to the main thread.

**Comment by kelset** [comment]
Understood - currently how are you benchmarking/which tools are you using?

**Comment by vishnevskiy** [comment]
For the repro steps above can simply wrap it with a `console.log` for the most simple debug tool :)

```javascript
const startTime = Date.now();
NativeModules.MyNativeModule.myTestMethod(array);
console.log('Call Time', Date.now() - startTime);
```

Assuming you follow the repro steps this should spit out a very large number.
