### ISSUE TITLE
TypeError: Network request failed On Android

### ISSUE THREAD

**Issue by keyz23** [facebook/react-native#25244]
Hi Everyone, I found this problem on my React-Native Android App.
When I using a fetch to communicate with a working api, this type of error is returned to me.

> TypeError: Network request failed

I Used the Chrome debbuger and I found this:

`TypeError: Network request failed
at XMLHttpRequest.xhr.onerror (whatwg-fetch.js:504)
at XMLHttpRequest.dispatchEvent (event-target.js:172)
at XMLHttpRequest.setReadyState (XMLHttpRequest.js:580)
at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:394)
at XMLHttpRequest.js:507
at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
at MessageQueue.__callFunction (MessageQueue.js:366)
at MessageQueue.js:106
at MessageQueue.__guard (MessageQueue.js:314)
at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:105)`

This is the code that I used:

`static creaUtente(identity, FirstName, LastName, FiscalCode , Email) {
        let formdata = new FormData();
        formdata.append('Identity', identity);
        formdata.append('FirstName', FirstName);
        formdata.append('LastName', LastName);
        formdata.append('FiscalCode', FiscalCode);
        formdata.append('Email', Email);

        console.log(Configuration.base_url.rest + Configuration.apiRoutes.signUp)
        console.log(formdata)

        return new Promise((resolve, reject)=> {
            fetch('https://linktotheapi.com',{
                method: 'POST',
                headers: {
                    'Content-Type': 'multipart/form-data',
                },
                body: formdata
            })
            .then((response) => response.json())
            .then((responseData) => {
                if(responseData.Error){
                    Alert.alert("Errore");
                }
                global.utente = responseData;
                resolve(responseData)
            })
            .catch((err) => {reject(err)})
        })
    }`

I manually tried to use the API and it works. So the problem is fetch.
I have seen and read that a lot have encountered this problem on android without a real solution.

The API link is a link type: https: //****.com (it is not a localhost).
I tried to use the http version of the API but the error still appears.

Now, This is my package.json

`    dependencies": {
    "@react-native-community/async-storage": "^1.4.2",
    "buffer": "^5.2.1",
    "pouchdb-adapter-asyncstorage": "^6.4.1",
    "pouchdb-authentication": "^1.1.3",
    "pouchdb-find": "^7.0.0",
    "pouchdb-react-native": "^6.4.1",
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-ble-manager": "^6.6.2",
    "react-native-ble-plx": "^1.0.3",
    "react-native-json-tree": "^1.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-tab-navigator": "^0.3.4",
    "react-native-vector-icons": "^6.4.2"
  },
  "devDependencies": {
    "@babel/core": "7.4.3",
    "@babel/runtime": "7.4.3",
    "babel-jest": "24.7.1",
    "jest": "24.7.1",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}`

I have read that this problem is on Android Device ( I obviously added internet permissions in the Manifest file ). Do you know nothing about this problem??

**Comment by 823844596** [comment]
did you solve it? i met too...

**Comment by keyz23** [comment]
No I haven't solve it...

**Comment by keyz23** [comment]
Nobody?

**Comment by Valiums** [comment]
hey @keyz23  @823844596, 
I recently encountered something similar using fetch and  formDatas (only on Android though). 
The workaround that worked for me was to use XMLHttpRequest instead of fetch. 
Hopefuly this will help you too!

**Comment by amohit1315** [comment]
Was anyone able to solve it??
I am facing similar issue with fetch. I have to use common code for android and iOS. fetch works great in iOS but in android throws error.

Trying to fetch data from remote server via api.
Using fetch(https:url:port) to fetch the data. But every time android emulator as well as physical device gives network request failed. While I can access same url within browser of emulator.

I have already went through various links, and many people have posted same problem but none of them had ample solution that works. While some people were not able to access localhost via api-call but it was resolved using IP address of system. But in my scenario I am trying to access remote host. Also domain name cannot be used in my scenario, so need a solution using (ip) in fetch method=get.

testlogin = https://10.209.7.115:8080/api/v1/
Basicauth = 'Basic cm9vdDpyb290'

fetch(testingLogin, {
        method: "GET",
        cache: "no-cache",
        mode: "cors",
        withCredentials: true,
        credentials: "include",
        headers: {
          'Authorization':Basicauth,
          Accept: "application/json",
          "Content-Type": "application/json"
        }
      }).then(response =>
        {
        if(response.status === 200)
        {
         this.props.navigation.navigate('Home');
        }
        else
        {
          alert("Authorization failed");
        }
      })
       .catch(error => {
         alert("**Request Failed** :Check the ip address Entered:Problem with server ");
         throw(error);

       })

Error:

TypeError: Network request failed
    onerror@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:24051:31
    dispatchEvent@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:28695:31
    setReadyState@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:28448:33
    __didCompleteResponse@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:28275:29
    emit@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:3280:42
    __callFunction@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2577:49
    http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2334:31
    __guard@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2531:15
    callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2333:21

**Comment by garrinmf** [comment]
@keyz23 you closed the ticket, but did you find a fix for it?

**Comment by IcebergRage** [comment]
@keyz23 @garrinmf do you find a solution ?

**Comment by Ailton265** [comment]
I have the same issue. Did any one was able to solve it?

**Comment by CYBERNEURONES** [comment]
Why this issue is not fix ?

**Comment by Dantalion** [comment]
Same issue. Still no fix?

**Comment by daybreaker** [comment]
We're having the same issue here but on iOS. Using rn 0.53. It was working fine a while ago.

The weird thing is if I have RN Debugger open, our code works. But with remote debugging turned off, everything with fetch returns a Network Request Failed error.

I know that when RN Debugger is open, RN uses V8 to run the code, and when remote debugging is off, it uses the device/simulator's native JavaScriptCore... I wonder if the most recent version of iOS has an updated version of JavaScriptCore that implements fetch differently from V8? 

I'm not educated enough in the internals of javascript engines to get much further than this, though.

Any help would be appreciated.

**Comment by DodoTheDeveloper** [comment]
Dear fellow developers, please check out my [comment](https://github.com/facebook/react-native/issues/24394#issuecomment-548280779) on the similar issue #24394 . I hope it will help some of you.

**Comment by Lpaydat** [comment]
I solved it but I'm not sure is it the same issue with you guys.

In my case, I used `expo` (in an android device) together with `relay-modern` and this error occurs when I try to fetch data from my server (localhost).

After spending an hour to find the solution with no results I just find out the source of my error.
It is the fetch url (I used `localhost` and it works in the browser so I just forgot about it).
When I change the url to the correct ip address, this issue have gone.

I hope this helps and sorry for my bad English.

**Comment by EzeRangel** [comment]
This is a problem with the cert. Your server should use intermediate certificates so Android should not reject the requests.

**Comment by Papyrus0120** [comment]
issue is not fixed then y its closed

**Comment by alanhalpern06** [comment]
I have the same problem here, the most curious thing is that this error just happen when it's a POST request, on my GET requests it's is working well.
Somebody have any ideia? 

My code:
 `
NetInfo.fetch().then(isConnected => {
            if(isConnected) {
                var url = "http://vvendas.com/api/home";
                var data = new FormData();                    

                data.append('dateBegin', dateBegin);
                data.append('dateEnd', dateEnd);
                data.append('format', 'json');

                fetch(url, {
                    method:'POST',
                    headers:{
                        'Accept': 'application/json', 
                        'Content-Type': 'application/json',
                        'Authorization': "Bearer "+ userToken
                      },
                    mode:"cors",
                    body: data,
                    redirect: 'follow'
                }).then(response => response.json())
                .then(resJSON => {

                    console.log('It WORKS',resJSON)
                }).catch(err => {
                     console.log(err)                  
                })
            }else{
                console.log('not Connected')
            }
        })

`

**Comment by ThalesCrisostomo** [comment]
Anything about that?

**Comment by alessiocancian** [comment]
Had a similar problem after upgrading react native, the only way I was able to solve it is using RNFetchBlob, as shown here: https://stackoverflow.com/a/50061209/5724186

**Comment by Baterka** [comment]
I have same problem on RN 0.62 :( Working fine in release but in debug very annoying!

**Comment by dotfelixb** [comment]
<application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>

**Comment by reidx882** [comment]
step1>
add ***android:usesCleartextTraffic="true"*** line in AndroidManifest.xml like:

<application
...
  android:usesCleartextTraffic="true"> // add this line
...
</application>

step2>
Delete all debug folder from your android folder..

**Comment by devkrkanhaiya** [comment]
step1>
add ***android:usesCleartextTraffic="true"*** line in AndroidManifest.xml like:

<application
...
  android:usesCleartextTraffic="true"> // add this line
...
</application>

step2>
Delete all debug folder from your android folder..

**Comment by akhan118** [comment]
@dotfelixb  @devkrkanhaiya  work on RN .62 👆💕

**Comment by Temirtator** [comment]
> @dotfelixb @devkrkanhaiya work on RN .62 👆💕

This solution doesnt solve my problem

**Comment by dotfelixb** [comment]
@Temirtator This is not a react native issue, is from Android so look into this, hope it helps

```xml
<application android:networkSecurityConfig="@xml/network_security_config"
                    ... >
        ...
    </application>
```

then create a file in your as ```res/xml/network_security_config.xml```

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">example.com</domain>
        <trust-anchors>
            <certificates src="@raw/my_ca"/>
        </trust-anchors>
    </domain-config>
</network-security-config>
```

you can read more at 
[Network security configuration](https://developer.android.com/training/articles/security-config)

**Comment by Temirtator** [comment]
@dotfelixb thanks for your answer. I found out, problem was with fetch request, so, to solve this problem, Im using RNFetchBlob(https://github.com/joltup/rn-fetch-blob) library, for sending files to server. But lately i'll check your solution.

**Comment by amit-tanwar** [comment]
> step1>
> add _**android:usesCleartextTraffic="true"**_ line in AndroidManifest.xml like:
> 
> <application
> ...
> android:usesCleartextTraffic="true"> // add this line
> ...
> 
> step2>
> Delete all debug folder from your android folder..

It worked for me  "react-native": "0.62.2"

**Comment by apostolou** [comment]
@amit-tanwar, @devkrkanhaiya , @dotfelixb , I've tried to insert the line you mention (add android:usesCleartextTraffic="true" ) in the AndroidManifest.xml file but didn't manage to make this work because I don't find the path of the debug folder to delete. Could you please explicitely give the path ? thanks a lot!

**Comment by dotfelixb** [comment]
@apostolou the debug folder is at "project_name//android/app/src/debug", 
not there's also an AndroidManifest.xml file that needs android:usesCleartextTraffic="true" too.

**Comment by apostolou** [comment]
@dotfelixb thanks for your feedback. Deleting the folder didn't fix the issue 👎 unfortunately.
I switched to rn-fetch-blob to make my upload work.

**Comment by amit-tanwar** [comment]
> @amit-tanwar, @devkrkanhaiya , @dotfelixb , I've tried to insert the line you mention (add android:usesCleartextTraffic="true" ) in the AndroidManifest.xml file but didn't manage to make this work because I don't find the path of the debug folder to delete. Could you please explicitely give the path ? thanks a lot!

Path is shared by @apostolou and hope you rebuild the app after following the steps. Usually (For me atleast) best approach is to close the metro server and restart with the command "react-native start --reset-cache" and rebuild the app.

**Comment by cultofdev** [comment]
same here, I can't get this to work with just a simple get request from a secured api, here is the snippet:

fetch('https://domainofapi/api/emp/position/all', {
      method: 'GET',
      cache: 'no-cache',
      mode: 'cors',
      headers: {
        'Accept': 'application/json',
      },
    })
      .then(response => response.json())
      .then(json => setPositions(json));

tied almost every solution I can find, usesCleartextTraffic, network security config, etc.

**Comment by Brianop** [comment]
@cultofdev  Did you find a fix for this ?

**Comment by cultofdev** [comment]
> @cultofdev Did you find a fix for this ?

No, after 3 days I just trashed the project and switched to flutter, and besides most of the suggested fixes that I found on the net is just a workaround and not even working..

**Comment by dotfelixb** [comment]
@cultofdev this is not a react-native bug, it's just the version of Android react-native is using

**Comment by Slals** [comment]
Project on RN v0.63.0-rc.1

I'm also getting `Network request failed` without any other infos.

I tried :
- Updating Flipper SDK to `0.44.0` and `0.46.0` ;
- Adding `android:usesCleartextTraffic="true"` in src/main/AndroidManifest.xml ;
- Commenting out all network related snippets from ReactNativeFlipper.java.

None worked, tried on a working URL, simple GET method. `fetch` is failing somewhere but I have no idea where it comes from. Anyone know how we can track this issue?

**Comment by nkpatnis** [comment]
Was facing same issue for RN 0.62.2
and was able to fix it by updating this
https://github.com/jhen0409/react-native-debugger/releases
to v0.11.3

`cleartextTrafficPermitted="true"` this should not be used in production until you know what you are doing.

**Comment by josmithua** [comment]
In my case it was only not working for localhost URLs. I changed `localhost` in the URL to my local IP and it worked. (RN 0.62.2)

**Comment by f4z3k4s** [comment]
As it seems nobody has been as careless as I were when running into this, but I'll give my two cents, hopefully it will help somebody save some time:

- [ ] The emulator that you are using has access to the internet and you are sure about it (e.g.: tested it outside of this app). If not, maybe [this link](https://stackoverflow.com/questions/42736038/android-emulator-not-able-to-access-the-internet) can help. It was the source of this issue in my case. I added Google's DNS server (`8.8.8.8`) to my Mac's network configurations and voilà, everything started to work. Note that I was working from an iPhone hotspot and that's why I had to set this up. If I am on wifi, it works perfectly without this extra configuration.

- [ ] The real device that you are using has access to the internet and you are sure about it (e.g.: tested it outside of this app).

If above boxes are checked meaning that your requests work perfectly from a browser, you could try debugging the issue further. 🤗

PS: I've just tested it on a 5ish-year-old Lenovo device with Android 5.1 and it works, also my Pixel 2 emulator with API 29.

**Comment by zcmgyu** [comment]
Just not work on Android.
android:usesCleartextTraffic="true" also does not thing

**Comment by devkrkanhaiya** [comment]
> Just not work on Android.
> android:usesCleartextTraffic="true" also does not thing

Delete all debug folder from your android folder..

**Comment by akmallmr** [comment]
Not work on me..

**Comment by yashwantt** [comment]
> step1>
> add _**android:usesCleartextTraffic="true"**_ line in AndroidManifest.xml like:
> 
> <application
> ...
> android:usesCleartextTraffic="true"> // add this line
> ...
> step2>
> Delete all debug folder from your android folder..

Awesome this worked for me

**Comment by asim47** [comment]
I fixed it by commenting a line in the
/android/app/src/debug/java/com/{your-app-name}/ReactNativeFlipper.java
file.
this is only fix that worked for me!

new NetworkingModule.CustomClientBuilder() {
@override
public void apply(OkHttpClient.Builder builder) {
// builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
}
});

**Comment by Kipsanga-Gregory** [comment]
> 
> 
> I fixed it by commenting a line in the
> /android/app/src/debug/java/com/{your-app-name}/ReactNativeFlipper.java
> file.
> this is only fix that worked for me!
> 
> new NetworkingModule.CustomClientBuilder() {
> @override
> public void apply(OkHttpClient.Builder builder) {
> // builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
> }
> });

Thanks Buddy, this one worked for me too. However, is it cool to just have that function return nothing now that we commented out its return value? please someone let me know about this

**Comment by Baterka** [comment]
>...However, is it cool to just have that function return nothing now that we commented out its return value?

Its `void` method :) it is not returning anything even when not commented ;)

**Comment by Calls4ever** [comment]
same problem looks like no body is fixing this problem

**Comment by safciplak** [comment]
> ccept: "application/json"

is it works?

**Comment by akhan118** [comment]
android/gradle.properties

Add this

FLIPPER_VERSION=0.50.0

**Comment by pedrogarciyalopez** [comment]
> android/gradle.properties
> 
> Add this
> 
> FLIPPER_VERSION=0.50.0

that's worked for me.

@akhan118 thanks a lot dude!

**Comment by Liqiankun** [comment]
@devkrkanhaiya  What are the debug folders?

**Comment by safaiyeh** [comment]
Hi all, we have a discussion here tracking this: https://github.com/facebook/react-native/issues/28551

There are a series of workarounds, mentioned in the thread. Check it out!

**Comment by Liqiankun** [comment]
#29845 For me case.

**Comment by Cyberon256** [comment]
@alanhalpern06
All should be well with these changes
`- data.append('dateBegin', dateBegin);
+ data.append('dateBegin', dateBegin.toString());
- data.append('dateEnd', dateEnd);
+ data.append('dateEnd', dateEnd.toString());

- 'Content-Type': 'application/json',
+ 'Content-Type': 'multipart/form-data',`

**Comment by Cyberon256** [comment]
@alanhalpern06
All should be well with these changes

- data.append('dateBegin', dateBegin);
+ data.append('dateBegin', dateBegin.toString());
- data.append('dateEnd', dateEnd);
+ data.append('dateEnd', dateEnd.toString());

- 'Content-Type': 'application/json',
+ 'Content-Type': 'multipart/form-data',

**Comment by Cyberon256** [comment]
@alanhalpern06
All should be well with these changes

`- data.append('dateBegin', dateBegin);`
`+ data.append('dateBegin', dateBegin.toString());`
`- data.append('dateEnd', dateEnd);`
`+ data.append('dateEnd', dateEnd.toString());`

`- 'Content-Type': 'application/json',`
`+ 'Content-Type': 'multipart/form-data',`

**Comment by Cocktails0921** [comment]
Same issues in here.
Fetch does not work well in Andorid.
It works well only IOS.
Is there any solutions to solve this?

**Comment by Liqiankun** [comment]
@Cocktails0921 #29845

**Comment by jamesjara** [comment]
Based on this code https://github.com/facebook/react-native/blob/476a336e3613f90b76e3a91d5bffaa098bf4e6ff/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L383 any request without headers content-type and payload body as string will start failing into "specified"

**Comment by lunoob** [comment]
> I fixed it by commenting a line in the
> /android/app/src/debug/java/com/{your-app-name}/ReactNativeFlipper.java
> file.
> this is only fix that worked for me!
> 
> new NetworkingModule.CustomClientBuilder() {
> @override
> public void apply(OkHttpClient.Builder builder) {
> // builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
> }
> });

good ! this worked for me too. rn version: 0.63.1

**Comment by pke** [comment]
Is this something new that appeared in a patch release? Because when I started the same code I have now could connect to the https Server I'm using.

**Comment by RahulDutta007** [comment]
> step1>
> add _**android:usesCleartextTraffic="true"**_ line in AndroidManifest.xml like:
> 
> <application
> ...
> android:usesCleartextTraffic="true"> // add this line
> ...
> step2>
> Delete all debug folder from your android folder..

Thank you, it works. You're a God

**Comment by SUMITIOS** [comment]
> hey @keyz23 @823844596,
> I recently encountered something similar using fetch and formDatas (only on Android though).
> The workaround that worked for me was to use XMLHttpRequest instead of fetch.
> Hopefully this will help you too!
> 
> I don't know if you are using expo but for me this problem started when I updated my expo SDK from 31 to 33 (so RN 0.57.1 to 0.59.8)

The same problem and solution in my case , XMLHttpRequests are working but fetch not. I am not using expo, RN version 0.62.2.

**Comment by obendevski** [comment]
Hey guys, I had the same problem. I was trying to upload audio .aac file via formData. 
For me, i had to prepend the `uri` part of the formData with `file://`.

Hope it helps someone.

**Comment by the-smart-home-maker** [comment]
> Based on this code
> 
> https://github.com/facebook/react-native/blob/476a336e3613f90b76e3a91d5bffaa098bf4e6ff/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L383
> 
> any request without headers content-type and payload body as string will start failing into "Network request failed." this is because the high-level wrappers are handing the Request Error call as "Network request failed." **but is not even reaching the internet**.
> 
> ```
>     try {
>       sendRequestInternal(
>           method,
>           url,
>           requestId,
>           headers,
>           data,
>           responseType,
>           useIncrementalUpdates,
>           timeout,
>           withCredentials);
>     } catch (Throwable th) {
>       FLog.e(TAG, "Failed to send url request: " + url, th);
>       ResponseUtil.onRequestError(getEventEmitter(), requestId, th.getMessage(), th);
>     }
>   }
> ```
> 
> 1. sendRequestInternal
> 
> ```
> else if (data.hasKey(REQUEST_BODY_KEY_STRING)) {
>       if (contentType == null) {
>         ResponseUtil.onRequestError(
>             eventEmitter, requestId, "Payload is set but no content-type header specified", null);
>         return;
>       }
> ```

@jamesjara: Awesome! I just hat to add the "Content-Type" as "multipart/form-data" and "Accept" as "application/json".--> now it works fine

**Comment by laurent22** [comment]
If that can help anyone, React Native 0.62+ seems to require a "Content-Type" header for certain fetch calls or else you get "Network request failed". More info in this issue: https://github.com/facebook/react-native/issues/30176

**Comment by impulse** [comment]
> android:usesCleartextTraffic="true"

Please avoid doing this.

You are most likely running into this issue because you are trying to develop locally with an emulator and don't have the correct (`10.0.2.2` is the default for AVD).

```ts
import { Platform } from "react-native";
export const API_URL =
  Platform.OS === "ios" ? "http://localhost:4000" : "http://10.0.2.2:4000";
```

If you need a public URL use https://ngrok.com/ or set up a small VPS with https://certbot.eff.org/

**Comment by Powersanth** [comment]
its working for me
url should be  10.0.2.2:3000/singup
localhost will not work
if you are sending from real android device
use your pc ip address

**Comment by bitfabrikken** [comment]
For anyone searching and landing here, I got this error if I feed an array as a value to the FormData object used in the fetch request body.
E.g., pseudocode, how to provoke the "TypeError: Network request failed" error on Android:

```js
var formData = new FormData();
formData.append("test", [10,20,30]);

var res = await fetch("https://google.com",{
    method: "POST",
    headers: {  
        'Accept':       'application/json',
        'Content-Type': 'multipart/form-data',
    },
    body: formData
}).catch((err) => {  
    console.log("caught err",err);
});
```
Headers do not matter, just that it's a POST request.

**Comment by youssef212** [comment]
what I found is when giving an empty form-data to fetch it fails as well with network request failed

**Comment by LightSmileMu** [comment]
"http://ip:port" format may be useful for android device.

**Comment by Asimurrehman** [comment]
I am also using "react-native": "0.63.2"
my error Gone i did like this :

1)Added a comment
// builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
file path: android/app/src/debug/java/com/{your_project}/ReactNativeFlipper.java
then Rebuild my App using 'yarn run android '
then every thing will successfully worked

my code 👍

    let body = new FormData();
    body.append('submit', 'ok');
    body.append('file', {
      uri: res.uri,
      name: res.fileName,
      type: res.type,
    });

**Comment by frankjosephbarbato** [comment]
I had this issue and learned that with fetch you cannot use localhost. You must use the IP address of your computer on the network.

**Comment by danieltaoxu** [comment]
> 
> 
> I had this issue and learned that with fetch you cannot use localhost. You must use the IP address of your computer on the network.

Oh my god, you saved me, it's that problem, do you know how to avoid use the IP address? it's so annoying .....

**Comment by frankjosephbarbato** [comment]
Not sure, I wonder if using the HTTP module has different behavior?

**Comment by danieltaoxu** [comment]
> Not sure, I wonder if using the HTTP module has different behavior?

I'll try it. Thanks.

**Comment by huynguyen0304** [comment]
Hope this issue will reopen.

**Comment by Asimurrehman** [comment]
my issue was solved

**Comment by johmedina** [comment]
It's still not solved with me. I tried using my machine's IP address instead of localhost but that didn't work for me. Anyone else facing the same problem?

**Comment by sawndur** [comment]
Also having the same issue ^^^. I changed the localhost to computer ip as well. I'm debugging on a physical device. When I send a fetch request, the application crashes with no errors thrown.

**Comment by Rolozuna** [comment]
> android / gradle.properties
> 
> Agrega esto
> 
> FLIPPER_VERSION = 0.50.0

Esto me funcionó! Gracias! 
react-native: 0.63.2

**Comment by johmedina** [comment]
My issue was solved and the problem rooted from using react native and asp.net core. Basically, I needed to change the code from my .net API. In launchsettings.js , change "applicationUrl": "https://localhost:5001;http://localhost:5000" to "applicationUrl": "http://localhost:5000" and then react native can fetch from localhost using the IP address without any issues.

**Comment by j-perl** [comment]
I can't thank you enough @akhan118

> android/gradle.properties
> 
> Add this
> 
> FLIPPER_VERSION=0.50.0

**Comment by ZeeshanZafar557** [comment]
remove from-data solved in my case

  var myHeaders = new Headers();
  myHeaders.append("auth-token", ids.token);
  var formdata = new FormData();
  var requestOptions = {
    method: 'PUT',
    headers: myHeaders,
   // body: formdata,
    redirect: 'follow'
  };
 
  return fetch(baseUrl+"api/v1/trip/"+ids.uId+'/'+ids.tripId+'/views', requestOptions)
  .then(response => {
   
    if(response.status==200)
    {
      return response.json()
    }
    else {  
      return response.text()
    }
  })
  .then(result => {
    return result
  })
  .catch(error => console.log('error', error));

**Comment by nilmeme** [comment]
I changed api url 'localhost' to real host, it works!!!
And 127.0.0.1 dons't work also

**Comment by danieltaoxu** [comment]
> 
> 
> I changed api url 'localhost' to real host, it works!!!
> And 127.0.0.1 dons't work also

10.0.2.2 works for me , it can avoid to change every time restart the machine

**Comment by Rolando-Barbella** [comment]
Can they please repopen this issue?? seems crutial

**Comment by petrosmm** [comment]
> Based on this code
> 
> https://github.com/facebook/react-native/blob/476a336e3613f90b76e3a91d5bffaa098bf4e6ff/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L383
> 
> any request without headers content-type and payload body as string will start failing into "Network request failed." this is because the high-level wrappers are handing the Request Error call as "Network request failed." **but is not even reaching the internet**.
> 
> ```
>     try {
>       sendRequestInternal(
>           method,
>           url,
>           requestId,
>           headers,
>           data,
>           responseType,
>           useIncrementalUpdates,
>           timeout,
>           withCredentials);
>     } catch (Throwable th) {
>       FLog.e(TAG, "Failed to send url request: " + url, th);
>       ResponseUtil.onRequestError(getEventEmitter(), requestId, th.getMessage(), th);
>     }
>   }
> ```
> 
> 1. sendRequestInternal
> 
> ```
> else if (data.hasKey(REQUEST_BODY_KEY_STRING)) {
>       if (contentType == null) {
>         ResponseUtil.onRequestError(
>             eventEmitter, requestId, "Payload is set but no content-type header specified", null);
>         return;
>       }
> ```

For posterity, I got it to work on the following:
I am certain the above was important, if not, absolutely correct. In my case it did not affect the outcome. My scenario was the following: fresh RN TS project 0.62.2, Android 4.4, Https (secure) request, 
and Emulator mode (debug). I kept seeing "Network Request Field". 
I was able to get this to work on Genymotion emulator for 4.4 with Google Playstore (NEEDED -- from opengapps.org) and this piece of [code](https://stackoverflow.com/a/55365033/3997521). Here is my sample code: 
```
function getTestRequest() {
  const headers = new Headers();
  headers.append('Content-Type', 'application/json');
  headers.append('Accept', 'application/json');

  const configInit: RequestInit = {
    method: 'GET',
    // headers: headers
  };

  const url = 'https://www.csattv.org/menu.json'
    ?? 'https://jsonplaceholder.typicode.com/todos/1';

  fetch(url)
    .then(res => {
      console.log('\r\n res', res, '\r\n');
      return res.json();
    }).then(data => {
      console.log(data);
      return data;
    }).catch(p => {
      console.warn(p);
      return;
    });
}
```

**Comment by infinitbility** [comment]
Solve HTTP and HTTPS Network request failed issue in react native fetch

https://infinitbility.com/network-request-failed-in-react-native-fetch

**Comment by Hel5ing** [comment]
> Dear fellow developers, please check out my [comment](https://github.com/facebook/react-native/issues/24394#issuecomment-548280779) on the similar issue #24394 . I hope it will help some of you.

hey man,you are awesome!!

**Comment by joe105598055** [comment]
If you are developing on mac and using wifi. Must remember add DNS (e.g. 8.8.8.8). It works for me.

<img width="671" alt="截圖 2021-06-17 上午9 20 49" src="https://user-images.githubusercontent.com/21593556/122316264-2334e580-cf4e-11eb-92d8-e39a143e3c28.png">

**Comment by alekseiaksenov** [comment]
It's July-2021, and the problem has never been solved?

**Comment by laurent22** [comment]
I think the core issue is the terrible error message. I mean it's a simply an HTTP request, it's plain text, so surely it's possible to get a proper error message from the underlying lib? eg "Missing header", "Invalid content type", etc. 

When a user of my app sees a "Network request failed" I can only tell them there's pretty much no way to know what the error is. They have to randomly try every config variations on their server until it works. That's not how it should be in 2021 - HTTP requests are well understood, and it should be possible to surface a proper error message when something happens.

**Comment by lorecast** [comment]
> Solve HTTP and HTTPS Network request failed issue in react native fetch
> 
> https://infinitbility.com/network-request-failed-in-react-native-fetch

Thanks, it's work for me

**Comment by coldshine** [comment]
I had the similar issue.
I was setting incorrect type in `FormData` object: it was `image` instead of `image/jpeg` or `image/png` or `image/whatever`.
My code was:
```javascript
const formData = new FormData();
formData.append('image', {
  uri: imageUri,
  name: 'someName',
  type: 'image'
});
```

And the working one:
```javascript
const uriParts = imageUri.split('.');
const fileType = uriParts[uriParts.length - 1];

const formData = new FormData();
formData.append('image', {
  uri: imageUri,
  name: 'someName',
  type: `image/${fileType}`
});
```

**Comment by SANDEEP1938** [comment]
> @IcebergRage, I got past this, forgot I'd commented anywhere though and it's a bit fuzzy now.
> 
> I believe in my case it was failing when I only had the header for `Content-Type: "multipart/form-data"` as that was enough to make it work on iOS. But, on Android, I also had to specify that I wanted JSON back with the header `Accept: "application/json"`. Simply specified both and .

but this thing is not working for me

**Comment by hieuplasma** [comment]
I had fixid this problem in ubuntu and . Folow these steps:
1. In terminal, press "ifconfig" and copy ipadress of device, in my case is usb0
2. Shake your device to open menu dev, choose "Dev settings" or "Settings"
3. Choose Debug server host & port fort device, press ip:8081, in my case is 192.168.**.**:8081
4. Open terminal again, and press adb reverse tcp:3000 tcp:3000
5. Now, you can request api with url http://localhost:3000/{params}

**Comment by nilsond** [comment]
I solved the problem with this video: https://www.youtube.com/watch?v=TNIz3P2r4rU

NOTE: This is for those who are using MAC

**Comment by LegalPlatform** [comment]
After Wasting one day finally I solve it !!

It was working on real host, but not on production environment,
So, what I did I past ipconfig command in cmd in windows.

Then I got my ip address from IPv4 Address and past it in fetch variable instead of localhost.

**Comment by tuoxiansp** [comment]
For me, it was solved in a quite simple way:

```javascript
headers: {
  // ...
}
```

-> 

```javascript
headers: new Headers({
  // ...
})
```

**Comment by sedhha** [comment]
Well to summarize it all, this definitely is not a problem with React Native. I have tested it well with all the scenarios, here are the things you might consider when you get this error:

1. Toggle between localhost and actual IP network (Very unlikely but worth a try, if you're requesting to global endpoint, then this step is not required.)
2. Make sure you're connected to Internet (In case you're using emulator, try to open a browser or something)
3. Make sure you're able to reach the endpoint with some other request client (Postman or any other HTTP client)

If you carefully examine above three, you would automatically find out what's missing, if you do the above in order, I am very sure you should be able to sort it out. Tested it with React 0.64.3

**Comment by flyskywhy** [comment]
[fixed `TypeError: Network request failed` when upload file to http not https with Android debug builds](https://github.com/facebook/react-native/issues/33217#issuecomment-1159844475)

**Comment by vshy108** [comment]
For me, I appended `file://` to android uri then the issue is solved while iOS does not need the append of `file://`

**Comment by rychel** [comment]
after this, if the problem persist don't forget disabled firewall

**Comment by samad324** [comment]
I'm still getting this error even after adding `android:usesCleartextTraffic="true"` in `AndroidManifest.xml` file.

so i added my domain name in `network_security_config.xml` file.

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <!-- deny cleartext traffic for React Native packager ips in release -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">10.0.2.2</domain>
        <domain includeSubdomains="true">10.0.3.2</domain>
        <domain includeSubdomains="true">domain.com</domain>
    </domain-config>
</network-security-config>
```

don't forget to add `android:networkSecurityConfig="@xml/network_security_config"` in 
```
 <application
     ...
      android:usesCleartextTraffic="true"
      android:networkSecurityConfig="@xml/network_security_config"
      ... >
```

**Comment by vladimirevstratov** [comment]
> Solve HTTP and HTTPS Network request failed issue in react native fetch
> 
> https://infinitbility.com/network-request-failed-in-react-native-fetch

In my case it was an issue with expired TLS certificate of domain, found it by checking TLS status of domain.

**Comment by SpaceSimon** [comment]
I have a "Network request failed", only on Android and only with DELETE requests, both in development and production.

The deletion works fine but the request fails so I cannot update the UI.

I have this in my headers (among other things):

```
Accept: "application/json; version=13.0;"
Content-Type: "application/json"
```

RN version is 0.63.5

**Comment by shahzaib803** [comment]
That solution worked for me .

I believe in my case it was failing when I only had the header for Content-Type: "multipart/form-data" as that was enough to make it work on iOS. But, on Android, I also had to specify that I wanted JSON back with the header Accept: "application/JSON". Simply specified both and 💥.

**Comment by GeorgeFlorian** [comment]
This worked for me on EXPO SDK 49:
I've installed `expo-build-properties` using `npx expo install expo-build-properties` and then added it as a plugin in `app.json`:

```json
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "usesCleartextTraffic": true
          }
        }
      ]
    ]
```

**Comment by 03balogun** [comment]
Here's how I resolved this.

The server expects `multipart/form-data` for file uploads, but it seems that the request is being sent with application/x-www-form-urlencoded instead. This discrepancy causes the server to reject the request on Android, it works fine on iOS.

The native error looks like this

```
Failed to send url request: http://redacted-host-url.com/upload
java.lang.IllegalArgumentException: multipart != application/x-www-form-urlencoded
	at okhttp3.MultipartBody$Builder.setType(MultipartBody.kt:241)
	at com.facebook.react.modules.network.NetworkingModule.constructMultipartBody(NetworkingModule.java:688)
	at com.facebook.react.modules.network.NetworkingModule.sendRequestInternal(NetworkingModule.java:442)
	at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:874)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:198)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:764)


```
Explicitly setting the content type via the header fixed the issue.

Adding `multipart/form-data` to the request header fixed the issue for me.

````
headers: {
        'Content-Type': 'multipart/form-data'
      }

**Comment by Buddhaa97** [comment]
@03balogun worked for me. Thanks
