### ISSUE TITLE
[UIExplorer] Example won't run

### ISSUE THREAD

**Issue by lowellbander** [facebook/react-native#2562]
When I run the UIExplorer Example either in the simulator or my device, I receive the following error:

```Bridge modules have not yet been initialized. You may be trying to access a module too early in the startup procedure.```

My search for solutions to this issue has been wholly unfruitful thus far.

**Comment by ide** [comment]
I believe this has been fixed in master.

**Comment by brentvatne** [comment]
Confirmed that this works on master, although I had to close Xcode, run `git clean -dfx` in the `react-native` directory, then `npm i` again, `npm start` and open up Xcode, [clean the build](http://url.brentvatne.ca/16ebR) and then compile. Closing this issue but feel free to ping me if it still doesn't work!

**Comment by chrisnojima** [comment]
I'm on master and I still have this issue when I run the pre-bundled flow (the server hosted js version works fine). I did a git clean -dfx, npm i, clean (and clean build folder). pre-bundled in sim and device has this issue for me.

**Comment by christopherdro** [comment]
Confirming that this works on master.

@chrisnojima Could it be your trying to run the example on your phone?
If so, you need to make sure update the localhost address inside of your AppDelegate.m folder to your computers network IP address.

`sourceURL = [NSURL URLWithString:@"http://localhost:8081/Examples/UIExplorer/UIExplorerApp.ios.bundle?platform=ios&dev=true"];`

If this dosn't work, could you possibly provide more information on what the issue is?

**Comment by chrisnojima** [comment]
I was able to get this to work on master now but noticed the url for creating the bundle is no longer valid.

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorer/AppDelegate.m#L69 says to curl a url but that is actually not valid (due to packager changes requiring the platform?) I get

``` 
{
type: "InternalError",
message: "react-packager has encountered an internal error, please check your terminal error output for more details"
}
```

and

```
Error: Error validating module options: child "platform" fails because ["platform" is required]
    at /Users/chrisnojima/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/chrisnojima/react-native/packager/react-packager/src/Server/index.js:161:20
    at tryCallOne (/Users/chrisnojima/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/chrisnojima/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/chrisnojima/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

If i hit http://localhost:8081/Examples/UIExplorer/UIExplorerApp.ios.bundle?platform=ios&dev=false it works fine

**Comment by jedlinlau** [comment]
On 0.11.4, I think I see a race condition between RCTBatchedBridge's `invalidate` and line 464 within `invalidate` that sets `_modulesByName` to nil. When I step through this code in the debugger, I see RCTBridge call `invalidate` due to a reload. Next, RCTBridge calls `[self setUp]`, which goes through the initialization of the modules again:
```obj-c
        -[RCTModuleData initWithExecutor:moduleID:instance:] + 792                                                                                                                   
        5   Samsara                             0x000000010b217f61                                                                                                                   
        -[RCTBatchedBridge initModules] + 3617                                                                                                                                       
        6   Samsara                             0x000000010b2157da                                                                                                                   
        -[RCTBatchedBridge start] + 282                                                                                                                                              
        7   Samsara                             0x000000010b215660                                                                                                                   
        -[RCTBatchedBridge initWithParentBridge:] + 1744                                                                                                                             
        8   Samsara                             0x000000010b2398b8
```

But, in the middle of this initialization, the debugger jumps to line 464 in RCTBatchedBridge.m:
```obj-c
  dispatch_group_notify(group, dispatch_get_main_queue(), ^{
    [_javaScriptExecutor executeBlockOnJavaScriptQueue:^{
      [_jsDisplayLink invalidate];
      _jsDisplayLink = nil;

      [_javaScriptExecutor invalidate];
      _javaScriptExecutor = nil;

      if (RCTProfileIsProfiling()) {
        RCTProfileUnhookModules(self);
      }
      _moduleDataByID = nil;
>>>>  _modulesByName = nil;   <<<<
      _frameUpdateObservers = nil;

    }];
  });
```

This nils out `_modulesByName` in the middle of initialization. When initialization of the modules continues, `[RCTBatchedBridge modules]` evaluates the assert, which fails. (`self.isValid` is YES, but `_modulesByName` is nil.)

**Comment by ide** [comment]
^ cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
@jedlinlau I'm not sure I get it, `[RCTBatchedBridge invalidate]` and `[RCTBatchedBridge modules]` are called in two different instances during reload and `_valid` is set to `NO` right at the top of `[RCTBatchedBridge invalidate]`.

Are you seeing an actual crash? If so, can you provide stack traces?

**Comment by jamesfzhang** [comment]
I ran into this exact same error when I forgot to require a native module.

**Comment by tachim** [comment]
I'm seeing the same issue:

```
2015-10-15 11:19:26.745 praxis[80639:4505201] *** Assertion failure in -[RCTBatchedBridge modules](), /Users/tachim/praxis/node_modules/react-native/React/Base/RCTBatchedBridge.m:411
2015-10-15 11:19:26.750 praxis[80639:4505201] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Bridge modules have not yet been initialized. You may be trying to access a module too early in the startup procedure.'
*** First throw call stack:
(
	0   CoreFoundation                      0x017d9a94 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0071de02 objc_exception_throw + 50
	2   CoreFoundation                      0x017d992a +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x0039d454 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 102
	4   praxis                              0x000b0322 -[RCTBatchedBridge modules] + 370
	5   praxis                              0x000e5812 -[RCTBridge(RCTRedBox) redBox] + 50
	6   praxis                              0x000ad59a __31-[RCTBatchedBridge loadSource:]_block_invoke + 458
	7   praxis                              0x000964ea __50+[RCTJavaScriptLoader loadBundleAtURL:onComplete:]_block_invoke + 3466
	8   CFNetwork                           0x0127d04b __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 48
	9   CFNetwork                           0x012915fb __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 353
	10  Foundation                          0x003caf98 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	11  Foundation                          0x002eee6f -[NSBlockOperation main] + 108
	12  Foundation                          0x002cf334 -[__NSOperationInternal _start:] + 697
	13  Foundation                          0x002cf074 -[NSOperation start] + 83
	14  Foundation                          0x002ceeb2 __NSOQSchedule_f + 245
	15  libdispatch.dylib                   0x04e189cd _dispatch_client_callout + 14
	16  libdispatch.dylib                   0x04dfc6d8 _dispatch_queue_drain + 2227
	17  libdispatch.dylib                   0x04dfbb8c _dispatch_queue_invoke + 570
	18  libdispatch.dylib                   0x04dfe843 _dispatch_root_queue_drain + 550
	19  libdispatch.dylib                   0x04dfe616 _dispatch_worker_thread3 + 115
	20  libsystem_pthread.dylib             0x05138270 _pthread_wqthread + 1050
	21  libsystem_pthread.dylib             0x05135f82 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/uiexplorer-example-wont-run

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
