### ISSUE TITLE
:ReactAndroid:installArchives fails from react native repo 0.60.3

### ISSUE THREAD

**Issue by lucidtheory** [facebook/react-native#25625]
React Native version: 0.60.3

## Steps To Reproduce

1. Install react-native repo
2. Checkout v0.60.3
3. run `yarn`
4 run `./gradlew :ReactAndroid:installArchives` or `./gradlew :ReactAndroid:installArchives --no-daemon`

Fails to compile for javadoc issues:
```
> Task :ReactAndroid:androidJavadoc
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/yoga/YogaNode.java:9: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/yoga/YogaConfig.java:9: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/yoga/YogaNodeJNIBase.java:12: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/yoga/YogaNative.java:10: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/yoga/YogaNodeJNIBatching.java:9: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/hermes/reactexecutor/RuntimeConfig.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/jni/HybridData.java:11: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/hermes/reactexecutor/HermesExecutor.java:12: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/hermes/reactexecutor/HermesExecutor.java:14: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/jni/Countable.java:9: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/jni/ThreadScopeSupport.java:9: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/jni/IteratorHelper.java:12: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/jni/CpuCapabilitiesJni.java:9: error: package com.facebook.soloader does not exist
import com.facebook.soloader.SoLoader;
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/jni/MapIteratorHelper.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/LazyReactPackage.java:11: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactPackage.java:16: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java:16: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java:22: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleHolder.java:8: error: package com.facebook.infer.annotation does not exist
import static com.facebook.infer.annotation.Assertions.assertNotNull;
                                           ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleHolder.java:8: error: static import only from classes and interfaces
import static com.facebook.infer.annotation.Assertions.assertNotNull;
^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleHolder.java:15: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleHolder.java:21: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleHolder.java:22: error: package javax.annotation.concurrent does not exist
import javax.annotation.concurrent.GuardedBy;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleHolder.java:23: error: package javax.inject does not exist
import javax.inject.Provider;
                   ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleSpec.java:9: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleSpec.java:11: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ModuleSpec.java:12: error: package javax.inject does not exist
import javax.inject.Provider;
                   ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/NativeModule.java:12: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManager.java:26: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManager.java:27: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/BaseJavaModule.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactShadowNode.java:22: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactStylesDiffMap.java:12: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ThemedReactContext.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/touch/JSResponderHandler.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableArray.java:12: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableArray.java:13: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableMap.java:13: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableMap.java:14: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java:9: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java:17: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java:18: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableMap.java:10: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableMap.java:11: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableArray.java:10: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableArray.java:11: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java:11: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java:14: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java:12: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java:30: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java:31: error: package javax.annotation.concurrent does not exist
import javax.annotation.concurrent.GuardedBy;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java:21: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java:22: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java:23: error: cannot find symbol
import com.facebook.react.R;
                         ^
  symbol:   class R
  location: package com.facebook.react
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java:40: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java:41: error: package javax.annotation.concurrent does not exist
import javax.annotation.concurrent.NotThreadSafe;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java:65: error: cannot find symbol
@NotThreadSafe
 ^
  symbol: class NotThreadSafe
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java:12: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java:13: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java:34: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcher.java:11: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagerRegistry.java:13: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/common/UIManagerType.java:14: error: cannot find symbol
import androidx.annotation.IntDef;
                          ^
  symbol:   class IntDef
  location: package androidx.annotation
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java:19: error: package androidx.collection does not exist
import androidx.collection.ArrayMap;
                          ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java:20: error: package com.facebook.common.logging does not exist
import com.facebook.common.logging.FLog;
                                  ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java:51: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContextBaseJavaModule.java:10: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContextBaseJavaModule.java:11: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/UIManager.java:11: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/common/UIManagerType.java:17: error: cannot find symbol
@IntDef({DEFAULT, FABRIC})
 ^
  symbol: class IntDef
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/common/SingleThreadAsserter.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/common/SingleThreadAsserter.java:12: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/ReactEventEmitter.java:13: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/ReactEventEmitter.java:19: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/RCTEventEmitter.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEvent.java:10: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEvent.java:12: error: package androidx.core.util does not exist
import androidx.core.util.Pools;
                         ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEvent.java:15: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEvent.java:30: error: package Pools does not exist
  private static final Pools.SynchronizedPool<TouchEvent> EVENTS_POOL =
                            ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewGroupManager.java:14: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java:11: error: package androidx.core.view does not exist
import androidx.core.view.ViewCompat;
                         ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java:15: error: cannot find symbol
import com.facebook.react.R;
                         ^
  symbol:   class R
  location: package com.facebook.react
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:10: error: package androidx.core.view does not exist
import androidx.core.view.AccessibilityDelegateCompat;
                         ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:11: error: package androidx.core.view does not exist
import androidx.core.view.ViewCompat;
                         ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:12: error: package androidx.core.view.accessibility does not exist
import androidx.core.view.accessibility.AccessibilityNodeInfoCompat;
                                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:13: error: package androidx.core.view.accessibility.AccessibilityNodeInfoCompat does not exist
import androidx.core.view.accessibility.AccessibilityNodeInfoCompat.AccessibilityActionCompat;
                                                                   ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:14: error: package androidx.core.view.accessibility.AccessibilityNodeInfoCompat does not exist
import androidx.core.view.accessibility.AccessibilityNodeInfoCompat.CollectionItemInfoCompat;
                                                                   ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:17: error: package androidx.core.view does not exist
import androidx.core.view.AccessibilityDelegateCompat;
                         ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:18: error: package androidx.core.view does not exist
import androidx.core.view.ViewCompat;
                         ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:19: error: package androidx.core.view.accessibility does not exist
import androidx.core.view.accessibility.AccessibilityNodeInfoCompat;
                                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:20: error: package androidx.core.view.accessibility.AccessibilityNodeInfoCompat does not exist
import androidx.core.view.accessibility.AccessibilityNodeInfoCompat.CollectionItemInfoCompat;
                                                                   ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:29: error: cannot find symbol
import com.facebook.react.R;
                         ^
  symbol:   class R
  location: package com.facebook.react
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:33: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java:23: error: package javax.annotation does not exist
import javax.annotation.Nonnull;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java:25: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java:40: error: cannot find symbol
public class ReactAccessibilityDelegate extends AccessibilityDelegateCompat {
                                                ^
  symbol: class AccessibilityDelegateCompat
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/LayoutShadowNode.java:23: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactShadowNodeImpl.java:9: error: package com.facebook.infer.annotation does not exist
import com.facebook.infer.annotation.Assertions;
                                    ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactShadowNodeImpl.java:28: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
/Users/lucid/Desktop/client/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/layoutanimation/LayoutAnimationController.java:8: error: package javax.annotation does not exist
import javax.annotation.Nullable;
                       ^
100 errors

> Task :ReactAndroid:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:androidJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/lucid/Desktop/client/react-native/ReactAndroid/build/tmp/androidJavadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
1 actionable task: 1 executed
```

Describe what you expected to happen:
Build successfully

Hoping to upgrade react native and our code has a patch requiring us to build from source. Any way to fix this?

**Comment by JofBigHealth** [comment]
@lucidtheory Had you attempted to run [`jetifier`](https://developer.android.com/studio/command-line/jetifier) to upgrade to AndroidX? Have you set

```
android.useAndroidX=true
android.enableJetifier=true
```
In your android/gradle.properties?

(I'm not using RNWeb currently so I'm not sure what the expected install process is so I might be suggesting you do the wrong thing... I just happen to be scanning through the issues here out of interest).

**Comment by lucidtheory** [comment]
I do need to update to AndroidX however, the main concern is that I cant seem to run the `installArchives` command and have it build successfully. 

That part is it's own contained issue that deals solely with the react native repo. 

I've prepped my system to be able to build from source following the (guide)[https://github.com/facebook/react-native/wiki/Building-from-source] but still get the above error

**Comment by MehmoodArib** [comment]
Did you doundd the solution, I am still getting error

**Comment by lucidtheory** [comment]
We are upgrading from 59.4 and there were a lot of big changes that needed to be made as per the [upgrade guide](https://react-native-community.github.io/upgrade-helper/?from=0.59.8&to=0.60.3).

After upgrading everything correctly I followed the directions for setting up [Building RN from Source](https://github.com/facebook/react-native/wiki/Building-from-source).

`cd node_modules/react-native && yarn install`
`cd ..`
`react-native run-android`

and this will do the same thing as the `installArchives` command. 
After that for our purposes we wanted the binaries created from that so those can be found in
`node_modules/react-native/android/com/facebook/react/react-native`

**Comment by dlowder-salesforce** [comment]
Reopening this since it is not yet resolved.

**Comment by dlowder-salesforce** [comment]
@kelset @hramos do you have any advice on how to solve this issue, or know someone on the RN core team who can help?

**Comment by bartolkaruza** [comment]
I think this was fixed by https://github.com/facebook/react-native/commit/ffdf3f22c68583fe77517f78dd97bd2e97ff1b9e Why not try 0.60.5?

**Comment by dlowder-salesforce** [comment]
@bartolkaruza : That commit (https://github.com/facebook/react-native/pull/25912) does not appear to fix the issue, at least for me.  @janicduplessis

**Comment by kelset** [comment]
Hey @dlowder-salesforce, can you maybe provide a repro that showcases this? Is this also happening in 61 rc?

It seems to be caused by AndroidX, so I would probably look at the upgrade process that led the app that showcase this error. But yeah, I mean, if you can repro it it would surely help.

Maybe @mikehardy has a better idea, dunnow - sorry 😅

**Comment by mikehardy** [comment]
I've never built react-native from source.
The build log failure is cluttered with missing AndroidX symbols yes, but it's also missing core react-native symbols (soloader etc) so to me it just looks like the gradle files are all stuffed up somehow. Maybe missing the repository definition in the main build.gradle, or something in settings.gradle that would point to the right directories so the symbols were available.

**Comment by lucidtheory** [comment]
Looking at the [Buck](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/BUCK) files, anything called with `react_native_dep` fails to load and results in the crash above where as the ones called with `react-native_target` get loaded.

The ones calling `react_native_dep` usually point to the `ReactAndroid/src/main/third-party` folder in the react native repo. All of these are Buck files which are intended to load the lib that was called but it seems like none of them are working.
