### ISSUE TITLE
Linking.getInitialURL() for android

### ISSUE THREAD

**Issue by sajaddp** [facebook/react-native#25675]
Hi,
On Android `Linking.getInitialURL()` has a problem and not return anything.
More precisely, none of the following logs are executed.
```
  Linking.getInitialURL().then((url) => {
      console.log('Initial url is: ' + url);
  }).catch(err => console.error('An error occurred', err));
```
but when i change https://github.com/facebook/react-native/blob/master/Libraries/Linking/Linking.js#L86-L92
to:
```
  getInitialURL(): Promise<?string> {
    return NativeLinking.getInitialURL();
  }
```
the problem was fixed.

React Native version:
```
System:
    OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 582.26 MB / 15.50 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by tgensol** [comment]
I can confirm that on Android, if the app is closed, **InteractionManager.runAfterInteractions**, will not work and then the getInitialURL will not return anything. 

But if the app was opened, everything works just fine.

I removed the **InteractionManager.runAfterInteractions** and the deep linking on Android, when the app is closed, works again

Thanks @sajaddp

**Comment by i7soft** [comment]
I fixed by that:
```
var NativeLinking=require("./node_modules/react-native/Libraries/Linking/NativeLinking").default;
NativeLinking.getInitialURL().then((url) => {
      console.log('Initial url is: ' + url);
  }).catch(err => console.error('An error occurred', err));
```

**Comment by shubham234** [comment]
I'm also facing this issue on RN v0.59.8. I'm trying to use aws-amplify [library](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/urlListener.native.ts#L43) and they make use of Linking.getInitialUrl() to listen to the Deeplink URL but it is always returning null. Can anyone suggest some solutions that I can try?

**Comment by joaocac** [comment]
Same here iOS is working great but Android fails.

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 68.70 MB / 16.00 GB
Packages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
    react-native-cli: 2.0.1

**Comment by mileszs** [comment]
We are seeing what we think is the same issue—works great on iOS, fails on Android cold starts. In particular, it fails on Android 10. It works on an old Android 7 phone I have.

**Comment by Stephen2** [comment]
Any update on this?  Or workaround?

**Comment by Stephen2** [comment]
Interestingly, `getInitialUrl` works on Google Pixel XL2 but doesn't work on Samsung S9 - both running Android 10.

I even changed code to:
`import NativeLinking from "react-native/Libraries/Linking/NativeLinking";`
`NativeLinking.getInitialURL().then(handleDeepLinking);`
(^^ code is cut down, I actually went as far as to put `url` into state and display in a `<Text>` for debug build, but nothing)

But to no avail... Samsung S9 refuses to call the `handleDeepLinking` function from cold start :(  Warm start is fine

**Comment by Stephen2** [comment]
```
"react": "16.9.0",
"react-native": "0.61.4",
"expo": "^36.0.0",
```

**Comment by Stephen2** [comment]
UPDATE:
 - forking `react-native` and reverting https://github.com/facebook/react-native/pull/24748 did NOT solve the issue
 - I downgraded Expo SDK from 36 to 35, which moved `react-native` from `0.61.4` back to `0.59.8` which did solve the issue

And please note the differing behaviour on different Android devices during my testing.  This was a consistent failure on Samsung, but consistently fine on Google Pixel

I will attempt to do a `git log --follow` on a few files between these 2 react-native versions, to get more info, but at this point I don't know which files/folders are most likely culprits.

**Comment by aurasphere** [comment]
I can confirm that I have this issue since I've updated from 0.59.* to 0.61.*

**Comment by phillipkey** [comment]
Is there any update on this issue? I'm experiencing the same. Not being able to utilize deep linking is a huge miss right now.

**Comment by bsonmez** [comment]
Is there any update? The bug still continue

**Comment by openwell** [comment]
Finally am not dumb.... Is there any update? The bug still continues

**Comment by ryzhak** [comment]
The same issue. `Linking.getInitialURL` works fine on ios, but on android(emulator SDK 28) this method seems not even to be called.

```
"react-native": "0.61.5",
"react-native-navigation": "^4.5.3",
```

**Comment by danieltrizzuto** [comment]
Same here on 0.61.5

**Comment by N1ghtly** [comment]
Any progress on this? Seems mind boggling to me that deeplinking is just completely broken in RN for Android?

**Comment by norbertschuler** [comment]
> Any progress on this? Seems mind boggling to me that deeplinking is just completely broken in RN for Android?

It’s not completely broken for me. It works for an already started app, but not for a newly started one.

**Comment by N1ghtly** [comment]
> > Any progress on this? Seems mind boggling to me that deeplinking is just completely broken in RN for Android?
> 
> It’s not completely broken for me. It works for an already started app, but not for a newly started one.

Well I'd argue that is *almost* completely broken then. Deeplinking is usually used when the app is not open.

**Comment by rsmelo92** [comment]
The culprit seems to be this line here
https://github.com/facebook/react-native/blob/c0d8c1db9077d08c3832b23e959bf70ad204307d/Libraries/Linking/Linking.js#L88

`InteractionManager.runAfterInteractions` takes too long and `Linking.getInitialURL` never resolves the desired effect!

After removing it it worked 100% of the times, so @Stephen2 workaround actually fixes it by the time being...
```
import NativeLinking from 'react-native/Libraries/Linking/NativeLinking';
NativeLinking.getInitialURL().then(url => {
      handleDeepLink({ url });
 });
```

**Comment by Stephen2** [comment]
> ```
> import NativeLinking from 'react-native/Libraries/Linking/NativeLinking';
> NativeLinking.getInitialURL().then(url => {
>       handleDeepLink({ url });
>  });
> ```

I've tried that earlier


> But to no avail... Samsung S9 refuses to call the handleDeepLinking function from cold start

**Comment by rsmelo92** [comment]
I'm not using Expo SDK, maybe that's what different. Here it works!

**Comment by rsmelo92** [comment]
Jest started complaining and now changed solution to 
```
export function getInitialURLOverride() {
  if (Platform.OS === 'android') {
    const NativeLinking = require('react-native/Libraries/Linking/NativeLinking').default;
    NativeLinking.getInitialURL().then(url => url && handleDeepLink({ url }));
  } else {
    Linking.getInitialURL().then(url => url && handleDeepLink({ url }));
  }
}
```

**Comment by Stephen2** [comment]
For me and team it was device specific.  Google Pixel XL2 worked, Samsung S9 didn't.

What devices are you testing with, may I ask?

**Comment by ssangervasi** [comment]
I'm experiencing this in _both_ Android and iOS as a result of the websocket implementations crashing due to a null base url.

I've implemented a check in my navigation logic that handles null `getInitialUrl` results, but there are other things running in my app that need websockets to... work.

I can't think of a workaround that doesn't require digging into the Java and ObjC code.

In Android:
```
 Exception in native call
 java.lang.NullPointerException: url == null
 	at okhttp3.Request$Builder.url(Request.java:156)
 	at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:94)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 	at android.os.Handler.handleCallback(Handler.java:873)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
 	at android.os.Looper.loop(Looper.java:193)
 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
 	at java.lang.Thread.run(Thread.java:764)
```

In iOS:
```
Exception '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter' was thrown while invoking connect on target WebSocketModule with params (
    "<null>",
    "<null>",
        {
        headers =         {
        };
    },
    6
)
```

**Comment by openwell** [comment]
> InteractionManager.runAfterInteractions

this works but how to make firebase dynamic link work with it... is the problem.

**Comment by kromsik** [comment]
I'm experiencing the same problem.
`myapp://profile` is not resolved after app cold start
`myapp://profile` is resolved the app is launched and in background state (miminized)

**Comment by VictorAtPL** [comment]
@kromsik 
Did you try @rsmelo92 fix? It works for me in both scenarios.

**Comment by esxquillon** [comment]
Same here, i having an issue on Linking.getInitialURL() that are not returning the correct url.

**Comment by rsmelo92** [comment]
In case anyone is still having problems, at least from version `0.61.5` to greater versions its working without any workarounds! 
Removed all of them and its all working on my project. 

In case anyone is with difficulties made this working repo to help!!
Its ok on both platforms, on `background`, `foreground` and `quit` states.
https://github.com/rsmelo92/deeplinkWorking

**Comment by Bardiamist** [comment]
Does this happen only on link open or on any app start?

**Comment by crisvergara** [comment]
I was able to replicate this issue consistently. The issue comes up because when our application is opened from cold, we have a spinner that is animated using Animated.timing while it loads other information (API calls and yes, the Linking.getInitialURL)

It looks like any animation will queue an interaction with the InteractionManager. The InteractionManager, in turn, will not look up  the initialURL unless the queue is completely empty.

Offending code:
```
  spinIt() {
    this.spinValue.setValue(0);
    Animated.timing(this.spinValue, {
      toValue: 1,
      duration: 800,
      easing: Easing.Out,
      useNativeDriver: false,
    }).start(() => this.spinIt());
  }
```
Fixed code:
```
  spinIt() {
    this.spinValue.setValue(0);
    Animated.timing(this.spinValue, {
      toValue: 1,
      duration: 800,
      easing: Easing.Out,
      useNativeDriver: false,
    }).start(() => setImmediate(this.spinIt.bind(this)));
  }
```

I also tried replacing with `Animated.loop`, but I found that I had the same issue. Only solve was to schedule the next loop using `setImmediate`.

**Comment by jtbeach** [comment]
I think there are probably 2 different issues/bugs here:

1. The promise returned by Linking.getInitialURL() seems not to resolve for some people (see example of @crisvergara above)
2. The promise returned by Linking.getInitialURL() **does resolve** and either returns null or a default Expo URL starting with https://expo.io (only if using the managed Expo workflow)

I think it probably makes sense to separate these 2 issues or at least declare which of the 2 people are seeing. For me, I am seeing number 2 above.

I did some research into this and have come to similar conclusions to @Stephen2:

- It does not seem related to a particular Android, but actually depends on timing. In addition to it only happening on certain phones, I found that you can get inconsistent results on the same phone.
- It is resolved by moving back from React Native 0.61 to React Native 0.59. Unfortunately, for those using Expo, this means going back to the Expo 35 SDK, which Apple is no longer accepting submissions from due to usage of deprecated UIWebView (see https://github.com/expo/expo/issues/5497)
- It is not related to Expo and can be reproduced by a trivial example in latest React Native after running `react-native init` and making some changes to `App.js` and `AndroidManifest.xml` (to register intent to view certain URLs). I have pushed this sample app at https://github.com/stellaai/rndeeplink

The bug seems timing dependent. Having put tracing debug statements throughout the native code, my hunch is that this relates to whether or not the React bridge is ready when the native code wants to set the initial URL by sending a message to the JS app via EventEmitter.

A workaround/hack (if using vanilla React Native or willing to eject from Expo managed workflow) might be to override the `getLaunchOptions` method in your own `ReactActivityDelegate ` subclass to explicitly get the URI from the Intent and pass it through as a prop to the root React component rather than relying on Linking.getInitialUrl(). See https://medium.com/@anutoshdatta/pass-initial-properties-to-react-native-from-java-or-objective-c-code-12880ba6198e for some details on this.

I have put a video of these inconsistent results up here: https://github.com/stellaai/rndeeplink/blob/master/deeplinkbug.mp4 -- note that pressing the the back button on Android destroys the activity, so this is showing a cold start every time.

Have also logged a bug in Expo prior to determining that this was a bug with RN upstream with some more logs, etc.: https://github.com/expo/expo/issues/8408

**Comment by paulsjohnson91** [comment]
Has there been any progress on this? I'm still getting the same result in react 62.2

**Comment by lakinduakash** [comment]
> Jest started complaining and now changed solution to
> 
> ```
> export function getInitialURLOverride() {
>   if (Platform.OS === 'android') {
>     const NativeLinking = require('react-native/Libraries/Linking/NativeLinking').default;
>     NativeLinking.getInitialURL().then(url => url && handleDeepLink({ url }));
>   } else {
>     Linking.getInitialURL().then(url => url && handleDeepLink({ url }));
>   }
> }
> ```

This works for me. +1

**Comment by tgensol** [comment]
On my side I changed react-native itself : 

```

diff --git a/node_modules/react-native/Libraries/Linking/Linking.js b/node_modules/react-native/Libraries/Linking/Linking.js
index 8c7dfa9..0cab0cc 100644
--- a/node_modules/react-native/Libraries/Linking/Linking.js
+++ b/node_modules/react-native/Libraries/Linking/Linking.js
@@ -84,11 +84,7 @@ class Linking extends NativeEventEmitter {
    * See https://facebook.github.io/react-native/docs/linking.html#getinitialurl
    */
   getInitialURL(): Promise<?string> {
-    return Platform.OS === 'android'
-      ? InteractionManager.runAfterInteractions().then(() =>
-          NativeLinking.getInitialURL(),
-        )
-      : NativeLinking.getInitialURL();
+    return NativeLinking.getInitialURL();
   }
 
   /*
```

On Android, the InteractionManager.runAfterInteractions doesn't always resolve on the application starting. Removing it (like the code for iOS), resolved all my initial url issues I could have (with firebase, facebook,...)

**Comment by MrLoh** [comment]
@tgensol maybe you should create a PR to get this fixed

**Comment by Stephen2** [comment]
@tgensol what you've done is revert https://github.com/facebook/react-native/pull/24748

During my testing this didn't fix it in all conditions

**Comment by Lowisoft** [comment]
Does this issue still exist on the latest React Native version (0.63.2)? 
And if so, is there a plan to fix this on a future release, because proper deep linking seems currently not possible.

**Comment by Stephen2** [comment]
Well, for us, upgrading to Expo38, upgrading `react-navigation` and using the new method of declaring a deep link handling function:
https://reactnavigation.org/docs/deep-linking/

Got deep linking working in all scenarios on all devices :fire: :partying_face:

**Comment by Lowisoft** [comment]
That’s good to hear that it works for you, but I was unsure, because the newest documentation of `react-navigation` has a note where it says that the bug still exists (and it is even linking to this issue): https://reactnavigation.org/docs/configuring-links

**Comment by jorgegvallejo** [comment]
> Does this issue still exist on the latest React Native version (0.63.2)?
> And if so, is there a plan to fix this on a future release, because proper deep linking seems currently not possible (on Android).

Running 0.63.2 and deep linking doesn't work in Android for me, but it does work in iOS.

**Comment by jorgegvallejo** [comment]
> Does this issue still exist on the latest React Native version (0.63.2)?
> And if so, is there a plan to fix this on a future release, because proper deep linking seems currently not possible (on Android).

Running 0.63.2 bare and deep linking works for both Android and iOS

**Comment by Lowisoft** [comment]
> 
> 
> > Does this issue still exist on the latest React Native version (0.63.2)?
> > And if so, is there a plan to fix this on a future release, because proper deep linking seems currently not possible (on Android).
> 
> Running 0.63.2 bare and deep linking works for both Android and iOS

For me, as far as I could test it, deep linking seems also to work for 0.63.2 on both Android and iOS, but it is likely that it might not work for some of the thousand different Android phones.

**Comment by hardcodet** [comment]
Just ran into this with expo SDK 39 on a Samsung S10e (Android 10) :(

**Comment by sathwik77** [comment]
Using expo ejected app. When I was running app with managed working in Expo and using Linking from `expo-linking` it was working fine in both IOS and andorid, I ejected my app and changed my Linking module to RN's linking and it always returns null to me in all devices IOS and Android
- RN 0.63.3
- Expo SDK 39.0

**Comment by Tibo46** [comment]
Hi,
I am having the same issue.
I have a bare expo project (all new from today), when doing:
`await Linking.getInitialURL();`
the result is always null (tested only on two different Android 9 emulator, I do not have a mac to test on iphone).
- Expo 40.0.0
- react-native 0.63.4

I have tried (with no luck)
- with expo-linking
- disabling remote debugging

Any other leads on how to solve this problem?

**Comment by AnibalDuarte** [comment]
> I fixed by that:
> 
> ```
> var NativeLinking=require("./node_modules/react-native/Libraries/Linking/NativeLinking").default;
> NativeLinking.getInitialURL().then((url) => {
>       console.log('Initial url is: ' + url);
>   }).catch(err => console.error('An error occurred', err));
> ```

That save my live, thanks bro!

**Comment by abdullahbayram** [comment]
Is getInitialURL for Android working on RN 0.63.4?

**Comment by Barney4242** [comment]
> Is getInitialURL for Android working on RN 0.63.4?

yes

**Comment by abdullahbayram** [comment]
I have tried suggested solutions but can not get initial url on android emulators(Pixel 2 API 28 and 29, Samsung Galaxy S10 API 29) or on the real devices(Sony Xperia Z3 API 23, Samsung S7 API 26). react-native version is 63.4. IOS works fine.

**Comment by kurtgn** [comment]
Still have this problem after upgrading to `"react-native": "0.63.4"`. Here's my solution (with a bit of java needed):


Override a method on `MainActivity`:

```
public class MainActivity extends ReactActivity {

  ...  
  @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Nullable
            @Override
            protected Bundle getLaunchOptions() {
                Intent intent = getIntent();
                Bundle initialProps = new Bundle();
                initialProps.putString("intentDataString", intent.getDataString());
                return initialProps;
            }
        };
    }
}

```

This will pass an `intent` prop to your react app:

```
const App = (props) => {

  console.log(props.intent);

  return ...;
}
```

this way, if you have `intent` prop, this means your app was cold started, and the value of this prop will be your deeplink URL.

**Comment by alariej** [comment]
Same issue here. Linking.getInitialURL() always returns 'null' on Android. Tested this with RN 0.63.4, without Expo, without debug, on a physical device (LG G6).

**Comment by dorianmariefr** [comment]
a cleaner solution:

```js
import NativeLinking from "react-native/Libraries/Linking/NativeLinking"

...

const url = await NativeLinking.getInitialURL()
handleUrl({ url })
```

tested with: `adb shell am start -W -a android.intent.action.VIEW -d socializus://dev.socializus.app/users/1 com.social.firebase.example.socializus`

**Comment by anastely** [comment]
> Jest started complaining and now changed solution to
> 
> ```
> export function getInitialURLOverride() {
>   if (Platform.OS === 'android') {
>     const NativeLinking = require('react-native/Libraries/Linking/NativeLinking').default;
>     NativeLinking.getInitialURL().then(url => url && handleDeepLink({ url }));
>   } else {
>     Linking.getInitialURL().then(url => url && handleDeepLink({ url }));
>   }
> }
> ```


This works in cold start well,
but if the app was in bg not works :\

**Comment by bachhuberdesign** [comment]
Just a side note for those who have upgraded to React Native 0.64.x. We were still having the same issue, but needed to change the workaround others are using to

```
require('react-native/Libraries/Linking/NativeIntentAndroid').default
```

rather than

```
require('react-native/Libraries/Linking/NativeLinking').default
```

Seems to work fine after making said change.

**Comment by DeniferSantiago** [comment]
I am surprised that there is still no version with the solution

**Comment by Kiura** [comment]
Is there a planned update to react-native that fixes this issue?
Universal linking is the main feature of many applications, maybe this should have higher priority?

**Comment by henrymoulton** [comment]
I've used [patch-package](https://www.npmjs.com/package/patch-package) with the following patch:

```
diff --git a/node_modules/react-native/Libraries/Linking/Linking.js b/node_modules/react-native/Libraries/Linking/Linking.js
index 2799801..1ad2274 100644
--- a/node_modules/react-native/Libraries/Linking/Linking.js
+++ b/node_modules/react-native/Libraries/Linking/Linking.js
@@ -94,13 +94,11 @@ class Linking extends NativeEventEmitter {
    * it will give the link url, otherwise it will give `null`
    *
    * See https://reactnative.dev/docs/linking.html#getinitialurl
+   * Modified with patch-package after seeing this comment:
+   * https://github.com/facebook/react-native/issues/25675#issuecomment-656137889
    */
   getInitialURL(): Promise<?string> {
-    return Platform.OS === 'android'
-      ? InteractionManager.runAfterInteractions().then(() =>
-          nullthrows(NativeIntentAndroid).getInitialURL(),
-        )
-      : nullthrows(NativeLinkingManager).getInitialURL();
+     return nullthrows(NativeLinkingManager).getInitialURL();
   }
 
   /*

```

**Comment by haveneersrobin** [comment]
> I've used [patch-package](https://www.npmjs.com/package/patch-package) with the following patch:
> 
> ```
> diff --git a/node_modules/react-native/Libraries/Linking/Linking.js b/node_modules/react-native/Libraries/Linking/Linking.js
> index 2799801..1ad2274 100644
> --- a/node_modules/react-native/Libraries/Linking/Linking.js
> +++ b/node_modules/react-native/Libraries/Linking/Linking.js
> @@ -94,13 +94,11 @@ class Linking extends NativeEventEmitter {
>     * it will give the link url, otherwise it will give `null`
>     *
>     * See https://reactnative.dev/docs/linking.html#getinitialurl
> +   * Modified with patch-package after seeing this comment:
> +   * https://github.com/facebook/react-native/issues/25675#issuecomment-656137889
>     */
>    getInitialURL(): Promise<?string> {
> -    return Platform.OS === 'android'
> -      ? InteractionManager.runAfterInteractions().then(() =>
> -          nullthrows(NativeIntentAndroid).getInitialURL(),
> -        )
> -      : nullthrows(NativeLinkingManager).getInitialURL();
> +     return nullthrows(NativeLinkingManager).getInitialURL();
>    }
>  
>    /*
> ```

This did not work for me as did no other solutions in this thread... Deep link works perfectly for iOS. On Android only if the app was running in the background, not from cold start: the `Linking.getInitialURL();` never resolves. Running RN 0.64.2. Any other suggestions?

**Comment by Kiura** [comment]
currently, I have a workaround that works for me on android (haven't checked on ios yet)
```js
useEffect(()=>{
      Linking.addEventListener('url', handleDeepLink);
      Linking.getInitialURL().then(url => {
        if (url) handleDeepLink({ url });
      });
})
```

**Comment by rsmelo92** [comment]
This issue has a lot of solutions, but none of them work with [COLD START](https://developer.android.com/topic/performance/vitals/launch-time#cold), since jul 2019 its still an issue...

**Comment by haveneersrobin** [comment]
> I've used [patch-package](https://www.npmjs.com/package/patch-package) with the following patch:
> 
> ```
> diff --git a/node_modules/react-native/Libraries/Linking/Linking.js b/node_modules/react-native/Libraries/Linking/Linking.js
> index 2799801..1ad2274 100644
> --- a/node_modules/react-native/Libraries/Linking/Linking.js
> +++ b/node_modules/react-native/Libraries/Linking/Linking.js
> @@ -94,13 +94,11 @@ class Linking extends NativeEventEmitter {
>     * it will give the link url, otherwise it will give `null`
>     *
>     * See https://reactnative.dev/docs/linking.html#getinitialurl
> +   * Modified with patch-package after seeing this comment:
> +   * https://github.com/facebook/react-native/issues/25675#issuecomment-656137889
>     */
>    getInitialURL(): Promise<?string> {
> -    return Platform.OS === 'android'
> -      ? InteractionManager.runAfterInteractions().then(() =>
> -          nullthrows(NativeIntentAndroid).getInitialURL(),
> -        )
> -      : nullthrows(NativeLinkingManager).getInitialURL();
> +     return nullthrows(NativeLinkingManager).getInitialURL();
>    }
>  
>    /*
> ```

Just to follow up and for anyone trying this patch, I get `[Error: Got unexpected null]` at the `return nullthrows(NativeLinkingManager).getInitialURL();` which makes my app crash. So this patch is probably not the fix

**Comment by haveneersrobin** [comment]
Another follow up, if you are creating a URL from the return value from `Linking. getInitialURL()` using the constructor (`new URL(...))` and check for the hostname using the getter, like so:
``` ts
const url = await Linking.getInitialURL();
  if (url) {
    callback(new URL(url));
  }
  
...

if (url.hostname === 'something')

```
make sure you use [`react-native-url-polyfill`](https://github.com/charpeni/react-native-url-polyfill) because the RN URL `hostname` getter is not supported 🤦‍♂️  This is what caused (part of) our issues ...
See: https://github.com/facebook/react-native/blob/356075355908f4901b87ad6ce33c157f01c8e748/Libraries/Blob/URL.js#L164

**Comment by B4ckes** [comment]
Hi, i'm having this same problem with `Linking.getInitialURL()` here. It's being used inside a singleton service function, where i use a `Linking.addEventListener()` that works fine.
But when i try to use the `getInitialURL` before `AppRegistry.registerComponent()` call, it works properly.
Using NativeLinking as suggested before works fine in the service.

**Comment by emilioheinz** [comment]
> a cleaner solution:
> 
> ```js
> import NativeLinking from "react-native/Libraries/Linking/NativeLinking"
> 
> ...
> 
> const url = await NativeLinking.getInitialURL()
> handleUrl({ url })
> ```
> 
> tested with: `adb shell am start -W -a android.intent.action.VIEW -d socializus://dev.socializus.app/users/1 com.social.firebase.example.socializus`

This doesn't work in the latest React Native version because the file doesn't exist. Any ideas?

**Comment by talaikis** [comment]
Linking` works fine in Android (0.65.1) w/o those modifications, except that it always passes empty url.

**Comment by markl-vesper** [comment]
While this issue seems to be more related to getInitialURL, I'm wondering if it has any wider impact on linking.

Current scenario is

RN 0.65.1
AWS Amplify 4.2.10

Have followed all instructions for Social Sign In via https://docs.amplify.aws/lib/auth/social/q/platform/js/

Google UI opens up and user authenticates. Cognito returns the callback url and we have tested this in browser via hosted UI and confirmed, yet app sits on the google auth screen and never closes as if the link was not handled. Authentication however is completed because if i restart the app and click google sign-in then the app must sense the token or gets a different response from google and signs me straight in. 

Wondering if it could be related to my gmail account requiring MFA? The in-app browser tab does blur when the MFA is completed though

Its actually likely the linking is working fine, as when I run

`adb shell am start -W -a android.intent.action.VIEW -d "cortexmonitoringapp://signin" com.cortexmonitoring/.MainActivity`

The app rcv's the intent/link OK although it obviously doesn't contain any token etc etc

Any clues gratefully accepted thanks

**Comment by kale1d** [comment]
Some updates on this issue? In version 0.65.1 still happens...

**Comment by ray-toby** [comment]
Some updates on this issue?

**Comment by bob007abc** [comment]
Almost 2.5 years, Great! Orz...

**Comment by footniko** [comment]
In our case, it turned out that our `intentFilters` were not configured properly. Everything works fine on Android without any workarounds.

**Comment by lnwanghao** [comment]
It's seems still a bug when app is from background to foreground Linking.getInitialURL return null

**Comment by Balthazar33** [comment]
I ended up using this workaround:

In **App.js**:

```
import NfcManager from 'react-native-nfc-manager';

useEffect(() => {
    getUrl();
  }, []);
  
async function getUrl() {
    let event = await NfcManager.getLaunchTagEvent();
    console.log('Event', event);
    //Outputs {"id": "A1B2C3D4", "techTypes": ["android.nfc.tech.IsoDep", "android.nfc.tech.NfcA"]}
  }
```

My **AndroidManifest.xml** looks like this:

```
<uses-permission android:name="android.permission.NFC" />

<application>
  <activity>
       <intent-filter>
          <action android:name="android.nfc.action.TAG_DISCOVERED" />
          <action android:name="android.nfc.action.NDEF_DISCOVERED" />
          <category android:name="android.intent.category.DEFAULT" />
        </intent-filter>
    </activity>
 </application>
```

**RN 0.68.0**

**Comment by kivohin** [comment]
> > In our case, it turned out that our `intentFilters` were not configured properly. Everything works fine on Android without any workarounds.
> 
> Hi @footniko Could you please mention what was missing?

To expand on @footniko answer, we are using Expo SDK v44 (React Native v0.64).
The reason `Linking.getInitialURL()` was always returning `null` on Android was because we never configured the `intentFilters` for Android.

In order to do so when using Expo you need to follow the instructions here:
https://docs.expo.dev/guides/linking/#deep-links-on-android
https://docs.expo.dev/versions/latest/config/app/#intentfilters

Keep in mind, in Expo when you change the `app.json` or `app.config.ts` files you need to do a full app store release in order for the changes to apply. You can not do an over-the-air update.

If you are not using Expo then you will probably need to apply the same `Intent Filter` changes but in the `AndroidManifest.xml` file.

**Comment by soulfresh** [comment]
> ```js
> import { Linking, Platform } from 'react-native'
> import NativeIntentAndroid from 'react-native/Libraries/Linking/NativeIntentAndroid'
>
> const NativeLinking = Platform.OS === 'android' ? NativeIntentAndroid : Linking
> 
> NativeLinking.getInitialURL().then(url => console.log(url))
> ```

I was struggling with this issue recently as well and found two things. 1) The above resolved the issue on Android for me. 2) The root cause of my issue actually turned out to be a custom animation using React Native `Animation` running at the same time that Linking was trying to get the initial URL. I haven't tracked down exactly what it is about the animation that was preventing `InteractionManager.runAfterInteractions` from firing on Android but preventing my animation from running resolved the `Linking` error without having to resort to `NativeIntentAndroid`.

Hope that helps someone.

**Comment by footniko** [comment]
> > In our case, it turned out that our `intentFilters` were not configured properly. Everything works fine on Android without any workarounds.
> 
> what did you fix in your intentFilters @footniko ?

Check this reply: https://github.com/facebook/react-native/issues/25675#issuecomment-1098636303

**Comment by rveruna** [comment]
Still an issue in 0.68.5. 
I went aroud it by using 
`import NativeIntentAndroid from 'react-native/Libraries/Linking/NativeIntentAndroid';`
`NativeIntentAndroid.getInitialURL().then(handleUrl);`

**Comment by GuillaumeHemmen** [comment]
This issue is still valid IMO; please remove the stale label.

**Comment by MaryKilduff68** [comment]
Has there been any update on this issue?

**Comment by fabOnReact** [comment]
could you provide a minimum reproducible example?
Can you reproduce this issue using an existing minimum reproducible example (like this one https://github.com/facebook/react-native/issues/25675#issue-468657941) and adding steps explained by https://github.com/facebook/react-native/issues/25675#issuecomment-1098636303?

**Comment by tmitchel2** [comment]
I've just started to get this issue after upgrading to 0.73, it is adding approximately 10s onto my app startup time waiting to resolve the promise.

It looks like in 0.73 the code has been moved to native code so the above workarounds will now no longer work.

Also for me I think the reason I get this is due to the fact im calling Linking.getInitialUrl as early as possible in my app start, even before a screen has been rendered.  I don't really want to change this because the initial url can actually determine alot about how my app starts up in testing scenarios.

I can only think that it should be optional to wait for an activity? (im not up on android app lifecycles though)

**Comment by stephenkopylov** [comment]
Facing this issue sometimes while trying to get initial url as soon as possible on the startup

Seems like something relates to the this topic

```
Error
Cannot await activity from more than one call to getInitialURL

    IntentModule:84 com.facebook.react.modules.intent.IntentModule.waitForActivityAndGetInitialURL
    IntentModule:59 com.facebook.react.modules.intent.IntentModule.getInitialURL
    Method.java:-2 java.lang.reflect.Method.invoke
    JavaMethodWrapper:372 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper:149 com.facebook.react.bridge.JavaModuleWrapper.invoke
    SourceFile:-2 com.facebook.jni.NativeRunnable.run
    Handler.java:743 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler:27 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:150 android.os.Looper.loop
    MessageQueueThreadImpl:234 com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
    Thread.java:833 java.lang.Thread.run
    node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:105:59 promiseMethodWrapper
    node_modules/react-native/Libraries/Linking/Linking.js:98:53 getInitialURL
    node_modules/@react-navigation/native/src/useLinking.native.tsx:31:29 anonymous
    node_modules/@react-navigation/native/src/useLinking.native.tsx:141:42 anonymous
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:3771:68 mountState
    node_modules/react/cjs/react.production.min.js:25:401 useState
    node_modules/@react-navigation/native/src/useThenable.tsx:4:34 useThenable
    node_modules/@react-navigation/native/src/NavigationContainer.tsx:103:48 NavigationContainerInner
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:3525:21 renderWithHooks
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:4316:29 updateForwardRef
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7929:24 beginWork$1
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7304:24 performUnitOfWork
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7297:53 workLoopSync
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7279:18 renderRootSync
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6975:33 performSyncWorkOnRoot
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2145:30 flushSyncCallbacks
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8462:57 batchedUpdatesImpl
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1106:29 batchedUpdates
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1137:16 _receiveRootNodeIDEvent
    node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1178:27 receiveEvent
    (native) apply
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:433:33 __callFunction
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:25 anonymous
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:10 __guard
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:16 callFunctionReturnFlushedQueue
```

**Comment by TomasSestak** [comment]
still valid

**Comment by BlackMonday-ai** [comment]
I am also facing this problem
 "expo": "~51.0.8",
 "react-native": "0.74.1",
 
 
 
 other
 "dependencies": {
    "@expo/metro-runtime": "~3.2.1",
    "@expo/vector-icons": "^14.0.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/material-top-tabs": "^6.6.13",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "expo": "~51.0.8",
    "expo-application": "~5.9.1",
    "expo-auth-session": "~5.5.2",
    "expo-constants": "~16.0.1",
    "expo-crypto": "~13.0.2",
    "expo-dev-client": "~4.0.14",
    "expo-device": "~6.0.2",
    "expo-font": "~12.0.5",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-notifications": "~0.28.3",
    "expo-secure-store": "~13.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-web-browser": "~13.0.3",
    "lottie-react-native": "6.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-swipe-up-down": "^1.2.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-web": "~0.19.6",
    "react-redux": "^9.1.0",
    "redux": "^5.0.1"
  },

**Comment by BlackMonday-ai** [comment]
any work around?

**Comment by ThunbergOlle** [comment]
Has anyone solved this?

**Comment by kulak91** [comment]
Can someone competent please elaborate on why this issue was closed as "Not Planned"? We're still experiencing this issue with React Native.

**Comment by evelant** [comment]
@cortinico would you please reopen this? I'm not sure why it got closed

**Comment by cortinico** [comment]
If you folks are still experiencing the same issue, you should open a new issue + provide a newer reproducer. We won't be reopening a 6 years old issue without a valid repro as it's inactionable for us

**Comment by evelant** [comment]
I think people keep landing here because this issue is linked in the react navigation docs https://reactnavigation.org/docs/configuring-links

> warning
Currently there seems to be bug ([facebook/react-native#25675](https://github.com/facebook/react-native/issues/25675)) which results in it never resolving on Android. We add a timeout to avoid getting stuck forever, but it means that the link might not be handled in some cases.
