### ISSUE TITLE
'React/RCTBridgeDelegate.h' file not found

### ISSUE THREAD

**Issue by BooYeu** [facebook/react-native#25838]
Same error for the demo AwesomeProject.
react-native info:

info Fetching system and libraries information...
System:
OS: macOS 10.14.6
CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
Memory: 1.15 GB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 12.6.0 - /usr/local/bin/node
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
Android SDK:
API Levels: 23, 28, 29
Build Tools: 28.0.3, 29.0.1
System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 3.4 AI-183.6156.11.34.5692245
Xcode: 10.3/10G8 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.6 => 16.8.6
react-native: 0.60.4 => 0.60.4
npmGlobalPackages:
react-native-cli: 2.0.1

**Comment by ldco2016** [comment]
Greetings, I am having a similar issue:

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.26 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

This is my `ios/NFIBEngage/AppDelegateh` file:

```
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;

@end
```

The error is telling me it can't find that import:

```
AppDelegate.h:8:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
```

**Comment by slavikdenis** [comment]
Duplicate https://github.com/facebook/react-native/issues/25707 ?

**Comment by ldco2016** [comment]
@slavikdenis , this:

Solution:
-Install Cocoa Pods
sudo gem install cocoapods
-In your Project Folder:
cd ios
pod install

is not a solution. I already have Cocoapods installed and ran `pod install`. In fact, the error I have above is what I got after I added new Targets to my XCode and ran a `pod deintegrate` cleaned the XCode and rebuilt it and then refactored the `Podfile` and then successfully ran `pod install`.

Afterwards, when I ran `react-native run-ios`, thats when I started getting the following error:

```
AppDelegate.h:8:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
```

The file does indeed exist in my `Pods/Headers/Public` directory inside of the `React/` folder that is inside of `React-Core/`. Any help would be appreciated. Here is the MVP that looks similar to what I have:

https://github.com/ldco2016/NFIBEngage

And this is the `Podfile` configuration it needs:

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'DEV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DEV
  # pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'

  # Pods for NFIBEngage
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'NFIBEngageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'NFIBEngage-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NFIBEngage-tvOS



end

target 'PROD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PROD
  # pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'

  # Pods for NFIBEngage
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

target 'QA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QA
  # pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'

  # Pods for NFIBEngage
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

target 'UA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UA
  # pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'

  # Pods for NFIBEngage
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end
```

If anyone can add the above configuration to that MVP and then run `react-native run-ios` and not get this error:

```
AppDelegate.h:8:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
```
that is what I am trying to accomplish myself.

**Comment by vnanaware** [comment]
After install pod also not working same error occured

act/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by slavikdenis** [comment]
@ldco2016 well, for me it somehow worked. Please let us know, if you find the solution for your problem. Thanks

**Comment by ldco2016** [comment]
So is this not a bug with React Native? A lot of people are reporting this same behavior.

**Comment by BooYeu** [comment]
I see “scheme” in Xcode shows React(missing)

**Comment by mohmmadmoussa1988** [comment]
> I see “scheme” in Xcode shows React(missing)

Did you find a solution for missing React in "scheme" ?

**Comment by ham118** [comment]
Facing the same problem "'React/RCTBridgeDelegate.h' file not found".

**Comment by dvuvne** [comment]
You can fix this issue by installing the missing dependencies using pods.
These are the steps you should follow:
`
cd ios
pod install
`
After that, re-run the project. It should build with no errors.

**Comment by dvuvne** [comment]
You can fix this issue by installing the missing dependencies using pods.
These are the steps you should follow:
- cd ios 
- pod install

After that, re-run the project. It should build with no errors.

**Comment by Moseqi** [comment]
> > I see “scheme” in Xcode shows React(missing)
> > Did you find a solution for missing React in "scheme" ?
> > did you?
> 
> I change the version from 0.60 to 0.59.10

Is it a bug with v0.60? I am using 0.60.5.

**Comment by iamawaisakram** [comment]
> > > I see “scheme” in Xcode shows React(missing)
> > > Did you find a solution for missing React in "scheme" ?
> > > did you?
> > 
> > 
> > I change the version from 0.60 to 0.59.10
> 
> Is it a bug with v0.60? I am using 0.60.5.

Same Version and same issue here as well!

**Comment by Moseqi** [comment]
@iamawaisakram any solution?

**Comment by rvaitkus23** [comment]
in Header Search Paths you should add `$(inherited)`. This has solved the problem for me. And if you would look at warnings after `pod install` it does indicate that.

**Comment by anilgurindapalli** [comment]
@dvuvne solutions solved my problem

**Comment by ham118** [comment]
> in Header Search Paths you should add `$(inherited)`. This has solved the problem for me. And if you would look at warnings after `pod install` it does indicate that.

Followed these steps still throw the same error.

**Comment by ziyoshams** [comment]
If you have React missing in in your scheme, you have to add `React.xcodeproj ` manually. 
 - On your **Project Navigator** (left panel with folders):
    - Click with two finger for the menu (anywhere).
    - Choose _Add Files to "YOUR PROJECT NAME"_
    - Navigate to `node_modules/react-native/React` and choose `React.xcodeproj`.
    - Clean your project and re-run.

**Note:** `React.xcodeproj` was removed from **0.61**.

**Comment by AshishKapoor** [comment]
Facing the same problem "'React/RCTBridgeDelegate.h' file not found".

Quick fix:
$ ```cd ios && pod install```

**Comment by dariuxmx** [comment]
@AshishKapoor it works, just need install pods.

**Comment by mauriciodeleonc** [comment]
> You can fix this issue by installing the missing dependencies using pods.
> These are the steps you should follow:
> 
>     * cd ios
> 
>     * pod install
> 
> 
> After that, re-run the project. It should build with no errors.

This fixed issue for react native v. 0.61 and xcode v. 11.0 (11A420a)

**Comment by DaveLomber** [comment]
Same issue here with RN61 - mission React 

`pod install` does not help

**Comment by pradhul-dev** [comment]
The same issue here when upgrading from RN59.5 to RN0.61.1.

**Comment by gakuru** [comment]
Installing cocoa pods then installing the missing dependencies with pods sorted the issue for me here are the steps to follow:

* sudo gem install cocoapods
* cd ios
* pod install

Close any current xcode sessions.
Close any current open simulators.

Then restart your app again

**Comment by findli** [comment]
pod install in ios dir giving me ".../bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory"

macos catalina 10.15 (19A602)

**Comment by davidmarinangeli** [comment]
I still have this problem in React Native Navigation files ( any "React/..." ). A workaround I have found is changing all `<React/XXXX.h>` in 'XXXX.h` but I don't think it will work properly. 

I have tried to add React to Schemes ( also if it shouldn't be required with 0.61...right? ), delete `Derived Data`, run `pod install` and many other things. 

Is there anyone who figured it out?

**Comment by enigmablue** [comment]
Same problem. Should React .xcodeproj have been removed when library imports are still looking up to it?

**Comment by macool** [comment]
I am having same issue. We're upgrading from 0.59.5 to 0.61.2.

Basically every `#import <React/{ModuleName}>` is not available - but **it is available** when requiring just “{ModuleName}”, eg:

```
#import <React/RCTBridgeModule.h>
# raises /node_modules/react-native-splash-screen/ios/RNSplashScreen.h:9:9: 'React/RCTBridgeModule.h' file not found

#import <RCTBridgeModule.h>
# this works however ^
```

**Comment by davidmarinangeli** [comment]
I tried to start fresh with a new project ( ` react-native init AwesomeProject ` ) and then added the lib`React Native Navigation ` ( that was the library that was giving this issue ). 

The build was successful so I tried to import all the pods and all the paths from the `Header search path` in XCode from there and paste in my project. After that, the problem was gone.

Unfortunately now they give me problems with `Mach O-Linker` so I think I will create a new project, import all the libraries and then try to make them work in the original one.

**Comment by damathryx** [comment]
`pod install` does not solve it for me. Has anyone found any other solution?

**Comment by davidmarinangeli** [comment]
@damathryx have you tried to do what I did in my last comment? Try to install the library that gives you issues with a fresh project then you should copy all the pods needed.

**Comment by ccielo** [comment]
I had the same problem.
in my case after starting the project,
only installed **react-native-camera** through pods,
It hasn't worked since then.

So the first reasoning was that only in react-native-camera
I reached this place to find out the cause of the problem

**[Experiment 1]**
I did one experiment. When I installed the latest version
Is there a React (missing)?
Curiously, already missing existed and was running well.

**[Experiment 2]**
Then simply didnt set anything(ex- react-native-camera)
I tried and run ios / pod install.
In this case, only the patch worked and it worked fine.

**[Experiment 3]**
installed react-native-camera
I've added it to the npm install & podfile as described in the manual.
In this case, 

> Link Binary With Libraries, Header search, etc.
The process was excluded.

**[Experiment 4]**
when I added link binary with libraries and it failed.
just there was libPods-$ {projectName}.

Then 

> can I import react-native-camera to code?

Was my question.
So I tried to import
It worked fine.

So my conclusion is this.
**Linked Frameworks and Binaries, only the libPods- * project * .a**
because already pod installed other pod.

**+ but, But I'm not sure it's just my judgment and my case!**

**Comment by Neha1405** [comment]
> `roj` was removed from **0.61**.

What to do for **0.61** ? i m getting the same error

**Comment by basha777** [comment]
same issue while upgrading from RN 0.59.9 to 0.60.0, any solution? .

**Comment by davidmarinangeli** [comment]
Hi guys, as I wrote some days ago, my problem was that `React Native Navigation` could not find the right pods and dependencies. 

The **first** thing you should do is to detect the library is causing this error: do the files that give you errors belong to some library? If so, have you tried to create a new project with a brand new version of RN and import the guilty library?

I would be very happy to help you since I spent like 4-5 days on it! 😅

**Comment by basha777** [comment]
If you guys are upgrading from 0.59.10 or below to 0.60.0 or above, the issue seems to be with the manual linked libraries, we need to remove all the manually libraries as show [here](https://github.com/react-native-community/upgrade-helper/issues/47) and we should instead add these manually linked libraries to our podfile for example if you have **react-native-vector-icons** installed, your pod file with core packages should look something like this 
`
target 'YourAppName' do

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#Add other pods here

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  post_install do |installer|
    installer.pods_project.targets.each do |target|

      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

    end
  end



  

  
end
`

after removing the libraries it should look some thing like this.
![Screenshot 2019-11-11 at 7 56 02 PM](https://user-images.githubusercontent.com/15177339/68595774-20dfef00-04c0-11ea-9964-384fb8700859.png)

At last 
```
cd ios
pod install 
```
i was able to solve this issue following these steps, hope it helps others.

**Comment by jcampuza** [comment]
@basha777 This works fine if all of the libraries in your project are compatible with cocoapods, but we still have some libraries that have to be manually linked. Those libraries all still fail with the same errors. Anybody found a workaround for that?

**Comment by enigmablue** [comment]
In the end i got it to work by putting this at the top of my podfile. Replace the packages with the ones that are failing for you, of course. It will create a new "project" and until the maintainers update the structure of their packages, it will be stuck.

I also believe i had to manual link the binaries

```
 workspace './xxxx.xcworkspace'
target 'RNSVG' do
   project '../node_modules/react-native-svg/ios/RNSVG.xcodeproj'
 end

 target 'RNMixpanel' do
   project '../node_modules/react-native-mixpanel/RNMixpanel.xcodeproj'
 end

 target 'RNViewShot' do
   project '../node_modules/react-native-view-shot/ios/RNViewShot.xcodeproj'
 end
```

**Comment by maulikdhameliya** [comment]
I was facing same problem when I added a new target and did a `pod install`. here is the [solution](https://stackoverflow.com/a/59007876/2053735).

My `react-native info` is as below.
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    Memory: 701.86 MB / 12.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Hope it helps to someone

**Comment by nihp** [comment]
I am getting the above error and also in Xcode Product -> Edit Scheme shows --> React missing.

This is because while runnig the pod install again it removing the react from the Podfile. Kindly refer the attached image. 

Anyone have any solution for this?

Also I am getting 

`failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening app.xcworkspace. Run CLI with --verbose flag for more details.
`
`error Could not find the following native modules: BugsnagReactNative, react-native-camera, react-native-cookies, react-native-fast-image, react-native-fetch-blob, RNImageCropPicker, react-native-image-picker, RNImageRotate, BVLinearGradient, react-native-orientation, RNShare, RNSVG, RNVectorIcons, RNViewShot, react-native-webview, rn-fetch-blob. Did you forget to run "pod install"`

![Screenshot 2019-11-25 at 10 14 56 AM](https://user-images.githubusercontent.com/36992338/69514311-dc992800-0f70-11ea-8e02-5fb78e316464.png)

**Comment by Alaa-Ben** [comment]
Here's what I did to solve this:
- cd ios && pod install.
- Then go to the same screen (scheme/build)
- Delete the React (missing)
- click on the + on the bottom left
- add React (from pods section). 
- Finally, check all the checkboxes and place React at the top of the list.

**Comment by nihp** [comment]
Now I am getting 
```

▸ Running script '[CP] Check Pods Manifest.lock'

❌  error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening helloworld.xcworkspace. Run CLI with --verbose
```

**Comment by Alaa-Ben** [comment]
@nihp I think you should clean up your pods:
- gem install cocoapods-deintegrate
- gem install cocoapods-clean
- Go to the project ios directory and run pod deintegrate
- run pod clean
- Run pod install

**Comment by nihp** [comment]
May you clarify why I am getting this error.

I have **fixed this Sandbox error** is resolved after removing podfile.lock and pod install

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening helloworld.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Applications/app/ios/build/helloworld
```

**Comment by Alaa-Ben** [comment]
I would still clean up pods using the steps in my previous comment.
Which command gives you this error ?

**Comment by nihp** [comment]
I have removed Podfile.lock and then pod install.

Then react-native run-ios

Now the Xcode shows the error which I have asked in the question(file not found)
In terminal it shows the error https://github.com/facebook/react-native/issues/25838#issuecomment-558095737

**Comment by nihp** [comment]
I will clean my pods and let you know.

I have a question. Shall i need to checkout the changes which is available for podfile.

**Comment by nihp** [comment]
I have cleaned as per your https://github.com/facebook/react-native/issues/25838#issuecomment-558093699. But again it shows the same error as in terminal and Xcode

**Terminal:** 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening helloworld.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Applications/app/ios/build/helloworld


**Xcode: (While compiling AppDelegate.m)**
 
/node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.h:3:9: 'React/RCTBridgeModule.h' file not found

**Comment by Alaa-Ben** [comment]
> Here's what I did to solve this:
> 
> * cd ios && pod install.
> * Then go to the same screen (scheme/build)
> * Delete the React (missing)
> * click on the + on the bottom left
> * add React (from pods section).
> * Finally, check all the checkboxes and place React at the top of the list.
Did you do this after cleaning pods ?

**Comment by Alaa-Ben** [comment]
> > 
> > * cd ios && pod install.
> > * Then go to the same screen (scheme/build)
> > * Delete the React (missing)
> > * click on the + on the bottom left
> > * add React (from pods section).
> > * Finally, check all the checkboxes and place React at the top of the list.
> 
> Did you do this after cleaning pods ?

**Comment by nihp** [comment]
@Alaa-Ben I am facing the same error repeatedly. If I run pod install react is added for the first time. For the next run of Pod install, it will delete the React. So the error RCTBridgeDelegate.h arise. 

If I add react and then it shows the Sandbox error.

I am facing these two errors and it gets me stuck and not able to build my apps. 

Kindly provide any correct solutions with steps which need to fix the above two errors

**Comment by nihp** [comment]
After cleaning it will shows like below attached image.
![Screenshot 2019-11-26 at 9 40 14 AM](https://user-images.githubusercontent.com/36992338/69599047-99eb5480-1031-11ea-8b10-9a76699529e2.png)

**Comment by pedromelo98** [comment]
Same problem here, pod install did not solve

**Comment by pedromelo98** [comment]
While there are no solutions yet, I presume, I just downgraded my react-native version at package.json:
`rm -rf node_modules/`
edit package.json file:
from:
`"react-native": "^0.61.4",`
to
`"react-native": "0.60.0",`
and
`npm install` again.
react-native 0.60 has React.xcodeproj but it's not the correctly solution.

**Comment by nihp** [comment]
Anyone have any solution

**Comment by nihp** [comment]
@pedromelo98 In 0.60.0 there is auto-link support or manual link.

Shall I need to create react-native.config.js file here.

**Comment by thiagofuss** [comment]
> Here's what I did to solve this:
> 
> * cd ios && pod install.
> * Then go to the same screen (scheme/build)
> * Delete the React (missing)
> * click on the + on the bottom left
> * add React (from pods section).
> * Finally, check all the checkboxes and place React at the top of the list.

Worked for me, thanks

**Comment by nihp** [comment]
@thiagofuss Which version of react-native you have upgrade

**Comment by Alaa-Ben** [comment]
@nihp FYI, the steps i wrote worked for me when I upgrade from 0.59.10 to 0.61.1

**Comment by nihp** [comment]
@Alaa-Ben I did like this can you confirm did you do like this or if you have any changes or any steps need to modify kindly let me know.

```

1. rm -rf node_modules (here I removed rnpm and chnaged the script as per react-upgrader in package.json file
2. npm install
3. run pod install(installed pods)
4. react-native run-ios (shows error need to unlink packages)
5. unlink all packages (now my pod file is empty)
6. Again i run pod install
7. It removed React, ImagePicker packages
8. Now the product ==>Edit scheme for react is missing (There is no list of third party packages in Manage schemes)
9. Then I remove Pods and Podfile.lock (now the podfile not have any packages in its target)
10. I did clean which you mentioned above
11. Again pod install
12. It only added the Frameworks which I added above for Crashlytics and Fabric
13.Then I have reverted the Pod file and run pod install. Again it added all packages and still the issue is there.
```

Can you tell how the podfile will shows the packages inside target after upgrade and how it will add in Product --> Edit scheme

**Comment by nihp** [comment]
@Alaa-Ben I still facing the same issues 

Above solution not worked for me

/Users/jesphin/work/projects/new_p/App/ios/MyApp/AppDelegate.m:11:9: 'RCTBundleURLProvider.h' file not found

**Comment by Alaa-Ben** [comment]
@nihp I don't understand why you pod install twice (I believe step 6 is not needed)

**Comment by nihp** [comment]
@Alaa-Ben 

Now I am facing the same error. While pod install it add 20 dependencies and shows success message.

But react-native run-ios failed with the error.

node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.m:4:9: 'RCTVersion.h' file not found


I have checked the Header Search paths it have the bugsnag.

Any solution for this

I am facing three error one by one 
React/RCTBridgeDelegate.h' file not found
React/RCTBundleURLProvider.h file not found


Step 10: Clean the build from Xcode

Step 6: Are you sure after unlinking the packages we not need to run pod install.

Also, I have added use_nativemodules in my podfile.

So the React is not removed after running pod install again.

**Comment by nihp** [comment]
@Alaa-Ben I created and checked with the another example project. These are my observations with my upgraded and example project

Before the upgrade the Header Seach path is like '(SRCTRoot/../..anypackages) same will be there after upgrade or not?

Because I have generated a new example project to check this. But I can see the difference in the Header search paths "${PODS_ROOT}/Headers/Public/BugsnagReactNative".

Also, I am facing RCTBridgeDelegate.h file and other files with extensions are not found while compiling my upgraded project.

But the example project is working fine. Can anyone suggest how can I isolate and build my existing upgraded app without a runtime error?

Note: Example app has third party packages in podfile but the existing project removed all third party packages while running react-native unlink command.

**Comment by Alaa-Ben** [comment]
You clearly failed your migration. The fact that you didn't add `use_nativemodules` before shows that you didn't add everything you should when migrating. I suggest you check react native upgrader again.

**Comment by nihp** [comment]
@Alaa-Ben I have added use_nativemodules already it is in my podfile. I not get you what you mean.

**Comment by nihp** [comment]
Are you mean while migrating all the header path will change. Can you help me how can I do it again to work this. Or need to work entirely new the upgradation process. Can you kindly suggest the steps? Already I have spend lot of time here. I don't want to make any mistake again.

**Comment by Alaa-Ben** [comment]
I've already written the steps I did to make it work. If it doesn't work for you, sorry but I have no idea what the problem is :/

**Comment by nihp** [comment]
Can you confirm how your Header Search Paths are like and provide a sample for me

**Comment by nihp** [comment]
@Alaa-Ben Can you confirm how the Header Search path is look like before and after upgrade.

In my case both shows the RCTROOT 

```
Before the upgrade the Header Seach path is like '(SRCTRoot/../..anypackages) same will be there after upgrade?

 But I can see the difference in the Header search paths while creating a new example project "${PODS_ROOT}/Headers/Public/BugsnagReactNative".
```

**Comment by LiangQiangQiang** [comment]
If it's 0.61. X, I find a solution to this problem!

in Podfile add:


#添加本地封装库
install! 'cocoapods',
:integrate_targets => false#消除警告
workspace 'path/to/Workspace.xcworkspace'
#这里开始描述
target 'RCTHttpCache' do    #Set the plug-in you want to use here!
  project '../node_modules/react-native-http-cache/ios/RCTHttpCache.xcodeproj'
end

**Comment by marlti7** [comment]
same problem  rn:0.59

**Comment by TheoGit** [comment]
@basha777 your solution WORKED!  Thank you!  That took days to figure out - a diagram goes a long way - it's unbelievable how many people are having this issue and there's not set solution - I hope the good folks running RN take notice.

**Comment by luatnd** [comment]
> **Check your Scheme** by going to _Product -> Scheme -> Edit Scheme -> Build_
> and if you see `React(missing)` in in your scheme, you have to add `React.xcodeproj ` manually.
> 
> * On your **Project Navigator** (left panel with folders):
>   
>   * Click with two finger for the menu (anywhere).
>   * Choose _Add Files to "YOUR PROJECT NAME"_
>   * Navigate to `node_modules/react-native/React` and choose `React.xcodeproj`.
>   * Clean your project and re-run.
> 
> **Note:** `React.xcodeproj` was removed from **0.61**.

Why dislike him? this is the most logical explanation !!

**Comment by Floridus** [comment]
I have the same error with RN 0.61.5. I removed missing React from my scheme and added React from Pods (see in image above)

![image](https://user-images.githubusercontent.com/21052305/72158051-9cbfc000-33b9-11ea-9c0f-b44392c15777.png)

I did all things:

rm -rf node-modules
rm -rf ios/Pods
rm ios/Podfile.lock
rm -rf ~Library/Developer/Xcode/DerivedData

and then yarn install + cd ios and pod install

but nothing helps

this is my podfile

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def my_deps
  # Pods for Placeholder
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'boost-for-react-native', :podspec => 'https://raw.githubusercontent.com/react-native-community/boost-for-react-native/master/boost-for-react-native.podspec'
  # React-Native-Share pod
  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Analytics', '~> 6.3.0'

  #target 'PlaceholderTests' do
    #inherit! :search_paths
    # Pods for testing
  #end
  
end

target 'Placeholder' do
  my_deps
  use_native_modules!
end

target 'Placeholder-tvOS' do
  my_deps
  use_native_modules!
end

#target 'Placeholder-tvOS' do
  # Pods for Placeholder-tvOS
  #target 'Placeholder-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end
#
```

**Comment by luatnd** [comment]
Upgrade from react-native 0.5x codebase to 0.61.x is a nightmare If you don't have ios/android library management experience.

I fixed by doing this:
https://github.com/facebook/react-native/issues/26665#issuecomment-571082076

**Comment by Rutvik17** [comment]
I am having the same issue and i'm going nuts, has anyone found the solution ?
`cd ios`
`pod install`
DOES NOT SOLVE THIS 
react is still missing from the project in xcode after removing node_modules reinstalling pods
Anyone can help ?

**Comment by TheoGit** [comment]
@Rutvik17 to get React into the project:  
first you should be in the workspace - not the project
click Product => Scheme => edit Scheme
select the Build scheme (top of the list) 
click the "+" sign at the bottom of the dialog box
a dialog will open that reads "Choose targets to build as part of this scheme"
open the Pods drop down
search for React - and select, then close and build

for the missing .h file --- make sure that any podspec that you created has search path in the podspec:

  s.ios.xcconfig = {
    'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../Frameworks"',
  }

**Comment by hramos** [comment]
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.

**Comment by hesa2020** [comment]
Issue still happening could be fixed by a quick fix ( it works for me locally ) however when i use apppcenter which redownload the original file it doesnt have my fix...

Replace the import in RCTBridgeModule.h for:

`#if __has_include("RCTDefines.h")
#import "RCTDefines.h"
#else
#import <React/RCTDefines.h>
#endif`

Please commit a fix for this :)

**Comment by fabellonnoe** [comment]
In your project file:

```
rm -rf node_modules
npm install
cd ios
pod install
```

**Comment by makarkotlov** [comment]
I added ${PODS_ROOT} recursive in Build Settings -> Search Paths -> Header Search Paths and it worked

**Comment by wirrareka** [comment]
I had the same issue, setting higher Deployment Target in the xcode project solved it in my case

**Comment by VladosDosvidos** [comment]
My solution in this case.
First I have added React in my scheme because I had React(missing).
After this, I go to the Project -> Info -> Configurations (under Deployment target)
<img width="616" alt="Screenshot 2020-04-09 at 21 08 39" src="https://user-images.githubusercontent.com/9086246/78926771-53f5d100-7aa6-11ea-9f4c-5ddf8328de0c.png">
In this menu I found my current target and select correct Pods configurations for each others 
<img width="580" alt="Screenshot 2020-04-09 at 21 10 37" src="https://user-images.githubusercontent.com/9086246/78927122-ff068a80-7aa6-11ea-9af1-01aaac925960.png">

**Comment by collamo** [comment]
Thanks @VladosDosvidos! your solution worked for me.
XCode:11.4
React Native:0.62.2

**Comment by barrylachapelle** [comment]
Me too! Nice one @VladosDosvidos

**Comment by kas** [comment]
I followed these steps to fix the issue:
* cd ios
* pod install
* Open .xcworkspace file with Xcode

**Comment by sanukumarNS** [comment]
Let's say you had a Scheme A, you duplicated it to Scheme B

What I found happens when you run npm install is
For every scheme except A, 
   Build phases settings get changed to default 

To fix this unfortunately, 
Delete the Scheme B
Duplicate the original scheme(A) again and make the changes to make it your scheme B

**Comment by nihp** [comment]
I have React with concentric circles, not a React shape of house.

If I add this does it works for me?
![Screenshot 2020-06-08 at 3 12 10 PM](https://user-images.githubusercontent.com/36992338/84017535-6dc76d80-a99c-11ea-8145-71e3135e0e39.png)

**Comment by nppull** [comment]
> If you guys are upgrading from 0.59.10 or below to 0.60.0 or above, the issue seems to be with the manual linked libraries, we need to remove all the manually libraries as show [here](https://github.com/react-native-community/upgrade-helper/issues/47) and we should instead add these manually linked libraries to our podfile for example if you have **react-native-vector-icons** installed, your pod file with core packages should look something like this
> 
> ```
> target 'YourAppName' do
> 
>   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
>   pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
>   pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
>   pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
>   pod 'React', :path => '../node_modules/react-native/'
>   pod 'React-Core', :path => '../node_modules/react-native/'
>   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
>   pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
>   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
>   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
>   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
>   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
>   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
>   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
>   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
>   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
>   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
>   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
>   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
>   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
>   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
>   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
>   pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
>   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
>   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> 
> #Add other pods here
> 
>   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
> 
> 
>   post_install do |installer|
>     installer.pods_project.targets.each do |target|
> 
>       targets_to_ignore = %w(React yoga)
>       
>       if targets_to_ignore.include? target.name
>         target.remove_from_project
>       end
> 
>     end
>   end
> 
> 
> 
>   
> 
>   
> end
> ```
> 
> after removing the libraries it should look some thing like this.
> ![Screenshot 2019-11-11 at 7 56 02 PM](https://user-images.githubusercontent.com/15177339/68595774-20dfef00-04c0-11ea-9964-384fb8700859.png)
> 
> At last
> 
> ```
> cd ios
> pod install 
> ```
> 
> i was able to solve this issue following these steps, hope it helps others.

save my life <3

**Comment by lucasfjportela** [comment]
> I see “scheme” in Xcode shows React(missing)

I could solve this upgrading my Cocoapods version (1.5.3 to the 1.9.3). Then, after a `pod deintegrate && pod install`, in Xcode > Scheme > Edit Scheme remove the React (missing) target and add the React with the target icon:

> I have React with concentric circles, not a React shape of house.
> 
> If I add this does it works for me?
> ![Screenshot 2020-06-08 at 3 12 10 PM](https://user-images.githubusercontent.com/36992338/84017535-6dc76d80-a99c-11ea-8145-71e3135e0e39.png)

Clean and build your project and will fix the React related errors.

**Comment by VladosDosvidos** [comment]
@sanukumarNS Yes, your advice is also useful. Because I have two schemas in my project.

**Comment by Michael24884** [comment]
Still getting this error when archiving, on React 63.2

**Comment by rodrigofbm** [comment]
1+ year later and this still persist. Unfortunately this client doesn't want to move to Flutter yet

**Comment by Michael24884** [comment]
Not really a solution but I only managed to fix it by making a new React Native app with the same name and just copied and paste everything(IOS folder only). Pod install again. Again not the best solution but it ended up working. 
I got this error when upgrading from 0.62 to 0.63

**Comment by raffibag** [comment]
In my experience, if you happen to install and uninstall the wrong npm package, for example, you may irreversibly mess up your React Native project. The likely culprit is that some small - yet critical - library is removed on uninstall. In these cases, a total rebuild of the project is required. Would be nice if there's a way to restore or rollback to a previous state.

**Comment by willbonde** [comment]
I have this problem after creating a brand new react-native project. I've gone through the miscellaneous suggestions in this thread, like running pod install, etc. Interestingly enough, I zipped up the entire project and transferred it to a friend's computer running the exact same version of Xcode (12.0.1). It built first try, with zero changes to the project or config. I'm wondering if the problem could be caused by an Xcode setting?

**Comment by BoKKeR** [comment]
Updating from rn0.62 to 0.63, dont forget to include every schema in your pods. Otherwise the pods will only work for the one main schema.

https://github.com/react-native-community/upgrade-support/issues/55

**Comment by mouhsnimohamed** [comment]
here is what I did to fix this issue:

1. cd ios && xcodebuild clean
2. pod init (if you don’t have podFile already)
3. pod install

**Comment by JasonFehr** [comment]
Embarrassed to say I fought this problem for over an hour, eventually realizing that several commits earlier, I had deleted the tvOS targets in XCode without deleting the targets in the Podfile. This caused an error during pod install, but the phrasing of the error didn't make it clear that the pod install hadn't actually completed.

Thus, although I kept thinking I was running pod install, it wasn't actually happening, which resulted in this React/RCTBridgeDelegate.h' problem.

I doubt very much anyone else here is making such a silly mistake, but I thought I'd share anyway.

**Comment by yachaka** [comment]
Hurray!
After having troubles for multiples hours, I fixed my issue.

When going in `Edit Scheme` > `My Scheme`, I had `React (missing)`.
I added React back (click [-] on React, click [+], search React), then I still had this error. 🤔 
Then, I saw a comment that said that React must be at the top of the list (it got added on the bottom).

I moved `React` to the top of the list, and now the error disappeared. 🎉 
But now I have `ReactNativeNavigation.h` not found 😂

**Comment by abdelhedydev** [comment]
This solution was solved my problem
joltup/rn-fetch-blob#461 (comment)

**Comment by SnowLew** [comment]
I've just close xcode, remove node_modules and yarn.lock or package-lock.json
and inside ios folder:
pod deintegrate && pod cache clean -all && pod install
after this just run xcode again and it works

**Comment by sunwooz** [comment]
I'm currently on a lower version than react-native .60 so do not make use of pods.

I had to remove the podfiles and uninstall pods with 

`pod deintegrate project.xcodeproj`

**Comment by Acousticdesk** [comment]
Definitely, not the greatest solution and is not applicable to everyone, however, these are the steps that helped me in my situation:

- Remove the project repository
- Clone it from the remote repository
- Navigate to the project folder
- `npm install`
- `cd ios`
- `pod install`
- `npm run ios`

**Comment by AdamLee321** [comment]
> I had the same issue, setting higher Deployment Target in the xcode project solved it in my case

Great find, my podfiles deployment target was 11.0 and my projects was set to 10.0. Thanks.

**Comment by FairWageFreelancing** [comment]
would you guys/gals PLEASE stop suggesting `pod install` - jesus.
