### ISSUE TITLE
[0.60.5] fontWeight Has No Affect on Android When Using Numerical Values

### ISSUE THREAD

**Issue by AlexK777** [facebook/react-native#26193]
`fontWeight` properties on `Text` components are not having an affect on Android styles on React Native Version `0.60.5`. If I use the `bold` value, the `Text` component picks up the `bold` style, but any other value `200` up through `800` all display the same appearance as `normal` or `100`. I performed the same change on RN Version `0.59.10` and the `Text` component is styled correctly. 

React Native version:
```
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 13.78 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/Developer/Projects/hy-vee-grocery/node_modules/.bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
```

## Steps To Reproduce

1. Change the `fontWeight` of a `Text` component from `100` to `600` on Android.

Describe what you expected to happen:
`Text` component should be styled with new `fontWeight`, but the style does not change. 

Snack, code example, screenshot, or link to a repository:
**RN 0.60.5**
![fontWeight60](https://user-images.githubusercontent.com/7462060/63704083-e4b9be00-c7ef-11e9-8938-1f203aa06f00.gif)
**RN 0.59.10**
![fontWeight59](https://user-images.githubusercontent.com/7462060/63704097-edaa8f80-c7ef-11e9-83ba-34c0a26a448f.gif)

I just used `react-native init` projects at RN `0.59.10` and `0.60.5` to reproduce this behavior.

**Comment by dulmandakh** [comment]
It's known issue due to Android limitations. Only way to use custom font weights is to create a custom font.

Android added support changing font weights programmatically, but won't work on older versions.

**Comment by hweister** [comment]
@dulmandakh why old version of react native works?

**Comment by jonnyberanek** [comment]
> It's known issue due to Android limitations. Only way to use custom font weights is to create a custom font.

So... How would you go about doing that?

**Comment by chgsilva** [comment]
I am facing the same issue, any tips?

**Comment by cdunkel** [comment]
I have the exact same question as @hweister. If this were a pure Android limitation then why does it work in 0.58.6 on the same Android device / emulator?

**Comment by greg7gkb** [comment]
PR was here: https://github.com/facebook/react-native/pull/25341
Workarounds here: https://github.com/facebook/react-native/issues/25696

**Comment by aelesia** [comment]
I wrote a npm package to handle mapping of custom fonts (eg. Roboto-Light, Roboto-Heavy) to font weights. Heavily modified from [jacobcabantomski-ct's code](https://github.com/facebook/react-native/issues/25696#issuecomment-553091605) above.

[react-native-font-weight (alpha)](https://www.npmjs.com/package/react-native-font-weight)

**Comment by ARDcode** [comment]
thanks @aelesia and @jacobcabantomski-ct for idea and code
its temporary solution before 0.62 release for Expo and RN: [react-native-text-weight](https://www.npmjs.com/package/react-native-text-weight)

**Comment by leolusoli** [comment]
Has it been fixed in RN 0.62.0?

**Comment by samufort** [comment]
> Has it been fixed in RN 0.62.0?

No

**Comment by dacevedo12** [comment]
This issue should be reopened

**Comment by knoxgon** [comment]
Only **'bold'** seems to be working... Badly need the numerical values.

**Comment by Saurabh-stack** [comment]
I am too facing same issue.
I am using expo client and Android mobile device.

**Comment by fabriziobertoglio1987** [comment]
@Saurabh-stack https://github.com/facebook/react-native/issues/25696 fixes this. This issue will be closed once https://github.com/facebook/react-native/issues/25696 is merged

**Comment by zhigang1992** [comment]
It seems like roboto doesn't have 600 weight

https://fonts.google.com/specimen/Roboto#standard-styles

**Comment by AzadKshitij** [comment]
I still have the same issue can anyone tell me about how to solve it!!
react-native-cli: 2.0.1
react-native: 0.63.2

**Comment by danielfx90** [comment]
This is still happening, working with react-native v0.63.3.

**Comment by thuynt99** [comment]
Have any solution to fix that? I not want to use fontWeight : 'bold', it too bold!

**Comment by fabriziobertoglio1987** [comment]
@thuynt99 https://github.com/facebook/react-native/pull/29117

**Comment by anhquan291** [comment]
> Have any solution to fix that? I not want to use fontWeight : 'bold', it too bold!

same issue here hic hic

**Comment by thuynt99** [comment]
@anhquan291  I use Platform below:
`fontWeight: Platform = 'ios' ? '600' : 'bold' `

**Comment by mariuspotor** [comment]
@thuynt99 `Platform === 'ios'`

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29117 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by araujobarret** [comment]
Idk why this issue is `closed` since the problem persists

**Comment by Un-dev** [comment]
I also have this issue

**Comment by southkeys** [comment]
Bump. Seeking answers

**Comment by disko998** [comment]
The only way for me is a custom font, so you should just change the fontFamily accordingly ('roboto-bold, roboto-regular, etc.') witch is annoying...

**Comment by mausic** [comment]
react-native cli v0.64.1 issue still persist

**Comment by rumax** [comment]
> It's known issue due to Android limitations. Only way to use custom font weights is to create a custom font.
> 
> Android added support changing font weights programmatically, but won't work on older versions.

@dulmandakh Can you, please, elaborate a bit more about what kind of Android issue it is. And is it Android or RN Android issue? Looking into Android dos https://developer.android.com/reference/android/graphics/fonts/FontStyle it seems like it should be possible to use numeric values. Cannot find any limitations.

>  but won't work on older versions.

That's fine if RN supports the same, right? Rather than do not support at all, which also brings inconsistency with iOS, where fonts work fine.

**Comment by jtibrewal09** [comment]
Does anyone have a work around for it?

**Comment by KonstantinZhukovskij** [comment]
Have any solution to fix that?

**Comment by buitrbao222** [comment]
fontWeight 800 not working on Android but it does on iOS

**Comment by Navipro70** [comment]
Example:
If you have font `Moderat` (just example) and 3 types (Regular, Medium, Bold), font-weight on IOS will works normaly, but android understand only font-weight: "bold" (set and show Moderat bold font), other font-weight's (400, 500, 600 etc.) will set the regular font.

Solution is next:
We need to set fontFamily: 'ModeratMedium' if we need medium font on android. 

All cases:
```
const IS_IOS = Platform.OS === 'ios'

const styles = StyleSheet.create({
  regular: {
    fontFamily: IS_IOS ? 'Moderat-Regular' : 'ModeratRegular'
  },
  medium: {
    fontFamily: IS_IOS ? 'Moderat-Medium' : 'ModeratMedium'
  },
  bold: {
    fontFamily: IS_IOS ? 'Moderat-Bold' : 'ModeratBold'
  },
})
```

And remember that IOS use post-script font name and Android use full font name

**Comment by 1Jesper1** [comment]
Thanks @thuynt99

**Comment by Forpee** [comment]
Anybody found the solution?

**Comment by tibbus** [comment]
@Forpee this should be fixed in the last React Native v0.65.1

**Comment by faraxftw** [comment]
It seems to me, it's still not working - 0.65.1 is used

Font file looks like this:
![image](https://user-images.githubusercontent.com/87714216/134527339-693a89b1-9c33-401f-81fc-b63fbd567f34.png)

Is being used like this
![image](https://user-images.githubusercontent.com/87714216/134527401-98831bbe-dc40-4d0b-92c7-0d935e7f9b7e.png)

And it doesn't apply to Android
iOS: 
![image](https://user-images.githubusercontent.com/87714216/134527520-3bad7657-151f-41a9-ae64-22aab46dc972.png)
Android:
![image](https://user-images.githubusercontent.com/87714216/134527575-a9537127-f16e-4b72-ae6e-eaa8ccb55ba3.png)

Or is the whole way, that I use the font, "wrong"?

**Comment by imVinayPandya** [comment]
Sep 2021 same issue is still going on.

**Comment by fabriziobertoglio1987** [comment]
Version [0.65][1] includes my pr to this issue.

[1]: https://github.com/react-native-community/releases/blob/0.66-changelog/CHANGELOG.md#v0650

The fontStyle italic was not meant to be used with numeric fontWeights in my PR.



[My changes](https://github.com/fabriziobertoglio1987/react-native/blob/4cd0ea2039abc343bfea93a754952beec39b971c/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTypefaceUtils.java#L108-L111) do not apply the 100-900 fontWeight if you are using Italic or Bold-Italic styles.

The Italic or Bold Italic style over-rides the 100-900 fontWeight.
You either use fontStyle Italic and Bold or Italic, but can not use fontWeight 100-900 with fontStyle Italic.

```java
if (style == Typeface.ITALIC) {
  newStyle = (newStyle == Typeface.BOLD) ? Typeface.BOLD_ITALIC : Typeface.ITALIC;
  typeface = Typeface.create(typeface, newStyle);
}
```

I can try to find an alternative solution and prepare a new pr in the future.

The idea behind this was if you are using Bold and/or Italic, we will not use 100-900, but this probably was wrong way to solve this and I should revisit my solution.

I also need to verify that numeric fontWeights (100-900) are easy to use and implement in ReactNative with the above functionalities, maybe there are some limitations in the Android API.

Remember that fontWeight 100-900 is only available since [API 28](https://developer.android.com/reference/android/graphics/Typeface#create(android.graphics.Typeface,%20int,%20boolean))

https://github.com/fabriziobertoglio1987/react-native/blob/4cd0ea2039abc343bfea93a754952beec39b971c/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTypefaceUtils.java#L112-L114

```java
    if(Build.VERSION.SDK_INT > Build.VERSION_CODES.O_MR1 && weight > Typeface.BOLD_ITALIC) {
      typeface = Typeface.create(typeface, weight, italic);
    }
```



> as a note for the future https://github.com/facebook/react-native/commit/39e64c01c51d670fdc8d98cd75b3a3324480bf5e was refactored with https://github.com/facebook/react-native/commit/9d2fedc6e22ca1b45fbc2059971cd194de5d0170

The original solution was changed in the Master Branch.
I have to take that in consideration when writing a fix.

**Comment by faraxftw** [comment]
Okay, that surely makes sense.
I just grabbed the first example, to show it. There are many, but I happened to grab one of the two italic ones 😄
So I removed the "italic" and... well. Same behaviour:
![image](https://user-images.githubusercontent.com/87714216/134633120-1cc4b6f6-6362-4841-8292-4096b05ec5d3.png)
iOS:
![image](https://user-images.githubusercontent.com/87714216/134633157-1b26a78a-2d8c-4f1a-bddb-0cd732938cdb.png)
Android:
![image](https://user-images.githubusercontent.com/87714216/134633191-588d3db4-04b3-48d6-86c2-c967d749a03a.png)

The API of the Android Emulator is 31.


But... It seems, like this problem goes further on my side - because I can't explain to myself, why even writing directly "OpenSans-Bold" oder "OpenSansBold" won't apply.
I checked, if those assets are in the android folder, passed them manually into android/app/src/assets/fonts, because linking doesn't seem to work.
I guess therefore it's more likely, that the reason why it won't work, lays somewhere in my project - but who knows

**Comment by fabriziobertoglio1987** [comment]
My implementation:

```java
if (family != null) {
  typeface = ReactFontManager.getInstance().getTypeface(family, newStyle, weight, assetManager);
}
// some logic
return typeface;
```

The previous implementation:

```java
if (family != null) {
  typeface = ReactFontManager.getInstance().getTypeface(family, want, weight, assetManager);
}
// some logic
return typeface
```

I did not test the scenario using a specific fontStyle and I did not notice it did not work.

https://github.com/facebook/react-native/blob/c447b25c01ce5665a7888ac0f902bdcacb87d6ed/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java#L69-L72

https://github.com/facebook/react-native/blob/c447b25c01ce5665a7888ac0f902bdcacb87d6ed/ReactAndroid/src/main/java/com/facebook/react/views/text/TypefaceStyle.java#L45-L55

I will have to read the changes to my functionality and fix this issue.
