### ISSUE TITLE
Hermes enabled bundle causes white screen when installed from Google Play

### ISSUE THREAD

**Issue by desmondmc** [facebook/react-native#26400]
Compiling a release with Hermes enabled causes a white screen after downloading from Google Play.

Literally everything else works fine, it only breaks after being uploaded to Google Play. 
- Debug builds work. 
- `./gradlew installRelease` works.
- Even extracting the apks from the `.aab` using [bundletool](https://github.com/google/bundletool)  and installing them with adb on a device works.

I know that Hermes is running because `global.HermesInternal != null`, not to mention it's lightning fast 💨.

React Native version: 0.65.0
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 22.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Compile and package release build with Hermes enabled
2. Upload it to Google Play (Alpha or Beta)
3. Once the app is available download and install the version from Google Play
4. Launch the app -> **White Screen**

Describe what you expected to happen:

I expect bundles compiled with Hermes enabled to behave the same after being uploaded to Google Play.

Snack, code example, screenshot, or link to a repository:

- My [build.gradle](https://gist.github.com/desmondmc/1fbd08ef1586b3bcdab68f27753a16b1)
- Device logs from `adb logcat` when launching the Play Store version of the app: [hermes-prod-logs.txt](https://github.com/facebook/react-native/files/3599513/hermes-prod-logs.txt)

**Comment by herio** [comment]
Facing the same problem only when upload the bundleRelease to play store, assembleRelease is OK.
    "react-native": "0.60.5",
    "hermes-engine": "0.1.1",

**Comment by githubdoramon** [comment]
A (terrible) workaround is to first run assembleRelease (so the js bundle is generated), and then run bundleRelease.

I don't think this is related to Hermes though, since even when I disabled it I still have the same problem with bundling the app

**Comment by desmondmc** [comment]
Just tested with `react-native` `0.61.1`. Still broken 😢

**Comment by panvourtsis** [comment]
same issue with @herio any test locally on debug or release is working. Only version returning the white screen is from the bundleRelease to play store

**Comment by LydGol90** [comment]
I am getting the same issue, also only when I upload bundle to play store with Hermes enabled. assembleRelease works fine and all works fine with Hermes disabled. RN version 0.61.1

**Comment by Shchepotin** [comment]
Same issue.

**Comment by longnk-1447** [comment]
.

**Comment by radko93** [comment]
Please upvote the first post, don't post `+1` or `same issue`. You can subscribe to this issue on the left side.

**Comment by courptwayne** [comment]
+1

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2019-10-08 om 09 46 15](https://user-images.githubusercontent.com/6492229/66376717-89631a00-e9b0-11e9-8e9e-bd93ff15a49f.png)

**Comment by Alaa-Ben** [comment]
Hey guys ! For me, it turned out it was a problem of SoLoader, which was fixed in 0.8.0. React Native 0.61.1 doesn't use this version yet, so the solution was to set it up manually by adding the following to app/build.gradle:
`
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
`

**Comment by radko93** [comment]
@Alaa-Ben cool. I will se if I can submit this as a PR.

**Comment by Alaa-Ben** [comment]
@radko93  Bumping SoLoader to 0.8.0 in the gradle properties should do the trick. Shoud I open a PR ?

**Comment by radko93** [comment]
@Alaa-Ben feel free, this should look like this https://github.com/facebook/react-native/commit/07d1075f372bb864ddc62b9c8f613b03becfa568

**Comment by RichardLindhout** [comment]
@Alaa-Ben Have you enabled hermes?

App crashes in the pre-launch rapport of the Google Play.

```
com.facebook.react.common.JavascriptException: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
This error is located at:
    in c
    in RCTView
    in Portal.Host
    in c
    in c
    in n
    in _
    in f
    in p
    in GestureHandlerRootView
    in y
    in v
    in RCTView
    in RCTView
    in h, js engine: hermes, stack:
```

**Comment by Alaa-Ben** [comment]
@RichardLindhout Yes, Hermes is enabled. I had 2 issues (only when downloading from GooglePlay) before forcing Soloader to 0.8.0. Either: 
1. White screen / crashes after splash screen.
2. App works but launches as debug (warning toasts, shaking device would make the debug menu appear, ...) even though it's supposed to be a release build (built with bundleRelease).

**Comment by RichardLindhout** [comment]
I have this know, maybe this can not work.

```
configurations.all {
    resolutionStrategy { force "com.facebook.soloader:soloader:0.8.0" }
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support' && requested.name != 'multidex') {
            details.useVersion "${rootProject.ext.supportLibVersion}"
        }
    }
}
```

**Comment by radko93** [comment]
I can confirm that the solution from @Alaa-Ben worked for me when deploying to Google Play.

**Comment by desmondmc** [comment]
Can also confirm that @Alaa-Ben's solution worked for me. Nice work 👍

**Comment by paolospag** [comment]
Confirm, this change on `app/build.gradle` file works fine with Hermes enabled and Android App Bundle:

```
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
```

**Comment by RichardLindhout** [comment]
For me this did not work, we're using react-native-navigation. It works with .apk though so we switched back to that.

**Comment by radko93** [comment]
> Hey guys !
> 
> For me, it turned out it was a problem of SoLoader, which was fixed in 0.8.0. React Native 0.61.1 doesn't use this version yet, so the solution was to set it up manually by adding the following to `app/build.gradle`:
> 
> ```
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```
> 
> I hope it works for you too :)

Unfortunately, https://github.com/facebook/react-native/pull/26759 breaks 0.61.x branch so an official fix will be included in 0.62 when it's released. This is a preferred workaround probably.

**Comment by gamingumar** [comment]
@Alaa-Ben solution worked for me in 0.61.2 but after upgrading to 0.61.3 I am getting error again in play store aab. (apk works fine)
```
couldn't find DSO to load: libhermes-executor-debug.so
```

**Comment by RichardLindhout** [comment]
I had that error at build time and cleaning my build fixed that error

**Comment by gamingumar** [comment]
@RichardLindhout I am getting this error in play store pre launch report. Installing from play store crashes app on launch. I have also tried ./gradlew clean
Can you tell me the commands that worked for you and if you are using 0.61.3?

**Comment by RichardLindhout** [comment]
I still use the APK build and I'm on 0.61.3.
Here are more people with the same problem: https://github.com/facebook/react-native/issues/26938

**Comment by RichardLindhout** [comment]
Maybe here is something valuable to find: https://github.com/facebook/react-native/issues/25537

**Comment by radko93** [comment]
@gamingumar I use the workaround I posted in this issue with 0.61.3 without any issues. I use CI to deploy the so the environment is always clean.

**Comment by TylerNRobertson** [comment]
@radko93 The provided solution above did not solve the issue for us on RN 0.61.3.

**Comment by RichardLindhout** [comment]
@TylerNRobertson Are you using react-native-navigation?

**Comment by TylerNRobertson** [comment]
@RichardLindhout Yes I am. Does that have another step thats needed? Or currently no workaround for using RNN?

**Comment by roots-ai** [comment]
> ```
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```

where should this code be put?
inside 
`android {
}`

or 

with `apply plugin:`

**Comment by jstheoriginal** [comment]
> > ```
> > configurations.all {
> >      resolutionStrategy {
> >        force "com.facebook.soloader:soloader:0.8.0"
> >      }
> > }
> > ```
> 
> 
> where should this code be put?
> 
> inside
> 
> `android { }`
> 
> 
> or
> 
> 
> with `apply plugin:`

It just goes at the file’s root; not inside anything. I put mine there yesterday to fix this issue and it resolved the crash the next release I did.

**Comment by roots-ai** [comment]
This didn't work for me

```
configurations.all {
    resolutionStrategy {
        force 'org.webkit:android-jsc:r241213'
        force "com.facebook.soloader:soloader:0.8.0"
    }
}
```

**Comment by jstheoriginal** [comment]
> @jstheoriginal This didn't work for me
> 
> ```
> configurations.all {
>     resolutionStrategy {
>         force 'org.webkit:android-jsc:r241213'
>         force "com.facebook.soloader:soloader:0.8.0"
>     }
> }
> ```

Odd. Are you sure you did a full clean before creating the new build?

**Comment by roots-ai** [comment]
@jstheoriginal Cleaning did resolve the issue of the app getting hanged.
But now the app is crashing with these logs (only with playstore)

```
  at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets (CatalystInstanceImpl.java)
  at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets (CatalystInstanceImpl.java)
  at com.facebook.react.bridge.JSBundleLoader$1.loadScript (JSBundleLoader.java)
  at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle (CatalystInstanceImpl.java)
  at com.facebook.react.ReactInstanceManager.createReactContext (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$000 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$100 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$200 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$902 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$1000 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$1102 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$1300 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager.access$1400 (ReactInstanceManager.java)
  at com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java)
  at java.lang.Thread.run (Thread.java:818)

```

**Comment by radko93** [comment]
Why do you set a different jsc version when you use @her

> @jstheoriginal This didn't work for me
> 
> ```
> configurations.all {
>     resolutionStrategy {
>         force 'org.webkit:android-jsc:r241213'
>         force "com.facebook.soloader:soloader:0.8.0"
>     }
> }
> ```
> 
> On RN 0.61.4

why do you set different JSC version when you use Hermes? You can either use JSC or Hermes.

**Comment by roots-ai** [comment]
@radko93 

I had just disabled it for dev.

```
if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
```

**Comment by roots-ai** [comment]
Just for other's reference. 

The previous issue was resolved. It was because of adding `apply ./react.gradle` to buid.gradle.

 Removing it and adding the entire path in the react-native bundle resolved it.

**Comment by TylerNRobertson** [comment]
@roots-ai by removing the react.gradle apply at the top of the file, where do you add the path for the bundle? I can't seem to locate where it needs to be changed.

**Comment by roots-ai** [comment]
Just update the `react.gradle` in `node_modules/react-native/`.

and run `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

Strange but it works.

**Comment by gamingumar** [comment]
I am getting this error in 0.61.4
```
E/SoLoader: couldn't find DSO to load: libjscexecutor.so
```
in android 6 nexus device. working fine in new devices like galaxy s9

**Comment by ScreamZ** [comment]
I almost died because of that… Thanks so much to the guys who gave great answer at this post @grabbou could you please save our life and take this in RN ?🙏🏻

**Comment by palerdot** [comment]
I can confirm @Alaa-Ben solution 
```
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
```
fixed the blank screen issue from google play for me. This is very very scary since the the production build with `react-native run-android --variant=release` works totally fine, but internally it builds an `apk`, while deploying to playstore it is in the form of `aab` which totally blanked out because of this issue. Many thanks again to @Alaa-Ben. Personally issue kind of reinforces how fragile is to use react native as I bump into these kind of weird things time and again.

**Comment by Alaa-Ben** [comment]
The play store offers a 'test store' for internal tests. I recommend using it from time to time, specially when upgrading React Native versions.

**Comment by rendomnet** [comment]
Is this fixed already or should we use `force "com.facebook.soloader:soloader:0.8.0"`?

**Comment by rendomnet** [comment]
@Alaa-Ben how can we test store?

**Comment by Alaa-Ben** [comment]
@rendomnet Go your app's page on the google play console and select 'App releases' on the left menu. There you'll have many tracks (production track, open track, closed track, etc.). What you want is the 'internal test track'. I believe one is created by default, if not add one. Add the aab you want to test to this track, then add your google email to the list of internal testers. Finally, if you log in  on a phone to the play store using the email you added to the list of internal testers, you will be able to access your test version (and the others won't see it of course).

**Comment by amixel** [comment]
> Hey guys !
> 
> For me, it turned out it was a problem of SoLoader, which was fixed in 0.8.0. React Native 0.61.1 doesn't use this version yet, so the solution was to set it up manually by adding the following to `app/build.gradle`:
> 
> ```
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```
> 
> I hope it works for you too :)

Thanks, solve it with me, I was trying to find out these errors, I was able to find out when disabled Hermes.
Then I searched and found this solution

**Comment by panda0603** [comment]
@Alaa-Ben Was trying to solve this issue for past 2 days until I met your comment. Thank you very much!! I have found one problem though. Indeed bundleRelease now works in google playstore when I enable SoLoader(0.8.0), it is debug mode(i.e. just react-native run-android) that doesn't work anymore. App crashes on start. So at the moment, I have to comment out 
```
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
```
on android/app/build.gradle when I use debug mode to develop, and enable that part again for bundleReleases. Am I the only one with this issue??

**Comment by Alaa-Ben** [comment]
@panda0603 I didn't have this issue, do you have a stacktrace ?

**Comment by panda0603** [comment]
@Alaa-Ben react-native log-android doesn't produce anything on crash so I've checked adb logcat. 
Here are some following text:

12-10 00:54:25.469 14396 14440 E SoLoader: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.weather/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)
12-10 00:54:25.470 14396 14440 E SoLoader: couldn't find DSO to load: libhermes.so caused by: APK was built for a different platform
12-10 00:54:25.471 14396 14440 E AndroidRuntime: FATAL EXCEPTION: create_react_context

Something to do with hermes? But works fine on production with Hermes so I think it is something else. Works fine when I comment out SoLoader 0.8.0

**Comment by douglasjunior** [comment]
> Hey guys !
> 
> For me, it turned out it was a problem of SoLoader, which was fixed in 0.8.0. React Native 0.61.1 doesn't use this version yet, so the solution was to set it up manually by adding the following to `app/build.gradle`:
> 
> ```
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```
> 
> I hope it works for you too :)

This worked for me, thanks.

**Comment by mxmzb** [comment]
This issue should be more visible I think. Quite some time of trying and googling until I found it. The provided solution worked for me.

**Comment by Gark** [comment]
```
configurations.all {
     resolutionStrategy {
       force "com.facebook.soloader:soloader:0.8.0"
     }
}
```
And remove `shrinkResources true` if exists for release buildType. This combination helps.

**Comment by ScreamZ** [comment]
@grabbou Can have a look on this? Everybody is commenting the same answer and this is a true bug :p

**Comment by kubilaykiymaci** [comment]
This bug has been fixed, you can see in 0.62 version. 

SO_LOADER_VERSION: 0.8.0

https://github.com/facebook/react-native/blob/0.62-stable/ReactAndroid/gradle.properties

**Comment by Frekansapp** [comment]
i'am facing this issue RN 0.61.5

**Comment by kartikk** [comment]
> Hey guys !
> 
> For me, it turned out it was a problem of SoLoader, which was fixed in 0.8.0. React Native 0.61.1 doesn't use this version yet, so the solution was to set it up manually by adding the following to `app/build.gradle`:
> 
> ```
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```
> 
> I hope it works for you too :)

<br>
  
In addition to the above, I had to add the following snippet to `app/build.gradle` to get the app working
```
packagingOptions {
    exclude '**/libjscexecutor.so'
}
```

**Comment by AlexandrDobrovolskiy** [comment]
> @Alaa-Ben Was trying to solve this issue for past 2 days until I met your comment. Thank you very much!! I have found one problem though. Indeed bundleRelease now works in google playstore when I enable SoLoader(0.8.0), it is debug mode(i.e. just react-native run-android) that doesn't work anymore. App crashes on start. So at the moment, I have to comment out
> 
> ```
> configurations.all {
>      resolutionStrategy {
>        force "com.facebook.soloader:soloader:0.8.0"
>      }
> }
> ```
> 
> on android/app/build.gradle when I use debug mode to develop, and enable that part again for bundleReleases. Am I the only one with this issue??

This solution works with real devices but breaks react-native run-android on emulators, the app's crashing after open with errors like this:
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: APK was built for a different platform
```

**Comment by SuhairZain** [comment]
We've been getting crash reports on our production app. Happens only to a minority of users, and we're unable to reproduce it on any of our test devices. We've released versions with hermes both disabled and enabled and we got the error `libhermes.so could not be found` on all of these. Also tried forcing the SoLoader version at 0.8.0. Same issue. Is anyone else facing the same?

**Comment by benjipott** [comment]
Seems to be only google play test devices that throw this error. No worries

**Comment by SuhairZain** [comment]
@benjipott Is there a way to know if the device is a google play test device?

**Comment by mtiziano** [comment]
still throwing this error

**Comment by wibb36** [comment]
Still the same issue with RN 0.62.1

**Comment by Lipo11** [comment]
I'm on the 0.62.2 version and this bug has been fixed!

**Comment by radko93** [comment]
I can also confirm that is fixed now without any workarounds.

**Comment by elmotan95** [comment]
0.62.2 still have this issue when run on bluestack with release variant.

**Comment by tuanth89** [comment]
@RichardLindhout Which crash report module are you using ? Can you give me name of this crash report ? Thanks

**Comment by RichardLindhout** [comment]
This was done by testing in Google Play store. I use RNN and we switched back to APK to work around this issue. Are you using React Native Navigation too?

**Comment by tuanth89** [comment]
> This was done by testing in Google Play store. I use RNN and we switched back to APK to work around this issue. Are you using React Native Navigation too?
Thank for reply. i use React Navigaiton. I want to know when app crash and trace log from it, like your screenshoot.

**Comment by tad3j** [comment]
Doesn't work for me on 0.62.2 (I've upgraded from 0.61.5 since I thought it will solve the problem, but it didn't). I've tried numerous workaround but still can't get this working. 

Interestingly I'm noticing it only happens on Android 6.0.1 (Galaxy S10) but seems to work on older version of android (Galaxy S7). Beside that, I'm noticing that app only crashes on loading screen for production/release build, staging one seems to work.

Here are the differences between build types:
```
   release {
      minifyEnabled enableProguardInReleaseBuilds
      proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
    }
    releasestaging {
      initWith release
      applicationIdSuffix ".releasestaging"
      matchingFallbacks =  ['release']
    }
```

**Comment by mym0404** [comment]
Now, React Native 0.63 is using SO_LOADER `0.8.2`. Then can we bundle application as aab without any further configurations?

**Comment by radko93** [comment]
@mym0404 yes, it should work directly.

**Comment by mrousavy** [comment]
I'm on 0.63.2 and this issue is still not fixed for me! Cannot run the Android App in Debug or Release with Hermes enabled or disabled on my Emulator!

**Comment by desmondmc** [comment]
Closing this issue as the original bug as described has been fixed.

**Comment by SnowLew** [comment]
> > @Alaa-Ben Was trying to solve this issue for past 2 days until I met your comment. Thank you very much!! I have found one problem though. Indeed bundleRelease now works in google playstore when I enable SoLoader(0.8.0), it is debug mode(i.e. just react-native run-android) that doesn't work anymore. App crashes on start. So at the moment, I have to comment out
> > ```
> > configurations.all {
> >      resolutionStrategy {
> >        force "com.facebook.soloader:soloader:0.8.0"
> >      }
> > }
> > ```
> > 
> > 
> > on android/app/build.gradle when I use debug mode to develop, and enable that part again for bundleReleases. Am I the only one with this issue??
> 
> This solution works with real devices but breaks react-native run-android on emulators, the app's crashing after open with errors like this:
> 
> ```
> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: APK was built for a different platform
> ```
> 
> **Fixed**
> According to `master` branch of react-native [https://github.com/facebook/react-native/blob/master/ReactAndroid/gradle.properties](url) you need to change SoLoader version to **0.8.2**
> 
> ```
>     configurations.all {
>         resolutionStrategy {
>             force "com.facebook.soloader:soloader:0.8.2"
>         }
>     }
> ```

Using this, all work fine in React-Native 0.60.6.

**Comment by Joshmatjjen** [comment]
@SnowLew  App Still Crashes on Startup React native After installed from Play Store 

"react-native": "^0.63.3",

project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,  // clean and rebuild if changing
]

configurations.all {
        resolutionStrategy {
            force "com.facebook.soloader:soloader:0.8.2"
        }
    }

**Comment by lukebrandonfarrell** [comment]
This still occurs with React Native and Hermes, can we re-open the issue?

**Comment by SnowLew** [comment]
> @SnowLew App Still Crashes on Startup React native After installed from Play Store
> 
> "react-native": "^0.63.3",
> 
> ```
> project.ext.react = [
>     entryFile: "index.js",
>     enableHermes: true,  // clean and rebuild if changing
> ]
> 
> configurations.all {
>         resolutionStrategy {
>             force "com.facebook.soloader:soloader:0.8.2"
>         } 
> }
> ```

I've try without hermes and works fine, but with hermes this issue continue.

**Comment by troZee** [comment]
In my case I needed to add hermes path for each android flavour 
```gradle
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
        qaImplementation files(hermesPath + "hermes-release.aar")
        stageImplementation files(hermesPath + "hermes-release.aar")
        prodImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
```

**Comment by ThinkSalat** [comment]
I'm on react-native 0.63.4 and this is still happening for me when I have hermes enabled. Soon as the app opens up, flashes a white screen and closes. It happens when I do `gradlew assembleRelease` and install to an emulator, as well as an `.aab` uploaded to the play store.

**Comment by akrger** [comment]
AAB will be required to use in some months and it seems that JSC is more or less abandonware (it also causes a lot of crashes, which were fixed the moment we switched to Hermes).

Please fix this issue.
