### ISSUE TITLE
react-native init suggests wrong directory path for .xcodeproj file

### ISSUE THREAD

**Issue by ewaltman** [facebook/react-native#2656]
running `react-native init NAME` suggests opening the following file path in Xcode: 
`/path/to/NAME/NAME.xcodeproj`.

It should instead suggest `/path/to/NAME/iOS/NAME.xcodeproj`.

**Comment by MikaelCarpenter** [comment]
It seems as if this has been fixed? 
```
end: function() {
    var projectPath = path.resolve(this.destinationRoot(), 'ios', this.name);
    this.log(chalk.white.bold('Next steps:'));
    this.log(chalk.white('   Open ' + projectPath + '.xcodeproj in Xcode'));
    this.log(chalk.white('   Hit Run button'));
  }
```
the `projectPath` looks like it now contains the ios in the path.
This is from [PR #2298](https://github.com/facebook/react-native/pull/2298)

**Comment by brentvatne** [comment]
Yeah this should be fixed on master :) Thanks @MikaelCarpenter for pointing it out

**Comment by ewaltman** [comment]
Okay I reinstalled, but still don't see it, so maybe I got an old version :/
