### ISSUE TITLE
App freezes when focus TextInput 

### ISSUE THREAD

**Issue by perlo27** [facebook/react-native#26707]
React Native version:
0.61.1

## Steps To Reproduce

1. npx react-native init test-textinput
2. add TextInput component
```
const App = () => {
  const [value, setValue] = useState('init');
  return (
    <View style={{ flex: 1, marginTop: 100 }}>
       <TextInput value={value} onChangeText={text => setValue(text)} />
    </View>
  );
};
```
3. Open app in Iphone8 emulator

Describe what you expected to happen:
it is possible to type text into input field

What actually happens:
Application freezes after focusing TextInput

**Comment by richardfelkl** [comment]
I experience the same issue with RN 0.61.2 as well. It works on Android but every focus to `TextInput` on iOS freezes the app.

**Comment by Looveh** [comment]
I experience the same issue on an iOS13 iPhone 11 Pro simulator using RN 0.59.9

**Comment by Annihil** [comment]
I can confirm also having this with RN 0.61.2 on iOS 13

**Comment by m4rcoperuano** [comment]
Same thing here :(. iPhone 8 simulator.

**Comment by Shooksie** [comment]
It's happening to me In Development, it seems to only impact ios13. I downloaded an ios12.2 simulator and there are no issues but when I try an ios13 simulator the whole app will freeze the moment I focus on any text input.

**Comment by mmmulani** [comment]
could you provide a stack frame of the app by doing:

open Activity Monitor on your Mac, sort by CPU usage. Your app should be at the top (it runs as a process on your Mac even though it's in an iPhone/iPad), hit the Info button and then click Sample in the bottom left. Then paste that stackframe here as a Gist. It should help us narrow down where the issue is coming from.

**Comment by swizes** [comment]
same problem occurs on iPhone X 13.0 simulator. The app is installed and launched via react-native run-ios

**Comment by farad4y** [comment]
Same problem here
```
RN 0.61.2 
iOS 13 
iPhone 11 Simulator
```

**Comment by mmmulani** [comment]
please stop commenting if you have the same problem as it isn't really helpful. Instead provide a stack frame as per my instructions here: https://github.com/facebook/react-native/issues/26707#issuecomment-538753825

**Comment by farad4y** [comment]
Stack Frame @mmmulani
https://gist.github.com/farad4y/b71dd7b0f490453b6d40f08c35bf89e5

**Comment by mmmulani** [comment]
@farad4y thanks a lot for that!

it looks like the main thread is trying to read from the pasteboard and locking up. I expect this is a Simulator only issue that probably happens when the Simulator is trying to sync pasteboards between the Simulator and your Mac.

if you’re seeing this, you might be able to get around it by disabling auto-sync clipboard in the Simulator settings.

**I do not expect this to be an issue on React Native’s side** but rather an Apple bug.

If you’re experiencing this issue, please try following the steps as above and if you see a stack frame that involves UIConcretePasteboard it is likely this issue.

**Comment by farad4y** [comment]
@mmmulani I tried to disabling auto-sync clipboard but not solved, app still freezes.

**Comment by mmmulani** [comment]
> @mmmulani I tried to disabling auto-sync clipboard but not solved, app still freezes.

yeah it's not a guaranteed fix. I would try disabling auto-sync and then manually send and get the pasteboard to the Simulator.

Also try opening the Messages/Contacts app and see if any of the text boxes freeze there. Again, it looks like an UIKit bug which I hope Apple will fix in an upcoming Xcode release.

I've heard anecdotally that it doesn't repro on older versions of the Simulator, so maybe try running against iOS 12, or try testing on device.

**Comment by lcszulpo** [comment]
I did some tests on the simulator, crashes are occurring in Text Inputs in the bare system, in the Search Bar for example,  outside react native apps. I agree with @mmmulani this is probably a UIKit bug.

**Comment by oleksandr-dziuban** [comment]
@lcszulpo Yes, just want to confirm, this is not a react native issue.
I can reproduce this on any text field in iOS 13. This is possibly iOS 13.0 Simulator issue.
Even in Safari search bar I can reproduce it.
Interesting is it fixed in iOS 13.1 Simulator. It still unavailbale

**Comment by mackenziemance** [comment]
Yep, fixed in 13.1. This can be closed.

**Comment by farad4y** [comment]
XCode 11.2 Beta works too

**Comment by oleksandr-dziuban** [comment]
@mackenziemance @farad4y Unfortunately I can still see this issue on on Xcode 11.1 / iOS 13.1 simulator. It is not related to react-native I think.
I can work ~ 1h normally, after that in any app, in browser, in app if I focus on text input - app is freezing. Same for all app installed on simulator.

I think this is the Simulator issue, because it is possible to fix that if just  select Simulator -> Erase all content and reinstall apps

**Comment by mackenziemance** [comment]
@oleksandr-dziuban Good catch, you're right.
Apple issue: https://forums.developer.apple.com/thread/122972

**Comment by rborn** [comment]
The last comment in the apple thread fixed for me: `Simulator: Hardware > "Erase all contents and settings"` + `disable pastebin sync`

**Comment by wesleynfreitas** [comment]
I try put

1 - import 'react-native-gesture-handler' at the top of index.js
2 - YellowBox.ignoreWarnings([
    'RCTRootView cancelTouches'
]);

And don't works. Any news about the solution?

**Comment by rborn** [comment]
@wesleynfreitas disable pastebin and reset the sim (as in my previous comment) and reinstall the app, it should work.

**Comment by oleksandr-dziuban** [comment]
@rborn Yes, but this issue will be reproduced later again, I reset simulator once per hour usually

**Comment by rborn** [comment]
🥺

**Comment by mmmulani** [comment]
closing this issue as it’s not caused by React Native and the later comments aren’t really helpful

**Comment by feiadan** [comment]
![image](https://user-images.githubusercontent.com/6028152/68454553-f8dc5b80-0233-11ea-887e-674b638b0041.png)

It is work for me!

**Comment by partriv** [comment]
> The last comment in the apple thread fixed for me: `Simulator: Hardware > "Erase all contents and settings"` + `disable pastebin sync`

this worked, I only had to disable pastebin sync and the problem was resolved. thank you.

**Comment by irfaan** [comment]
On Simulator, disable `Edit > Automatically Sync Pasteboard`

**Comment by GhayoorUlHaq** [comment]
> The last comment in the apple thread fixed for me: `Simulator: Hardware > "Erase all contents and settings"` + `disable pastebin sync`

This worked for me. Thanks ✌️

**Comment by azhararmar** [comment]
> The last comment in the apple thread fixed for me: `Simulator: Hardware > "Erase all contents and settings"` + `disable pastebin sync`

Erase all contents and settings worked for me.

**Comment by soroushchehresa** [comment]
These steps resolved my problem.

#### Reset simulator: Device > "Erase All Contents and Settings..."

<img width="300" alt="Screen Shot 2020-11-25 at 4 18 33 PM" src="https://user-images.githubusercontent.com/20001233/100230193-a3581700-2f3a-11eb-86d8-def0f565e79e.png">

#### Disable pastebin sync: Edit > "Automatically Sync Pasteboard"

<img width="300" alt="Screen Shot 2020-11-25 at 4 19 31 PM" src="https://user-images.githubusercontent.com/20001233/100230183-9e936300-2f3a-11eb-996e-633602db4aed.png">

**Comment by wobsoriano** [comment]
Erase all contents and settings worked for me in iOS 14.2

**Comment by Ericnsamba** [comment]
> The last comment in the apple thread fixed for me: `Simulator: Hardware > "Erase all contents and settings"` + `disable pastebin sync`

worked for me 👍
