### ISSUE TITLE
console.log commands are not shown their code line locations

### ISSUE THREAD

**Issue by ezranbayantemur** [facebook/react-native#26788]
After 0.61.x releases on the debug mode ```console.log``` commands are not showing their code line locations. They always shown at  ```... Project Directioy ...\projectName\node_modules\react-native\Libraries\Core\setUpDeveloperTools.js:73``` directory. 

For example;
**Before update:**
![1_Ot8O3BcmnRF_JkeerVYWfA](https://user-images.githubusercontent.com/42299721/66490643-29f13100-eaba-11e9-8eb5-3b0180064cc6.jpg)

**After update:**
![t1 (1)](https://user-images.githubusercontent.com/42299721/66490654-2eb5e500-eaba-11e9-830a-2cfac52005e2.jpg)

Is this a bug? If it's not previous version was way more useful for variable, data or etc.. tracking.

**Versions:**
```
    "react": "16.9.0",
    "react-native": "0.61.1"
```
**Environment:**
`[skip envinfo]`

**Comment by TheSavior** [comment]
@motiz88, does this look familiar to any recent changes? Maybe something like framesToPop on console.log?

**Comment by motiz88** [comment]
This is probably due to the way we wrap console methods to add React component stacks. I'm not sure whether Chrome exposes a way to manipulate the call site attribution for logs. cc @bvaughn

**Comment by ezranbayantemur** [comment]
I'm not sure why and how it's happening but it would be more better to work like other version.

**Comment by JulianCurrie** [comment]
I'm getting the same result in my console with the newer versions of RN.

**Comment by acoutts** [comment]
I'm also experiencing this after upgrading to React Native 0.61.2. Worked fine in 0.60.x

**Comment by bvaughn** [comment]
To be clear, **this is 100% expected to happen for v61+ and not for v60 (or earlier)** because v61 embeds the new backend from [`react-devtools-core`](https://www.npmjs.com/package/react-devtools-core) v4.

I also made a judgement call for the override to be **on by default** (so it's opt-out rather than opt-in) because (1) people might not be running the DevTools frontend at all and (2) even if they were, there's an initialization race during which any logged errors would not get the appended callstack.

This decision is somewhat controversial. If folks feel that I made the wrong decision by defaulting on, we can talk about it.

**Comment by acoutts** [comment]
Thanks @bvaughn  - for those of us on v61+ now, what's the recommended toolset to continue debugging to see line numbers? I'm willing to switch tools if it means I can see the line numbers again.

**Comment by bvaughn** [comment]
See [my comment right above](https://github.com/facebook/react-native/issues/26788#issuecomment-540626884) where I copied instructions for disabling it?

**Comment by acoutts** [comment]
When I tried to start react-devtools v4, it said: `DevTools v4 is incompatible with this version of React` so then I tried v3 and it doesn't look like your screenshot there.

Is this documented anywhere for me to read more and understand the issue rather than me continue to ask questions?

**Comment by bvaughn** [comment]
Does not sound like you are running v61 of React Native if you saw that message. The v4 frontend can only connect and work with the v4 backend, and vice versa.

**Comment by acoutts** [comment]
Hm, I followed the upgrade guide and checked every change in every file, it's definitely on that version as I have fast refresh as well. 

```
$ react-native upgrade
info No version passed. Fetching latest...
warn Specified version "0.61.2" is already installed in node_modules and it satisfies "0.61.2" semver range. No need to upgrade
```

**Comment by ezranbayantemur** [comment]
> [You should be able to disable it in the general settings](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#component-stacks).
> 
> > React component authors have often requested a way to log warnings that include the React ["component stack"](https://reactjs.org/docs/error-boundaries.html#component-stack-traces). DevTools now provides an option to automatically append this information to warnings (`console.warn`) and errors (`console.error`).
> > ![Example console warning with component stack added](https://user-images.githubusercontent.com/29597/62228120-eec3da80-b371-11e9-81bb-018c1e577389.png)
> > It can be disabled in the general settings panel:
> > ![Settings panel showing "component stacks" option](https://user-images.githubusercontent.com/29597/62227882-8f65ca80-b371-11e9-8a4e-5d27011ad1aa.png)

I was tracking logs on Google Chrome Debugger, not React Devtools, so there is no way to disable such as you mention it. But anyway, like @acoutts said when I try to devtools I got incompatible errors.

**Comment by IceDev-xyz** [comment]
I also use Chrome Debugger tools, It feels simpler... if this decision can be discussed, count my vote for allowing to see logs like before without having to install React DevTools.

**Comment by ledzep9012** [comment]
Can we default it to see logs as they were before if React Devtools is not installed?

**Comment by bvaughn** [comment]
My takeaway from this is that the current default is probably not working out very well for folks, so I'll change it (off instead of on). Sorry for the inconvenience.

**Comment by acoutts** [comment]
Thanks @bvaughn. I think most of the confusion comes from most people not using react devtools but just using Chrome (the thing that opens by default when you enable debugging).

**Comment by bvaughn** [comment]
Follow up clarification question for my benefit: Why was the "before" behavior of showing `YellowBox.js` (already a React Native `console` override) preferable to the new location of showing the DevTools backend? Neither is the original place the error/warning was logged.

**Comment by ledzep9012** [comment]
> Follow up clarification question for @ezranbayantemur @ledzep9012 etc: Why was the "before" behavior of showing `YellowBox.js` (already a React Native `console` override) preferable to the new location of showing the DevTools backend? Neither is the original place the error/warning was logged.

@bvaughn I was referring to `console.log` statements

**Comment by bvaughn** [comment]
Gotcha. I misunderstood the screenshots.

DevTools overrides `console.log` too so that it can suppress logging when shallow re-rendering a component to inspect hooks values ([learn more here](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks)). This uses the same mechanism as the "component stacks" feature but the purpose is different.

Maybe this override could be deferred until the first time a component was actually inspected (which would never happen, unless you were actually using the frontend UI)

**Comment by bvaughn** [comment]
Gotcha. I misunderstood the screenshots.

DevTools overrides `console.log` too so that it can suppress logging when shallow re-rendering a component to inspect hooks values ([learn more here](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks)). This uses the same mechanism as the "component stacks" feature but the purpose is different.

However, this override is deferred until the first time a component is actually inspected (which would never happen if you weren't using the DevTools UI). It's also unpatched as soon as we're done inspecting. ([See the source code here.](https://github.com/facebook/react/blob/4cb399a433771c84e861d5ca3d38a24733d23ad8/packages/react-devtools-shared/src/backend/renderer.js#L2291-L2313))

So I'm now unsure of how the originally reported issue was being triggered. Are we actually seeing `console.log` being overridden eagerly? Are we potentially talking about `console.trace` instead?

**Comment by gaearon** [comment]
I think there’s a misunderstanding.

Could it be that console.logs are being eaten by the thing that sends them to Metro? So then it wouldn’t be React DevTools-related at all.

In that case ideally the fix would be to somehow detect if we’re in a “rich console” environment like Chrome or not. When we are, don’t send hijack console to send logs to Metro.

A possible way to detect that could be to check whether console methods are native or RN polyfill. Maybe by toString-ing them. Or by checking for some Chrome specific property on console. Need to make sure the fix doesn’t give a false positive for Hermes.

**Comment by bvaughn** [comment]
Yes!

https://github.com/facebook/react-native/blob/b7c14f29cf391ae9b35a2011dca4e631c881dfd7/Libraries/Core/setUpDeveloperTools.js#L62-L81

This makes more sense, given that the console screenshot above shows `setupDeveloperTools.js` rather than `backend.js`

**Comment by cpojer** [comment]
Checking whether console is native or not and skipping the Metro logging setup makes sense to me. Do you wanna send a PR for that?

**Comment by rickhanlonii** [comment]
This is fixed by https://github.com/facebook/react-native/pull/26883

That diff will revert this back to showing "YellowBox.js":

<img width="836" alt="Screen Shot 2019-10-16 at 2 05 08 PM" src="https://user-images.githubusercontent.com/2440089/66922554-2fe99380-f01f-11e9-8805-2145237d1134.png">

This will stay the case until Chrome exposes a way for us to ignore our wrapping frame (see [here](https://github.com/whatwg/console/issues/163)).

Until then, if you want to see the true frame, you can blackbox `YellowBox.js` (or any script) and Chrome will know to skip that frame:

<img width="836" alt="Screen Shot 2019-10-16 at 2 14 32 PM" src="https://user-images.githubusercontent.com/2440089/66922777-a5edfa80-f01f-11e9-9c51-d8f0aee50a0f.png">

_Note: The regexes to use are `/YellowBox\.js$` and `/setUpDeveloperTools\.js$`_

<img width="836" alt="Screen Shot 2019-10-16 at 2 15 07 PM" src="https://user-images.githubusercontent.com/2440089/66922782-a9818180-f01f-11e9-87ef-2340f4bbac11.png">

_Note:  Notice that `App.js` is referenced here instead of `YellowBox.js`_

You can read more about Chrome Blackboxing [here](https://developer.chrome.com/devtools/docs/blackboxing)

**Comment by acoutts** [comment]
> This is fixed by #26883

I just applied this patch and chrome console logs work again for me and it's showing the correct files/ line numbers as before.

![Screenshot_2019-10-16_09-37-26](https://user-images.githubusercontent.com/9597207/66924410-96a78680-eff8-11e9-93bd-fa4a103bd69b.png)

**Comment by Dellybro** [comment]
When will the patch fix be merged into the repo?

**Comment by gaearon** [comment]
It will be merged when it's ready. Likely next week.

**Comment by ezranbayantemur** [comment]
> This is fixed by #26883

Thanks for the support, like @acoutts said this fixed the issue. We waiting for merge.

Closing the issue for fixed, have a great day you all, bugless coding ! 🍺

**Comment by bvaughn** [comment]
Yay!

**Comment by rickhanlonii** [comment]
The fix was merged, we went with a strategy that was a bit better than the original patch tested above so please check it out and let me know if you have any questions https://github.com/facebook/react-native/commit/42ac240bceb104474494c6007df0089baec00f7a

**Comment by IceDev-xyz** [comment]
0.61.3 - Still shows `setUpDeveloperTools.js:73 ` .. I was with the idea that the fix was already merged for this release, did I miss something?

**Comment by tapz** [comment]
0.61.5: 

ReactNativeJS: 'Unhandled promise rejection', [TypeError: Cannot read property 'reset' of undefined]

**App showing:**


console.error: "Unhandled promise rejection', [TypeError: Cannot read property 'reset' of undefined, js engine: hermes
```
apply

_construct
construct.js:30:26

Wrapper
wrapNativeSuper.js:26:23

call

appyl

SyntheticError
index.bundle?platform=andoird&dev=true&minify=false;35761:111

reactConsoleErrorHandler
ExceptionsManager.js:135:52

call

apply

perform$argument_0
....
```

**Comment by tapz** [comment]
index.bundle?platform=andoird&dev=true&minify=false;35761:111 is basically useless line numer.

**Comment by rickhanlonii** [comment]
@tapz that looks like a different issue, it seems like symbolication is only partially applied.

If you can repro, can you create a new issue?
