### ISSUE TITLE
Problem with init a project on Windows

### ISSUE THREAD

**Issue by xgrommx** [facebook/react-native#2681]
Hi all! I have been tried use react-native for Android on Windows but I got error. This is my steps:

npm i react-native -g
react-native init AwesomeProject

```
This will walk you through creating a new React Native project in C:\tmp\AwesomeProject
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by chirag04** [comment]
Right now only OSX is supported as stated here: https://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by guillaume86** [comment]
Using cross-spawn (https://www.npmjs.com/package/cross-spawn) as a replacement for child_process.spawn fixes this particular error.

**Comment by xgrommx** [comment]
It will be in future?

**Comment by mkonicek** [comment]
As @chirag04 said, Windows is not supported yet. There are also a few places in the CLI where we call into `sh` so the error you mention won't be the only one. Windows support would be great but can't promise an ETA yet. Pull request to make the CLI work on Windows are welcome.

The remaining components are the packager and Gradle. Gradle build _should_ work on Windows out of the box. You can try using this example as a template for your app: https://github.com/facebook/react-native/tree/master/Examples/SampleApp

**Comment by ide** [comment]
Another point I'd like to communicate is that most engineers at FB develop on Macs (w remote Linux server) so those platforms are naturally going to receive more dogfooding within the company. Great Windows support will come from an individual or group of individuals who are passionate to making sure RN runs well on Windows. When the packager is moved to its own repo (happening soon I believe) it should be easier to take in PRs that improve Windows support.

**Comment by ngenerio** [comment]
I just looked into the code for the `react-native-cli` and realized it used `node.js`'s default `child_process.spawn`. I changed this to use `shelljs` and it worked. Don't know how to get that back into the `react-native-cli` source on github because after cross-checking, there seems to be some differences in the one on npm and the source code on github.

**Comment by kmagiera** [comment]
Mergint to master task for linux/windows support #2681 let's discuss workarounds there

**Comment by bret-johnson** [comment]
@kmagiera it looks like you linked back to this issue.  Did you mean to link to a pull request instead?

**Comment by mkonicek** [comment]
The issue is #2693.

**Comment by ligboy** [comment]
@chirag04 Ubuntu/linux works well......

**Comment by leon456** [comment]
Wish window can support ASAP,thanks

**Comment by bret-johnson** [comment]
FYI - I've been taking a look at getting Windows support to work.  It looks like this issue, with "react-native init", no longer happens when I pulled the latest CLI source from github.   I'm now trying to get the packer to fully work.   I fixed one problem there and am trying to track down the next one.

**Comment by martinbigio** [comment]
@bret-johnson this might be related to your problem #2789

**Comment by BerndWessels** [comment]
Hi @mkonicek 
I think this issue is back. I get this with the latest master from an hour ago:

    Y:\>react-native init hope
    This will walk you through creating a new React Native project in Y:\hope
    events.js:141
          throw er; // Unhandled 'error' event
          ^

    Error: spawn npm ENOENT
        at exports._errnoException (util.js:837:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT (internal/child_process.js:344:16)
        at doNTCallback2 (node.js:429:9)
        at process._tickCallback (node.js:343:17)
        at Function.Module.runMain (module.js:477:11)
        at startup (node.js:117:18)
        at node.js:951:3

**Comment by BerndWessels** [comment]
@mkonicek Mmh, OK, `react-native init` works if I replace 'react-native-cli` with the latest one from `master` manually.

**Comment by bret-johnson** [comment]
BTW, when I pull from master and build that on Windows (#2961 helps in building), everything seems to work now on Windows, including the packager and watchman-style file change monitoring.   That said, if anyone knows of issues that remain on Windows, with what's in master, why don't you list them here.   I may take a look.

**Comment by davidgilbertson** [comment]
`react-native init MyApp` works for me with the (manually copied) current master.

**Comment by PBartrina** [comment]
`react-native init myApp` still doesn't work for me, even with the manually copied master

**Comment by BBLN** [comment]
@PBartrina please post the log.

**Comment by mikla** [comment]
@BerndWessels after replacing react-native-cli - react-native init command works fine. 
But, how to deal with react-native start? 
it print's me the error: 

```javascript 
d:\work\AwesomeProject>react-native start
module.js:338
    throw err;
    ^

Error: Cannot find module 'd:\work\AwesomeProject\packager.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by davidgilbertson** [comment]
@mikla have you followed these steps? https://gist.github.com/davidgilbertson/9bee68548037fe00f2a8

The current version of `react-native-cli` works fine with Windows but you'll still need to follow carefully the steps in that gist to get it all working

**Comment by yangzkun1223** [comment]
hi  all  I hava get a new problem ,  how to deal with this problem?
`Error:This socket is closed `
![image](https://cloud.githubusercontent.com/assets/17006406/20426728/702d71e0-adbb-11e6-95a8-b6367ad6de47.png)
