### ISSUE TITLE
Animations do not run on Android debug builds including the class 'android.support.test.rule.ActivityTestRule', such as is brought in by detox

### ISSUE THREAD

**Issue by prios-ben-siron** [facebook/react-native#27010]
It is unnecessarily difficult on Android with RN 0.60.0 and higher to control when Animations are turned on/off.

Currently the Animation classes will use emptyAnimations instead of the real ones when Platform.isTesting is true (which comes from https://github.com/facebook/react-native/commit/45686c86e2b50c98436d511dd63f0e987f565008#diff-35653b5f6360716ec796e5ffdd483841), and Platform.isTesting is set to true when the class 'android.support.test.rule.ActivityTestRule' is found, per https://github.com/facebook/react-native/commit/f2d20d29046802f5d9c94a8749bdc4590da75190#diff-cfd916ca2051bbed5b47c289c9338543, which began to be included in RN as of 0.60.0.

Platform.isTesting is false always in release builds, but is true in debug builds according to the following condition from ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoModule.java:

   System.getProperty('IS_TESTING') = 'true'
      OR
   Class.forName("android.support.test.rule.ActivityTestRule") does not throw.    

Unfortunately, the 2nd condition is often triggered accidentally, such as when the android build includes a reference to detox.  Our workaround at present is to make one kind of build for debug with detox and debug without detox included.  We would really like something less difficult to work with.

React Native version:

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 249.87 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.10.2 
    react-native: ^0.61.0 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1.  Create a RN project referencing detox in the build.gradle file, such as with: 
    // DETOX
    implementation('com.wix:detox:+') { transitive = true } 
    testImplementation 'junit:junit:4.12'

2. Have the app show a component using Animated classes from the react-native package.

3. Make a debug build of the app for android and run it.

4. The components will be displayed with their initially properties only, but animations will not run at all.  It does not matter whether or not you use useNativeDriver: true, or any other settings because MockAnimations will be used instead of the actual animation classes, where everything has been implemented with a no-op.

### Describe what you expected to happen:

Any of the following things would be an improvement:

- allow a separate System property or environment variable to set Platform.isTesting on or off (when that new switch is provided) that overrides the existing condition
- allow a separate System property or environment variable to only turn animations on or off independently of the Platform.isTesting bit
- provide a way in JS to turn animations on or off
- emptyAnimations could be a little more friendly so that they work partially, such as instantly transitioning to the destination values instead of doing nothing (as was mentioned by @PeteTheHeat / @cpojer in https://github.com/facebook/react-native/commit/45686c86e2b50c98436d511dd63f0e987f565008#diff-35653b5f6360716ec796e5ffdd483841)

**Comment by d4vidi** [comment]
@prios-ben-siron thanks for this submission in favor of Detox! Please also follow related notes in https://github.com/wix/Detox/issues/1585. I'll try my best to contact RN devs and ask them to give this a high priority.

**Comment by rewieer** [comment]
We are having this trouble right now in `react-native-modal` since we rely on Animations to animate the modal.

**Comment by d4vidi** [comment]
Hi, any intentions of getting this fixed? I've performed some thorough testing of ways to work around this, and unfortunately there seem to be no clean ones -- the only one I've found is to search-and-replace equivalent code on the JS side, which is pretty ugly. I'm quite certain there's a better way to determine `isTesting` than to check for the `android.support.test.rule.ActivityTestRule` class, or alternatively - allow for an external override somehow. Please give this some priority as both Detox devs and the entire Detox users community are affected by this issue.

**Comment by TheSavior** [comment]
I think @PeteTheHeat and @JoshuaGross are the most familiar with the code in question. Thanks for flagging this

**Comment by d4vidi** [comment]
In the meantime, the solution worked out by @yedidyak in order to work around this (in debug mode) was to run this in either a post-install or before tests initiation:

```
sed -i bak 's/Platform.isTesting/false/g' node_modules/react-native/Libraries/Animated/src/Animated.js
```

**Comment by PeteTheHeat** [comment]
Hey @prios-ben-siron, sorry for missing this issue the past couple months. 

I think https://github.com/facebook/react-native/commit/1fbc6a7c178d13421b0b84d6ea01f9174105325f should fix it. Let me know if it doesn't.

**Comment by PeteTheHeat** [comment]
I'm assuming this is fixed. I'll close out, feel free to re-open if it isn't.

**Comment by barak109** [comment]
Hey guys,
I use detox(last version) and RN( "0.61.5") and I still have the problem, do I need to add something?
It works for me if I run @d4vidi  answer.
but I want to work with the fix that you mention @PeteTheHeat.

**Comment by d4vidi** [comment]
@barak109 iirc this was released in rn 62

**Comment by BatDroid** [comment]
I'm wondering why no one mentions where this command should be run:
`sed -i bak 's/Platform.isTesting/false/g' node_modules/react-native/Libraries/Animated/src/Animated.js`
Before `detox build` ? in package.json or what? :)
