### ISSUE TITLE
Cannot connect to the server with the iOS simulator

### ISSUE THREAD

**Issue by zendevil** [facebook/react-native#27765]
I have a server running at localhost:5000, and I'm using then http-proxy-middleware to connect my development client like so:

```
const proxy = require('http-proxy-middleware');
module.exports = function(app) {
    app.use(proxy('/auth/google', 
        { target: 'http://localhost:5000/' }
		 ));
    app.use(proxy('/api/*', 
        { target: 'http://localhost:5000/' }
    ));
}
```

But the proxy isn't working. I get the following:
```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``: 

None of these files exist:
  * debugger-ui/debuggerWorker.d9da4ed7(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
  * debugger-ui/debuggerWorker.d9da4ed7/index(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (/Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/lib/transformHelpers.js:267:42
    at /Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/Server.js:1305:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/prikshetsharma/Documents/vendo/client/native/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[Unhandled promise rejection: Error: Network Error]
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:154704:26 in createError
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:154606:27 in handleError
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:32436:31 in dispatchEvent
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:31520:33 in setReadyState
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:31347:29 in __didCompleteResponse
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:7023:42 in emit
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2774:49 in __callFunction
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2487:31 in <unknown>
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2728:15 in __guard
* http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2486:21 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
* http://localhost:19003/debugger-ui/debuggerWorker.d9da4ed7.js:4:907 in <unknown>
```

Why might this be?

**Comment by ebaynaud** [comment]
Got stuck with this exact issue for hours. Just found that this occurs only on device where app is already installed with debug mode enabled.

I fixed it by:
- uninstalling manually app from device (cmd+H to display simulator home) then long click on app icon and click on cross to delete app
=> this forces disabling debug mode
- then run app again from xcode

Enabling debug mode after that works normally.

**Comment by garrettm** [comment]
I have this issue right now on Android, reinstalling the app doesn't seem to fix it.  RN 0.61.5

**Comment by bobber205** [comment]
> I have this issue right now on Android, reinstalling the app doesn't seem to fix it. RN 0.61.5

Having the same issue but on iOS.

**Comment by israNascimento** [comment]
Same here, any update? I didn't saw this before update to RN 0.61.5. In my case, the app shows a red box with "fetch is not a function", but on terminal the error is "Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``: "

**Comment by VitaliyGaliy** [comment]
+

**Comment by spzm** [comment]
I had the same issue and tried several ways to fix: [first](https://stackoverflow.com/questions/59300743/react-native-debug-mode-throws-an-error-why-is-that-so) , [second](https://stackoverflow.com/questions/59658998/expo-unable-to-resolve-module-debugger). Unfortunately, it didn't help. But after rebooting my machine - debug start working fine.

**Comment by trydalch** [comment]
I just had this issue. All I had to do was kill the app on the simulator. Double click the home button, click drag the app up to kill it. 

Returned to the terminal where the bundler was still running, pressed `i` and it loaded just fine. Left the remote debugger going and it connected on its own.
