### ISSUE TITLE
[android] windows npm start  ERROR  Watcher took too long to load

### ISSUE THREAD

**Issue by bluedreamfly** [facebook/react-native#2841]
C:\Users\zh\Desktop\studyPlan\reactNative\reactDemo\node_modules\react-native\packager>node packager.js
     ┌────────────────────────────────────────────────────────────────────────────┐
     │  Running packager on port 8081.                                            │
     │                                                                            │
     │  Keep this packager running while developing on any JS projects. Feel      │
     │  free to close this tab and run your own packager instance if you          │
     │  prefer.                                                                   │
     │                                                                            │
     │  https://github.com/facebook/react-native                                  │
     │                                                                            │
     └────────────────────────────────────────────────────────────────────────────┘
    Looking for JS files in
       C:\Users\zh\Desktop\studyPlan\reactNative\reactDemo

    React packager ready.

    [22:33:52] <START> Building Dependency Graph
    [22:33:52] <START> Crawling File System
    [22:34:09] <START> request:/index.android.bundle?platform=android
    [22:34:09] <START> find dependencies
     ERROR  Watcher took too long to load
    Try running `watchman version` from your terminal
    https://facebook.github.io/watchman/docs/troubleshooting.html
    Error: Watcher took too long to load
    Try running `watchman version` from your terminal
    https://facebook.github.io/watchman/docs/troubleshooting.html
        at [object Object]._onTimeout (C:/Users/zh/Desktop/studyPlan/reactNative/reactDemo/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:102:16)
        at Timer.listOnTimeout (timers.js:89:15)

    See http://facebook.github.io/react-native/docs/troubleshooting.html
    for common problems and solutions.

**Comment by tdzl2003** [comment]
https://github.com/facebook/react-native/commit/f5409c1a51f32535eacfe41fa60ab4f46fec5c5e

I thinks this issue is already fixed by this commit.

**Comment by mryonax** [comment]
This is another issue, caused by [these lines](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/FileWatcher/index.js#L100-L114). For some reason NodeWatcher under windows doesn't trigger the 'ready' event.

**Comment by Bluedreamfly** [comment]
@tdzl2003 I have changed the code, but there are still wrong

**Comment by Bluedreamfly** [comment]
@mryonax I know, but how to solve this problem

**Comment by mryonax** [comment]
@Bluedreamfly For example:
* pass --nonPersistent option to packager.js -  this will completely disable the file watcher
* replace [these](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/FileWatcher/index.js#L100-L114) lines with simple 
```javascript
return Promise.resolve(watcher);
```
With later variant, file watching and reloading works perfectly under windows. And don't forget to take a look [here](https://gist.github.com/mqli/e1e6576e9838d885a43a)  for finding a way to fix various other issues.

**Comment by kmagiera** [comment]
#2693

**Comment by Bluedreamfly** [comment]
@mryonax @kmagiera  thanks,The problem is resolved.

**Comment by bret-johnson** [comment]
What do we think the current state is of the watcher on Windows?   For me (running with the latest code, from master, using SampleApp) watcher updates seem to work fine on Windows even without the "return Promise.resolve(watcher);" change that @mryonax suggests above.   However, if we think it's better to include that change, when on Windows, I can submit a pull request.

**Comment by tonychenl** [comment]
change : node_modules\react-native\packager\react-packager\src\FileWatcher\index.js  line 17 MAX_WAIT_TIME to 50000 or higher

**Comment by jettandres** [comment]
can confirm with @tonychenl 's solution. thanks!

**Comment by dentrite** [comment]
@tonychenl 's solution works for me, MAX_WAIT_TIME at 120000

**Comment by jsierles** [comment]
@facebook-github-bot answered
