### ISSUE TITLE
ReferenceError: Can't find variable: BigInt

### ISSUE THREAD

**Issue by ryuheimat** [facebook/react-native#28492]
I am trying to use the library which I used at web frontend development.
But when I am trying to use that library, it says 
`ReferenceError: Can't find variable: BigInt`

`BigInt `is a javascript built-in library, and I am not sure why React Native does not support, or React native does not support all new features of ES2020?

Binaries:
    Node: 12.15.0
    Yarn: 1.22.0
    npm: 6.13.4
    Watchman: 4.9.0
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0
    react-native: 0.61.5

![Screen Shot 2020-04-02 at 11 45 20 AM](https://user-images.githubusercontent.com/40835770/78229137-8c2b6b80-750a-11ea-9e39-df805d8bba4a.png)

**Comment by shpetimselaci** [comment]
Same issue here.
Do you think it has to do with the bundler?
Did you resolve it?

**Comment by ryuheimat** [comment]
BigInt is one of the new feature of the ECMAScript 2020, and I think react native does not support latest ECMAScript.

**Comment by xiaods** [comment]
Same issue here.
don't know what reason for that.

**Comment by hsavit1** [comment]
NOOO VERY BAD @Stalebot

**Comment by vitolipari** [comment]
I have the same issue

**Comment by natalyayyad** [comment]
Same Issue here!

**Comment by vitolipari** [comment]
Try to add the `@babel/plugin-syntax-bigint` plugin in your babel configuration file.

My `babel.config.js` file before
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset']
};
```

My `babel.config.js` file now
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ["@babel/plugin-syntax-bigint"]
};
```

I fixed it in this way

**Comment by monaye** [comment]
@vitolipari  thank you for posting the possible solution. I tried adding the suggested plugin but still getting the same error. Would you mind sharing the `npm list` ?

**Comment by vitolipari** [comment]
> @vitolipari thank you for posting the possible solution. I tried adding the suggested plugin but still getting the same error. Would you mind sharing the `npm list` ?

this is a part of my `package.json` file

```
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "react-native-device-info": "7.2.1",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.13.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
}```

**Comment by gre** [comment]
This should be addressed. It makes some library (like ripple-lib) to behave inconsistently depending on iOS / android.

**Comment by gre** [comment]
@stalebot @cpojer please consider reopening this one.

**Comment by daveGregorian** [comment]
I also have the same issue. Adding the `@babel/plugin-syntax-bigint` did not help.

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 81.20 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.14.6 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.63.1
```

**Comment by vikil143** [comment]
I m having same issue is there any solution

**Comment by kjawadDeveloper** [comment]
Need a solution for this. I am also facing it.

**Comment by jessgusclark** [comment]
If you are still having this problem, here is how I solved it.

You are importing a package somewhere that requires BigInt as a dependency. For the most part [RN uses JavaScriptCore](https://reactnative.dev/docs/javascript-environment#:~:text=In%20most%20cases%2C%20React%20Native,executable%20memory%20in%20iOS%20apps) which may not have the support of BigInt.

Okay, so one of your dependencies requires Bigint and it needs to be shim'ed. Your project probably relates to crypto and you are probably using [rn-nodeify](https://github.com/tradle/rn-nodeify) to shim the packages that you need. You have a `shim.js` file at the root of your project. 

### 1. Add big-integer to your list of dependencies:

```
yarn add @rsksmart/rns-resolver.js
```

### 2. Add a reference in shim.js

In your `shim.js` file, check if BigInt is undefined and if so assign it to the package you just installed:

```
if (typeof BigInt === 'undefined') global.BigInt = require('big-integer')
```

[See this commit for the implementation](https://github.com/rsksmart/rwallet/commit/1a642efc91ef4301157278c5bb49dfd535b0fb92).

**Comment by ghaschel** [comment]
@jessgusclark Thanks, that worked!

**Comment by Jarrio** [comment]
> If you are still having this problem, here is how I solved it.
> 
> You are importing a package somewhere that requires BigInt as a dependency. For the most part [RN uses JavaScriptCore](https://reactnative.dev/docs/javascript-environment#:~:text=In%20most%20cases%2C%20React%20Native,executable%20memory%20in%20iOS%20apps) which may not have the support of BigInt.
> 
> Okay, so one of your dependencies requires Bigint and it needs to be shim'ed. Your project probably relates to crypto and you are probably using [rn-nodeify](https://github.com/tradle/rn-nodeify) to shim the packages that you need. You have a `shim.js` file at the root of your project.
> 
> ### 1. Add big-integer to your list of dependencies:
> ```
> yarn add @rsksmart/rns-resolver.js
> ```
> 
> ### 2. Add a reference in shim.js
> In your `shim.js` file, check if BigInt is undefined and if so assign it to the package you just installed:
> 
> ```
> if (typeof BigInt === 'undefined') global.BigInt = require('big-integer')
> ```
> 
> [See this commit for the implementation](https://github.com/rsksmart/rwallet/commit/1a642efc91ef4301157278c5bb49dfd535b0fb92).

your solution got me past the big int issue, but it introduced another issue 
![image](https://user-images.githubusercontent.com/748557/129223798-72fcfbf6-c02e-4983-8921-ea349aa9770c.png)
Do you (or anyone else) happen to know how to deal with this?

**Comment by jessgusclark** [comment]
Hey @Jarrio, glad that moved you slightly forward. This error does not look to be related to the issue here, rather perhaps, data that is in an incorrect format from the API, or being converted incorrectly in your project (or dependency). I'd take a look at the stack, where this is happening. I wonder if the `e+3` can't be parsed with the `parseStringValue` method?

**Comment by hildjj** [comment]
What version of JSC is react-native currently using?  It looks like JSC *does* support BigInt now, at least the one on my box does.  (MacOS 10.6, Safari 15.0)
