### ISSUE TITLE
xcode 11.4 build fatal error: module map file xxx/Build/Products/Debug-iphoneos/YogaKit/YogaKit.modulemap' not found

### ISSUE THREAD

**Issue by rs-frank** [facebook/react-native#28503]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
fatal error: module map file '/Users/miaohao/Library/Developer/Xcode/DerivedData/apex_baojia2-cdczyhhwbgshmtbdymitajpzamao/Build/Products/Debug-iphoneos/YogaKit/YogaKit.modulemap' not found

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 219.52 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3
      System Images: android-23 | Android TV Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.react-native init XXX
2.cd ios && pod install
3. xcode Product/build

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
![image](https://user-images.githubusercontent.com/27323629/78332197-1c74b980-75ba-11ea-90ea-09dfe4dffe31.png)
![image](https://user-images.githubusercontent.com/27323629/78332211-2696b800-75ba-11ea-83e7-186e7294c636.png)

**Comment by apostopher** [comment]
I'm facing the same issue. but only in the release mode. the debug build works fine.
```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.05 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
```

**Comment by hramos** [comment]
@apostopher this matches what I observed in Circle CI when I verified our iOS tests on Xcode 11.4.0 - no issues at all on debug mode.

**Comment by LeviWilliams** [comment]
Facing sporatically in debug as well

**Comment by neibesh** [comment]
I seemed to have had the same issue when I was attempting to run react-native run-ios, In my case I found that there was a error that was being produced in the cli around schemas not being found... After following this [stack overflow post](https://stackoverflow.com/questions/33521526/the-project-named-foo-does-not-contain-a-scheme-named-bar-bitrise-io) I managed to get it working...

**Comment by apostopher** [comment]
I managed to resolve the issue in my app. 
I had a mismatch between the ios version in Xcode and Podfile.
![image](https://user-images.githubusercontent.com/270924/78455180-54b9ec00-76cf-11ea-8626-a37bcafdea82.png)

![image](https://user-images.githubusercontent.com/270924/78455203-73b87e00-76cf-11ea-9c66-37f1c52eef81.png)

I changed my Podfile to `platform :ios, '9.0'` and ran `pod install` again.
That did the trick.

**Comment by wildlifechorus** [comment]
I have this issue too. And it's not a mismatch between versions.

**Comment by arjndr** [comment]
I had this issue too, I'm not very familiar with XCode, but I opened the `.xcodeworkspace` file and then clicked build, which was successful!

**Comment by wangxum168** [comment]
Same issue. 
React Native -> 0.62
Xcode -> 11.4

**Comment by rs-frank** [comment]
use .xcodeworkspace is ok

**Comment by stephanos7** [comment]
> use .xcodeworkspace is ok

not sure why the many thumbs up? is this working for people? The above problem happens also when running .xcodeworkspace in xcode.

**Comment by dariodilorenzo** [comment]
I am also facing the issue. Any luck ?

**Comment by weshines** [comment]
I am also facing the same issue. Not sure what to do from here.

**Comment by NiklasMencke** [comment]
also the same issue and stuck here :(

**Comment by weshines** [comment]
If I run my project from project workspace then this error deosn't show up. And whenever you are using pods. You should always run your project from workspace

**Comment by eoinnorris** [comment]
People who are saying this is caused by not using the workspace aren't really being helpful. Thats not the cause of this specific bug, most people who use Pods would know to use the workspace, not the project.

**Comment by collamo** [comment]
XCode: 11.4
React Native: 0.62.2
---
For me, changing the Build System from "Legacy Build System" to "New Build System" fixed this problem.

**Comment by schultka** [comment]
I'm not 100% sure if the first line did the trick, or if it was just a terminal restart, but this worked for me:

`sudo xcode-select --switch /Applications/Xcode.app`

restart terminal **(important)**

`cd ios && pod install`

**Comment by wangxum168** [comment]
> Same issue.
> React Native -> 0.62
> Xcode -> 11.4
> After you create the app. it shows that:
> ![image](https://user-images.githubusercontent.com/17580566/78507773-ef99e100-7736-11ea-867b-28b2917d5236.png)
> It asks you to use **.xcodeworkspace** file to run, but I just want to know why I have this error in the **.xcodeproj** flie.

my solution is to add the library MANUALLY: 
![image](https://user-images.githubusercontent.com/17580566/79098564-21064400-7d17-11ea-9caf-0630ac05a011.png)

**Comment by giacomoalonzi** [comment]
I've incurred in the same error, it doesn't work also with blank RN project.

**Comment by bunsha** [comment]
Same issue. started from nowhere. Done nothing, except internal js logic change.

**Comment by giacomoalonzi** [comment]
> Same issue. started from nowhere. Done nothing, except internal js logic change.

If I can help you, I solved with a reboot. I mean, I did just a reboot of osx, opened the .xcworkspace file and it worked.

**Comment by bunsha** [comment]
> > Same issue. started from nowhere. Done nothing, except internal js logic change.
> 
> If I can help you, I solved with a reboot. I mean, I did just a reboot of osx, opened the .xcworkspace file and it worked.

thank you. I solved it by turning off this stupid icloud backup. First of all - its rly slows down everything, and second - its just start copying some files from my project, and i belive simply corrupt one of the files during the process.

**Comment by Shaharsha** [comment]
+1 :(

**Comment by Shaharsha** [comment]
In my case the problem was in the provisioning profile. I fixed it by checking "Automatically manage signing" in Xcode -> Signing & Capabilities, and Choosing a Team.

**Comment by temitopealabi** [comment]
still having issues to build my project through xcode 11..on screen error is YogaKit.modulemap not found...any assistance will be highly appreciated..
I have tried different suggested solution out here but none work for me

**Comment by Image0108** [comment]
> still having issues to build my project through xcode 11..on screen error is YogaKit.modulemap not found...any assistance will be highly appreciated..
> I have tried different suggested solution out here but none work for me

so do I

**Comment by temitopealabi** [comment]
> still having issues to build my project through xcode 11..on screen error is YogaKit.modulemap not found...any assistance will be highly appreciated..
> I have tried different suggested solution out here but none work for me


Finally,  I found a fix
finally i resolved the problem you have to give xcode full disk access all toy have to do
1- open system preference
2- open security & privacy
3- click on full disk access
4- click on the light yellow padlock  in order to add xcode to the list
5-click on + button to add new app and choose xcode
6- dropdown will open then click on Applications 
7- Double click on Xcode
8-click on yellow padlock to lock the folders back 
9- close xcode
10 -go to your project
run below code
Go to your project ios folder
then click on .xcworkspace extension file to open your project with xcode
click on Project tab then click click on clean project
Now click on build project or the play button

**Comment by alexma01** [comment]
I had the same problem after updating to the latest version of xcode. The problem solved itself by restarting the mac.

**Comment by jchaves07** [comment]
> > still having issues to build my project through xcode 11..on screen error is YogaKit.modulemap not found...any assistance will be highly appreciated..
> > I have tried different suggested solution out here but none work for me
> 
> Finally, I found a fix
> finally i resolved the problem you have to give xcode full disk access all toy have to do
> 1- open system preference
> 2- open security & privacy
> 3- click on full disk access
> 4- click on the light yellow padlock in order to add xcode to the list
> 5-click on + button to add new app and choose xcode
> 6- dropdown will open then click on Applications
> 7- Double click on Xcode
> 8-click on yellow padlock to lock the folders back
> 9- close xcode
> 10 -go to your project
> run below code
> Go to your project ios folder
> then click on .xcworkspace extension file to open your project with xcode
> click on Project tab then click click on clean project
> Now click on build project or the play button

Awesome, Working for me, you are great!!!!!

**Comment by AlexaJosse** [comment]
I face the same issue, none of the solutions above worked for me.

**Comment by Valonfeka** [comment]
Hi there,

The only way for me to fix this was to switch Target from 9.0 to 11.00
Hopefully, I help someone.
![Screen Shot 2020-05-06 at 7 26 51 PM](https://user-images.githubusercontent.com/10377080/81208888-09497500-8fd0-11ea-950b-555ee8bdf17b.png)

**Comment by Fortidude** [comment]
> `sudo xcode-select --switch /Applications/Xcode.app`

Yesterday I run some clean up on my computer. Xcode cache was wiped out, as well as some simulators data etc.

Not quite sure - but today I had similar issue, telling me `YogaKit.modulemap` is not found in DeriveredData. 
It was working from xcode, but not from terminal (I'm using fastlane). 

The above "solution" did the job but I'm thinking it's more a workaround than actually fix.

**Comment by romulotorres** [comment]
> > Same issue.
> > React Native -> 0.62
> > Xcode -> 11.4
> > After you create the app. it shows that:
> > ![image](https://user-images.githubusercontent.com/17580566/78507773-ef99e100-7736-11ea-867b-28b2917d5236.png)
> > It asks you to use **.xcodeworkspace** file to run, but I just want to know why I have this error in the **.xcodeproj** flie.
> 
> my solution is to add the library MANUALLY:
> ![image](https://user-images.githubusercontent.com/17580566/79098564-21064400-7d17-11ea-9caf-0630ac05a011.png)
> Then, it just works!

Man, I dont found that lib. U have a link?

**Comment by sureshmss2007** [comment]
I followed the step from below link.

http://helpinterview.com/?q=content/fatal-error-module-map-file-not-found-xcode

**Comment by jasperkuperus** [comment]
> > Same issue. started from nowhere. Done nothing, except internal js logic change.
> 
> If I can help you, I solved with a reboot. I mean, I did just a reboot of osx, opened the .xcworkspace file and it worked.

My specific issue was that running `react-native run-ios` failed. But in Xcode (of course, opening the `.xcworkspace`) worked like a charm. Surprisingly... After trying everything in here, the reboot worked for me 😨

**Comment by Tucker2015** [comment]
I just had this error but changed the Target IOS to match the Podfile in Xcode .

**Comment by mweststrate** [comment]
For me the solution of @Valonfeka (https://github.com/facebook/react-native/issues/28503#issuecomment-624785816) + the earlier suggestion to open the workspace instead of the project fixed it as well.

**Comment by thanh-taro** [comment]
For me, it's duplication of FileRef in file `contents.xcworkspacedata`.

```
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "group:whateverA.xcodeproj">
   </FileRef>
   <FileRef
      location = "group:Pods/Pods.xcodeproj">
   </FileRef>
   <FileRef
      location = "group:whatevera.xcodeproj">
   </FileRef>
</Workspace>
```

Just remove the last one and then it's OK.

**Comment by phatlaunchdeck** [comment]
> Hi there,
> 
> The only way for me to fix this was to switch Target from 9.0 to 11.00
> Hopefully, it helps someone.
> ![Screen Shot 2020-05-06 at 7 26 51 PM](https://user-images.githubusercontent.com/10377080/81208888-09497500-8fd0-11ea-950b-555ee8bdf17b.png)

Man you totally saved my life. I found out that in Podfile I set the target to 11.0 but in XCode setting it was still 9.0, setting them both to the same version did the trick, thank you so much!

**Comment by eucrod** [comment]
> I had this issue too, I'm not very familiar with XCode, but I opened the `.xcodeworkspace` file and then clicked build, which was successful!

This worked for me!!!

**Comment by supritshah1289** [comment]
> For me, it's duplication of FileRef in file `contents.xcworkspacedata`.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Workspace
>    version = "1.0">
>    <FileRef
>       location = "group:whateverA.xcodeproj">
>    </FileRef>
>    <FileRef
>       location = "group:Pods/Pods.xcodeproj">
>    </FileRef>
>    <FileRef
>       location = "group:whatevera.xcodeproj">
>    </FileRef>
> </Workspace>
> ```
> 
> Just remove the last one and then it's OK.

Location of this file? I couldn't find it in IOS folder

**Comment by jamal-rahimzadegan** [comment]
> > still having issues to build my project through xcode 11..on screen error is YogaKit.modulemap not found...any assistance will be highly appreciated..
> > I have tried different suggested solution out here but none work for me
> 
> Finally, I found a fix
> finally i resolved the problem you have to give xcode full disk access all toy have to do
> 1- open system preference
> 2- open security & privacy
> 3- click on full disk access
> 4- click on the light yellow padlock in order to add xcode to the list
> 5-click on + button to add new app and choose xcode
> 6- dropdown will open then click on Applications
> 7- Double click on Xcode
> 8-click on yellow padlock to lock the folders back
> 9- close xcode
> 10 -go to your project
> run below code
> Go to your project ios folder
> then click on .xcworkspace extension file to open your project with xcode
> click on Project tab then click click on clean project
> Now click on build project or the play button

It's worked for me

**Comment by karan-rawal** [comment]
None of the above worked for me.
I had added some new configurations and deleted the default 'Debug' configuration from xcode.

So I had to change the following line in Podfile
:configuration => 'Debug'

to
:configurations => ['DevDebug',  'QADebug', 'StageDebug', 'ProdDebug']

**Comment by NaNtrack** [comment]
> XCode:11.4
> React Native:0.62.2
> For me, changing the Build System from "Legacy Build System" to "New Build System" fixed this problem.

also add the **YogaKit** target before your app target in your **project scheme**

**Comment by namanicebed** [comment]
Change the Schema Settings and Product>Scheme>Edit Scheme> Find Implicit Dependencied should be checked.
This worked for me...

**Comment by surendrasourcesoft** [comment]
> I managed to resolve the issue in my app.
> I had a mismatch between the ios version in Xcode and Podfile.
> 
> ## Podfile
> ![image](https://user-images.githubusercontent.com/270924/78455180-54b9ec00-76cf-11ea-8626-a37bcafdea82.png)
> 
> ## Xcode
> ![image](https://user-images.githubusercontent.com/270924/78455203-73b87e00-76cf-11ea-9c66-37f1c52eef81.png)
> 
> I changed my Podfile to `platform :ios, '9.0'` and ran `pod install` again.
> That did the trick.

but my app there is requirement of  Plateform 11.0 . How i fix this issue?

**Comment by mweststrate** [comment]
Change both to 11? Do make sure you open the workspace file and not the
project file.

**Comment by MrLoh** [comment]
The cause for me was that the new scheme I had created was not setup in my Podfile, I needed to add a line:
```
project 'MyProject', 
  'debug' => :debug,
  'myNewScheme' => :release 
```

**Comment by GwFreak01** [comment]
I gotta bump up this issue because it seems like many other people having the same issue including me.

[YogaKit Missing](https://www.gitmemory.com/issue/facebook/react-native/28503/614092615)
#29605
[YogaKi Stackoverflow 1](https://stackoverflow.com/questions/63342540/yogakit-yogakit-modulemap-not-found-react-native)
[YogaKi Stackoverflow 2](https://stackoverflow.com/questions/63261150/yogakit-modulemap-not-found-after-running-the-ios-simulator)

**Comment by JH108** [comment]
I was getting this error when using `xcodebuild` to automate the build process. I found out my failing build command:

```
xcodebuild clean archive 
  -scheme releaseScheme 
  -configuration Release 
  -archivePath ../builds/<AppName>.xcarchive 
  -allowProvisioningUpdates
  DEVELOPMENT_TEAM=<TeamId> 
``` 

was missing `-workspace <AppName>.xcworkspace` to specify that I was trying to build the workspace and not the project. The complete command that was working for me is below.

```
xcodebuild clean archive 
  -scheme releaseScheme 
  -configuration Release 
  -archivePath ../builds/<AppName>.xcarchive 
  -allowProvisioningUpdates
  -workspace <AppName>.xcworkspace
  DEVELOPMENT_TEAM=<TeamId> 
```

**Comment by matheushf** [comment]
Tried everything, what worked was to delete the whole `DerivedData` folder, when running `react-native run-ios` again it just worked. Located in: `/Users/YOUR-USER/Library/Developer/Xcode/DerivedData/`

Just `rm -rf /Users/YOUR-USER/Library/Developer/Xcode/DerivedData/`

**Comment by henrymartison** [comment]
> > > still having issues to build my project through xcode 11..on screen error is YogaKit.modulemap not found...any assistance will be highly appreciated..
> > > I have tried different suggested solution out here but none work for me
> > 
> > 
> > Finally, I found a fix
> > finally i resolved the problem you have to give xcode full disk access all toy have to do
> > 1- open system preference
> > 2- open security & privacy
> > 3- click on full disk access
> > 4- click on the light yellow padlock in order to add xcode to the list
> > 5-click on + button to add new app and choose xcode
> > 6- dropdown will open then click on Applications
> > 7- Double click on Xcode
> > 8-click on yellow padlock to lock the folders back
> > 9- close xcode
> > 10 -go to your project
> > run below code
> > Go to your project ios folder
> > then click on .xcworkspace extension file to open your project with xcode
> > click on Project tab then click click on clean project
> > Now click on build project or the play button
> 
> It's worked for me

None of the above worked. Thanks man, you totally saved me!!!!!

**Comment by cohen72** [comment]
I'm banging my head trying every answer here with no luck.

I have no problem running the project from Xcode, but I stubbornly really want the option to run the project via `react-native run-ios` from the command line using iTerm.

In an effort to further understand the cause, I run the same command from my VSCode terminal, and it works! Why?

Why....?

If anyone can shed some light, perhaps this can help others resolve the issue.  I assume there is some sort of definition within my iTerm that is causing this - is it an npm versioning thing? a react-native cli versioning thing?

**Comment by jpggvilaca** [comment]
Tried every single solution as well. Nothing worked. Updated everything, cleaned project, restarted mac/iterm/xcode, ran from iTerm and from Xcode and nothing yet.

**Comment by Vijaysuryawanshi1993** [comment]
> Tried everything, what worked was to delete the whole `DerivedData` folder, when running `react-native run-ios` again it just worked. Located in: `/Users/YOUR-USER/Library/Developer/Xcode/DerivedData/`
> 
> Just `rm -rf /Users/YOUR-USER/Library/Developer/Xcode/DerivedData/`

Thanks man.
It worked (on existing project suddenly I was getting that issue).

**Comment by edemagbenyo** [comment]
> use .xcodeworkspace is ok

This saved my day!!!

**Comment by luskin** [comment]
> None of the above worked for me.
> I had added some new configurations and deleted the default 'Debug' configuration from xcode.
> 
> So I had to change the following line in Podfile
> :configuration => 'Debug'
> 
> to
> :configurations => ['DevDebug', 'QADebug', 'StageDebug', 'ProdDebug']

@karan-rawal Your syntax is unfamiliar to me as we are used to generally something along the lines of this:

```ruby
project 'YourProject',
  'Staging.Debug' => :debug,
  'Staging.Release' => :release,
  'Production.Debug' => :debug,
  'Production.Release' => :release
```

That being said, we are still dealing with this issue after exactly what you said, we put in some custom build configurations and renamed Debug to `Staging.Debug`. Would you mind posting your exact setup here for how you setup your custom build configurations in your Podfile? Thank you. Also, what version of iOS is your project supporting? We need to still support iOS 10 so we cant bump to 11 like many have said to do. Thanks for the help!

**Comment by pathansajidkhan** [comment]
> Tried every single solution as well. Nothing worked. Updated everything, cleaned project, restarted mac/iterm/xcode, ran from iTerm and from Xcode and nothing yet.

I am having same issue on App Center. Locally on MacBook no issues.

**Comment by shaheer912** [comment]
Hi,

I tried ALL of the above solutions, they did not work for me. What did work for me was
- Open xcode .xcworkspace file
- Try build
- It should fail with the Yogakit.modulemap error
- With error it should also show you some warnings, along the lines of **update project settings to recommended** this warning should be listed twice, one for POD project and one for your app project
- Click on the warnings and update the project to recommended settings, for both warnings.
- Then, it should also show you another warning **Convert to swift 5 available**, if you click it, it will specifically show you the YogaKit module, click convert.
- Its gonna take time, go drink a coffee or something.
- When its done, click build again, thats also gonna take time, this time, take your family for lunch or dinner.
- The build should succeed this time.

**Comment by fadiquader** [comment]
I had this issue on a real device, the **OS** version installed on the phone was incompatible with **Xcode**

**Comment by maxlxq** [comment]
Xcode 12. React Native: 0.63.2, +1

**Comment by dopplerDistortion** [comment]
> Xcode 12. React Native: 0.63.2, +1

same here on device it works. I am able to build for generic and adhoc but not for simulators

**Comment by twelvearrays** [comment]
In my User-Defined section of Build Settings I have VALID_ARCHS defined as arm64 arm64e armv7s because some of my libraries do not support older architectures.  I need this to build on device and for release but it seems that it breaks the simulator for Xcode 12.  By removing VALID_ARCHS from my build settings my simulators will build but I have to put the setting back for devices or releases.  Hope this helps somebody!

**Comment by sagittaracc** [comment]
it doesn't work when I run a blank RN project from Xcode, but it does work from terminal.
Could this react native shit be more tricky???

**Comment by dopplerDistortion** [comment]
> > Xcode 12. React Native: 0.63.2, +1
> 
> same here on device it works. I am able to build for generic and adhoc but not for simulators

Quick update according to this. Downgrading Xcode from 12 to 11.7 is solved the issue. I will stay away from 12 for a while

**Comment by sagittaracc** [comment]
downgraded Xcode to 11.7. still can't build even a blank project. it says yogakit.modulemap not found

**Comment by hannigand** [comment]
> I managed to resolve the issue in my app.
> I had a mismatch between the ios version in Xcode and Podfile.
> 
> ## Podfile
> ![image](https://user-images.githubusercontent.com/270924/78455180-54b9ec00-76cf-11ea-8626-a37bcafdea82.png)
> 
> ## Xcode
> ![image](https://user-images.githubusercontent.com/270924/78455203-73b87e00-76cf-11ea-9c66-37f1c52eef81.png)
> 
> I changed my Podfile to `platform :ios, '9.0'` and ran `pod install` again.
> That did the trick.

This solved my issue. Instead of changing the Podfile version I:

- Selected my app and navigated to the `General` tab
- Scroll to `Deployment Info` 
- Changed `iOS 9.0` to `iOS 11.0`

**Comment by azelaya6** [comment]
for me there were 2 warnings in the issue navigator in xcode mentioning recommended build settings update. i clicked on them, xcode performed the update and now it works

**Comment by hilkbahar** [comment]
> Hi,
> 
> I tried ALL of the above solutions, they did not work for me. What did work for me was
> 
>     * Open xcode .xcworkspace file
> 
>     * Try build
> 
>     * It should fail with the Yogakit.modulemap error
> 
>     * With error it should also show you some warnings, along the lines of **update project settings to recommended** this warning should be listed twice, one for POD project and one for your app project
> 
>     * Click on the warnings and update the project to recommended settings, for both warnings.
> 
>     * Then, it should also show you another warning **Convert to swift 5 available**, if you click it, it will specifically show you the YogaKit module, click convert.
> 
>     * Its gonna take time, go drink a coffee or something.
> 
>     * When its done, click build again, thats also gonna take time, this time, take your family for lunch or dinner.
> 
>     * The build should succeed this time.

I didnt work for me, get the error !

<img width="410" alt="resim" src="https://user-images.githubusercontent.com/12161006/93760620-0fee2700-fc15-11ea-9de1-95e3e124deec.png">

**Comment by OctavianRotari** [comment]
Upgrading to RN 63.2 solved the issue for me

**Comment by shaheer912** [comment]
> 
> 
> > Hi,
> > I tried ALL of the above solutions, they did not work for me. What did work for me was
> > ```
> > * Open xcode .xcworkspace file
> > 
> > * Try build
> > 
> > * It should fail with the Yogakit.modulemap error
> > 
> > * With error it should also show you some warnings, along the lines of **update project settings to recommended** this warning should be listed twice, one for POD project and one for your app project
> > 
> > * Click on the warnings and update the project to recommended settings, for both warnings.
> > 
> > * Then, it should also show you another warning **Convert to swift 5 available**, if you click it, it will specifically show you the YogaKit module, click convert.
> > 
> > * Its gonna take time, go drink a coffee or something.
> > 
> > * When its done, click build again, thats also gonna take time, this time, take your family for lunch or dinner.
> > 
> > * The build should succeed this time.
> > ```
> 
> I didnt work for me, get the error !
> 
> <img alt="resim" width="410" src="https://user-images.githubusercontent.com/12161006/93760620-0fee2700-fc15-11ea-9de1-95e3e124deec.png">

Hmmm. I am not really an expert in React Native right now, still learning. While it might not be the cause but I think you should make sure that you are using some version of Xcode 11 (not 12 and not anything below 10).
I am using MAC OS Catalina.
Also make sure that you have tried all of the solutions listed before my solution, because I tried them all so may be something from that caused my solution to work but not yours?

**Comment by zsn6034** [comment]
open xxx.xcworkspace rather than xxx.xcodeproj make success

**Comment by loveaurell** [comment]
Restarting my computer solved this problem for me

**Comment by AkhtarZaman7** [comment]
terminate Xcode and run again. Worked for me

**Comment by nqdung16** [comment]
Xcode12 still not working. I tried all of those solutions and none of them work for me. Need help urgently

**Comment by deejayxd07** [comment]
This is how it worked for me


1. Close Xcode
2. `rm -Rf ~/Library/Developer/Xcode/DerivedData`
3. On your Podfile, update platform :ios  to `platform :ios, '11.0'` 
3. `yarn && cd ios/ && pod install`

4. Run XCode (open .xcworkspace) again then you will see a warning to upgrade to swift 5, Click the warning then update (This will take some time)
5. After that run the build again, then the app will run.

If that didn't work out for you, clean your repo and remove all the untracked files `git clean -fdx` then do the steps again.
Note that `git clean -fdx` will remove all the untracked files so it's better to have a backup of all your working changes.

**Comment by rumax** [comment]
Project works fine from xcode, but from command line not

```
$ /usr/bin/xcodebuild -version
Xcode 11.3.1
Build version 11C505
```

RN version:
```
"react": "16.13.1",
"react-native": "0.63.3",
```

Steps to reproduce:

```
react-native init test_project
cd test_project/
cd ios/
pod install
xcrun xcodebuild \
  -scheme test_project \
  -project test_project.xcodeproj/ \
  -configuration Debug \
  -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=13.3' \
  -UseModernBuildSystem=NO \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED="NO" \
  build
```

Result 

```
fatal error: module map file
      '/Users/rumax/Library/Developer/Xcode/DerivedData/test_project-fumdkepkulgdnzbkwrntjarkbyai/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap'
      not found
1 error generated.

** BUILD FAILED **
```

**Comment by rumax** [comment]
That change solved the issue in command line and `xcodebuild` for me 

```
-  -project {NAME}.xcodeproj/
+  -workspace {NAME}.xcworkspace 
```

**Comment by rumax** [comment]
I've got the same issue with `Xcode 11.3.1` after upgrading project to `0.63.3`, but only with custom `xcodebuild` scripts in command line. The script used `-project {NAME}.xcodeproj/` and `-UseModernBuildSystem=NO`. Solution was to remove `-UseModernBuildSystem=NO` and  use `-workspace{NAME}.xcworkspace` instead of `-project`

**Comment by huynguyen3tiki** [comment]
Let me show you.
delete all the pod files
Leave this alone.
`config = use_native_modules!
  use_react_native! (: path => config ["reactNativePath"]) `
pod install again and it will work well.

**Comment by rgomezp** [comment]
I have tried many suggestions. None of them work for me

**Comment by mweststrate** [comment]
Summarised the common solutions offered in this thread in the trouble shooting guide: https://fbflipper.com/docs/troubleshooting/#yogakitmodulemap-not-found.

Will close this issue now so that any future reports can come with more detailed information.

**Comment by OctavianRotari** [comment]
For projects that use pods ( which it did for me because I'm using RN63 ) I found that I had to set the version of `IPHONEOS_DEPLOYMENT_TARGET` for all the pods installed in the app, the version had to be consistent with what the version specified in `platform :ios` and with the version specified in Xcode. Making the version consistent across the whole project solved the issue. 

To set `IPHONEOS_DEPLOYMENT_TARGET` for all the pods you need to add:

```
  post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
		end
	end
  end
```

and then run `pod install`

**Comment by jafar-jabr** [comment]
Yogakit was not copied for a reason, the reason most likely is a problem in "CpResource" (build in cmd to make sure)
in this case you can either clean the resources manually or disable "Copy Bundle Resource" from xcode Build phases
this was the solution in my case.

**Comment by Andreyco** [comment]
> I'm not 100% sure if the first line did the trick, or if it was just a terminal restart, but this worked for me:
> 
> `sudo xcode-select --switch /Applications/Xcode.app`
> 
> restart terminal **(important)**
> 
> `cd ios && pod install`

this helped. fml 🤦

**Comment by mdehghani65** [comment]
I had such a statement in my podfile where i've forgotten to remove the last comma, therefore receiving same error. I removed last comma and everything continued smoothly

`project 'dadhesab',
'Sibapp.Debug' => :debug,
'Sibapp.Release' => :release`

**Comment by willnaoosmith** [comment]
Got the same error on Xcode 12.
None of the above solutions worked.
This error only happens when using a emulator instead of a real device.

**Comment by matamicen** [comment]
After fighting for a while, we can run the app on real device and emulators on xcode 12.2 and ios 14.2, here is how we fix the modulemap issue:

0) unistall old xcode
1) install Xcode 12.2 (Release candidate)  and command line 12.2 (Release candidate) from apple developer area (make sure the xcode path is from 12.2 and then go to PREFERENCE form xcode 12.2 and select the command line 12.2 you had installed)
2) Update CocoaPods to 1.10 (supporting Xcode 12)
3) npm install (npm uses some of xcode 12.2 command line, otherwise it will throw errors or bad installation)
4) add the arm64 exclude architectures and DELETE VALID_ARCHS more info in this [blog](https://medium.com/@khushwanttanwar/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9)
5) pod install
6) may be has some failed on emulator becasue of Target issue, we accept the Xcode recomendation and build again and it works.

Hope it helps :)

**Comment by ejeanneau** [comment]
Hello,

Here my solution : 

- uninstall xcode
- restart computer
- install xcode 12.2
- `expo init ProjectName`
- `cd ProjectName`
- `expo-cli login` (type email & password)
- `expo eject --no-install`
- `npm install`
- `cd ios/`
- `pod install`
- `cd ..`
- `react-native run-ios`

Enjoy !

**Comment by fabianoneumann** [comment]
I was facing the same problem. What fixed for me was going to Edit Scheme... -> Run -> Change Build Configuration to Release.

**Comment by marcelocrljunior** [comment]
Hi, I`ve tried everything on this thread, but nothing worked out. So when I build the app with the workspace in xcode, the app build ok, but I need to publish the app, and when I build the app using fastlane that uses command line to build, the YogaKit module.map not found appears again, So anyone please cloud help me to fix this issue?

**Comment by Garretming** [comment]
<img width="912" alt="截屏2020-12-18 上午11 38 33" src="https://user-images.githubusercontent.com/20328248/102571923-c20a9180-4125-11eb-96ea-2c5d678f820e.png">
Make sure it is checked，and then,you can clean and build.

**Comment by tusharahinave** [comment]
> I've incurred in the same error, it doesn't work also with blank RN project.
> 
> ```
> System:
>     OS: macOS 10.15.4
>     CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
>     Memory: 26.77 MB / 8.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 10.16.0 - /var/folders/mm/zm3z3hx96p7_9jxhs_6f8v2h0000gn/T/yarn--1586964002884-0.9192953256519525/node
>     Yarn: 1.22.4 - /var/folders/mm/zm3z3hx96p7_9jxhs_6f8v2h0000gn/T/yarn--1586964002884-0.9192953256519525/yarn
>     npm: 6.14.4 - ~/.nvm/versions/node/v10.16.0/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.9.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: 3.6 AI-192.7142.36.36.6241897
>     Xcode: 11.4/11E146 - /usr/bin/xcodebuild
>   Languages:
>     Java: 13.0.2 - /usr/bin/javac
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.11.0 => 16.11.0 
>     react-native: 0.62.2 => 0.62.2 
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```

ohhh really

**Comment by wujianbotju** [comment]
In my case, if your xcode's version is above 12, check the 'Build Settings' of your project & target, search valid_archs, if valid_archs configuration item exsits and x86_64 is missing, add x86_64.

**Comment by lieberscott** [comment]
People are saying to use the .xcworkspace file, but my project doesn't have this file. (Have tried every other solution in this thread but nothing has worked). I used `expo eject` to create this project. See the screenshot below. Is there some way for me to create a .xcworkspace file?

![Screen Shot 2021-01-10 at 1 47 18 AM](https://user-images.githubusercontent.com/26235414/104117305-dcc7c480-52e5-11eb-9039-74017bf77ab1.png)

**Comment by lkspc** [comment]
> In my case, if your xcode's version is above 12
> 
> 1. check the 'Build Settings' of your project & target, search valid_archs.
> 2. if valid_archs configuration item exsits and x86_64 is missing, add x86_64.

Worked for me. And I have seen an explaining here in chinese https://juejin.cn/post/6875270871083286542

**Comment by harbolaez** [comment]
tried few stuff suggested here - getting this issue with Fastlane? Does anyone have any idea how to fixed there?

**Comment by MaximRG** [comment]
Excluded architectures in pod file get removed on pod install sometimes.

<img width="731" alt="Screen Shot 2021-01-31 at 1 54 24 PM" src="https://user-images.githubusercontent.com/20373805/106384582-e5368b00-63cb-11eb-930e-7831b9bff048.png">

That fixes it. 
(Mac M1)

**Comment by cavalos0086** [comment]
@MaximRG Awesome! this fixed my issue. Thanks!

**Comment by kubilaytural** [comment]
I have the same problem. I tried everything but couldn't figure it out.

My problem is all about getting the archive.

Even when I try to create and archive a project with react-native-init, I get this error.

Help.

macOS version: Big Sur 11.1
Xcode version: 12.4

<img width="867" alt="Screen Shot 2021-01-31 at 22 29 49" src="https://user-images.githubusercontent.com/23127307/106395550-db387a80-6413-11eb-89d7-15276692826f.png">


<img width="605" alt="Screen Shot 2021-01-31 at 22 30 52" src="https://user-images.githubusercontent.com/23127307/106395577-002ced80-6414-11eb-95e2-7891e91dc3ad.png">

**Comment by fernandovrgas** [comment]
Eu tbm com 

macOS version: Big Sur 11.2
Xcode version: 12.4 (12D4e)

Mesmo problema

**Comment by kubilaytural** [comment]
I was able to solve my problem by synchronizing the xcode development target and pod target version.

**Comment by RPadden97** [comment]
Been struggling with this issue for a while, but was able to fix it. For me, the iOS version in the Pods file (and on the pods project in Xcode) had to be the same as iOS Deployment Target in the app's project. This also includes going through the build settings and making sure each "iOS deployment target" also matches that version. Unfortunately, changing the overall iOS Deployment Target wouldn't trickle down through the rest of the build settings.

**Comment by MaazF94** [comment]
In case someone is looking through this and still couldn't resolve like me:

I tried many of the solutions above. I found that XCode was not generating my libraries in the debug-iphonesimulator folder so I went to visual studio and ran react-native run-ios. This generated all the folders, ran the app properly, went back to xcode, no more warnings or errors. Was also able to run the app from xcode thereafter as well.

**Comment by rodrigofbm** [comment]
I run npx react-native run-ios on Vs code and work fine. Then I opened the . xcworkspace file on XCode and it worked too

**Comment by ttibau** [comment]
> I run npx react-native run-ios on Vs code and work fine. Then I opened the . xcworkspace file on XCode and it worked too

Thanks, this worked for me <3

**Comment by jocoders** [comment]
Guys I have the same problem on Macbook M1, Xcode 12.4, react-native: 0.63.4, React Native project from scratch, worked just a few days, I did not make any IOS changes, and after build failed: 

> fatal error: module map file '/Users/jocoders/Library/Developer/Xcode/DerivedData/CryptoWalletApp-hfiwvoyqlbgufkgtyvqtxygiaodf/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found

I tried a lot of ways from this tread, but nothing works for me. Any new decisions? Please 🙏🙏🙏

**Comment by gmonte** [comment]
@jocoders I have the same issue with Macbook Pro Intel 2020. Do you found any solution?

**Comment by nambka** [comment]
I'm having the same issue, none of the above solutions works... 
`building file list ... rsync: link_stat "../react-native/packages/rn-tester/Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework//react-native/packages/rn-tester/Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/." failed: No such file or directory (2)

Command PhaseScriptExecution failed with a nonzero exit code
`

**Comment by oswalgopal** [comment]
faced same issue but tried following steps and it worked
1. remove Pods folder and Podfile.lock
2. open chat_app.xcworkspace file in xcode.
3. clean the build folder and try running it.

It will run.

**Comment by interhub** [comment]
Solved:
**1) open terminal and run "npx react-native run-ios" and await end load
2) open xcode and run app on simulator or run archive app** 
that ALL!
Welcome!

**Comment by balwinder4264** [comment]
I tried everything This is what worked for me.

problem is with

Before podFile :
 use_flipper! 

After :
use_flipper!({ 'Flipper' => '0.74.0' }) 

then:

pod install

**Comment by jmalStorm** [comment]
revert all changes, pod install, add exclude `arm64` to project and pods - worked for me

**Comment by shra1dhar** [comment]
Disclaimer: I've M1 mac setup. 
The above methodologies were not working for me. However this worked:
Run XCode in Rosetta. 

`Xcode in applications folder -> Get Info -> set Open with Rosetta to true`

More info [https://developer.apple.com/forums/thread/670006](url)

**Comment by heron2014** [comment]
M1 mac - setup:

<img width="776" alt="Screenshot 2021-04-18 at 22 14 22" src="https://user-images.githubusercontent.com/8476884/115161064-747e4100-a093-11eb-899b-a7e81a88f75d.png">

plus I added in Podfile:

```post_install do |installer|
    react_native_post_install(installer)
     installer.pods_project.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
     end
  end
```

After remove ```Podfile.lock``` and ```Pods``` and re-run ```pod install```

**Comment by crrobinson14** [comment]
I tried everything listed above and nothing seemed to help me. This was in a fresh 0.63.4 installation (my app needs a library that doesn't work in 0.64 yet) just after adding the Swift Bridging Header. What finally worked (probably in addition to some of the suggestions above, like excluding `arm64`) was running `yarn ios`. I had previously been trying over and over to get XCode itself to compile the project and kept getting this error. But `yarn ios` fixed it, both in the CLI AND in XCode. I'm not sure what black magic is going on but...

**Comment by cd-gene** [comment]
Perhaps you guys opened up .xcodeproj and not the .xcworkspace

**Comment by lilien1010** [comment]
make sure the Yogakit iOS deployment target match, This worked for me!!!
![image](https://user-images.githubusercontent.com/3814966/117243974-c6cca980-ae6a-11eb-9f4b-f6c4698a1585.png)

**Comment by greatnonso7** [comment]
Change your iOS version to match with what you have on your podfile

**Comment by marinne** [comment]
On my system (MacBook Air M1, Xcode 12.4) everything worked fine but one day I performed "Product > Clean Build Folder" action then suddenly this "module map file not found" error happened and kept occurring. I setup a new project, the "Clean Build Folder" action introduced the same "module map file not found" error (although for different pod).

This error only occurred when I tried to build/run on a simulator. The build worked fine when running on a physical device.

I tried many of the suggested solutions, building in VS Code terminal ( > npm run ios) solved the problem. The build worked fine in VS Code terminal and after I successfully built in VS Code, building in Xcode also began working again.

**Comment by tbanj** [comment]
@ ghost this work for me, opening the project through workspace

**Comment by twistezo** [comment]
If you have this problem on M1 with clean new project `react-native init Foo` just comment `use_flipper!()` in `ios/Podfile` -> remove folder `ios/Pods` -> remove file `ios/Podfile` -> run `pods install`

Then you can run this sample project in simulator `react-native run-ios`

Xcode 12.5
react-native 5.0.1

**Comment by sebastiancichos** [comment]
remove Podfile.lock, next `use_flipper!({ 'Flipper' => '0.91.1' })` and `pod install`

**Comment by quanghoahcm** [comment]
I have same problem.
I run ok with command: 'npx react-native run-ios' but it not work when i run in my real device Iphone 11 Pro Max.
Pls help me.

**Comment by tbanj** [comment]
@quanghoahcm Have you try opening your project with the .workspace file in the ios folder

**Comment by samrezikram** [comment]
Described solution will work 100% on Apple silicon and while running Xcode without rosetta.

Please try necessary steps only but if still not work than Please try everything including necessary and unnecessary steps. 

1 - Not important(Package.json)

    "dependencies": {
     "react": "17.0.1",
     "react-native": "0.64.2"
    }

---
2 - necessary

      use_flipper!()
      post_install do |installer|
        react_native_post_install(installer)
            installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
            end
      end

OR

      use_flipper!()
    
      post_install do |installer|
        react_native_post_install(installer)
          installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
              end
          end
      end

----

3 - Add `arm64` under Architectures->Excluded Architectures

----

**[![Add a *swift file* under your project, can be empty, can be BridgingFile.swift(nothing special in it), this will trigger a bridging header. Wallah, here you go.][1]][1]**

  


  [1]: https://i.stack.imgur.com/rV2pk.png

**Comment by jmsn123** [comment]
> If I run my project from project workspace then this error deosn't show up. And whenever you are using pods. You should always run your project from workspace

Workspace isnt giving me any fiels its just empty

**Comment by jinhale** [comment]
I had this problem also. I got this problem after upgrading the project's NPM packages including , on the Windows computer for an Android project, and then pulling in the code and performing an upgrade using `yarn` and `cd ios && pod update`. Trying to roll back to a version that first worked with Xcode 12.5 has not worked and yields the same error. 

If I open using the alternative extension, `xcodeworkspace`, any build or archive will be run against 

There is no section, project, in the Podfile, but if I add the recommended line, the error remains. 

Adding the following line of code doesn't work: `installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"`

For me, adding the following to Podfile was necessary: `{ 'Flipper' => '0.91.1' }`. Thanks @sebastiancichos

```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 214.45 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/npm-global/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ankitsh2715** [comment]
> I was banging my head trying every answer here with no luck.
> 
> I had no problem running the project from Xcode, but I stubbornly really wanted the ability to run the project via `react-native run-ios` from the command line using iTerm.
> 
> In an effort to debug, I run the same command from my VSCode terminal, and it worked! Why? Why.... I yelled inside.
> 
> So I restarted my iTerm, and it began working. I'm not sure what's happening under the hood with iTerm, but a simple restart fixed my issue.

Your comment saved me from factory resetting my mac. Was able to build my app from xcode but `react-native run-ios` command somehow started giving errors. No errors in VSCode !

**Comment by ankitsh2715** [comment]
> I was banging my head trying every answer here with no luck.
> 
> I had no problem running the project from Xcode, but I stubbornly really wanted the ability to run the project via `react-native run-ios` from the command line using iTerm.
> 
> In an effort to debug, I run the same command from my VSCode terminal, and it worked! Why? Why.... I yelled inside.
> 
> So I restarted my iTerm, and it began working. I'm not sure what's happening under the hood with iTerm, but a simple restart fixed my issue.

Your comment saved me. Was able to build my app from xcode but react-native run-ios command somehow started giving errors. No errors in VSCode !

**Comment by QuentinNolan** [comment]
None of the answers above fixed my problem. I was already using `.xcodeworkspace ` and platform target was the same in Xcode and in Podfile.

I fixed this issue by adding this line to Podfile:
`config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"`

This example shows where to write the line above:
`post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
     end
  end`

**Comment by mikehardy** [comment]
Here's intel or m1 / apple silicon mac working in debug and release on react-native 0.65 with hermes and flipper. It's a mess!

```ruby

  post_install do |installer|
    react_native_post_install(installer)

    installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)'] // or it won't build on apple silicon
          # without explicitly clearing this out, it flaps between excluding arm64 or not
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "" // stop this setting from waffling between arm65/x86_64 machines after pod install
          # Fix some library / linker errors
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' // only one at a time
          config.build_settings['VALID_ARCHS'] = 'arm64 x86_64' // you need both to work on both CPU archs / release etc
          config.build_settings['EXCLUDED_ARCHS'] = 'i386' // or you get directory not found linker errors
        end
      end
      aggregate_target.user_project.save
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        # We support a smaller range of deployment than some libraries, eliminate related noise
        # This also avoids a nasty Folly bug about an API not available until ios10+
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSMinimumDeployVersion
      end
    end

    # If you move versions around though you get another nasty Folly bug about redefined symbols, fix that...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`

  end
```

**Comment by matthoffner** [comment]
> Here's intel or m1 / apple silicon mac working in debug and release on react-native 0.65 with hermes and flipper. It's a mess!
> 
> ```ruby
>   post_install do |installer|
>     react_native_post_install(installer)
> 
>     installer.aggregate_targets.each do |aggregate_target| 
>       aggregate_target.user_project.native_targets.each do |target|
>         target.build_configurations.each do |config|
>           config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)'] # or it won't build on apple silicon
>           # without explicitly clearing this out, it flaps between excluding arm64 or not
>           config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "" # stop this setting from waffling between arm65/x86_64 machines after pod install
>           # Fix some library / linker errors
>           config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' # only one at a time
>           config.build_settings['VALID_ARCHS'] = 'arm64 x86_64' # you need both to work on both CPU archs / release etc
>           config.build_settings['EXCLUDED_ARCHS'] = 'i386' # or you get directory not found linker errors
>         end
>       end
>       aggregate_target.user_project.save
>     end
> 
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
> 
>         # We support a smaller range of deployment than some libraries, eliminate related noise
>         # This also avoids a nasty Folly bug about an API not available until ios10+
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSMinimumDeployVersion
>       end
>     end
> 
>     # If you move versions around though you get another nasty Folly bug about redefined symbols, fix that...
>     `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
> 
>   end
> ```

Thank you, confirming this resolved it for me resolving this issue on M1 without having to use x86_64.

**Comment by martin-richter-uk** [comment]
> Change your iOS version to match with what you have on your podfile

This worked for me

**Comment by narcismihaitech** [comment]
> I managed to resolve the issue in my app. I had a mismatch between the ios version in Xcode and Podfile.
> ## Podfile
> 
> ![image](https://user-images.githubusercontent.com/270924/78455180-54b9ec00-76cf-11ea-8626-a37bcafdea82.png)
> ## Xcode
> 
> ![image](https://user-images.githubusercontent.com/270924/78455203-73b87e00-76cf-11ea-9c66-37f1c52eef81.png)
> 
> I changed my Podfile to `platform :ios, '9.0'` and ran `pod install` again. That did the trick.

This solved the issue for me. I had  `platform :ios, '11.0'` in my Podfile, but 10.0 as the iOS version in Xcode. I changed the iOS version to 11.0 in Xcode and was afterwards able to generate the archive. Thank you!

**Comment by kelokchan** [comment]
Everything magically worked again after restarting the Terminal

**Comment by yemd** [comment]
> Disclaimer: I've M1 mac setup. The above methodologies were not working for me. However this worked: Run XCode Rosetta.
> 
> `Xcode in applications folder -> Get Info -> set Open with Rosetta to true`
> 
> More info [https://developer.apple.com/forums/thread/670006](url)

Crazy how you just saved me from insanity.
This should be pinned on the home page of GitHub and SO for every M1 user so they can avoid losing DAYS.
Xcode is now under Rosetta forever, Hyper as well.

**Comment by mikehardy** [comment]
@yemd Xcode should not be under Rosetta, nothing should be under Rosetta. There are real updates to the software in use that should have everything working fine without Rosetta. Next version of react-native actually checks and complains if you attempt to use Rosetta, because it can cause problems if you use it sometimes but not other times (for instance, brew will have lots of issues...)

I suppose it's possible to consider "updating toolchains and software in use to current stable versions" as "insanity" and/or "losing" time, but as a maintainenance-minded person I think it quite the opposite, keeping current fixes bugs (like "it doesn't work on my M1") before you even know the bugs existed

**Comment by yemd** [comment]
> @yemd Xcode should not be under Rosetta, nothing should be under Rosetta. There are real updates to the software in use that should have everything working fine without Rosetta. Next version of react-native actually checks and complains if you attempt to use Rosetta, because it can cause problems if you use it sometimes but not other times (for instance, brew will have lots of issues...)
> 
> I suppose it's possible to consider "updating toolchains and software in use to current stable versions" as "insanity" and/or "losing" time, but as a maintainenance-minded person I think it quite the opposite, keeping current fixes bugs (like "it doesn't work on my M1") before you even know the bugs existed

Well I tried very very hard to get everything working properly for too many days using RN and my M1, unfortunately besides some really basic apps it was a nightmare, if you have solutions  to make M1 + RN + Flipper + FB SDK + Google SDK work properly natively without shady hacks natively I am more than welcome to know. 

 I also am a man of maintainability wherever I can and that would ease my mind a great deal, and everyone could benefit from this.

**Comment by mikehardy** [comment]
Sure. I demonstrate exactly what you want with this full-featured template: https://github.com/invertase/react-native-firebase-authentication-example - I help maintain react-native-fbsdk-next, react-native-google-signin, react-native-firebase, and have worked on the patches that make react-native itself work on the M1. It all works, or should work. Please be careful with the word "shady" when used in conjunction with hack. Some hacks are beautiful. Some are ugly, but none really deserve a moral label applied to them. Think in terms of "understandable", "localized", "functional", "temporary" as criteria. The M1 "hack" required for react-native is understandable, localized, functional and temporary, and as such if you wanted to get moral with it, is a beautiful thing.

Curious to hear if that template, used in conjunction with Xcode 13.2.1 and cocoapods 11.2 has any issues for you while running native / no rosetta on M1. It should work.

**Comment by yemd** [comment]
> 

Quite a comment! I'm well aware of what you are working on and thank you for that!
 I will try what you just sent me and come back here with great pleasure!

**Comment by yemd** [comment]
> Sure. I demonstrate exactly what you want with this full-featured template: https://github.com/invertase/react-native-firebase-authentication-example - I help maintain react-native-fbsdk-next, react-native-google-signin, react-native-firebase, and have worked on the patches that make react-native itself work on the M1. It all works, or should work. Please be careful with the word "shady" when used in conjunction with hack. Some hacks are beautiful. Some are ugly, but none really deserve a moral label applied to them. Think in terms of "understandable", "localized", "functional", "temporary" as criteria. The M1 "hack" required for react-native is understandable, localized, functional and temporary, and as such if you wanted to get moral with it, is a beautiful thing.
> 
> Curious to hear if that template, used in conjunction with Xcode 13.2.1 and cocoapods 11.2 has any issues for you while running native / no rosetta on M1. It should work.

Quite a comment! I'm well aware of what you are working on and thank you for that!
 I will try what you just sent me and come back here with great pleasure!

**Comment by Raja4567** [comment]
After trying every solution on the internet, this worked for me.

`
cd ios && pod install && cd ..
`
then
`
npx react-native link
`
or
`
yarn react-native link
`

**Comment by jinhale** [comment]
> After trying every solution on the internet, this worked for me.
> 
> `cd ios && pod install && cd ..` then `npx react-native link` or `yarn react-native link`

Linking that way, as opposed to the automatic way, is only recommended and useful for older versions of React Native. Doing that with the most recent version of RN should either be a no-op or cause the project to be broken from a misconfiguration. 

For the uninitiated, linking packages, which is what `yarn react-native link` does, is different than [linking to apps](https://reactnative.dev/docs/linking) such as a browser.

**Comment by mjstelly** [comment]
> @quanghoahcm Have you try opening your project with the .workspace file in the ios folder

This isn't a solution. It's simply a shortcut way of launching Xcode directly into your project. Nothing special occurs using this method vs. launching Xcode through CLI or GUI.

**Comment by mjstelly** [comment]
> After trying every solution on the internet, this worked for me.
> 
> `cd ios && pod install && cd ..` then `npx react-native link` or `yarn react-native link`

`react-native link` is deprecated. It mentions this in the launch sequence:

> error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-device-info (to unlink run: "react-native unlink react-native-device-info")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

**Comment by zoobibackups** [comment]
My issue resolve by this:

```
Xcode v11.4

// Pod file config...

use_flipper!({ 'Flipper' => '0.91.1' })
  post_install do |installer|
    flipper_post_install(installer)
 end
```
```
'react": "17.0.2",
"react-native": "0.67.3",
```

**Comment by edglo98** [comment]
> I managed to resolve the issue in my app. I had a mismatch between the ios version in Xcode and Podfile.
> ## Podfile
> 
> ![image](https://user-images.githubusercontent.com/270924/78455180-54b9ec00-76cf-11ea-8626-a37bcafdea82.png)
> ## Xcode
> 
> ![image](https://user-images.githubusercontent.com/270924/78455203-73b87e00-76cf-11ea-9c66-37f1c52eef81.png)
> 
> I changed my Podfile to `platform :ios, '9.0'` and ran `pod install` again. That did the trick.

this works for me, could there be any impact?

**Comment by musabgulfam** [comment]
Still facing this issue

**Comment by macci10** [comment]
I solved this issue by adding 3 liner code in PodFile on my m1 macbook. 
`installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end`
Full Example below
`post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
   installer.pods_project.targets.each do |target|
     if (target.name&.eql?('FBReactNativeSpec'))
       target.build_phases.each do |build_phase|
         if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
           target.build_phases.move(build_phase, 0)
         end
       end
     end
   end
  end`

**Comment by Garretming** [comment]
已收到，我会尽快回复的了！

**Comment by Garretming** [comment]
已收到，我会尽快回复的了！

**Comment by lucifer-cw** [comment]
pod install try

**Comment by Garretming** [comment]
已收到，我会尽快回复的了！

**Comment by pprasha** [comment]
The issue I was facing when I received this error was, I had opened the wrong file in Xcode. Instead of opening the `*.xcworkspace` file, I opened the `*.xcodeproj` file.

The solution to this issue is to open the `*.xcworkspace` file in Xcode instead of the `*.xcodeproj` file.

**Comment by codemobiles** [comment]
In my case M1, I have proven the suggestion above. If anyone can run via opening *.xcworkspace but cannot run via terminal app or terminal in vscode.  You just re-open the terminal or vscode first and try to run again. Now it works without any errors.

**Comment by cglacet** [comment]
Does anyone have an idea how to debug this kind of issue? I tried many of the suggested soluions but I still have this error (several missing .modulemap files). It seems like the build is supposed to move this files by itself because the location is something that is not part of my folder structure (something like `/Users/mylogin/Library/Developer/Xcode/DerivedData/Kune-<random-uid>/Build/Products/Development.Release-iphonesimulator/YogaKit/YogaKit.modulemap`).

I really struggle understanding builds (and therefore its hard to figure out what is going on). Everything is a bit too opaque and the terminology is very complex (workspace, projet, target, scheme, configuration, pods, …).

**Comment by marlonschlosshauer** [comment]
> In my case M1, I have proven the suggestion above. If anyone can run via opening *.xcworkspace but cannot run via terminal app or terminal in vscode. You just re-open the terminal or vscode first and try to run again. Now it works without any errors.

This solved it for me. I had previously built from Xcode, which also launched  the terminal. I reused that terminal instance and kept getting a wall of text when running `npm run ios`. Restarted my M1 and it worked fine again.

**Comment by waqaskhanroghani** [comment]
ANY Solution ???
----------------------------------------------
Error: 
The following build commands failed:
	CompileC /Users/apple/Library/Developer/Xcode/DerivedData/CCMS-fstgkackpdifrgfsclbkhczdgkkb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsi.build/Objects-normal/x86_64/JSIDynamic.o /Users/apple/Bircube/QR-Scanner/node_modules/react-native/ReactCommon/jsi/jsi/JSIDynamic.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-jsi' from project 'Pods')
(1 failure)

**Comment by Garretming** [comment]
已收到，我会尽快回复的了！

**Comment by w8ight** [comment]
Tried almost all the solutions from three - nothing helped, Xcode kept showing the error. But for some reason was able to build app from Terminal by running `react-native run-ios --simulator=\"iPhone 14 Pro\"`

**Comment by AlkanV** [comment]
> I'm not 100% sure if the first line did the trick, or if it was just a terminal restart, but this worked for me:
> 
> `sudo xcode-select --switch /Applications/Xcode.app`
> 
> restart terminal **(important)**
> 
> `cd ios && pod install`

you are a hero my friend. some heros does not wear capes.

**Comment by alvesrafa** [comment]
check if u have .xcode.env in your /ios folder
if u dont have, try to create with this:

```
# This `.xcode.env` file is versioned and is used to source the environment
# used when running script phases inside Xcode.
# To customize your local environment, you can create an `.xcode.env.local`
# file that is not versioned.

# NODE_BINARY variable contains the PATH to the node executable.
#
# Customize the NODE_BINARY variable here.
# For example, to use nvm with brew, add the following line
# . "$(brew --prefix nvm)/nvm.sh" --no-use
export NODE_BINARY=$(command -v node)

```

after created, re-open your project in xcode.

**Comment by zhuiye** [comment]
> I solved this issue by adding 3 liner code in PodFile on my m1 macbook.
> 
> ```
> installer.pods_project.build_configurations.each do |config|
>       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
> ```
> 
> Full Example below
> 
> ```
> post_install do |installer|
>     react_native_post_install(installer)
>     installer.pods_project.build_configurations.each do |config|
>       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
>    installer.pods_project.targets.each do |target|
>      if (target.name&.eql?('FBReactNativeSpec'))
>        target.build_phases.each do |build_phase|
>          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
>            target.build_phases.move(build_phase, 0)
>          end
>        end
>      end
>    end
>   end
> ```

bro,save my life ,i use m2/ mini，

**Comment by BrewCurious** [comment]
For whatever it's worth, I found that opening either the <project_name>.xcodeproj or the <project_name>.xcworkspace files in Xcode came up unbuildable. Either I had access to all of my project files, but ran into a series of "Module not found" messages or I had access to all of the Pods configuration information, but no way to build the app for testing or archiving.

When I opened the *directory* in which all of those files were located, however, I had both the app build files as well as the pod configurations available within the navigation pane of Xcode and running the code successfully built and launched into either the simulator or archive.

Maybe just my situation, but there you are.

**Comment by Yasir12598** [comment]
In my case I resolved by enabling the rossetta in xcode 14.3 [link](https://sarunw.com/posts/open-using-rosetta-in-xcode-14-3/)

**Comment by Vorobeyko** [comment]
I fixed this problem for my when set arm64 to exluded arch
![image](https://github.com/facebook/react-native/assets/11293201/5100af82-6d03-4aaa-9fd4-3b78d6097db0)

**Comment by sajjad-karimi** [comment]
in my case I just set `Build Active Architecture Only` `Debug` to `Yes` ,
from `Buid Settings`
<img width="712" alt="Screenshot 2023-11-15 at 2 51 26 PM" src="https://github.com/facebook/react-native/assets/30430992/d8aff39f-9488-401b-baeb-ef04edcc2472">

**Comment by leechanghoon3024** [comment]
@macci10 
Good. Thank you

**Comment by lukebrandonfarrell** [comment]
I had this issue sporadically when trying to run detox build, which runs the xcodebuild -workspace command. The first time it came up, I solved it by upgrading my system's Ruby version from 2.6.10 to 2.7.5. The second time it came up, I solved it by closing Xcode and simulators, removing and reinstalling /node_modules and /ios/Pods, and then rerunning the command. Somehow, the error vanished 🤷

I suspect there is an issue in the build process that results in module map files not being generated, possibly some race condition.

**Comment by ketan-pcs** [comment]
use .xcodeworkspace is ok  and 
I'm not 100% sure if the first line did the trick, or if it was just a terminal restart, but this worked for me:

sudo xcode-select --switch /Applications/Xcode.app

restart terminal (important)

cd ios && pod install
