### ISSUE TITLE
useWindowDimensions() returns swapped height and width in iOS

### ISSUE THREAD

**Issue by vicary** [facebook/react-native#29290]
## Description
When tested with iPad simulator, the `useWindowDimensions(...)` hook returns incorrect width and height.

## React Native version:
Run `react-native info` in your terminal and copy the results here.

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 24.79 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /var/folders/k_/twn4fnrn6g56kn0xjlkp3zx00000gn/T/yarn--1594122179123-0.9086048405049534/node
    Yarn: 1.22.4 - /var/folders/k_/twn4fnrn6g56kn0xjlkp3zx00000gn/T/yarn--1594122179123-0.9086048405049534/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.0
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 11.68s.
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use `react-native init` to create a new project.
2. Edit `App.js` with the following code
    ```jsx
    import React from "react";
    import { Text, View, useWindowDimensions } from "react-native";

    export const App = () => {
      const { width, height } = useWindowDimensions();

      return (
        <View
          style={{
            width: "100%",
            height: "100%",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Text>{width > height ? "landscape" : "portrait"}</Text>
          <Text>{`width: ${width}, height: ${height}`}</Text>
        </View>
      );
    };
    ```

## Expected Results
1. At the first time I rotate the simulator to *landscape*, it should display `"landscape"` instead of nothing happens.
2. At the second time the simulator rotates back to portrait position, it should render `"portrait"` on the screen.
3. At the second time I rotate from portrait to landscape, it should display `"landscape"` instead of `"portrait"`.

## Snack, code example, screenshot, or link to a repository:
It is not easy to show device orientation features in snack, I'll attach screen recordings below.

![Screen Recording 2020-07-07 at 7 39 07 PM](https://user-images.githubusercontent.com/85772/86777634-fc0e3c80-c08b-11ea-858b-e50bed6d4c1d.gif)

You may download the original video to pause for the rendered text.
[Screen Recording 2020-07-07 at 7.39.07 PM.zip](https://github.com/facebook/react-native/files/4884736/Screen.Recording.2020-07-07.at.7.39.07.PM.zip)

**Comment by chrisglein** [comment]
Is it that useWindowDimensions is returning the wrong numbers, or is the component not rerendering in response to the changes in orientation? Have you validated that it's running (with a log statement or whatever) and reporting the wrong numbers?
Have you tried this on Android?

**Comment by vicary** [comment]
@chrisglein Android is working fine.

iOS is behaving strangely, not a simple unresponsive but kind of a “delayed” state.

1. You start the app in portrait
2. The first time it changes from portrait to landscape, nothing happens
3. You rotate back to portrait
4. It now changes to landscape (width > height)
5. Now you rotate to landscape again
6. It now reports portrait (width < height)

Since step 3 the behaviour repeats, only by re-launching the app could you reproduce step 1 and 2.

**Comment by vicary** [comment]
Adding to the context, the above behavior is also confirmed with console logs.

**Comment by silencer07** [comment]
This is problem too. The solution i did was to listen to view onlayoutevent to get the right width and height(which you store on state)

For orientation, i used react native locker and do Orientatio.addListener and store the result in state too.

Yeah unfortunately handling those is sometimes feels too manual

**Comment by vicary** [comment]
Only workaround is to work with custom native modules.

Even `DeviceInfo` uses the same [logic](https://github.com/react-native-community/react-native-device-info/blob/9227f7d598bfb04fe53204774406aa7ca6a9f11a/src/index.ts#L1059) for landscape detection than native values, the potential affected users is sizeable in that sense.

**Comment by jaulz** [comment]
I also noticed that the sizes are swapped for a very short amount of time when the iPad is unlocked and the app was still active. Though, I am not dealing with with Dimensions directly but instead have a root view that has an `onLayout` handler:
```typescript
import React, { useCallback } from 'react'
import { LayoutChangeEvent, StyleSheet, View } from 'react-native'
import { useDebouncedCallback } from '../../../hooks'

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
})

let i = 0
const MeasureView: React.FC = (props) => {
  const { children } = props

  // Create handlers
  const [setDimensions] = useDebouncedCallback(
    (width: number, height: number) => {
      alert('setDimensions ' + i + ': width=' + width)
      i++
    },
    500
  )
  const handleLayout = useCallback(
    (event: LayoutChangeEvent) => {
      const { width, height } = event.nativeEvent.layout

      alert('handleLayout ' + i + ': width=' + width)
      i++
      setDimensions(width, height)
    },
    [setDimensions]
  )

  return (
    <View style={styles.container} onLayout={handleLayout}>
      {children}
    </View>
  )
}

export default MeasureView
```

The output is:
```
handleLayout 0: width=1024
setDimensions 1: width=1024
(lock iPad, unlock iPad)
handleLayout 2: width=768
handleLayout 3: width=1024
setDimensions 4: width=1024
```

**Comment by vicary** [comment]
@jaulz your issue may not be the same as this one, but the snippet could be a workaround of mine though!

**Comment by jaulz** [comment]
@vicary in fact this was my approach as a workaround but as you can see it doesn't solve the dimensions issue but just uses a debounce to avoid it. The original issue that dimensions are swapped is still a problem.

**Comment by tylerc** [comment]
I'm seeing similar problems on Android, except that after the 1st rotation, the values seem to be stuck on whatever the 2nd state was (e.g. if I started in portrait mode, after I rotate to landscape the `width` and `height` returned by `Dimensions.get` are pegged to landscape. If I started in landscape, after going to portrait mode `Dimensions.get` will always return portrait dimensions.)

**Comment by vicary** [comment]
I am curious on how Facebook addresses this kind of issues, is it supposed to be fixed by the community via PR or shall we wait?

**Comment by elmcapp** [comment]
I only have this issue with Android. If device is in portrait and I rotate it to landscape and quickly back to portrait the width and height numbers returns swap.   This hurts my layout as my layout depends on these numbers

**Comment by 3GOMESz** [comment]
Android landscape, fullscreen without system's Status Bar or Navigation Bar.

 I noticed that the "**red rectangle**" had a kind of vertical margin and I solved it using the height as "100%"
 
-------------------------------------------------

 ```
const {width, height} = useWindowDimensions();

 <MyView style={{position: 'absolute', backgroundColor: 'red', width: width, height: height}}/>
```
<img width="946" alt="Screen Shot 2022-04-29 at 18 01 00" src="https://user-images.githubusercontent.com/28831375/166068739-b37cec62-b9be-4856-8de2-04d6ac6e1778.png">

is different from 

 ```
 <MyView style={{position: 'absolute', backgroundColor: 'red', width: '100%', height: '100%'}}/>
 ```
 
 <img width="964" alt="Screen Shot 2022-04-29 at 18 00 39" src="https://user-images.githubusercontent.com/28831375/166068728-b7d7603a-473b-458f-878a-1afb2014c417.png">
 
-------------------------------------------------

**Comment by vicary** [comment]
This issue is still valid to this date.

If any anyone is interested and want more information to start working, please let me know.

**Comment by zerobertelprivat** [comment]
Hello, i am experiencing a similar issue on Ipad ... "useWindowDimensions" is not returning new screen size values after the first 90deg device rotation. With the second rotation and any following, the hook is returning new values but swapped (incorrect). My suspicion is, that this is maybe related to the Scene Logic, we have implemented with Carplay. Did you have a similar core refactoring? Greets, Robert

**Comment by daholino** [comment]
We experienced same issues with swapped widths and heights on iOS devices. We are running React Native code in a custom UIWindow where we noticed that the bounds for that UIWindow do not change. This could probably be an iOS bug?

We then proceeded to use `Dimensions.get("screen")` as screen size gets updated properly.

**Comment by gerwld** [comment]
I've also noticed this issue. Both Dimensions.get('window') and useWindowDimensions doesn't handle it properly, and as I can see it return previous values even if called multiple time after rotate is done... I found closed issue from 2016 that shows up the same problem. Does anyone know any way to handle it, maybe some custom hook?

**Comment by vicary** [comment]
@gerwld A simple custom hook is not enough. It's likely caused by a delayed orientation change event, and in turn lead to a stale state returned by `Dimensions.get('window')` and `useWindowDimensions`.

You may try building a custom Native Module that directly listens to the orientation change event.

**Comment by girlboss-energy** [comment]
+1 
This also happens in my app, it messes up the layout heavily as it is dependent on screen size

**Comment by Dylan0115** [comment]
+1

**Comment by philipheinser** [comment]
+1000

**Comment by HeavenMin** [comment]
Any update on this one? It also happens in my project in iPad.

**Comment by HeavenMin** [comment]
I've implemented a hook with “react-native-orientation-locker” for now to solve this problem, if you still have this issue, you can use this hook to solve it.
```
import { useState } from 'react';
import { useOrientationChange, PORTRAIT } from 'react-native-orientation-locker';

const useIsLandscape = () => {
  const [isLandscape, setIsLandscape] = useState(false);

  // Listen to orientation changes
  useOrientationChange((orientation) => {
    if (orientation.includes(PORTRAIT)) {
      setIsLandscape(false);
    } else {
      setIsLandscape(true);
    }
  });

  return isLandscape;
};

export default useIsLandscape;
```

**Comment by jameswilddev** [comment]
> Any update on this one? It also happens in my project in iPad.

Might be this: https://github.com/facebook/react-native/pull/46353

**Comment by vicary** [comment]
I may not be testing this in the near future, not before expo picks it up and we plan to upgrade some of our projects.

If anyone is going to testing this in the upcoming RC, please post your succesful story here so I can close this issue.

**Comment by petrbela** [comment]
A workaround seems to work by detecting a change in orientation and swapping the height/width values https://gist.github.com/petrbela/d859308b22a09b4233fd72e26f2f9725

**Comment by vishnuc** [comment]
Hi , So what is the solution ?this issue is open from 2020 and no solution ? ? @petrbela you got any method ?

**Comment by vishnuc** [comment]
hello any solution ?

**Comment by gregbrinker** [comment]
If anyone is experiencing this, here's the patch my team used for react-native 0.76.5

```
diff --git a/node_modules/react-native/React/CoreModules/RCTDeviceInfo.mm b/node_modules/react-native/React/CoreModules/RCTDeviceInfo.mm
index 454a325..018b2f3 100644
--- a/node_modules/react-native/React/CoreModules/RCTDeviceInfo.mm
+++ b/node_modules/react-native/React/CoreModules/RCTDeviceInfo.mm
@@ -54,6 +54,11 @@ - (void)initialize

   _currentInterfaceDimensions = [self _exportedDimensions];

+    [[NSNotificationCenter defaultCenter] addObserver:self
+                                             selector:@selector(interfaceOrientationDidChange)
+                                                 name:UIApplicationDidChangeStatusBarOrientationNotification
+                                               object:nil];
+
   [[NSNotificationCenter defaultCenter] addObserver:self
                                            selector:@selector(interfaceOrientationDidChange)
                                                name:UIApplicationDidBecomeActiveNotification
```

`UIApplicationDidChangeStatusBarOrientationNotification` is deprecated on iOS, but in the meantime, this worked

**Comment by vicary** [comment]
The alternative of the deprecated `UIApplicationDidChangeStatusBarOrientationNotification` is to override `UIViewController/viewWillTransition(to:with:)`, but rewriting `RCTDeviceInfo` may means dropping support on some older versions of iOS.

Without diving into how React Native's support matrix works, I would assume a deprecated feature is better than a broken feature.

@gregbrinker Do you think it's a good idea to open a PR and add this back?

**Comment by gregbrinker** [comment]
@vicary I'm not quite sure what the best course of action is. I'd be interested to hear thoughts from someone that works more closely with the React Native ecosystem

**Comment by AlejandroRM-DEV** [comment]
I ended replacing it with useSafeAreaFrame

**Comment by vishnuc** [comment]
I am using expo Expo ScreenOrientation , if landscape i check if width > height else i swap it. works good so far in emulators and real devices.

@AlejandroRM-DEV btw where is documentation of useSafeAreaFrame and how did u solve it with that

**Comment by AlejandroRM-DEV** [comment]
https://appandflow.github.io/react-native-safe-area-context/
const { width, height } = useSafeAreaFrame() instead of  const { width, height } = useWindowDimensions()


For me, useWindowDimensions had a delay after some rotations showing me landscape when changing to portrait.

**Comment by ipekorken** [comment]
> https://appandflow.github.io/react-native-safe-area-context/ const { width, height } = useSafeAreaFrame() instead of const { width, height } = useWindowDimensions()
> 
> For me, useWindowDimensions had a delay after some rotations showing me landscape when changing to portrait.

It's work for me, thank you!

Example:
import React from 'react';
import {View, Text, useWindowDimensions} from 'react-native';
import {useSafeAreaFrame} from 'react-native-safe-area-context';

const HomeScreen = () => {
  const width1 = useWindowDimensions().width;
  const height1 = useWindowDimensions().height;

  const width2 = useSafeAreaFrame().width;
  const height2 = useSafeAreaFrame().height;

  console.log('width1 => ', width1);
  console.log('height1 => ', height1);

  console.log('width2 => ', width2);
  console.log('height2 => ', height2);

  return (
    <View style={{backgroundColor: 'white', paddingTop: 100, flex: 1}}>
      <Text>width1: {width1}</Text>
      <Text>height1: {height1}</Text>

      <Text>width1: {width2}</Text>
      <Text>height1: {height2}</Text>
    </View>
  );
};

export default HomeScreen;

![Image](https://github.com/user-attachments/assets/6b07de8c-561a-45d9-b7d4-0085f877c21b)

**Comment by liestig** [comment]
> useSafeAreaFrame()

You rock on this one

**Comment by liestig** [comment]
> https://appandflow.github.io/react-native-safe-area-context/ const { width, height } = useSafeAreaFrame() instead of const { width, height } = useWindowDimensions()
> 
> For me, useWindowDimensions had a delay after some rotations showing me landscape when changing to portrait.

You rock on this one, thank you!

**Comment by jgo80** [comment]
> https://appandflow.github.io/react-native-safe-area-context/ const { width, height } = useSafeAreaFrame() instead of const { width, height } = useWindowDimensions()
> 
> For me, useWindowDimensions had a delay after some rotations showing me landscape when changing to portrait.

Unfortunately this does not work well with React Native Web, so no option on cross platform Apps.

**Comment by petrbela** [comment]
> > https://appandflow.github.io/react-native-safe-area-context/ const { width, height } = useSafeAreaFrame() instead of const { width, height } = useWindowDimensions()
> > For me, useWindowDimensions had a delay after some rotations showing me landscape when changing to portrait.
> 
> Unfortunately this does not work well with React Native Web, so no option on cross platform Apps.

For web you can just add a .web.ts override with the original useWindowDimensions.

But the solution I've finally landed on, and the only one that works on ARM Mac builds for me ("Mac - Designed for iPad"), is adding an invisible View in the root and measuring its size, like this:

```ts
import { useCallback } from 'react'
import { LayoutChangeEvent, StyleSheet, View } from 'react-native'

import { create } from 'zustand'

interface DimensionsStore {
  width: number
  height: number
  setDimensions: (dimensions: { width: number; height: number }) => void
}

export const useDimensionsStore = create<DimensionsStore>((set) => ({
  width: 0,
  height: 0,
  setDimensions: ({ width, height }) => set({ width, height }),
}))

export function DimensionsMeasurer() {
  const { setDimensions } = useDimensionsStore()

  // https://github.com/facebook/react-native/issues/36118#issuecomment-1500981629
  const handleLayout = useCallback(
    (event: LayoutChangeEvent) => {
      setDimensions(event.nativeEvent.layout)
    },
    [setDimensions],
  )

  return <View onLayout={handleLayout} style={StyleSheet.absoluteFill} />
}
```

**Comment by jgo80** [comment]
Thanks, @petrbela this is in deed the only reliable working solution across all platforms atm. 🙏 Glad I'm working with zustand just like you.

**Comment by vishnuc** [comment]
> > > https://appandflow.github.io/react-native-safe-area-context/ const { width, height } = useSafeAreaFrame() instead of const { width, height } = useWindowDimensions()
> > > For me, useWindowDimensions had a delay after some rotations showing me landscape when changing to portrait.
> > 
> > 
> > Unfortunately this does not work well with React Native Web, so no option on cross platform Apps.
> 
> For web you can just add a .web.ts override with the original useWindowDimensions.
> 
> But the solution I've finally landed on, and the only one that works on ARM Mac builds for me ("Mac - Designed for iPad"), is adding an invisible View in the root and measuring its size, like this:
> 
> import { useCallback } from 'react'
> import { LayoutChangeEvent, StyleSheet, View } from 'react-native'
> 
> import { create } from 'zustand'
> 
> interface DimensionsStore {
>   width: number
>   height: number
>   setDimensions: (dimensions: { width: number; height: number }) => void
> }
> 
> export const useDimensionsStore = create<DimensionsStore>((set) => ({
>   width: 0,
>   height: 0,
>   setDimensions: ({ width, height }) => set({ width, height }),
> }))
> 
> export function DimensionsMeasurer() {
>   const { setDimensions } = useDimensionsStore()
> 
>   // https://github.com/facebook/react-native/issues/36118#issuecomment-1500981629
>   const handleLayout = useCallback(
>     (event: LayoutChangeEvent) => {
>       setDimensions(event.nativeEvent.layout)
>     },
>     [setDimensions],
>   )
> 
>   return <View onLayout={handleLayout} style={StyleSheet.absoluteFill} />
> }

hey can u share web.ts file..

**Comment by petrbela** [comment]
```ts
// useDimensions.ts (used by web)
import { useWindowDimensions } from 'react-native'
export const useDimensions = useWindowDimensions
```

```ts
// useDimensions.native.ts
import { useDimensionsStore } from '~/stores/dimensions'

export function useDimensions() {
  return useDimensionsStore()
}
```

**Comment by Shaninnik** [comment]
<s>Will this issue be ever fixed in RN itself? This is affecting many libraries out there that are using `useWindowDimensions`. Sure, `useSafeAreaFrame` works for our own code, but we can't patch every lib out there. Either RN should provide correctly working version or not provide any at all.</s>

Apologies, I tried to create a minimal repro with React-Native 0.81.4 and it appears to be working just fine so it seems like this issue has been fixed?

**Comment by Relax594** [comment]
It's not fixed. I can still easily reproduce it on iPad with React-Native 0.81.6.
