### ISSUE TITLE
Missing request token for request: <NSURLRequest: 0x60000253e5a0> { URL: file://

### ISSUE THREAD

**Issue by sagarlava** [facebook/react-native#29364]
## Description
I just upgraded to RN 0.63.0 and all fine, but only for upload using axios, i get 

```
Missing request token for request: <NSURLRequest: 0x60000253e5a0> { URL: file:
```

![image](https://user-images.githubusercontent.com/27483482/87408394-1e034400-c5e3-11ea-9d53-9bacdccb67b6.png)

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 163.19 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Here is my code snippet and that gives me error

```
  const cleanURL = body.imageData.uri.replace("file://", "");
  const data = new FormData();
  let fileName = body.imageData.fileName ? body.imageData.fileName : moment().unix()+'.jpg'
  data.append('file', {
    uri: cleanURL,
    name: fileName,
    type: body.imageData.type
  });
  data.append('fileName', fileName)
  return axiosclient.post(
    '/upload,
    data,
    {
      headers: {
        "content-type": "multipart/form-data"
      }
    }
  ).then(res => {
   
  }).catch(err => {
    
  })
```

## Expected Results
Should upload file, it was fine in 0.62.2

**Comment by PaitoAnderson** [comment]
Same issue with `fetch` for me when updating to 0.63.0.

**Comment by ramacatur** [comment]
Same issue with axios after update to 0.63.0

**Comment by YannDeck** [comment]
The issue is still here with 0.63.1, 100% reproducible on iOS. (tested with fetch and axios)
The problem seems to come from `loadImageWithURLRequest` as mentioned [here](https://github.com/facebook/react-native/issues/29021#issuecomment-657540950)

**Comment by struct78** [comment]
Here is a minimal repo that demonstrates this error. Choose a file from the camera roll and then try to retrieve that using fetch.

https://github.com/struct78/react-native-0.63.1-missing-request-token

**Comment by helderburato** [comment]
Same issue with axios after update to `0.63.1`.

**Comment by caiangums** [comment]
Hey, I caught up @helderburato and we tried some approaches. This seems an error not much related to `token`, even the error sending this message.

**TL;DR:** We do not manage to correct the issue. But we made some research, discovered something about it, created assumptions but for now, we are downgrading the version of our RN lib to 0.61.4. Here is what we managed to discover! 😄 

Some steps to catch what we accomplish:
- Added some logs at `RCTNetworkTask.mm`, method `start()`:
```objc
- (void)start
{
  if (_status != RCTNetworkTaskPending) {
    RCTLogError(@"RCTNetworkTask was already started or completed");
    return;
  }

  if (_requestToken == nil) {
    id token = [_handler sendRequest:_request withDelegate:self];

    RCTLog(@"token %@", token); // <- here
    RCTLog(@"_handler %@", _handler); // <- here
    if ([self validateRequestToken:token]) {
      _selfReference = self;
      _status = RCTNetworkTaskInProgress;
    }
  }
}
```

- Added some logs at `RCTNetworkTask.mm`, method `validateRequestToken()`:
```objc
- (BOOL)validateRequestToken:(id)requestToken
{
  BOOL valid = YES;
  if (_requestToken == nil) {
    if (requestToken == nil) {
      if (RCT_DEBUG) {
        RCTLog(@"error _handler %@", _handler); // <- here
        RCTLog(@"error requestToken %@", requestToken); // <- here
        RCTLogError(@"Missing request token for request: %@", _request);
      }
      valid = NO;
    }
    _requestToken = requestToken;
  } else if (![requestToken isEqual:_requestToken]) {
    if (RCT_DEBUG) {
      RCTLogError(@"Unrecognized request token: %@ expected: %@", requestToken, _requestToken);
    }
    valid = NO;
  }
  /* ... */
}
```

Then I identified an issue with `RCTImageLoader` on calling the method `sendRequest()`. Then I went across the implementation inside the `RCTImageLoader.mm` file and added some logs inside of it. After discussing with an iOS developer friend (@Cherobin) that knows how Obj-C works, we created the assumption of the problem being the callback from `requestToken` not being fulfilled resulting in token being `nil` (`null`). This maybe happens because of how quick the code executes in comparison of how slow the callback is executed based on image size. We are reducing the image size with a JS lib before sending requests, so this happens with even a small size of images.

We tried to use a `Semaphore` but it seems not to resolve the issue. At the file `RCTImageLoader` we created some logs at `sendRequest()` and the following code is what we produced:

```objc
- (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
{
  // create the semaphore
  dispatch_semaphore_t sema = dispatch_semaphore_create(0);

  __block RCTImageLoaderCancellationBlock requestToken;
  requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
    RCTLog(@"error %@", error); // <- log here
    if (error) {
      [delegate URLRequest:requestToken didCompleteWithError:error];
      return;
    }

    NSString *mimeType = nil;
    NSData *imageData = nil;
    if (RCTImageHasAlpha(image.CGImage)) {
      mimeType = @"image/png";
      imageData = UIImagePNGRepresentation(image);
    } else {
      mimeType = @"image/jpeg";
      imageData = UIImageJPEGRepresentation(image, 1.0);
    }
    RCTLog(@"mimeType %@", mimeType); // <- log here
    RCTLog(@"imageData %@", imageData); // <- log here

    NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
                                                        MIMEType:mimeType
                                           expectedContentLength:imageData.length
                                                textEncodingName:nil];
    RCTLog(@"response %@", response); // <- log here

    [delegate URLRequest:requestToken didReceiveResponse:response];
    [delegate URLRequest:requestToken didReceiveData:imageData];
    [delegate URLRequest:requestToken didCompleteWithError:nil];
    RCTLog(@"delegate %@", delegate); // <- log here

    // Release the semaphore
    dispatch_semaphore_signal(sema);
  }];

  // Here we lock until the semaphore release
  if (![NSThread isMainThread]) {
      dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);
  } else {
      while (dispatch_semaphore_wait(sema, DISPATCH_TIME_NOW)) {
          [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:0]];
      }
  }

  RCTLog(@"RCTImageLoader requestToken %@", requestToken); // <- log here
  return requestToken;
}
```

Hope that helps someone! 😄

**Comment by uusa35** [comment]
![Simulator Screen Shot - iPhone Xʀ - 2020-07-20 at 01 25 28](https://user-images.githubusercontent.com/3815504/87886729-14853c00-ca28-11ea-9aec-dc5a9ffa04f5.png)

i have the same issue RN 0.63.1 
any updates ? !

**Comment by uusa35** [comment]
fixed the error 

before i was fetching image.path and it was working just fine.

now u have to pass the sourceURL as the following 

<img width="1076" alt="Screen Shot 2020-07-21 at 8 12 17 AM" src="https://user-images.githubusercontent.com/3815504/88015509-07e90c80-cb2a-11ea-8b4a-a4ff7fbbd755.png">

**Comment by jamesshaw49** [comment]
> fixed the error
> 
> before i was fetching image.path and it was working just fine.
> 
> now u have to pass the sourceURL as the following
> 
> <img alt="Screen Shot 2020-07-21 at 8 12 17 AM" width="1076" src="https://user-images.githubusercontent.com/3815504/88015509-07e90c80-cb2a-11ea-8b4a-a4ff7fbbd755.png">

This doesn't seem to have fixed it for me. Problem is only present on the simulator though, no issue on an actual device.

**Comment by caiangums** [comment]
> fixed the error
> 
> before i was fetching image.path and it was working just fine.
> 
> now u have to pass the sourceURL as the following
> 
> <img alt="Screen Shot 2020-07-21 at 8 12 17 AM" width="1076" src="https://user-images.githubusercontent.com/3815504/88015509-07e90c80-cb2a-11ea-8b4a-a4ff7fbbd755.png">

Hey! Can you tell more about how you did it and deliver an example to reproduce it?

**Comment by jamesshaw49** [comment]
> > fixed the error
> > before i was fetching image.path and it was working just fine.
> > now u have to pass the sourceURL as the following
> > <img alt="Screen Shot 2020-07-21 at 8 12 17 AM" width="1076" src="https://user-images.githubusercontent.com/3815504/88015509-07e90c80-cb2a-11ea-8b4a-a4ff7fbbd755.png">
> 
> Hey! Can you tell more about how you did it and deliver an example to reproduce it?

Hi @caiangums, I actually thought it may be related to the library I was using, so I posted more detail about this issue on their repo. Check it out here: https://github.com/ivpusic/react-native-image-crop-picker/issues/1348

Something interesting and related to @uusa35 comment, is that the sourceURL is actually null for the image selected. 

Finally, I remember a strange bug I once had with Android when posting images to the server. It turned out to be related to the Flipper version (https://github.com/facebook/react-native/issues/28551). I tried disabling Flipper in RN 63, but this made no difference. I thought I would mention it incase those more knowledgable about RN could find a link between the two issues.

**Comment by anthony1110** [comment]
I also have same issue. I use hack for this https://github.com/facebook/react-native/issues/29021#issuecomment-662196480.

**Comment by caiangums** [comment]
Hi @anthony1110! Thanks for mentioning it.

I think your solution is a bad approach. Instead of correcting the issue, you avoided an error and considered valid.

**Comment by anthony1110** [comment]
@caiangums , yup, that hack is a bad method, just a temporary hack to make it working. Still require react-native developer to provide a real fix for this.

**Comment by caiangums** [comment]
Good point @anthony1110! I think we all made some progress with our knowledge and maybe when someone from the RN team comes here they will have some ground on where to start.

btw does your "hack" generated side-effects? Did you notice something? 🤔

**Comment by uusa35** [comment]
> > fixed the error
> > before i was fetching image.path and it was working just fine.
> > now u have to pass the sourceURL as the following
> > <img alt="Screen Shot 2020-07-21 at 8 12 17 AM" width="1076" src="https://user-images.githubusercontent.com/3815504/88015509-07e90c80-cb2a-11ea-8b4a-a4ff7fbbd755.png">
> 
> Hey! Can you tell more about how you did it and deliver an example to reproduce it?


find the comment below
https://github.com/facebook/react-native/issues/29364#issuecomment-660718932

also i can confirm that my solution worked on ios but not on android. so weird

**Comment by SocialBrothersDEV** [comment]
Same issue here on 0.63

**Comment by anthony1110** [comment]
> Good point @anthony1110! I think we all made some progress with our knowledge and maybe when someone from the RN team comes here they will have some ground on where to start.
> 
> btw does your "hack" generated side-effects? Did you notice something? 🤔

@caiangums , so far so good from my application to upload and download image with the hack. Again, it is still bad hack, still need to wait react-native developer to fix it. Also, I believe upgrade Flipper version will fix the issue but I am not sure how to upgrade Flipper version in IOS/podfile.

**Comment by caiangums** [comment]
> > > fixed the error
> > > before i was fetching image.path and it was working just fine.
> > > now u have to pass the sourceURL as the following
> > > <img alt="Screen Shot 2020-07-21 at 8 12 17 AM" width="1076" src="https://user-images.githubusercontent.com/3815504/88015509-07e90c80-cb2a-11ea-8b4a-a4ff7fbbd755.png">
> > 
> > 
> > Hey! Can you tell more about how you did it and deliver an example to reproduce it?
> 
> find the comment below
> [#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-660718932)
> 
> also i can confirm that my solution worked on ios but not on android. so weird

Hey @uusa35, thanks for your reply. My request is for an example to reproduce. As far as I can see, your comment just has some prints from your code and it was traced that the issue may be related to some bug inside the Objective-C RN lib.

Just to be clear:
- _"Works on my machine"_ is not a good reply in any case (I tested your solution on my code and still not work)
- "An example to reproduce it" by far is not prints from your code. @struct78 [gave an example with a repo](https://github.com/struct78/react-native-0.63.1-missing-request-token) and this is a real example to reproduce it
- The thread has some other information about it. If possible, maybe you can check it out. As an example, @anthony1110 found a way to avoid the issue modifying the RN source code directly and it worked but he already said this is a "hack" and is better to wait until someone from RN team(or anyone with more knowledge in Obj-C background) catch-up and fix the issue

**Comment by ajanauskas** [comment]
The main issue like someone mentioned is within `RCTImageLoader.mm` implementation:

```objective-c
- (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
{
  __block RCTImageLoaderCancellationBlock requestToken;
  requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
    if (error) {
      [delegate URLRequest:requestToken didCompleteWithError:error];
      return;
    }

    NSString *mimeType = nil;
    NSData *imageData = nil;
    if (RCTImageHasAlpha(image.CGImage)) {
      mimeType = @"image/png";
      imageData = UIImagePNGRepresentation(image);
    } else {
      mimeType = @"image/jpeg";
      imageData = UIImageJPEGRepresentation(image, 1.0);
    }

    NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
                                                        MIMEType:mimeType
                                           expectedContentLength:imageData.length
                                                textEncodingName:nil];

    [delegate URLRequest:requestToken didReceiveResponse:response];
    [delegate URLRequest:requestToken didReceiveData:imageData];
    [delegate URLRequest:requestToken didCompleteWithError:nil];
  }];

  return requestToken;
}
```

Error is thrown out because `requestToken` is `nil`. Like someone else has pointed out it is nil because `completionBlock` executes before `requestToken` is initialised. It happens because some image loader is performing task synchronously.

I've managed to fix issue for my project by reverting this commit: https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c

**Comment by dan-lee** [comment]
@ajanauskas Looks promising, but unfortunately it didn't change anything for me.

<details>
<summary>My patch looks like this</summary>

```diff
diff --git a/node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm b/node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm
index 8669ad3..7a55058 100644
--- a/node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm
+++ b/node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm
@@ -49,19 +49,28 @@ - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                  partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                   completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
 {
-  UIImage *image = RCTImageFromLocalAssetURL(imageURL);
-  if (image) {
-    if (progressHandler) {
-      progressHandler(1, 1);
+  __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
+  RCTExecuteOnMainQueue(^{
+    if (cancelled->load()) {
+      return;
     }
-    completionHandler(nil, image);
-  } else {
-    NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
-    RCTLogWarn(@"%@", message);
-    completionHandler(RCTErrorWithMessage(message), nil);
-  }

-  return nil;
+    UIImage *image = RCTImageFromLocalAssetURL(imageURL);
+    if (image) {
+      if (progressHandler) {
+        progressHandler(1, 1);
+      }
+      completionHandler(nil, image);
+    } else {
+      NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
+      RCTLogWarn(@"%@", message);
+      completionHandler(RCTErrorWithMessage(message), nil);
+    }
+  });
+
+  return ^{
+    cancelled->store(true);
+  };
 }

 @end

```
</details>

Is that all that needs to be done?

**Comment by anthony1110** [comment]
I tested @ajanauskas fix and it is working. Thanks @ajanauskas !

**Comment by keithhackbarth** [comment]
Worth noting that the above fix only works on iOS and similar issue appears to exist on Android

**Comment by awinograd** [comment]
@keithhackbarth The original issue and error information added to this issue seems pretty iOS specific. If you're seeing something similar on android i'd suggest opening a separate issue.

**Comment by keithhackbarth** [comment]
Sorry @awinograd . Looks like a more generic discussion is happening on #29021 I'll move my comment over there.

**Comment by joaoschaab** [comment]
any update on this ?

**Comment by sammy-SC** [comment]
> Here is a minimal repo that demonstrates this error. Choose a file from the camera roll and then try to retrieve that using fetch.
> 
> https://github.com/struct78/react-native-0.63.1-missing-request-token

@struct78 thanks for the repro!

-----

# Update:

I've identified the issue, in https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339 I've broken the invariant that every `[RCTImageURLLoader loadImageForURL]` returns a request token. 

Fix is under review.

**Comment by osikes** [comment]
Seems weird this hasn't been resolved and released yet. No one using 0.63 can build an app that uploads files until then.

**Comment by mrprkr** [comment]
@osikes Yep, this is actually pretty ridiculous. The patch doesn't seem to work on my CI either and couldn't roll back to 62 without breaking changes. Now stuck not able to release an app version until an update is available.

**Comment by ssuchanowski** [comment]
@mrprkr do you know which version was last to work?

**Comment by fikar46** [comment]
> The main issue like someone mentioned is within `RCTImageLoader.mm` implementation:
> 
> ```objc
> - (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
> {
>   __block RCTImageLoaderCancellationBlock requestToken;
>   requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
>     if (error) {
>       [delegate URLRequest:requestToken didCompleteWithError:error];
>       return;
>     }
> 
>     NSString *mimeType = nil;
>     NSData *imageData = nil;
>     if (RCTImageHasAlpha(image.CGImage)) {
>       mimeType = @"image/png";
>       imageData = UIImagePNGRepresentation(image);
>     } else {
>       mimeType = @"image/jpeg";
>       imageData = UIImageJPEGRepresentation(image, 1.0);
>     }
> 
>     NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
>                                                         MIMEType:mimeType
>                                            expectedContentLength:imageData.length
>                                                 textEncodingName:nil];
> 
>     [delegate URLRequest:requestToken didReceiveResponse:response];
>     [delegate URLRequest:requestToken didReceiveData:imageData];
>     [delegate URLRequest:requestToken didCompleteWithError:nil];
>   }];
> 
>   return requestToken;
> }
> ```
> 
> Error is thrown out because `requestToken` is `nil`. Like someone else has pointed out it is nil because `completionBlock` executes before `requestToken` is initialised. It happens because some image loader is performing task synchronously.
> 
> I've managed to fix issue for my project by reverting this commit: [3198009#diff-9a034658197479288c4d346a0eb4d98c](https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c)

thank you bro, this is very work for me, rather than waiting for an update from react native that is very long

**Comment by mrprkr** [comment]
> @mrprkr do you know which version was last to work?

0.62 worked with no issues

**Comment by osikes** [comment]
Reverting the commit https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c does work thanks 😊 . However for people actually with jobs in RN they likely have CI process, so now that has to get modified as well... because this apparently great framework can't offer basic functionality like upload a profile image or a file.

**Comment by mrprkr** [comment]
> However for people actually with jobs in RN they likely have CI process.

This is exactly the issue, I have a TestFlight pipeline setup with beta users able to receive nightly builds. I'm not sure how I would go about specifying a particular commit in `package.json` for the CI to use.

**Comment by Vednus** [comment]
You could use `patch-package` to run as a post install step. That's what I've done

**Comment by joaoschaab** [comment]
> > However for people actually with jobs in RN they likely have CI process.
> 
> This is exactly the issue, I have a TestFlight pipeline setup with beta users able to receive nightly builds. I'm not sure how I would go about specifying a particular commit in `package.json` for the CI to use.

Downgrade is the way to go

**Comment by weblancaster** [comment]
Like @joaoschaab and others mentioned. Downgrading is probably the best option but depending on how much dependencies your project has you might have issues.

In my case, going from 0.63.0 to 0.62.0 had a couple of issues that would take too much effort/time to fix them but going from 63 to 0.61.5 I had to do very little changes.

**Comment by mrprkr** [comment]
Thanks all, have downgraded to 0.62.2 (and jumped through hoops to get pods working again!). Everything seems to be working on this version.

**Comment by yewenxiang23** [comment]
My React - Native version is 0.63.2, And I found that this problem occurs when the interface for uploading images is secondary interface, but it doesn't exist when it is the initial route

**Comment by HarshaUdaraSandaru** [comment]
Seem to still has the error in React-Native version 0.63.2.

**Comment by luskin** [comment]
For anyone else having this issue, as a temporary fix update your local file: `node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm` and replace the Obj-C method `shouldCacheLoadedImages` with the following

```objc
- (BOOL)shouldCacheLoadedImages
{
  // UIImage imageNamed handles the caching automatically so we don't want
  // to add it to the image cache.
  return NO;
}

 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                               size:(CGSize)size
                                              scale:(CGFloat)scale
                                         resizeMode:(RCTResizeMode)resizeMode
                                    progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                                 partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                  completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
{
__block auto cancelled = std::make_shared<std::atomic<bool>>(false);
  RCTExecuteOnMainQueue(^{
    if (cancelled->load()) {
      return;
    }
     UIImage *image = RCTImageFromLocalAssetURL(imageURL);
    if (image) {
      if (progressHandler) {
        progressHandler(1, 1);
      }
      completionHandler(nil, image);
    } else {
      NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
      RCTLogWarn(@"%@", message);
      completionHandler(RCTErrorWithMessage(message), nil);
    }
  });

  return ^{
    cancelled->store(true);
  };
}
```

**Comment by yewenxiang23** [comment]
@luskin Thank you very much. That solved my problem

**Comment by yewenxiang23** [comment]
Now I have encountered a new problem. The first upload is ok and the picture is displayed normally. After that, if I want to modify the picture, the second upload will have the same error

**Comment by paddlefish** [comment]
For those encountering this issue, I think I found a fix and have submitted a PR: https://github.com/facebook/react-native/pull/29595  The minimal line is to initialize `requestToken` by addint `= ^{};` to `sendRequest:withDelegate:` in RCTImageLoader.mm on line 1044 approximately.

**Comment by barunprasad** [comment]
Started facing this issue when we upgraded our RN project from 0.61.5 to 0.63.2. Hoping to get this issue resolved soon as this is a blocker.

**Comment by CDAracena** [comment]
Facing this issue after upgrading RN to 0.63.2

**Comment by ssuchanowski** [comment]
There are workarounds in this thread (eg. reverting https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c by using `patch-package`). It takes like 5 minutes to do this so for everybody with this issue please do that and let's monitor what the team is doing.

For sure if it's gonna be fixed in the next version someone will mention this here.

**Comment by sordev** [comment]
> = ^{};

this seems to be working 
just replacing line 
__block RCTImageLoaderCancellationBlock requestToken;
with 
__block RCTImageLoaderCancellationBlock requestToken = ^{};
fixed the issue.

**Comment by sordev** [comment]
> For those encountering this issue, I think I found a fix and have submitted a PR: #29595 The minimal line is to initialize `requestToken` by addint `= ^{};` to `sendRequest:withDelegate:` in RCTImageLoader.mm on line 1044 approximately.

this seems to be working
just replacing line
__block RCTImageLoaderCancellationBlock requestToken;
with
__block RCTImageLoaderCancellationBlock requestToken = ^{};
fixed the issue.

**Comment by AndriyF** [comment]
another possible option here is to change `validateRequestToken` method, see https://github.com/facebook/react-native/commit/ffc90c7f92e63e1a53ed107833e3deed492ab435#diff-479bdaeb9bb8ca6ea323675b6b479fc6
`patch-package` can be used for that as @Vednus  and @ssuchanowski suggested

**Comment by Monojitgit** [comment]
Seem to still has the error in React-Native version 0.63.2. Plz help me...
ExceptionsManager.js:179 Missing request token for request: <NSURLRequest: 0x6000019b3580> { URL: file:///Users/...../...../Data/Application/F880FB79-B4FB-40BB-9F34-2FAE72753A07/Documents/images/E4CC6AA6-895D-426C-97A6-B65EFE3360AB.jpg }

ExceptionsManager.js:179 Error processing request body: Error Domain=RCTErrorDomain Code=0 "Invalid request token." UserInfo={NSLocalizedDescription=Invalid request token.}

**Comment by ajanauskas** [comment]
@Monojitgit read the whole thread, it already provides couple of workarounds/solutions. (eg. reverting 3198009 by using patch-package)

**Comment by SYNTAG** [comment]
None of these patching solutions seem to work on the latest version of React Native `0.63.2`

**Comment by harrigee** [comment]
> None of these patching solutions seem to work on the latest version of React Native `0.63.2`

For is https://github.com/facebook/react-native/issues/29364#issuecomment-670150318 did the trick.

**Comment by SYNTAG** [comment]
> > None of these patching solutions seem to work on the latest version of React Native `0.63.2`
> 
> For us [#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-670150318) did the trick. (RN 0.63.2)

Sorry, I should've been more clear. The token error goes away with that patch but still can't upload the actual image. Might be related to Flipper/Network issues with the latest version of React Native.

Also, I found this 2 liner patch that gets rid of the missing request token error instead of doing `RCTLocalAssetImageLoader.mm`.

**Comment by caiangums** [comment]
> > > None of these patching solutions seem to work on the latest version of React Native `0.63.2`
> > 
> > 
> > For us [#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-670150318) did the trick. (RN 0.63.2)
> 
> Sorry, I should've been more clear. The token error goes away with that patch but still can't upload the actual image. Might be related to Flipper/Network issues with the latest version of React Native (#29493)
> 
> Also, I found this 2 liner patch that gets rid of the missing request token error instead of changing `RCTLocalAssetImageLoader.mm` here: [#29021 (comment)](https://github.com/facebook/react-native/issues/29021#issuecomment-662231934)

I read on another Issue about updating the Flipper version to lastest and that solve the issue with it. Just check if it's your case! :smile:

**Comment by SYNTAG** [comment]
> > > > None of these patching solutions seem to work on the latest version of React Native `0.63.2`
> > > 
> > > 
> > > For us [#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-670150318) did the trick. (RN 0.63.2)
> > 
> > 
> > Sorry, I should've been more clear. The token error goes away with that patch but still can't upload the actual image. Might be related to Flipper/Network issues with the latest version of React Native (#29493)
> > Also, I found this 2 liner patch that gets rid of the missing request token error instead of changing `RCTLocalAssetImageLoader.mm` here: [#29021 (comment)](https://github.com/facebook/react-native/issues/29021#issuecomment-662231934)
> 
> I read on another Issue about updating the Flipper version to lastest and that solve the issue with it. Just check if it's your case! 😄

@caiangums I can confirm that in my case updating Flipper to `0.52.1` allowed me to upload but on Android only. I am experiencing this uploading issue on iOS. Is there a way to update Flipper's version on iOS somehow? On React Native `0.63.2` they removed the FLIPPER_VERSION option in the Podfile. Perhaps it will be the same fix.

**Comment by santhoshbanda** [comment]
facing the same issue. none of the "fixes" working for me :(

**Comment by FabrizioCaldarelli** [comment]
I temporary fixed using `rn-fetch-blob`, but the issue is present in 0.63.2 version and I didn't want to patch node_modules react-native images library.

**Comment by safaiyeh** [comment]
Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:

iOS: Revert a PR, requires modifying node_modules: https://github.com/facebook/react-native/issues/29364#issuecomment-671565181
Android: Upgrade Flipper version https://github.com/facebook/react-native/issues/28551#issuecomment-674351386

**Comment by safaiyeh** [comment]
Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:

iOS: Revert a PR, requires modifying node_modules: https://github.com/facebook/react-native/issues/29364#issuecomment-671565181, PR submitted here for the fix: https://github.com/facebook/react-native/pull/29595

Android: Upgrade Flipper version https://github.com/facebook/react-native/issues/28551#issuecomment-674351386

**Comment by tobilastik** [comment]
> __block RCTImageLoaderCancellationBlock requestToken = ^{};

I can confirm this worked for me, but wouldn't it change when I kind of reload the app?

**Comment by paddlefish** [comment]
> > __block RCTImageLoaderCancellationBlock requestToken = ^{};
> 
> I can confirm this worked for me, but wouldn't it change when I kind of reload the app?

I don’t think this would affect reload. In this case, “requestToken” is associated with this particular request.  After reload a new image load would get its own, new requestToken. A *static* variable could hold state across reloads, but fortunately this variable is not static.

**Comment by matheus-rn** [comment]
To temporarily correct this problem in CI, I added a post-installation to package.json, to run a script that replaces the RCTLocalAssetImageLoader.mm file in the node_modules folder. The file used for content replacement is the file quoted at https://github.com/facebook/react-native/issues/29364#issuecomment-670150318. In the file fix_ios.sh it has the command: 

cat config/fix_ios/RCTLocalAssetImageLoader.mm > node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm

in package.json postinstall looks like this:

...
"scripts": {
    "postinstall": "sh ./fix_ios.sh",
...

**Comment by paddlefish** [comment]
Check out patch-package.  It's a very easy way to apply patches and when you update the component, it reminds you to update the patch -- or if the bugs are fixed you can just delete the patch.

**Comment by SYNTAG** [comment]
> Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:
> 
> iOS: Revert a PR, requires modifying node_modules: [#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-671565181), PR submitted here for the fix: #29595
> 
> Android: Upgrade Flipper version [#28551 (comment)](https://github.com/facebook/react-native/issues/28551#issuecomment-674351386)

Can confirm that these issues worked for me. Earlier I said it didn't work on iOS but I eventually found out why. Posting here in case anyone else has the same issue.

> Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:
> 
> iOS: Revert a PR, requires modifying node_modules: [#29364 (comment)](https://github.com/facebook/react-native/issues/29364#issuecomment-671565181), PR submitted here for the fix: #29595
> 
> Android: Upgrade Flipper version [#28551 (comment)](https://github.com/facebook/react-native/issues/28551#issuecomment-674351386)

I can confirm that both of these solutions worked for me. Earlier I said it didn't work on iOS but I eventually found out why. Posting here in case anyone else has the same issue on React Native 0.63.2 (after making the above changes). Apparently my issue was that `react-native-image-picker` was not grabbing the file name on iOS. This didn't happen on earlier versions, but apparently that's what was preventing upload for me. For more context, I am using Node JS and Multer on my backend. Hope this helps someone.

**Comment by tobilastik** [comment]
> > > __block RCTImageLoaderCancellationBlock requestToken = ^{};
> > 
> > 
> > I can confirm this worked for me, but wouldn't it change when I kind of reload the app?
> 
> I don’t think this would affect reload. In this case, “requestToken” is associated with this particular request. After reload a new image load would get its own, new requestToken. A _static_ variable could hold state across reloads, but fortunately this variable is not static.

What I was saying just happened, I made the change in my code yesterday, when I close the editor and open it back today, the "= ^{};" I added yesterday is no more there I have to add it again, that means it will always happen that way. Any solution to that?

**Comment by paddlefish** [comment]
Look at https://www.npmjs.com/package/patch-package.  That's how I apply custom code fixes to node modules.

**Comment by tobilastik** [comment]
okay, thanks

**Comment by safaiyeh** [comment]
Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:

iOS: Revert a PR, requires modifying node_modules: #29364 (comment), PR submitted here for the fix: #29595

Android: Upgrade Flipper version #28551 (comment), PR raised #29787

**Comment by FabrizioCaldarelli** [comment]
> Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:

Using `rn-fetch-blob` does not require any fixes.

**Comment by yenda** [comment]
There is already a working fix and PR that has been sitting for weeks

**Comment by FabrizioCaldarelli** [comment]
> There is already a working fix and PR that has been sitting for weeks

In my opinion, fixing a library in node_modules is a bad solution and it should avoid as much as possible and it should be only the last chance to compile and launch the application.

In all other cases, it should be used a more stable solution (in this case, rn-fetch-blob).

**Comment by SYNTAG** [comment]
> > There is already a working fix and PR that has been sitting for weeks
> 
> In my opinion, fixing a library in node_modules is a bad solution and it should avoid as much as possible and it should be only the last chance to compile and launch the application.
> 
> In all other cases, it should be used a more stable solution (in this case, rn-fetch-blob).

Under normal circumstances, I would probably agree, but [patch-package](https://www.npmjs.com/package/patch-package) is a no brainer with how easy it is to add, plus it is a stable solution since it saves the patch script and applies it on install.

**Comment by safaiyeh** [comment]
> > Bringing together all the fixes here, hopefully we can get a fix for this merged to core soon:
> 
> Using `rn-fetch-blob` does not require any fixes.

rn-fetch-blob is external to react-native, this should not break with fetch hence the necessary fixes

**Comment by GreatAuk** [comment]
0.63.2 still exist

**Comment by Merlier** [comment]
same issue with RN 0.63 but passing through with `rn-fetch-blob`

**Comment by LcsGrz** [comment]
Will it be fixed in the next version of RN?

**Comment by jonathantroncoso82** [comment]
I had to switch to version 0.62.2 and it worked without any problems !! I tried all the options that are on the forum and nothing ... just going back to version 0.62.2.

**Comment by bohdan145** [comment]
I've changed  react-native/Libraries/Image/RCTLocalAssetImageLoader.mm and image upload is working
But i can't apply patch for react-native using patch-package 
When i do npx patch-package react-native i receive this error: 
Error: ENOENT: no such file or directory, stat '/node_modules/react-native/node_modules/metro-source-map/node_modules/.bin/metro-symbolicate'

I tried to exclude node_modules dir in react-native, but it didn't help 
Any help ??

**Comment by vinaygoyal20** [comment]
I was able to resolve this in two ways Either one can be used to resolve but both require to do some changes in node_modules/react-native/Libraries/Image
A) https://github.com/facebook/react-native/pull/29595
Replace the - (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate function in  node_modules/react-native/Libraries/Image/RCTImageLoader.mm with below
```
- (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
{
  @synchronized(self) {
    __block RCTImageLoaderCancellationBlock requestToken = ^{};
    requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
      @synchronized(self) {

        if (error) {
          [delegate URLRequest:requestToken didCompleteWithError:error];
          return;
        }

        NSString *mimeType = nil;
        NSData *imageData = nil;
        if (RCTImageHasAlpha(image.CGImage)) {
          mimeType = @"image/png";
          imageData = UIImagePNGRepresentation(image);
        } else {
          mimeType = @"image/jpeg";
          imageData = UIImageJPEGRepresentation(image, 1.0);
        }

        NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
                                                            MIMEType:mimeType
                                               expectedContentLength:imageData.length
                                                    textEncodingName:nil];

        [delegate URLRequest:requestToken didReceiveResponse:response];
        [delegate URLRequest:requestToken didReceiveData:imageData];
        [delegate URLRequest:requestToken didCompleteWithError:nil];
      }
    }];

    return requestToken;
  }
}
```


B)https://stackoverflow.com/questions/54663887/missing-request-token-for-request

Replace the function loadImageForURL in /Libraries/Image/RCTLocalAssetImageLoader.mm with the following:

 ```
- (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                           size:(CGSize)size
                                          scale:(CGFloat)scale
                                     resizeMode:(RCTResizeMode)resizeMode
                                progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                             partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                              completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
 {
   __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
   RCTExecuteOnMainQueue(^{
     if (cancelled->load()) {
       return;
     }

     UIImage *image = RCTImageFromLocalAssetURL(imageURL);
     if (image) {
       if (progressHandler) {
         progressHandler(1, 1);
       }
       completionHandler(nil, image);
     } else {
       NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
       RCTLogWarn(@"%@", message);
       completionHandler(RCTErrorWithMessage(message), nil);
     }
   });

   return ^{
     cancelled->store(true);
   };
 }

```

**Comment by faraznaqvi99** [comment]
> The main issue like someone mentioned is within `RCTImageLoader.mm` implementation:
> 
> ```objc
> - (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
> {
>   __block RCTImageLoaderCancellationBlock requestToken;
>   requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
>     if (error) {
>       [delegate URLRequest:requestToken didCompleteWithError:error];
>       return;
>     }
> 
>     NSString *mimeType = nil;
>     NSData *imageData = nil;
>     if (RCTImageHasAlpha(image.CGImage)) {
>       mimeType = @"image/png";
>       imageData = UIImagePNGRepresentation(image);
>     } else {
>       mimeType = @"image/jpeg";
>       imageData = UIImageJPEGRepresentation(image, 1.0);
>     }
> 
>     NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
>                                                         MIMEType:mimeType
>                                            expectedContentLength:imageData.length
>                                                 textEncodingName:nil];
> 
>     [delegate URLRequest:requestToken didReceiveResponse:response];
>     [delegate URLRequest:requestToken didReceiveData:imageData];
>     [delegate URLRequest:requestToken didCompleteWithError:nil];
>   }];
> 
>   return requestToken;
> }
> ```
> 
> Error is thrown out because `requestToken` is `nil`. Like someone else has pointed out it is nil because `completionBlock` executes before `requestToken` is initialised. It happens because some image loader is performing task synchronously.
> 
> I've managed to fix issue for my project by reverting this commit: [3198009#diff-9a034658197479288c4d346a0eb4d98c](https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c)

Can you please guide me about how to revert this commit? Do I have to only change the file in node modules or something else needs to be done?

**Comment by ajanauskas** [comment]
> > The main issue like someone mentioned is within `RCTImageLoader.mm` implementation:
> > ```objc
> > - (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
> > {
> >   __block RCTImageLoaderCancellationBlock requestToken;
> >   requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
> >     if (error) {
> >       [delegate URLRequest:requestToken didCompleteWithError:error];
> >       return;
> >     }
> > 
> >     NSString *mimeType = nil;
> >     NSData *imageData = nil;
> >     if (RCTImageHasAlpha(image.CGImage)) {
> >       mimeType = @"image/png";
> >       imageData = UIImagePNGRepresentation(image);
> >     } else {
> >       mimeType = @"image/jpeg";
> >       imageData = UIImageJPEGRepresentation(image, 1.0);
> >     }
> > 
> >     NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
> >                                                         MIMEType:mimeType
> >                                            expectedContentLength:imageData.length
> >                                                 textEncodingName:nil];
> > 
> >     [delegate URLRequest:requestToken didReceiveResponse:response];
> >     [delegate URLRequest:requestToken didReceiveData:imageData];
> >     [delegate URLRequest:requestToken didCompleteWithError:nil];
> >   }];
> > 
> >   return requestToken;
> > }
> > ```
> > 
> > 
> > Error is thrown out because `requestToken` is `nil`. Like someone else has pointed out it is nil because `completionBlock` executes before `requestToken` is initialised. It happens because some image loader is performing task synchronously.
> > I've managed to fix issue for my project by reverting this commit: [3198009#diff-9a034658197479288c4d346a0eb4d98c](https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c)
> 
> @ajanauskas Can you please guide me about how to revert this commit? Do I have to only change the file in node modules or something else needs to be done?

Yes, make changes in node modules and re-compile app. Like some people mentioned in a thread - you can use https://github.com/ds300/patch-package to make sure changes are not lost after re-runing `yarn install`

**Comment by faraznaqvi99** [comment]
> > > The main issue like someone mentioned is within `RCTImageLoader.mm` implementation:
> > > ```objc
> > > - (id)sendRequest:(NSURLRequest *)request withDelegate:(id<RCTURLRequestDelegate>)delegate
> > > {
> > >   __block RCTImageLoaderCancellationBlock requestToken;
> > >   requestToken = [self loadImageWithURLRequest:request callback:^(NSError *error, UIImage *image) {
> > >     if (error) {
> > >       [delegate URLRequest:requestToken didCompleteWithError:error];
> > >       return;
> > >     }
> > > 
> > >     NSString *mimeType = nil;
> > >     NSData *imageData = nil;
> > >     if (RCTImageHasAlpha(image.CGImage)) {
> > >       mimeType = @"image/png";
> > >       imageData = UIImagePNGRepresentation(image);
> > >     } else {
> > >       mimeType = @"image/jpeg";
> > >       imageData = UIImageJPEGRepresentation(image, 1.0);
> > >     }
> > > 
> > >     NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
> > >                                                         MIMEType:mimeType
> > >                                            expectedContentLength:imageData.length
> > >                                                 textEncodingName:nil];
> > > 
> > >     [delegate URLRequest:requestToken didReceiveResponse:response];
> > >     [delegate URLRequest:requestToken didReceiveData:imageData];
> > >     [delegate URLRequest:requestToken didCompleteWithError:nil];
> > >   }];
> > > 
> > >   return requestToken;
> > > }
> > > ```
> > > 
> > > 
> > > Error is thrown out because `requestToken` is `nil`. Like someone else has pointed out it is nil because `completionBlock` executes before `requestToken` is initialised. It happens because some image loader is performing task synchronously.
> > > I've managed to fix issue for my project by reverting this commit: [3198009#diff-9a034658197479288c4d346a0eb4d98c](https://github.com/facebook/react-native/commit/31980094107ed37f8de70972dbcc319cc9a26339#diff-9a034658197479288c4d346a0eb4d98c)
> > 
> > 
> > @ajanauskas Can you please guide me about how to revert this commit? Do I have to only change the file in node modules or something else needs to be done?
> 
> Yes, make changes in node modules and re-compile app. Like some people mentioned in a thread - you can use https://github.com/ds300/patch-package to make sure changes are not lost after re-runing `yarn install`

@ajanauskas Please tell me specifically where do I need to change. Because I tried changing the code in node modules but the error is still there. I have to submit tonight and I need help. Thanks in advance

**Comment by luskin** [comment]
@faraznaqvi99 please see my post: https://github.com/facebook/react-native/issues/29364#issuecomment-670150318

This should resolve your issue as it did for many of us. Replace this obj-c function and then rebuild your iOS application before archiving and submitting to the app store. Remember that any time you pod install you run the risk of this being overwritten (same with re-installing node_modules... etc).

**Comment by safaiyeh** [comment]
I believe @hramos was looking into this. Any updates?

**Comment by amilaDulanjana** [comment]
any update? I am having the same issue

**Comment by hramos** [comment]
Hey all, after looking through the entire thread, it looks like this issue was resolved on `master` once @sammy-SC 's fix, ffc90c7f92e63e1a53ed107833e3deed492ab435 landed. That occurred on July 28.

The fix _is not present in 0.63.2_. Samuel already requested this fix to be cherry-picked into a 0.63.3 release, if there is one (see https://github.com/react-native-community/releases/issues/203#issuecomment-665754860).

Several workarounds have been shared on this thread, such as cherry-picking the fix, or reverting the offending commit, into your own React Native custom release. You may also consider downgrading, or waiting for the next 0.64 release to be cut.

To discuss a 0.63.3 or 0.64.0 release, please use the appropriate release issue at https://github.com/react-native-community/releases/issues.

**Comment by devkrkanhaiya** [comment]
in 
node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm   file

 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                               size:(CGSize)size
                                              scale:(CGFloat)scale
                                         resizeMode:(RCTResizeMode)resizeMode
                                    progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                                 partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                  completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
{
  UIImage *image = RCTImageFromLocalAssetURL(imageURL);
  if (image) {
    if (progressHandler) {
      progressHandler(1, 1);
    }
    completionHandler(nil, image);
  } else {
    NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
    RCTLogWarn(@"%@", message);
    completionHandler(RCTErrorWithMessage(message), nil);
  }
  
  return nil;
}

**With**



 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                           size:(CGSize)size
                                          scale:(CGFloat)scale
                                     resizeMode:(RCTResizeMode)resizeMode
                                progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                             partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                              completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
 {
   __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
   RCTExecuteOnMainQueue(^{
     if (cancelled->load()) {
       return;
     }

     UIImage *image = RCTImageFromLocalAssetURL(imageURL);
     if (image) {
       if (progressHandler) {
         progressHandler(1, 1);
       }
       completionHandler(nil, image);
     } else {
       NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
       RCTLogWarn(@"%@", message);
       completionHandler(RCTErrorWithMessage(message), nil);
     }
   });

   return ^{
     cancelled->store(true);
   };
 }

This..

Like and Love , if it work 👍

**Comment by devkrkanhaiya** [comment]
in 
node_modules/react-native/Libraries/Image/RCTLocalAssetImageLoader.mm   file

 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                               size:(CGSize)size
                                              scale:(CGFloat)scale
                                         resizeMode:(RCTResizeMode)resizeMode
                                    progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                                 partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                  completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
{
  UIImage *image = RCTImageFromLocalAssetURL(imageURL);
  if (image) {
    if (progressHandler) {
      progressHandler(1, 1);
    }
    completionHandler(nil, image);
  } else {
    NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
    RCTLogWarn(@"%@", message);
    completionHandler(RCTErrorWithMessage(message), nil);
  }
  
  return nil;
}

**With**



 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                           size:(CGSize)size
                                          scale:(CGFloat)scale
                                     resizeMode:(RCTResizeMode)resizeMode
                                progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                             partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                              completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
 {
   __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
   RCTExecuteOnMainQueue(^{
     if (cancelled->load()) {
       return;
     }

     UIImage *image = RCTImageFromLocalAssetURL(imageURL);
     if (image) {
       if (progressHandler) {
         progressHandler(1, 1);
       }
       completionHandler(nil, image);
     } else {
       NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
       RCTLogWarn(@"%@", message);
       completionHandler(RCTErrorWithMessage(message), nil);
     }
   });

   return ^{
     cancelled->store(true);
   };
 }

This..

Like and Love , if it work 👍

**Comment by fahelmoreira** [comment]
dataForm.append('file', { uri: Platform.OS=='ios'?photo.uri.replace("file://", "/private"):photo.uri, name: 'photo.jpg', type: 'image/jpg' });

IOS : photo.uri.replace("file://", "/private")

**Comment by patrick-agency73** [comment]
For now
npm i react-native@0.0.0-949dedca9 --save

**Comment by onebotforyou** [comment]
> For now
> npm i react-native@0.0.0-949dedca9 --save

is that work?

**Comment by safaiyeh** [comment]
> > For now
> 
> > npm i react-native@0.0.0-949dedca9 --save
> 
> 
> 
> is that work?

Yeah there are nightly builds.

**Comment by anastely** [comment]
@onebotforyou Don't forget to delete `Pods` and run `npx pod-install` again ;)

**Comment by Jonatthu** [comment]
@fahelmoreira  it works for me on real device thanks!

> dataForm.append('file', { uri: Platform.OS=='ios'?photo.uri.replace("file://", "/private"):photo.uri, name: 'photo.jpg', type: 'image/jpg' });
> 
> IOS : photo.uri.replace("file://", "/private")
> 
> It only works for the real device, on simulator still give the error but at lease foi can deploy you app until this issue is patched

**Comment by fdkitlui** [comment]
> I also have same issue. I use hack for this [#29021 (comment)](https://github.com/facebook/react-native/issues/29021#issuecomment-662196480).

Nice temporary hack! It works in RN 0.63.2
I think we can do one more step.

copy the hacked RCTNetworkTask.mm into ios folder.
create a script 'runThisPodInstall.sh' in ios folder with these content:

`#!/bin/sh

rm -rf *.xcworkspace
rm -rf Pods/
cp -f RCTNetworkTask.mm ../node_modules/react-native/Libraries/Network/
pod install`

chmod +x runThisPodInstall.sh
everytime we remove the node_modules, wait for yarn install to be done, cd ios and ./runThisPodInstall.sh

**Comment by karanmartian** [comment]
> dataForm.append('file', { uri: Platform.OS=='ios'?photo.uri.replace("file://", "/private"):photo.uri, name: 'photo.jpg', type: 'image/jpg' });
> 
> IOS : photo.uri.replace("file://", "/private")
> 
> It only works for the real device, on simulator still give the error but at least you can deploy your app until this issue is patched

Beautiful it works, but can you explain the logic for this? What's private supposed to do?

**Comment by joealba** [comment]
React Native 0.63.3 is available now.  And in my local testing, this issue is now resolved.  Thanks so much, all!

**Comment by karanmartian** [comment]
Great! But is it available in the Expo RN version?

**Comment by safaiyeh** [comment]
Glad the fix made it!

**Comment by sagarlava** [comment]
Good job.. thanks a lot

**Comment by phillipkey** [comment]
Can also confirm that with RN 63.3 I am no longer seeing the issue.

**Comment by honzajerabek** [comment]
upload form data image with axios fixed with v0.63.3

**Comment by EmersonGarrido** [comment]
v0.63.3 axio / expo and react native i am still having problem request token in the upload of image formData IOS

**Comment by AliUZAR** [comment]
Same issue on v0.63.2 
`npx react-native upgrade` upgraded to v0.63.3 fixed the error.

**Comment by NathanNovak** [comment]
> Same issue on v0.63.2
> `npx react-native upgrade` upgraded to v0.63.3 fixed the error.

@AliUZAR This worked for me.

**Comment by Balasnest** [comment]
@joealba getting this build error after upgrade from 0.63.2 to 0.63.3. 

`error: /Users/bala/Desktop/projectName/node_modules/react-native/React/AccessibilityResources/en.lproj: No such file or directory`

Any idea?

**Comment by TrivilinVilaApps** [comment]
Error fixed when updating React Native to version 0.63.3

**Comment by GuilhermeTrivilin** [comment]
Error fixed when updating React Native to version 0.63.3

**Comment by namxg6626** [comment]
> Same issue on v0.63.2
> `npx react-native upgrade` upgraded to v0.63.3 fixed the error.

it worked. thanks

**Comment by teachdugsimt** [comment]
1. go : node_modules/react-native/Libraries/image    
replace following. 
/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <React/RCTLocalAssetImageLoader.h>

#import <atomic>
#import <memory>

#import <React/RCTUtils.h>
#import <ReactCommon/RCTTurboModule.h>

#import "RCTImagePlugins.h"

@interface RCTLocalAssetImageLoader() <RCTTurboModule>
@end

@implementation RCTLocalAssetImageLoader

RCT_EXPORT_MODULE()

- (BOOL)canLoadImageURL:(NSURL *)requestURL
{
  return RCTIsLocalAssetURL(requestURL);
}

- (BOOL)requiresScheduling
{
  // Don't schedule this loader on the URL queue so we can load the
  // local assets synchronously to avoid flickers.
  return NO;
}

- (BOOL)shouldCacheLoadedImages
{
  // UIImage imageNamed handles the caching automatically so we don't want
  // to add it to the image cache.
  return NO;
}

 - (RCTImageLoaderCancellationBlock)loadImageForURL:(NSURL *)imageURL
                                               size:(CGSize)size
                                              scale:(CGFloat)scale
                                         resizeMode:(RCTResizeMode)resizeMode
                                    progressHandler:(RCTImageLoaderProgressBlock)progressHandler
                                 partialLoadHandler:(RCTImageLoaderPartialLoadBlock)partialLoadHandler
                                  completionHandler:(RCTImageLoaderCompletionBlock)completionHandler
{
   __block auto cancelled = std::make_shared<std::atomic<bool>>(false);
    RCTExecuteOnMainQueue(^{
    if (cancelled->load()) {
      return;
    }
   UIImage *image = RCTImageFromLocalAssetURL(imageURL);
    if (image) {
      if (progressHandler) {
        progressHandler(1, 1);
      }
      completionHandler(nil, image);
    } else {
      NSString *message = [NSString stringWithFormat:@"Could not find image %@", imageURL];
      RCTLogWarn(@"%@", message);
      completionHandler(RCTErrorWithMessage(message), nil);
    }
  });

  return ^{
    cancelled->store(true);
  };
}

@end

Class RCTLocalAssetImageLoaderCls(void) {
  return RCTLocalAssetImageLoader.class;
}




2. build formData like this
 let formData = new FormData();
                formData.append("file", {
                    name:file.fileName,
                    uri:  Platform.OS == 'ios' ? file.uri.replace("file://", "") : file.uri,
                    type: file.type,
                    width: file.width,
                    size: file.fileSize
                })

** rn version : 0.63+

**Comment by lfoliveir4** [comment]
> React Native 0.63.3 is available now. And in my local testing, this issue is now resolved. Thanks so much, all!

I had this same problem in 0.62.2 Only the update to version 0.63.3 solved the problem.

Update link: https://react-native-community.github.io/upgrade-helper/?from=0.63.2&to=0.63.3

**Comment by victorglomer** [comment]
in my mac I needed to do like this (without "/private"):
   
     const data = new FormData();
        data.append("avatar", {
          type: "image/jpeg",
          name: `${user.id}.jpg`,
          uri:
            Platform.OS == "ios"
              ? response.uri?.replace("file://", "/")
              : response.uri,
        });
