### ISSUE TITLE
Local images not rendered on iOS 14 physical device for release build

### ISSUE THREAD

**Issue by syntheticencounters** [facebook/react-native#29813]
The bug previously listed where images aren't rendered on iOS 14 beta devices appears to be a bit deeper than what was listed. When running 0.63.2, local images are now rendered in an iOS 14 simulator, development build on iOS 14 physical device, but no local images are rendered on a iOS 14 physical device release build. 

## Description
Remote images are rendered without any issue. Local images are rendered on an iOS 14 simulator and when running a development build on a physical device running iOS 14 beta. Local images are NOT rendered when running a release build on physical device running iOS 14 beta 

## React Native version:
react-native: 0.63.2
Tested running a brand new project created with create-react-native-app and then ejected. 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Render an image component with the source set to a local image file 
2. Run release build on a physical device running iOS 14 beta

## Expected Results
Image data should be rendered as shown in development build

**Comment by safaiyeh** [comment]
Hi @syntheticencounters sorry you're having issues! Could you provide a repro for your issue? iOS 14 is still in beta so issues like this are nice to highlight upcoming challenges

**Comment by syntheticencounters** [comment]
> Hi @syntheticencounters sorry you're having issues! Could you provide a repro for your issue? iOS 14 is still in beta so issues like this are nice to highlight upcoming challenges

Thanks for the quick reply! 

Unfortunately I can't post any direct code from the project due to the agreements in place for the project as a whole. 

The issue appears to be present across multiple projects running various versions of RN ranging from 0.59.x to 0.63.2. All projects that did not historically have any issues with image rendering prior to iOS 14.

Apps built with both Xcode 11 and Xcode 12 beta seem to be effected when built using Big Sur. I have not had a chance to try building on Catalina but will attempt tomorrow. 

Physical devices used include iPhone SE, iPhone 7, and iPhone 11 Pro running iOS 14 beta 2 through beta 6. 

The RN 0.63.0 patch listed in a previous post resolved the issue for remote images and local images for simulator and development builds but the issue persists for physical devices. 

Please let me know if there's any more information that I can provide to help identify the root cause.

**Comment by saachitech** [comment]
How do you embed local images? I think they won't work unless you embed them in the package, so for example, if you don't use require('localimage') or import them, they won't work in release build because they won't be packaged unless you explicitly embed them in ios package. You can either add them in build settings or create image sets.

**Comment by syntheticencounters** [comment]
> How do you embed local images? I think they won't work unless you embed them in the package, so for example, if you don't use require('localimage') or import them, they won't work in release build because they won't be packaged unless you explicitly embed them in ios package. You can either add them in build settings or create image sets. 

Thanks for the information. All local images are loaded via require.

**Comment by dulmandakh** [comment]
My app built with RN 0.63 works as expected on iOS 14 beta. Could you please create a reproducible demo code you help us investigate the issue. Will re-open is when we have demo code. Thanks

**Comment by safaiyeh** [comment]
Reopening, there are known issues for local images. Many issues have been filed for this. Looking for a direction for all of them.

@syntheticencounters we need a repro to understand your issue, if you could provide one that would speed up the process

**Comment by syntheticencounters** [comment]
> Reopening, there are known issues for local images. Many issues have been filed for this. Looking for a direction for all of them.
> 
> 
> 
> @syntheticencounters we need a repro to understand your issue, if you could provide one that would speed up the process
> 
> 

Thanks for reopening. 
I'll get something posted tomorrow when I'm back at my machine.

**Comment by KDBINMC17** [comment]
same issue

**Comment by saachitech** [comment]
This has been discussed here and may be available in the next release https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

#29279

**Comment by vish2595** [comment]
Same issue, Images not rendered on IOS 14.1 physical device for release but showing in DEV. Please help me out of this.

Xcode Version: 12
Device: iPhone 7, OS: 14.1

**Comment by mateodaza** [comment]
> Same issue, Images not rendered on IOS 14.1 physical device for release but showing in DEV. Please help me out of this.
> 
> Xcode Version: 12
> Device: iPhone 7, OS: 14.1

I have the same issue

**Comment by LeviWilliams** [comment]
Same issue for me happening over multiple devices both iOS 14 and 14.1

**Comment by aperomingo** [comment]
this could helps you
**https://github.com/facebook/react-native/issues/29279**

**Comment by vish2595** [comment]
I also do that "this could helps you #29279" but not working. @aperomingo

**Comment by aperomingo** [comment]
This is the fix you need https://github.com/facebook/react-native/commit/123423c2a9258c9af25ca9bffe1f10c42a176bf3
I did it manually, and it works

RN 0.63.1

**Comment by mateodaza** [comment]
It works fine in debug but not for release @aperomingo did you try it building your app as release mode?

**Comment by saachitech** [comment]
@mateodaza I tried that fix for dev and release. It works great. I build through xCode using Product>Archive though.

**Comment by mateodaza** [comment]
Nevermind!! This time the error was human haha, it works. Thanks!

**Comment by safaiyeh** [comment]
@mateodaza could you share what caused the error in your context? It may help people out

**Comment by renatobenks** [comment]
it seems to be fixed @dulmandakh, I think you can close it for good, once it's not happening anymore since https://github.com/facebook/react-native/commit/663b5a878be9faafd13b41c222a1bc2ac7bb3a65 was introduced in the version [v0.63.3](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0633)

**Comment by safaiyeh** [comment]
Thanks for confirming @renatobenks! Closing the issue.

**Comment by KDBINMC17** [comment]
I decompressed the IPA installation package and found that the assets file was missing. Then I added the assets file dependency when packaging. The problem was solved.

**Comment by syntheticencounters** [comment]
Can we re-open this? The issue is still present on 0.63.3. I created a blank project using create-react-native-app and local images are still not visible on a release build. Assets folder is packaged with the distribution but nothing is displayed in the app. Is there something that I'm missing? I haven't had an issue with images for any of the past react-native apps that I've built.

**Comment by telltokichu** [comment]
Facing same issue 
in dev flow it is working fine , but while in release build - **images are not rendering**

**Comment by udaysagartammina** [comment]
> Facing same issue
> in dev flow it is working fine , but while in release build - **images are not rendering**

I am also facing same issue, any solution?
Thanks in advance.

**Comment by renatobenks** [comment]
@safaiyeh any idea why this is still happening? I didn't struggle anymore with that issue, since 0.63.3 actually 🤔

**Comment by khalednailigit** [comment]
I am also facing same issue, any solution?
Thanks in advance.

**Comment by khalednailigit** [comment]
Please check XCode console log first. You will find that the app couldn't find out those specific image assets on path "{project name}.app/assets/resources/.."
https://stackoverflow.com/questions/35354998/react-native-ios-app-not-showing-static-assets-images-after-deploying
