### ISSUE TITLE
Error when archiving in XCode: EMFILE

### ISSUE THREAD

**Issue by TheRealNate** [facebook/react-native#29915]
This error has been reported before, but the solution did not help me.

## Description
I am seeing this error when archiving from XCode. I have not encountered this issue before and have tried reverting my code:
````
node /.../node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output ... --assets-dest ...

warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/.../node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:311:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:133:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
````

I have tried the following steps to fix:
- Reinstall Watchman (`sudo port uninstall watchman`, `sudo port install watchman`, reboot) (this has been the solution on similar issues but has not helped me)
- Reset Cocoapods (Deintegrate, rm Pods/, reinstall etc)
- Reset Watchman Cache (watchman watch-del-all)
- Clean Build Folder in XCode

If I run the bundle command manually from terminal it succeeds, it only seems to have a problem when archiving from XCode.

I also run `npx react-native doctor` and there is a ✅ next to Watchman

## Versions:
Environment: macOS Catalina
React Native CLI Version: 4.10.1
Node Version 12.16.1
React Native Version: 0.63.2
Watchman Version: 4.9.0

**Comment by TheRealNate** [comment]
Interesting development. If I manually run the xcodebuild command the archive succeeds:
````
xcodebuild -workspace ... -scheme ... archive
````

Isn't this basically identical to Product > Archive in XCode? Are there any explanations for this.

**Comment by watanabeyu** [comment]
same issue ...

**Comment by jdbarrera** [comment]
I am getting the same error.  The program builds fine in the command line but has this error when built in xCode.

**Comment by alexyangjie** [comment]
Same issue here.

**Comment by alexfoxy** [comment]
I am also experiencing this issue. It occurs at the `Bundle React Native code and images` build phase.  React Native: 0.63.4.

**Comment by Natteke** [comment]
still exist RN 0.64. tried nodejs 14 / 16. Watchman installed. OS BigSur. chip M1

ulimit -a:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8176
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2000
virtual memory          (kbytes, -v) unlimited

**Comment by ekram21** [comment]
Same issue on Macbook M1. The issue in my opinion is that the metro bundler does not start up inside a separate new terminal like it does when I am archiving in my intel macbook. The metro bundler attempts to start inside the xcode where it does not let watchman work properly so this error gets thrown.

**Comment by ekram21** [comment]
This got fixed recently in newest version of watchman. The problem was with bug in fsevents library for mac m1 which got fixed in latest release. Update your watchman, reinstall your project, pods everything and things should work

**Comment by jdbarrera** [comment]
@ekram21 I upgraded watchman, yarn install, and npx pod-install and I am still getting the same error.  Am I missing something?

**Comment by ekram21** [comment]
> @ekram21 I upgraded watchman, yarn install, and npx pod-install and I am still getting the same error. Am I missing something?

I don't know your environment and what device you are using but I will list the things to keep in mind:

- This is for MAC M1 Silicon
- Latest Versions of Node, React Native being used
- Latest Versions of Watchman and Brew being used
- I did not use Yarn. NPM install used to install all node modules and navigated to iOS folder and just used pod install - consult these thread if pod install doesn't work: https://github.com/CocoaPods/CocoaPods/issues/10349 
- Make duplicate terminals with one running on Rosetta and the other native. 
- Brew should be installed with native terminal, and then watchman after
- After this you need open Settings - Security Preference and give complete disk access to xcode, watchman, terminal and any other tools being used in your environment.
- Your project cannot be under desktop or downloads. Make sure it is under /Users/myname/

Also look at this thread: https://github.com/facebook/metro/issues/668

These are the steps I followed to make the project archive in xcode. Note that the project would compile fine in simulator outside of xcode before but the above steps finally got it to archive in xcode where it was failing

**Comment by deepakverma4** [comment]
@ekram21 which watchman version are you using?

**Comment by chaohuichen** [comment]
any updates on this issue? 

I am getting the same issues


`events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/chaohuichen/Desktop/PCC/fillup/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:400:28)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
`

**Comment by eshunnar** [comment]
> Interesting development. If I manually run the xcodebuild command the archive succeeds:
> 
> ```
> xcodebuild -workspace ... -scheme ... archive
> ```
> 
> Isn't this basically identical to Product > Archive in XCode? Are there any explanations for this?
> 
> Another note: Another much smaller RN app archives successfully in XCode on my machine.

Works for me with same error on latest version of watchman error.

**Comment by majirosstefan** [comment]
still

**Comment by JulianKingman** [comment]
I started having this issue after upgrading to yarn 2

**Comment by hernancasillas** [comment]
Still

**Comment by acamara2016** [comment]
same here, currently on Venture 13.1 trying to run yarn test

**Comment by AbdullahPrime** [comment]
> I was able to fix that issue by both installing watchman and setting the path to homebrew on XCode build phase "Bundle React Native code and images" before the react native xcode shell script, as follows:
> 
> ```
> export PATH=/opt/homebrew/bin:$PATH
> export NODE_BINARY=node
> ../node_modules/react-native-schemes-manager/lib/react-native-xcode.sh
> ```
> 
> Solution found on https://stackoverflow.com/a/70177808/17614397

I did this but issue is still there

export NODE_BINARY=/opt/homebrew/opt/node@22/bin/node
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

**Comment by alordiel** [comment]
Having same issue on M1, building for debug is working without any problem. I've tried all mentioned solutions here, also suggested "working" fix from this [stackoverflow](https://stackoverflow.com/questions/67621315/error-emfile-too-many-open-files-using-xcode-to-archive-react-native-app) but without any success. XCode at version 16.

**Comment by yassir-agharben** [comment]
> I was able to fix that issue by both installing watchman and setting the path to homebrew on XCode build phase "Bundle React Native code and images" before the react native xcode shell script, as follows:
> 
> ```
> export PATH=/opt/homebrew/bin:$PATH
> export NODE_BINARY=node
> ../node_modules/react-native-schemes-manager/lib/react-native-xcode.sh
> ```
> 
> Solution found on https://stackoverflow.com/a/70177808/17614397

This solution to add "export PATH=/opt/homebrew/bin:$PATH" worked for me.

**Comment by petertoth-dev** [comment]
Sometimes it's not about `watchman` even if the error tells that:

If you've already tried everything (restart, clean build, watchman install, watchman reinstall, increase watcher limit etc....), your case might be similar to mine, and you don't have `node` in `PATH` for the Xcode environment.

Xcode -> Build Phases -> Scroll down to "Bundle React Native code and images", and add `node` to `PATH`:
`export PATH=$PATH:/opt/homebrew/bin`

In case your `node` is in a different path (e.g. you installed it with nvm), check your node's PATH and add it to PATH like above.

To check your node's path, open terminal and `which node` should tell you the path.

`export PATH=$PATH:/path/to/your/node/folder`

**Comment by mustafazeb381-123** [comment]
i have this error when i want to distribute the app in m1 mac "Reached end of file while looking for: Mach-O slice." how can i resolve this issue anyone know about this
"
