### ISSUE TITLE
Success installed the app on the device but nothing happens since Xcode update from yesterday

### ISSUE THREAD

**Issue by bidetaggle** [facebook/react-native#29975]
## Description
When I want to start the app on my physical iPhone, everything seems to work well but nothing happen on the phone. It was working well yesterday. Today I opened Xcode and there were a pop-up saying that Xcode needs to install some stuffs, I clicked Okay and wait for the progress bar to finish. Nothing else has changed, only an update for Safari, no mac update, no iPhone update since.

Here is the output:
```
npx react-native run-ios --device "Bide’s iPhone"
info Found Xcode workspace "kisschatproudchat.xcworkspace"
`instruments` is now deprecated in favor of 'xcrun xctrace' (see `man xctrace` for more information on its replacement)
info Building (using "xcodebuild -workspace kisschatproudchat.xcworkspace -configuration Debug -scheme kisschatproudchat -destination id=7c4d0fcb017347e75d6affb40397f3a277de6f18")
......................................................................
2020-09-18 18:06:20.756 xcodebuild[22873:499730]  DTDeviceKit: deviceType from 7c4d0fcb017347e75d6affb40397f3a277de6f18 was NULL
2020-09-18 18:06:20.868 xcodebuild[22873:499730]  DTDeviceKit: deviceType from 7c4d0fcb017347e75d6affb40397f3a277de6f18 was NULL
2020-09-18 18:06:20.868 xcodebuild[22873:499730]  DTDeviceKit: deviceType from 7c4d0fcb017347e75d6affb40397f3a277de6f18 was NULL
info Installing and launching your app on Bide’s iPhone
success Installed the app on the device.
```

## React Native version:
```
$ npx react-native info                            
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 142.27 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1 
    react: ~16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `$ npx react-native run-ios --device "Bide’s iPhone"`

## Expected Results
The app to launch on the iPhone

## What I tried already
```
$ rm -rf node_modules
$ npx pod-install
$ npm i
$ brew upgrade ios-deploy
```
Still not working. It launches from Xcode tho, but I cannot properly work on it without the Fast Refresh

**Comment by tradebulls** [comment]
+1. Facing same issue

**Comment by kshestakov** [comment]
+1 Struggling with this issue too

**Comment by MrAlekhin** [comment]
+1

**Comment by ithaqua** [comment]
+1

**Comment by dantereve** [comment]
I'm facing the same issue since Xcode 12 update for the two apps I'm working on. The build is ok, but nothing happens on the device, the apps are not installed whatsoever. I've tested on iPhone and iPad running iOS 14 and even tried on iOS 13.

Apps are running smoothly on simulator. 

(Please note that I had to use the patch from https://github.com/facebook/react-native/issues/29279 to fix images display but I don't think It's related.)

Here's my react-native info : 
```
➜ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 566.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.22.0/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3
      System Images: android-24 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
  IDEs:
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

**Comment by bidetaggle** [comment]
Anyone got it fixed by a way or another since?

**Comment by joeshub** [comment]
I noticed the same thing, couple of changes did the trick for me.

- unpair the device and repaired it from the Devices and Simulators window in Xcode, using a cable.
- added one argument to force debug mode to be on.

```shell
npx react-native run-ios --device "Bide’s iPhone" --configuration "Debug"
```

**Comment by dantereve** [comment]
I’m still facing some issues here. I've tried the solutions described in this other issue (#30028) without any success whatsoever.

My apps have two schemes in Xcode. One for our production API and another one for our staging API. 

I’m launching my commands via a makefile. 

The production scheme which is the default one can be launched on a device with this command and is working fine on device:

```bash
run-on-ios@production: export ENVFILE = .env.production
run-on-ios@production: ## Run on iOS device [PROD]
	./node_modules/.bin/react-native run-ios --port ${BUILDER_PORT} --configuration Debug --device $(IOS_DEVICE)
```

But the Staging scheme fails silently to launch on device with `run-ios` with this command: 
```bash
run-on-ios@staging: export ENVFILE = .env.staging
run-on-ios@staging: ## Run on iOS device [STAGING]
	./node_modules/.bin/react-native run-ios --port ${BUILDER_PORT} --scheme Staging --configuration Staging.Debug --device $(IOS_DEVICE)
```

I can see a success message at the end.

```bash
▸ Build Succeeded
info Installing and launching your app on iPad de dev Mounki
success Installed the app on the device.
```

I'm a bit clueless here. 🤷‍♂️

**Comment by bidetaggle** [comment]
Guys I messed around with `npm`, `rm -rf node_modules`, `npx react-native run-ios  --device "Bide’s iPhone"` for days until I don't even recognize my `package.json` file and today, I tried again from the beginning and it worked literally without any change on my repo. I don't even need `--configuration "Debug"`
This is pure magic, don't know what to say.

**Comment by ikara5** [comment]
‫أُرسلت من الـ iPad‬

**Comment by lkwjohn** [comment]
@bidetaggle it couldn't have been magic, some configuration might have been changed that makes it work.

**Comment by bidetaggle** [comment]
Well it really looks like magic and I was expecting someone to explain how it's not 😆

For now, it works well only on my personal hotspot using my data plan. For any other WiFi (home, working place, friend's place) the app will launch and quit without any error, the metro server is unreachable from the iPhone. What can I do about it?

**Comment by showtan001** [comment]
+++1

**Comment by showtan001** [comment]
Xcode 12.2 Beta 4
iOS 14.0
react native 0.61.5

`npx react-native run-ios`

error: 
```
2020-11-12 15:31:29.919 xcodebuild[49422:365431]  DTDeviceKit: deviceType from 00008030-00190D5A3A04802E was NULL
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/yoga_vers.o /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/DerivedSources/yoga_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/Objects-normal/x86_64/jsinspector_vers.o /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/DerivedSources/jsinspector_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

Xcode run APP

Details

```
Unable To Install “路桥”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework; Extra info about Info.plist: Couldn't stat /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework/Info.plist: No such file or directory
--
Failed to load Info.plist from bundle at path /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework; Extra info about Info.plist: Couldn't stat /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework/Info.plist: No such file or directory
Domain: MIInstallerErrorDomain
Code: 35
User Info: {
    FunctionName = "-[MIBundle _validateWithError:]";
    LegacyErrorString = PackageInspectionFailed;
    SourceFileLine = 131;
}
--


System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 12.2 (17535) (Build 12B5044c)
Timestamp: 2020-11-12T15:42:33+08:00
```

**Comment by mifi** [comment]
FWIW I replugged my iPhone and now it works

**Comment by rzrobert** [comment]
> Xcode 12.2 Beta 4
> iOS 14.2
> react native 0.61.5
> 
> `npx react-native run-ios`
> 
> error:
> 
> ```
> 2020-11-12 15:31:29.919 xcodebuild[49422:365431]  DTDeviceKit: deviceType from 00008030-00190D5A3A04802E was NULL
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/yoga_vers.o /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/DerivedSources/yoga_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
> 	CompileC /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/Objects-normal/x86_64/jsinspector_vers.o /Users/mac/Library/Developer/Xcode/DerivedData/RoadArchives-exjnpbkrtnvnumfundufcrkbooyi/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-jsinspector.build/DerivedSources/jsinspector_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
> (2 failures)
> ```
> 
> Xcode run APP
> 
> Details
> 
> ```
> Unable To Install “路桥”
> Domain: IXUserPresentableErrorDomain
> Code: 1
> Failure Reason: Please try again later.
> Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework; Extra info about Info.plist: Couldn't stat /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework/Info.plist: No such file or directory
> --
> Failed to load Info.plist from bundle at path /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework; Extra info about Info.plist: Couldn't stat /Users/mac/Library/Developer/CoreSimulator/Devices/272E784E-49DB-4EAF-9F2C-1C2975564066/data/Library/Caches/com.apple.mobile.installd.staging/temp.MwHyED/extracted/RoadArchives.app/Frameworks/RCTVibration.framework/Info.plist: No such file or directory
> Domain: MIInstallerErrorDomain
> Code: 35
> User Info: {
>     FunctionName = "-[MIBundle _validateWithError:]";
>     LegacyErrorString = PackageInspectionFailed;
>     SourceFileLine = 131;
> }
> --
> 
> 
> System Information
> 
> macOS Version 10.15.6 (Build 19G2021)
> Xcode 12.2 (17535) (Build 12B5044c)
> Timestamp: 2020-11-12T15:42:33+08:00
> ```


Did you fixed this bug?

**Comment by bidetaggle** [comment]
@rzrobert Your problem is not related to this issue, i'm closing it because it's outdated now.

According to your error, I suggest you to search for `MIInstallerErrorDomain` and `RCTVibration` on google.

**Comment by canberkatbinici** [comment]
I having same issue with fresh project created by react-native init 
<img width="455" alt="Screen Shot 2022-01-05 at 16 02 56" src="https://user-images.githubusercontent.com/32189700/148221879-853df770-5e55-453b-8b8c-4e4569d55cdb.png">
<img width="303" alt="Screen Shot 2022-01-05 at 15 52 52" src="https://user-images.githubusercontent.com/32189700/148220670-1269e8c4-7ae3-4180-b1aa-677f2b037667.png">
<img width="568" alt="Screen Shot 2022-01-05 at 16 03 28" src="https://user-images.githubusercontent.com/32189700/148221948-99601491-04e6-4b03-816c-2e389f99d368.png">
<img width="568" alt="Screen Shot 2022-01-05 at 16 03 51" src="https://user-images.githubusercontent.com/32189700/148222014-6653e370-5102-4722-8483-f805054e9871.png">
<img width="1058" alt="Screen Shot 2022-01-05 at 16 04 20" src="https://user-images.githubusercontent.com/32189700/148222076-3dd86ab0-7153-429b-8d9b-54b36548dc4e.png">
I did npm install and pod install 
Emulator working fine but physical device doesn't download application from metro or other message came from metro. 
there is only one connected device and here is my build command for ios device
"npx react-native run-ios --device"
And other hand I tried past loaded applications on ios device by react-native and metro same thing happened but I open application myself and touched reload js after that everything become normal for this build process. 
It's happening in all projects from past day it's started suddenly from one project when I m trying to build. 


Does anyone have any idea ?
