### ISSUE TITLE
[DatePicker] 0.12.0-rc gives: `DatePickerIOS` has no propType for native prop `RCTDatePicker.onChange` of native type `BOOL`

### ISSUE THREAD

**Issue by olofd** [facebook/react-native#3154]
I upgraded from 0.11.0 to 0.12.0-rc and now I get:
`DatePickerIOS` has no propType for native prop `RCTDatePicker.onChange` of native type `BOOL`

I've leaned the project in xcode and reset the simulator, but to no wail.
Can't see that I'm doing anything wrong.

**Comment by Crash--** [comment]
Can you share with us the code you use for the DatePickerIOS stuff? Because I don't have any problem with my code or UIExplorer.

**Comment by brentvatne** [comment]
@olofd - you should clean your build with cmd+shift+k from Xcode and run it again. It looks like your native code is stale, because `onChange` is type `RCTBubblingEventBlock` on 0.12.0-rc and not BOOL

**Comment by olofd** [comment]
You were right! My bad! Sry!

**Comment by mschipperheyn** [comment]
I also have this issue, even after cmd+shift+k. Is there another level of staleness that cmd+shift+K might not clean?

**Comment by mschipperheyn** [comment]
Also seeing various errors such as 
/Users/Shared/java/projects/react/msa/project/node_modules/react-native/packager/transformer.js:32
    filename,
            ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)

I think I'll try to reinstall react-native

**Comment by mschipperheyn** [comment]
This is the offending code. I have 0.12.0-rc

var RCTDatePickerIOS = requireNativeComponent('RCTDatePicker', DatePickerIOS, {
  nativeOnly: { onChange: true },
});

**Comment by alfonsodev** [comment]
Exactly same problem, and cmd+shift+k doesn't help, 
https://github.com/facebook/react-native/blob/master/Libraries/Components/DatePicker/DatePickerIOS.ios.js#L149
And last modification of the file 
https://github.com/facebook/react-native/commit/33036b1f01c1e3816745bfe9c243a478445559ee
Thoughts ?

**Comment by alfonsodev** [comment]
Ok for me the problem was solved closing packager terminal,
cleaning project and running packager by myself. 
@mschipperheyn give it a try. 
this was caused because I opened a old react 0.11 project, and then went back to different project 0.12 
without closing packager process. 
I hope it helps.

**Comment by alvingarcia** [comment]
Just upgraded from 0.11.4 to 0.12.
Still can't make the error disappear using those methods @brentvatne @alfonsodev 

When I removed  `DatePickerIOS: require('DatePickerIOS'),` on `react-native.js`, another error appears : 
`ScrollView` has no propType for native prop `RCTScrollView.snatToAlignment` of native type `NSString`

**Comment by gre** [comment]
@alvingarcia make sure you stop any existing packager terminal, clean from XCode and that you don't use an old bundle. Also I would even recommend a complete `rm -rf node_modules` if it still don't work.

**Comment by alfonsodev** [comment]
@alvingarcia  also check that new packager process that you run is actually running , sometimes it can fail on starting because for instance you have a chrome debugger session opened.

**Comment by christopherdro** [comment]
Just upgraded to 0.12.0 and started to notice this as well.  I cleared all node_modules, cleaned out the build and reset content and settings for the simulator but still couldn't get it to work.

I even double checked and the code being executed was what @brentvatne mentioned earlier with it being `RCTBubblingEventBlock`.

Finally ended up just restarting the system and now everything is working fine.

**Comment by xinthink** [comment]
Facing the same problem on 0.12.0

**Comment by andresbravog** [comment]
same problem here

**Comment by kenfdev** [comment]
same here, too. restarted the system as @christopherdro said and it started working fine.

**Comment by ohadpartuck** [comment]
same here. tried restating the packeger , cleaning and nothing

**Comment by christopherdro** [comment]
@ohadpartuck Did you try restarting your computer?

**Comment by iammerrick** [comment]
Seeing this same issue with a brand new react native integration to an existing applicaiton. Using nothing but simple view demos

**Comment by idibidiart** [comment]
I run this, which I have in my .bash_profile, which deletes XCode derived data.  It’s the location where Xcode stores all kinds of intermediate build results, generated indexes, etc. 

```ddd() {
    #Save the starting dir
    startingDir=$PWD

    #Go to the derivedData
    cd ~/Library/Developer/Xcode/DerivedData

    #Sometimes, 1 file remains, so loop until no files remain
    numRemainingFiles=1
    while [ $numRemainingFiles -gt 0 ]; do
        #Delete the files, recursively
        rm -rf *

        #Update file count
        numRemainingFiles=`ls | wc -l`
    done

    echo Done

    #Go back to starting dir
    cd $startingDir
}```

then I restarted XCode, cleaned, removed app from Simulator

restarted packager

then rebuilt

It works fine now (at least for me) but this needs to be traced to the root cause and resolved properly

**Comment by ohadpartuck** [comment]
@christopherdro yes, tried now. still nothing. also tried @idibidiart solution.

**Comment by alfonsodev** [comment]
Check with 'ps aux' is still any packager process running?
Also when packager starts have a look to the output, it can fail when
starting.

**Comment by kyle-ssg** [comment]
Any update on this? I've been running into this issue a lot since upgrading one of my projects to 12
