### ISSUE TITLE
React-Native 0.64.2 iOS simulator crash on reloading after updating RN version

### ISSUE THREAD

**Issue by fullstack17** [facebook/react-native#31742]
## Description
I updated the react-native version from 0.63.3 to latest version(0.64.2), and it runs properly on iOS simulator. when I hit the Reload on Debug Menu, it's crashed.
## React Native version:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 134.27 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Turn on `Debug with Chrome` of Debug Menu.
2. Click `Reload` button on Debug Menu.

## Expected Results
It should reload the app.

## Snack, code example, screenshot, or link to a repository:
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This method must not be called before the JS thread is created'
terminating with uncaught exception of type NSException
CoreSimulator 757.5 - Device: iPhone 11 (BFC75FB2-4AC4-49A8-9570-C9C59BFE0C2B) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 11
```
<img width="1194" alt="122442310-1c868c80-cfa7-11eb-85f5-bdf38912c674" src="https://user-images.githubusercontent.com/44271282/122788074-a2b01500-d2be-11eb-97b0-e9beaba2cde5.png">

**Comment by felire** [comment]
I had to use an older version of Flipper and the issue was solved on my side, I had to do this on the `Podfile`: 

```
  use_flipper!({'Flipper' => '0.87.0' , 'Flipper-Folly' => '2.5.3' , 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    react_native_post_install(installer)
  end
```

**Comment by fullstack17** [comment]
@felire I tried, but it's still crashed. If `Debug with chrome` is enabled, it's always crashed whenever the app is reloaded, otherwise, it's working fine.

**Comment by DatNguyenCore** [comment]
i have bug too, in react native version 0.64.1

**Comment by yemd** [comment]
Similar bug here too
