### ISSUE TITLE
Safe area view not working properly in iphone 12 series

### ISSUE THREAD

**Issue by vishal1198** [facebook/react-native#32142]
Current behavior
These kind of issues were already been raised as an issue and those issues got solutions and those issues where closed now.

I have also raised the same issue in react-navigation also 

But my observation is most of the issues says that need to upgrade the packages that are related to react-navigation like react-navigation, react-navigation-stack, react-navigation-drawer, react-navigation-tabs or add react-native-safe-area-context, react-native-safe-area-view. 

But I couldn't solve the issue even though I implemented all the ways that are mentioned in closed issues.

Below I have attached the sample reference screenshot and the git issue link that I tried to fix my issue.

The code is not yet attached .Will attach it asap.

Kindly someone do the needful to get out of this issue. Thanks in advance folks. 

## React Native version:
SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-S | Google APIs Intel x86 Atom_64, android-S | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

<img width="819" alt="Screen Shot 2021-09-03 at 1 00 56 PM" src="https://user-images.githubusercontent.com/34634564/131967682-25998b4f-c101-4e6b-9ba0-35e8c85d2ea1.png">

## Expected Results
the expected behaviour is supposed to be like all the iphone devices should display an same UI.

**Comment by vishal1198** [comment]
**List of attempts**

1. Tried adding safeAreaView for the whole app. It fixed in iphone 12 but all other devices got issue with same ui.
2. Tried upgrading 
        -  react-navigation-drawer from 2.3.3 to 2.6.0
        - react-navigation-stack from 1.9.4 to 2.10.0
        - react-navigation from  4.0.10 to 4.4.3
     still behaved the same.
3. Tried adding react-native-safe-area-view and react-native-safe-area-context and used safe area view, still behaved the same.
4.Tried "react-native-safe-area-view": "^2.0.0" since ,mentioned in some article still behaved the same.
5. Now I tried to reproduce the same issue with some sample project. there I could replicate the same issue without using any navigation related compoonents, and I fixed the issue by just wrapped the whole code with SafeAreaView. Now the issue got fixed. but when I tried the same way in required its not working. 
6. then I tried to upgrade react native from 0.61.2 - 0.63.3. now I face lot of package dependency issues.


For any other details please dont hesitate to comment. Thanks In advance

**Comment by brettdh** [comment]
I still have this issue as well, after upgrading all the things you upgraded. I also tried adding a SafeAreaView around the whole app [as described here](https://github.com/react-navigation/react-navigation/issues/8972#issuecomment-714474997), but even that didn't work for me.

@vishal1198 did you ever land on a solid solution for this?

**Comment by brettdh** [comment]
Never mind... silly mistake running my app with the wrong bundler, so my upgrades weren't actually running on the simulator. 🤦 Upgrades have fixed the issue for me (and wrapping the app wasn't necessary).
