### ISSUE TITLE
Published react-native-codegen@0.0.10 is broken

### ISSUE THREAD

**Issue by friederbluemle** [facebook/react-native#32533]
Not sure if something went wrong during publishing of the package yesterday, but looking at the contents of `react-native-codegen@0.0.10` reveals that it only contains 2 files (`README.md` and `package.json`).

The previous version (`0.0.9`) contains 127 files (as expected).

**Comment by friederbluemle** [comment]
Unpacked sizes
https://www.npmjs.com/package/react-native-codegen/v/0.0.9 (920 kB)
vs
https://www.npmjs.com/package/react-native-codegen/v/0.0.10 (1.73 kB)

**Comment by cortinico** [comment]
Thanks for the nice catch @friederbluemle, you're right `react-native-codegen@0.0.10` is broken. It got published with an empty `lib`. That package has no `prepublish` script (we should fix this) so this time the `npm publish`.

I've just published `react-native-codegen@0.0.11`. A PR for the bump is forthcoming. You'll anyway get it if you `yarn install` due to semver.

**Comment by friederbluemle** [comment]
Great thanks @cortinico :+1:

**Comment by TheWirv** [comment]
v0.0.11 does contain the full `lib` folder now. It is still missing the `script` dir, however.

**Comment by cortinico** [comment]
> Nvm, I just noticed that `scripts` was never part of the npm package (at least not since 0.0.8). Now I'm confused why I'm seeing this error. 😅

This should be fixed by codegen `0.0.11`. If not, please let me know.
You were seing that error because the infra was missing the `lib` and was falling back to the `react-native-codegen/scripts/oss/build.sh` script to try to build it, which is used only when we used the codegen from source.

**Comment by TheWirv** [comment]
@cortinico Thanks for checking back. Yes, it is fixed in `0.0.11`, and your explanation makes perfect sense!
