### ISSUE TITLE
Warning: Failed prop type: Invalid prop `autoComplete` of value `password-new`

### ISSUE THREAD

**Issue by TheWirv** [facebook/react-native#32557]
### Description

I am getting this warning when supplying the value `'password-new'` to `TextInput`'s `autoComplete` prop, although this is supported, as per the latest docs. This is the full warning:

```
Warning: Failed prop type: Invalid prop `autoComplete` of value `password-new` supplied to `ForwardRef(TextInput)`, expected one of 
["cc-csc","cc-exp","cc-exp-month","cc-exp-year","cc-number","email","name","password","postal-code","street-address","tel","username","off"].
[...Stack trace]
```

I am guessing this is because of the type discrepancies between [the JS](https://github.com/facebook/react-native/blob/main/Libraries/Components/TextInput/TextInput.js#L331) and [native component](https://github.com/facebook/react-native/blob/main/Libraries/Components/TextInput/AndroidTextInputNativeComponent.js#L99) files.

### Version

0.66.2

### Output of `react-native info`

```
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 13.70 GB / 31.68 GB
  Binaries:
    Node: 16.12.0 - ~\AppData\Local\Temp\yarn--1636384436565-0.4897942578758505\node.CMD 
    Yarn: 1.22.15 - ~\AppData\Local\Temp\yarn--1636384436565-0.4897942578758505\yarn.CMD 
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\Users\mlasaj\AppData\Local\Watchman\bin\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2, 30.0.3, 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.14393.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: 16.11.31624.102 (Visual Studio Enterprise 2019)
  Languages:
    Java: 13.0.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Install RN v0.66.2 on Android
2. Create `TextInput` component
3. Add `autoComplete` prop with value `'password-new'`

### Snack, code example, screenshot, or link to a repository

![Screenshot_1636384608](https://user-images.githubusercontent.com/4397989/140767970-603a5cfd-43f0-4f57-8521-87199b50dd1d.png)

**Comment by TheWirv** [comment]
My assumption that the culprit was the difference between `TextInput` and `AndroidTextInputNativeComponent` was wrong. It was actually `DeprecatedTextInputPropTypes` and I fixed it and created a PR #32575 for it.

**Comment by dusan-dragon** [comment]
@TheWirv I still see this error with 'sms-otp' value in 0.67.1 🤔

**Comment by itsjaychang** [comment]
> @TheWirv I still see this error with 'sms-otp' value in 0.67.1 🤔

The warning seems to be fixed with 0.68 with https://github.com/facebook/react-native/commit/9eb0881c8fecd0e974b1cb9f479bad3075854340

With that said, is anyone able to get the `sms-opt` prop to work? I am unable to have it populate the text field with a SMS with the app hash on the sim

**Comment by dusan-dragon** [comment]
@itsjaychang Yeah we got it working. Make sure you set `importantForAutofill` to true :) and double check the spelling it is `otp` not `opt` - just in case you never now

**Comment by canerd7u** [comment]
> @itsjaychang Yeah we got it working. Make sure you set `importantForAutofill` to true :) and double check the spelling it is `otp` not `opt` - just in case you never now

Hello, How to use it ? i create new RN project with 0.68 version. and i dont how to try this sms-otp ? i open emulator and try sms similator ?

**Comment by dusan-dragon** [comment]
@canerd7u 

To test it out on simulator make sure you are signed in with your google account in simulator, then navigate to settings / privacy settings and there you should see autofill, make sure it is enabled... Another way should be to install some other 3rd party service on your phone which will manage autofill stuff and to test it out with that...

**Comment by DusanVulic74** [comment]
> @itsjaychang Yeah we got it working. Make sure you set `importantForAutofill` to true :) and double check the spelling it is `otp` not `opt` - just in case you never now

than you very much but actually it is not set to true but :

importantForAutofill="yes"
