### ISSUE TITLE
libc.so Crash report by firebase crashlytics in android app 

### ISSUE THREAD

**Issue by RajeshRRathod** [facebook/react-native#33083]
### Description

libc.so
Crashed: Thread #1
SIGSEGV 0x0000000000000020

We can not reproduce crash in some device so this issue device specific or not ? 
Please Give me solution for this crash asap.
 
[open this link to check device list to crash](https://i.stack.imgur.com/qUagO.png)
Crash device list by firebase crashlytics  

**> HUAWEI (86% )**
- Honor 10

**> Samsung  (6%)**
- Galaxy Note9
- Galaxy S9
- Galaxy A13 5G
- Galaxy A02s

**> Xiaomi (3%)**
- Redmi 6
- POCO M3

**> Realme (2%)**
- realme C11

**> INFINIX MOBILITY LIMITED (1%)**

### Version

0.63.4

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 36.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

We can check multiple devices , but we can not reproduce this crash 
we can not reproduce this Crash from below device list 

- Redmi note 7s (OS : 10),
- Samsung Galaxy F62 (OS : 11),
- Huwai (OS : 8.1),
- OnePlus 3 (OS : 11),
- OnePlus node  (OS : 11),
- Samsung m31s (OS:11),
- realme (OS:11),

### Snack, code example, screenshot, or link to a repository
```
0 libhwui.so (Missing UUID dea0f9eed9d9ace602a4e6115205e264)
1 libhwui.so (Missing UUID dea0f9eed9d9ace602a4e6115205e264)
2 libhwui.so (Missing UUID dea0f9eed9d9ace602a4e6115205e264)
3 libhwui.so (Missing UUID dea0f9eed9d9ace602a4e6115205e264)
```
_No response_

**Comment by bigyank** [comment]
I can confirm that I too got the same crash report.
Further investigating, I found that this could be a recurring issue on Samsung devices [[1]](https://stackoverflow.com/questions/19614526/android-crash-system-lib-libhwui-so)[[2](https://stackoverflow.com/questions/24033912/native-crash-at-system-lib-libhwui-so)][[3](https://stackoverflow.com/questions/45993325/android-8-native-crash-at-libhwui-so)].

[Here's](https://github.com/firebase/quickstart-unity/issues/1170) a similar thread on this issue.

Furthermore, in my case, this issue was seen on A12 Samsung devices when the app was launched with wifi on, and then it crashed when the wifi was turned off. I found a thread on this exact issue [here](https://github.com/firebase/firebase-unity-sdk/issues/73)

**Comment by bigyank** [comment]
Has there been any update on this?

**Comment by IseeUDenis** [comment]
I also met this issues. Is there any solution for this?

**Comment by Filippo39** [comment]
I also have the same issue, 200 crashes and 75% due to smasung devices such as:
- Galaxy A51
- Galaxy S10+
- Galaxy S10e
- Galaxy S10
- Galaxy S21 FE 5G
- Galaxy Note10+
- Galaxy S20+
- Galaxy Note10 Lite
- Galaxy S20 Ultra 5G
- Galaxy Z Flip3 5G
- Galaxy A13
- ...

**Comment by deggertsen** [comment]
Similar issues on RN 0.67.3
228 crash events affecting 219 users in the last 24 hours. 86% Samsung.
```
Crashed: Thread :  SIGSEGV  0x0000000000000048
#00 pc 0x6703bc libjsc.so 
#01 pc 0x624 linux-vdso.so.1 
#02 pc 0x16524 libutils.so 
#03 pc 0x16408 libutils.so 
#04 pc 0x151dcc libandroid_runtime.so 
```

**Comment by Hysham** [comment]
I am also having the issue. Any update, please?

**Comment by HessiPard** [comment]
same issue :/ any update?

**Comment by 3NM79** [comment]
We're also facing the same issue with Samsung immediately after the first screen in the app gets mounted
Device: Galaxy A52 5G

**Comment by Hysham** [comment]
I have got rid of this issue by enabling Hermes

**Comment by HessiPard** [comment]
hi, we faced similar crashes on firebase and google play console too:
```
backtrace:
  #00  pc 000000000004e40c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #00  pc 0000000000062730  /apex/com.android.runtime/lib64/bionic/libc.so (__stack_chk_fail+20)
  #00  pc 0000000000653b88  /system/lib64/libhwui.so (GrTextStrike::addGlyphToAtlas(SkGlyph const&, GrMaskFormat, bool, GrResourceProvider*, GrDeferredUploadTarget*, GrAtlasManager*, GrGlyph*)+840)
  #00  pc 0000000000657894  /system/lib64/libhwui.so (GrTextBlob::VertexRegenerator::regenerate(int, int)+712)
  #00  pc 000000000061726c  /system/lib64/libhwui.so (GrAtlasTextOp::onPrepareDraws(GrMeshDrawOp::Target*)+1288)
  #00  pc 0000000000513418  /system/lib64/libhwui.so (GrOpsTask::onPrepare(GrOpFlushState*)+356)
  #00  pc 0000000000501c00  /system/lib64/libhwui.so (GrDrawingManager::flush(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrPrepareForExternalIORequests const&)+1584)
  #00  pc 0000000000502a20  /system/lib64/libhwui.so (GrDrawingManager::flushSurfaces(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&)+132)
  #00  pc 0000000000532bec  /system/lib64/libhwui.so (GrRenderTargetContext::flush(SkSurface::BackendSurfaceAccess, GrFlushInfo const&)+96)
  #00  pc 000000000056780c  /system/lib64/libhwui.so (SkGpuDevice::flush()+48)
  #00  pc 0000000000218154  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+256)
  #00  pc 00000000002151b8  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+416)
  #00  pc 000000000021e198  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+832)
  #00  pc 00000000002205ec  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+480)
  #00  pc 000000000020ed94  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220)
  #00  pc 000000000023006c  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88)
  #00  pc 00000000000154cc  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
  #00  pc 0000000000014d90  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412)
  #00  pc 00000000000b0048  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 00000000000503c8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by WBoda** [comment]
We're also facing the same issue 
any update on this?

**Comment by cortinico** [comment]
Just a small heads up: without a reproducer this can't be fixed.
Moreover, some of the posted stacktraces have references only of `libc` and `libhwui`, which are outside of our control, so I'm unsure this is even related to React Native in the first place.

**Comment by bigyank** [comment]
I was able to solve the issue was by upgrading React Native version to 0.65.2.

**Comment by mluksha** [comment]
I have the save issue (react-native: 0.67.1) only on Android 12:
Galaxy S20 FE 5G
Galaxy S21 5G
Galaxy S21 Ultra 5G
...

**Comment by tarouboy** [comment]
Same issue for me, RN 0.66
Devices are more diverse, data coming from around 70 devices:
<img width="468" alt="Screenshot 2022-06-18 at 11 15 44 AM" src="https://user-images.githubusercontent.com/21119498/174420779-2a26a40f-b85f-4ad0-b87c-1ed00860d359.png">

**Comment by sarons** [comment]
Had same problem. Hermes was always enabled so that wasn't the issue. It was the WebView, found some solutions here
https://github.com/react-native-webview/react-native-webview/issues/1915

`opacity=0.99` in WebView and `overScrollMode ="never"` in ScrollView fixed the issue. Not a single crash since

**Comment by mayankyadav-zepto** [comment]
> Had same problem. Hermes was always enabled so that wasn't the issue. It was the WebView, found some solutions here [react-native-webview/react-native-webview#1915](https://github.com/react-native-webview/react-native-webview/issues/1915)
> 
> `opacity=0.99` in WebView and `overScrollMode ="never"` in ScrollView fixed the issue. Not a single crash since

In your case, app was getting crashed when webview was opened? Do you think this might help when the app is crashing on the launch of first activity?

**Comment by tamarinda** [comment]
In our case we were having this same crash on Android with error log: `libc: Fatal signal 11 (SIGSEGV) ...`
We don't have hermes enabled.

We found out that this was due to a compatibility issues of two dependencies: `react-native-reanimated v2` + `realm` as stated in this thread:
https://github.com/realm/realm-js/issues/3837
Realm doesn't have yet support for hermes, they are currently working on it.

We have decided to remove realm from the project and we are not experiencing this crash anymore.

**Comment by ponikar** [comment]
Is there anyway to reproduce this issue in development mode?

**Comment by mk04366** [comment]
Can everyone make sure they have sufficient memory before the crash? I have this same exact crash but at the time of it, free RAM is around 20-200 Mb only so I think that also might be a reason for it.

**Comment by douglasjunior** [comment]
> Can everyone make sure they have sufficient memory before the crash? I have this same exact crash but at the time of it, free RAM is around 20-200 Mb only so I think that also might be a reason for it.

In crashlytics most report 40mb to 150mb free RAM.

**Comment by serjek** [comment]
Had anyone tried method described in here? https://github.com/facebook/react-native/issues/24261#issuecomment-548149232

**Comment by MarouaniALA** [comment]
any news  here and i can confirm it's not caused by the WebView i commented that part on project

**Comment by wjaykim** [comment]
Add compileOptions with JavaVersion 1.8 like this under your app level build.gradle android block:
```gradle
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by murilogok** [comment]
Fixed in RN 0.66.5 by enabling hermes. 0 new occurrences reported.

**Comment by roneyyb** [comment]
We are still facing this issue majorly on xiaomi and Samsung device after upgrading from react native 0.67.4 to 0.69.9 with hermes enabled. This is the stack trace. Can anyone please provide solution for this?
[com.streakcard_issue_f4e23ef0af3b92e13a709b01f249ecfd_crash_session_646f2d85010f00010a1509de538becb6_DNE_0_v2_stacktrace.txt](https://github.com/facebook/react-native/files/11563486/com.streakcard_issue_f4e23ef0af3b92e13a709b01f249ecfd_crash_session_646f2d85010f00010a1509de538becb6_DNE_0_v2_stacktrace.txt)

**Comment by serjek** [comment]
I have switched to [v8](https://github.com/Kudo/react-native-v8#readme) on android and my user-perceived crash rate went from 8% to below 1% eliminatiing libc.so crash entirely. No performance drawbacks or any other issues discovered for more than 6 months of usage.

**Comment by zjkuang** [comment]
> I have got rid of this issue by enabling Hermes

We still have this issue with `hermesEnabled=true`

**Comment by zjkuang** [comment]
> Add compileOptions with JavaVersion 1.8 like this under your app level build.gradle android block:
> 
> ```groovy-gradle
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> ```
> 
> This fixed my issue in RN 0.71

We still have this issue with this attempt.

**Comment by cnx-caiobarroso** [comment]
Also experiencing this issue with react-native "0.72.3" with hermes enabled. It isn't viable using v8 or any other because almost every lib uses hermes...

**Comment by Arslan106** [comment]
Also experiencing this issue with react-native "0.72.6"

**Comment by 100sarthak100** [comment]
Same issue with react-native "0.73.4"

**Comment by trungledangAxonActive** [comment]
I also got the issue with react native `0.68.7` and hermes is enabled

**Comment by rahulpunchh** [comment]
having same issue

**Comment by AntonioLoco** [comment]
having same issue in react-native@0.74.3 and expo@51.0.18 with hermes enabled

**Comment by zguo123** [comment]
I do not know why this issue is closed. This is **clearly** an issue.

**Comment by 2ducanhpham** [comment]
This error is too serious and there is still no solution.

**Comment by serjek** [comment]
Guys, give a shot to  [v8](https://github.com/Kudo/react-native-v8#readme). I've been using it ever since I posted the comment above and quite happy with current crash rate being under 1%. Besides the more users will switch the more prominent it will become for RN maintainers.

**Comment by 2ducanhpham** [comment]
@serjek  I am using version 0.70 but v8 integration crashes after opening the app.
I am trying to upgrade to 0.73
After upgrade if error still appear i will try v8 integration
![Screenshot 2024-07-29 at 16 20 43](https://github.com/user-attachments/assets/350661ee-5258-447f-92db-b471c93770be)

**Comment by serjek** [comment]
> @serjek I am using version 0.70 but v8 integration crashes after opening the app. I am trying to upgrade to 0.73 After upgrade if error still appear i will try v8 integration ![Screenshot 2024-07-29 at 16 20 43](https://private-user-images.githubusercontent.com/14899775/352990067-350661ee-5258-447f-92db-b471c93770be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDY4NDUsIm5iZiI6MTcyMjI0NjU0NSwicGF0aCI6Ii8xNDg5OTc3NS8zNTI5OTAwNjctMzUwNjYxZWUtNTI1OC00NDdmLTkyZGItYjQ3MWM5Mzc3MGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA5NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZTMxZWY1NTEzNzRkZjUwYmEwNzEzNzIyMWZmMDhiMTJhMzUwZjlhYzZkMzMzMjgzNmNiZmFmNDY4ZmJkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DWOesVQiHCAp3ZiSuOg6WKnKd1w9pZuzenZFkx8HFaw)

did you follow installation steps corretly though? Specifically this one:
<img width="867" alt="image" src="https://github.com/user-attachments/assets/b42867b3-d966-473a-9717-24c6d94db02e">

**Comment by 2ducanhpham** [comment]
@serjek sure, because integration is simple

**Comment by serjek** [comment]
Well in that case you shouldn't be observing `libjsc.so` related crashes, because V8 aims to replace this lib entirely. If that is still the case then perhaps JSC is still somehow crawling into your package - something worth investigation.

**Comment by MSinghBhangu** [comment]
@serjek @2ducanhpham @tamarabernad  @rahulpunchh @cnx-caiobarroso @100sarthak100 Hi , Did you find anything related to this issue causing Sigbart Crash in abundance on start of the application and which is not reproducible happens in release ?

**Comment by 2ducanhpham** [comment]
I have not found the cause and solution yet.

**Comment by michaelpomogajko** [comment]
I'm facing the same issue on RN 0.73, expo 50

**Comment by Kumargaurav11998** [comment]
still getting this issue

**Comment by rjalkuino** [comment]
hi guys , having this issue as well when building bundled apk , but when running in emulator it doesn't crash

**Comment by web3-coder-hub** [comment]
same issue in 0.78.1

**Comment by thisisadarshjaiswal** [comment]
Any solution here? after upgrading RN this has increased too much!
