### ISSUE TITLE
ios socket.io-client is ok, android  ''Error: undefined is not an object (evaluating RCTWebSocketModule.connect)

### ISSUE THREAD

**Issue by jimtang9527** [facebook/react-native#3378]
my project,ios call npm socket.io-client is ok
but android has error.

build.gradle 
compile 'com.facebook.react:react-native:0.12.+'

my code:
var ioc = require('socket.io-client/socket.io') 
var socket = ioc('ws://192.168.0.243:8030', {})
socket.on('connect', function() {
  console.log('socket server connected')
})

![1013_3](https://cloud.githubusercontent.com/assets/7098183/10448870/53122d0c-71c2-11e5-8ad9-64d5dd9b85ed.jpg)

**Comment by satya164** [comment]
WebSocket is not in the 0.12 release.

**Comment by javache** [comment]
This was fixed by #2870

**Comment by whokilledtheelectricmonk** [comment]
I still see this on 0.14-rc. Is there some special way of setting up web sockets? Edit the android manifest or something?

**Comment by ide** [comment]
@whokilledtheelectricmonk do you have an old project? I believe people are using WebSockets successfully so probably a configuration problem on your end unless 0.13 works but 0.14-rc doesn't.

**Comment by whokilledtheelectricmonk** [comment]
The project was created on an older version but all the dependencies are reporting as up-to-date. Is there a way to cleanly update a project's Android component, or compare it to the latest default config?

-----Original Message-----

**Comment by ide** [comment]
There's a brand new tool you could try: https://facebook.github.io/react-native/docs/upgrading.html, though it's hard to beat creating a new project and copying over your JS files in terms of complete reliability.

**Comment by whokilledtheelectricmonk** [comment]
Ok, no more red screen. Submitting #3741 to put a link to that on the README.

**Comment by yash2code** [comment]
same issue
