### ISSUE TITLE
[eslint-config] Environment key "jest/globals" is unknown

### ISSUE THREAD

**Issue by Bardiamist** [facebook/react-native#33955]
### Description

I use `@react-native-community/eslint-config` with TypeScript. After update "@typescript-eslint/eslint-plugin", "@typescript-eslint/parser", and "@typescript-eslint/typescript-estree" from "5.24.0" to "5.25.0" I have error

```
Oops! Something went wrong! :(

ESLint: 8.16.0

Error: .eslintrc.js » @react-native-community/eslint-config#overrides[2]:
        Environment key "jest/globals" is unknown

    at /Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2058:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2052:34)
    at ConfigValidator.validateConfigArray (/Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2202:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3947:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3753:21)
    at FileEnumerator._iterateFilesRecursive (/Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/eslint/lib/cli-engine/file-enumerator.js:446:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/bardiamist/Documents/my-proj/my-proj-mobile/node_modules/eslint/lib/cli-engine/file-enumerator.js:297:49)
    at iterateFiles.next (<anonymous>)
error Command failed with exit code 2.
```

### Version

3.0.2

### Output of `npx react-native info`

```
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.97 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
    Watchman: 2022.05.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
 ```

### Steps to reproduce

Use `@react-native-community`
Run `yarn eslint .`

### Snack, code example, screenshot, or link to a repository

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    'plugin:@typescript-eslint/recommended',
    '@react-native-community',
    'airbnb',
  ],
  ...
};
```

**Comment by Bardiamist** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/5132

**Comment by Bardiamist** [comment]
Looks fixed in typescript-eslint 5.27.1

**Comment by megacherry** [comment]
I had the same error and what worked was yarn-deduplicate, see also this comment: https://github.com/facebook/react-native/issues/32181#issuecomment-966998048

I think it's related.

**Comment by JDMathew** [comment]
Updating `jest` in `package.json` fixed this for me

**Comment by Bardiamist** [comment]
Problem appears often afetr some depencencies update

I fixing by next steps:
1. Set in `package.json` version of `@react-native-community/eslint-config` to `2.0.0` (`3.1.0` don't work)
2. `yarn`
3. Set version back to `3.2.0`
4. `yarn`

**Comment by PrgrmmrOleg** [comment]
Here is what helped me
`npm i eslint-plugin-jest -D`

More details [here](https://stackoverflow.com/questions/69612449/eslint-8-0-1-implementing-jest-into-config-throws-an-error)

**Comment by tonsnoei** [comment]
In my case I was missing the file: `jest.config.js` in the root of my project. I added it with the following contents:
```json
module.exports = {
    preset: 'react-native',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
};
```

**Comment by martinezguillaume** [comment]
For me this command fix it...
`yarn upgrade @typescript-eslint/eslint-plugin @typescript-eslint/parser`

**Comment by fdobre** [comment]
For me this error showed up at upgrading from RN 0.73.9 to 0.74.5,

I fixed it with updating in package.json the following 2 modules vrom v5 to v7:
```
-    "@typescript-eslint/eslint-plugin": "^5.40.1",
-    "@typescript-eslint/parser": "^5.40.1",
+    "@typescript-eslint/eslint-plugin": "^7.18.0",
+    "@typescript-eslint/parser": "^7.18.0",
```

**Comment by jose920405** [comment]
This combination worked for me

devDependencies

```
"@react-native/eslint-config": "0.73.2",
"eslint": "8.19.0",
```

that `eslint-config` version requires also

```
"eslint-plugin-ft-flow": "3.0.7",
```

This is an example of my `.eslintrc.js` file.

```
module.exports = {
  root: true,
  extends: '@react-native',
  rules: {
    'prettier/prettier': 0,
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        'prettier/prettier': 0,
        '@typescript-eslint/no-shadow': ['error'],
        'no-shadow': 'off',
        'no-undef': 'off',
        'no-console': 'error',
        'jsx-quotes': ['error', 'prefer-single'],
        'sort-vars': ['error', { ignoreCase: true }],
      },
    },
  ],
};

```

**Comment by friederbluemle** [comment]
Yes, this error can happen when upgrading React Native and certain TS/ESLint related dependencies are still incorrectly held back by explicit entries in package.json and/or yarn.lock.

An existing project might still have have `@typescript-eslint` dependencies in its package.json, possibly because it was originally based on the (now deprecated) react-native-template-typescript.

Newer versions of `@react-native/eslint-config` **already have direct dependencies** on the correct `@typescript-eslint` packages. If lower versions are declared in package.json, it might accidentally override it and lead to the errors above.

In many cases the simplest solution is the following: 

```
yarn remove @typescript-eslint/eslint-plugin @typescript-eslint/parser
```
