### ISSUE TITLE
iOS 16 upgrade -> No longer validates or uploads to Testflight

### ISSUE THREAD

**Issue by mvniekerk** [facebook/react-native#34716]
### Description

Upgrade of XCode and iOS 16 has broken our RN app.
Reproducable with clean app.

### Version

0.69.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 249.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /Users/mike/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

expo init test
<select Blank Typescript>
cd test
expo eject
cd ios; pod install; cd ../
open ios/test.xcworkspace 
Select release profile
Archive project
Try Validate it

### Snack, code example, screenshot, or link to a repository

https://github.com/mvniekerk/ios16-rn-fail

**Comment by auhonganh** [comment]
Same error after updating Xcode 14.

**Apple Store connect operation error** 
The app references non-public selectors in Payload/: isPassthrough, onSuccess:, removeValuesForKeys:completion:, viewManager

<img width="746" alt="ios_validation_error" src="https://user-images.githubusercontent.com/4928629/190942271-3cb8a77d-6620-4da4-a727-bdb16e9883bc.png">

**Comment by chiragh241** [comment]
+1

**Comment by arnaudschlupp** [comment]
Same one here (no pod updates or package addition since the last release), guessing the issue comes from Apple backend validation from what I read so far

```
The app references non-public selectors in Payload/nameoftheapp.app/nameoftheapp: isPassthrough, onSuccess:, removeValuesForKeys:completion:, setHighlightsToday:
```

**Comment by EddyDunda** [comment]
Any updates?

**Comment by karltaylor** [comment]
Can these still be submited, reviewed and released on the App Store?

I managed to upload to Testflight and download and install on a device. Need to release to store so will check.

**Comment by xgenem** [comment]
App was still uploaded however.

Waiting to see if it can be installed.

**Comment by xgenem** [comment]
Confirmed. The uploaded build worked well.

**Comment by mvniekerk** [comment]
Does not upload for us.
<img width="752" alt="Screenshot 2022-09-20 at 09 09 42" src="https://user-images.githubusercontent.com/1570687/191190815-48f75fbb-6686-461e-8871-fdb73d37caa1.png">

**Comment by mvniekerk** [comment]
Weird! Just minutes later I get a notification that it has uploaded and it is ready to be tested.

**Comment by auhonganh** [comment]
I have validated the app's success after having downgraded Xcode to **13.4.1**.

**Comment by tradebulls** [comment]
+1 Getting Same issue with Xcode + iOS 16 and React Native 69

**Comment by karltaylor** [comment]
> Can these still be submitted, reviewed and released on the App Store?
> 
> I managed to upload to Testflight and download and install on a device. Need to release to store so will check.

Want to update and confirm if you are on a tight schedule @auhonganh has [best answer here](https://github.com/facebook/react-native/issues/34716#issuecomment-1253319285), stay on **13.4.1** for now.

**Comment by wojtekmaj** [comment]
I'm happy to say I've built two apps using RN 0.70 + Xcode 14, pushed them to TestFlight, got the warning this thread is all about, and they passed Review process with no issues whatsoever.

**Comment by auhonganh** [comment]
> > Can these still be submitted, reviewed and released on the App Store?
> > I managed to upload to Testflight and download and install on a device. Need to release to store so will check.
> 
> Want to update and confirm if you are on a tight schedule @auhonganh has [best answer here](https://github.com/facebook/react-native/issues/34716#issuecomment-1253319285), stay on **13.4.1** for now.

@karltaylor: Yes, I submitted and passed the review process by Apple Store.

**Comment by princefishthrower** [comment]
@wojtekmaj To clarify, despite the warning messages, your app _did_ appear in App Store Connect eventually as normal after some time?

**Comment by princefishthrower** [comment]
Update: I just noticed despite the app store connect message saying it is an "error", the title of the window _does_ say "Distribution completed with warnings".

**Comment by edritech93** [comment]
same issue, using :
Xcode 14
React Native 0.70.4

**Comment by bsonmez** [comment]
> same issue, using :
> Xcode 14
> React Native 0.70.4

same here

**Comment by avuenja** [comment]
+1

**Comment by pavshr** [comment]
> same issue, using : Xcode 14 React Native 0.70.4

same

**Comment by methineeinkan** [comment]
same issue, using :
Xcode 14
React Native 0.69.7

**Comment by edritech93** [comment]
same issue, using:
Xcode 14.1
React Native 0.70.6

**Comment by jeong-sik** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/45959991/206619001-45d315b8-269b-434b-8804-956923953298.png">

RN: 0.70.6
Xcode: 14.1

The Minimum Deployment was 12.4, but when I changed it to 11.0, it was uploaded correctly.

**Comment by AngelDev727** [comment]
I was solved this problem by downgrade Minimum Deployment.
The Minimum Deployment was 12.4, but when I changed it to 12.0, it was uploaded correctly.

**Comment by IlanZ93** [comment]
Hey my minimum deployment was 10.0 i changed to 11.0, but i still have the warning, did anyone know how to get rid of this warning without downgrading xcode or upgrading RN ?

React Native 0.63.5
xCode : 14.2 (14C18)
macOS : 13.2 (22D49)

**Comment by chuyihuang** [comment]
> 

mine is exactly the same. I am using RN0.64.4....it was so weird some builds were successfuly uploaded, but after half an hour they all gone. disappeared from the testflight tab without any warning from apple

**Comment by Ahmetaksungur** [comment]
> > 
> 
> mine is exactly the same. I am using RN0.64.4....it was so weird some builds were successfuly uploaded, but after half an hour they all gone. disappeared from the testflight tab without any warning from apple

I have the same problem. Did you find a solution?

**Comment by waqaskhanroghani** [comment]
finally I solve the problem  => 
1: Minimum Deployments IOS version change from 12.4 to 12.0.
2: rebuild the app

**Comment by aklevko** [comment]
How to solve this problem without downgrade Minimum Deployment?

**Comment by mihaibulic2** [comment]
+1, RN dictating our min deployment is unacceptable.  What else can be done?

**Comment by mklb** [comment]
The minimum iOS version change to 11.0 did not do the trick for me. So I left it at 12.0.

**I submitted and got my app approved with the errors twice now.** I think we can ignore the errors for now.
