### ISSUE TITLE
bundleRelease Error: Execution failed for task ':app:bundleReleaseJsAndAssets'.

### ISSUE THREAD

**Issue by OmarThinks** [facebook/react-native#35583]
### Description

# React-Native-Build-Error

https://github.com/OmarThinks/ReactNativeBuildError

# Acknowledgement:

Thank you so much React Native Team for your hard and consistent work.

# Reporducability of issue:

Here the are 2 projects: https://github.com/OmarThinks/ReactNativeBuildError  
I have created a Github repo to make it easy for you to spot the error.  
JS and TS projects.  
I have been stuck here for 3 consecutive days.  
I tried everything I could find.  
https://stackoverflow.com/questions/59695135/react-native-android-build-process-command-npx-cmd-finished-with-non-zero
https://github.com/facebook/react-native/issues/28510  
None of these soltions worked.  
I have also tried several React native versions, and tried changing Gradle versions, and JDK versions. None of these worked.

# How I Generated these projects:

```bash
npx react-native init AwesomeProject
```

```bash
npx react-native init AwesomeTSProject --template react-native-template-typescript
```

I did not add any other code to the templates, just signning the keys.

# Error:

```bash
$ ./gradlew bundleRelease
> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
8 actionable tasks: 3 executed, 5 up-to-date
```

# Key:

Key is already generated on `/android/app/my-upload-key.keystore`. But, if you want to regenerate a new key, you can follow the steps below:

```bash
keytool -genkey -v -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000


MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=abcdefghijklmnop
MYAPP_UPLOAD_KEY_PASSWORD=abcdefghijklmnop
```

# Acknowledgement (Again):

Thank you so much React Native Team for your hard and consistent work.  
You saved us from Java.

### Version

0.70.6

### Output of `npx react-native info`

$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 18.15 GB / 31.83 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.17 - /c/Program Files/Eclipse Adoptium/jdk-11.0.17.8-hotspot/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

# Reproduction:

## 1) GitHub Repo:
https://github.com/OmarThinks/ReactNativeBuildError  
I have created this GitHub repo which contains all the code to help run the code easily.

## 2) Normal way of creating templates:

```bash
npx react-native init AwesomeProject
```

```bash
npx react-native init AwesomeTSProject --template react-native-template-typescript
```

### Snack, code example, screenshot, or link to a repository

https://github.com/OmarThinks/ReactNativeBuildError  

Thank you so much for your hard, patient, and persistent work!

**Comment by therafibhuiyan** [comment]
My problem was the same as yours, but the command (.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets) solved it for me now I am facing another issue, which is that when I run the command (npx react-native run-android) everything is fine, but when I build an APK by using this command (.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets) it's crashes.

**Comment by OmarThinks** [comment]
> My problem was the same as yours, but the command (.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets) solved it for me now I am facing another issue, which is that when I run the command (npx react-native run-android) everything is fine, but when I build an APK by using this command (.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets) it's crashes.

Hello! @therafibhuiyan  
It must crash.  
Because `.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets`, that `-x` I believe means `without`.  
So, there will be no bundling for Release of JS and Assists.  
So, it must crash.  
I will never ever use this `-x bundleReleaseJsAndAssets` again. 
:)

**Comment by therafibhuiyan** [comment]
> > My problem was the same as yours, but the command (.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets) solved it for me now I am facing another issue, which is that when I run the command (npx react-native run-android) everything is fine, but when I build an APK by using this command (.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets) it's crashes.
> 
> Hello! @therafibhuiyan It must crash. Because `.\gradlew app:assembleRelease -x bundleReleaseJsAndAssets`, that `-x` I believe means `without`. So, there will be no bundling for Release of JS and Assists. So, it must crash. I will never ever use this `-x bundleReleaseJsAndAssets` again. :)

Hello! @OmarThinks
Someone told me it basically binds all of my app's artifacts and makes a release version APK ready to be deployed for production. But it seems to me that I have made a mistake by using this command.

**Comment by OmarThinks** [comment]
@therafibhuiyan I am not 100% sure what it means. Maybe he is right.  
But the app crashes every time I do this. LOL!
I tried lots of things. :)

**Comment by therafibhuiyan** [comment]
@OmarThinks 
The development of my application has been completed but I am unable to push it to the production build due to this issue.

**Comment by OmarThinks** [comment]
@therafibhuiyan 
`.\gradlew app:assembleRelease`  
`.\gradlew bundleRelease`  
Are correct.  
Or also you can use android studio to generate the APK or Bundle.  
Top Bar => Build => Generate Signed Bundle / APK  
All of these should work.  
But, I meant that this **`-x bundleReleaseJsAndAssets`** is the one that I will never use again. :) :)
-----------
Yeah. I agree with you!
The React Native Team is doing Great work. I really can't thank them enough.  
I just wish they resolve that tiny little bug.
:) :)

**Comment by therafibhuiyan** [comment]
@OmarThinks 
After doing some research, I was able to build a working APK. First I have to install React-Native globally by using `npm install -g react-native-cli`. I changed the ExecutionPolicy by running `Set-ExecutionPolicy Unrestricted` in PowerShell on administrator power, Then, I created a folder called assets in `android/app/src/main/` this directory. Once that's done, I run `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` from the root of the project and then run this `./gradlew assembleRelease -x bundleReleaseJsAndAssets` from the android folder. Now I just have to create an abb file and let's see what happens.

**Comment by cortinico** [comment]
> According to the RN official documentation if we want to create an abb file then we have to use `./gradlew bundleRelease.` If this is a bad practice then why in the official documentation they mentioned this command to generate an abb file?

Sorry for being confusing, I've edited my answer with a clarification. In general the CLI offers a variety of commands (like `react-native run-android`) that help you achieve most of the things you need. For `bundleRelease` there is no such command (we're actually recently introduced `react-native build-android` so we might consider it for this scenario).

> Then, I created a folder called assets in android/app/src/main/ this directory. Once that's done, I run react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res from the root of the project and then run this ./gradlew assembleRelease -x bundleReleaseJsAndAssets from the android folder

In general, you should not invoke `react-native bundle` manually. If you just invoke `./gradlew bundleRelease`, the bundling will be done for you.
The fact that the task is failing with `Execution failed for task ':app:bundleReleaseJsAndAssets'.` means that there is an underlying issue in your setup, taht you're not fixing and you're just circumventing

**Comment by therafibhuiyan** [comment]
@cortinico 
It might be a problem with my setup, but if we search on the internet for the exact same issue, we'll find out that there are many people experiencing this issue as well. Various approaches are being taken to fix this. Let's just forget about it all and just focus on what @OmarThinks says. He just generated the template and did not add any other code to the template, just signed the keys but still got the same problem. What are you'll gonna say about this?

**Comment by cortinico** [comment]
> It might be a problem with my setup, but if we search on the internet for the exact same issue, we'll find out that there are many people experiencing this issue as well

Could you share those links please?

> Let's just forget about it all and just focus on what @OmarThinks says. He just generated the template and did not add any other code to the template, just signed the keys but still got the same problem. What are you'll gonna say about this?

If that is the case, then this is a bug I'd like to address/handle.
@OmarThinks can you share your full build log?
Also can you try the same on the latest RC of `0.71.x` as I believe this issue is already solved:

```
npx react-native init AwesomeProject --version next
```

**Comment by therafibhuiyan** [comment]
There are two links to this error.
[Stackoverflow](https://stackoverflow.com/questions/49513047/react-native-assemblerelease-fails-for-task-appbundlereleasejsandassets)
[Github](https://github.com/facebook/react-native/issues/28510)

**Comment by OmarThinks** [comment]
@cortinico @therafibhuiyan 
This is the code (As mentioned in the description).  https://github.com/OmarThinks/ReactNativeBuildError 
I would like to thank you so much Mr. @cortinico for your care and support.  :)  
And thank you so much @therafibhuiyan for helping me clarify the error.  

-----

The code there is just the plain code without any edits   
There were only 2 edits made:  
1. The guides for the keystore and adding the keystore file
2. Modifing `.gitignore` to accept the keystore file.

Other than that, it is just the plain code from running the following commands
```bash
npx react-native init AwesomeProject
npx react-native init AwesomeTSProject --template react-native-template-typescript
```
For both the JS template and the TS Template.

:) :) :)
Thank you so much for your effort!
:) :) :)
I really can't think you enough guys.
@cortinico  @therafibhuiyan

**Comment by OmarThinks** [comment]
This is the error:
```bash
$ ./gradlew bundleRelease
> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
8 actionable tasks: 3 executed, 5 up-to-date
```

The same error occurs when I use android studio:  
Top Bar => Build => generate Signed Bundle/APK  
I have tried lots of things.  
:) :) :)
Thnk you so much!

**Comment by OmarThinks** [comment]
> There are two links to this error. [Stackoverflow](https://stackoverflow.com/questions/49513047/react-native-assemblerelease-fails-for-task-appbundlereleasejsandassets) [Github](https://github.com/facebook/react-native/issues/28510)

@cortinico 
As @therafibhuiyan mentioned, I and @therafibhuiyan are not the only people suffering from this tiny little bug.  
I guess too many are.

Thank you so much! :) :)

**Comment by OmarThinks** [comment]
> > It might be a problem with my setup, but if we search on the internet for the exact same issue, we'll find out that there are many people experiencing this issue as well
> 
> Could you share those links please?
> 
> > Let's just forget about it all and just focus on what @OmarThinks says. He just generated the template and did not add any other code to the template, just signed the keys but still got the same problem. What are you'll gonna say about this?
> 
> If that is the case, then this is a bug I'd like to address/handle. @OmarThinks can you share your full build log? Also can you try the same on the latest RC of `0.71.x` as I believe this issue is already solved:
> 
> ```
> npx react-native init AwesomeProject --version next
> ```

@cortinico 
Yes, sir!  
I will do them both right immediately (If God willed) as soon as possible.  
The edits will be in the repo: https://github.com/OmarThinks/ReactNativeBuildError
While working on the repo, I just used the commands:  
```bash
npx react-native init AwesomeProject
npx react-native init AwesomeTSProject --template react-native-template-typescript
```
I did not specify the version, so the version used was :
```
    "react-native": "0.70.6"
```
As can be seen here:  
https://github.com/OmarThinks/ReactNativeBuildError/blob/master/AwesomeProject/package.json#L14   
https://github.com/OmarThinks/ReactNativeBuildError/blob/master/AwesomeTSProject/package.json#L14

------

If God willed, I will try The versions that you suggested immediately: `0.71.x`, and `next`.  

Thank you so much!  
:) :) :) 👍 💯

**Comment by OmarThinks** [comment]
@cortinico  
Update!  
I tried version `0.71.x` using this command:  

```bash
$ npx react-native init AwesomeProject71 --version 0.71

                  Welcome to React Native!
                 Learn once, write anywhere

- Downloading template
× Downloading template
error Error: Command failed: npm install --save --save-exact react-native@0.71
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native@0.71.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MainUser\AppData\Local\npm-cache\_logs\2022-12-08T17_15_03_983Z-debug-0.log
.
Error: Error: Command failed: npm install --save --save-exact react-native@0.71
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native@0.71.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MainUser\AppData\Local\npm-cache\_logs\2022-12-08T17_15_03_983Z-debug-0.log

    at createFromTemplate (C:\Users\MainUser\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\commands\init\init.js:169:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initialize [as func] (C:\Users\MainUser\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\commands\init\init.js:222:3)
    at async Command.handleAction (C:\Users\MainUser\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\index.js:140:9)
info Run CLI with --verbose flag for more details.
```

---

## Conclusion:  
I guess `0.71.x` has not been released yet.

----
Now, if God willed, I will try `next`.  
Thank you so much!

:) :) :) 👍 💯

**Comment by cortinico** [comment]
> There are two links to this error.
> [Stackoverflow](https://stackoverflow.com/questions/49513047/react-native-assemblerelease-fails-for-task-appbundlereleasejsandassets)
> [Github](https://github.com/facebook/react-native/issues/28510)

@therafibhuiyan the two links you shared are for way older version of RN and makes impossible for us to reproduce/fix those kind of issues.

> I am testing it right now.

@OmarThinks please let me know if in 0.71 the issue is fixed

**Comment by OmarThinks** [comment]
@cortinico 
Sure, sir!  
I am working on it.  
:) :)

**Comment by OmarThinks** [comment]
@cortinico 

## Update:

I concluded that `0.71` is the same as `next`.

I used this command to create the `next` template:

```bash
npx react-native init AwesomeProjectNext --version next
```

And, here it is:

https://github.com/OmarThinks/ReactNativeBuildError/blob/master/AwesomeProjectNext/package.json#L14

I can't work on `next`. Because `next` depends on (AGP (Android Gradle Plugin) 7.4.0-beta05), which is still in development, and I can't even figure out how to install it manually.

<img src="https://github.com/OmarThinks/ReactNativeBuildError/blob/master/Media/next-error.png?raw=true"/>

The last supported AGP version by android studio is `7.3.1`.

<img src="https://github.com/OmarThinks/ReactNativeBuildError/blob/master/Media/Supported_AGP.png?raw=true"/>

https://developer.android.com/reference/tools/gradle-api

**Comment by cortinico** [comment]
Thanks for the update. That's expected as we're still in RC. You would need a beta of Android Studio to open it.

Does it work from the command line though?

**Comment by OmarThinks** [comment]
@cortinico  
I tried as you told me, sir!  
That was the result.  

```bash
 $ cd AwesomeProjectNext/
 $ cd android/
 $ ./gradlew bundleRelease
> Task :app:createBundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
9 actionable tasks: 7 executed, 2 up-to-date
```

**Comment by OmarThinks** [comment]
If something is wrong with my setup, this should spot it:

```bash
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 6.23 GB / 31.83 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022)
  Languages:
    Java: 19.0.1 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0-rc.3 => 0.71.0-rc.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by OmarThinks** [comment]
Also this:
```bash
$ npx @react-native-community/cli doctor
- Running diagnostics...
Common
 ✓ Node.js
 ✓ npm

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   0
Warnings: 0
```

**Comment by cortinico** [comment]
> I tried as you told me, sir!
> That was the result.

Thanks for the heads up. This seems to be a Windows specific issue. We'll have to look into it next week.

**Comment by OmarThinks** [comment]
@cortinico Thank you so much!  
:) :)

**Comment by therafibhuiyan** [comment]
@cortinico we look forward to receiving the patch shortly. Thank you so much.

**Comment by meetajhu** [comment]
@therafibhuiyan still facing the same issue. Using RN 0.71.

![image](https://user-images.githubusercontent.com/3233495/213174372-64480011-b444-42a3-a41a-9ff223ab5b33.png)

**Comment by therafibhuiyan** [comment]
@meetajhu 
Maybe they are working on the patch & I hope the patch will come soon. If you're facing the same issue you don't need to change anything just follow my instruction. 

1. Install React-Native globally by using npm install -g react-native-cli. 
2. Changed the ExecutionPolicy by running Set-ExecutionPolicy Unrestricted in PowerShell on administrator power.
3. Created a folder called assets in android/app/src/main/ this directory.
4. Run react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res from the root of the project.
5. Run this ./gradlew assembleRelease -x bundleReleaseJsAndAssets from the android folder.
6. Run this ./gradlew bundleRelease -x bundleReleaseJsAndAssets from the android folder.

I'm generating APK & ABB file by this. Now it's up to you. You can use this or you can wait for the patch.

**Comment by OmarThinks** [comment]
@therafibhuiyan 
I thought that `... -x bundleReleaseJsAndAssets ` would create the APK.  
But it won't run.  
Because this generates the APK without assets.  
:) :)

**Comment by meetajhu** [comment]
@therafibhuiyan This PR fixed it. 

https://github.com/facebook/react-native/pull/35872/files

**Comment by cortinico** [comment]
Hey @OmarThinks,
Is the issue still happening for you on React Native 0.71.0 on a Windows Machine?

The PR that @meetajhu linked is unrelated.

**Comment by OmarThinks** [comment]
@cortinico  
I will try it ASAP, sir!  
I am just kinda busy now.  
I will try it in a few hours, and provide feedback!
:)  :)

**Comment by OmarThinks** [comment]
Hello, @cortinico!   
So, I have tried.  



<details>
  <summary><h2>I got this error:  </h2> </summary>
  
```
$ ./gradlew bundleRelease
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :app:createBundleReleaseJsAndAssets FAILED
Execution optimizations have been disabled for task ':app:createBundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'D:\Dev\New folder\DeleteLater\AwesomeProject\android\app\build\generated\res\react\release'. Reason: Task ':app:mergeReleaseResources' uses this output of task ':app:createBundleReleaseJsAndAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 1m 54s
24 actionable tasks: 22 executed, 2 up-to-date
```
</details>

# For Diagnosis:
I am using Windows 11.  
If there is a problem in my configurations, I am willing to admit.

<details>
  <summary><h3>1) React Native Doctor :</h3> </summary>
  
```
$ npx @react-native-community/cli doctor
- Running diagnostics...
Common
 ✓ Node.js
 ✓ npm

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

Errors:   0
Warnings: 0
```
</details>
<details>
  <summary><h3>2) React Native Info :</h3> </summary>
  
```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 14.16 GB / 31.83 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 25, 28, 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-29 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022)
  Languages:
    Java: 19.0.1 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.0 => 0.71.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
</details>


Thank you so much!
:)

**Comment by cortinico** [comment]
>   - Gradle detected a problem with the following location: 'D:\Dev\New folder\DeleteLater\AwesomeProject\android\app\build\generated\res\react\release'. Reason: Task ':app:mergeReleaseResources' uses this output of task ':app:createBundleReleaseJsAndAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

@OmarThinks could you try again making sure there are no spaces in your path, as this could be a duplicate of https://github.com/facebook/react-native/issues/34878 ?

**Comment by OmarThinks** [comment]
@cortinico 

<details>
  <summary><h3>Looks like the same error </h3> </summary>
  
```
~ ... /d/Dev/rn/AwesomeProject/android
$ ./gradlew bundleRelease
> Task :app:createBundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
9 actionable tasks: 7 executed, 2 up-to-date
```
</details>


Thank you! :) :)

**Comment by cortinico** [comment]
Thanks for the report. There is something going on with the Windows setup on 0.71 that needs to be investigated. I don't have a Windows machine with me at the moment, I'll follow up as soon as I have one (cc @kelset @mganandraj)

**Comment by OmarThinks** [comment]
Thank you!

**Comment by JulioRosil** [comment]
Hello @OmarThinks , did you tried on Mac or Linux?

I have the same issue in both Windows 11 machines and i'm gonna try it on Mac from zero.


```
> Task :app:createBundleReleaseJsAndAssets FAILED
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1
```

**Comment by OmarThinks** [comment]
@JulioRosil   
Hello!  
A windows machine is all I got.  
I really do not have a Linux or a MacOS machine.  
:) :)

**Comment by JulioRosil** [comment]
@OmarThinks 
Ok thanks, i'm gonna try on Mac M1 and comment if the issue is solved. :)

**Comment by OmarThinks** [comment]
@JulioRosil 
Please note!  
If you try it on a MacOS or Linux, and the problem does not show up, and everything works fine, that does not mean the problem is closed.  
Because the original problem is on a windows machine.  
But the info that you will provide us about the situation in other operating systems is indeed helpful.  
:) :) 👍

**Comment by mganandraj** [comment]
Hi @OmarThinks Looks like you are building from WSL. Did you try from vanilla command prompt ?

**Comment by OmarThinks** [comment]
@mganandraj 
I use git bash.  
:)

**Comment by mganandraj** [comment]
@OmarThinks 
Could you try building from standard windows command prompt (cmd.exe). Also add the following to the gradle.properties file,

REACT_WINDOWS_BASH=c:\\program files\\git\\bin\\bash.exe

**Comment by JulioRosil** [comment]
Hey @OmarThinks @cortinico ,

It actually worked on Mac with M1 chip. Just following the MacOS Android guides from React Native site.

My app is using react-native@0.71.1 compiled with Zulu11.

We also tried on Windows 11 and it failed. So it seems it's a Windows issue.

Hope it helps :)

**Comment by OmarThinks** [comment]
@JulioRosil 
Thanks for letting us know.  
I really appreciate your feedback.  
:) :)  
And yeah. It looks like a windows issue.

**Comment by OmarThinks** [comment]
@mganandraj 

----

I apologize for my late response.

-----

I have just discovered that cmd is not opening on my PC, for some reason.  
I open it, it just closes immediately.  
Maybe there is a corrupt file on my PC.  
Troubleshooting this problem will take me time.   

----
@JulioRosil @therafibhuiyan   
If someone gives us a hand here, it will be awesome.   
Thank you so much!

**Comment by OmarThinks** [comment]
@mganandraj @JulioRosil @therafibhuiyan 
Update:  
I solved the cms problem.  
Now I will try this method.  
:) :)

**Comment by OmarThinks** [comment]
Well, something weird happened. :) :)   
@mganandraj 


<details>
<summary>I created 2 new react native apps, `next`, and `0.70`. </summary>

```
npx react-native init abcd
npx react-native init abc0 --version 0.70
```   
Then I rebuilt the project on android studio.  

</details>



Then I ran `./gradlew bundleRelease`.  
It worked for both of them, without any changes, and using git bash.  
(But they are not debuggable (that looks like another story - out of current topic)).

-----
So maybe one of these two reasons is true:

## 1) RN templates were updated:
React Native templates were updated to solve the release problem.  
That's why generating bundle releases happened successfully.

## 2) We (complaining Windows users) got `cmd` corrupted:
We all need to follow the steps in this video: https://www.youtube.com/watch?v=xT9OyVlyT3I  
Because once I followed these steps, it worked.
(Or maybe, React Native team should put into account that maybe, some windows users got cmd corrupted.)

-----

@JulioRosil @therafibhuiyan 
Just a small task guys, if got extra time. it won't take a minute.  
Does `cmd` crash on your PC?  
Did you have the same problem that I found its solution (in this video: https://www.youtube.com/watch?v=xT9OyVlyT3I)?  

1) Go to the search bar in Windows
2) type `cmd`
3) Simply just open the first item (Command Prompt)
4) Do not type anything


Will the cmd window open normally when you open it, or will it crash crash?  
Thank you so much!  
:) :) :)

**Comment by JulioRosil** [comment]
@OmarThinks hey,

In my case CMD works fine, not crashing.

Hope it helps :)

**Comment by OmarThinks** [comment]
I think that the problem is solved on my PC.  





<details>
<summary>As I mentioned earlier, there are 2 probabilities.</summary>

## 1) RN templates were updated:
Maybe React Native templates were updated to solve the release problem.  
That's why generating bundle releases happened successfully.

## 2) We (complaining Windows users) got `cmd` corrupted:
Maybe We all need to follow the steps in this video: https://www.youtube.com/watch?v=xT9OyVlyT3I  
Because once I followed these steps, it worked.
(Or maybe, React Native team should put into account that maybe, some windows users got cmd corrupted.)
</details>






  
But I suggest that before we close, we need feedback from more users other than me.  
It is just a suggestion.  
If you can give us a hand guys, that will be highly appreciated before we close.  
@therafibhuiyan @JulioRosil

**Comment by OmarThinks** [comment]
@therafibhuiyan @JulioRosil 
If anyone can try to generate an APK or Bundle now and see if it works it will be highly appreciated.  
:) :)  
Thank you!

**Comment by fadlifr** [comment]
> 
hi @OmarThinks ,
i still have the problem when run gradlew assembleRelease.
the error message exactly like yours.
i have tried "gradlew clean, gradlew --stop",
still failed.
would you explain it to me how you resolved the error ?
much apperciate

**Comment by OmarThinks** [comment]
@fadlifr 

Try these steps in a new project

### 1) Create new app

```
npx react-native init AwesomeProject
```

### 2) Build project:
In android studio, Open `AwesomeProject/android`  
Wait for it to build, then `Build` => `Rebuild project` inside android studio



### 3) Generate and bundle.

```
cd AwesomeProject/android
./gradlew bundleRelease
```


---
Try these steps, if they do not work, let me know, please. 

:) :)

**Comment by fadlifr** [comment]
> @fadlifr
> 
> Try these steps in a new project
> 
> ### 1) Create new app
> ```
> npx react-native init AwesomeProject
> ```
> 
> ### 2) Build project:
> In android studio, Open `AwesomeProject/android` Wait for it to build, then `Build` => `Rebuild project` inside android studio
> 
> ### 3) Generate and bundle.
> ```
> cd AwesomeProject/android
> ./gradlew bundleRelease
> ```
> 
> Try these steps, if they do not work, let me know, please.
> 
> :) :)


Thanks bro @OmarThinks 
your solution works for the new template
but my project still error
and  i can not redo my project with new template..

**Comment by OmarThinks** [comment]
@fadlifr 
I understand.  
I think in that case it can work on a MacOS or a Linux.  
I think it was easy for React Native development team to fix this issue on the new release.  
But it is harder to fix for previous releases.  

----
So I am closing the issue.  
:) :)
Thanks to the React Native dev team.

**Comment by cortinico** [comment]
Just a small heads up that I've tested this on 0.71 today and I can confirm that everything works as expected

**Comment by 7geekerLarr** [comment]
I have the same issue in Windows 11 machine


react": "18.2.0",
"react-native": "0.71.2",


2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installRelease -PreactNativeDevServerPort=8081
"C:\PROYECTOS" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s

    at makeError (C:\PROYECTOS 2023\xaf\node_modules\execa\index.js:174:9)
    at C:\PROYECTOS 2023\xaf\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\PROYECTOS 2023\xaf\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\PROYECTOS 2023\xaf\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

**Comment by shivenmian** [comment]
@7geekerLarr This is because you have a space in your path (`C:\PROYECTOS 2023\xaf`). A fix for this has been added - see [this comment](https://github.com/facebook/react-native/issues/34878#issuecomment-1420974718) - and will be available in the next version or point release for RN71.

**Comment by hasan-abir** [comment]
> @7geekerLarr This is because you have a space in your path (`C:\PROYECTOS 2023\xaf`). A fix for this has been added - see [this comment](https://github.com/facebook/react-native/issues/34878#issuecomment-1420974718) - and will be available in the next version or point release for RN71.

This solved it. Now I'm kinda scared to put spaces in folder paths on my machine...

**Comment by w4t3r-45** [comment]
doing yarn install made a fix for me , i was building using fastlane , just in case.

**Comment by rajveernic** [comment]
To remove this error  > Task :app:bundleReleaseJsAndAssets FAILED  just simply enable false the enableHermes
 project.ext.react = [
    enableHermes: false, 
]

**Comment by ceconcarlsen** [comment]
any work around for W11 users?

**Comment by codingslash76** [comment]
@cortinico  I am also getting the same error with the latest RN (0.76.5) on MacOS. I have described it in the above issue.☝️

**Comment by starkfire** [comment]
This still happens in RN 0.76.6 (Windows 11) and I solved this by running `.\gradlew assembleRelease --info` instead of using the `--stacktrace` option. It is somehow misleading at first glance, since it seems like `cmd` is not being found:

```
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1
```

The real problem is the instruction that the build process is trying to invoke using `cmd`. Instead of displaying the instruction that caused the failure, it instead displays a message that seems to imply that the reason for the failure was `cmd`.

Passing the `--info` option is only when you'll get hints about the `cmd` instructions being invoked along the way. For instance:

```
cmd /c node ..\..\node_modules\react-native\cli.js bundle --platform android --dev false --reset-cache --entry-file index.js --bundle-output .\android\app\build\generated\assets\createBundleReleaseJsAndAssets\index.android.bundle --assets-dest .\android\app\build\generated\res\createBundleReleaseJsAndAssets --sourcemap-output .\android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.map --minify false --verbose
```

If I call this from CMD/Powershell manually, this will then fail because `node` is not found. Thus, it is not `cmd` which caused Gradle to fail here, but the fact that `cmd` failed because the instruction it is trying to invoke failed (i.e., `node` is not found). In my case, Powershell can find the path to `node` but not CMD, so I had to edit my environment variables as a solution (this may happen when you also install Node using tools like [fnm](https://github.com/Schniz/fnm), which would give you a different path to `node` if you try to call `which`).

By trying to follow through `--info` outputs, you might also encounter issues like this: https://github.com/facebook/react-native/issues/35927. From this issue, you'll then realize that `hermesCommand` should be provided a path to `hermesc` relative to the app project's root directory, not from `/android/app`. I think this detail might be useful to people working on monorepos.

Overall, I think this issue could be better resolved if there would just be clearer log messages from Gradle/RN whenever `gradlew` is being called. Using the `--stacktrace` option here wouldn't suffice, since it wouldn't give you clear information about the instructions that Gradle is trying to invoke along the way. 

There is a chance that in most cases that this happened, it is more of an environment issue rather than an actual issue in RN, and unclear log messages made it seem like an RN problem.

**Comment by Manikanta-duEITC** [comment]
Anyone solution for this issue, i am on react-native0.80?

**Comment by liusAlviando** [comment]
Anyone solution for this issue, i am on react-native 0.81?

**Comment by liusAlviando** [comment]
> Anyone solution for this issue, i am on react-native 0.81 on mac?

i got this handled,

some times your gradle is stuck with older node version,
make sure to run 
`./gradlew --stop`

and 

`rm -rf $TMPDIR/metro-*`

or clean all the build and node_modules

**Comment by YuryCSilva** [comment]
> Alguém tem alguma solução para esse problema? Estou usando o React Native 0.81.

Hey man, I faced this issue in my project... I really don't know what caused it, but you can follow my steps to fix it, maybe it can help you:
- First, I run ```./gradlew assembleRelease --info``` and after running this command, I encounter the error "Error: Cannot find module 'babel-preset-expo'"
- After understanding the error above, I run ```npm install babel-preset-expo``` and I can run my code.

I hope these steeps can help you.

**Comment by aslihanturkdonmez** [comment]
Android Studio had automatically switched to JDK 21.
After switching back to JDK 17 under
Android Studio → Settings → Build, Execution, Deployment → Build Tools → Gradle → Gradle JDK,
the issue was resolved for me.

**Comment by nikhilg-cyber** [comment]
> > [@7geekerLarr](https://github.com/7geekerLarr) This is because you have a space in your path (`C:\PROYECTOS 2023\xaf`). A fix for this has been added - see [this comment](https://github.com/facebook/react-native/issues/34878#issuecomment-1420974718) - and will be available in the next version or point release for RN71.
> 
> This solved it. Now I'm kinda scared to put spaces in folder paths on my machine...

thanks alot you saved my life bro
