### ISSUE TITLE
Fresh project does not build on Android

### ISSUE THREAD

**Issue by BZaldua** [facebook/react-native#35892]
### Description

I just created a new project and as soon as I open it on Android Studio, this error is shown:

`Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.facebook.react:react-android:0.71.0, variant=com.facebook.react:react-android:0.71.0 variant debugVariantDefaultApiPublication, variantName=null, artifactFile=/MY_USER/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.71.0/4760de5b8fcda11cc969ec2b872ff61b760f1433/react-android-0.71.0-debug.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=/MY_USER/PROJECT_DIR/RN71/android, react-native-gradle-plugin=//MY_USER/PROJECT_DIR/RN71/node_modules/react-native-gradle-plugin})`

If I create a fresh project with 0.70.6 everything is OK, but this last version does not seem to be working

### Version

0.71.0

### Output of `npx react-native info`

System:
    OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 3.94 GB / 15.50 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

react-native init <NAME>
cd android
./gradlew build

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment]
> Null extracted folder for artifact

This often happens if your device runs out of memory.
I would suggest you give the JVM more memory.

1. Open `android/gradle.properties`
2. Change `org.gradle.jvmargs=` and give `-Xmx4096M`

**Comment by BZaldua** [comment]
Unfortunatelly keeps showing the same error. I even cleared Gradle cache but the same error is raised

**Comment by cortinico** [comment]
> I even cleared Gradle cache but the same error is raised

What specifically have you done?

**Comment by BZaldua** [comment]
`./gradlew cleanBuildCache` and just in case `rm -r $HOME/.gradle/caches/`

**Comment by cortinico** [comment]
> `./gradlew cleanBuildCache` and just in case `rm -r $HOME/.gradle/caches/`

In your specific case I'd try to also:
1. `cd android && ./gradlew --stop`
2. `kill` all the `java` and `gradle` processes
3. `rm -r $HOME/.gradle`

Try to rebuild after every step. The last one is pretty disruptive and will take you quite some time to rebuild after it.

**Comment by BZaldua** [comment]
@cortinico Sadly, it's worse after running that:

`> Task :app:createBundleReleaseJsAndAssets FAILED
Execution optimizations have been disabled for task ':app:createBundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/bzalduanaru/Escritorio/Sites/RN71/android/app/build/generated/res/react/release'. Reason: Task ':app:mergeReleaseResources' uses this output of task ':app:createBundleReleaseJsAndAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':app:createBundleReleaseJsAndAssets' (type 'BundleHermesCTask').
  - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '/MY_USER/PROJECT_DIR/android/index.js' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the file exists before the task is called.
      2. Make sure that the task which produces the file is declared as an input.
    
    Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
`

**Comment by cortinico** [comment]
> @cortinico Sadly, it's worse after running that:

Actually the issue you were facing "Null extracted folder for artifact: ResolvedArtifact" is solved.

Now your build is failing as you have specified an entry file which doesn't exist.
Can you share your `android/app/build.gradle`?

**Comment by aytekinsahin** [comment]
> 


hi, i have the same error. I did what you said but the error is not fixed.

Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.facebook.react:react-native:0.71.0-rc.0, variantName=null, artifactFile=/Users/aytekinsahin/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=/Users/aytekinsahin/Desktop/Galva Mobile Apps/Yedek-SteelService/android}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@36caeb78)

**Comment by RajBhadania737** [comment]
i getting this error 

A problem was found with the configuration of task ':app:createBundleReleaseJsAndAssets' (type 'BundleHermesCTask').
  - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '/Users/sid/Desktop/Lumin/LuminApp/index.js' which doesn't exist.

if you have any solution . Share me

**Comment by MuhammadNasirr** [comment]
> @cortinico Sadly, it's worse after running that:
> 
> ```
> > Task :app:createBundleReleaseJsAndAssets FAILED
> Execution optimizations have been disabled for task ':app:createBundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
>   - Gradle detected a problem with the following location: '/MY_USER/PROJECT_DIR/android/app/build/generated/res/react/release'. Reason: Task ':app:mergeReleaseResources' uses this output of task ':app:createBundleReleaseJsAndAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
> 
> FAILURE: Build completed with 2 failures.
> 
> 1: Task failed with an exception.
> -----------
> * What went wrong:
> A problem was found with the configuration of task ':app:createBundleReleaseJsAndAssets' (type 'BundleHermesCTask').
>   - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '/MY_USER/PROJECT_DIR/android/index.js' which doesn't exist.
>     
>     Reason: An input file was expected to be present but it doesn't exist.
>     
>     Possible solutions:
>       1. Make sure the file exists before the task is called.
>       2. Make sure that the task which produces the file is declared as an input.
>     
>     Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> java.lang.StackOverflowError (no error message)
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> ```

@BZaldua  can you tell me what is the solution of this above error?

**Comment by eman747** [comment]
change index.tsx or index.ts to index.js

**Comment by alainib** [comment]
i had this error since few days.  how to solve it please?

**Comment by DenisPostnikov** [comment]
> i had this error since few days. how to solve it please?

If you cannot find the gradle-plugin in the @react-native directory, try removing the node modules, cleaning the npm cache with npm cache clean --force, and then reinstalling. This worked for me.
