### ISSUE TITLE
✖ Installing Bundler error Error: Looks like your iOS environment is not properly set.

### ISSUE THREAD

**Issue by laurencebedford** [facebook/react-native#36170]
### Description

Issue Occurring on MAC OS M1 chip - I am not the only one with this:

https://stackoverflow.com/questions/75040578/i-got-a-problem-installing-bundler-when-trying-create-my-new-react-native-projec

 - except I have Xcode installed and I have other projects using expo which run perfectly with simulators etc etc
```
✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing Bundler
error Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring ffi-1.15.3 because its extensions are not built. Try: gem pristine ffi --version 1.15.3
Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2

✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/private/var/root/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:129:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initialize [as func] (/private/var/root/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:181:3)
    at async Command.handleAction (/private/var/root/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:106:9)
info Run CLI with --verbose flag for more details.
```

### Version

10.1.3

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 161.55 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    Watchman: 2023.01.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

`npx react-native init newProject`

### Snack, code example, screenshot, or link to a repository

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/69059597/219035034-a579c500-9ca7-4cd9-a117-3243d01fdbe2.png">

**Comment by cortinico** [comment]
Hi @laurencebedford 
Thanks for reporting this issue.

This looks like an issue with our CLI. Don't you mind opening this issue here instead:
https://github.com/react-native-community/cli/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by laurencebedford** [comment]
> Hi @laurencebedford Thanks for reporting this issue.
> 
> This looks like an issue with our CLI. Don't you mind opening this issue here instead: https://github.com/react-native-community/cli/issues
> 
> I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

https://github.com/react-native-community/cli/issues/1832

**Comment by klwdallas** [comment]
I am having this issue on an Intel Mac. First timer following: https://reactnative.dev/docs/environment-setup

```
info Fetching system and libraries information...
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 196.89 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 32.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_321 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by muzamil01hussain** [comment]
> ### Description
> Issue Occurring on MAC OS M1 chip - I am not the only one with this:
> 
> https://stackoverflow.com/questions/75040578/i-got-a-problem-installing-bundler-when-trying-create-my-new-react-native-projec
> 
> * except I have Xcode installed and I have other projects using expo which run perfectly with simulators etc etc
> 
> ```
> ✔ Downloading template
> ✔ Copying template
> ✔ Processing template
> ✖ Installing Bundler
> error Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
> Ignoring ffi-1.15.3 because its extensions are not built. Try: gem pristine ffi --version 1.15.3
> Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
> 
> ✖ Installing Bundler
> error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
> Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
>     at createFromTemplate (/private/var/root/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:129:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Object.initialize [as func] (/private/var/root/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:181:3)
>     at async Command.handleAction (/private/var/root/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:106:9)
> info Run CLI with --verbose flag for more details.
> ```
> 
> ### Version
> 10.1.3
> 
> ### Output of `npx react-native info`
> ```
> info Fetching system and libraries information...
> System:
>     OS: macOS 13.0.1
>     CPU: (8) arm64 Apple M1
>     Memory: 161.55 MB / 8.00 GB
>     Shell: 3.2.57 - /bin/sh
>   Binaries:
>     Node: 18.12.1 - /usr/local/bin/node
>     Yarn: 1.22.11 - /usr/local/bin/yarn
>     npm: 9.4.2 - /usr/local/bin/npm
>     Watchman: 2023.01.23.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: Not Found
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
>     Android SDK: Not Found
>   IDEs:
>     Android Studio: Not Found
>     Xcode: 14.2/14C18 - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_292 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: Not Found
>     react-native: Not Found
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> ### Steps to reproduce
> `npx react-native init newProject`
> 
> ### Snack, code example, screenshot, or link to a repository
> <img alt="image" width="1403" src="https://user-images.githubusercontent.com/69059597/219035034-a579c500-9ca7-4cd9-a117-3243d01fdbe2.png">

i have same this issue

**Comment by Anuj97Anuj** [comment]
Issue Occurring on MAC OS M1 chip -

Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.

**Comment by jkotchoff** [comment]
Perhaps you need to ensure you're using version 2.7.6 of ruby (which is what [the facebook/react-native project uses](https://github.com/facebook/react-native/blob/v0.71.3/.ruby-version)) and that will help building the ffi gem per [this suggestion](https://github.com/react-native-community/cli/issues/1832#issuecomment-1454851466).

However, that didn't work for me on an M1 Macbook. I'm still seeing the error:
```bash
✔ Installing Bundler
✖ Installing CocoaPods dependencies (this may take a few minutes)
error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Users/jason/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:131:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initialize [as func] (/Users/jason/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:184:3)
    at async Command.handleAction (/Users/jason/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:106:9)
info Run CLI with --verbose flag for more details.
```

Not sure if it's relevant, however in that stacktrace, the cocoapods gem seems to be vendored with ruby 2.7.0, not sure if that' introducing any incompatability.

**Comment by ravis-farooq** [comment]
I am getting 
`An error occurred while installing ffi (1.15.5), and Bundler
cannot continue.
Make sure that `gem install ffi -v '1.15.5' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.12.1, which depends on
    cocoapods-core was resolved to 1.12.1, which depends on
      typhoeus was resolved to 1.4.0, which depends on
        ethon was resolved to 0.16.0, which depends on
          ffi`

**Comment by khanakia** [comment]
I am trying to do a fresh react install and i doubled checked everything is setup properly still getting error
```sh
✔ Processing template
✔ Installing Bundler
✖ Installing CocoaPods dependencies (this may take a few minutes)
error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.6.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Users/khanakia/.npm/_npx/dea611a43221eddd/node_modules/@react-native-community/cli/build/commands/init/init.js:131:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initialize [as func] (/Users/khanakia/.npm/_npx/dea611a43221eddd/node_modules/@react-native-community/cli/build/commands/init/init.js:184:3)
    at async Command.handleAction (/Users/khanakia/.npm/_npx/dea611a43221eddd/node_modules/@react-native-community/cli/build/index.js:106:9)
```

**Comment by parsaimon** [comment]
same issue

**Comment by khanakia** [comment]
I solved it using this command
```
sudo xcode-select --switch /Applications/Xcode.app
```

**Comment by skippergoroye** [comment]
✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing Ruby Gems
error Your Ruby version is 2.6.3, but your Gemfile specified >= 2.6.10
✖ Installing Ruby Gems
error Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/environment-setup?os=macos&platform=android and follow the React Native CLI QuickStart guide for macOS and iOS.
info Run CLI with --verbose flag for more details.



Please why am i getting this error

**Comment by khanakia** [comment]
You need to upgrade your ruby version

1. Update `[PROJECT ROOT]/Gemfile` ruby version to `ruby '>= 3.0.0`
and then upgrade your ruby version using below commands
```sh
curl -sSL https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable\n
source ~/.rvm/scripts/rvm\n
rvm reinstall "ruby-3.0.0" --with-openssl-dir=/opt/homebrew/etc/openssl@1.1
ruby --version
```
