### ISSUE TITLE
[ScrollView]'showsHorizontalScrollIndicator' didn't work

### ISSUE THREAD

**Issue by leohuangyi** [facebook/react-native#3666]
On the Android 5.0 platform,if scrollView’s horizontal set to true,there is always has Indicator .
```
                    <ScrollView
                        showsHorizontalScrollIndicator={false}
                        showsVerticalScrollIndicator={false}
                        horizontal={true}
                        />
```
My English is not well ,Sorry.
在安卓5.0平台中，一旦ScrollView的horizontal属性设置为true,无论showsHorizontalScrollIndicator属性怎么设置，都会存在滚动条Indicator。

**Comment by leohuangyi** [comment]
android 4.0 did not work well too

**Comment by negativetwelve** [comment]
Can you post an example gist or [RNPlay app](https://rnplay.org/) that displays this issue?

**Comment by leohuangyi** [comment]
https://rnplay.org/apps/hLGdAg
This is  RNPlay app  to displays this issue.
Thank You. ：）

**Comment by ide** [comment]
This is fixed in master.

**Comment by leohuangyi** [comment]
The issue still has ,it seem did not Fixed
My Package.json is
"dependencies": {
    "react-native": "^0.14.0-rc"
  }

**Comment by leohuangyi** [comment]
@ide

**Comment by leohuangyi** [comment]
This is fixed,Thanks a lot :+1:

**Comment by leohuangyi** [comment]
@ide It seems did not fiexd,
 I ‘react-native init’ a new project，there is still HorizontalScrollIndicator 。
![screenshot_2015-11-01-03-41-41](https://cloud.githubusercontent.com/assets/12397290/10865597/314423d2-804b-11e5-8144-7a03b375c9ec.jpg)

**Comment by leohuangyi** [comment]
Thanks, it is fixed。
