### ISSUE TITLE
Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65

### ISSUE THREAD

**Issue by fvalles** [facebook/react-native#37559]
### Description

My iOS builds started to break overnight with the following message (no more detail than this...):

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app`

I opened Xcode, build the app there and I found out messages like the following:

```
Showing Recent Issues
module map file '.../Library/Developer/Xcode/DerivedData/AppName-atmsvifnbguognhimfttpacxlgjb/Build/Products/Debug-iphonesimulator/DatadogSDK/Datadog.modulemap' not found
```

The same happened with modules such as:
- YogaKit
- Lottie ios
- segment analytics react native

What is weird about this error is that it started happening without having installed anything new and that my `dev`, `qa` and `release` builds works just fine and the issue only happens when building the app locally, which I run with `react-native run-ios --scheme 'cuchefs_local' --configuration Debug --simulator='iPhone 14 Pro'`

I honestly tried tons of different solutions and that's why I am opening this issue now. Among the different things I tried to do to fix this error I can mention:
1. Delete `Pods` folder, `Podfile.lock` and then run `pod install`
2. Clone the repository in a different folder and try to build there
3. I had Xcode 12.5 installed, so I downloaded the version 12.4 and try to build then
4. Clean the project with the magic command `npx react-native-clean-project` and try building again
5. Run the following commands` rm -rf ~/Library/Caches/CocoaPods && rm -rf Pods && rm -rf ~/Library/Developer/Xcode/DerivedData/* && cd ios && pod deintegrate && pod setup` and try building again
6. Look at the `Podfile` and `Xcode config` and make sure that the iphone deployment target is the same in both places
7. Build the app in a different iOS simulator
8. Clean build folder from Xcode (Product -> Clean build folder) and try building again
9. Make sure that Xcode has the option "Open using rosetta" because my macbook has an `Apple M1 chip`
10. Make sure that arm64 was added under Architectures->Excluded Architectures

-

What I also found out was that the folder` /Build/Products/Debug-iphonesimulator/ `under `Xcode/DerivedData` had only a file named as my app and nothing else was there (that's because the error says that the module map files are not found)

-

Another curious thing is that the build is breaking when it is compilling a `Dummy.swift` file I have inside /ios folder. The only line of code that file has is `import Foundation`

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 93.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/fvalles/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

just run:

`react-native run-ios --scheme 'cuchefs_local' --configuration Debug --simulator='iPhone 14 Pro'`

### Snack, code example, screenshot, or link to a repository

My `Podfile` is

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'AppName' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    if !ENV['CI']
      flipper_post_install(installer)
    end

    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end

      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end

    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
```

and `Podfile.lock` file:

```
PODS:
  - Base64 (1.1.2)
  - boost (1.76.0)
  - BVLinearGradient (2.6.2):
    - React-Core
  - CocoaAsyncSocket (7.6.5)
  - CodePush (7.1.0):
    - Base64 (~> 1.1)
    - JWT (~> 3.0.0-beta.12)
    - React-Core
    - SSZipArchive (~> 2.2.2)
  - DatadogSDK (1.15.0)
  - DatadogSDKCrashReporting (1.15.0):
    - DatadogSDK (= 1.15.0)
    - PLCrashReporter (~> 1.11.0)
  - DatadogSDKReactNative (1.4.0):
    - DatadogSDK (~> 1.15.0)
    - DatadogSDKCrashReporting (~> 1.15.0)
    - React-Core
  - DoubleConversion (1.1.6)
  - FBLazyVector (0.70.6)
  - FBReactNativeSpec (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - RCTRequired (= 0.70.6)
    - RCTTypeSafety (= 0.70.6)
    - React-Core (= 0.70.6)
    - React-jsi (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - Firebase/CoreOnly (8.15.0):
    - FirebaseCore (= 8.15.0)
  - Firebase/Database (8.15.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 8.15.0)
  - Firebase/Messaging (8.15.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 8.15.0)
  - FirebaseCore (8.15.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (8.15.0):
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseDatabase (8.15.0):
    - FirebaseCore (~> 8.0)
    - leveldb-library (~> 1.22)
  - FirebaseInstallations (8.15.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - PromisesObjC (< 3.0, >= 1.2)
  - FirebaseMessaging (8.15.0):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Reachability (~> 7.7)
    - GoogleUtilities/UserDefaults (~> 7.7)
    - nanopb (~> 2.30908.0)
  - Flipper (0.125.0):
    - Flipper-Folly (~> 2.6)
    - Flipper-RSocket (~> 1.4)
  - Flipper-Boost-iOSX (1.76.0.1.11)
  - Flipper-DoubleConversion (3.2.0.1)
  - Flipper-Fmt (7.1.7)
  - Flipper-Folly (2.6.10):
    - Flipper-Boost-iOSX
    - Flipper-DoubleConversion
    - Flipper-Fmt (= 7.1.7)
    - Flipper-Glog
    - libevent (~> 2.1.12)
    - OpenSSL-Universal (= 1.1.1100)
  - Flipper-Glog (0.5.0.5)
  - Flipper-PeerTalk (0.0.4)
  - Flipper-RSocket (1.4.3):
    - Flipper-Folly (~> 2.6)
  - FlipperKit (0.125.0):
    - FlipperKit/Core (= 0.125.0)
  - FlipperKit/Core (0.125.0):
    - Flipper (~> 0.125.0)
    - FlipperKit/CppBridge
    - FlipperKit/FBCxxFollyDynamicConvert
    - FlipperKit/FBDefines
    - FlipperKit/FKPortForwarding
    - SocketRocket (~> 0.6.0)
  - FlipperKit/CppBridge (0.125.0):
    - Flipper (~> 0.125.0)
  - FlipperKit/FBCxxFollyDynamicConvert (0.125.0):
    - Flipper-Folly (~> 2.6)
  - FlipperKit/FBDefines (0.125.0)
  - FlipperKit/FKPortForwarding (0.125.0):
    - CocoaAsyncSocket (~> 7.6)
    - Flipper-PeerTalk (~> 0.0.4)
  - FlipperKit/FlipperKitHighlightOverlay (0.125.0)
  - FlipperKit/FlipperKitLayoutHelpers (0.125.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutTextSearchable
  - FlipperKit/FlipperKitLayoutIOSDescriptors (0.125.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutHelpers
    - YogaKit (~> 1.18)
  - FlipperKit/FlipperKitLayoutPlugin (0.125.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutHelpers
    - FlipperKit/FlipperKitLayoutIOSDescriptors
    - FlipperKit/FlipperKitLayoutTextSearchable
    - YogaKit (~> 1.18)
  - FlipperKit/FlipperKitLayoutTextSearchable (0.125.0)
  - FlipperKit/FlipperKitNetworkPlugin (0.125.0):
    - FlipperKit/Core
  - FlipperKit/FlipperKitReactPlugin (0.125.0):
    - FlipperKit/Core
  - FlipperKit/FlipperKitUserDefaultsPlugin (0.125.0):
    - FlipperKit/Core
  - FlipperKit/SKIOSNetworkPlugin (0.125.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitNetworkPlugin
  - fmt (6.2.1)
  - glog (0.3.5)
  - GoogleDataTransport (9.2.1):
    - GoogleUtilities/Environment (~> 7.7)
    - nanopb (< 2.30910.0, >= 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.11.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.11.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.11.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (7.11.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.11.0)"
  - GoogleUtilities/Reachability (7.11.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.11.0):
    - GoogleUtilities/Logger
  - hermes-engine (0.70.6)
  - IQKeyboardManager (4.0.13)
  - JWT (3.0.0-beta.14):
    - Base64 (~> 1.1.2)
  - leveldb-library (1.22.1)
  - libevent (2.1.12)
  - libwebp (1.2.4):
    - libwebp/demux (= 1.2.4)
    - libwebp/mux (= 1.2.4)
    - libwebp/webp (= 1.2.4)
  - libwebp/demux (1.2.4):
    - libwebp/webp
  - libwebp/mux (1.2.4):
    - libwebp/demux
  - libwebp/webp (1.2.4)
  - lottie-ios (3.4.0)
  - lottie-react-native (5.1.4):
    - lottie-ios (~> 3.4.0)
    - React-Core
  - MMKV (1.2.15):
    - MMKVCore (~> 1.2.15)
  - MMKVCore (1.2.15)
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - OpenSSL-Universal (1.1.1100)
  - PLCrashReporter (1.11.0)
  - PromisesObjC (2.2.0)
  - RCT-Folly (2021.07.22.00):
    - boost
    - DoubleConversion
    - fmt (~> 6.2.1)
    - glog
    - RCT-Folly/Default (= 2021.07.22.00)
  - RCT-Folly/Default (2021.07.22.00):
    - boost
    - DoubleConversion
    - fmt (~> 6.2.1)
    - glog
  - RCT-Folly/Futures (2021.07.22.00):
    - boost
    - DoubleConversion
    - fmt (~> 6.2.1)
    - glog
    - libevent
  - RCTRequired (0.70.6)
  - RCTTypeSafety (0.70.6):
    - FBLazyVector (= 0.70.6)
    - RCTRequired (= 0.70.6)
    - React-Core (= 0.70.6)
  - React (0.70.6):
    - React-Core (= 0.70.6)
    - React-Core/DevSupport (= 0.70.6)
    - React-Core/RCTWebSocket (= 0.70.6)
    - React-RCTActionSheet (= 0.70.6)
    - React-RCTAnimation (= 0.70.6)
    - React-RCTBlob (= 0.70.6)
    - React-RCTImage (= 0.70.6)
    - React-RCTLinking (= 0.70.6)
    - React-RCTNetwork (= 0.70.6)
    - React-RCTSettings (= 0.70.6)
    - React-RCTText (= 0.70.6)
    - React-RCTVibration (= 0.70.6)
  - React-bridging (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - React-jsi (= 0.70.6)
  - React-callinvoker (0.70.6)
  - React-Codegen (0.70.6):
    - FBReactNativeSpec (= 0.70.6)
    - RCT-Folly (= 2021.07.22.00)
    - RCTRequired (= 0.70.6)
    - RCTTypeSafety (= 0.70.6)
    - React-Core (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-Core (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default (= 0.70.6)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/CoreModulesHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/Default (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/DevSupport (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default (= 0.70.6)
    - React-Core/RCTWebSocket (= 0.70.6)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-jsinspector (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTActionSheetHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTAnimationHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTBlobHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTImageHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTLinkingHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTNetworkHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTSettingsHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTTextHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTVibrationHeaders (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-Core/RCTWebSocket (0.70.6):
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-Core/Default (= 0.70.6)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - Yoga
  - React-CoreModules (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - RCTTypeSafety (= 0.70.6)
    - React-Codegen (= 0.70.6)
    - React-Core/CoreModulesHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-RCTImage (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-cxxreact (0.70.6):
    - boost (= 1.76.0)
    - DoubleConversion
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-callinvoker (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsinspector (= 0.70.6)
    - React-logger (= 0.70.6)
    - React-perflogger (= 0.70.6)
    - React-runtimeexecutor (= 0.70.6)
  - React-hermes (0.70.6):
    - DoubleConversion
    - glog
    - hermes-engine
    - RCT-Folly (= 2021.07.22.00)
    - RCT-Folly/Futures (= 2021.07.22.00)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-jsiexecutor (= 0.70.6)
    - React-jsinspector (= 0.70.6)
    - React-perflogger (= 0.70.6)
  - React-jsi (0.70.6):
    - boost (= 1.76.0)
    - DoubleConversion
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-jsi/Default (= 0.70.6)
  - React-jsi/Default (0.70.6):
    - boost (= 1.76.0)
    - DoubleConversion
    - glog
    - RCT-Folly (= 2021.07.22.00)
  - React-jsiexecutor (0.70.6):
    - DoubleConversion
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-perflogger (= 0.70.6)
  - React-jsinspector (0.70.6)
  - React-logger (0.70.6):
    - glog
  - react-native-flipper (0.162.0):
    - React-Core
  - react-native-flipper-performance-plugin (0.3.1):
    - React-Core
    - react-native-flipper-performance-plugin/FBDefines (= 0.3.1)
  - react-native-flipper-performance-plugin/FBDefines (0.3.1):
    - React-Core
  - react-native-mmkv (2.5.1):
    - MMKV (>= 1.2.13)
    - React-Core
  - react-native-netinfo (9.3.7):
    - React-Core
  - react-native-pager-view (5.4.25):
    - React-Core
  - react-native-restart (0.0.24):
    - React-Core
  - react-native-safe-area-context (4.5.0):
    - RCT-Folly
    - RCTRequired
    - RCTTypeSafety
    - React-Core
    - ReactCommon/turbomodule/core
  - react-native-webview (11.26.1):
    - React-Core
  - React-perflogger (0.70.6)
  - React-RCTActionSheet (0.70.6):
    - React-Core/RCTActionSheetHeaders (= 0.70.6)
  - React-RCTAnimation (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - RCTTypeSafety (= 0.70.6)
    - React-Codegen (= 0.70.6)
    - React-Core/RCTAnimationHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-RCTBlob (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - React-Codegen (= 0.70.6)
    - React-Core/RCTBlobHeaders (= 0.70.6)
    - React-Core/RCTWebSocket (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-RCTNetwork (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-RCTImage (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - RCTTypeSafety (= 0.70.6)
    - React-Codegen (= 0.70.6)
    - React-Core/RCTImageHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-RCTNetwork (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-RCTLinking (0.70.6):
    - React-Codegen (= 0.70.6)
    - React-Core/RCTLinkingHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-RCTNetwork (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - RCTTypeSafety (= 0.70.6)
    - React-Codegen (= 0.70.6)
    - React-Core/RCTNetworkHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-RCTSettings (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - RCTTypeSafety (= 0.70.6)
    - React-Codegen (= 0.70.6)
    - React-Core/RCTSettingsHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-RCTText (0.70.6):
    - React-Core/RCTTextHeaders (= 0.70.6)
  - React-RCTVibration (0.70.6):
    - RCT-Folly (= 2021.07.22.00)
    - React-Codegen (= 0.70.6)
    - React-Core/RCTVibrationHeaders (= 0.70.6)
    - React-jsi (= 0.70.6)
    - ReactCommon/turbomodule/core (= 0.70.6)
  - React-runtimeexecutor (0.70.6):
    - React-jsi (= 0.70.6)
  - ReactCommon/turbomodule/core (0.70.6):
    - DoubleConversion
    - glog
    - RCT-Folly (= 2021.07.22.00)
    - React-bridging (= 0.70.6)
    - React-callinvoker (= 0.70.6)
    - React-Core (= 0.70.6)
    - React-cxxreact (= 0.70.6)
    - React-jsi (= 0.70.6)
    - React-logger (= 0.70.6)
    - React-perflogger (= 0.70.6)
  - ReactNativeKeyboardManager (4.0.13-17):
    - IQKeyboardManager (= 4.0.13)
    - React
    - React-RCTText
  - ReactNativeWebPFormat (1.1.2):
    - React
    - SDWebImageWebPCoder
  - RNCAsyncStorage (1.17.11):
    - React-Core
  - RNCClipboard (1.5.1):
    - React-Core
  - RNCMaskedView (0.2.0):
    - React-Core
  - RNCPicker (2.4.8):
    - React-Core
  - RNDeviceInfo (10.4.0):
    - React-Core
  - RNFastImage (8.6.3):
    - React-Core
    - SDWebImage (~> 5.11.1)
    - SDWebImageWebPCoder (~> 0.8.4)
  - RNFBApp (14.12.0):
    - Firebase/CoreOnly (= 8.15.0)
    - React-Core
  - RNFBDatabase (14.12.0):
    - Firebase/Database (= 8.15.0)
    - React-Core
    - RNFBApp
  - RNFBMessaging (14.12.0):
    - Firebase/Messaging (= 8.15.0)
    - React-Core
    - RNFBApp
  - RNGestureHandler (2.9.0):
    - React-Core
  - RNLocalize (2.2.4):
    - React-Core
  - RNReanimated (2.14.4):
    - DoubleConversion
    - FBLazyVector
    - FBReactNativeSpec
    - glog
    - RCT-Folly
    - RCTRequired
    - RCTTypeSafety
    - React-callinvoker
    - React-Core
    - React-Core/DevSupport
    - React-Core/RCTWebSocket
    - React-CoreModules
    - React-cxxreact
    - React-jsi
    - React-jsiexecutor
    - React-jsinspector
    - React-RCTActionSheet
    - React-RCTAnimation
    - React-RCTBlob
    - React-RCTImage
    - React-RCTLinking
    - React-RCTNetwork
    - React-RCTSettings
    - React-RCTText
    - ReactCommon/turbomodule/core
    - Yoga
  - RNScreens (3.20.0):
    - React-Core
    - React-RCTImage
  - RNSentry (4.15.0):
    - React-Core
    - Sentry/HybridSDK (= 7.31.5)
  - RNShare (7.9.1):
    - React-Core
  - RNSnackbar (2.4.0):
    - React-Core
  - RNSVG (12.5.1):
    - React-Core
  - SDWebImage (5.11.1):
    - SDWebImage/Core (= 5.11.1)
  - SDWebImage/Core (5.11.1)
  - SDWebImageWebPCoder (0.8.5):
    - libwebp (~> 1.0)
    - SDWebImage/Core (~> 5.10)
  - segment-analytics-react-native (2.13.0):
    - React-Core
    - sovran-react-native
  - Sentry/HybridSDK (7.31.5)
  - SocketRocket (0.6.0)
  - sovran-react-native (0.4.5):
    - React-Core
  - SSZipArchive (2.2.3)
  - Yoga (1.14.0)
  - YogaKit (1.18.1):
    - Yoga (~> 1.14)

DEPENDENCIES:
  - boost (from `../node_modules/react-native/third-party-podspecs/boost.podspec`)
  - BVLinearGradient (from `../node_modules/react-native-linear-gradient`)
  - CodePush (from `../node_modules/react-native-code-push`)
  - "DatadogSDKReactNative (from `../node_modules/@datadog/mobile-react-native`)"
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)
  - FBReactNativeSpec (from `../node_modules/react-native/React/FBReactNativeSpec`)
  - Flipper (= 0.125.0)
  - Flipper-Boost-iOSX (= 1.76.0.1.11)
  - Flipper-DoubleConversion (= 3.2.0.1)
  - Flipper-Fmt (= 7.1.7)
  - Flipper-Folly (= 2.6.10)
  - Flipper-Glog (= 0.5.0.5)
  - Flipper-PeerTalk (= 0.0.4)
  - Flipper-RSocket (= 1.4.3)
  - FlipperKit (= 0.125.0)
  - FlipperKit/Core (= 0.125.0)
  - FlipperKit/CppBridge (= 0.125.0)
  - FlipperKit/FBCxxFollyDynamicConvert (= 0.125.0)
  - FlipperKit/FBDefines (= 0.125.0)
  - FlipperKit/FKPortForwarding (= 0.125.0)
  - FlipperKit/FlipperKitHighlightOverlay (= 0.125.0)
  - FlipperKit/FlipperKitLayoutPlugin (= 0.125.0)
  - FlipperKit/FlipperKitLayoutTextSearchable (= 0.125.0)
  - FlipperKit/FlipperKitNetworkPlugin (= 0.125.0)
  - FlipperKit/FlipperKitReactPlugin (= 0.125.0)
  - FlipperKit/FlipperKitUserDefaultsPlugin (= 0.125.0)
  - FlipperKit/SKIOSNetworkPlugin (= 0.125.0)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - hermes-engine (from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`)
  - libevent (~> 2.1.12)
  - lottie-ios (from `../node_modules/lottie-ios`)
  - lottie-react-native (from `../node_modules/lottie-react-native`)
  - OpenSSL-Universal (= 1.1.1100)
  - RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)
  - RCTRequired (from `../node_modules/react-native/Libraries/RCTRequired`)
  - RCTTypeSafety (from `../node_modules/react-native/Libraries/TypeSafety`)
  - React (from `../node_modules/react-native/`)
  - React-bridging (from `../node_modules/react-native/ReactCommon`)
  - React-callinvoker (from `../node_modules/react-native/ReactCommon/callinvoker`)
  - React-Codegen (from `build/generated/ios`)
  - React-Core (from `../node_modules/react-native/`)
  - React-Core/DevSupport (from `../node_modules/react-native/`)
  - React-Core/RCTWebSocket (from `../node_modules/react-native/`)
  - React-CoreModules (from `../node_modules/react-native/React/CoreModules`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-hermes (from `../node_modules/react-native/ReactCommon/hermes`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - React-logger (from `../node_modules/react-native/ReactCommon/logger`)
  - react-native-flipper (from `../node_modules/react-native-flipper`)
  - react-native-flipper-performance-plugin (from `../node_modules/react-native-flipper-performance-plugin`)
  - react-native-mmkv (from `../node_modules/react-native-mmkv`)
  - "react-native-netinfo (from `../node_modules/@react-native-community/netinfo`)"
  - react-native-pager-view (from `../node_modules/react-native-pager-view`)
  - react-native-restart (from `../node_modules/react-native-restart`)
  - react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React-perflogger (from `../node_modules/react-native/ReactCommon/reactperflogger`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - React-runtimeexecutor (from `../node_modules/react-native/ReactCommon/runtimeexecutor`)
  - ReactCommon/turbomodule/core (from `../node_modules/react-native/ReactCommon`)
  - ReactNativeKeyboardManager (from `../node_modules/react-native-keyboard-manager`)
  - ReactNativeWebPFormat (from `../node_modules/react-native-webp-format`)
  - "RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)"
  - "RNCClipboard (from `../node_modules/@react-native-community/clipboard`)"
  - "RNCMaskedView (from `../node_modules/@react-native-masked-view/masked-view`)"
  - "RNCPicker (from `../node_modules/@react-native-picker/picker`)"
  - RNDeviceInfo (from `../node_modules/react-native-device-info`)
  - RNFastImage (from `../node_modules/react-native-fast-image`)
  - "RNFBApp (from `../node_modules/@react-native-firebase/app`)"
  - "RNFBDatabase (from `../node_modules/@react-native-firebase/database`)"
  - "RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`)"
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - RNLocalize (from `../node_modules/react-native-localize`)
  - RNReanimated (from `../node_modules/react-native-reanimated`)
  - RNScreens (from `../node_modules/react-native-screens`)
  - "RNSentry (from `../node_modules/@sentry/react-native`)"
  - RNShare (from `../node_modules/react-native-share`)
  - RNSnackbar (from `../node_modules/react-native-snackbar`)
  - RNSVG (from `../node_modules/react-native-svg`)
  - "segment-analytics-react-native (from `../node_modules/@segment/analytics-react-native`)"
  - "sovran-react-native (from `../node_modules/@segment/sovran-react-native`)"
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  trunk:
    - Base64
    - CocoaAsyncSocket
    - DatadogSDK
    - DatadogSDKCrashReporting
    - Firebase
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseDatabase
    - FirebaseInstallations
    - FirebaseMessaging
    - Flipper
    - Flipper-Boost-iOSX
    - Flipper-DoubleConversion
    - Flipper-Fmt
    - Flipper-Folly
    - Flipper-Glog
    - Flipper-PeerTalk
    - Flipper-RSocket
    - FlipperKit
    - fmt
    - GoogleDataTransport
    - GoogleUtilities
    - IQKeyboardManager
    - JWT
    - leveldb-library
    - libevent
    - libwebp
    - MMKV
    - MMKVCore
    - nanopb
    - OpenSSL-Universal
    - PLCrashReporter
    - PromisesObjC
    - SDWebImage
    - SDWebImageWebPCoder
    - Sentry
    - SocketRocket
    - SSZipArchive
    - YogaKit

EXTERNAL SOURCES:
  boost:
    :podspec: "../node_modules/react-native/third-party-podspecs/boost.podspec"
  BVLinearGradient:
    :path: "../node_modules/react-native-linear-gradient"
  CodePush:
    :path: "../node_modules/react-native-code-push"
  DatadogSDKReactNative:
    :path: "../node_modules/@datadog/mobile-react-native"
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  FBLazyVector:
    :path: "../node_modules/react-native/Libraries/FBLazyVector"
  FBReactNativeSpec:
    :path: "../node_modules/react-native/React/FBReactNativeSpec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  hermes-engine:
    :podspec: "../node_modules/react-native/sdks/hermes/hermes-engine.podspec"
  lottie-ios:
    :path: "../node_modules/lottie-ios"
  lottie-react-native:
    :path: "../node_modules/lottie-react-native"
  RCT-Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec"
  RCTRequired:
    :path: "../node_modules/react-native/Libraries/RCTRequired"
  RCTTypeSafety:
    :path: "../node_modules/react-native/Libraries/TypeSafety"
  React:
    :path: "../node_modules/react-native/"
  React-bridging:
    :path: "../node_modules/react-native/ReactCommon"
  React-callinvoker:
    :path: "../node_modules/react-native/ReactCommon/callinvoker"
  React-Codegen:
    :path: build/generated/ios
  React-Core:
    :path: "../node_modules/react-native/"
  React-CoreModules:
    :path: "../node_modules/react-native/React/CoreModules"
  React-cxxreact:
    :path: "../node_modules/react-native/ReactCommon/cxxreact"
  React-hermes:
    :path: "../node_modules/react-native/ReactCommon/hermes"
  React-jsi:
    :path: "../node_modules/react-native/ReactCommon/jsi"
  React-jsiexecutor:
    :path: "../node_modules/react-native/ReactCommon/jsiexecutor"
  React-jsinspector:
    :path: "../node_modules/react-native/ReactCommon/jsinspector"
  React-logger:
    :path: "../node_modules/react-native/ReactCommon/logger"
  react-native-flipper:
    :path: "../node_modules/react-native-flipper"
  react-native-flipper-performance-plugin:
    :path: "../node_modules/react-native-flipper-performance-plugin"
  react-native-mmkv:
    :path: "../node_modules/react-native-mmkv"
  react-native-netinfo:
    :path: "../node_modules/@react-native-community/netinfo"
  react-native-pager-view:
    :path: "../node_modules/react-native-pager-view"
  react-native-restart:
    :path: "../node_modules/react-native-restart"
  react-native-safe-area-context:
    :path: "../node_modules/react-native-safe-area-context"
  react-native-webview:
    :path: "../node_modules/react-native-webview"
  React-perflogger:
    :path: "../node_modules/react-native/ReactCommon/reactperflogger"
  React-RCTActionSheet:
    :path: "../node_modules/react-native/Libraries/ActionSheetIOS"
  React-RCTAnimation:
    :path: "../node_modules/react-native/Libraries/NativeAnimation"
  React-RCTBlob:
    :path: "../node_modules/react-native/Libraries/Blob"
  React-RCTImage:
    :path: "../node_modules/react-native/Libraries/Image"
  React-RCTLinking:
    :path: "../node_modules/react-native/Libraries/LinkingIOS"
  React-RCTNetwork:
    :path: "../node_modules/react-native/Libraries/Network"
  React-RCTSettings:
    :path: "../node_modules/react-native/Libraries/Settings"
  React-RCTText:
    :path: "../node_modules/react-native/Libraries/Text"
  React-RCTVibration:
    :path: "../node_modules/react-native/Libraries/Vibration"
  React-runtimeexecutor:
    :path: "../node_modules/react-native/ReactCommon/runtimeexecutor"
  ReactCommon:
    :path: "../node_modules/react-native/ReactCommon"
  ReactNativeKeyboardManager:
    :path: "../node_modules/react-native-keyboard-manager"
  ReactNativeWebPFormat:
    :path: "../node_modules/react-native-webp-format"
  RNCAsyncStorage:
    :path: "../node_modules/@react-native-async-storage/async-storage"
  RNCClipboard:
    :path: "../node_modules/@react-native-community/clipboard"
  RNCMaskedView:
    :path: "../node_modules/@react-native-masked-view/masked-view"
  RNCPicker:
    :path: "../node_modules/@react-native-picker/picker"
  RNDeviceInfo:
    :path: "../node_modules/react-native-device-info"
  RNFastImage:
    :path: "../node_modules/react-native-fast-image"
  RNFBApp:
    :path: "../node_modules/@react-native-firebase/app"
  RNFBDatabase:
    :path: "../node_modules/@react-native-firebase/database"
  RNFBMessaging:
    :path: "../node_modules/@react-native-firebase/messaging"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  RNLocalize:
    :path: "../node_modules/react-native-localize"
  RNReanimated:
    :path: "../node_modules/react-native-reanimated"
  RNScreens:
    :path: "../node_modules/react-native-screens"
  RNSentry:
    :path: "../node_modules/@sentry/react-native"
  RNShare:
    :path: "../node_modules/react-native-share"
  RNSnackbar:
    :path: "../node_modules/react-native-snackbar"
  RNSVG:
    :path: "../node_modules/react-native-svg"
  segment-analytics-react-native:
    :path: "../node_modules/@segment/analytics-react-native"
  sovran-react-native:
    :path: "../node_modules/@segment/sovran-react-native"
  Yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  Base64: cecfb41a004124895a7bcee567a89bae5a89d49b
  boost: a7c83b31436843459a1961bfd74b96033dc77234
  BVLinearGradient: 34a999fda29036898a09c6a6b728b0b4189e1a44
  CocoaAsyncSocket: 065fd1e645c7abab64f7a6a2007a48038fdc6a99
  CodePush: dce1b253fde81078249ea9cd4b948e4ac7b761a9
  DatadogSDK: d7e3ef65693db38842f85885c01ba0865e10a782
  DatadogSDKCrashReporting: 4be11b3693ed048f461391f724788ea96d31633a
  DatadogSDKReactNative: 6d1426209f448acbf58c13673b963a8b25cf00f5
  DoubleConversion: 5189b271737e1565bdce30deb4a08d647e3f5f54
  FBLazyVector: 48289402952f4f7a4e235de70a9a590aa0b79ef4
  FBReactNativeSpec: dd1186fd05255e3457baa2f4ca65e94c2cd1e3ac
  Firebase: 5f8193dff4b5b7c5d5ef72ae54bb76c08e2b841d
  FirebaseCore: 5743c5785c074a794d35f2fff7ecc254a91e08b1
  FirebaseCoreDiagnostics: 92e07a649aeb66352b319d43bdd2ee3942af84cb
  FirebaseDatabase: f567afd233e54a303d84423207736590a6feb419
  FirebaseInstallations: 40bd9054049b2eae9a2c38ef1c3dd213df3605cd
  FirebaseMessaging: 5e5118a2383b3531e730d974680954c679ca0a13
  Flipper: 26fc4b7382499f1281eb8cb921e5c3ad6de91fe0
  Flipper-Boost-iOSX: fd1e2b8cbef7e662a122412d7ac5f5bea715403c
  Flipper-DoubleConversion: 2dc99b02f658daf147069aad9dbd29d8feb06d30
  Flipper-Fmt: 60cbdd92fc254826e61d669a5d87ef7015396a9b
  Flipper-Folly: 584845625005ff068a6ebf41f857f468decd26b3
  Flipper-Glog: 70c50ce58ddaf67dc35180db05f191692570f446
  Flipper-PeerTalk: 116d8f857dc6ef55c7a5a75ea3ceaafe878aadc9
  Flipper-RSocket: d9d9ade67cbecf6ac10730304bf5607266dd2541
  FlipperKit: cbdee19bdd4e7f05472a66ce290f1b729ba3cb86
  fmt: ff9d55029c625d3757ed641535fd4a75fedc7ce9
  glog: 04b94705f318337d7ead9e6d17c019bd9b1f6b1b
  GoogleDataTransport: ea169759df570f4e37bdee1623ec32a7e64e67c4
  GoogleUtilities: c2bdc4cf2ce786c4d2e6b3bcfd599a25ca78f06f
  hermes-engine: 2af7b7a59128f250adfd86f15aa1d5a2ecd39995
  IQKeyboardManager: 8eab4d8111418414619d1df8e4779ce5d0f8d7e2
  JWT: ef71dfb03e1f842081e64dc42eef0e164f35d251
  leveldb-library: 50c7b45cbd7bf543c81a468fe557a16ae3db8729
  libevent: 4049cae6c81cdb3654a443be001fb9bdceff7913
  libwebp: f62cb61d0a484ba548448a4bd52aabf150ff6eef
  lottie-ios: 69495122151a378fdc7d1bb4c5930347e37baf1f
  lottie-react-native: b702fab740cdb952a8e2354713d3beda63ff97b0
  MMKV: 7f34558bbb5a33b0eaefae2de4b6a20a2ffdad6f
  MMKVCore: ddf41b9d9262f058419f9ba7598719af56c02cd3
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  OpenSSL-Universal: ebc357f1e6bc71fa463ccb2fe676756aff50e88c
  PLCrashReporter: 7a9dff14a23ba5d2e28c6160f0bb6fada5e71a8d
  PromisesObjC: 09985d6d70fbe7878040aa746d78236e6946d2ef
  RCT-Folly: 0080d0a6ebf2577475bda044aa59e2ca1f909cda
  RCTRequired: e1866f61af7049eb3d8e08e8b133abd38bc1ca7a
  RCTTypeSafety: 27c2ac1b00609a432ced1ae701247593f07f901e
  React: bb3e06418d2cc48a84f9666a576c7b38e89cd7db
  React-bridging: 572502ec59c9de30309afdc4932e278214288913
  React-callinvoker: 6b708b79c69f3359d42f1abb4663f620dbd4dadf
  React-Codegen: 74e1cd7cee692a8b983c18df3274b5e749de07c8
  React-Core: b587d0a624f9611b0e032505f3d6f25e8daa2bee
  React-CoreModules: c6ff48b985e7aa622e82ca51c2c353c7803eb04e
  React-cxxreact: ade3d9e63c599afdead3c35f8a8bd12b3da6730b
  React-hermes: ed09ae33512bbb8d31b2411778f3af1a2eb681a1
  React-jsi: 5a3952e0c6d57460ad9ee2c905025b4c28f71087
  React-jsiexecutor: b4a65947391c658450151275aa406f2b8263178f
  React-jsinspector: 60769e5a0a6d4b32294a2456077f59d0266f9a8b
  React-logger: 1623c216abaa88974afce404dc8f479406bbc3a0
  react-native-flipper: 7eeb9b59b667dd0619372c7349cf7c78032d1de2
  react-native-flipper-performance-plugin: 2b873b68da3e368afeaf29c9c7a8c2b0ff908c4f
  react-native-mmkv: 69b9c003f10afdd01addf7c6ee784ce42ee2eff3
  react-native-netinfo: 2517ad504b3d303e90d7a431b0fcaef76d207983
  react-native-pager-view: da490aa1f902c9a5aeecf0909cc975ad0e92e53e
  react-native-restart: 45c8dca02491980f2958595333cbccd6877cb57e
  react-native-safe-area-context: 39c2d8be3328df5d437ac1700f4f3a4f75716acc
  react-native-webview: 9f111dfbcfc826084d6c507f569e5e03342ee1c1
  React-perflogger: 8c79399b0500a30ee8152d0f9f11beae7fc36595
  React-RCTActionSheet: 7316773acabb374642b926c19aef1c115df5c466
  React-RCTAnimation: 5341e288375451297057391227f691d9b2326c3d
  React-RCTBlob: b0615fc2daf2b5684ade8fadcab659f16f6f0efa
  React-RCTImage: 6487b9600f268ecedcaa86114d97954d31ad4750
  React-RCTLinking: c8018ae9ebfefcec3839d690d4725f8d15e4e4b3
  React-RCTNetwork: 8aa63578741e0fe1205c28d7d4b40dbfdabce8a8
  React-RCTSettings: d00c15ad369cd62242a4dfcc6f277912b4a84ed3
  React-RCTText: f532e5ca52681ecaecea452b3ad7a5b630f50d75
  React-RCTVibration: c75ceef7aa60a33b2d5731ebe5800ddde40cefc4
  React-runtimeexecutor: 15437b576139df27635400de0599d9844f1ab817
  ReactCommon: 349be31adeecffc7986a0de875d7fb0dcf4e251c
  ReactNativeKeyboardManager: d0e285b82ef60a861d71834d8e996fbc09607a67
  ReactNativeWebPFormat: 4275844b80c2c385a10ab64f50264d720f2d691c
  RNCAsyncStorage: 8616bd5a58af409453ea4e1b246521bb76578d60
  RNCClipboard: 41d8d918092ae8e676f18adada19104fa3e68495
  RNCMaskedView: 5c799d0290aa76c3ffa077b90207292a95b121b2
  RNCPicker: 0bf8ef8f7800524f32d2bb2a8bcadd53eda0ecd1
  RNDeviceInfo: 749f2e049dcd79e2e44f134f66b73a06951b5066
  RNFastImage: 5c9c9fed9c076e521b3f509fe79e790418a544e8
  RNFBApp: e4439717c23252458da2b41b81b4b475c86f90c4
  RNFBDatabase: 16daa56d773d353b2ef2752a229cedf195b51cf3
  RNFBMessaging: 40dac204b4197a2661dec5be964780c6ec39bf65
  RNGestureHandler: 071d7a9ad81e8b83fe7663b303d132406a7d8f39
  RNLocalize: 0df7970cfc60389f00eb62fd7c097dc75af3fb4f
  RNReanimated: 6668b0587bebd4b15dd849b99e5a9c70fc12ed95
  RNScreens: 218801c16a2782546d30bd2026bb625c0302d70f
  RNSentry: 50f8b7147d1d0973a56635e524b192ec80e53195
  RNShare: a5dc3b9c53ddc73e155b8cd9a94c70c91913c43c
  RNSnackbar: be3333a21a453ccc272f41a8add5a71f7d44dfcd
  RNSVG: d7d7bc8229af3842c9cfc3a723c815a52cdd1105
  SDWebImage: a7f831e1a65eb5e285e3fb046a23fcfbf08e696d
  SDWebImageWebPCoder: 908b83b6adda48effe7667cd2b7f78c897e5111d
  segment-analytics-react-native: bd1f13ea95bad2313a9c7130da032af0e9a6da60
  Sentry: 4c9babff9034785067c896fd580b1f7de44da020
  SocketRocket: fccef3f9c5cedea1353a9ef6ada904fde10d6608
  sovran-react-native: fd3dc8f1a4b14acdc4ad25fc6b4ac4f52a2a2a15
  SSZipArchive: 62d4947b08730e4cda640473b0066d209ff033c9
  Yoga: 99caf8d5ab45e9d637ee6e0174ec16fbbb01bcfc
  YogaKit: f782866e155069a2cca2517aafea43200b01fd5a

PODFILE CHECKSUM: 7745e788d6657b6d37505a3d2ba03f900aac66e9

COCOAPODS: 1.11.3

```

**Comment by khanakia** [comment]
Any solution ?

**Comment by fvalles** [comment]
I thought nobody was going to answer... Not yet man. My workaround was starting using my iPhone for building and testing the iOS app. Do you have any idea of how to solve this?

**Comment by khanakia** [comment]
I solved it myself by debugging the build into the Xcode and i had some pod giving error so removed it and then it worked

**Comment by x7Michi10x** [comment]
@fvalles Were you able to fix the error?

**Comment by khanakia** [comment]
Jus try to run and see if it works
```
cd ios
pod update
```

**Comment by fvalles** [comment]
> @fvalles Were you able to fix the error?

nope :(. I am debugging with my physical iOS device for the moment and didn't give this a try again to try to fix it. I believe the problem it's something heavily cached in my machine

**Comment by x7Michi10x** [comment]
Meanwhile, I solved it for my case, but the solution is very specific, so I believe it won't help others.

In my case, I had the subdependency 'react-native-jw-media-player' in a package. After I explicitely add jw-media-player to my package.json in a newer version, the build runs successful.
I found the problem by rolling back to older versions of my project.

**Comment by fvalles** [comment]
mm I haven't that dependency and it's working perfectly on my iOS physical device 😞

**Comment by jitendraAn** [comment]
I have same problem. anybudy have solution this problme.Please help me.

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65`

<img width="812" alt="Screenshot 2023-07-31 at 3 48 32 PM" src="https://github.com/facebook/react-native/assets/31131116/d3287856-3d72-4a18-b85f-9b9052de6b14">

**Comment by jitendraAn** [comment]
my problem is solved. I am remove space from project path fold name.
for example: 
your project path is "user/react native/awersomeproject".
solution: "user/reactnative/awersomeproject"

**Comment by JDMathew** [comment]
For me adding the scheme and the configuration into the build arguments fixed the issue. i.e in `package.json`:
```json
"ios": "react-native run-ios --scheme 'App Dev' --configuration Debug"
```

and then running:
```shell
yarn ios
```

**Comment by fvalles** [comment]
> For me adding the scheme and the configuration into the build arguments fixed the issue. i.e in `package.json`:
> 
> ```json
> "ios": "react-native run-ios --scheme 'App Dev' --configuration Debug"
> ```
> 
> and then running:
> 
> ```shell
> yarn ios
> ```

I have always had the scheme and configuration set, so that's not a solution

**Comment by jitendraAn** [comment]
@fvalles Please check pod install properly or not.

**Comment by fvalles** [comment]
> 

Tried pod install as described in the description of this issue and it didn't work

**Comment by startopandrey** [comment]
> my problem is solved. I am remove space from project path fold name. for example: your project path is "user/react native/awersomeproject". solution: "user/reactnative/awersomeproject"

u saved my day, thanx

**Comment by Monkeystation** [comment]
> my problem is solved. I am remove space from project path fold name. for example: your project path is "user/react native/awersomeproject". solution: "user/reactnative/awersomeproject"

This worked for me too! Thanks!!

**Comment by aryaadinulfadlan** [comment]
> my problem is solved. I am remove space from project path fold name. for example: your project path is "user/react native/awersomeproject". solution: "user/reactnative/awersomeproject"

 I cannot Thank you enough, I was facing this issue for few days. 
 Build is now working without any issue. Really appreciate your help. 
 God Bless U, my brother.

**Comment by TarifEzaz** [comment]
The folder that contains your project has spaces. For example, my folder was named MotuSmash 4. After I changed it to MotuSmash-4, the error was resolved.

**Comment by andresmartindoria** [comment]
> Jus try to run and see if it works
> 
> ```
> cd ios
> pod update
> ```

i'ts works for me, thanks!

**Comment by ildaneta** [comment]
In my case the same error was caused by `cocoapods` update to version `1.15.2` so, I installed the version `1.14.2`, ran 

```bash
cd ios
npx po-install
```

and my problem was solved.

**Comment by alainib** [comment]
i have the same error since few days

i cannot try your fix @ildaneta 

> npx po-install

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/po-install - Not found
npm ERR! 404
npm ERR! 404  'po-install@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/alainibrahim/.npm/_logs/2024-02-19T20_15_26_281Z-debug-0.log

**Comment by alainib** [comment]
any other solution please? i tryed all above and still get this error :( 

if i do "pod install" it update COCOAPODS: from to 1.14.2 to  1.15.2  , how to force downgrade ?

**Comment by yn-lgting** [comment]
> > Jus try to run and see if it works尝试运行一下看看是否有效
> > ```
> > cd ios
> > pod update
> > ```
> 
> i'ts works for me, thanks!我对我有用，谢谢！



> > Jus try to run and see if it works
> > ```
> > cd ios
> > pod update
> > ```
> 
> i'ts works for me, thanks!

i'ts works for me, thanks!

**Comment by ArindamRayMukherjee** [comment]
This error code 65 is a generic code that indicates an xcode-build crash without any way of tracing back why.
The best bet is to debug the RN app build in XCode itself where you might see the reason of why.
For me it was the autogenerated `ios/.xcode.env.local` file, that contained a strange location for the node binary.
Deleting that file made things "better" wink wink.

See the discussion here - https://github.com/facebook/react-native/issues/35657#issuecomment-2131222019

**Comment by ascooper57** [comment]
For my instance of the 65 generic code, the solution was posted here: https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w

**Comment by kaylee182000** [comment]
> my problem is solved. I am remove space from project path fold name. for example: your project path is "user/react native/awersomeproject". solution: "user/reactnative/awersomeproject"

How can I know what is my project path, sir? Can you help me?

**Comment by jitendraAn** [comment]
Project path means the path to the project root folder.

**Comment by armantalib** [comment]
first delete node modules and yarn.lock and package.json.lock file then install node module then delete pods folder and pods.lock file and install pods.

If the above not solve the then simply open your Xocde clean the build folder simply build the project then Xcode sends some error related to your package remove that package or just change the version of that package again build

hopefully its works for you

**Comment by xyaistic** [comment]
cd ios
pod update

it works

**Comment by dbaltor** [comment]
> my problem is solved. I am remove space from project path fold name. for example: your project path is "user/react native/awersomeproject". solution: "user/reactnative/awersomeproject"

My problem was related to the project path as well so this answer helped me to solve it. In my case I didn't have any space in the path but I had changed the project folder name in between running `npx expo prebuild` and `npx expo run:ios`

**Comment by TCasablancas** [comment]
In my case, i was taking this error for several, until i start debbuging inside XCode and discover that the ReactNativeDependencies package was asking for v18.20.8. So i just ran nvm install 18.20.8 on terminal, and cmd+b on XCode. It runs perfectly. Then just npx react-native run-ios and it's done!
