### ISSUE TITLE
0.72: Remote debugging broken on Android

### ISSUE THREAD

**Issue by edstbbz** [facebook/react-native#38006]
### Description

When upgrading to 0.72, the application crashes when connected to the Chrome debugger (test on Android)

2023-06-22 00:19:01.199 22414-22948 libc                    com.myapp.releasestaging         A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22948 (mqt_js), pid 22414 (.releasestaging)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A  Cmdline: com.myapp.releasestaging
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A  pid: 22414, tid: 22948, name: mqt_js  >>> com.myapp.releasestaging <<<
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #00 pc 000000000003b7f4  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreact_render_runtimescheduler.so (facebook::react::RuntimeSchedulerBinding::createAndInstallIfNeeded(facebook::jsi::Runtime&, std::__ndk1::shared_ptr<facebook::react::RuntimeScheduler> const&)+68) (BuildId: 154f261ff589aa1e)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #01 pc 00000000002055e1  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #02 pc 0000000000205591  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #03 pc 0000000000205531  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #04 pc 00000000002054e1  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #05 pc 0000000000204300  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #06 pc 000000000028b3a9  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #07 pc 000000000028ad2c  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (std::__ndk1::function<void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) const+44) (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #08 pc 000000000028ac68  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #09 pc 000000000028ac11  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #10 pc 000000000028abb1  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #11 pc 000000000028ab61  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #12 pc 0000000000289ab0  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #13 pc 00000000002b56b9  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #14 pc 00000000002b5629  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (std::__ndk1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const+57) (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.750 22956-22956 DEBUG                   pid-22956                            A        #15 pc 00000000002b55e6  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #16 pc 00000000002b556c  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #17 pc 00000000002b551c  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #18 pc 00000000002b54ec  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #19 pc 00000000002b43b8  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #20 pc 00000000003e56d1  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libhermes_executor.so (BuildId: 53166c965b19a311)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #21 pc 00000000003e5694  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libhermes_executor.so (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: 53166c965b19a311)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #22 pc 00000000002153c4  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #23 pc 000000000021533c  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #24 pc 00000000002152ec  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #25 pc 00000000002152bc  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #26 pc 0000000000214248  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libreactnativejni.so (BuildId: eedf0b28937d60c0)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #27 pc 0000000000016979  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libfbjni.so (facebook::jni::detail::MethodWrapper<void (facebook::jni::JNativeRunnable::*)(), &(facebook::jni::JNativeRunnable::run()), facebook::jni::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>)+25) (BuildId: 24c51b71e72aa958d98c6f3c2304d6447e26c99e)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #28 pc 00000000000168f4  /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/lib/x86_64/libfbjni.so (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>))+52) (BuildId: 24c51b71e72aa958d98c6f3c2304d6447e26c99e)
2023-06-22 00:19:01.751 22956-22956 DEBUG                   pid-22956                            A        #37 pc 00000000003ea1f2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~4hmgMGlidXP0t4CIdUV4PA==/com.myapp.releasestaging-ZdypyK0mTp6SdihqT5qtnA==/base.apk] (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+74)

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
  OS: macOS 12.6.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 38.58 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.2.1
    path: /usr/local/bin/yarn
  npm:
    version: 8.1.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2022.10.24.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 16.0
      - macOS 12.3
      - tvOS 16.0
      - watchOS 9.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9514443
  Xcode:
    version: 14.0.1/14A400
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.5
    path: /Users/user/.rvm/rubies/ruby-2.6.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

1) react-native-run-android
2) connect to Chrome debugger

### Snack, code example, screenshot, or link to a repository

-

**Comment by lunaleaps** [comment]
Was able to reproduce this with a new app. See stacktrace: https://gist.github.com/lunaleaps/b6dafc94fbe22017e2737b15831ec0ad

**Comment by lunaleaps** [comment]
As well, with iOS I get this error:
```
info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
error Browser exited with error:, invalid url, missing http/https protocol
info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
error Browser exited with error:, invalid url, missing http/https protocol
```

**Comment by cipolleschi** [comment]
cc. @huntie as you are working on this part

**Comment by blakef** [comment]
I think this is unrelated, that looks like you don't have the flipper client installed (which should register to handle the `flipper` url scheme.
> As well, with iOS I get this error:
> 
> ```
> info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
> error Browser exited with error:, invalid url, missing http/https protocol
> info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...
> error Browser exited with error:, invalid url, missing http/https protocol
> ```

**Comment by huntie** [comment]
Hi @edstbbz! Sorry you're encountering this issue. Can you share a little more info on which debugging method you're attempting to launch here? ⬇️

> 2. connect to Chrome debugger

As @lunaleaps and @blakef have noted, the current "Open Debugger" flow in the Dev Menu requires a local installation of the Flipper desktop app, and we unfortunately have an unclear error message when this URL cannot be handled 😔.

Likely workarounds:

- Install Flipper: https://fbflipper.com/docs/getting-started/
- **Recommended**: As a workaround, our recommended debugging flow (right now) if you're using Hermes is via the [manual Chrome DevTools connection flow](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools). This will enable direct (connected to the JS engine on device) debugging via Hermes and React DevTools.

**Comment by kudnayce** [comment]
debugging on android does not work the same error!

**Comment by edstbbz** [comment]
> Hi @edstbbz! Sorry you're encountering this issue. Can you share a little more info on which debugging method you're attempting to launch here? ⬇️
> 
> > 2. connect to Chrome debugger
> 
> As @lunaleaps and @blakef have noted, the current "Open Debugger" flow in the Dev Menu requires a local installation of the Flipper desktop app, and we unfortunately have an unclear error message when this URL cannot be handled 😔.
> 
> Likely workarounds:
> 
> * Install Flipper: https://fbflipper.com/docs/getting-started/
> * **Recommended**: As a workaround, our recommended debugging flow (right now) if you're using Hermes is via the [manual Chrome DevTools connection flow](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools). This will enable direct (connected to the JS engine on device) debugging via Hermes and Chrome DevTools.

Hello, @huntie ! The problem occurs when connecting to http://localhost:8081/debugger-ui or https://github.com/jhen0409/react-native-debugger , when I connect to it, app crashes

**Comment by edstbbz** [comment]
The connection to the flipper worked, but the logs in hermes were not shown, perhaps because there is an old client, since we use Chrome for debugging

**Comment by AshlandWest** [comment]
I am also experiencing this bug, on a clean install of React Native 0.72.0.
My steps to reproduce:

- `npx react-native init <myProjectsName>`
- `yarn start`
- `a`
The app loaded the example page, then I shook the device and started the debugger. The app crashed immediately and since then has crashed on launch.
In my zsh terminal, the last printed line is: `Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.<myAppsName>/.MainActivity }`
In Logcat on Android Studio, it fails on the error: `Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 17160 (mqt_js), pid 17088 (com.<myAppsName>)`

**Comment by pipo151086** [comment]
hi....

same here....

Chrome Dev Tools and Flipper 

BOTH DOESNT WORK....

Hermes debugger does not connect, console is allways empty and breakpoints doest work either>

Flipper V 190
RN 0.72

**Comment by danisOktaxi** [comment]
Hi, same error 
with RN 0.72.0
Flipper: 0.182.0

Error log crash on Flipper desktop app:

```
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 10277 (mqt_js), pid 10191 (AppName.debug)
Unknown
```

**Comment by lunaleaps** [comment]
Hey folks, thanks for the continued reports. 

We are working on a fix for the remote debugging (when you use the dev menu -> debugger which uses  uses V8 JS engine) flow for 0.72. 

We've also found an issue with direct debugging on Android (when you [debug like this](https://reactnative.dev/docs/next/hermes#debugging-js-on-hermes-using-google-chromes-devtools) and are actively investigating. 

Direct debugging on iOS for 0.72 is functional, it seems to be an Android-only issue

**Comment by lunaleaps** [comment]
Issue is fixed for Android, remote debugging: https://github.com/facebook/react-native/commit/0fe5ffd568b46104625479e1f9afa1b18cdf71b6

Pick request for 72: https://github.com/reactwg/react-native-releases/discussions/76#discussioncomment-6328673

I will open a new issue for direct debugging

**Comment by AshlandWest** [comment]
I am still experiencing this issue on React Native 72.3. Should I continue here or open a new issue?
