### ISSUE TITLE
Custom Admob View problem

### ISSUE THREAD

**Issue by checkraiser** [facebook/react-native#391]
I've created custom admob view manager followed by tutorial on react-native homepage like this:
// GADBannerViewManager.h

    @import GoogleMobileAds;
     #import "RCTViewManager.h"

    @interface GADBannerViewManager : RCTViewManager
        @property (weak, nonatomic)  GADBannerView  *bannerView;
    @end 

// GADBannerViewManager.m

    #import "GADBannerViewManager.h"

    @implementation GADBannerViewManager
    - (UIView *)view
    {
         self.bannerView.adUnitID = @"ca-app-pub-3940256099942544/2934735716"; 
        GADRequest *request = [GADRequest request];
        request.testDevices = @[
                            @"2077ef9a63d2b398840261c8221a0c9a"  // Eric's iPod Touch
                            ];
        [self.bannerView loadRequest:request];
        return self.bannerView;
    }
    RCT_EXPORT_VIEW_PROPERTY(adUnitID, NSString)
    @end

// admob.js
    'use strict';

    var createNative = require('createReactIOSNativeComponentClass');
    module.exports = createNative({
	uiViewClassName: 'GADBannerView'
    })

But there's an error throwed at debugger.
Please help.

**Comment by sahrens** [comment]
The view method needs to allocate a new GABannerView instance and return that.  You also need to specify the valid attributes in your createNative call or you won't be able to set them from JS.

**Comment by checkraiser** [comment]
I've edited liks this:
    // admob.js
    'use strict';
    var createNative = require('createReactIOSNativeComponentClass');
    module.exports = createNative({
        validAttributes: {adUnitID: "ca...},
        uiViewClassName: 'GADBannerView'
    })

    // GADBannerViewManager.m
    - (UIView*)view
    {
        GADBannerView *bannerView = [[GADBannerView alloc].....
        UIViewController *rootViewController = [UIAPplication sharedApplication].delegate.window.rootViewController;
        bannerView.rootViewController = rootViewController;
        GADRequest *request = [GADRequest request];
        request.testDevices = ...
        [bannerView loadRequest:request];
        return bannerView;
    }
    RCT_EXPORT_VIEW_PROPERTY(adUnitID, NSString)

and finally, use the admob module in index.ios.js:
    var GADBannerView = require('./admob');
    var AdmobTest = React.createClass({
        render: function(){
            <GADBannerView adUnitID="ca...." />
        }
    }

When running, the debugger doesn't make any admob request, and nothing to show.
What's wrong here?

**Comment by brentvatne** [comment]
@checkraiser - I believe I recall us resolving this in IRC. If I'm mistaken, let's follow up there or feel free to create a StackOverflow thread.

**Comment by steve-ng** [comment]
hi @brentvatne can you share how it was resolved? 

I saw the admob request, but there's nothing to be shown

 
    - (UIView *)view
    {
      bannerHeight = 50;
  
      GADRequest *request = [GADRequest request];
      bannerView = [[GADBannerView alloc] initWithAdSize:kGADAdSizeBanner];
  
      bannerView.adUnitID = @"id";
      bannerView.delegate = self;
      UIViewController *rootViewController = [UIApplication sharedApplication].delegate.window.rootViewController;
      bannerView.rootViewController = rootViewController;
  
      bannerView loadRequest:request];

      return bannerView;
    }

**Comment by brentvatne** [comment]
@steve-ng - sorry I can't remember what we ended up with here, @checkraiser do you still have your code to share?

**Comment by checkraiser** [comment]
Hi @brentvatne : I end up with a Wrap AdmobViewController, and make AdmobView a subview. It's pure ObjectiveC solution. I still don't have a pure JS solution.

**Comment by brentvatne** [comment]
Thanks @checkraiser! cc @steve-ng

**Comment by steve-ng** [comment]
Hi thanks both! :)
