### ISSUE TITLE
[Android]Image resizeMode 'contain' should be converted as 'FIT_CENTER'

### ISSUE THREAD

**Issue by ldn0x7dc** [facebook/react-native#4031]
I'm using React Native v0.12.0.
When using **Image** with *resizeMode* specified as *'contain'*, There is a big difference if the png resource is smaller than the Image view size between iOS and Android.
on iOS: the image is scaled up to fill the view with ratio unchanged
![iOS](http://pan.lndroid.me/owncloud/index.php/s/kAUR55Qf6IUZnpI/download)

on Android: the image is **NOT** scaled, which is not prefered
![android](http://pan.lndroid.me/owncloud/index.php/s/MVPAxowFy53zwNB/download)

I've dig into the related source code in *com.facebook.react.views.image.ImageResizeMode*:
> public static ScalingUtils.ScaleType toScaleType(@Nullable String resizeModeValue) {
   if ("contain".equals(resizeModeValue)) {
      return ScalingUtils.ScaleType.CENTER_INSIDE;
    }
   ...
  }

But I think it should be **FIT_CENTER**, as follows
> if ("contain".equals(resizeModeValue)) {
      return ScalingUtils.ScaleType.FIT_CENTER;
    }

Does anyone else have also noticed this issue?

**Comment by ldn0x7dc** [comment]
If the image failed to load, try refresh...

**Comment by zhuchaowe** [comment]
YES,I got this issue too;
I'm using React Native v0.14+.

**Comment by NoBaR** [comment]
I also believe FIT_CENTER would be the correct choice here...

**Comment by alvinwoon** [comment]
+1

**Comment by thstarshine** [comment]
+1

**Comment by christopherdro** [comment]
Just gave this PR a try an am still getting a white screen when setting `resizeMode` to "contain".

Can anyone else try this out and report back? Thanks!

**Comment by bcalik** [comment]
Any progress on this? Small png images does not fill the view when `resizeMode` is `contain`.

**Comment by christopherdro** [comment]
@bcalik It appears PR #5738 was shipped 3 days ago. I can't say for certain in which version in will land but you can follow that PR for further progress.

**Comment by zackify** [comment]
Glad this is getting fixed, weird to me it was setup like this.

**Comment by zackify** [comment]
For anyone interested in a fix for now. You can open up react-native in your node modules and edit `ImageResizeMode.java` located here: 
<img width="345" alt="screen shot 2016-03-02 at 12 14 26 pm" src="https://cloud.githubusercontent.com/assets/449136/13468409/6f6fdd10-e070-11e5-9634-7a0a34a383ca.png">

**Comment by christopherdro** [comment]
Fixed via https://github.com/pglotov/react-native/commit/8dab14f06263067af0762b0c44799397ab62e181

**Comment by skleest** [comment]
@christopherdro contain is still not scaling up images--am I missing something?

**Comment by christopherdro** [comment]
@skleest The fix is in 0.23-rc.

**Comment by skleest** [comment]
@christopherdro Thanks for the response, I tried both 0.23-rc as well as changing the source code manually. Maybe a bug with Fresco?

**Comment by benadamx** [comment]
@skleest @christopherdro same, just tried 0.23.0-rc1 and the behavior doesn't seem to have changed, images are not scaling to fit

**Comment by veronicapowersbeardon** [comment]
I am on RN 0.19, and I have manually changed CENTER_INSIDE to FIT_CENTER in the source code and rebuilt the app, but contain still doesn't scale images up for me.

**Comment by bcalik** [comment]
@veronicapowersbeardon just upgrade the version. It is not hard.

**Comment by benadamx** [comment]
@veronicapowersbeardon you have to recompile the entire react-native module (not just your app) from source to get those changes to be picked up, much easier (and a few hours less work) to switch to 0.23-rc1 as mentioned above

**Comment by veronicapowersbeardon** [comment]
Ah, I see.  Thank you!
