### ISSUE TITLE
Xcode build error for react-native AwesomeProject

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#4034]
I follow step but receive below output from Xcode :cry: 

```
../node_modules/react-native/packager/react-native-xcode.sh: line 45: react-native: command not found
Command /bin/sh failed with exit code 127
```

could anybody rescue me? thx ..

**Comment by ide** [comment]
This issue should be fixed in 0.14.2. Please try upgrading and close this issue if it's fixed for you.

**Comment by L-Jovi** [comment]
@ide  thanks, fix it :+1:

**Comment by brancusi** [comment]
Hi, I'm still getting this error. Just installed fresh today, package.json specifies 0.14.2. 

```bash
../node_modules/react-native/packager/react-native-xcode.sh: line 45: react-native: command not found
Command /bin/sh failed with exit code 127
```

react-native-cli is also installed globally. 

```bash
$ react-native -v #0.1.7
```

Any ideas?

**Comment by brancusi** [comment]
If I add this to the shell file right above the call to react-native it builds:

```bash
PATH=${PATH}:/Users/aramz/.node/bin
```

```bash
$ which react-native #/Users/aramz/.node/bin//react-native
```

So my path is somehow messed up.

**Comment by arunshan** [comment]
@ide I am trying to start a new project and get the following error

```
../node_modules/react-native/packager/react-native-xcode.sh: line 45: react-native: command not found
Command /bin/sh failed with exit code 127

```

**Comment by L-Jovi** [comment]
previously  I use nvm to manage node version, and this issue point that Xcode path can't find nvm path correctly, you could try my method below ..

open your `react-native-xcode.sh` which live `[your project root location]/node_modules/react-native/packager`, and add below two lines.

    source ~/.nvm/nvm.sh
    nvm use stable

maybe current stable node version is v5.0.0, when you finished above try, re-run your Xcode.

hope make sense.

**Comment by ide** [comment]
react-native-xcode.sh will source nvm.sh for you in RN 0.14.2. Perhaps you need to run `nvm alias default node` to make sure the sourcing actually does something?

**Comment by samueleaton** [comment]
I'm not seeing a `nvm.sh` in my `~/.nvm directory`. I only see an `alias`, `bin`, `nvm-exec` and `versions`. That's probably why I'm getting a failed build. But I never did any modifications to nvm so this is weird.

**Comment by samueleaton** [comment]
I am confirming my second edit in my last comment. I uninstalled nvm from homebrew and installed it using the recommended curl method. Now it compiles.

**Comment by brianjd** [comment]
Had this issue, now resolved.  It was a result of using prefixes (for installed packages) in npm configuration, which in turn was breaking nvm, which hosed the script. 

https://github.com/creationix/nvm/issues/855

**Comment by lamberta** [comment]
I ran into this issue and I'm not running nvm:
~~~
../node_modules/react-native/packager/react-native-xcode.sh: line 45: react-native: command not found
Command /bin/sh failed with exit code 127
~~~
The `react-native-xcode.sh` script is run as `$USER` but it's not getting my environment `$PATH`. (I use the prefix config option in `.npmrc`)
Here's the `$PATH` var within `react-native-xcode.sh`:
~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
~~~
