### ISSUE TITLE
Fetch stuck in (pending) iOS

### ISSUE THREAD

**Issue by Johnsgaard** [facebook/react-native#43136]
### Description

https://github.com/apollographql/apollo-client/issues/11608

I have opened an issue with `apollo/client` as I was under the assumption that it was an issue with that library. It turns out that this might be something that is more on the `react-native` / `iOS` specific side of things.

### Steps to reproduce

1.  `git clone git@github.com:Johnsgaard/fogtown.git`
2. `npm install`
3. `npm run ios` (assuming you have expo)

### React Native Version

0.73.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 994.88 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
No stack trace. Network request on iOS is locked on (pending) when making a request.
```

### Reproducer

https://github.com/Johnsgaard/fogtown

### Screenshots and Videos

![Uploading Screenshot 2024-02-21 at 10.25.22 AM.png…]()

**Comment by Johnsgaard** [comment]
<img width="1728" alt="Screenshot 2024-02-21 at 10 25 22 AM" src="https://github.com/facebook/react-native/assets/11530155/9aa088f1-74ce-4de8-8489-a4bbe45817bf">

**Comment by mekanics** [comment]
I'm having the same issue, but with redux-toolkit & rtk query. 

First I thought there was an issue with the `pollingInterval` of the queries, but at some point I was able to observe a request being sent, but never resolved in Flipper. 

Reinstalling the app helps ... for a day or two.  

Maybe it has something to do with https://github.com/facebook/react-native/issues/20405 🤔

Currently I'm using react-native v0.73.5 (upgraded while trying to solve that issue), but the problem already occurred with v0.72.7.

**Comment by mekanics** [comment]
I was able to solve the issue in our project by replacing `@babel/plugin-proposal-class-properties`, which is [deprecated](https://www.npmjs.com/package/@babel/plugin-proposal-class-properties), with `@babel/plugin-transform-class-properties`

here is the patch I use


```patch
diff --git a/node_modules/@react-native/babel-preset/src/configs/main.js b/node_modules/@react-native/babel-preset/src/configs/main.js
index e921b1b..a45aafa 100644
--- a/node_modules/@react-native/babel-preset/src/configs/main.js
+++ b/node_modules/@react-native/babel-preset/src/configs/main.js
@@ -28,7 +28,7 @@ const defaultPlugins = [
   [require('@babel/plugin-syntax-flow')],
   [require('babel-plugin-transform-flow-enums')],
   [require('@babel/plugin-transform-block-scoping')],
-  [require('@babel/plugin-proposal-class-properties'), {loose}],
+  [require('@babel/plugin-transform-class-properties'), {loose}],
   [require('@babel/plugin-transform-private-methods'), {loose}],
   [require('@babel/plugin-transform-private-property-in-object'), {loose}],
   [require('@babel/plugin-syntax-dynamic-import')],

```

**Comment by Johnsgaard** [comment]
@mekanics Amazing 👏 

I updated my `@react-native/babel-preset` but I still can't seem to get it to respond. I am wondering if I am doing something wrong when bundling the app for iOS. This will require an up-stream change I assume?

**Comment by Johnsgaard** [comment]
I updated my react-native version to the latest `0.73.6` and it seems to have the babel plugin updated in it but it still doesn't seem to work for me. 🙃

**Comment by Johnsgaard** [comment]
I also confirmed that the endpoint works inside the safari of the simulated iOS device:

<img width="1080" alt="Screenshot 2024-03-27 at 2 26 15 PM" src="https://github.com/facebook/react-native/assets/11530155/49c4c211-e850-42e7-b14d-ffe12c20708c">

I couldn't get the plugin change to work though 😕

**Comment by mekanics** [comment]
> @mekanics Amazing 👏
> 
> I updated my `@react-native/babel-preset` but I still can't seem to get it to respond. I am wondering if I am doing something wrong when bundling the app for iOS. This will require an up-stream change I assume?
> 
> Are you using `expo` to bundle / simulate your app?

No I'm not using expo. 

Is your issue always occurring? I'm asking because, I had a hard time testing/reproducing it. The problem only occurred after some time (mostly after a day or two).

**Comment by Johnsgaard** [comment]
Yeah, unfortunately I can't get it passed the (pending) step no matter what I do.

The strange thing is it works in android, curl requests are completely fine, but when I switch out the apollo-client to another api endpoint it returns in iOS. This makes me feel like it is a server configuration on my end but I can't figure it out for the life of me. I might just move my API to another host and see if that helps in anyway. Probably something to do with the SSL certs or something internal to apple that I have no idea how to resolve 😛.

**Comment by rodrigodiasf1984** [comment]
Any update on this? I've the same problem at the RN074.1

**Comment by hakonk** [comment]
I recently fixed a data race in RCTNetworkTask related to the status of the task. Probably a long shot, but do you have any thoughts on whether this fix may affect the issue you are describing here: https://github.com/facebook/react-native/issues/44694 ?

**Comment by hakonk** [comment]
If not, it would be interesting to know how the mentioned example behaves with breakpoints enabled to see how it ends up being stuck in pending mode.

**Comment by hakonk** [comment]
@Johnsgaard FYI 👆

**Comment by Johnsgaard** [comment]
@hakonk I will take a look ASAP. Do you have a version number?

**Comment by hakonk** [comment]
@Johnsgaard it's not released yet, so I guess you need to fetch the branch in the PR I submitted

**Comment by Johnsgaard** [comment]
@hakonk I can't seem to install `react-native#fix/data-race-RCTNetworkTask` branch. Will you update me when this merges and I will try to update my `react-native` version and test this.

**Comment by hakonk** [comment]
@Johnsgaard did you set my fork of the repo instead of Facebook's?

**Comment by Johnsgaard** [comment]
@hakonk thanks! I will give it a go.

**Comment by jaaywags** [comment]
Was this part of the 0.74.4 or 0.74.5 release?

**Comment by hakonk** [comment]
@jaaywags My PR only pertains to iOS. Not sure if it did resolve the issue @Johnsgaard experienced. Since then, I have had other PRs related to fixing data races merged. I believe `0.74.5` should contain all relevant to this issue. I have however not checked whether they fix this issue. I was merely curious whether the fixes could fix this as well.

**Comment by jaepang** [comment]
@hakonk 
Hey! Thank you for PR for solving issue. I reproduced this pending issue when request is **redirected** with http status code `307`.

My version is this:
```
"expo": "~51.0.36",
"react-native": "0.74.5",
```

And my request is POST to POST redirection.

**Comment by hakonk** [comment]
> @hakonk 
> 
> Hey! Thank you for PR for solving issue. I reproduced this pending issue when request is **redirected** with http status code `307`.
> 
> 
> 
> My version is this:
> 
> ```
> 
> "expo": "~51.0.36",
> 
> "react-native": "0.74.5",
> 
> ```
> 
> 
> 
> And my request is POST to POST redirection.

Hey @jaepang ! I'm happy it worked for you. Have you been able to pinpoint the fix to my PR?

**Comment by Nehal-Zeller** [comment]
@hakonk  could you help me with a weird behaviour I'm facing on my react-native app (built using cli)
When I put my application in background on ios, network calls from all 3-party sdks are _I think_ getting blocked but network calls fired to our own backend server has request body size of 174.  
Also, this happens only on production. 

expected behaviour: 3-party sdks network calls should behave same as our own network calls with proper payload. 

<img width="703" alt="Screenshot 2024-11-05 at 9 56 18 AM" src="https://github.com/user-attachments/assets/79f9b04b-27f1-4048-823c-4bb8966b7ad8">
<img width="861" alt="Screenshot 2024-11-05 at 11 13 32 AM" src="https://github.com/user-attachments/assets/1b318f94-0e0e-4316-90c1-405a32e48570">

**Comment by hakonk** [comment]
@Nehal-Zeller hi! I'm not sure if the issue you are experiencing is related to my PR.

When you say third party sdks, have you verified through which network stack they make network requests? Are they using `fetch` as well?

**Comment by Nehal-Zeller** [comment]
Thank you for your response :) 
yes, react-native-auth0 and LaunchDarkly uses `fetch` under the hood. 
Although it's might not be related to your PR but do you know, why these network calls are coming with `0 ` request_body_size and happens only on iOS and when app is in background.

**Comment by hakonk** [comment]
@Nehal-Zeller sorry, I wouldn't know unless I specifically debugged your code. Good luck!

**Comment by fahey252** [comment]
I experience HTTP requests being stuck in Pending status in the React Native DevTools Network (Expo, unstable) tab. This was due to security tools on my device enabled (Netskope). Once I disabled it, the requests were no longer stuck in Pending/working.
