### ISSUE TITLE
horrible memory leak in version 0.16

### ISSUE THREAD

**Issue by TerranTian** [facebook/react-native#4381]
create an empty project with "react-native init",run the xcode project， then you can see the memory increasing by almost 1M every second, it is horrible!
below is my screenshot,the memory reach to 400M in 4mins.
![memory leak](https://cloud.githubusercontent.com/assets/2083024/11436097/3f4b05b4-951c-11e5-8540-65878a7b5858.png)
here is then application view,just a empty project.
![screen](https://cloud.githubusercontent.com/assets/2083024/11436140/b6698490-951c-11e5-975d-65cc325f44b4.png)

**Comment by ide** [comment]
KP (https://github.com/facebook/react-native/issues/3953) -- should be fixed in master.

**Comment by rclai** [comment]
Running 0.16.0 and I am still seeing this memory leak, except it seems to be worse.

**Comment by IlyasM** [comment]
+1

**Comment by almasakchabayev** [comment]
Still having the same issue

**Comment by satya164** [comment]
@rclai Ca you try the 0.17-rc and see if it's fixed?

**Comment by pixelgamma** [comment]
I have the same issue with react-native 0.17.
