### ISSUE TITLE
RTL Layout Direction Not Updating after app reload with New React Native Architecture

### ISSUE THREAD

**Issue by serhii-yalla** [facebook/react-native#45661]
### Description

When using I18nManager to switch the layout direction between RTL (Right-to-Left) and LTR (Left-to-Right), the changes do not reflect after reload on the UI(doesn't force styles), but apply for animations. This issue appears specifically with the new React Native architecture. The styles and layout directions are only applied correctly after the app is fully restarted.

### Steps to reproduce

1. Set up a React Native project with the new architecture enabled.
2. Use I18nManager.forceRTL(true/false) to change the layout direction and use `react-native-restart`. to restart the app.
3. Observe that the UI does not update immediately(styles not forced to be like `text-align: right`.

### React Native Version

0.74.0

### Affected Platforms

Runtime - iOS, Build - MacOS

### Areas

Fabric - The New Renderer, TurboModule - The New Native Module System, JSI - Javascript Interface, Bridgeless - The New Initialization Flow, Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 272.36 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 4.3.1
    path: ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

info React Native v0.74.3 is now available (your project is running on v0.74.0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".

```
```


### Stacktrace or Logs

```text
No crush or failure
```

### Reproducer

-

**Comment by cortinico** [comment]
@serhii-yalla great thanks for the info.
Could you add a couple of videos of OldArch/NewArch? It would make it easier for me to find an owner for this one.

**Comment by serhii-yalla** [comment]
> @serhii-yalla great thanks for the info. Could you add a couple of videos of OldArch/NewArch? It would make it easier for me to find an owner for this one.

@cortinico Here it is.

https://github.com/user-attachments/assets/4068afb8-2edb-4342-94a2-91f588adfc19

https://github.com/user-attachments/assets/3ee9aa01-6d7f-4b94-ad63-11eda6da5d24

**Comment by cortinico** [comment]
Great thank you!
If we could also have a small reproducer using this template: https://github.com/react-native-community/reproducer-react-native 

it would be gold

**Comment by serhii-yalla** [comment]
@cortinico Here is reproducer for you
https://github.com/serhii-yalla/RTL-Layout-Direction-Not-Updating-after-app-reload-with-New-React-Native-Architecture

**Comment by numandev1** [comment]
getting the same issue, in the new architecture, the Layout direction is not working

**Comment by numandev1** [comment]
maybe it is related to https://github.com/facebook/react-native/pull/39803

**Comment by asgarPeerbits** [comment]
I am also facing the same issue in version 0.76.1. However, it works perfectly on Android; the issue only occurs on iOS.

**Comment by mohamedadlyy** [comment]
ihave the same issue on ios

**Comment by a-eid** [comment]
weirdly enough if you close and relaunch the app it works.

**Comment by Kaveh-ap** [comment]
The same goes for iOS and the version "react-native": "0.75.4" with the new architecture.
.
` // Enable RTL support
  [[RCTI18nUtil sharedInstance] allowRTL:YES];
  [[RCTI18nUtil sharedInstance] forceRTL:YES];`
  
  Adding these lines to the AppDelegate, or removing them doesn't make a difference at all.

**Comment by omarabualhija** [comment]
any solution for this issue ?

**Comment by a-eid** [comment]
I have not found a workaround for this yet.

**Comment by hkellou-vitalcare** [comment]
Any news on the issue ? We're unable to update our app to New Arch with this issue still going on as we heavily rely on RTL/LTR language switch especially for our demos.

**Comment by mohamedhelmi70** [comment]
I fixed the problem by adding this line of style for my reusable view component
and it's good 
the direction of the app is changed after reload the app using react-native-restart
`<View style={{ direction: I18nManager.isRTL ? "rtl" : "ltr" }} {...otherProps} />`

**Comment by a-eid** [comment]
> I fixed the problem by adding this line of style for my reusable view component and it's good the direction of the app is changed after reload the app using react-native-restart `<View style={{ direction: I18nManager.isRTL ? "rtl" : "ltr" }} {...otherProps} />`

this didn't work for me.

**Comment by hkellou-vitalcare** [comment]
> I fixed the problem by adding this line of style for my reusable view component and it's good the direction of the app is changed after reload the app using react-native-restart `<View style={{ direction: I18nManager.isRTL ? "rtl" : "ltr" }} {...otherProps} />`

Thanks for your answer. It's not a total fix for now, for example : TabNavigator isn't changing, some items using offset are going off and so on. I would say it's an "ok"-ish solution for a temporary fix, but it shouldn't behave like that with new arch vs old arch imho.

**Comment by blakef** [comment]
We spent a little time looking into this.  One of the things that came up was what's the real world use case for dynamically being able to change this when the application is running?  Clearly it's useful for testing, but how is this affecting users of your React Native application?

We're just trying to colour the impact of this.

**Comment by a-eid** [comment]
@blakef yes it's needed in the real world cases, users change languages in the app and expect to see the change reflect immediately. this works flawlessly on the web for example.

**Comment by hkellou-vitalcare** [comment]
> We spent a little time looking into this.  One of the things that came up was what's the real world use case for dynamically being able to change this when the application is running?  Clearly it's useful for testing, but how is this affecting users of your React Native application?
> 
> We're just trying to colour the impact of this.

People use to change the language say from English to Arabic and need to see those interfaces actually switch from ltr to rtl. Basically you need to "restart" app for that to happen and we've been actively using react-native-restrat until now. However with new arch it's no longer possible and this means people are going to have different app behvaiours and that's not ideal at all. Especially that closing and opening the app will give yet another view to the user (the actual expected one: say for the bottom tabs for examples that will be shown from right-to-left in rtl languages) which means it can be a really confusing UX

**Comment by mdaldoukhi** [comment]
any solution?

**Comment by KSayed91** [comment]
the issue is still exist in react-native@0.76.3 new Architecture

**Comment by mrusmanali** [comment]
I guess we have to leave an undeclared variable after the language change to let tha app crash... and hope that user will open it again.

**Comment by hkellou-vitalcare** [comment]
> I guess we have to leave an undeclared variable after the language change to let tha app crash... and hope that user will open it again.

I would advice against it, that will make your crash metrics go down hill and might trigger an alert in your google play console.

**Comment by AsherSheikh** [comment]
Having facing the same issue only on iOS, android work perfectly in react native version 0.76.3... any update for iOS ??

**Comment by cortinico** [comment]
Another reproducer: https://github.com/bhojaniasgar/RTLIssue

**Comment by ahmamedhat** [comment]
Facing the same issue here, I use:

```
"react-native": "0.76.3",
"expo": "~52.0.11"
```

**Comment by armata99** [comment]
I'm experiencing same issue on IOS with `react-native: 0.76.3` and newArch enabled. Android is fine.

**Comment by mktufan21** [comment]
Disable newArch until it is fixed
add this inside your PodFile
use_react_native!(:path => config[:reactNativePath], :new_arch_enabled => false)

# Optional: Remove React-Codegen (it is only required with the new architecture)
$ReactNativePath = "../node_modules/react-native"
pod 'React-Codegen', :path => $ReactNativePath, :inhibit_warnings => true if false

**Comment by asgarPeerbits** [comment]
@mktufan21  After making this false react-native-mmkv is not working in Version 3.x..x  and when downgrading MMKV 2.x.x then android not working 

is there any way to use MMKV version 3.x.x in android and 2.x.x in iOS till this issue solves in new Architecture

**Comment by a-eid** [comment]
@asgarPeerbits ah I didn't get your question correctly, I don't think there is a proper way to use mmkv v2 on ios & v3 on android. just downgrade back to mmkv v2 until this is fixed.

**Comment by Saad962404** [comment]
I'm also experiencing same with new arch.
 "react-native": "0.76.1",

**Comment by blakef** [comment]
Locking as we’re aware this has never worked on iOS with the new architecture.

**Comment by cipolleschi** [comment]
This should be fixed by https://github.com/facebook/react-native/pull/49455

**Comment by a-eid** [comment]
@Linuhusainnk I think it'll be released to both 0.76 & 0.77 cc @cortinico

**Comment by ahmamedhat** [comment]
@a-eid @Linuhusainnk Guys any idea how to make a patch with this until its released? i have tried adding this line
`[self _updateLayoutContext];` 
in the same exact place changed in the PR, deleted ios directory and rebuilt the app again but sadly it didn’t work
i am using rtl manager and forcing to and from RTL and then call RNRestart the app restarts but nothing happens had to close and reopen the app, is there’s something im missing here?!

**Comment by a-eid** [comment]
@ahmamedhat I am not sure TBH, could you share your patch file and some details about your setup ?

**Comment by cipolleschi** [comment]
If you want for the patch to be released, you need to open pick requests for each version using [this template](https://github.com/reactwg/react-native-releases/issues/new?template=pick_request_form.yml).

We release new patches of older version periodically, when there is a critical commit or when there are enough commits to ship to justify the release.

**Comment by baraa-rasheed** [comment]
The UI is being updated correctly but the native-stack navigator is not, you can test this by setting the headerLargeTitle to true and try to change the RTL direction.

**Comment by karem-details** [comment]
RTL problem still exists on iOS expo: "53.0.4", react-native: "0.79.1" [https://streamable.com/x88p91](url)

**Comment by karem-details** [comment]
> RTL problem still exists on iOS expo: "53.0.4", react-native: "0.79.1"
> 
>  Simulator.Screen.Recording.-.iPhone.16.-.2025-05-11.at.14.29.31.mp4

The problem fixed after removing expo-localization package

**Comment by cipolleschi** [comment]
The pick has not been made for 0.77 and 0.78.
@Linuhusainnk you opened only a pick request for 0.76: https://github.com/reactwg/react-native-releases/issues?q=sort%3Aupdated-desc%20is%3Aissue%20state%3Aclosed%20RTL

We need pick requests for all the versions that need it. 0.79 is going to ship with the fix already, so we need a pick request for 0.77 and one for 0.79

**Comment by a-eid** [comment]
@cipolleschi it's worth noting that this doesn't fully fix the issue completely. sometimes after restarting the bundle the app maintain it's direction and doesn't switch properly.

**Comment by MKSisti** [comment]
@cipolleschi any news on this topic ? we're still getting the issue of RTL not being applied properly. Reloading the app manually does nothing (checking rtl using something like 'rtl:bg-indigo-500' shows clearly that rtl is being set to the app)
using 0.79.4 and expo 53

**Comment by Karemhz** [comment]
> @cipolleschi any news on this topic ? we're still getting the issue of RTL not being applied properly. Reloading the app manually does nothing (checking rtl using something like 'rtl:bg-indigo-500' shows clearly that rtl is being set to the app)
> using 0.79.4 and expo 53

Fixed after removing expo-localization

**Comment by MKSisti** [comment]
> > [@cipolleschi](https://github.com/cipolleschi) any news on this topic ? we're still getting the issue of RTL not being applied properly. Reloading the app manually does nothing (checking rtl using something like 'rtl:bg-indigo-500' shows clearly that rtl is being set to the app)
> > using 0.79.4 and expo 53
> 
> Fixed after remove expo-localization

removing expo-localization doesn't fix the issue, plus we need expo-localization in our app

EDIT:
removing expo-localization did fix it at the end, moving things around (when to reload and how) plus removing the expo-localization seems to fix the issue. thanks @Karemhz appreciate it

**Comment by Karemhz** [comment]
I'm using "react-native-get-device-locale" instead of "expo-localization" to get device locale

**Comment by Nader-CS** [comment]
yes i can confirm remove `expo-localization` fixed it

**Comment by trushal-dev1111** [comment]
I'm not using Expo CLI; I'm working with the React Native CLI.
I also haven’t installed any localization-related library, and the issue occurs only on iOS — everything works fine on Android.

Here is my package.json:
{
  "name": "RTLTab",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.5",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "i18next": "^23.16.8",
    "react": "19.0.0",
    "react-i18next": "^13.5.0",
    "react-native": "0.78.0",
    "react-native-restart": "^0.0.27",
    "react-native-screens": "^3.37.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "^13.6.9",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.78.0",
    "@react-native/eslint-config": "0.78.0",
    "@react-native/metro-config": "0.78.0",
    "@react-native/typescript-config": "0.78.0",
    "@types/jest": "^29.5.13",
    "@types/react": "^19.0.0",
    "@types/react-test-renderer": "^19.0.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "19.0.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

**Comment by usmannazir786** [comment]
the solution is here add the below line to the file RCTFabricSurface.mm [self _updateLayoutContext]

where can you find these file : ios/Pods/React/Fabric/Surface/RCTFabricSurface.mm (or) node_modules/react-native/React/Fabric/Surface/RCTFabricSurface.mm

depends on how your rn project setuped

if (!_view) {

[self _updateLayoutContext]; // add this line _view = [[RCTSurfaceView alloc] initWithSurface:(RCTSurface *)self]; _touchHandler = [RCTSurfaceTouchHandler new]; [_touchHandler attachToView:_view]; } after adding I re-builded the app

it works for me!

After adding [self _updateLayoutContext]; and rebuilding, the issue is fixed on iOS for me too.

**Comment by a-eid** [comment]
funny enough this is still an issue.
