### ISSUE TITLE
[iOS] Upload Symbols Failed on Xcode 16 

### ISSUE THREAD

**Issue by zzz08900** [facebook/react-native#46853]
### Description

So everything looks to be working fine, but when building .ipa/uploading to AppStore Connect I got this warning:
The archive did not include a dSYM for the hermes.framework with the UUIDs *****

Although everything seems to be in working order (the ipa is successfully uploaded to AppStore Connect), I'm wondering if there's a way to get rid of this warning.

### Steps to reproduce

1. Create react native project with `npx @react-native-community/cli@latest init rnTest1 --version 0.74.5`
3. Open project in Xcode 16 and build it, then upload the ipa to AppStore Connect
4. At the end of uploading process you'll be greeted with the warning.

### React Native Version

0.74.5

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (12) x64 Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz
  Memory: 34.94 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.18.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/lib/ruby/gems/3.3.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.3.5
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.75.4 is now available (your project is running on v0.74.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.75.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.5
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Stacktrace or Logs

```text
null
```

### Reproducer

https://github.com/zzz08900/react-native-hermes-dSYM

### Screenshots and Videos

<img width="751" alt="Screenshot 2024-10-07 at 00 38 34" src="https://github.com/user-attachments/assets/feb6e7e3-52df-49d2-a566-88505e2ceac3">

**Comment by cipolleschi** [comment]
@zzz08900 Thanks for the issue. we fixed that already with this commit f529fe48768b8a1ee4d74a4964a294c485da83b9, but we forgot to cherry pick it. Let me create pick requests for that.

To unblock yourself, you can 
- open the file `<yourApp>/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/Info.plist`
- manually remove ALL the instances of the following lines:
```xml
<key>DebugSymbolsPath</key>
<string>dSYMs</string>
``` 
- save the file
- create a new build

**Comment by migueldaipre** [comment]
Fixed in the release candidate [v0.76](https://github.com/facebook/react-native/releases/tag/v0.76.0-rc.5)

**Comment by kashmiry** [comment]
> @zzz08900 Thanks for the issue. we fixed that already with this commit [f529fe4](https://github.com/facebook/react-native/commit/f529fe48768b8a1ee4d74a4964a294c485da83b9), but we forgot to cherry pick it. Let me create pick requests for that.
> 
> To unblock yourself, you can
> 
> * open the file `<yourApp>/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/Info.plist`
> * manually remove ALL the instances of the following lines:
> 
> ```
> <key>DebugSymbolsPath</key>
> <string>dSYMs</string>
> ```
> 
> * save the file
> * create a new build

I have tried this on 0.74.6 and previously on 0.73.8. but the warning still does not disappear when i remove the lines.

**Comment by matttturnbull** [comment]
Thanks for the fix in 0.76, in the mean time:

Does anyone know how to patch this fix so that it stays in place after a re-install? If I run the following:

- `rm -rf node_modules`
- `yarn`
- `npx pod-install`

Then the fix is reverted and the error persists.

**Comment by auhonganh** [comment]
> @zzz08900 Thanks for the issue. we fixed that already with this commit [f529fe4](https://github.com/facebook/react-native/commit/f529fe48768b8a1ee4d74a4964a294c485da83b9), but we forgot to cherry pick it. Let me create pick requests for that.
> 
> To unblock yourself, you can
> 
> * open the file `<yourApp>/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/Info.plist`
> * manually remove ALL the instances of the following lines:
> 
> ```
> <key>DebugSymbolsPath</key>
> <string>dSYMs</string>
> ```
> 
>  * save the file
> * create a new build

I have tried this on version 0.74.2, but the warning still appears when validating the archive.

**Comment by cipolleschi** [comment]
We should backport the fix to previous versions then.

**Comment by matttturnbull** [comment]
Should this be re-opened? As it seems that the issue is still present in 0.76.3

**Comment by joaonew** [comment]
Having the same issue on react-native 0.76.3

**Comment by axuu** [comment]
Having the same issue on react-native 0.76.2

**Comment by Vishalgihub** [comment]
![WhatsApp Image 2024-12-12 at 8 30 04 PM](https://github.com/user-attachments/assets/2f8ae542-496f-4f06-8d84-c8fc03797235)


my react native ios give this error 

i am using a xcode version 16 and my react  native version is 74

i can try
 https://github.com/facebook/react-native/issues/46853#issuecomment-2527452044
 
 this but still i get this error i can use this chat all related answer but not working please help

**Comment by nes123** [comment]
The need to download the dSYM files with every package update is overly burdensome.

**Comment by nes123** [comment]
I am tempted to turn off hermes which in any case makes start-up very slow in iOS

**Comment by cipolleschi** [comment]
There are some issues related to Xcode 16 that might make this worse: https://forums.developer.apple.com/forums/thread/763731?page=4

It might not be a React Native problem, as many other libraries are affected

Out of curiosity, is there someone that is encountering this issue and that is developing using Expo and uploading with EAS?

**Comment by Hknzbyn** [comment]
@cipolleschi Hello, in my case, I moved an application that I built with eas and successfully sent to testflight to cli due to sdks that do not support expo.
In summary, eas build / submit processes were smooth

**Comment by Harry-Drew-CyanBytes** [comment]
Any updates on this? I still get the error in react native version: 0.76.6

**Comment by cipolleschi** [comment]
Which version of Xcode are you using?
I also reached out to Expo to understand if they do something special when uploading to the App Store with EAS.

The error makes no sense to me, because there are no references to the dSYMS in the Hermes.xcframework...

**Comment by eedeebee** [comment]
I'm getting the same  symptom with RN 0.72 when I upgradef from older XCode to XCode 16 in order to ,make debug builds for an iOS 18 device.  I"m trying to upload a release build.   Since I was doing this same build pre XCode 16, I'm asssuming this wartning is just letting me know aomehting about my bujilds thay is not new as I didn't otherwize change anything about my RN bujild other than moving to XCode 16....

**Comment by hassanharoon321** [comment]
did anyone find the solution I'm still looking for solution nothing works here

**Comment by cipolleschi** [comment]
@hassanharoon321 
1. move to Xcode 16.2
2. clean up all the caches for cocoapods:
  i. `rm -rf Pods Podfile.lock <YourApp>.xcworkspace`
  ii. clean up derived data `rm -rf ~/Library/Developer/Xcode/DerivedData/`
  iii. `rm -rf ~/Library/Caches/CocoaPods/Pods/External/hermes-engine/`
3. clean up `node_modules` `rm -rf node_modules`
4. rerun `yarn install && cd ios && bundle install && bundle exec pod install`

**Comment by suhitaga** [comment]
yeah i just got this too... the app seems to upload to testflight still but it's weird and interesting nonetheless

**Comment by fivecar** [comment]
> [@hassanharoon321](https://github.com/hassanharoon321)
> 
> 1. move to Xcode 16.2
> 2. clean up all the caches for cocoapods:
>    i. `rm -rf Pods Podfile.lock <YourApp>.xcworkspace`
>    ii. clean up derived data `rm -rf ~/Library/Developer/Xcode/DerivedData/`
>    iii. `rm -rf ~/Library/Caches/CocoaPods/Pods/External/hermes-engine/`
> 3. clean up `node_modules` `rm -rf node_modules`
> 4. rerun `yarn install && cd ios && bundle install && bundle exec pod install`

@cipolleschi Ran that just now on Xcode 16.2 and RN 0.76.6, and still get the error...

**Comment by Noam-shushan** [comment]
> > [@hassanharoon321](https://github.com/hassanharoon321)
> > 
> > 1. move to Xcode 16.2
> > 2. clean up all the caches for cocoapods:
> >    i. `rm -rf Pods Podfile.lock <YourApp>.xcworkspace`
> >    ii. clean up derived data `rm -rf ~/Library/Developer/Xcode/DerivedData/`
> >    iii. `rm -rf ~/Library/Caches/CocoaPods/Pods/External/hermes-engine/`
> > 3. clean up `node_modules` `rm -rf node_modules`
> > 4. rerun `yarn install && cd ios && bundle install && bundle exec pod install`
> 
> [@cipolleschi](https://github.com/cipolleschi) Ran that just now on Xcode 16.2 and RN 0.76.6, and still get the error...

As well here:

<img width="744" alt="Image" src="https://github.com/user-attachments/assets/33f1965f-2a59-45c3-afd4-84c4c9a13d65" />

![Image](https://github.com/user-attachments/assets/d6494572-1f23-4150-8c13-66ed74c79245)

**Comment by anndoman** [comment]
I think i checked all the options in the comments and none of them work, I am still getting error :( 
xcode version: 16.2
react native version: 0.76.3 but I also upgraded the version to 0.76.5 and checked it

**Comment by vitalybaev** [comment]
Also having the same issue for quite some time. XCode 16.2, `react-native` `0.76.6`

**Comment by importre** [comment]
Same issue with RN 0.77.0 and Xcode 16.2.

# Workaround

To resolve this issue, I added the following script to the Pre-actions of the Archive step in Xcode’s scheme settings.


## generate-hermes-dsym.sh
```sh
if [[ -z "$1" ]]; then
  echo "❌ Usage: $0 <TargetName>"
  exit 1
fi

TARGET_NAME=$1

export ARCHIVE_PATH=$(ls -dt ~/Library/Developer/Xcode/Archives/*/"$TARGET_NAME"*.xcarchive | head -1)
echo "📦 Using Archive Path: $ARCHIVE_PATH"

if [[ ! -d "$ARCHIVE_PATH" ]]; then
  echo "❌ Archive not found for target: $TARGET_NAME! Please archive the project first in Xcode."
  exit 1
fi

echo "🔍 Existing dSYM files:"
find "$ARCHIVE_PATH/dSYMs" -name "*.dSYM"

export HERMES_BINARY=$(find "$ARCHIVE_PATH/Products/Applications" -name "hermes.framework" -type d)
echo "📍 Hermes Binary Path: $HERMES_BINARY"

if [[ ! -d "$HERMES_BINARY" ]]; then
  echo "❌ Hermes framework not found!"
  exit 1
fi

dsymutil "$HERMES_BINARY/hermes" -o "$ARCHIVE_PATH/dSYMs/hermes.framework.dSYM"
echo "✅ Hermes dSYM generated at: $ARCHIVE_PATH/dSYMs/hermes.framework.dSYM"

echo "📂 Final dSYM files:"
find "$ARCHIVE_PATH/dSYMs" -name "*.dSYM"

echo "🎉 Done! Hermes dSYM successfully generated!"
```

## Xcode Pre-actions Setup

In Edit Scheme → Archive → Pre-actions, add the following script

```
sh generate_hermes_dsym.sh "$TARGET_NAME"
```

**Comment by gkasireddy202** [comment]
Facing the same issue on Xcode 16.2
react-native:0.73.7

**Comment by gkasireddy202** [comment]
> [@zzz08900](https://github.com/zzz08900) Thanks for the issue. we fixed that already with this commit [f529fe4](https://github.com/facebook/react-native/commit/f529fe48768b8a1ee4d74a4964a294c485da83b9), but we forgot to cherry pick it. Let me create pick requests for that.
> 
> To unblock yourself, you can
> 
> * open the file `<yourApp>/ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/Info.plist`
> * manually remove ALL the instances of the following lines:
> 
> <key>DebugSymbolsPath</key>
> <string>dSYMs</string>
> * save the file
> * create a new build

@cipolleschi  - I followed the above steps in my project. My project has react-native:0.73.7.
uncomment the below one.


<img width="1319" alt="Image" src="https://github.com/user-attachments/assets/a6169440-4842-4fb4-8c9d-89a5fc4febbf" />

<img width="1193" alt="Image" src="https://github.com/user-attachments/assets/16dd6266-1b61-4372-bba7-9519409e74c3" />

**Comment by cipolleschi** [comment]
I believe something is wrong with Xcode 16.2. Those steps use to work with previous versions of Xcode when this was happening.

Sadly, there is very little I can do as we don't control Xcode.

For anyone reading: what you are seeing is just a warning. It does not prevent you from upload and submit your app and Apple will not reject your app because of missing debug symbols in the release binary.

**Comment by kaushikdas0** [comment]
This issue still exists even today, can we not request to reopen this issue for tracking?

**Comment by cipolleschi** [comment]
The issue is duplicated by other issues. 
- #49059
- #35863
- #46243

I'll lock this and the other two that are closed already, please forward all the comments to the one open: #49059
