### ISSUE TITLE
*** -[NSXPCEncoder _checkObject:]: This coder only encodes objects that adopt NSSecureCoding (object is of class 'RCTWeakEventEmitterWrapper').

### ISSUE THREAD

**Issue by Voxar** [facebook/react-native#47762]
### Description

Crash as soon as I enter anything in a `<TextInput />`, when running app via Mac Catalyst

### Steps to reproduce

1. New project with `npx create-expo-app@latest`
2. Start it up to create ios folder `npm expo run:ios`
3. Cancel the run after CocoaPods install
4. Start metro with `yarn start`
5. Open Xcode project, go to projects General tab
6. Remove the iPad destination
7. Add the Mac Catalyst destination
8. Pick a Development Team under Signing & Capabilities
9. Run with target "My Mac (Designed for iPhone)" and make sure it works. 
10. Add a `<TextInput />` anywhere in the example app. 
11. Fix eventual "Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView"
12. Try to type something into your TextField

### React Native Version

0.76.2

### Affected Platforms

Runtime - iOS, Runtime - Desktop

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
⚠️ react-native depends on @react-native-community/cli for cli commands. To fix update your package.json to include:


  "devDependencies": {
    "@react-native-community/cli": "latest",
  }
```

### Stacktrace or Logs

```text
*** -[NSXPCEncoder _checkObject:]: This coder only encodes objects that adopt NSSecureCoding (object is of class 'RCTWeakEventEmitterWrapper').
(
	0   CoreFoundation                      0x0000000193488ec0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000192f6ecd8 objc_exception_throw + 88
	2   Foundation                          0x0000000194595214 -[NSXPCEncoder _checkObject:] + 308
	3   Foundation                          0x0000000194594ee8 -[NSXPCEncoder _encodeUnkeyedObject:] + 40
	4   Foundation                          0x00000001945a5f20 -[NSXPCEncoder _encodeArrayOfObjects:forKey:] + 184
	5   Foundation                          0x00000001945c04fc -[NSDictionary(NSDictionary) encodeWithCoder:] + 568
	6   Foundation                          0x0000000194595520 -[NSXPCEncoder _encodeObject:] + 488
	7   Foundation                          0x00000001946620e8 -[NSAttributedString encodeWithCoder:] + 224
	8   Foundation                          0x0000000194595520 -[NSXPCEncoder _encodeObject:] + 488
	9   RemoteTextInput                     0x00000001b30d9874 -[RTIDocumentState encodeWithCoder:] + 592
	10  Foundation                          0x0000000194595520 -[NSXPCEncoder _encodeObject:] + 488
	11  Foundation                          0x000000019459a210 _NSXPCSerializationAddInvocationWithOnlyObjectArgumentsArray + 116
	12  Foundation                          0x000000019459a0c8 -[NSXPCEncoder _encodeInvocationObjectArgumentsOnly:count:typeString:selector:isReply:into:] + 212
	13  Foundation                          0x00000001945939e4 -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 1208
	14  Foundation                          0x0000000194599fb8 -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:] + 128
	15  Foundation                          0x0000000194599ee0 _NSXPCDistantObjectSimpleMessageSend2 + 68
	16  RemoteTextInput                     0x00000001b30de054 __52-[RTIInputSystemClient _updateTextForSessionWithID:]_block_invoke + 72
	17  RemoteTextInput                     0x00000001b30dd9b8 __58-[RTIInputSystemClient enumerateServices:force:withBlock:]_block_invoke.139 + 60
	18  CoreFoundation                      0x00000001934462c4 __NSSET_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	19  CoreFoundation                      0x00000001934591b0 -[__NSSetM enumerateObjectsWithOptions:usingBlock:] + 276
	20  RemoteTextInput                     0x00000001b30dd888 -[RTIInputSystemClient enumerateServices:force:withBlock:] + 288
	21  RemoteTextInput                     0x00000001b30ddfd8 -[RTIInputSystemClient _updateTextForSessionWithID:] + 244
	22  RemoteTextInput                     0x00000001b30df75c -[RTIInputSystemClient remoteTextInputSessionWithID:documentDidChange:] + 156
	23  UIKitCore                           0x00000001c58e65f0 __39-[UIKBRTIPartner documentStateChanged:]_block_invoke + 136
	24  UIKitCore                           0x00000001c58eae70 __48-[UIKBRTIPartner _updateRTIStateWithCompletion:]_block_invoke + 288
	25  UIKitCore                           0x00000001c58f307c -[UIKBRTIPartner _queryUIKitDocumentRequest:completion:] + 4336
	26  UIKitCore                           0x00000001c58f0ca8 -[UIKBRTIPartner _queryDocumentRequest:completion:] + 136
	27  UIKitCore                           0x00000001c58ead1c -[UIKBRTIPartner _updateRTIStateWithCompletion:] + 312
	28  UIKitCore                           0x00000001c58e99c4 -[UIKBRTIPartner updateStateWithCompletion:updateTraits:] + 144
	29  UIKitCore                           0x00000001c58e6554 -[UIKBRTIPartner documentStateChanged:] + 176
	30  UIKitCore                           0x00000001c587bfe0 -[UIKeyboardImpl _selectionScrolling:scroller:] + 84
	31  UIKitCore                           0x00000001c587bf24 -[UIKeyboardImpl selectionScrolling:] + 152
	32  CoreFoundation                      0x000000019340af80 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
	33  CoreFoundation                      0x000000019349c274 ___CFXRegistrationPost_block_invoke + 88
	34  CoreFoundation                      0x000000019349c1bc _CFXRegistrationPost + 436
	35  CoreFoundation                      0x00000001933d9634 _CFXNotificationPost + 732
	36  Foundation                          0x0000000194581924 -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
	37  UIKitCore                           0x00000001c5e87cd4 -[UIScrollView _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:animation:animationConfigurator:] + 452
	38  UIKitCore                           0x00000001c5d039a4 -[UIFieldEditor setContentOffset:animated:] + 112
	39  UIKitCore                           0x00000001c5e78e4c -[UIScrollView scrollRectToVisible:animated:] + 668
	40  UIKitCore                           0x00000001c5d038a0 -[UIFieldEditor _scrollRangeToVisible:animated:] + 300
	41  UIKitCore                           0x00000001c5d03910 -[UIFieldEditor scrollSelectionToVisible:] + 64
	42  UIKitCore                           0x00000001c5d015d8 -[UIFieldEditor textInputDidChangeSelection:] + 80
	43  UIKitCore                           0x00000001c5d2372c -[UITextInputController _sendDelegateChangeNotificationsForText:selection:replacement:characterRange:] + 100
	44  UIKit                               0x000000026edb2298 -[UITextInputControllerAccessibility _sendDelegateChangeNotificationsForText:selection:] + 96
	45  UIKitCore                           0x00000001c5d24144 __46-[UITextInputController setSelectedTextRange:]_block_invoke_3 + 192
	46  UIKitCore                           0x00000001c5d2444c __52-[UITextInputController _coordinateSelectionChange:]_block_invoke + 104
	47  UIFoundation                        0x000000019835d268 -[NSTextStorage coordinateReading:] + 56
	48  UIKitCore                           0x00000001c5d243c0 -[UITextInputController _coordinateSelectionChange:] + 144
	49  UIKitCore                           0x00000001c5d23eec -[UITextInputController setSelectedTextRange:] + 488
	50  UIKitCore                           0x00000001c5d248cc -[UITextInputController _insertText:fromKeyboard:] + 728
	51  UIKitCore                           0x00000001c5d25344 -[UITextInputController insertText:] + 360
	52  UIKitCore                           0x00000001c5d03cbc -[UIFieldEditor _handleObscuredTextInputIfNecessaryWithEditingBlock:] + 376
	53  UIKitCore                           0x00000001c5d03f14 -[UIFieldEditor insertFilteredText:] + 392
	54  UIKitCore                           0x00000001c5d18c24 -[UITextField insertFilteredText:] + 76
	55  UIKitCore                           0x00000001c55a8ebc -[UIKBInputDelegateManager insertText:updateInputSource:] + 292
	56  UIKit                               0x000000026eca0a94 -[UIKBInputDelegateManagerAccessibility insertText:updateInputSource:] + 112
	57  UIKitCore                           0x00000001c55a3568 -[UIKBInputDelegateManager insertText:] + 92
	58  UIKitCore                           0x00000001c51ee5ec -[_UIKeyboardStateManager performKeyboardOutput:checkingDelegate:forwardToRemoteInputSource:] + 3732
	59  UIKit                               0x000000026ec91e90 -[_UIKeyboardStateManagerAccessibility performKeyboardOutput:checkingDelegate:forwardToRemoteInputSource:] + 140
	60  UIKitCore                           0x00000001c58f0920 -[UIKBRTIPartner _performKeyboardOutputOperations:] + 608
	61  UIKit                               0x000000026ec9553c -[UIKBRTIPartnerAccessibility _performKeyboardOutputOperations:] + 100
	62  UIKitCore                           0x00000001c58eeed0 -[UIKBRTIPartner _queued_performTextOperations:resultHandler:] + 780
	63  libdispatch.dylib                   0x0000000100c04b64 _dispatch_call_block_and_release + 32
	64  libdispatch.dylib                   0x0000000100c068a4 _dispatch_client_callout + 20
	65  libdispatch.dylib                   0x0000000100c19d38 _dispatch_main_queue_drain + 1092
	66  libdispatch.dylib                   0x0000000100c198e4 _dispatch_main_queue_callback_4CF + 44
	67  CoreFoundation                      0x0000000193455680 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
	68  CoreFoundation                      0x000000019341517c __CFRunLoopRun + 1996
	69  CoreFoundation                      0x0000000193414334 CFRunLoopRunSpecific + 572
	70  HIToolbox                           0x000000019e84c0cc RunCurrentEventLoopInMode + 292
	71  HIToolbox                           0x000000019e851ebc ReceiveNextEventCommon + 636
	72  HIToolbox                           0x000000019e852020 _BlockUntilNextEventMatchingListInModeWithFilter + 76
	73  AppKit                              0x0000000196f57a70 _DPSNextEvent + 660
	74  AppKit                              0x000000019787d7b8 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
	75  AppKit                              0x0000000196f4ab7c -[NSApplication run] + 480
	76  AppKit                              0x0000000196f2144c NSApplicationMain + 888
	77  AppKit                              0x000000019716f8e4 +[NSWindow _savedFrameFromString:] + 0
	78  UIKitMacHelper                      0x00000001adb938b0 UINSApplicationMain + 972
	79  UIKitCore                           0x00000001c4af3c40 UIApplicationMain + 148
	80  RamiLora.debug.dylib                0x00000001059a8a5c __debug_main_executable_dylib_entry_point + 96
	81  dyld                                0x0000000192fac274 start + 2840
)
```

### Reproducer

https://github.com/Voxar/react-native-textinput-crash

### Screenshots and Videos

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/0ca3a928-20a4-465e-a1b6-76e356389dd9">

**Comment by miinos** [comment]
Having the same issue when running application on macos m1.

**Comment by jbcullis** [comment]
Problem exhibits on 76.2 but 76.1 is fine.
Quick fix is to revert to 76.1

Also, issue only exhibits on catalyst. Building to an iPhone or iPhone simulator works fine.

**Comment by toy0605** [comment]
I’m experiencing the same issue. I’m building using Mac Catalyst.

This issue might have been caused by https://github.com/facebook/react-native/commit/36fd5533f68b0f907a949db87884b58820015ba8 (related to [React Native v0.76.2 release](https://github.com/facebook/react-native/releases/tag/v0.76.2)).

**Comment by simonbengtsson** [comment]
We hade this issue with 0.76.3. Downgraded to 0.76.1 as suggested above and it now works.

**Comment by Voxar** [comment]
Thanks for verifying. I'll add to the description that it only affects Catalyst.

My workaround is to disable new arch. I only use catalyst for development so I hope to be able to enable it without further changes for release builds.

- app.json: `"newArchEnabled": false,`
- gradle.properties: `newArchEnabled=false`
- Podfile.properties.json: `"newArchEnabled": "false"`

**Comment by iwater** [comment]
this crash also happen on a iOS build app running on Apple Silicon Mac(in Xcode Destination: "Mac(Designed for iPad)") not only Mac Catalyst

**Comment by jakeherm** [comment]
Was this issue solved? I am still getting this crash on an iPad.

**Comment by cipolleschi** [comment]
@jakeherm iPad should use the same iOS code. On which version are you? We released 0.76.6 last week and it should contain the fix.

**Comment by jakeherm** [comment]
Perfect. I will update.

**Comment by claitonlovato** [comment]
Any updates on this issue please? We are having the same issue, were using 0.76.5, updated to 0.76.6 today but same issue still present. Upgrading to 0.77.0 is not an option right now for us because of some additional expo packages that are not compatible.

**Comment by cipolleschi** [comment]
@claitonlovato I reopened the issue. We had to revert it because the PR was making some inner text anchors not clickable anymore. Sadly we don't have a clean solution right now. Some of my colleagues are investigating it.

**Comment by Voxar** [comment]
Woho! I did build with the new arch just this week and was surprised to not crash 🥳
