### ISSUE TITLE
[TextInput] Error setting property 'text' of RCTTextField with tag #144: Native TextInput(Hdsgdh) is 4 events ahead of JS - try to make your JS faster.

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#4845]
This error happens when you type extremely fast. The more components you have alongside it, the more likelihood that this will happen.

```
<TextInput value={this.state.value} onChangeText={value => this.setState({ value })} />
```

And if you hit submit IMMEDIATELY after typing, the value won't be set and the input may just be blank.

In order for the value to actually be there, you have to wait just a little bit, then you can hit enter and the value will stay. 

This is on iOS.

**Comment by brentvatne** [comment]
`setState` must be expensive, can you re-create this issue with an example project that we can clone and try?

**Comment by tomauty** [comment]
I believe it's due to creating a function for every re-render of TextInput. I know this is "old" in RN time, but try putting that function outside of the render function

**Comment by rclai** [comment]
I'll have to give that a try, thanks.

**Comment by rclai** [comment]
@tomauty you were right, putting the function outside made it perform faster and I didn't get the error when I typed really fast.

**Comment by someok** [comment]
My function outside, but I still meet this warn.

```
<TextFieldHolder withValue={hasText}>
                    <TextInput
                        ref="textInput"
                        placeholder={this.props.placeHolder}
                        style={[styles.valueText, this.props.textInputStyle]}
                        multiline={this.props.multiline}
                        value={this.state.text}
                        onFocus={this._setFocus}
                        onBlur={this._unsetFocus}
                        onChangeText={this._setText}
                        {...this.props.textInputProps}
                    />
                </TextFieldHolder>
```

**Comment by kristikristo** [comment]
My function is outside too, but I still meet the warnings. When I test it on the device, is really slow when I try to move to the next TextInput. Any solution yet?

**Comment by chandlervdw** [comment]
+1 — I'm also looking for a solution to this.

**Comment by tuxtux00** [comment]
+1 - and me too

**Comment by stief510** [comment]
+1

**Comment by kristojorg** [comment]
+1

**Comment by rclai** [comment]
@brentvatne is this a legitimate issue that deserves a Product Pains post or is it just a matter of keeping your components light-weight so that re-renders don't cause this?

**Comment by wootwoot1234** [comment]
@tomauty thanks for the tip.  That helped but didn't totally fix it. 

Anyone else have a good work around?

The solutions I can think of are to pass the text value in the onBlur prop or add another prop that is like onChangeText but with some sort of delay so that it doesn't fire until the user takes a break from typing (or deleting).

**Comment by wootwoot1234** [comment]
I think this needs to be reopend.

**Comment by Brockify** [comment]
+1  I agree

**Comment by jpgarcia** [comment]
+1

**Comment by jgkim** [comment]
+1

**Comment by nlively** [comment]
+1

**Comment by dwilt** [comment]
+1

**Comment by dwilt** [comment]
For anyone looking for a workaround who doesn't need to constantly read the state of the text and only needs it on submission, I think I have one. I'm not sure this is reliable yet but it seems to work and definitely gets rid of the warning and the slowness.

**The workaround is to remove the `onChangeText` all together and read from the input's `_lastNativeText` property off the `ref`: `this.refs.input._lastNativeText`.** 

For more details on what I did..

Here's what my original `SearchInput.js` input looked like:

```javascript
render() {
    var { backgroundColor, isEditing, onFocus, onBlur, onSubmitEditing, onChangeText } = this.props;

    // ... edited for brevity 

    return (
        <View style={containerStyles}>
            <View style={styles.inputContainer}>
                <TextInput
                    ref="input"
                    style={styles.input}
                    returnKeyType={returnKeyType}
                    onFocus={onFocus}
                    onBlur={onBlur}
                    onSubmitEditing={onSubmitEditing}
                    onChangeText={onChangeText}
                />
                {inputIcon}
                {label}
                {clearButton}   
            </View>
        </View>
    )
}
```
As suggested above, I was reading from the props directly above and it didn't work (not having an inline callback rendered every time). I also tried passing `this.props.onChangeText` directly to `onChangeText` instead of the destructuring like you're seeing above. I still had the warnings and shit performance like everyone else though. I tried in my SearchInput container capturing the current text value in a class instance variable instead of the `state` to prevent additional re-renders as our UI didn't call for any immediate reaction to what was being typed:

```javascript
class SearchInputContainer extends Component {

    constructor(props) {
        super(props);

        this.searchValue = '';
    }

    onSubmitEditing() {
        this._submit();
        this._startEditing();
    }
    _submit() {
        var { getSearchResults, searchResultsAreVisible } = this.props;
        var query = this.searchValue;

        if(!searchResultsAreVisible) {
            this._showSearchResults();
        }

        getSearchResults(query)
    }

    onChangeText(text) {
        this.searchValue = text;
    }

    render() {
        var { searchResultsAreVisible } = this.props,
            backgroundColor = searchResultsAreVisible ? 'rgba(0, 0, 0, .85)' : 'black';

        return (
            <SearchInput
                {...this.props}
                onBlur={this.onBlur.bind(this)}
                onFocus={this.onFocus.bind(this)}
                onSubmitEditing={this.onSubmitEditing.bind(this)}
                onChangeText={this.onChangeText.bind(this)}
                onClear={this.onClear.bind(this)}
                backgroundColor={backgroundColor}
            />
        )
    }
}
```
Note the `this.searchValue = '';` in the constructor. Also note the `onChangeText` method that I was using to update it and that I was then reading that value when I fired the `_submit` method. I was pretty surprised that this had performance issues because I'm not re-rendering the `state` every time they typed. _What was even odder though_, was that when I first loaded my view with the search input on it, it was immediately slow before I had even started typing.

So, I removed the `onChangeText` handler, and tied into the `onSubmitEnding` callback and passed in the current value:

```
render() {
        var { backgroundColor, isEditing, onFocus, onBlur, onSubmitEditing } = this.props;

        var onSubmit = () => {
            var value = this.refs.input._lastNativeText;

            onSubmitEditing(value);
        };

        // ... edited for brevity 

        return (
            <View style={containerStyles}>
                <View style={styles.inputContainer}>
                    <TextInput
                        ref="input"
                        style={styles.input}
                        returnKeyType={returnKeyType}
                        onFocus={onFocus}
                        onBlur={onBlur}
                        onSubmitEditing={onSubmit}
                    />
                    {inputIcon}
                    {label}
                    {clearButton}
                </View>
            </View>
        )
    }
```
Note the `onSubmit` method defined above. Also note the removed `onChangeText` handler.

and then updated my container accordingly:

```
class SearchInputContainer extends Component {

    onSubmitEditing(query) {
        this._submit(query);
        this._startEditing();
    }

    _submit(query) {
        var { getSearchResults, searchResultsAreVisible } = this.props;

        if(!searchResultsAreVisible) {
            this._showSearchResults();
        }

        getSearchResults(query)
    }

    render() {
        var { searchResultsAreVisible } = this.props,
            backgroundColor = searchResultsAreVisible ? 'rgba(0, 0, 0, .85)' : 'black';

        return (
            <SearchInput
                {...this.props}
                onBlur={this.onBlur.bind(this)}
                onFocus={this.onFocus.bind(this)}
                onSubmitEditing={this.onSubmitEditing.bind(this)}
                onClear={this.onClear.bind(this)}
                backgroundColor={backgroundColor}
            />
        )
    }
}
```

**Comment by crobinson42** [comment]
I only experience this issue when I have `remote debug` `live reload` `hot reload` all turned on... If I turn them off, I no longer experience the issue.

**Comment by crobinson42** [comment]
### Here's a repo to demonstrate the issue:

Bare bones ReactNative 0.33, redux, & react-redux example on a simple login form (only 1 component)

[react-native-issue-808](https://github.com/crobinson42/react-native-issue-808/tree/master)

**Comment by ajonno** [comment]
Im also seeing this issue, ONLY when **live reload** and **debug remotely** are both on. Im currently using RN version 0.37.0

**Comment by perrosnk** [comment]
+1

**Comment by avogel3** [comment]
+1

**Comment by sarovin** [comment]
#10559

**Comment by perrosnk** [comment]
I fixed the problem by doing:

1. Stop Remote JS Debugging and Disable Hot reloading
2. Close Chrome window where the debugging is running
3. Open a new Chrome window (not just new tab)
4. Start Remote JS Debugging and Enable Hot reloading

I don't know what causes the problem, but in my case it appears when my mac resumes from sleep, with the simulator running.

**Comment by Choicelin** [comment]
the last few comments seems to associate with the performance of our simulator or mobile,I think it is the reason too.

**Comment by pitops** [comment]
The problem is still there after all this time. Also what helped is close remote debugging

**Comment by JasonHenson** [comment]
I don't think trying to make your views faster, stopping debugging, etc. are real answers. I am working on an app that uses external barcode scanners and the scanner inputs text extremely fast, of which, I doubt any amount of optimization would help fix my issue. I even have this issue in release mode with barcode scanners. Why can it not just update in a delayed manner?

**Comment by MovingGifts** [comment]
@brentvatne I am still having this issue (so are many others in this thread) Is there a solution to this similar to what @JasonHenson suggested?

**Comment by brentvatne** [comment]
cc @sahrens who worked on this initially

**Comment by PaulAndreRada** [comment]
It's definitely the `live reload` and `remote debug` in my case. 
I tested it with the `performance monitor`  on a text input while typing as fast as my little piggies could handle, my RAM moved from:

`150MB` to roughly `162MP` when off. 
`150MB` to a whopping `193MB` when `live reload` and `remote debug` where on

@JasonHenson You might want to look into [debounce and throttle](https://css-tricks.com/debouncing-throttling-explained-examples/). It's saved me a few times before.

**Comment by kravchuck-den** [comment]
Hi all. I had the same problem, but I founded solution that works for me. The error is because we have a lot of setState in queue. So my solution is:

**Comment by minhphung210** [comment]
same issues

**Comment by jayasimhaprasad** [comment]
I still continue to face this issue.  I have a need to enable or disable a button based on if text input being empty or not. 
AS @kravchuck-den pointed out this issue does not occur if i remove the setState. What is good  way to handle view changes that are dependent on the text being empty or not ?

**Comment by jayasimhaprasad** [comment]
My requirement was to disable the button only when the text was empty.  I put an if condition to call setState only of this condition turned true and it solved my problem.

**Comment by juliancorrea** [comment]
+1
Same issues

**Comment by yuyao110120** [comment]
+1
Same issues. Debugging, Live Reload and Hot Reload Disabled.

**Comment by 12343954** [comment]
my solution is :  use `this.refs._txt_comment._lastNativeText`

<TextInput ref='_txt_comment'
    style={styles.input_comment}
    multiline={true} maxLength={100}
    placeholder='评论'
    placeholderTextColor='gray'
    keyboardAppearance='dark'
    // value={this.state._txt_comment}    **// DO NOT Binding value**   <----- X
    onEndEditing={() => {
        // console.log(this.refs._txt_comment) 
        this.setState({ _txt_comment: this.refs._txt_comment._lastNativeText });                                                            
    }}
    // onChangeText={()=>{}}    **// DO NOT USE 'onChangeText'**   <----- X
/>

you can use `this.refs._txt_comment._lastNativeText` anywhere .
such as `alert(this.refs._txt_comment._lastNativeText)` in a button click event .

because , calling `this.setState()` so many times , it will show the Warning `Native TextInput(xxx) is x events ahead of JS - try to make your JS faster.`

**Comment by Abby3017** [comment]
I was also having that issue. But when I tried that on device instead of simulator it worked fine. No lag as shown in simulator. If you use debounce on the onChange function the lags that are coming up will be resolved. Take a cue from this article [debounce example](https://medium.com/@devmrin/debouncing-touch-events-in-react-native-prevent-navigating-twice-or-more-times-when-button-is-90687e4a8113)
Try that and if someone have better idea, please let us know.

**Comment by wzup** [comment]
@crobinson42 
> I only experience this issue when I have remote debug live reload hot reload all turned on...

I have this issue even on real device! `debug live reload hot reload` doesn't matter here
