### ISSUE TITLE
[0.75][0.76] HAS FIX - React Native Android Build error - `zip END header not found` - INDIA Only

### ISSUE THREAD

**Issue by kush-scs** [facebook/react-native#49115]
## IMPORTANT

> [!IMPORTANT]  
> The latest official update on this issue [is available here](https://github.com/facebook/react-native/issues/49115#issuecomment-2640333409)

### Description

When i run my react native app in debug mode which is already running without errors using npx react-native run-android command then suddenly it gives gradle build running error like below screenshot and description from today in all pc.

**My Configurations**
react-native: 0.76.1
gradle-wrapper version: gradle-8.10.2

```
BUILD FAILED in 935ms
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build completed with 2 failures. 1: Task failed with an exception.
-----------
* Where:
Settings file '/Users/cspl01/...../android/settings.gradle' line: 2 * What went wrong:
Error resolving plugin [id: 'com.facebook.react']
> A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'. > java.util.zip.ZipException: zip END header not found * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
============================================================================== 2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@7edd8fd3 of type BuildFlowService.Parameters > A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'. > java.util.zip.ZipException: zip END header not found * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
============================================================================== BUILD FAILED in 935ms.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
```

please help me to solve this error!!

### Steps to reproduce

1. clone reproducer i have given or change configurations given by me in project
2. run yarn android(react-native run-android)
3. gradle plugin error occurs

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1
  CPU: (10) arm64 Apple M4
  Memory: 128.14 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: ~/Kush/ReactNative/projects/SeaNeB-Mobile-App-All/SeaNeB-Mobile/node_modules/.bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.11.11.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23726.103.2422.12816248
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Executing tasks: [:gradle-plugin:react-native-gradle-plugin:clean, :gradle-plugin:shared-testutil:clean, :gradle-plugin:settings-plugin:clean, :gradle-plugin:clean, :gradle-plugin:shared:clean, :gradle-plugin:react-native-gradle-plugin:assemble, :gradle-plugin:react-native-gradle-plugin:testClasses, :gradle-plugin:shared-testutil:assemble, :gradle-plugin:shared-testutil:testClasses, :gradle-plugin:settings-plugin:assemble, :gradle-plugin:settings-plugin:testClasses, :gradle-plugin:assemble, :gradle-plugin:testClasses, :gradle-plugin:shared:assemble, :gradle-plugin:shared:testClasses] in project /Users/cspl01/....../android


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Settings file '/Users/cspl01/..../android/settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'.
   > java.util.zip.ZipException: zip END header not found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@44ed0867 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'.
      > java.util.zip.ZipException: zip END header not found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 126ms
```

### Reproducer

https://github.com/kush-scs/reproducer-gradle-build

### Screenshots and Videos

![Image](https://github.com/user-attachments/assets/ae35b7a6-a0ce-4ff1-816c-e047c9e6af72)

**Comment by harshitparkar-ardent** [comment]
The solution to this error is UPGRADE react-native package to 0.77.0

**Comment by SanjayKumarCode** [comment]
**Given below Error **Automativallu****
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'.
java.io.UncheckedIOException: java.util.zip.ZipException: zip END header not found
java.util.zip.ZipException: zip END header not found
org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@3ecb2b09 of type BuildFlowService.Parameters
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'.
java.io.UncheckedIOException: java.util.zip.ZipException: zip END header not found
java.util.zip.ZipException: zip END header not found

**Comment by gautamsamyak** [comment]
Same issue

**Comment by kashyap-rathod-us** [comment]
Same issue

**Comment by gautamsamyak** [comment]
UPGRADE react-native package to 0.77.0 is working fine.

**Comment by PrathameshTI** [comment]
+1

**Comment by ItsAman0P** [comment]
+1

**Comment by rohitkushwaha831** [comment]
+1

**Comment by jdarshan5** [comment]
+1

**Comment by PrathameshTI** [comment]
> tive package to 0.77.0

this worked, also had to upgrade few libraries.

**Comment by ramanic** [comment]
+1 Project was working fine till Friday and it suddenly stopped working on Monday.
Tried Cleaning the whole Project 
tried changing gradle version , Nothing Worked

**Comment by HemangiVekaria** [comment]
I am facing same issue. It works well on friday and today when i run it throws error. I tried gradle delete from user, rebuild multiple times, deleted node modules multiple times, updated react-native version from 0.76.4 to 0.77.0 but still getting same error,

![Image](https://github.com/user-attachments/assets/57e083c9-cd2f-4a25-b290-7d805c3e0824)

**Comment by dpatilzensar** [comment]
Same here it was working till Friday, But it stoped working today react native version 0.75.4.

<img width="1243" alt="Image" src="https://github.com/user-attachments/assets/70b0ef93-0fad-4800-bed5-7a1ccef274bf" />

**Comment by riteshshukla04** [comment]
+1

If you urgently need to fix is to install @react-native/gradle-plugin to latest version and change the distribution URL accordingly . However this is highly not recommended .

**Comment by gautamsamyak** [comment]
@HemangiVekaria have you properly upgraded to 0.77 or just change version in package.json and install npm again?

**Comment by HemangiVekaria** [comment]
> roperly upgraded to 0.77 or just change version in package.json and install npm aga

I run `npm uninstall react-native` and then run `npm install react-native.`

**Comment by amithashtechy** [comment]
@gautamsamyak Yes bro i and all other developers world wide facing this issue on android side. All they and i also tried everting that we can think like  gradle delete from user, rebuild multiple times, deleted node modules multiple times, updated react-native version from 0.76.4 to 0.77.0 but still getting same error.
Version upgrade also downgrade and all other possibilities but the issue is not from our side it's a bug from it self the react native side we can't do anything they have to fix it any how because this same is is facing every one without changing any code of their project.

**Comment by gautamsamyak** [comment]
@HemangiVekaria very bed practice. You have to follow [https://react-native-community.github.io/upgrade-helper/?from=0.76.4&to=0.77.0](url) this.

You can also create a new project and transfer the src file to the new project.

**Comment by gautamsamyak** [comment]
@amithashtech I have already resolved this issue by creating a new project and transferring the old src to this.

**Comment by amithashtechy** [comment]
@gautamsamyak okay but i  created new react native project with this command npx @react-native-community/cli@latest init AwesomeProject and still getting same issue on the latest app.

**Comment by gautamsamyak** [comment]
@HemangiVekaria have you tried to create a new project and run on Android?

**Comment by HemangiVekaria** [comment]
> [@HemangiVekaria](https://github.com/HemangiVekaria) have you tried to create a new project and run on Android?

Yes i created using` npx @react-native-community/cli@latest init` this and it gives me same error. Now i am trying to create new project again.

**Comment by gautamsamyak** [comment]
@HemangiVekaria first clean gradle using : **rm -rf ~/.gradle/** then try new project.

**Comment by SanjayKumarCode** [comment]
but i am working on Same Project last 6 month so not prosible to update react native version, then how to possible to solve this error

**Comment by HemangiVekaria** [comment]
> [@HemangiVekaria](https://github.com/HemangiVekaria) first clean gradle using : **rm -rf ~/.gradle/** (Mac os) then try new project.

I am using window system.

**Comment by Manav541** [comment]
@gautamsamyak what about native changes? src folder we can easily move to other project but we cant move native changes.

**Comment by gautamsamyak** [comment]
@HemangiVekaria 
goto C:\Users\<YourUsername>\.gradle and remove all inside this folder.

**Comment by vishalsohani27** [comment]
when you do nothing still something can be happend with you.😜😜. Yesturday everyghing was fine.  From morning i am also facing same issue. i updated/downloadgrade react native, gradle, reinstall npm and other stuff but nothing is working.

**Comment by HemangiVekaria** [comment]
> [@HemangiVekaria](https://github.com/HemangiVekaria) goto C:\Users<YourUsername>.gradle and remove all inside this folder.

I did that also 2 times. No success :(

**Comment by brijeshbhikadiya** [comment]
Same i also do everything But still same issue

**Comment by Byloop** [comment]
Hey @gautamsamyak 
I tried to remove all inside this .gradle folder and created a new react native project but getting this error - 
 java.io.UncheckedIOException: Could not move temporary workspace (D:\project-name\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-d89d4ba8-30f2-4589-b2a4-d298e51bcf31) to immutable location (D:\project-name\android\.gradle\8.10.2\dependencies-
accessors\569c8b261a8a714d7731d5f568e0e5c05babae10

**Comment by RiteshTriveni** [comment]
> Hello everyone,
> 
> I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> 
> This is a temporary solution until React Native provides an official patch.
> 
> Thanks!

Yes, Working well, you save my day 🙂, buddy 👍

**Comment by HemangiVekaria** [comment]
> Hello everyone,
> 
> I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> 
> This is a temporary solution until React Native provides an official patch.
> 
> Thanks!

I added [@react-native/gradle-plugin] and now build get success. Thanks @Jignesh. But i am getting another error related to syntax. Does anyone have any idea about this error? I am using 
```
"aws-amplify": "6.10.2",
    "aws-appsync": "4.1.10",
    "aws-appsync-auth-link": "3.0.7",
"@aws-amplify/analytics": "^7.0.58",
    "@aws-amplify/react-native": "^1.1.6",
    "@aws-amplify/rtn-push-notification": "^1.2.31",
    "@aws-amplify/rtn-web-browser": "^1.1.1",
```

![Image](https://github.com/user-attachments/assets/84834de5-b28b-4691-b78b-37df2b3c04dd)

**Comment by TGS-DivyeshPatel** [comment]
> Hello everyone,
> 
> I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> 
> This is a temporary solution until React Native provides an official patch.
> 
> Thanks!


I had the same issue, and following this solution completely fixed it! After installing [@react-native/gradle-plugin](https://www.npmjs.com/package/@react-native/gradle-plugin) and rebuilding my project, everything worked perfectly.

A huge thank you for sharing this fix—you made my day! 🙌

**Comment by brijeshbhikadiya** [comment]
> > Hello everyone,
> > I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> > This is a temporary solution until React Native provides an official patch.
> > Thanks!
> 
> I had the same issue, and following this solution completely fixed it! After installing [@react-native/gradle-plugin](https://www.npmjs.com/package/@react-native/gradle-plugin) and rebuilding my project, everything worked perfectly.
> 
> A huge thank you for sharing this fix—you made my day! 🙌

Can you Please share your Gradle Version?

**Comment by Jignesh-Rana** [comment]
> > > Hello everyone,
> > > I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> > > This is a temporary solution until React Native provides an official patch.
> > > Thanks!
> > 
> > 
> > I had the same issue, and following this solution completely fixed it! After installing [@react-native/gradle-plugin](https://www.npmjs.com/package/@react-native/gradle-plugin) and rebuilding my project, everything worked perfectly.
> > A huge thank you for sharing this fix—you made my day! 🙌
> 
> Can you Please share your Gradle Version?

"react": "18.3.1"
"react-native": "0.75.4"
"@react-native/gradle-plugin": "^0.77.0"
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip

**Comment by Byloop** [comment]
Hello Everyone,
I have installed react-native-gradle-plugin in my existing project with react native 0.76.1
and distribution url - distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
but I am still getting this error -
 java.io.UncheckedIOException: Could not move temporary workspace (D:\project-name\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-2771be0d-6ab8-4e40-879b-d36843a12914) to immutable location (D:\project-name\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10)
 "react": "18.3.1",

**Comment by Byloop** [comment]
@Jignesh-Rana Can you please share version of react native and distribution url you are using?

**Comment by Mandipbh** [comment]
npm i @react-native/gradle-plugin@latest
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip

make sure to delete .gradle file first
and then old node modules

**Comment by riteshshukla04** [comment]
https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2

The issue is not related to react native but of kotlin version 1.9.24. Try changing the kotlin version in RNGP(using patch package) and your build.gradle to 1.9.25 . See the referred commit above .

**Comment by SanjayKumarCode** [comment]
**when install in existing project @react-native/gradle-plugin then comes given below error** 
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with 
an exception. * Where: Settings file 'D:\sparepartwale-mobileapp\android\settings.gradle' line: 2 * What went wrong: Error resolving plugin [id: 'com.facebook.react.settings'] > Could not read workspace metadata from C:\Users\Brijesh\.gradle\caches\8.8\kotlin-dsl\accessors\b22002a57a45d84a557a6d199ea7ef01\metadata.bin * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 38s.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

**Comment by vishalsohani27** [comment]
For me it's working 
library https://www.npmjs.com/package/@react-native/gradle-plugin
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
kotlinVersion = "1.9.24"
"react-native": "^0.75.4"

problem is related with gradle and kotlin only. so i dont think react native version will cause any issue.

**Comment by LonelyCpp** [comment]
> [riteshshukla04/React-native-zip-header-repro@de19abb](https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2)
> 
> The issue is not related to react native but of kotlin version 1.9.24. Try changing the kotlin version in RNGP(using patch package) and your build.gradle to 1.9.25 . See the referred commit above .

This worked, but still seems like a hack. What could be the root cause?

**Comment by kamlesh-tp** [comment]
> [riteshshukla04/React-native-zip-header-repro@de19abb](https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2)
> 
> The issue is not related to react native but of kotlin version 1.9.24. Try changing the kotlin version in RNGP(using patch package) and your build.gradle to 1.9.25 . See the referred commit above .

This worked. Also had to bump versions in expo-core-modules

**Comment by pkalani1999** [comment]
- Go to /Users/{USER_NAME}/.gradle, delete all folders and files in this folder and run again and uninstall old apk from device
- some times is not working

**Comment by Resource-4** [comment]
@kamlesh-tp can you please add more details what have you changed for expo-core-modules ?

**Comment by pooja-vipulbhai-darji** [comment]
Same Issue

**Comment by HemangiVekaria** [comment]
This morning, I cloned my project from Git, added [@react-native/gradle-plugin], and it worked without any issues. I am using this React Native version.

```
"react": "18.3.1",
"react-native": "0.76.3"
```

Yesterday, I tried upgrading the React Native version, adding the Gradle plugin, and changing the Kotlin version, but nothing worked. Today, only adding the Gradle plugin worked like a charm.

**Comment by OmkarK45** [comment]
Do we know the root cause? What suddenly changed in upstream? IMO this bug should be fixed in upstream and not by the consumers.

**Comment by riteshshukla04** [comment]
> Do we know the root cause? What suddenly changed in upstream? IMO this bug should be fixed in upstream and not by the consumers.

RN team will probably give a hotfix for this . PR for the fix has been raised

> This morning, I cloned my project from Git, added [@react-native/gradle-plugin], and it worked without any issues. I am using this React Native version.
> 
> ```
> "react": "18.3.1",
> "react-native": "0.76.3"
> ```
> 
> Yesterday, I tried upgrading the React Native version, adding the Gradle plugin, and changing the Kotlin version, but nothing worked. Today, only adding the Gradle plugin worked like a charm.

As mentioned above . Upgrading AGP is not the correct fix and should be avoided

**Comment by amithashtechy** [comment]
> > [riteshshukla04/React-native-zip-header-repro@de19abb](https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2)
> > The issue is not related to react native but of kotlin version 1.9.24. Try changing the kotlin version in RNGP(using patch package) and your build.gradle to 1.9.25 . See the referred commit above .
> 
> This worked. Also had to bump versions in expo-core-modules

It's working for me also thanks for saving our day. the react native shouldn't be more active to not getting this kind of errors or bugs in the future.

**Comment by jainrocks999** [comment]
same issue on  my app on react native 
 "react": "18.3.1",
    "react-native": "0.76.2",

**Comment by vishv-unjiya** [comment]
> > > > Hello everyone,
> > > > I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> > > > This is a temporary solution until React Native provides an official patch.
> > > > Thanks!
> > > 
> > > 
> > > I had the same issue, and following this solution completely fixed it! After installing [@react-native/gradle-plugin](https://www.npmjs.com/package/@react-native/gradle-plugin) and rebuilding my project, everything worked perfectly.
> > > A huge thank you for sharing this fix—you made my day! 🙌
> > 
> > 
> > Can you Please share your Gradle Version?
> 
> "react": "18.3.1" "react-native": "0.75.4" "@react-native/gradle-plugin": "^0.77.0" distributionUrl=https://services.gradle.org/distributions/gradle-8.9-all.zip

**Comment by vishv-unjiya** [comment]
**This solution worked for me:**

"react": "18.3.1"
"react-native": "0.76.6"
"@react-native/gradle-plugin": "^0.77.0"
distributionUrl=https://services.gradle.org/distributions/gradle-8.9-all.zip

After setting the versions, navigate to the android directory and run the following commands:
./gradlew clean
./gradlew assembleRelease

This should build the release successfully.

**Comment by ct-els-salvit1** [comment]
Working for me after updating react-native: 0.77.0. Thanks

**Comment by AnuragHarod** [comment]
I follow this steps to solve android gradle issue
- Install the library "@react-native/gradle-plugin"
- In gradle.properties file replace "**MaxPermSize**" with "**MaxMetaspaceSize**"
- In gradle-wrapper.properities file Upgrade to gradle zip 8.9
      distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip

**Comment by vishv-unjiya** [comment]
**This solution worked for me:**

“react”: “18.3.1"
“react-native”: “0.76.6"
“@react-native/gradle-plugin”: “^0.77.0"
distributionUrl=https://services.gradle.org/distributions/gradle-8.9-all.zip

After setting the versions, navigate to the android directory and run the following commands:
./gradlew clean
./gradlew assembleRelease

This should build the release successfully.

**Comment by Anikroychoudhury** [comment]
Install the library "@react-native/gradle-plugin"

**Comment by ramanic** [comment]
If anyone is still struggling , Here is an article to fix it without needing to upgrade the RN version :
[Fixed : React Native App Gradle Plugin Build error -(zip END header not found)](https://lraman.com.np/blogs/react-native-gradle-plugin-build-error/)

**Comment by heart2friend** [comment]
Worked for me after installing @react-native/gradle-plugin 0.77 and upgrading distributionUrl to gradle-8.9-all.zip in gradle-wrapper.properties. My project is targeting to React Native version 0.75.3

https://github.com/facebook/react-native/issues/46046

**Comment by shambhabyaM** [comment]
its still not working for me, i am using expo prebuild, any one facing same issue with expo prebuild?

**Comment by Deepakdkhamkar09** [comment]
same issue. 
please provide kotlinVersion
“react”:
“react-native”: 
“@react-native/gradle-plugin”: 
distributionUrl=https://services.gradle.org/distributions/

**Comment by vishv-unjiya** [comment]
> same issue. please provide kotlinVersion “react”: “react-native”: “@react-native/gradle-plugin”: distributionUrl=https://services.gradle.org/distributions/

“react”: “18.3.1"
“react-native”: “0.76.6"
“@react-native/gradle-plugin”: “^0.77.0"
kotlinVersion = "1.9.25"
distributionUrl=https://services.gradle.org/distributions/gradle-8.9-all.zip

**Comment by kinjalgajera22** [comment]
Solve my problem and  project run successfully just now

follow below steps

1. Delete package-lock.json
2. Delete node_modules
3. In package.json add or update version of dependencie -   "@react-native/gradle-plugin": "^0.77",
4. In gradle-wrapper.properties files set distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
5. npm i
6. cd android
7. ./gradlew clean
8. react-native run-android

kotlinVersion is "1.9.25"

**Comment by shivam0107** [comment]
after installing “@react-native/gradle-plugin”: “^0.77.0" getting this error 

* What went wrong:
Included build /Users/----/node_modules/react-native/node_modules/@react-native/gradle-plugin has build path :gradle-plugin which is the same as included build /Users/----/node_modules/@react-native/gradle-plugin

**Comment by Deepakdkhamkar09** [comment]
getting something like this

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> Could not resolve all artifacts for configuration 'classpath'.
   > Failed to transform foojay-resolver-0.5.0.jar (org.gradle.toolchains:foojay-resolver:0.5.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.internal.instrumented=instrumented-and-upgraded, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for MergeInstrumentationAnalysisTransform: C:\Users\a2z\.gradle\caches\8.9\transforms\68f5b8f52a3d432cb1b14ab0b759f4ec\transformed\analysis\instrumentation-dependencies.bin.
         > com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Could not deserialize analysis from a file: C:\Users\a2z\.gradle\caches\8.9\transforms\68f5b8f52a3d432cb1b14ab0b759f4ec\transformed\analysis\instrumentation-hierarchy.bin

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
Error:  \android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86,armeabi-v7a exited with 
non-zero code: 1

**Comment by Sohail-suflon** [comment]
> getting something like this
> 
> * What went wrong:
>   Error resolving plugin [id: 'com.facebook.react.settings']
> 
> > Could not resolve all artifacts for configuration 'classpath'.
> > Failed to transform foojay-resolver-0.5.0.jar (org.gradle.toolchains:foojay-resolver:0.5.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.internal.instrumented=instrumented-and-upgraded, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
> > > Execution failed for MergeInstrumentationAnalysisTransform: C:\Users\a2z.gradle\caches\8.9\transforms\68f5b8f52a3d432cb1b14ab0b759f4ec\transformed\analysis\instrumentation-dependencies.bin.
> > > com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Could not deserialize analysis from a file: C:\Users\a2z.gradle\caches\8.9\transforms\68f5b8f52a3d432cb1b14ab0b759f4ec\transformed\analysis\instrumentation-hierarchy.bin
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 2s Error: \android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=x86,armeabi-v7a exited with non-zero code: 1

try to change java version probability to solve it this issue

**Comment by shivam0107** [comment]
@divyangDevX i have 
react-native - 0.74.5
In gradle-wrapper.properties files set distributionUrl=https://services.gradle.org/distributions/gradle-8.9-all.zip
android kotlin version - 1.9.24

still it not worked
What went wrong:
Included build /Users/----/node_modules/react-native/node_modules/@react-native/gradle-plugin has build path :gradle-plugin which is the same as included build /Users/----/node_modules/@react-native/gradle-plugin

**Comment by BogdanRad** [comment]
Hello, I get this error when trying to run on an M4 Mac after updating React Native to 0.76.6. I have Xcode 16.2. The app runs on an Intel processor... Has anyone else this issue?

<img width="896" alt="Image" src="https://github.com/user-attachments/assets/0914e5d3-0454-4a39-b78a-fec6be92576c" />

**Comment by DarshanMRI** [comment]
I am facing the same issue when I install @react-native/gradle-plugin in my Expo project. At that time, I get the following error:
Included build /Users/----/node_modules/react-native/node_modules/@react-native/gradle-plugin has build path :gradle-plugin which is the same as included build /Users/----/node_modules/@react-native/gradle-plugin

**Comment by Sohail-suflon** [comment]
I am try to solve this from yesterday but today i have this issue 

First delete the node module and install npm i then upgrade the react native version, latest version is showing thats okh. but notshowing latest version then add it manually latest version and install npm then this issue will be solve.

also update the ndk version and kotlin version

   ndkVersion = "21.4.7075529"
        kotlinVersion = "1.9.24"

this solution work it proper for me..

**Comment by ronakYudiz** [comment]
> [riteshshukla04/React-native-zip-header-repro@de19abb](https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2)
> 
> The issue is not related to react native but of kotlin version 1.9.24. Try changing the kotlin version in RNGP(using patch package) and your build.gradle to 1.9.25 . See the referred commit above .

My React Native version is 0.76.6

I am able to solve this by following this man reply

Step 1: change Kotlin version from 1.9.24 -> 1.9.25
Step 2: change Same Kotlin version at this path node_modules/@react-native/gradle-plugin/gradle/libs.versions.toml
and bingo.


Thanks Ritesh

**Comment by Serv-Alok** [comment]
I have done this 

My React Native version is 0.76.6

Step 1: change Kotlin version from 1.9.24 -> 1.9.25
Step 2: change Same Kotlin version at this path node_modules/@react-native/gradle-plugin/gradle/libs.versions.toml
and bingo.

but still, my error persists

Error resolving plugin [id: 'com.facebook.react.settings']

can anyone pls help me out

**Comment by Devilzer** [comment]
Facing same issue
react-native - 0.75.4

**Comment by cortinico** [comment]
Hey all,
Nicola from the React Native team here.

We got several reports that several Android builds are failing with `zip END header not found`. The issue seems to be related to a blocked resource from the Indian Ministry of Electronics and Information Technology ([source](https://github.com/facebook/react-native/pull/49135#issuecomment-2634254709)).

This is causing builds depending on Kotlin 1.9.24 to fail.

The affected React Native versions are **0.75.x** and **0.76.x**

The current workarounds are **either**:
1. Update your projects to React Native 0.77 as it's using Kotlin 2.x so it's not affected.
2. Use `patch-package` to update the Kotlin version here `node_modules/@react-native/gradle-plugin/gradle/libs.versions.toml` as following:

```diff
[versions]
agp = "8.5.0"
gson = "2.8.9"
guava = "31.0.1-jre"
javapoet = "1.13.0"
junit = "4.13.2"
-kotlin = "1.9.24"
+kotlin = "1.9.25"
assertj = "3.25.1"
```

We're working on releasing patch version of React Native 0.76 and 0.75 that contains this change already so you won't have to use patch-package.

**Comment by Resource-4** [comment]
After changing kotlin = "1.9.25" i got following error:

> Task :expo-modules-core:compileDebugKotlin FAILED
e: This version (1.5.14) of the Compose Compiler requires Kotlin version 1.9.24 but you appear to be using Kotlin version 1.9.25 which is not known to be compatible.  Please consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin to choose a compatible version pair (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

This version (1.5.14) of the Compose Compiler requires Kotlin version 1.9.24 but you appear to be using Kotlin version 1.9.25 which is not known to be compatible.  Please consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin to choose a compatible version pair (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).


react native - 0.76.3
expo - ^52.0.11

**Comment by hitu-kaka** [comment]
@cortinico 
Facing same issue started after mac os update, Project is working fine yesterday night and after update stoped working, tried every possible solve, same project working fine on another laptop 

My project have some config as reported by @kush-scs  

sharing info of working system 

`info Fetching system and libraries information...
(node:4707) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
 OS: macOS 14.5
 CPU: (11) arm64 Apple M3 Pro
 Memory: 94.66 MB / 18.00 GB
 Shell:
  version: "5.9"
  path: /bin/zsh
Binaries:
 Node:
  version: 23.6.1
  path: ~/.nvm/versions/node/v23.6.1/bin/node
 Yarn:
  version: 1.22.22
  path: /opt/homebrew/bin/yarn
 npm:
  version: 10.9.2
  path: ~/.nvm/versions/node/v23.6.1/bin/npm
 Watchman:
  version: 2024.08.19.00
  path: /opt/homebrew/bin/watchman
Managers:
 CocoaPods:
  version: 1.15.2
  path: /opt/homebrew/bin/pod
SDKs:
 iOS SDK: Not Found
 Android SDK: Not Found
IDEs:
 Android Studio: 2024.1 AI-241.18034.62.2411.12169540
 Xcode:
  version: /undefined
  path: /usr/bin/xcodebuild
Languages:
 Java:
  version: 17.0.12
  path: /usr/bin/javac
 Ruby:
  version: 2.6.10
  path: /usr/bin/ruby
npmPackages:
 "@react-native-community/cli":
  installed: 15.0.1
  wanted: 15.0.1
 react:
  installed: 18.3.1
  wanted: 18.3.1
 react-native:
  installed: 0.76.3
  wanted: 0.76.3
 react-native-macos: Not Found
npmGlobalPackages:
 "*react-native*": Not Found
Android:
 hermesEnabled: true
 newArchEnabled: true
iOS:
 hermesEnabled: Not found
 newArchEnabled: false

info React Native v0.77.0 is now available (your project is running on v0.76.3).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.77.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.76.3&to=0.77.0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".`

**Comment by riteshshukla04** [comment]
> After changing kotlin = "1.9.25" i got following error:
> 
> > Task :expo-modules-core:compileDebugKotlin FAILED
> > e: This version (1.5.14) of the Compose Compiler requires Kotlin version 1.9.24 but you appear to be using Kotlin version 1.9.25 which is not known to be compatible.  Please consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin to choose a compatible version pair (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
> 
> This version (1.5.14) of the Compose Compiler requires Kotlin version 1.9.24 but you appear to be using Kotlin version 1.9.25 which is not known to be compatible. Please consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin to choose a compatible version pair (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
> 
> react native - 0.76.3 expo - ^52.0.11

Try updating the kotlin version in `android/build.gradle` . I think expo picks up the version from there. If this doesn't work you have to patch expo too

**Comment by codewithdevansh** [comment]
use vpn and run command ./gradlew clean in android 
then run the app
it worked for me

**Comment by Rahulthenoobcoder** [comment]
Install 
npm i @react-native/gradle-plugin

and then change the gradle version to 8.9 in gradle wrapper.properties

It will work

**Comment by bs-farhan-shaikh** [comment]
This works 👍
`npm i @react-native/gradle-plugin`

**Comment by Resource-4** [comment]
@riteshshukla04 can you please give more details ? It would be really helpful

**Comment by vishalSS131990** [comment]
I follow this steps to solve android gradle issue

Install the library "@react-native/gradle-plugin"
In gradle.properties file replace "MaxPermSize" with "MaxMetaspaceSize"
In gradle-wrapper.properities file Upgrade to gradle zip 8.9 distributionUrl=[services.gradle.org/distributions/...](https://services.gradle.org/distributions/gradle-8.9-all.zip)
After completing above steps, just do the gradle clean and re run the app.

**Comment by pairohit305** [comment]
@cortinico when is the new patch coming ?

**Comment by Deepakdkhamkar09** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Included build     project_path \node_modules\react-native\node_modules\@react-native\gradle-plugin has build path :gradle-plugin which is the same as included build project_path\node_modules\@react-native\gradle-plugin

after adding this @react-native/gradle-plugin

**Comment by riteshshukla04** [comment]
> [@riteshshukla04](https://github.com/riteshshukla04) can you please give more details ? It would be really helpful

https://github.com/expo/expo/pull/34674/files 

Pls refer to the above pull request. Just do the changes as done above in your node_modules .

**Comment by LonelyCpp** [comment]
an alternate solution that doesn't rely on patching the modules (since this only affects users in India) :

1. remove your local cache for kotlin 1.9.24
2. connect to a VPN outside that connects to a server outside India
3. rebuild android

local cache on macos is usually in `~/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin.jvm/org.jetbrains.kotlin.jvm.gradle.plugin/1.9.24/**` (I deleted this whole folder)

**Comment by McMohanCycle** [comment]
@kush-scs I was facing the same issue. Try the following steps:
1. Connect to a US VPN.
2. Delete `.gradle` from your home dir.
3. Delete `.gradle` from `project/android` dir.
4. Delete node modules
5. Yarn/NPM
6. ./gradlew clean
7. Build app

This worked for me.

**Comment by cortinico** [comment]
**IMPORTANT**: Installing a different version of `@react-native/gradle-plugin` is **NOT** the right fix. Your project will break once you update React Native version.

**Comment by Parthshiroya06** [comment]
Hello, this issue resolve with this stackOverflow solution.
go to cd android directory then enter  `./gradlew --stop` command 

if ./gradlew clean not work
if yarn android/ npm run android command not work.

https://stackoverflow.com/questions/79195694/build-failed-error-resolving-plugin-id-com-facebook-react-settings-in-reac

**Comment by sandeepsuthar** [comment]
0.76.7 version released just now, hope this will fix your issues.

**Comment by hitu-kaka** [comment]
@McMohanCycle I have tried NordVpn and VPN Unlimited paid versions, but not able to download, getting timeout or invalid host
can you please share the name of vpn that is working. thanks

and please consider this comment https://github.com/facebook/react-native/issues/49115#issuecomment-2635709332

**Comment by sandeepsuthar** [comment]
@hitu-kaka  Current RN version?

**Comment by hitu-kaka** [comment]
@sandeepsuthar  - 0.76.3, just now I have upgraded to 0.76-stable and it solved my problem ,but my question is why it's still working on my second laptop

**Comment by sandeepsuthar** [comment]
@hitu-kaka  Try to clean build and gradle, will face same issue.

**Comment by SumitR9910** [comment]
getting this error after upgrading to 0.76.7

`[RUN_GRADLEW] > Task :expo-modules-core:compileDebugKotlin FAILED
[RUN_GRADLEW] e: This version (1.5.14) of the Compose Compiler requires Kotlin version 1.9.24 but you appear to be using Kotlin version 1.9.25 which is not known to be compatible.  Please consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin to choose a compatible version pair (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
[RUN_GRADLEW] > Task :app:processDebugResources
[RUN_GRADLEW] > Task :expo-dev-launcher:dataBindingMergeDependencyArtifactsDebug
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
[RUN_GRADLEW] 336 actionable tasks: 336 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-modules-core:compileDebugKotlin'.
[RUN_GRADLEW] > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
[RUN_GRADLEW]    > Compilation error. See log for more details
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 12s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

**Comment by sandeepsuthar** [comment]
@SumitR9910 Upgrade kotlinVersion to 1.9.25 in android/build.gradle

**Comment by SumitR9910** [comment]
> [@SumitR9910](https://github.com/SumitR9910) Upgrade kotlinVersion to 1.9.25 in android/build.gradle

does not seem to work unfortunately, I also tried explicitly setting the kotlinVersion to 1.9.25 in the expo-build-properties config plugin but still get the same error.

**Comment by McMohanCycle** [comment]
> [@McMohanCycle](https://github.com/McMohanCycle) I have tried NordVpn and VPN Unlimited paid versions, but not able to download, getting timeout or invalid host can you please share the name of vpn that is working. thanks
> 
> and please consider this comment [#49115 (comment)](https://github.com/facebook/react-native/issues/49115#issuecomment-2635709332)

@hitu-kaka I used a "private" VPN pointing to a US server. But seems like your issue is already resolved so...

**Comment by zyauddinkhanin** [comment]
1. Delete .gradle from your home dir.
2. Delete .gradle from project/android dir.
3. run yarn android or npm run android

it's worked for me, thanks

**Comment by yashghantala** [comment]
Can avoid all patch etc, just download official JAR from https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin/1.9.24 and replace existing corrupted JAR(don't change the name of this file) with newly downloaded one.

Doing this makes sense as you don't have to patch expo, react-native, RN reanimated etc packages.

**Comment by kapilw360** [comment]
> Hello, this issue resolve with this stackOverflow solution. go to cd android directory then enter `./gradlew --stop` command
> 
> if ./gradlew clean not work if yarn android/ npm run android command not work.
> 
> https://stackoverflow.com/questions/79195694/build-failed-error-resolving-plugin-id-com-facebook-react-settings-in-reac

Thank you so much. it works for me.

**Comment by kapilw360** [comment]
> > [@SumitR9910](https://github.com/SumitR9910) Upgrade kotlinVersion to 1.9.25 in android/build.gradle
> 
> does not seem to work unfortunately, I also tried explicitly setting the kotlinVersion to 1.9.25 in the expo-build-properties config plugin but still get the same error.

Try with below approch
go to cd android directory then enter ./gradlew --stop command
then ./gradlew clean

**Comment by SumitR9910** [comment]
> > > [@SumitR9910](https://github.com/SumitR9910) Upgrade kotlinVersion to 1.9.25 in android/build.gradle
> > 
> > 
> > does not seem to work unfortunately, I also tried explicitly setting the kotlinVersion to 1.9.25 in the expo-build-properties config plugin but still get the same error.
> 
> Try with below approch go to cd android directory then enter ./gradlew --stop command then ./gradlew clean

still getting the same error, what react-native version are you on?

**Comment by SumitR9910** [comment]
> After upgrading to react native version 0.77.0
> 
> I am getting below error:
> 
> Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > Compilation error. See log for more details

try updating the `react-native-vision-camera` package to the latest version, the version you have installed probably does not. have support for `react-native-0.77`

**Comment by abdulmaajid-dev** [comment]
> After upgrading to react native version 0.77.0
> 
> I am getting below error:
> 
> Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > Compilation error. See log for more details

@TamilVannan navigate to this path node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt 

you can check this url as reference
https://github.com/mrousavy/react-native-vision-camera/pull/3382/files

  change this line - override fun getLifecycle(): Lifecycle = lifecycleRegistry
  to this - override val lifecycle: Lifecycle
    get() = lifecycleRegistry

**Comment by vishaldadarwal** [comment]
Error : 
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Settings file '/Users/apple/Desktop/my-work/zero/android/settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'.
   > **java.util.zip.ZipException: zip END header not found**


**Chipset**: M1
**React Native CLI**: 0.76.5 

--------------------- Solutions----------------------------- 

rm -rf ~/.gradle/caches
rm -rf ~/.gradle/wrapper
rm -rf android/.gradle
rm -rf android/app/build
rm -rf android/build


=> android/build.gradle

repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        // classpath("com.android.tools.build:gradle")
        classpath("com.android.tools.build:gradle:8.2.2")  
        classpath("com.facebook.react:react-native-gradle-plugin")
        // classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21")
    }

=> file : gradle-wrapper.properties

distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip

I am facing the same issue and this solution works for me. 🙂

**Comment by kapilw360** [comment]
> Error : FAILURE: Build completed with 2 failures.
> 
> ## 1: Task failed with an exception.
> * Where:
>   Settings file '/Users/apple/Desktop/my-work/zero/android/settings.gradle' line: 2
> * What went wrong:
>   Error resolving plugin [id: 'com.facebook.react.settings']
> 
> > A problem occurred configuring project ':gradle-plugin:react-native-gradle-plugin'.
> > **java.util.zip.ZipException: zip END header not found**
> 
> **Chipset**: M1 **React Native CLI**: 0.76.5
> 
> --------------------- Solutions-----------------------------
> 
> rm -rf ~/.gradle/caches rm -rf ~/.gradle/wrapper rm -rf android/.gradle rm -rf android/app/build rm -rf android/build
> 
> => android/build.gradle
> 
> repositories { google() mavenCentral() gradlePluginPortal() } dependencies { // classpath("com.android.tools.build:gradle") classpath("com.android.tools.build:gradle:8.2.2") classpath("com.facebook.react:react-native-gradle-plugin") // classpath("org.jetbrains.kotlin:kotlin-gradle-plugin") classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21") }
> 
> => file : gradle-wrapper.properties
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-8.10.2-all.zip
> 
> I am facing the same issue and this solution works for me. 🙂

Thanxx

**Comment by kapilw360** [comment]
> > > > [@SumitR9910](https://github.com/SumitR9910) Upgrade kotlinVersion to 1.9.25 in android/build.gradle
> > > 
> > > 
> > > does not seem to work unfortunately, I also tried explicitly setting the kotlinVersion to 1.9.25 in the expo-build-properties config plugin but still get the same error.
> > 
> > 
> > Try with below approch go to cd android directory then enter ./gradlew --stop command then ./gradlew clean
> 
> still getting the same error, what react-native version are you on?

RN: 0.76.3

actually i took new pull and did above steps then it worked for me . or else you can try another approach one guy mentioned at the last.

**Comment by krokhale** [comment]
Gradle clean, remove ~/.gradle, expo prebuild clean and use a VPN.

**Comment by kapilw360** [comment]
> Gradle clean, remove ~/.gradle, expo prebuild clean and use a VPN.

not using expo

**Comment by abdulmaajid-dev** [comment]
Hi, Kindly try following these steps it works for me

#### **1. Update Android Studio and Dependencies**
- **Update Android Studio**: 
  - Go to *Help > Check for Updates* → Install **2024.2.2 (Ladybird Feature Drop)** or newer.
  - Ensure the **Android Gradle Plugin (AGP)** is **8.6.0**+ (File > Project Structure > Project Settings).

---

#### **2. Modify `android/build.gradle`** 📝
  ```gradle
  buildscript {
      ext {
          buildToolsVersion = "35.0.0"
          minSdkVersion = 24
          compileSdkVersion = 35
          targetSdkVersion = 34
          ndkVersion = "26.1.10909125"
          // ▼ Update Kotlin to 1.9.25 ▼
          kotlinVersion = "1.9.25"
      }
      repositories {
          google()
          mavenCentral()
      }
      dependencies {
          classpath("com.android.tools.build:gradle:8.6.0") // Explicit version
          classpath("com.facebook.react:react-native-gradle-plugin")
          // ▼ Ensure Kotlin plugin matches the version ▼
          classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
      }
  }
  apply plugin: "com.facebook.react.rootproject"
  ```

---

#### **3. Clean Project Cache & Dependencies** 🧹
  ```bash
  # Global gradle cache
  rm -rf ~/.gradle/caches

  # Project-specific files
  rm -rf android/.gradle android/app/build android/build node_modules

  # Reinstall dependencies
  npm install (or yarn)
  ```

  **⚠️ For Windows:**  
  Use `rd /s /q` instead of `rm -rf`, or use Android Studio’s *File > Invalidate Caches*.

---

#### **4. Gradle Sync in Android Studio** 🔄
  - Open `project/android/` as a project in Android Studio.
  - Wait for **Gradle sync** to finish (check for errors in the "Build" tab).
  - Ensure sync uses **Gradle 8.10.2** (*gradle-wrapper.properties*):
    ```properties
    distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
    ```

---

#### **5. Build and Run** ▶️
  - Terminal:
    ```bash
    npx react-native run-android
    # or
    yarn android
    ```
  - If sync/network issues persist:
    - **Use a VPN (Europe/North America)**: Helps bypass regional Maven repository blocks.

---

#### **Critical Checks** 🔍
  1. **JDK 17 Compatibility**: Set JDK 17 in Android Studio (*File > Project Structure > SDK Location*).
  2. **Check `settings.gradle`**: Ensure no duplicate plugin declarations.
  3. **Disable `org.gradle.caching`** temporarily in `gradle.properties` if builds stall.

---

### **Why This Works** 💡
- Updates AGP and Kotlin to versions with critical bug fixes.
- Cleares corrupted/incompatible cached Gradle files.
- Explicit dependency versions prevent version resolution conflicts.

Still stuck? Share the **exact error log** for targeted troubleshooting! 🚨

**Comment by rahulaauji-30** [comment]
I tried every single solution mentioned in this but it didnt worked for me getting same error again and again.

**Comment by cortinico** [comment]
> [!IMPORTANT]  
> This is an official update from the React Native team

Hey all,
Nicola from the React Native team here, with the latest update.

1. As a reminder: If you're on React Native 0.77, you won't be affected.
1. We just released React Native 0.76.7 which mitigates this issue: https://github.com/facebook/react-native/releases/tag/v0.76.7
  1. If you're on a previous version of 0.76.x, please update to 0.76.7 
1. We're about to release 0.75.5 which will mitigate this issue as well as 0.75.

If you're on Expo, you will need a patch release of Expo SDK. 
Please refer to this issue: 
- https://github.com/expo/expo/issues/34613

Do not comment here if you're using Expo, you're just creating unnecessary noise.

Please comment further **only** if:
- You're not using Expo **AND**
- You're either on React Native 0.77, 0.76.7, 0.75.5 **AND**
- You're getting build failure with `zip END header not found`

Thank you very much for your patience and cooperation

**Comment by avinashkumar0808** [comment]
Can anyone explain me what is the cause of this error..
I don't need solution I have already solved it but kindly tell me what is the cause of this error?

**Comment by rahulaauji-30** [comment]
@avinashkumar0808 
Can you share the solution

**Comment by shubham-crypto** [comment]
try running with cmd as an administrator (important and run simply metro in another cmd and npm run android in one cmd)
Note: before running these commands navigate to your project folder
this works for me

**Comment by brentvatne** [comment]
💡 👁 👁 ➡  **If you are using Expo SDK 52 / React Native 0.76 and based out of India, please ensure that you are using the latest version of SDK 52 by running `npx expo install --fix`. This is resolved in `expo@52.0.31` and `react-native@0.76.7`**

**Comment by getsettalk** [comment]
same issue, how to fix it without upgrading it

**Comment by webmigratesmj** [comment]
> when you do nothing still something can be happend with you.😜😜. Yesturday everyghing was fine. From morning i am also facing same issue. i updated/downloadgrade react native, gradle, reinstall npm and other stuff but nothing is working.

Welcome to the React Native 😜

**Comment by getsettalk** [comment]
😃😃😂

**Comment by mehuljetani** [comment]
1. Clean Gradle Caches:

rm -rf ~/.gradle/caches
rm -rf ~/.gradle/wrapper
rm -rf android/.gradle
rm -rf android/app/build
rm -rf android/build

2. Update Kotlin Version in build.gradle:

ext {
    kotlinVersion = "1.9.25"
}

3. Update Gradle Version in gradle-wrapper.properties:

distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip


4. Apply GitHub Commit Fix: Apply changes from https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2

5. comment Classpaths in build.gradle:

//classpath("com.android.tools.build:gradle")
//classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")

npx react-native run-android

This Worked for me.

**Comment by avinashkumar0808** [comment]
Not It is working in my previous environment.. I didn’t updated react native it just started working...

**Comment by webmigratesmj** [comment]
> 1. Clean Gradle Caches:
> 
> rm -rf ~/.gradle/caches rm -rf ~/.gradle/wrapper rm -rf android/.gradle rm -rf android/app/build rm -rf android/build
> 
> 2. Update Kotlin Version in build.gradle:
> 
> ext { kotlinVersion = "1.9.25" }
> 
> 3. Update Gradle Version in gradle-wrapper.properties:
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-8.9-all.zip
> 
> 4. Apply GitHub Commit Fix: Apply changes from [riteshshukla04/React-native-zip-header-repro@de19abb](https://github.com/riteshshukla04/React-native-zip-header-repro/commit/de19abbfa08e8f802f9f07d2db223315460423f2)
> 5. comment Classpaths in build.gradle:
> 
> //classpath("com.android.tools.build:gradle") //classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
> 
> npx react-native run-android
> 
> This Worked for me.

Thanks @mehuljetani its worked for me!

**Comment by adityadesai192k** [comment]
> Hello everyone,
> 
> I encountered a similar issue and managed to resolve it by using the [@react-native/gradle-plugin] https://www.npmjs.com/package/@react-native/gradle-plugin library. Simply install the library and try rebuilding your project.
> 
> This is a temporary solution until React Native provides an official patch.
> 
> Thanks!

Thanks  this is working🙏

**Comment by badalsaibo** [comment]
> Hey all, Nicola from the React Native team here.
> 
> We got several reports that several Android builds are failing with `zip END header not found`. The issue seems to be related to a blocked resource from the Indian Ministry of Electronics and Information Technology ([source](https://github.com/facebook/react-native/pull/49135#issuecomment-2634254709)).
> 
> This is causing builds depending on Kotlin 1.9.24 to fail.
> 
> The affected React Native versions are **0.75.x** and **0.76.x**
> 
> The current workarounds are **either**:
> 
> 1. **Update your projects to React Native 0.77** as it's using Kotlin 2.x so it's not affected.
> 2. Use `patch-package` to update the Kotlin version here `node_modules/@react-native/gradle-plugin/gradle/libs.versions.toml` as following:
> 
> [versions]
> agp = "8.5.0"
> gson = "2.8.9"
> guava = "31.0.1-jre"
> javapoet = "1.13.0"
> junit = "4.13.2"
> -kotlin = "1.9.24"
> +kotlin = "1.9.25"
> assertj = "3.25.1"
> We're working on releasing patch version of React Native 0.76 and 0.75 that contains this change already so you won't have to use patch-package.

Please follow this official fix guys!!

**Comment by cortinico** [comment]
We're closing this as React Native 0.75.5 has also been released so all the supported versions out there are patched: https://www.npmjs.com/package/react-native/v/0.75.5

Expo also released a patched version of their SDK.

If you still have this kind of issue (`zip END header not found`), please open a new bug report.
