### ISSUE TITLE
[Android] Images with 301 redirect don't load

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#4940]
Loading images from server where it does a redirect doesn't seem to work on Android. It works fine on iOS.

Demo - https://rnplay.org/apps/UEdIbw

Currently I'm working around this by having a native module which resolves the final URL and sends it back to JavaScript. Its terrible, but at least it gets the job done.

**Comment by satya164** [comment]
https://productpains.com/post/react-native/bug-android-images-with-301-redirect-dont-load/

**Comment by mkonicek** [comment]
@tyronen Does Fresco support redirects off the box?

I searched the codebase for '301', 'redirect', 'moved', 'permanently':
https://github.com/facebook/fresco/search?utf8=%E2%9C%93&q=301

**Comment by mkonicek** [comment]
Upvoted: https://productpains.com/post/react-native/images-with-301-redirect-dont-load/

**Comment by satya164** [comment]
@mkonicek No idea. I had searched, but didn't find anything on this. Also on a quick look, the Native module just seems to pass the URL to Fresco. Thanks for the upvote and the correct link. I had no idea that changing the title changes the link on ProductPains.

**Comment by mkonicek** [comment]
Pinged Tyrone.

**Comment by satya164** [comment]
@mkonicek Thank you ❤️

**Comment by tyronen** [comment]
In ReactNative apps, Fresco delegates the network request to OkHttp. By default, OkHttp [does follow 301 redirects](https://github.com/square/okhttp/blob/parent-2.5.0/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java#L1077). 

We'd need to debug through OkHttp source to find out why this doesn't seem to be happening.

**Comment by satya164** [comment]
@tyronen Lemme know if I can do anything to help.

**Comment by satya164** [comment]
@mkonicek @tyronen Has there been any movement on this?

**Comment by just4fun** [comment]
@satya164 I encountered same issue here #5616 , but you mentioned that it works fine on iOS. My APP is built with RN but only for iOS, the pics with 301 will only display **sometimes**, it's very weird.

**Comment by npomfret** [comment]
I have exactly the opposite problem. Android seemed to be ok, but IOS would only load the image once and subsequent attempts at displaying the image wouldn't work.  Looking at the web server logs it doesn't even make a request.

Using RN 0.23

**Comment by lacker** [comment]
This looks like it was fixed in https://github.com/facebook/react-native/releases/tag/v0.26.0 . I'm going to close the issue but feel free to reopen if I am wrong about that.

**Comment by just4fun** [comment]
@lacker I think what has been fixed in 0.26.0 is just for iOS version, please refer this commit [192ab6](https://github.com/facebook/react-native/commit/192ab663b76dd8e640915c0670830c2de557804f).

**Comment by kimwue** [comment]
We can confirm that this issue is still present in version 0.39 and Android, seems to be only fixed for iOS. Please reopen if possible.

Thanks!

**Comment by luco** [comment]
Still happening on Android, can confirm on `0.40`

**Comment by danieldkim** [comment]
Also happening for me with 0.40.0.  I've tested on 2 nougat devices (a Google pixel phone and a Nexus 6P emulator) and on an older Samsung phone running Android 6.0.1.  The issue occurs on both nougat devices but not on the Marshmallow device.

**Comment by jenstah** [comment]
I see this is happening on iOS as @npomfret reported on April 20.  

In Facebook search "Danielles Guide to 504 Plans" which leads you to a card from Spokin Inc.  Tapping on that card the first time successfully takes user to the URL http://www.spokin.com/504plans.  But hitting back button and tapping on that card going forward goes to a 404.

**Comment by dotneet** [comment]
I have encountered same issue with RN v0.4.51 iOS. 
I tried to display facebook profile image with the url like this: http://graph.facebook.com/<user_id>/picture?type=large
but not works.
So, I changed the url to redirect target of the url(CDN's url). It works.

**Comment by dotneet** [comment]
I'm sorry, I resolved it and it's not related to this issue.
My issue is caused by App Transport Security. I changed a url to 'https' and it works.

**Comment by Noitidart** [comment]
I am using Android - react native 0.48.1 and image with redirect is not loading. So this was only fixed for iOS here correct? - https://github.com/facebook/react-native/commit/192ab663b76dd8e640915c0670830c2de557804f

**Comment by Silvercast** [comment]
same here. Images shown randomly
