### ISSUE TITLE
Facing [runtime not ready]: Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by IAMDeveloperChetanSharma** [facebook/react-native#49867]
### Description

Hi Team, I am upgrading my project's RN version to 0.78 from 0.73.6, having Firebase's Latest version 11.4.0.

### Steps to reproduce

For IOS

yarn reinstall will do ("rm -rf iod/Pods && rm -rf node_modules && yarn install && yarn podinstall") for you then do
yarn ios

### React Native Version

0.78.0

### Affected Platforms

Runtime - iOS

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.3.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 117.27 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/admin/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.5
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/admin/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.78.0
    wanted: 0.78.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
index.js:32 This method is deprecated (as well as all React Native Firebase namespaced API) and will be removed in the next major release as part of move to match Firebase Web modular SDK API. Please see migration guide for more details: https://rnfirebase.io/migrating-to-v22 Please use `getApp()` instead.
&platform=ios&dev=tr…m.kulturpass:412548 [runtime not ready]: Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp(), js engine: hermes
anonymous	@	console.js:654
reactConsoleErrorHandler	@	ExceptionsManager.js:182
overrideMethod	@	backend.js:17785
anonymous	@	setUpDeveloperTools.js:62
registerError	@	LogBox.js:211
anonymous	@	LogBox.js:79
handleException	@	ExceptionsManager.js:154
handleError	@	setUpErrorHandling.js:25
reportFatalError	@	error-guard.js:49
guardedLoadModule	@	require.js:179
metroRequire	@	require.js:92
global	@	&platform=ios&dev=tr…m.kulturpass:412548
Show less
console.js:654 Running "cultureapp" with {"rootTag":1,"initialProps":{},"fabric":true}
console.js:654 [runtime not ready]: Invariant Violation: "cultureapp" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
anonymous	@	console.js:654
reactConsoleErrorHandler	@	ExceptionsManager.js:182
overrideMethod	@	backend.js:17785
anonymous	@	setUpDeveloperTools.js:62
registerError	@	LogBox.js:211
anonymous	@	LogBox.js:79
```

### Reproducer

https://github.com/IAMDeveloperChetanSharma/reproducer-react-native/tree/main/ReproducerApp

### Screenshots and Videos

![Image](https://github.com/user-attachments/assets/bab6fd75-f71f-408c-ab52-76cf7bf8dfbe)

**Comment by cipolleschi** [comment]
Can you share your appdelegate?
I believe that you are not calling the `[FIRApp configure]` method at the right time.

**Comment by saurabbhatt** [comment]
@cipolleschi :

```
import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    self.moduleName = "cultureapp"
    self.dependencyProvider = RCTAppDependencyProvider()

    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = [:]

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}

```

**Comment by cipolleschi** [comment]
yeah.. you are not calling `[FIRApp configure]` at all. That's why.
docs: https://rnfirebase.io/#configure-firebase-with-ios-credentials

**Comment by IAMDeveloperChetanSharma** [comment]
Hi @cipolleschi,

The link you shared has an appDelegate.h and .mm reference, but from the rn 0.78 appDelegate.swift has been introduced. I found a solution here: https://github.com/facebook/react-native/issues/48865#issuecomment-2630329685 for the .swift file 
but it is not working.

Can you explain it more? thank you.


import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
import Firebase


@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    Firebase.configure()
    self.moduleName = "cultureapp"
    self.dependencyProvider = RCTAppDependencyProvider()
    
    
    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = [:]

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}

**Comment by IAMDeveloperChetanSharma** [comment]
> The right call is `FirebaseApp.configure()`, not `Firebase.configure()`.

Will not it return module 'FirebaseApp' has no member named 'configure'?

**Comment by rentalrunner** [comment]
Same issue with mine as well. Been a pain the a** for about 2 weeks now. 

import UIKit
import FirebaseCore
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication,
                            didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
    print("AppDelegate: Launching app. Configuring Firebase...")
    
    FirebaseApp.configure()
    if let app = FirebaseApp.app() {
      print("Firebase initialized successfully with app name: \(app.name)")
    } else {
      print("FirebaseApp configuration failed!")
    }
    
    self.moduleName = "RentalRunner"
    self.dependencyProvider = RCTAppDependencyProvider()
    self.initialProps = [:]
    
    print("AppDelegate: Calling super.application()")
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    return bundleURL()
  }

  override func bundleURL() -> URL? {
    #if DEBUG
      return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
    #else
      return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
    #endif
  }
}

**Comment by furkananter** [comment]
I am getting a same issue with expo.

**Comment by omarsdev** [comment]
I just have this issue and fix it by adding 

```
import FirebaseCore
FirebaseApp.configure()
```


here is my full code

```
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
import RNBootSplash 
import FirebaseCore // ⬅️ this

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    self.moduleName = "YourAppName"
    self.dependencyProvider = RCTAppDependencyProvider()

    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = [:]
    FirebaseApp.configure() // ⬅️ this

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }

  // ⬇️ override this method
  override func customize(_ rootView: RCTRootView!) {
    super.customize(rootView)
    RNBootSplash.initWithStoryboard("BootSplash", rootView: rootView) // ⬅️ initialize the splash screen
  }
}


```

**Comment by IAMDeveloperChetanSharma** [comment]
> The right call is `FirebaseApp.configure()`, not `Firebase.configure()`.

Fixed for me after doing this.

**Comment by HemantRMali** [comment]
@cipolleschi  how to fix this in .mm file (Objective C, C++)?

**Comment by cipolleschi** [comment]
That's should be the fix. If that's still happening, it means that your bundle has some errors or that some other module crashes react native. 

1. on which version are you?
2. can you provide a reproducer?

**Comment by HemantRMali** [comment]
> That's should be the fix. If that's still happening, it means that your bundle has some errors or that some other module crashes react native.
> 
> 1. on which version are you?
> 2. can you provide a reproducer?

Below are the versions..
    "react": "18.3.1",
    "react-native": "0.77.1",

    "@react-native-firebase/analytics": "^21.8.0",
    "@react-native-firebase/app": "^21.8.0",
    "@react-native-firebase/crashlytics": "^21.8.0",
    "@react-native-firebase/remote-config": "^21.8.0",

**Comment by DonovanEnas** [comment]
> import FirebaseCore

Still getting the same error

**Comment by cipolleschi** [comment]
@DonovanEnas, [this comment](https://github.com/facebook/react-native/issues/49867#issuecomment-2708439389) contains the solution. On top of `import FirebaseCore`, you need to update your AppDelegate code to call `FirebaseApp.configure()`

---

@HemantRMali Iy your app delegate imports the right headers and calls [FIRApp configure] before React Native starts, it should work. It should be worth trying to debug the what happens after the `configure` method is called and before React Native starts. It could be that there is a race condition or an error that prevents Firebase to initialize properly.

**Comment by DonovanEnas** [comment]
> [@DonovanEnas](https://github.com/DonovanEnas), [this comment](https://github.com/facebook/react-native/issues/49867#issuecomment-2708439389) contains the solution. On top of `import FirebaseCore`, you need to update your AppDelegate code to call `FirebaseApp.configure()`
> 
> [@HemantRMali](https://github.com/HemantRMali) Iy your app delegate imports the right headers and calls [FIRApp configure] before React Native starts, it should work. It should be worth trying to debug the what happens after the `configure` method is called and before React Native starts. It could be that there is a race condition or an error that prevents Firebase to initialize properly.

I have already done these changes as per the firebase docs. But still facing this issue.

**Comment by aurangblackbuck** [comment]
Today I updated my react-native version to: "react-native": "0.79.0"
I started getting this error for Redux Saga:

![Image](https://github.com/user-attachments/assets/51b1ec11-8ec8-4265-9f8e-5142694df967)

**Comment by cipolleschi** [comment]
@DonovanEnas I believe then that there is something else interfering with firebase. I'd suggest you to create a new app and start adding your dependencies one at the time, starting with firebase, until you find the app the creates issues. I was testing firebase last week and it was working fine for me.

---

@aurangblackbuck this is usually a crash in the C++ happening due to some native module crashing. I'd suggest you to run the app in Xcode with the debugger attached to learn which module is crashing.

**Comment by aurangCreatah** [comment]
Thanks for the response @cipolleschi 
I fixed it with:

```
- import createSagaMiddleware from 'redux-saga';
+ const createSagaMiddleware = require('redux-saga').default;
```

I'm not sure that's the recommended way or not, but this worked!

**Comment by cipolleschi** [comment]
@aurangCreatah  yes, that's expected! https://reactnative.dev/blog/2025/04/08/react-native-0.79#internal-modules-updated-to-export-syntax

**Comment by Bob-JZhao** [comment]
> > [@DonovanEnas](https://github.com/DonovanEnas), [this comment](https://github.com/facebook/react-native/issues/49867#issuecomment-2708439389) contains the solution. On top of `import FirebaseCore`, you need to update your AppDelegate code to call `FirebaseApp.configure()`
> > [@HemantRMali](https://github.com/HemantRMali) Iy your app delegate imports the right headers and calls [FIRApp configure] before React Native starts, it should work. It should be worth trying to debug the what happens after the `configure` method is called and before React Native starts. It could be that there is a race condition or an error that prevents Firebase to initialize properly.
> 
> I have already done these changes as per the firebase docs. But still facing this issue.

Hi @cipolleschi, thanks for you replying in advance, I have follow the firebase document and add  `import FirebaseCore` and ` FirebaseApp.configure()` both, but I am still having this issue. The firebase version I use is 14.7.0

**Comment by rentalrunner** [comment]
I meant to circle back. My code worked. The issue was that for some reason all my other files would update when I restarted Xcode but for some reason my AppDelegate wouldn't so I just had to manually add it and boom. All was good.

**Comment by Bob-JZhao** [comment]
> I meant to circle back. My code worked. The issue was that for some reason all my other files would update when I restarted Xcode but for some reason my AppDelegate wouldn't so I just had to manually add it and boom. All was good.

hi @rentalrunner do you have any thought about my above question? Thanks

**Comment by rentalrunner** [comment]
> > I meant to circle back. My code worked. The issue was that for some reason all my other files would update when I restarted Xcode but for some reason my AppDelegate wouldn't so I just had to manually add it and boom. All was good.
> 
> hi @rentalrunner do you have any thought about my above question? Thanks 

Mine is above a few comments back and mine works exactly like that. May be some others that are too. Honestly nothing ever works for me and for once something did. Just be sure to check and make sure your code is actually updating in Xcode too. For some reason I had to delete it and manually add the new version.

**Comment by cipolleschi** [comment]
@Bob-JZhao you need to initialize firebase BEFORE starting react native.

```diff
+   FirebaseApp.configure()
    factory.startReactNative(withModuleName: "test", in: window, launchOptions: launchOptions);
-   FirebaseApp.configure()
```

Otherwise ReactNative will start, wil try to load firebase stuff, but FB is not configured and you get the error.

**Comment by Bob-JZhao** [comment]
> [@Bob-JZhao](https://github.com/Bob-JZhao) you need to initialize firebase BEFORE starting react native.
> 
> +   FirebaseApp.configure()
>     factory.startReactNative(withModuleName: "test", in: window, launchOptions: launchOptions);
> -   FirebaseApp.configure()
> Otherwise ReactNative will start, wil try to load firebase stuff, but FB is not configured and you get the error.

hi @cipolleschi thanks, actually I tried put it on the top, see my code line 18, it's not working as well. Maybe worth to mention that I use react-native version is 0.79.1. I upgraded the latest firebase version, it works now!

**Comment by IAMDeveloperChetanSharma** [comment]
Hi, After doing all the changes. Now I am facing No such module 'RNFBMessagingModule'. 
Below is my AppDelegate.

```
import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
import Firebase
import RNFBMessagingModule
import React_RCTLinking

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
    FirebaseApp.configure()
    self.moduleName = "cultureapp"
    self.dependencyProvider = RCTAppDependencyProvider()

    // Add custom initial props
    self.initialProps = RNFBMessagingModule.addCustomProps(toUserProps: nil, withLaunchOptions: launchOptions)

    #if DEBUG
    // Enable console.log logging in macOS Console App for Release builds
    RCTSetLogThreshold(RCTLogLevel.info.rawValue - 1)
    RCTSetLogFunction { level, source, fileName, lineNumber, message in
      NSLog("%@", RCTFormatLog(nil, level, nil, nil, message))
    }
    #endif

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    return self.getBundleURL()
  }

  func getBundleURL() -> URL? {
    #if DEBUG
    return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
    #else
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
    #endif
  }

  // Adds Deeplinking support
  override func application(_ application: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
    return RCTLinkingManager.application(application, open: url, options: options)
  }

  override func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    return RCTLinkingManager.application(application, continue: userActivity, restorationHandler: restorationHandler)
  }
}

```


<img width="1140" alt="Image" src="https://github.com/user-attachments/assets/3502e37a-8bea-4893-9758-847d23b6ca92" />

**Comment by cipolleschi** [comment]
@IAMDeveloperChetanSharma the `RNFBMEssagingModule` is a firebase specific module.
It seems to me that you forgot to install the module properly.

[This is the guide](https://github.com/invertase/react-native-firebase/tree/main/packages/in-app-messaging) on how to do it, scroll down and the README will show you how to install it properly.

You can also double check if you have the module properly installed in the `Pods` project.

**Comment by saurabbhatt** [comment]
Hi @cipolleschi , We tried that approach, but we're still facing the issue with the following dump in the pipeline:

`info  sapExecuteFastlane - ❌ /Users/admin/hyperspace-mobile-london/_work/1/s/ios/***/AppDelegate.swift:6:8: no such module 'RNFBMessagingModule'
info  sapExecuteFastlane - import RNFBMessagingModule
info  sapExecuteFastlane -        ^
info  sapExecuteFastlane - [***] Compiling GeneratedAssetSymbols.swift
info  sapExecuteFastlane - [***] Compiling AppDelegate.swift
info  sapExecuteFastlane - ❌ /Users/admin/hyperspace-mobile-london/_work/1/s/ios/***/AppDelegate.swift:6:8: no such module 'RNFBMessagingModule'
info  sapExecuteFastlane - import RNFBMessagingModule`



As per your suggestion we have added RNFBMEssagingModule correctly. ( we ran : yarn add @react-native-firebase/in-app-messaging ) 

![Image](https://github.com/user-attachments/assets/abc772c2-f635-4bd0-b3d5-734555961686)

**Comment by Spero-Sourabh** [comment]
> > [@Bob-JZhao](https://github.com/Bob-JZhao) you need to initialize firebase BEFORE starting react native.
> > 
> > * FirebaseApp.configure()
> >   factory.startReactNative(withModuleName: "test", in: window, launchOptions: launchOptions);
> > 
> > 
> > * FirebaseApp.configure()
> >   Otherwise ReactNative will start, wil try to load firebase stuff, but FB is not configured and you get the error.
> 
> hi [@cipolleschi](https://github.com/cipolleschi) thanks, actually I tried put it on the top, see my code line 18, it's not working as well. Maybe worth to mention that I use react-native version is 0.79.1. I upgraded the latest firebase version, it works now!

could you share you AppDelegate.swift file full code

**Comment by Muhammadmahadsaeed** [comment]
@cipolleschi @Bob-JZhao i am facing same issue on android and ios. i have checked the confirguration multiple times and its correct also google-service.json and GoogleService-Info.plist are placed in correct directory. Here is my version of firebase and react native
"@react-native-firebase/app": "21.10.1",
    "@react-native-firebase/messaging": "21.10.1",
 "react": "18.3.1",
    "react-native": "0.76.9",

i am using this classpath 'com.google.gms:google-services:4.4.2' and also tried with 4.3.15 but still facing same issue

**Comment by SinaSultani** [comment]
Hey everyone, I managed to solve this issue.

I noticed that in Xcode → Project Folder → Build Phases, the AppDelegate.swift that Xcode was actually compiling was different from the one I had been editing. The compiled one was just the boilerplate AppDelegate without any of my Firebase imports or setup.

The key things that fixed it for me were:

Make sure your AppDelegate.swift is in the root ios/ folder, not in ios/YourApp/. Xcode will only pick up the one in the root for the build (at least in my case).

Import and configure Firebase exactly as shown in the React Native Firebase docs:

import Firebase
FirebaseApp.configure()


Docs reference: [Configure Firebase with iOS credentials (React Native 0.77+)](https://rnfirebase.io/#configure-firebase-with-ios-credentials-react-native-077)

After doing this, Firebase initialized correctly and my app started working.

**Comment by Girish-GAP** [comment]
Hi @Muhammadmahadsaeed , Facing same issue in android for ^0.76 is anything worked for you ?

**Comment by anubisdark** [comment]
Hi there i upgrade expo for sdk 51 to sdk 54, and use the libraries por firebase react native library, and implementing of said the documentation, but i have the same error, in my case i try to run in ios, when run the project, i see the error for double initialize in native and javascript, for this delete the initialize in javascript, and let it native code initialize the firebase. But i have the same issue. 
This is the dependencies i use:

  "dependencies": {
    "@expo-google-fonts/lato": "^0.2.3",
    "@expo/webpack-config": "~19.0.1",
    "@react-native-async-storage/async-storage": "2.2.0",
    "@react-native-clipboard/clipboard": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-firebase/analytics": "^18.7.3",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/crashlytics": "^18.7.3",
    "@react-native-firebase/messaging": "^18.7.3",
    "@react-navigation/material-bottom-tabs": "^6.2.15",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.5",
    "@shopify/flash-list": "2.0.2",
    "babel-plugin-module-resolver": "^5.0.2",
    "expo": "^54.0.10",
    "expo-apple-authentication": "~8.0.7",
    "expo-build-properties": "~1.0.9",
    "expo-camera": "~17.0.8",
    "expo-config-plugins": "^0.1.2",
    "expo-dev-client": "~6.0.12",
    "expo-font": "~14.0.8",
    "expo-image": "~3.0.8",
    "expo-image-picker": "~17.0.8",
    "expo-local-authentication": "~17.0.7",
    "expo-network": "~8.0.7",
    "expo-screen-orientation": "~9.0.7",
    "expo-secure-store": "~15.0.7",
    "expo-sharing": "~14.0.7",
    "expo-status-bar": "~3.0.8",
    "expo-system-ui": "~6.0.7",
    "i18next": "^23.15.0",
    "i18next-http-backend": "^2.6.1",
    "i18next-localstorage-backend": "^4.2.0",
    "intl-pluralrules": "^2.0.1",
    "jail-monkey": "^2.8.0",
    "moment": "^2.30.1",
    "onesignal-expo-plugin": "^2.0.2",
    "patch-package": "^8.0.0",
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "react-hook-form": "^7.48.2",
    "react-i18next": "^15.0.1",
    "react-native": "0.81.4",
    "react-native-alert-notification": "^0.4.0",
    "react-native-countdown-circle-timer": "^3.2.1",
    "react-native-device-info": "^10.12.0",
    "react-native-dialog": "^9.3.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-element-dropdown": "^2.12.4",
    "react-native-gesture-handler": "~2.28.0",
    "react-native-get-random-values": "~1.11.0",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-modal": "^13.0.1",
    "react-native-paper": "^5.11.3",
    "react-native-public-ip": "^1.0.2",
    "react-native-reanimated": "~4.1.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "~5.6.0",
    "react-native-screens": "~4.16.0",
    "react-native-svg": "15.12.1",
    "react-native-svg-transformer": "1.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "~4.0.3",
    "react-native-worklets": "0.5.1",
    "react-redux": "^9.2.0",
    "url": "^0.11.3",
    "util": "^0.12.5",
    "uuid": "^9.0.1"
  }

**Comment by Ahsanali012** [comment]
I am too facing this issue in react native cli for android build. Any solution ?

**Comment by thanhlv263** [comment]
> I am too facing this issue in react native cli for android build. Any solution ?
@Ahsanali012 

if App.tsx or index call firebase, move to another file

**Comment by JVGS1111** [comment]
I had this when I was upgrading my RN from 0.75 to 77 and I had it only on IOS.
I managed it by updating the libraries from version 18 to 23.

**before:**
```json
    "@react-native-firebase/analytics": "18.6.0",
    "@react-native-firebase/app": "18.6.0",
    "@react-native-firebase/database": "18.6.0",
    "@react-native-firebase/messaging": "18.6.0",
    "@react-native-firebase/remote-config": "18.6.0",
```

**After:**
```json
    "@react-native-firebase/analytics": "^23.7.0",
    "@react-native-firebase/app": "^23.7.0",
    "@react-native-firebase/database": "^23.7.0",
    "@react-native-firebase/messaging": "^23.7.0",
    "@react-native-firebase/remote-config": "^23.7.0",
```

**Comment by Arafat-alim** [comment]
## ✅ Issue Resolution: Firebase Remote Config Integration

**Tech Stack Used:**
- React Native CLI (Android) v0.83
- TypeScript
- Firebase App v23.8.4
- Firebase Remote Config v23.8.4

---

### 🔧 Configuration Steps

**1. Update `android/build.gradle` (Project Level)**
```gradle
buildscript {
    ext {
        buildToolsVersion = "36.0.0"
        minSdkVersion = 24
        compileSdkVersion = 36
        targetSdkVersion = 36
        ndkVersion = "27.1.12297006"
        kotlinVersion = "2.1.20"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath("com.google.gms:google-services:4.4.4")  // ✅ Add Google Services plugin
    }
}
```

**2. Update `android/app/build.gradle` (App Level)**
```gradle
apply plugin: "com.android.application"
apply plugin: "org.jetbrains.kotlin.android"
apply plugin: "com.facebook.react"
apply plugin: "com.google.gms.google-services"   // ✅ Apply Google Services plugin (CRITICAL)

dependencies {
    implementation("com.facebook.react:react-android")
    implementation 'com.google.android.gms:play-services-auth:21.3.0'   // ✅ Optional: For Google Auth
    
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}
```

**3. Add Firebase Configuration**
- Download `google-services.json` from your Firebase project console
- Place it in `android/app/` directory
- Ensure the package name matches your Firebase project

---
