### ISSUE TITLE
RefreshControl ignores style prop

### ISSUE THREAD

**Issue by plneple** [facebook/react-native#51914]
### Description

This is relevant to our project because we have a top section view that must maintain its background color during the ScrollView bounce effect. To achieve this, we layer an absolutely positioned view with the same background color beneath the ScrollView, and elevate the RefreshControl above it using zIndex. This approach works as expected in the old architecture, but it no longer functions correctly after upgrading to the new architecture.

The issue is resolved with the following patch, which addresses the zIndex behavior specifically
[patch.patch](https://github.com/user-attachments/files/20667196/patch.patch)

### Steps to reproduce

1. Open the Snack
2. `RefreshControl` is under the view

### React Native Version

0.79.3

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: macOS 15.5
  CPU: (10) arm64 Apple M4
  Memory: 156.75 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.17.0/bin/yarn
  npm:
    version: 11.2.0
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2025.02.17.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.5
      - iOS 18.5
      - macOS 15.5
      - tvOS 18.5
      - visionOS 2.5
      - watchOS 11.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.25659.59.2432.13423653
  Xcode:
    version: 16.4/16F6
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.14
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/u/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: 18.0.0
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.3
    wanted: 0.79.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
not relevant
```

### MANDATORY Reproducer

https://snack.expo.dev/@lsbbdbxnzhsbdb/refreshcontrol-zindex-issue

### Screenshots and Videos

https://github.com/user-attachments/assets/2fc991d6-5ba4-40c3-bb47-56eaeb74e88e
https://github.com/user-attachments/assets/7cfa800c-b4c7-415e-b315-f8df8ad5ad17

**Comment by cipolleschi** [comment]
Hi @plneple, thanks for the issue.
Was it working in 0.78 or previous versions of React Native with the New Architecture?

I remember landing a couple of fixes for RCTScrollComponentView but they are not recent. I'm trying to understand whether this is a regression or not.

**Comment by plneple** [comment]
Hey @cipolleschi,

I'm currently migrating the app to the New Architecture. It's definitely working on the old architecture v0.77.

It looks like the bug comes from how `RCTPullToRefreshViewComponentView` is built. It seems to be two views, and the styles that should apply by default aren't actually hitting the one being rendered. I think that's the core of the problem.

Happy to check older New Architecture versions if that would help you out, but it will take me some time to get back to you (I am not sure how to run expo snack on previous versions of react-native, so I would have to setup a project locally)

**Comment by cipolleschi** [comment]
I tried to disable the New Architecture and the PulltoRefresh was visible but the top view is still red... 🤔 which I assume is not the expectation... you second video shows that the view on top is blue...

![Image](https://github.com/user-attachments/assets/5db2a729-54ab-4c40-9f9d-63ed63b2c4af)

I think that there is something else going on, also. It renders differently:

| New Arch (first render)| New Arch (after pulling) | Old Arch (first render) | Old Arch (after pulling) |
| --- | --- | --- | --- |
| ![Image](https://github.com/user-attachments/assets/5619c995-09fe-4f54-a7cf-cb382b2215ac) | ![Image](https://github.com/user-attachments/assets/86faa539-0952-4314-bf41-896aff11e004) | ![Image](https://github.com/user-attachments/assets/15a974d3-dcf9-4dc7-b883-9d90e1cc72a0) | ![Image](https://github.com/user-attachments/assets/095b9483-20ab-4245-9ddd-0a87d5634044) |

Also, in the new architecture, the refresh control doesn't move, while in the new architecture it does.

| Old Architecture | New Architecture |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/81ab3824-b278-416c-b4ab-a46cc512c45b) | ![Image](https://github.com/user-attachments/assets/1a90b35b-5550-4d58-be1e-e2cec4fd1ed2) |

**Comment by Bram-dc** [comment]
The refresh control is currently really buggy. I would love to see some work done on it. In the new arch it also jumps around for me. For me most bugs occurred after upgrading from 0.76

**Comment by saadi-ninjasCode** [comment]
In RN 0.80, colors are not applied on RefreshControl

**Comment by plneple** [comment]
Hi @cipolleschi,

Apologies for the delayed response.

It looks like the videos I initially shared may have caused some confusion. To clarify, both recordings were taken using the new architecture.

* The first video demonstrates what happens when a “top view” is added to prevent the background from changing during the bounce. This view ends up covering the `RefreshControl`, and there doesn't appear to be a way to place it above it.
* The second video shows the result without that view (still using the new architecture). The purpose was to confirm that the issue is related to styling and not due to the RefreshControl failing to render. In hindsight, using opacity might have illustrated this more clearly.

From your recordings, I can see the issue is reproducible on your end as well, so I won't spend additional time identifying the exact `react-native` version where the regression was introduced.

Thanks again for taking a look!

**Comment by fe-dudu** [comment]
In my app (RN 0.80), the refresh control does not display properly in iOS dark mode.
When will this issue be fixed?

**Comment by cipolleschi** [comment]
All issues should have been solved by these commits:
- https://github.com/facebook/react-native/commit/09daad27ea22b83fab65176ea3c7f5f1488ba408
- https://github.com/facebook/react-native/commit/21b93d8d7d46a26f728df19764f85a8aebf318bb
- https://github.com/facebook/react-native/commit/27217e8bd601757b5db6efc022db428b552a2aa4

and they will be released in 0.82.

We might consider them to be picked in previous version of React Native if you can try to apply those pathces into your apps and you verify that they work.

If that happens, you can open a pick request [here](https://github.com/reactwg/react-native-releases/issues/new?template=pick_request_form.yml)

**Comment by Noitham** [comment]
Hey @cipolleschi,

FYI - I've patched 0.81.1, and unfortunately, those commits don't seem to address the issue with the RefreshControl Spinner not applying correctly the tintColor on mount.

Looking forward 0.82

**Comment by landabaso** [comment]
I’m having the same problem as @plneple.

I was also using an absolute-positioned `<View>` with a white background and relying on `zIndex` tricks so that the `RefreshControl` would still show on iOS. This worked fine before the new architecture, but it no longer does.

I tried backporting the commits mentioned in this thread to React Native `0.79.5` (expo 53.0.22), but that didn’t fix the issue.

@plneple , how did you end up fixing it?

**Comment by saiyam-zepto-dev** [comment]
@cipolleschi THese fixed the issue for the first time mount. When i go back and open my screen again and try refreshing , the indicator is again not shown

**Comment by plneple** [comment]
@landabaso I’m currently using the patch I initially shared.

I plan to test the commits that will be included in react-native@0.82, but I haven’t tried them yet.

At the moment, I’m on react-native@0.79 and migrating to react-native@0.81, which includes a precompiled react-native for iOS. With that change, the patch will no longer work. Perhaps you’re on a later version already, which might explain why it isn’t working on your side?

**Comment by landabaso** [comment]
Thanks, @plneple. I ended up using the **[latest](https://github.com/facebook/react-native/blob/40c60adacf17f3d5fe54cfcbaf70138de1fe0537/packages/react-native/React/Fabric/Mounting/ComponentViews/ScrollView/RCTPullToRefreshViewComponentView.mm)** `RCTPullToRefreshViewComponentView.mm` from main, which already includes @cipolleschi’s fixes, instead of patching my older RN version. After adapting a couple of import paths, it works correctly for me (Expo, RN **0.79.5**, iOS, New Architecture).

Thanks to both of you!

**Comment by plneple** [comment]
@cipolleschi I’ve tested RefreshControl with react-native@0.82.0, and the issue appears to be resolved.

Thank you for the fix! 🙌

**Comment by Jamal-Ud-Din-hub** [comment]
Still same issue

`"react-native": "0.80.2"`

**Comment by luchinayan** [comment]
Still same issue

"react-native": "0.81.5"

tintColor doesnt work

**Comment by jackw3434** [comment]
same for me "react-native": "0.81.5", expo sdk 54, ios
