### ISSUE TITLE
RN0.73.4 upgrade to 0.80.1，app crash error: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreact_featureflagsjni.so" not found

### ISSUE THREAD

**Issue by cx5168** [facebook/react-native#52698]
### Description

RN0.73.4 upgrade to 0.80.1，app crash error: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreact_featureflagsjni.so" not found.

MainApplication.java:
using SoLoader.init(this, false); have a crash error.

using SoLoader.init(this, OpenSourceMergedSoMapping); OpenSourceMergedSoMapping is invalid error.
using SoLoader.init(this, OpenSourceMergedSoMapping); same the invalid erro.

android/build.gradle:
buildToolsVersion = "36.0.0"
        minSdkVersion = 24
        compileSdkVersion = 36
        targetSdkVersion = 36
        ndkVersion = "27.1.12297006"
        kotlinVersion = "2.1.20

android/gradle.properties:
newArchEnabled=false

### Steps to reproduce

1,build OK
2,install app
3,crash

### React Native Version

0.80.1

### Affected Platforms

Build - Windows

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
  Memory: 1.60 GB / 15.83 GB
Binaries:
  Node:
    version: 20.12.2
    path: D:\nodeVM\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: D:\nodeVM\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 19.0.0
    wanted: 19.0.0
  react:
    installed: 19.1.0
    wanted: 19.1.0
  react-native:
    installed: 0.80.1
    wanted: 0.80.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
E  FATAL EXCEPTION: main
                                                                                                    Process: [Package Name], PID: 18397
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libreact_featureflagsjni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:812)
                                                                                                    	at com.facebook.react.internal.featureflags.ReactNativeFeatureFlagsCxxInterop.<clinit>(ReactNativeFeatureFlagsCxxInterop.kt:28)
                                                                                                    	at com.facebook.react.internal.featureflags.ReactNativeFeatureFlagsCxxAccessor.enableBridgelessArchitecture(ReactNativeFeatureFlagsCxxAccessor.kt:137)
                                                                                                    	at com.facebook.react.internal.featureflags.ReactNativeFeatureFlags.enableBridgelessArchitecture(ReactNativeFeatureFlags.kt:79)
                                                                                                    	at com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlags.enableBridgelessArchitecture(ReactNativeNewArchitectureFeatureFlags.kt:38)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.lambda$onCreate$0(ReactActivityDelegate.java:127)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.$r8$lambda$HPdXfLmAU1y4Wc1XbwAHziPP2WA(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactActivityDelegate$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at com.facebook.systrace.Systrace.traceSection(Systrace.kt:35)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:118)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:61)
                                                                                                    	at 
[Package Name].MainActivity.onCreate(MainActivity.java:16)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9002)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

### MANDATORY Reproducer

none reproducer

**Comment by cx5168** [comment]
i need help everybody

**Comment by pierroo** [comment]
first questions that come to mind is:
- why are you still using java files for MainApplication?
- RN0.80+ no longer use SoLoader 
- New arch is now enabled by default, so your newArchEnabled is probably useless?

Did you use the upgrade helper to know exactly what you must change?
https://react-native-community.github.io/upgrade-helper/?from=0.79.3&to=0.80.1

**Comment by cx5168** [comment]
@pierroo 
Thank you, brother. I'll give it a try

**Comment by cortinico** [comment]
Duplicate of:
- https://github.com/facebook/react-native/issues/50508

There is something wrong with your app update, you haven't followed all the steps of the upgrade helper

**Comment by cx5168** [comment]
@pierroo @cortinico 
According to RN0.80.1, the upgrade content has been fully configured and the problem has been solved.

Thanks!

**Comment by WebtualUtsav** [comment]
"react": "19.1.0",
"react-native": "0.81.0",

i getting same error in above version try all method but still getting same error

**Comment by bmitioglov** [comment]
I removed SoLoader call, looks like it helped

**Comment by DevCCC** [comment]
@cx5168 @cortinico @pierroo  how did you solve that error i have having the same error do i need to replace mainapplication.java with kotlin and remove soloader?
