### ISSUE TITLE
Text not fully rendered on iOS

### ISSUE THREAD

**Issue by soutua** [facebook/react-native#53450]
### Description

We noticed an issue on our app that is using a lot of text (news articles), where in some specific cases the text is not fully rendered on iOS, after we moved into using the new architecture in our last release. I'm not sure what are all the factors that are needed for the issue to occur, but I was able to make a reproducer with some experimenting.

### Steps to reproduce

Reproducer Snack can be found on: https://snack.expo.dev/@pekka.soutua/text-cut-off-on-ios
Note that it's important to use the iPhone 16 Pro emulator, since the issue seems to be dependant on e.g. screen dimensions. I also tested that the issue reproduces on the issue reproducer template with the latest React Native version: https://github.com/soutua/react-native-new-architecture-text-rendering-issue

Scroll down the text until you see a paragraph with text "Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit. This sentence is cut off.".

The sentence in the end "This sentence is cut off.", is not being fully rendered, the rest of it should be rendered on the next line but it isn't.

### React Native Version

0.81.0

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx @react-native-community/cli info`

```text
Reproducible e.g. on the snack.expo.dev environment or on the issue reproducer template.
```

### Stacktrace or Logs

```text
-
```

### MANDATORY Reproducer

https://snack.expo.dev/@pekka.soutua/text-cut-off-on-ios

### Screenshots and Videos

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/74c7144c-c29f-4b87-944d-9435708024c8" />

**Comment by emirdeliz** [comment]
Same here! But I noticed this occurs after opening the app for the second time.

<img width="372" height="306" alt="Image" src="https://github.com/user-attachments/assets/bf3c6abd-14f8-4bf7-a28c-acfdb1c43a61" />

**Comment by johankasperi** [comment]
We are seeing the same issue in our app (also when showing news articles)

**Comment by johankasperi** [comment]
Can it be an issue with using `lineHeight`? Because when setting it to undefined in your repro https://github.com/soutua/react-native-new-architecture-text-rendering-issue/blob/b57f531407db0cc7380287294bdda626d81180b7/ReproducerApp/App.tsx#L319 I'm not seeing the bug. But when setting it to something else, texts is not fully rendered in one or several of the paragraphs.

**Comment by soutua** [comment]
> Can it be an issue with using `lineHeight`? 

Yes I think it is a factor in this, I was not able to reproduce the issue either if I did not set the `lineHeight`.

Also other interesting observation during my reproduction experiments was that it's not about any single text paragraph in itself, but all the content in the screen can affect the reproduction of the issue. For example if you remove some of the text in my reproducer, the issue might go away.

**Comment by johankasperi** [comment]
I think the issue is caused by [these lines](https://github.com/facebook/react-native/blob/9dba7112cfd09b02300869a77dba3dca16f49a28/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L226) somehow. By removing `paragraphystyles.minimumLineHeight` all text is rendered. But they have the wrong lineheight.

**Comment by johankasperi** [comment]
Doing something like this also seems to solve it in your repro and it produces the correct lineheight
```
    paragraphStyle.minimumLineHeight = lineHeight - 0.01;
    paragraphStyle.maximumLineHeight = lineHeight + 0.01;
```
but not sure if it solves it in all cases, for example is the 0.01 value arbitrary

**Comment by johankasperi** [comment]
This code also fixes it
```
    paragraphStyle.lineHeightMultiple = round((lineHeight / font.lineHeight) * 10000.0) / 10000.0;
```
But this also feels unsafe. It doesn't work when I'm not rounding it

**Comment by johankasperi** [comment]
Ended up doing this hack in my app. Probably just a workaround and not a real solution to the problem
```
    paragraphStyle.maximumLineHeight = lineHeight * 1.01;
    paragraphStyle.minimumLineHeight = lineHeight * 0.99;
    paragraphStyle.lineHeightMultiple = lineHeight / font.lineHeight;
```

**Comment by pierroo** [comment]
I am also facing the issue, not sure if it's exactly the same, but just in case:
https://github.com/facebook/react-native/issues/53666

it's on android though.
It happened only after updating to 0.81.x

do you guys face this issue on 0.80.x?

**Comment by soutua** [comment]
> do you guys face this issue on 0.80.x?

We encountered this issue also on 0.79, so might be a different issue (with similar symptoms).

**Comment by renopp** [comment]
> > do you guys face this issue on 0.80.x?
> 
> We encountered this issue also on 0.79, so might be a different issue (with similar symptoms).

Our app (news articles) encountered this issue starting from 0.76 until 0.81. It seems this issue occurs based on the content and display size of the device.

**Comment by pierroo** [comment]
This bug makes it impossible to release an actual app at the moment considering how bad it is.
Have you guys thought any other links to that?  did any of you try @johankasperi suggestion for a fix, and did it work for you?

On my end the issue remains on android, haven't tested on iOS, but if this "hack" is confirmed to work I might dig deeper into android native files to find something similar.

Not sure if react native's team acknowledged this issue yet somewhere?
It feels like a show stopper to me.

**Comment by soutua** [comment]
I have been looking into this issue this week and it feels to me that this is a rounding error in calculating the line heights for the text being rendered, it would also somewhat explain why it also matters what other text is on the screen since the text layout y coordinates change, which can then affect the calculations and the rounding errors occurring.

So what I think happens is that here in this [measureTextStorage function](https://github.com/facebook/react-native/blob/61bd649c935d69bc4a33a095007b7d510d115ea5/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm#L333) where the line heights are calculated, the calculated height is a bit too small, so the last line of the paragraph is missing fraction of the height that is required to render the text on the final line of the paragraph, so iOS decides to render it on the second last line, running off the screen. It also explains why @johankasperi's workaround of decreasing the minimum line height workarounds the issue, since it gives iOS's text renderer permission to render it with a bit less line height so that it fits on the last line even though it does have a bit less height.

I also found [this code](https://github.com/facebook/react-native/blob/6eb456bc4e6bcdf2f9f9b41c4b8265b9bee3af54/packages/react-native/Libraries/Text/Text/RCTTextShadowView.mm#L449) in the React Native's old architecture's code where apparently similar issue has been fixed [8 years ago](https://github.com/facebook/react-native/commit/a534672e132136e7bbd17c94a7f4e67149bcc67a).

I tested that doing a similar fix/workaround in the new architecture code where I do this [here](https://github.com/facebook/react-native/blob/61bd649c935d69bc4a33a095007b7d510d115ea5/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm#L389):

So instead of:

```
  size = (CGSize){
      ceil(size.width * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
      ceil(size.height * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
```
add the epsilon:
```
  CGFloat epsilon = 0.001;
  size = (CGSize){
      ceil(size.width * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor + epsilon,
      ceil(size.height * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor + epsilon};
```
and the issue no longer reproduces, at least on my reproducer app. Not sure if this the best fix for this or not, but at least the fix is the same as in the old architecture's code.

Edit:
Or actually I think this code makes more sense where the epsilon is added before the pixel snapping operation, since otherwise the pixel snapping is kinda pointless if the result is modified after:
```
  CGFloat epsilon = 0.001;
  size = (CGSize){
      ceil((size.width + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
      ceil((size.height + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
```

**Comment by johankasperi** [comment]
> Or actually I think this code makes more sense where the epsilon is added before the pixel snapping operation, since otherwise the pixel snapping is kinda pointless if the result is modified after:
> 
> ```
>   CGFloat epsilon = 0.001;
>   size = (CGSize){
>       ceil((size.width + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
>       ceil((size.height + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
> ```

This seems to do the trick! Much better solution than my earlier attempts. Thank you @soutua!

**Comment by soutua** [comment]
> This seems to do the trick! Much better solution than my earlier attempts. Thank you [@soutua](https://github.com/soutua)!

We also released a version today with this change patched in. We were using the old architecture in the interim, but now moved back into using the new architecture with this patch. In our internal testing we were no longer able to reproduce the issue. But we'll see from the user (and several hundred angry journalists when they see words are missing from their articles) feedback if it's 100% fixed or not.

**Comment by Kitcheone** [comment]
I'm also experiencing this issue, only on iOS on new architecture.

@soutua I tried applying your fix (using patch-package), but the issue still persists for me. How did you apply your fix? The contents of my patch file look like this:

```
diff --git a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
index 216bb23..fe45309 100644
--- a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
+++ b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
@@ -386,9 +386,10 @@ static NSLineBreakMode RCTNSLineBreakModeFromEllipsizeMode(EllipsizeMode ellipsi
     size.height = enumeratedLinesHeight;
   }
 
+  CGFloat epsilon = 0.001;
   size = (CGSize){
-      ceil(size.width * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
-      ceil(size.height * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
+      ceil((size.width + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
+      ceil((size.height + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
 
   __block auto attachments = TextMeasurement::Attachments{};
```

**Comment by soutua** [comment]
> I'm also experiencing this issue, only on iOS on new architecture.
> 
> [@soutua](https://github.com/soutua) I tried applying your fix (using patch-package), but the issue still persists for me. How did you apply your fix? The contents of my patch file look like this:
> 
> ```
> diff --git a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
> index 216bb23..fe45309 100644
> --- a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
> +++ b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
> @@ -386,9 +386,10 @@ static NSLineBreakMode RCTNSLineBreakModeFromEllipsizeMode(EllipsizeMode ellipsi
>      size.height = enumeratedLinesHeight;
>    }
>  
> +  CGFloat epsilon = 0.001;
>    size = (CGSize){
> -      ceil(size.width * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
> -      ceil(size.height * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
> +      ceil((size.width + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
> +      ceil((size.height + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
>  
>    __block auto attachments = TextMeasurement::Attachments{};
> ```

The patch seems correct to me at least. I'm applying the patch with yarn's patching feature (resolutions). Have you checked  e.g. by `less node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm` that the lines have changed, so that the patch has applied correctly?

We've now been running the patch in production for couple of weeks and we've not gotten any feedback about the issue still occurring, so it seems to be fixed on our app with the patch. Although we are still using React Native 0.79 due to some issues with our dependencies with newer react native versions so we might not be running exactly the same code as you.

**Comment by Kitcheone** [comment]
@soutua Thanks for the reply. Yes, I can see that the lines have changed in my node_modules directory, so the patch has applied correctly, and yet it doesn't seem to fix the issue. I'm currently running on React Native 0.81.4 (via Expo 54), so yes there could be something else at play.

I'll keep digging and report back here if I manage to resolve it!

**Comment by Kitcheone** [comment]
@soutua FYI, your fix does indeed work against RN 0.79.5. So it seems like there's a further problem with RN 0.81, which I haven't been able to fix yet. I've tried larger values of epsilon (as a test), but it still always truncates.

Note that the code in RCTTextLayoutManager in RN is a little bit different in 0.79, so the patch I generated looks like this:

```
diff --git a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
index f75f78f..98b8afd 100644
--- a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
+++ b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
@@ -373,7 +373,8 @@ static NSLineBreakMode RCTNSLineBreakModeFromEllipsizeMode(EllipsizeMode ellipsi
     size.width = textContainer.size.width;
   }
 
-  size = (CGSize){RCTCeilPixelValue(size.width), RCTCeilPixelValue(size.height)};
+  CGFloat epsilon = 0.001;
+  size = (CGSize){RCTCeilPixelValue(size.width + epsilon), RCTCeilPixelValue(size.height + epsilon)};
 
   __block auto attachments = TextMeasurement::Attachments{};
 ```

**Comment by soutua** [comment]
Yep the lines are a bit different in the 0.79, with the same functionality though. 

It's interesting if the fix doesn't work in RN 0.81, since the reproducer app that is linked in the issue description is using 0.81, and the issue was fixed also in the reproducer app with the patch. But could of course be that just that it just made it less likely to happen 🤔

**Comment by Unuuuuu** [comment]
I'm also experiencing this issue on React Native 0.81.4 with the new architecture on iOS.
Can confirm that the proposed fix doesn't seem to work on 0.81.4 as mentioned by @Kitcheone.

This is a critical issue for apps with text-heavy content. Hoping this gets resolved soon.

**Comment by soutua** [comment]
I now tested our app with RN version 0.81.5 with and without this change:
```
  CGFloat epsilon = 0.001;
  size = (CGSize){
      ceil((size.width + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
      ceil((size.height + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
```
If I don't have that patch included, I can reproduce the issue quite easily, maybe in 50% of our app's news articles. If I use the patch, I haven't yet been able to reproduce it, I checked maybe 50 articles when testing. I'm wondering if the issue you are encountering might possibly be some other issue? Since to me it seems like the patch works similarly as it did in the RN 0.79 we are using in production 🤔

**Comment by soutua** [comment]
One thing that came to mind; check that you are not using the pre-compiled React Native iOS binaries. That option came in RN 0.81. If you are using the pre-compiled version, then the patch is not used.

**Comment by Kitcheone** [comment]
@soutua that's a really good point! We're using Expo, and so we were trying RN 0.81 with Expo SDK54, which does use precompiled RN binaries by default. I'll try disabling it.

**Comment by Unuuuuu** [comment]
@soutua 
Thank you for pointing that out! As you mentioned, we were indeed using the precompiled RN binary. After enabling the `buildReactNativeFromSource` option to build RN from source instead of using the precompiled binary, we can confirm that the issue has been resolved in all the places where it was previously reproducible.

**Comment by Kitcheone** [comment]
I can also confirm that the patch seems to fix the problem on RN 0.81, once we enabled `buildReactNativeFromSource`.

@soutua I think we should raise a PR with your fix. As the exact same fix used to exist on old arch, I would hope that it would get approved and merged. Do you want to raise it? If not, I'm happy to raise it.

**Comment by soutua** [comment]
Yep, wanted to make sure that no one here is still able to reproduce the issue when using the patch, but I've now made a PR of it: https://github.com/facebook/react-native/pull/54260

**Comment by Kitcheone** [comment]
@soutua Nice one - great stuff. Let's hope it gets merged!

**Comment by renopp** [comment]
@soutua Thanks for the suggestion. Since applying this patch, and after releasing the app a couple of weeks ago, our journalists and users have stopped reporting the issue of text cutoff on the iOS platform. 🫡 

```
  CGFloat epsilon = 0.001;
  size = (CGSize){
      ceil((size.width + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
      ceil((size.height + epsilon) * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
```

**Comment by KestasVenslauskas** [comment]
> Yep, wanted to make sure that no one here is still able to reproduce the issue when using the patch, but I've now made a PR of it: [#54260](https://github.com/facebook/react-native/pull/54260)

https://github.com/facebook/react-native/pull/54510 Looks like PR got reverted, any reason for that?

**Comment by douglowder** [comment]
Hi @soutua @Kitcheone @renopp I was testing this out today and noticed that the bug only occurs if the `textDidWrap` value from the layoutManager code above is set to true. So instead of #54260 ,  I would propose a fix like this, where we adjust only the height when it appears that text is going to wrap. This definitely fixes the issue in the snack example here, using RN 0.81. Could you and others here try this out and see if the issue still repros after applying this patch?

```diff
diff --git a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
index 216bb23..28e616a 100644
--- a/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
+++ b/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
@@ -386,9 +386,13 @@ static NSLineBreakMode RCTNSLineBreakModeFromEllipsizeMode(EllipsizeMode ellipsi
     size.height = enumeratedLinesHeight;
   }
 
+  // If the text wraps, we want to add additional height
+  CGFloat additionalHeight = textDidWrap ? 1.0 : 0.0;
+
   size = (CGSize){
-      ceil(size.width * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
-      ceil(size.height * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor};
+    ceil(size.width * layoutContext.pointScaleFactor) / layoutContext.pointScaleFactor,
+    ceil(size.height * layoutContext.pointScaleFactor + additionalHeight) / layoutContext.pointScaleFactor
+  };
 
   __block auto attachments = TextMeasurement::Attachments{};
 
```

**Comment by soutua** [comment]
@douglowder Yes I think adding the `textDidWrap` condition makes sense, since the issue only happens with wrapping text. I couldn't reproduce the issue with the added condition at least in a brief testing. Small comment about the value `1.0`; in our testing the value in my PR `0.001` has been enough to fix the issue, just thinking that `1.0` might be so much that some sharp eyed users might actually see the added line height (since it might be multiple pixels depending on the pixel density).

On another matter, I saw that this PR in Yoga was linked to my PR: https://github.com/facebook/yoga/pull/1860
I didn't study the solution but it feels to me that the root cause is possibly in Yoga and that PR might actually fix the root of the issue, while my solution (or the solution in the old arch which was the same), is probably more of a band-aid.

**Comment by douglowder** [comment]
> Small comment about the value `1.0`; in our testing the value in my PR `0.001` has been enough to fix the issue, just thinking that `1.0` might be so much that some sharp eyed users might actually see the added line height (since it might be multiple pixels depending on the pixel density).

Good point -- the 1.0 should go outside the `ceil()` call. Thanks for catching that! And thanks very much for flagging the Yoga PR -- I do agree that it should be fixed there if possible.

**Comment by GrantMacgregor97** [comment]
I'm using react native 0.81.4 with Expo SDK 54. I have tried applying the patch with the CGFloat epsilon = 0.001; but this didn't resolve the issue. Has anyone got any other suggestions of things to try, specifically for expo projects? Does anyone know if this has been fixed in the more recent versions of React Native?

**Comment by Kitcheone** [comment]
@GrantMacgregor97 When you added the patch, did you also enable `buildReactNativeFromSource` in `app.json`? This is needed to make sure RN is built from source including your patch - otherwise Expo will use pre-built RN, which won't include your patch.

As far as I know, this hasn't been fixed in any versions of RN yet..

**Comment by GrantMacgregor97** [comment]
@Kitcheone That was the piece I was missing. The patch has now been applied successfully and i'm no longer seeing the bug. Thanks for taking the time to help.

For anyone else using Expo, it might need to be in your app.config.ts file that you add the `buildReactNativeFromSource` flag, using `expo-build-properties`

`[
        "expo-build-properties",
        {
          "ios": {
            "buildReactNativeFromSource": true
          }
        }
      ]`

**Comment by Daniel-Griffiths** [comment]
Any updates on this issue? This bug still exists as of the 16th June 2026.

I've had to re-apply all the patches in this thread to every app I work on 😅

**Comment by KestasVenslauskas** [comment]
> Any updates on this issue? This bug still exists as of the 16th June 2026.
> 
> I've had to re-apply all the patches in this thread to every app I work on 😅

Same 😁

**Comment by philipheinser** [comment]
Its still happens in rn 0.86 and the fix works

**Comment by fabriziocucci** [comment]
FYI folks, we are trying to land the fix again in #57698.

**Comment by Daniel-Griffiths** [comment]
Thanks @fabriziocucci!

**Comment by fabriziocucci** [comment]
Quick update: #57698 landed and so far the fix is holding. I'll keep monitoring things internally.

**Comment by iscordero** [comment]
We hit this same bug in a production app (Expo SDK 54, RN 0.81.5, new architecture) — first
observed in the wild on a physical device in TestFlight with completely different content and
styles (fontSize 14 / lineHeight 20, a Google Sans Flex variable font), then reproduced
deterministically with this issue's reproducer content inside our app on an iPhone 17 Pro
simulator (402pt logical width). Some findings that may help narrow it down:

**It is a draw-side divergence; measurement is correct.** `onTextLayout` reports the correct
line count (6 lines for the "This sentence is cut off." paragraph) on every mount, and Yoga
reserves the correct multi-line height — the paragraph's box is the right size, with the last
line's worth of space left empty. Only the draw is wrong: the final line is merged onto the
previous one and runs past the container edge with no ellipsis. This also means the bug is
invisible to JS-side detection.

**It is fully deterministic for a given (text, width, metrics, context).** Same content, same
styles, same FlatList: the same paragraph draws clipped on every fresh mount across repeated
app relaunches.

**A forced remount does not fix it.** Re-keying the `<Text>` 400ms after mount (new native
view, identical metrics) draws clipped again — it is not stale cached layout state.

**`lineBreakStrategyIOS` has no effect.** Both `"standard"` and `"push-out"` still clip.

**Any 1pt metric change dodges that instance.** Removing `lineHeight: 24`, or changing it to
25, makes this paragraph render correctly — presumably by moving the layout off whatever edge
condition triggers the bad path. This is why the bug looks "random" across content in real
apps: arbitrary (text × width × metrics) combinations land on it.

**Context matters.** The same paragraph at the same width in a plain ScrollView rendered
fine in our tests; inside the FlatList reproducer it clips.

Happy to provide more details from our runs if useful.
