### ISSUE TITLE
Horrible Memory usage in integrated dev environment

### ISSUE THREAD

**Issue by DickyT** [facebook/react-native#5475]
I am now using react native in a Swift project, most of my functions are written in react native, and some of my native function written in Swift and I bridge them to react native by Objective C. After I finish my whole project, I found a horrible thing is that the memory usage in my App is REALLY HORRIBLE.

Here is my screen shot of XCode. I tested on my latest iPod touch. The memory usage can easily goes over 600M in several minutes, even if you just open the App and not touching the device. After several minutes my app got terminated by system because of high memory usage.
![screen shot 2016-01-22 at 01 02 39](https://cloud.githubusercontent.com/assets/4535844/12502871/62b85a34-c0a4-11e5-9a1a-0e6d7876ef36.png)
![screen shot 2016-01-22 at 01 03 04](https://cloud.githubusercontent.com/assets/4535844/12502870/62b74a36-c0a4-11e5-974d-c611e0ed0352.png)

*I have think about if my application and JSX construction is not really good, but I try to boot my App with the code below, and the memory keep raising in a speed about 1M/s even I don't touch my device.*
![rnmemory](https://cloud.githubusercontent.com/assets/4535844/12502925/1b9dae14-c0a5-11e5-988c-f745659c43e1.gif)

```
'use strict';

import React from 'react-native';
var {
  Text,
  Component,
  } = React;

class Test extends Component {
  render() {
    return (
        <Text>Hello</Text>
    );
  }
}

React.AppRegistry.registerComponent('test', () => Test);
```
And when I removed the react native view controller and restart my App, nothing's gonna happen anymore.

I am wondering if the memory control is exist / enabled in integrated environment or how can I manually enable them?

**Comment by DickyT** [comment]
my version is react native 0.16 installed by cocoapods

**Comment by moooji** [comment]
I think those leaks in dev mode have been fixed in 0.17

**Comment by DickyT** [comment]
@moooji thanks i will try in 0.17!

**Comment by DickyT** [comment]
@moooji Thanks for guiding.
I just tried 0.17 and it still exists, but later I tried updating to 0.19rc, and this memory leak no longer happens!
