### ISSUE TITLE
Upload file "Network request failed" with FormData in 0.83.0

### ISSUE THREAD

**Issue by AlexCernik** [facebook/react-native#54881]
### Description

Hello, I currently do this in version 83.0 and I get the error `Network request failed`.

The image are
```javascript
{
  name: 'IMG-20251203-WA0008.jpg',
  type: 'image/jpeg',
  uri: 'content://...' or 'file://...
}
```

```javascript
const formData = new FormData(); 

formData.append('content', data.content); 
data.images.forEach((e, i) => formData.append('images', e));

const response = await fetch('url', { 
  method: 'POST', 
  body: formData, 
});
```

### Steps to reproduce

```javascript
const formData = new FormData(); 

formData.append('content', data.content); 
data.images.forEach((e, i) => formData.append('images', e));

const response = await fetch('url', { 
  method: 'POST', 
  body: formData, 
});
```

### React Native Version

0.83.0

### Affected Platforms

Runtime - Android

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (4) x64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
  Memory: 2.04 GB / 7.62 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 22.21.0
    path: /usr/bin/node
  Yarn: Not Found
  npm:
    version: 10.9.4
    path: /usr/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "34"
      - "35"
      - "36"
    Build Tools:
      - 33.0.0
      - 34.0.0
      - 35.0.0
      - 36.0.0
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.17
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 20.0.0
    wanted: 20.0.0
  react:
    installed: 19.2.0
    wanted: 19.2.0
  react-native:
    installed: 0.83.0
    wanted: 0.83.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
TypeError: Network request failed
    at anonymous (fetch.umd.js:567:31)
```

### MANDATORY Reproducer

https://github.com/AlexCernik/rn-formdata-reproducer

**Comment by rishad-mhd** [comment]
I’m also facing this issue on Android.
Works correctly on React Native 0.82.x, but fails on 0.83.x with Axios (Network Error) for multipart/form-data uploads.
iOS works perfectly on the same code.

**Comment by SameerAther** [comment]
I am also experiencing this issue on Android 16 with React Native 0.83.0. The same flow was working correctly on React Native 0.82.x. After upgrading to 0.83.0, the app crashes on Android when DevTools are connected and it shows Network Error when the DevTools are not connected. 
When DevTools are connected and the app crashes, further inspection using adb logcat shows the following as the root cause:

`E/IPCThreadState( 4544): Binder transaction failure. id: 79805106, BR_*: 29201, error: -28 (No space left on device)
E/JavaBinder( 4544): !!! FAILED BINDER TRANSACTION !!! (parcel size = 44766632)`

**Comment by NikhilMasurkar** [comment]
Im also facing the same issue on Android, please find the solution I thought I missed something but there are multiple user facing the same isseue

**Comment by AlexCernik** [comment]
> Im also facing the same issue on Android, please find the solution I thought I missed something but there are multiple user facing the same isseue 

I had to downgrade the version to 0.82.1 for it to work.

**Comment by Prajwaltechversant** [comment]
+1

**Comment by kdwkr** [comment]
This was broken by #54804. I temporarily fixed it using a patch.
```diff
diff --git a/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkEventUtil.kt b/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkEventUtil.kt
index c0ed0c965844ee2422d8feb4cb1b6f82d30353b1..94c991121565261571f28cfe454c1bf48d3c8453 100644
--- a/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkEventUtil.kt
+++ b/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkEventUtil.kt
@@ -35,8 +35,7 @@ internal object NetworkEventUtil {
           request.url().toString(),
           request.method(),
           headersMap,
-          (request.body() as? ProgressRequestBody)?.getBodyPreview()
-              ?: request.body()?.toString().orEmpty(),
+          request.body()?.toString().orEmpty(),
           request.body()?.contentLength() ?: 0,
       )
       InspectorNetworkReporter.reportConnectionTiming(devToolsRequestId, headersMap)
```

**Comment by huntie** [comment]
@kdwkr Thanks, let me verify this and look at shipping a patch release.

**Comment by dgreasi** [comment]
I am experiencing the same on `v0.83.0`. I was able to replicate with both `axios` and `fetch`.

For me, the fix that @kdwkr suggested didn't work. Downgrading to `0.82.1` worked for me

**Comment by nakshatrasinghh** [comment]
Facing the same here - https://github.com/facebook/react-native/issues/54796#issuecomment-3617560180

iOS works fine, but debugger does not log the network request on inspect. Android is not at all working.

Does someone have a temporary fix for this please?

**Comment by huntie** [comment]
@dgreasi Are you able to share a [repro](https://github.com/react-native-community/reproducer-react-native)? Want to check this gets thoroughly fixed for everyone.

Potentially @kdwkr's solution does work for you, but you may be using an Android prebuilt where patching the package source may not take effect.

**Comment by rishik-simplifix** [comment]
I have same issue with v0.82.1 as well

**Comment by NikhilMasurkar** [comment]
@huntie I am encountering this same issue on Android. The API call fails silently or results in a network error because the FormData is not being processed correctly (it appears the boundary/Content-Type headers are not being preserved or generated correctly during the native request).

I cannot provide a full repo at the moment, but here is the minimal code implementation that reproduces the failure. I am using axios (which relies on XMLHttpRequest) and react-native-documents/picker.

Environment:

React Native: 0.83.1 (Please verify this version number, usually it is 0.76.x etc)

Platform: Android

File URI Scheme: content://

```import React from 'react';
import { Button } from 'react-native';
import { pick, types } from '@react-native-documents/picker';
import axios from 'axios';

// 1. Setup Axios
const APIHandler = axios.create({
  baseURL: 'https://your-api-endpoint.com',
  timeout: 30000,
});

// 2. The Upload Function
const uploadImage = async () => {
  try {
    // Pick the file
    const [imageObj] = await pick({
      allowMultiSelection: false, 
      type: [types.images]
    });

    if (!imageObj) return;

    console.log('File Picked:', imageObj.uri);

    // Prepare FormData
    const postBody = new FormData();
    postBody.append('image', {
      uri: imageObj.uri, // content://...
      type: imageObj.type || 'image/jpeg',
      name: imageObj.name || 'upload.jpg',
    });

    // Validating headers before send
    // Note: We are NOT manually setting Content-Type here to let the browser/native layer handle the boundary.
    
    console.log('Sending request...');
    
    const response = await APIHandler.post('/upload-endpoint', postBody, {
      headers: {
        'Accept': 'application/json',
        // 'Content-Type': 'multipart/form-data', // Intentionally left out to allow boundary generation
      },
    });

    console.log('Success:', response.status);

  } catch (error) {
    console.error('Upload Failed:', error);
    if (error.response) {
      console.log('Server Response:', error.response.data);
    } else if (error.request) {
      console.log('Request made but no response received (Network/Native Error)');
    }
  }
};

const App = () => (
  <Button title="Upload Image" onPress={uploadImage} />
);

export default App;

**Comment by dgreasi** [comment]
@huntie It's probably also related with axios in a manner.

When using axios a form data request is failing in both `v0.83.0`, `v0.82.1`.

I switched to native fetch and now this is only occurring in `v0.83.0`.

Example:

```
export interface S3File {
  uri: string;
  name: string;
  type: string;
}

export interface UploadResult {
  success: true;
  data: unknown;
}

export interface UploadOptions {
  // optional custom headers to send (e.g. Authorization)
  headers?: Record<string, string>;
  // optional progress callback (0-100). When provided uses XHR to enable progress.
  onProgress?: (percent: number) => void;
  // name of the file field expected by the target endpoint (default 'file')
  fileFieldName?: string;
}

/**
 * Upload a file to an S3 presigned POST URL.
 * Returns a Promise resolving to UploadResult on success or throwing on failure.
 */
export async function uploadToS3(
  uploadUrl: string,
  file: S3File,
  fields: Record<string, string>, // Presigned POST fields returned by your server (policy, x-amz-*, key, acl, etc)
  options: UploadOptions = {},
): Promise<UploadResult> {
  const { headers = {}, onProgress, fileFieldName = 'file' } = options;

  // Build form data
  const formData = new FormData();
  if (fields) {
    Object.keys(fields).forEach((k) => {
      formData.append(k, String(fields[k]));
    });
  }

  // Normalize file object
  const fileForUpload: S3File = {
    uri: file.uri,
    name: file.name || 'file',
    type: file.type || 'application/octet-stream',
  };

  formData.append(fileFieldName, fileForUpload);

  // If caller provided onProgress use XHR to get progress events
  if (typeof onProgress === 'function') {
    return new Promise<UploadResult>((resolve, reject) => {
      try {
        const xhr = new XMLHttpRequest();
        xhr.open('POST', uploadUrl);

        // Set headers (safe to set Authorization, etc). Do NOT override multipart Content-Type.
        Object.keys(headers).forEach((h) => {
          // Some environments expect header names in original case; use as provided
          xhr.setRequestHeader(h, headers[h]);
        });

        xhr.onload = () => {
          // 2xx is success for S3 POST
          if (xhr.status >= 200 && xhr.status < 300) {
            resolve({ success: true, data: xhr.responseText });
          } else {
            const msg = `S3 upload failed with status ${xhr.status}: ${xhr.responseText || '<no body>'}`;
            reject(new Error(msg));
          }
        };

        xhr.onerror = () => {
          reject(new Error('Network error while uploading to S3'));
        };

        if (xhr.upload && typeof onProgress === 'function') {
          xhr.upload.onprogress = (evt: ProgressEvent) => {
            if (evt.lengthComputable) {
              const pct = Math.round((evt.loaded / evt.total) * 100);
              try {
                onProgress(pct);
              } catch {
                // swallow progress handler errors
              }
            }
          };
        }

        xhr.send(formData);
      } catch (err) {
        reject(err);
      }
    });
  }

  // Otherwise use fetch (simpler and often reliable). Pass headers (except Content-Type).
  // IMPORTANT: do not set 'Content-Type' header here if the runtime cannot compute boundary.
  const fetchHeaders: Record<string, string> = {};
  // Copy caller headers except content-type
  Object.keys(headers || {}).forEach((k) => {
    if (k.toLowerCase() === 'content-type') return;
    fetchHeaders[k] = headers[k];
  });

  const response = await fetch(uploadUrl, {
    method: 'POST',
    body: formData,
    headers: fetchHeaders,
  });

  if (!response.ok) {
    let text = '<unable to read response body>';
    try {
      text = await response.text();
    } catch {}
    throw new Error(`S3 upload failed with status ${response.status}: ${text}`);
  }

  const data = await response.text();
  return { success: true, data };
}
```

**Comment by hxzrx** [comment]
Same issue, React Native 0.83.0, upsloaded file by [ky](https://github.com/sindresorhus/ky).

**Comment by huntie** [comment]
Based on @AlexCernik's [original reproducer](https://github.com/AlexCernik/rn-formdata-reproducer), I'm pretty sure this is fixed.

| Before | After |
|--------|--------|
| <img width="2146" height="1063" alt="Image" src="https://github.com/user-attachments/assets/bdc2dc4e-7f66-4a1c-a951-dd1440d7c11e" /> | <img width="2249" height="1321" alt="Image" src="https://github.com/user-attachments/assets/91f6b9a4-85b6-4df1-97ba-1f3b552959c3" /> |

## Incoming

- Release 0.83.1 will come out today with this fix.
- For the time being, we will render `[Preview unavailable]` for all request payload previews on Android.

**Comment by kocaagasefa** [comment]
For anyone patching 0.83.0 and still seeing multipart uploads fail or DevTools showing real payloads: you must build React Native from source for the patch to take effect. 

The prebuilt Android AARs ignore your patched node_modules. Follow the “Build from Source” guide: 

https://reactnative.dev/contributing/how-to-build-from-source

After enabling source build (and cleaning/reinstalling), the [Preview unavailable] behavior applies and uploads no longer double-read the body.

**Comment by huntie** [comment]
### 0.83.1 is now out, please update 🙏🏻

https://github.com/facebook/react-native/releases/tag/v0.83.1

**Comment by GaelCO** [comment]
Thanks @huntie !
Version 0.83.1 fixes my FormData crash issue with Axios.

**Comment by nakshatrasinghh** [comment]
For some reason, I do not see the FormData request flowing in inside the "network inspector". The API call indeed happen, but does not show up on the network tab, what could be the issue? This is happening on both iOS and Android

**Comment by dgreasi** [comment]
> Thanks [@huntie](https://github.com/huntie) ! Version 0.83.1 fixes my FormData crash issue with Axios.

Same for me. It's working now

**Comment by nakshatrasinghh** [comment]
@dgreasi do you see the FormData requests flowing in on "network" tab?

**Comment by dgreasi** [comment]
@nakshatrasinghh 

I am using `Reactotron`. I can see the FormData requests there.

Keep in mind that I am using native `fetch` for FormData requests.

**Comment by jayashreepairalabs** [comment]
it is working in 0.83.1 version but svg file upload is not working it is showing same network error
