### ISSUE TITLE
bug: back handler stops working after re-foregrounding the app

### ISSUE THREAD

**Issue by Rexogamer** [facebook/react-native#54887]
### Description

back handlers seem to stop working after sending the app to the background - all back gestures (except in Modals) just close the app instead. see the video below for a clearer demonstration.

I'm using the Android 16 QPR2 beta (BP41.250916.015.A1) on a Pixel 8.

I can reproduce this using either the `@react-native-community/hooks` hook *or* the usage example in [the `BackHandler` docs](https://reactnative.dev/docs/backhandler). the hook works fine in React Native v0.80 (I assume because the target SDK was still 35?).

### Steps to reproduce

1. Start the app
2. Press the button at the top
3. Do a back gesture and observe that it respects the back handler
4. Do another one to go home
5. Re-open the app
6. Press the button at the top again
7. Do another back gesture and observe that it exits out of the app instead of respecting the back handler

### React Native Version

0.83.0

### Affected Platforms

Runtime - Android, Build - Linux

### Output of `npx @react-native-community/cli info`

```text
System:
  OS: Linux 6.17 Ubuntu 25.10 25.10 (Questing Quokka)
  CPU: (8) x64 Intel(R) Core(TM) Ultra 7 256V
  Memory: 4.46 GB / 14.72 GB
  Shell:
    version: 5.2.37
    path: /bin/bash
Binaries:
  Node:
    version: 24.5.0
    path: /home/rexo/.nvm/versions/node/v24.5.0/bin/node
  Yarn:
    version: 4.12.0
    path: /home/rexo/.nvm/versions/node/v24.5.0/bin/yarn
  npm:
    version: 11.5.1
    path: /home/rexo/.nvm/versions/node/v24.5.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "31"
      - "35"
      - "36"
    Build Tools:
      - 34.0.0
      - 35.0.0
      - 35.0.1
      - 36.0.0
    System Images:
      - android-35 | Google APIs Intel x86_64 Atom
      - android-35 | Google Play Intel x86_64 Atom
      - android-36 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.17
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 20.0.0
    wanted: 20.0.0
  react:
    installed: 19.2.0
    wanted: 19.2.0
  react-native:
    installed: 0.83.0
    wanted: 0.83.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
N/A
```

### MANDATORY Reproducer

https://github.com/Rexogamer/backhandler-test

### Screenshots and Videos

https://github.com/user-attachments/assets/a48256a0-d956-446d-b5da-1ceccc824d91

**Comment by anferrat** [comment]
I observe same issue on Android emulator API 36, react-native version 0.81.0

**Comment by illestomas** [comment]
im experiencing the same issue, react-native 0.83.1, Xiaomi Redmi note 13

**Comment by anferrat** [comment]
> im experiencing the same issue, react-native 0.83.1, Xiaomi Redmi note 13

The issue should be fixed in react-native 0.83.2 or 0.84.0

**Comment by illestomas** [comment]
@anferrat have you tried if 0.83.2 fixes the issue ?

**Comment by simarmol** [comment]
I'm not the original poster, but I'm on `0.83.4` and I'm still seeing this issue. Weirdly, we have not been able to reproduce it on Pixel devices but it is still happening on other ones.

I've gotten reports that it's no longer happening on:
- Pixel 10 Pro XL
- Pixel 5

But still happening on
- Galaxy Tab S10 Plus
- Samsung S26 Ultra
- Samsung S25 Ultra
- Samsung S24
- Samsung Galaxy S22

**Comment by anferrat** [comment]
> [@anferrat](https://github.com/anferrat) have you tried if 0.83.2 fixes the issue ?

> I'm not the original poster, but I'm on `0.83.4` and I'm still seeing this issue. Weirdly, we have not been able to reproduce it on Pixel devices but it is still happening on other ones.
> 
> I've gotten reports that it's no longer happening on

I was wrong earlier; the fix was introduced only in 0.84.0 - [changelog](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#:~:text=BackHandler%3A%20Fix%20BackHandler%20callbacks%20not%20working%20after%20app%20resume%20on%20API%2036%2B%20(fef5b84996%20by%20%40anferrat)). I haven't had chance to try it out in the release version though. 0.83.x will still have this bug (Also it seems to only affect Android API 36+)

**Comment by marcshilling** [comment]
Are we sure the fix isn't in [0.86](https://reactnative.dev/blog/2026/06/11/react-native-0.86#:~:text=BackHandler%20resume%20fix%20on%20API%2036%2B%3A%20BackHandler%20callbacks%20stopped%20working%20after%20the%20app%20was%20resumed%20from%20the%20background%20on%20Android%20API%2036%2B.%20The%20fix%20ensures%20the%20back%20button%20handler%20is%20properly%20re%2Dregistered%20during%20onHostResume.)? 

Anyway, I was able to fix this in 0.83.9 by adding this to `MainActivity.kt`:
```
override fun invokeDefaultOnBackPressed() {
    moveTaskToBack(true)
}
```
