### ISSUE TITLE
[android] RCTNetworking.sendRequest got 7 arguments, expected 6

### ISSUE THREAD

**Issue by TangSirOnGit** [facebook/react-native#5658]
![device-2016-02-01-153614](https://cloud.githubusercontent.com/assets/10524715/12711302/cb0aee96-c8f9-11e5-8ce6-233e69dbede7.png)

I Got this error when practising [
Integrating with Existing Apps](http://facebook.github.io/react-native/docs/embedded-app-android.html#content) . Any ideas what it can be?

thanks a lot

**Comment by TangSirOnGit** [comment]
fixed by changing react-native to 0.19.0

compile 'com.facebook.react:react-native:0.19.0'

**Comment by cubbuk** [comment]
I got the same error, thanks @TangSirOnGit for the solution.

**Comment by awitherow** [comment]
@TangSirOnGit how are you running this compile 'com.facebook.react:react-native:0.19.0'?

**Comment by cubbuk** [comment]
@awitherow you need to update build.gradle file. That should reside under android/app/build directory. You need to change the dependencies section in that file for react-native line. This should be probably fixed in the main repo too.

**Comment by danielweinmann** [comment]
Thanks, @TangSirOnGit :D

**Comment by alvaromb** [comment]
I'm still getting this error, and I have 
```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:0.19.+"
}
```
under ``build.gradle`` file.

**Comment by kapv89** [comment]
Facing the same problem. setting react-native version to 0.19.0 fixed the problem once, but enabling hot module replacement did it in again

**Comment by alvaromb** [comment]
How do you disable hot module replacement, @kapv89 ?

**Comment by kapv89** [comment]
In the emulator, F2, clicked on the option

**Comment by awitherow** [comment]
I was only getting this error when trying to use the react-native-webpack-server. Never had it without.

**Comment by alvaromb** [comment]
Ok, I reinstalled dependencies and then I ran into this other issue: https://github.com/facebook/react-native/issues/5655#issuecomment-178896957
