### ISSUE TITLE
Incorrect visual initialization of transform scale 0

### ISSUE THREAD

**Issue by Cryszon** [facebook/react-native#6278]
Initializing a component with `transform: [{scale: 0}]` visually initializes it as `transfrom: [{scale: 1}]`. However, when animating the component it animates as if the initial value was actually `0`. Using a float (`0.0`) doesn't work either.

The example code below demonstrates this problem. Tested on Android using React Native 0.21.

Initially pressing "Animate to 0" doesn't animate the first box at all because its "real" scale is 0. Pressing the other two texts makes it jump to 0 and animate to x from there.

The example also shows how normal components look visually identical when given scales of 0 and 1.

```
import React, {
  Animated,
  Component,
  StyleSheet,
  Text,
  View,
} from "react-native";

export default class TransformExample extends Component {
  constructor() {
    super(arguments[0]);
    this.state = {
      value1: new Animated.Value(0),
      value2: new Animated.Value(0.5),
      value3: new Animated.Value(1),
    }
  }

  animateTo(val) {
    Animated.spring(this.state.value1, {toValue: val}).start();
    Animated.spring(this.state.value2, {toValue: val}).start();
    Animated.spring(this.state.value3, {toValue: val}).start();
  };

  render() {
    const boxStyle = {
      width: 150,
      height: 50,
      backgroundColor: "#3fc6ae",
      margin: 10,
    }

    return (
      <View style={{alignItems: "center"}}>
        <Text onPress={() => this.animateTo(0)}>Animate to 0</Text>
        <Text onPress={() => this.animateTo(1)}>Animate to 1</Text>
        <Text onPress={() => this.animateTo(1.2)}>Animate to 1.2</Text>

        <Animated.Text style={[
          boxStyle,
          {transform: [{scale: this.state.value1}]}
        ]}>
          Initial scale: 0
        </Animated.Text>

        <Animated.Text style={[
          boxStyle,
          {transform: [{scale: this.state.value2}]}
        ]}>
          Initial scale: 0.5
        </Animated.Text>

        <Animated.Text style={[
          boxStyle,
          {transform: [{scale: this.state.value3}]}
        ]}>
          Initial scale: 1
        </Animated.Text>

        <Text style={[
          boxStyle,
          {transform: [{scale: 0}]}
        ]}>
          Fixed scale: 0
        </Text>

        <Text style={[
          boxStyle,
          {transform: [{scale: 1}]}
        ]}>
          Fixed scale: 1
        </Text>
      </View>
    )
  }
}
```

**Comment by brentvatne** [comment]
@facebook-github-bot label Android

**Comment by brentvatne** [comment]
This works as expected on iOS, but indeed appears to be broken on Android.

#### iOS

<img width="242" alt="screen shot 2016-03-06 at 3 06 34 pm"  style="display: inline-block" src="https://cloud.githubusercontent.com/assets/90494/13557929/148b821a-e3ad-11e5-996a-dd4927227ef8.png">


#### Android

<img width="270" alt="screen shot 2016-03-06 at 3 06 15 pm" style="display: inline-block" src="https://cloud.githubusercontent.com/assets/90494/13557927/0e624338-e3ad-11e5-8285-fef67333b177.png">
See: https://rnplay.org/apps/-NwWMw

**Comment by grabbou** [comment]
Also, same for height: 0 to height: 40 animation on Android, works normally on iOS. See http://stackoverflow.com/questions/35926051/why-does-rn-animated-timing-tovalue-of-0-not-animate for reference.

**Comment by 9mm** [comment]
Have you found any workarounds? Setting it to `0.01` is the only thing I can find.

**Comment by grabbou** [comment]
The issue might lay somewhere deeper - height: 0 on a `<View />` also does not seem to work.

**Comment by m3vaz** [comment]
This was a problem as of 0.30, but appears to have been fixed as of 0.31.

@Cryszon can you confirm 0.31 fixes your issue?

**Comment by m3vaz** [comment]
Setting scale to 0 seems to strip the component of other applied styles/transforms.
Modifying the original example:

```
import React, { Component } from 'react';
import {
  Animated,
  Easing,
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class TransformExample extends Component {
  constructor() {
    super(arguments[0]);
    this.state = {
      value1: new Animated.Value(0),
      value2: new Animated.Value(0.5),
      value3: new Animated.Value(1),
    }
  }

  animateTo(val) {
    Animated.timing(this.state.value1, {fromValue: 0, toValue: val, easing: Easing.linear}).start();
    Animated.timing(this.state.value2, {toValue: val}).start();
    Animated.timing(this.state.value3, {toValue: val}).start();
  };

  render() {
    const boxStyle = {
      width: 150,
      height: 50,
      backgroundColor: "#3fc6ae",
      margin: 10,
    }

    return (
      <View style={{alignItems: "center"}}>
        <Text onPress={() => this.animateTo(0)}>Animate to 0</Text>
        <Text onPress={() => this.animateTo(1)}>Animate to 1</Text>
        <Text onPress={() => this.animateTo(1.2)}>Animate to 1.2</Text>

        <Animated.Text style={[
          boxStyle,
          {transform: [{scale: this.state.value1}]}
        ]}>
          Initial scale: 0
        </Animated.Text>

        <Animated.Text style={[
          boxStyle,
          {transform: [{scale: this.state.value2}]}
        ]}>
          Initial scale: 0.5
        </Animated.Text>

        <Animated.Text style={[
          boxStyle,
          {transform: [{scale: this.state.value3}]}
        ]}>
          Initial scale: 1
        </Animated.Text>

        <Text style={[
          boxStyle,
          {transform: [{scale: 0}, {translateX: -50}, {rotate: '90deg'}]}
        ]}>
          Fixed scale: 0
        </Text>

        <Text style={[
          boxStyle,
          {transform: [{scale: 1}, {translateX: -50}, {rotate:'90deg'}]}
        ]}>
          Fixed scale: 1
        </Text>
      </View>
    )
  }
}
```

**Comment by LeoBakerHytch** [comment]
Still an issue as of 0.35. Using an initial value of `0.005` seems to work ¯\_(ツ)_/¯

**Comment by funkysoul** [comment]
I'm experiencing a similar issue, bit different though.
I have an Image which I want to scale from 1 to 0 using an interpolation value on  transform:[{scale:value}].

The scale animation runs through but as soon as it hits 0 the image is fully scaled again (back to scale: 1) 

But setting the end value (0) to 0.0001 works fine.

This happens to me on Android and iOS with RN 0.40

**Comment by bsonntag** [comment]
Here is another example that doesn't even use `Animated`:

https://rnplay.org/apps/4O316Q

When a node has a scale set to 0, it seems to use it's last sibling's scale value.
As other people said, using values close to zero (e.g. 0.001), works fine.

Running the above example in the emulators has the same result:

**iOS** on the left, **Android** on the right:

![ios-screenshot](https://cloud.githubusercontent.com/assets/6205451/22737202/f37e241c-edf9-11e6-8461-3560a3167a70.png)  ![android-screenshot](https://cloud.githubusercontent.com/assets/6205451/22737101/77b3e4ac-edf9-11e6-937e-6c623d2d1951.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/incorrect-visual-initialization-of-transform-scale-0

**Comment by dantman** [comment]
It's been inactive because no-one has fixed it, the issue hasn't gone away! This is a big error that results from something simple and straightforward being done. Closing it makes no sense.

**Comment by hramos** [comment]
Would you like to volunteer and provide a fix?

**Comment by dantman** [comment]
How am I supposed to fix it? I have no clue where React Native implements low level transform style handling or how to debug it.

This is a bug that needs someone well versed in React Native's internals to fix.

**Comment by CusProjects** [comment]
Thanks @9mm, your solution worked as we expected, but we still don't know why this is happening as it.

**Comment by peterjuras** [comment]
Still an issue with react-native v0.49.3.

I think the issue should be reopened.

**Comment by hramos** [comment]
Instead of re-opening, I recommend filing a new issue and filling out the template.

**Comment by brentvatne** [comment]
> Instead of re-opening, I recommend filing a new issue and filling out the template.

:+1:
