### ISSUE TITLE
Image display black block，and crashed after scroll

### ISSUE THREAD

**Issue by aqlu** [facebook/react-native#6556]
I'm  using react-native version 0.20.0，some android phone display image with black block，when scroll the view, the image display can change，and app crashed when repeated scroll.

Here is a screenshots：
![1](http://ww4.sinaimg.cn/large/44608603gw1f24kd6cz8pg206r0c0qv5.gif)
![2](http://ww3.sinaimg.cn/large/44608603gw1f24k7x0ai1g206r0c0u0x.gif)
![3](http://ww3.sinaimg.cn/large/44608603gw1f24k6ipf9og206r0c0qv5.gif)

**Comment by hufeng** [comment]
+1 we met the some problem.

**Comment by karthickvkumar** [comment]
+1 I met this problem

**Comment by jingpeicomp** [comment]
+1 It make trouble for me too.

**Comment by LzxHahaha** [comment]
+1 I met this problem, version 0.25

**Comment by lacker** [comment]
I think this has been fixed.

**Comment by farzadab** [comment]
I think the problem is not completely fixed. I also encountered this problem (on **Android**), the profile picture loads at first, but then turns black and the application crashes if I don't change the screen (e.g. press back).

Here's a screenshot:
![image-darken-crash](https://cloud.githubusercontent.com/assets/5062458/23988175/57a7d8b6-0a42-11e7-8824-f9c04fd972d4.gif)

-------------
Versions:
react: 15.4.2
react-native: 0.41.2
react-native-cli: 2.0.1

Devices:
Sony C6603, android version: 5.1.1 (the one in the screenshot)
LG-D618, android version: 5.0.2

**Comment by bltnico** [comment]
I have fixed this problem when i have removed image border like `borderWidth: 1` and `borderColor: #000`

**Comment by boplennon** [comment]
Im sufferring from the same isue and the quick hack from @bltnico works.

RN version: 0.46.4

**Comment by MasterDaveh** [comment]
@bltnico I had a similar experience. I have borderRadius set on the Image component itself. If I set it on the wrapper view, with `overflow:'hidden'`, the app is not crashing nor the images gets black but they get weirdly cropped. 
![screenshot_2018-02-07-07-07-03-1](https://user-images.githubusercontent.com/16387187/35901365-8645499c-0bd6-11e8-841a-c47839e5e0c1.png)
This problem disappears if I take out the borderRadius completely. But I can't do it, I need it in the UI. 

RN 0.51.0

**Comment by nppull** [comment]
Same problem, Android 5.1 `<Image> - borderRadius`
