### ISSUE TITLE
Here is a rendering errors in 6p/6sp.

### ISSUE THREAD

**Issue by fakefish** [facebook/react-native#6951]
here is in iphone 6
![image](https://cloud.githubusercontent.com/assets/1334025/14482035/d3e26acc-016a-11e6-9242-f6c24b845e03.png)
and the same code in iphone 6plus
![image](https://cloud.githubusercontent.com/assets/1334025/14482038/dace1bec-016a-11e6-8863-c5ac90c0ec49.png)

both in simulator and real device, the code is just `ListView` with some `View`s and `Text`s.

and the react-native version is 0.22
here is my app [https://itunes.apple.com/us/app/qi-wu-zhou-kan/id1089804570?mt=8](https://itunes.apple.com/us/app/qi-wu-zhou-kan/id1089804570?mt=8)

the parent component is a `ListView`

```
// render return:
render() {
  <ListView
        style={[
          styles.container,
          styles.weeklyContentWraper,
          this.state.type == 'detail' ? {marginBottom: 0}:null]}
        dataSource={this.state.dataSource}
        renderRow={this._renderRow.bind(this)}
        renderHeader={()=>{
          return <Text style={{position:'absolute',top:0}}></Text>;
        }}
      />
}
var styles = StyleSheet.create({
  container: {
    marginBottom: 30,
    backgroundColor:'#fafafa'
  },
  weeklyContentWraper: {
    marginTop: -1,
  },
})
```

and  the list item is 
```
render() {
    return (
      <View key={this.state.topic} style={styles.weeklyWraper}>
        <Text style={styles.weeklyTopic}>{this.state.topic}</Text>
        {this.state.list.map((item) => {
          return <WeeklyItem {...item} key={item.title} {...this.props}/>
        })}
      </View>
    )
  }
var styles = StyleSheet.create({
  weeklyWraper: {
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    marginBottom: 18,
    paddingVertical:10,
  },
  weeklyTopic: {
    height: 30,
    backgroundColor: '#649F0C',
    color: '#fff',
    lineHeight: 22,
    paddingLeft: 15,
    width: 150,
  },
})
```

and weeklyItem is : 
```
render() {
    return (
      <View style={styles.container}>
        <View style={styles.topMenu}>
          {this.props.provider != '' ? 
            <Text style={styles.recommend}>{this.props.provider}推荐</Text>:
            <Text style={styles.recommend}>主编推荐</Text>}
        </View>
        <TouchableOpacity
          onPress={()=>{
            this._jumpPage(this.props)
          }}
          style={styles.titleWrapper}>
          <Text style={styles.title}>{this.props.title}</Text>
          <Text style={styles.description}>{this.props.description}</Text>
        </TouchableOpacity>
        <View style={styles.tagList}>
          {this.props.tags.map((tag)=>{
            return <Text style={styles.tagText} key={tag}>{tag}</Text>
          })}
        </View>
      </View>
    )
  }
var styles = StyleSheet.create({
  container: {
    paddingHorizontal: 15,
    marginTop: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold'
  },
  titleWrapper: {
    marginTop: 10,
  },
  recommend: {
    fontSize: 10,
    color: '#ccc',
  },
  topMenu: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  btn: {
    fontSize: 10
  },
  description: {
    color: '#666',
    marginTop: 10,
  },
  tagList: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  tagText: {
    marginTop: 10,
    color: '#999',
    marginRight: 10
  }
})
```

**Comment by dsibiski** [comment]
Can you post a snippet of the relevant code and a more descriptive summary of what the problem is?

**Comment by satya164** [comment]
What's the error?

**Comment by shahankit** [comment]
I don't is this @fakefish 's error. But I'm also facing similar issue of rendering in iphone 6s/6sp where the margins of cell inside listview are shown with overlapping light gray color.
![simulator screen shot 17-apr-2016 6 45 26 am](https://cloud.githubusercontent.com/assets/4739743/14584534/6d72209c-0468-11e6-9333-02e52ba9682f.png)

**Comment by fakefish** [comment]
@satya164 the background color is missing somewhere.

**Comment by saleeh93** [comment]
any updates

**Comment by viix** [comment]
borderTopWidth: 0.5,
borderBottomWidth: 0.5,

possibly problem exists here

we solve it by using StyleSheet.hairlineWidth

**Comment by fakefish** [comment]
thinks @viix ,I will try this way

**Comment by lacker** [comment]
It sounds like this issue is resolved so I am going to close it.

**Comment by hubciorz** [comment]
@lacker 
I think the problem still exists. `StyleSheet.hairlineWidth` solves that, right, but `borderTopWidth: 0.5` on iPhone 6/6s Plus should rather render nothing as a border than break the layout. Don't use think?

borderTopWidth: 0.5
![image](https://cloud.githubusercontent.com/assets/6502822/23074430/fd0e128a-f538-11e6-9a33-1cb2bf8dd264.png)

borderTopWidth: StyleSheet.hairlineWidth
![image](https://cloud.githubusercontent.com/assets/6502822/23074470/195704e2-f539-11e6-8fdc-48244acef3c2.png)
