### ISSUE TITLE
UIExplorer red-box run error "No script URL provided" ?

### ISSUE THREAD

**Issue by esutton** [facebook/react-native#7705]
Following the [UIExplorer README.md](https://github.com/facebook/react-native/tree/master/Examples/UIExplorer):
```
git clone https://github.com/facebook/react-native.git
cd react-native
npm install
Open Examples/UIExplorer/UIExplorer.xcodeproj in Xcode
Hit the Run button
```

The Examples/Movies/ still runs fine

react-native 26
XCode 7.3

**Comment by esutton** [comment]
Work-around is to comment-out the following lines in AppDelegate.m to prevent it from setting sourceURL = nil

//  if (!getenv("CI_USE_PACKAGER")) {
//     sourceURL = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
//  }

The Movies example works fine.

The Movies example does not have this line checking for CI_USE_PACKAGER environment variable.

**Comment by esutton** [comment]
This change broke running of **UIExplorer** example.

https://github.com/facebook/react-native/commit/913b4ccee492780ae180657094c261805455deea

**Comment by nathanajah** [comment]
Should be fixed with 18d6d8

**Comment by wan54** [comment]
Still not completely fixed.
Worked the first time I ran UIExplorer on the phone, but not subsequently. No problems running on the simulator.
