### ISSUE TITLE
<Modal /> doesn't handle screen sizes and orientations properly

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#7708]
So today I was trying to refactor my code to migrate from a custom imperative `Modal` API to React Native's `<Modal />` and found some issues which made me write my own component in JS instead.
- [x] Modal's height doesn't include the statusbar, so when the app has a translucent statusbar, Modal is drawn under the statusbar and there's empty space left at the bottom
- [x] Modal is not responsive to orientation, even if the device is in landscape mode, Modal is drawn according to potrait mode, so it kinda covers half the screen and the bottom part gets hidden
- [ ] It would be nice if the native Modal could respond to screen size and orientation change like a JS based Modal does
- [ ] With the slide animation, the animating Modal has a strip at the top which resembles the statusbar for some reason

**Comment by sreejith-driveu** [comment]
Which version of RN are you running? I tested `Modal` in RN `0.26.21` with React `15.0.2` and the orientation worked fine.

**Comment by sreejithr** [comment]
Which version of RN are you running? I tested Modal in RN 0.26.21 with React 15.0.2 and the orientation worked fine.

**Comment by satya164** [comment]
@sreejithr Pretty sure I saw this on 0.26.x.

**Comment by satya164** [comment]
Related https://github.com/facebook/react-native/issues/7893

**Comment by lulutia** [comment]
The same problem, Modal is not responsive to orientation on RN 0.26.2 on Android system. However, it's perfect on iOS.

**Comment by sreejithr** [comment]
@satya164 Sorry, that was a false alarm. It is, indeed, broken in 0.26. I was fooling around in the codebase. So, after a change in orientation to landscape, I followed the execution from `UIImplementation.java:updateRootNodeSize()` (which gets called because of the `setOnSizeChangedListener`) to `NativeViewHierarchyOptimizer:applyLayoutRecursive()`.

There, I'm seeing that for the `ReactTextShadowNode` inside my Modal, **`getScreenWidth()` gives the old width (portrait).** I understand that `CSSNode:calculateLayout()` on the root node updates the layout information. Shouldn't it update the dimensions of this text node as well?

Here's the markup I rendered code:
```
      <View style={styles.container}>
        <Modal visible={this.state.modalVisible}
         onRequestClose={e => this._setModalVisible(false)}>
          <Text style={{backgroundColor: "red"}}>Inside Modal</Text>
        </Modal>
        <TouchableHighlight
         onPress={e => this.setState({modalVisible: true})}>
          <Text>Show</Text>
        </TouchableHighlight>
      </View>
```
Sorry for the clarification. I'm new to the codebase. Please do let me know if my assumptions are wrong.

**Comment by sreejithr** [comment]
Also, I'd like to work on this issue if it wasn't apparent already :)

**Comment by satya164** [comment]
Sorry, I'm not very familiar with Modal's code. May be @dmmiller can help.

**Comment by dmmiller** [comment]
Modal definitely isn't resizing properly in rotation.  I'm aware of that but haven't had a chance to fix it.  If @sreejithr wants to look at it, that would be awesome.  Unfortunately I'm a little stuck on some other things currently.  I will probably get back to Modal stuff next week.

**Comment by ekryski** [comment]
@corymsith and I have also noticed this. We're crunching through a deadline as well but may be able to help out with this.

**Comment by esamelson** [comment]
Any updates on the status of this? I'm still seeing this issue on Android with RN 0.30.

**Comment by gelobelo02** [comment]
Any updates on this also?

**Comment by 7mllm7** [comment]
Urgently needed, any updates? Or workarounds anyone???

**Comment by esamelson** [comment]
I finally just gave up and replaced my `<Modal />` component with a View with the following style:
```
<View style={position: 'absolute',
  flex: 1,
  top: 0,
  right: 0,
  bottom: 0,
  left: 0,
} />
```
with a `<ScrollView />` inside. This actually worked quite nicely for displaying the Modal, and resizes properly upon orientation. However, I had to implement the Android back button functionality manually (using `BackAndroid`) and the entry animations, for which I used [react-motion](https://github.com/chenglou/react-motion). Not an ideal solution, but it works.

**Comment by CapitanRedBeard** [comment]
Are we working on this for 32?

**Comment by satya164** [comment]
Nobody is working on this. Feel free to take this up if you want.

**Comment by peter4k** [comment]
Is this fixed in 4.36?

**Comment by sharnik** [comment]
Looks like it's fixed on master. Close?

**Comment by jrodiger** [comment]
Tested on 0.36, android is working, but the issue still exists on iOS

**Comment by saigrandhi** [comment]
This bug exists in iOS as well. Tested it on 0.36 and 0.37

**Comment by sckoh** [comment]
still not working on iOS

**Comment by sreejithr** [comment]
> Modal is not responsive to orientation, even if the device is in landscape mode, Modal is drawn according to potrait mode, so it kinda covers half the screen and the bottom part gets hidden

I think this is fixed in Android as of `0.37.0`.

**Comment by fcFn** [comment]
The bug is still there on Android/RN 0.41.

**Comment by mchandleraz** [comment]
@fcFn I just created a new app with `react-native init --version="0.41.0" ReactNativeIssue7708`, and then implemented a Modal as shown in [the docs](https://facebook.github.io/react-native/docs/modal.html). Everything seemed to be working fine.

**Comment by fcFn** [comment]
It does work fine. I just wasn't handling the orientation change. Silly me. :sweat:

**Comment by markusguenther** [comment]
I used Modal in version 0.40 ad now 0.42 and everything works fine on iOS and android. So I can not reproduce this behavior.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/modal--doesnt-handle-screen-sizes-and-orientations-properly

**Comment by pvinis** [comment]
this should help https://github.com/facebook/react-native/pull/15102

**Comment by Morriz** [comment]
OMG, I just wasted some hours trying to figure out why the incoming dimensions were flipping like mad. Only to find here that I had to add `supportedOrientations={['portrait', 'landscape']}` to my `Modal` ??? Why is that not default?

**Comment by pvinis** [comment]
heh i guess it was just overlooked. i hope my pr above will be merged soon.

**Comment by Morriz** [comment]
yah, please :)
