### ISSUE TITLE
BUILD FAILED due to cxxreact module not found.

### ISSUE THREAD

**Issue by naveensingh-daffodil** [facebook/react-native#7911]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:ReactAndroid:compileLint
:ReactAndroid:copyReleaseLint UP-TO-DATE
:ReactAndroid:preBuild UP-TO-DATE
:ReactAndroid:preReleaseBuild UP-TO-DATE
:ReactAndroid:checkReleaseManifest
:ReactAndroid:preDebugAndroidTestBuild UP-TO-DATE
:ReactAndroid:preDebugBuild UP-TO-DATE
:ReactAndroid:preDebugUnitTestBuild UP-TO-DATE
:ReactAndroid:preReleaseUnitTestBuild UP-TO-DATE
:ReactAndroid:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:ReactAndroid:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:ReactAndroid:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:ReactAndroid:prepareComFacebookFrescoDrawee0100Library UP-TO-DATE
:ReactAndroid:prepareComFacebookFrescoFbcore0100Library UP-TO-DATE
:ReactAndroid:prepareComFacebookFrescoFresco0100Library UP-TO-DATE
:ReactAndroid:prepareComFacebookFrescoImagepipeline0100Library UP-TO-DATE
:ReactAndroid:prepareComFacebookFrescoImagepipelineBase0100Library UP-TO-DATE
:ReactAndroid:prepareComFacebookFrescoImagepipelineOkhttp30100Library UP-TO-DATE
:ReactAndroid:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:ReactAndroid:prepareReleaseDependencies
:ReactAndroid:compileReleaseAidl UP-TO-DATE
:ReactAndroid:compileReleaseRenderscript UP-TO-DATE
:ReactAndroid:generateReleaseBuildConfig UP-TO-DATE
:ReactAndroid:generateReleaseAssets UP-TO-DATE
:ReactAndroid:mergeReleaseAssets UP-TO-DATE
:ReactAndroid:generateReleaseResValues UP-TO-DATE
:ReactAndroid:generateReleaseResources UP-TO-DATE
:ReactAndroid:mergeReleaseResources UP-TO-DATE
:ReactAndroid:processReleaseManifest UP-TO-DATE
:ReactAndroid:processReleaseResources UP-TO-DATE
:ReactAndroid:generateReleaseSources UP-TO-DATE
:ReactAndroid:createNativeDepsDirectories UP-TO-DATE
:ReactAndroid:downloadBoost UP-TO-DATE
:ReactAndroid:prepareBoost UP-TO-DATE
:ReactAndroid:downloadDoubleConversion UP-TO-DATE
:ReactAndroid:prepareDoubleConversion UP-TO-DATE
:ReactAndroid:downloadFolly UP-TO-DATE
:ReactAndroid:prepareFolly UP-TO-DATE
:ReactAndroid:downloadGlog UP-TO-DATE
:ReactAndroid:prepareGlog UP-TO-DATE
:ReactAndroid:downloadJSCHeaders UP-TO-DATE
:ReactAndroid:prepareJSC
:ReactAndroid:buildReactNdkLib
Android NDK: WARNING: Ignoring unknown import directory: /home/bhola/naveen/projects/demoPro/node_modules/react-native/ReactAndroid/../ReactCommon    
Android NDK: Android.mk: Cannot find module with tag 'cxxreact' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make: Entering directory `/home/bhola/naveen/projects/demoPro/node_modules/react-native/ReactAndroid/src/main/jni/xreact/jni'
make: Leaving directory `/home/bhola/naveen/projects/demoPro/node_modules/react-native/ReactAndroid/src/main/jni/xreact/jni'
Android.mk:36: *** Android NDK: Aborting.    .  Stop.
:ReactAndroid:buildReactNdkLib FAILED
Error:Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command '/home/bhola/android-ndk-r10e/ndk-build'' finished with non-zero exit value 2

**Comment by naveensingh-daffodil** [comment]
I am stuck very badly at this point. Help me out.

**Comment by basketofsoftkittens** [comment]
i am having a similar issue. i am using android-ndk-r10e and have the `$ANDROID_NDK` path set in `.bash_profile`,`locale.properties` and in android studio -> Preferences -> Path Variables

**Comment by satya164** [comment]
It should be fixed now. Also try clearing your build folder before building.

**Comment by naveensingh-daffodil** [comment]
it fixed.

**Comment by konark-hike** [comment]
Am still facing this issue, @satya164 @naveensingh-daffodil Can you please explain what was the issue and what are the steps required to resolve this

**Comment by satya164** [comment]
@konark-hike it was an issue in RN's build configuration which was fixed.

**Comment by naveensingh-daffodil** [comment]
@konark-hike what version of RN your are using....

**Comment by konark-hike** [comment]
@satya164  @naveensingh-daffodil  Am building React from source and am on master branch.
Error i am facing now :

Android NDK: /mnt/jenkins_jobs/jobs/dev_react/workspace/node_modules/react/ReactAndroid/src/main/jni/first-party/fb/Android.mk: Cannot find module with tag 'folly' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make: Entering directory `/mnt/jenkins_jobs/jobs/dev_react/workspace/node_modules/react/ReactAndroid/src/main/jni/react/jni'
make: Leaving directory `/mnt/jenkins_jobs/jobs/dev_react/workspace/node_modules/react/ReactAndroid/src/main/jni/react/jni'
/mnt/jenkins_jobs/jobs/dev_react/workspace/node_modules/react/ReactAndroid/../ReactCommon/cxxreact/Android.mk:42: *** Android NDK: Aborting.    .  Stop.
All input files are considered out-of-date for incremental task ':cardview:mergeReleaseShaders'.
Unable do incremental execution: full task run
:ReactAndroid:cleanReactNdkLib FAILED

Am badly stuck on this one, Can someone please a guide a solution for this

**Comment by musicode** [comment]
* version: 0.48.3
* os: ios

![image](https://user-images.githubusercontent.com/2732303/30312834-cea6aff0-97cd-11e7-8563-6b3b6c3e779a.png)

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/30312930-2267540a-97ce-11e7-9654-5b069d69f925.png)

**Comment by musicode** [comment]
0.48.x is so hard to upgrade.
