### ISSUE TITLE
uglify-js 2.6.3 breaks 0.25.1 bundle (and maybe future versions)?

### ISSUE THREAD

**Issue by LeBlaaanc** [facebook/react-native#8259]
The recent update to uglify-js (2.6.3) seems to cause the following error when running `react-native bundle ios --entry-file index.ios.js --bundle-output ./foo.bundle --dev false`

```
Worker Farm: Received message for unknown index for existing child. This should not happen!
/Users/chrisleblanc/Repositories/catalyst-mobileapp/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

TypeError: Cannot read property 'option' of undefined
```

Downgrading the package to 2.6.2 makes it bundle work just fine.

**Comment by avdg** [comment]
Any way to get the error while Uglify is responsible for handling code? Given that we're in a phase we have to release an other bug fix on the uglifyjs side, it would be nice to get a reproduceable sample.

**Comment by LeBlaaanc** [comment]
@avdg pardon my ignorance, what exactly may I help with?

**Comment by Proyoyo** [comment]
Happened to me on RN 0.24.1 as well. Only happened on "Release" scheme though.

**Comment by LeBlaaanc** [comment]
As a temporary solution I added "uglify-js": "2.6.2" to my package.json and reinstalled all of my node_modules.

**Comment by avdg** [comment]
And nobody still knows what went wrong?

**Comment by avdg** [comment]
(sorry for not reacting here, though it would have a bisect like commented over at https://github.com/mishoo/UglifyJS2/issues/1153#issuecomment-227285320)

**Comment by LeBlaaanc** [comment]
@avdg I am not a pro debugger of javascript compiling tools so I'd need some help to help :(

**Comment by avdg** [comment]
This issue is also popping up for grunt-contrib-uglify users.

**Comment by avdg** [comment]
Bug is found in mishoo/UglifyJS2#1154

**Comment by avdg** [comment]
@LeBlaaanc No worries.

**Comment by avdg** [comment]
Can this ticket and mishoo/uglifyJS2#1153 be closed now?

**Comment by satya164** [comment]
Closing as @avdg says it's fixed now.

**Comment by acresta88** [comment]
Hi I tried with multiple version of uglify-js (2.6.2, 2.6.4, 2.7.3, 2.7.5) but still getting the same error, can we reopen it? I'm on RN 0.40

**Comment by avdg** [comment]
Even in 2.8.x?

**Comment by acresta88** [comment]
Yes, I just tried with "uglify-js": "^2.8.14" and get the same problem. But to be honest the error message is not very clear, it just says ` Unexpected token: punc (.) ` but it's not clear where. But after googling the problem the only related issue found is the one with uglify. Is there a way to debug the bundling step thoroughly?

**Comment by avdg** [comment]
how to reproduce from scratch?

**Comment by acresta88** [comment]
@avdg Thanks for the help, after I upgraded I still had the problem, so I dag into uglify to find out what file was creating the problem. At last I found a ` new.target ` in the code that created the problem. From what I can see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) that should be usable, but it's not. An the biggest problem is that uglify didn't tell me anything about where the error was. Now is fixed in my code by removing that statement, but I guess others can have the same problem, so better to share the details about what happened with me :)

**Comment by avdg** [comment]
There was some `new.target` code implemented on the harmony branch. But I think it's a feature that isn't used a lot (unless proven otherwise).

Given that this issue probably refers to the master branch of harmony and by so, don't rely on harmony features, can you please remove these `new.target` snippets from the code?

**Comment by acresta88** [comment]
I'm not using harmony actually, unless is used by some submodule by default. The error with new.target was in my code but uglify didn't tell me where.

**Comment by avdg** [comment]
Stable uglify can't handle `new.target` as it is a harmony feature. remove it.
