### ISSUE TITLE
TextInput's onLayout not called

### ISSUE THREAD

**Issue by nicnocquee** [facebook/react-native#8405]
Not sure why the `onLayout` is not called in `TextInput` component but called in `View` component.

```javascript
  <TextInput
              ref="textInput"
              onLayout={(e) => {
                console.log('--- this is not called?')
              }}
              style={{height: 44, color: 'black', borderColor: 'black', borderWidth: 1, paddingHorizontal: 10, marginHorizontal: 10}}
              placeholder='text here'
              text={'cool'}
              placeholderTextColor={'rgba(0,0,0,.4)'}
              underlineColorAndroid='rgba(0,0,0,0)'
            />
```

Sample project [here](https://github.com/nicnocquee/TestTextInput)

React Native version: 0.28.0
Target: iOS 9.3
Development OS: OS X

**Comment by mangogogos** [comment]
https://github.com/facebook/react-native/releases/tag/v0.29.0-rc.0
Fixed in RN 29

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/92926f9858c0b60cf9f2e51cb8f25f2e1501c9c1

**Comment by StevenKing9** [comment]
not fix ，I found this bug on  a little android‘s device ，example ： 
Nexus and MEIZU

**Comment by jjhesk** [comment]
@facebook-github-bot open
this is an outstanding bug and it is not fixed on version 0.38.0-rc1
I confirm

**Comment by unicornRainbows** [comment]
Not fixed in 
react-native-cli: 1.0.0
react-native: 0.37.0

Not working on View
<View onLayout={(event) => this.measureView(event)} ref="imageProfileHolder" style={{
        flex: 1,
        height: 120
      }}>

measureView(event) {
    console.log('event peroperties: ', event);

    this.setState({svgHeight: event.nativeEvent.layout.height, svgWidth: event.nativeEvent.layout.width});
  }

<3 UnicornRainbows

**Comment by peacechen** [comment]
+1
Confirmed that it's broken in RN 0.37.0.
What's the timeline for this fix?

**Comment by nik910** [comment]
This issue has been fixed in this commit -> https://github.com/facebook/react-native/commit/8a073c1d8b89305a9a2561a7c33740919730f408#diff-b48972356bc8dca4a00747d002fc3dd5
