### ISSUE TITLE
Property autoCapitalize don't work on Android 

### ISSUE THREAD

**Issue by Sylor73** [facebook/react-native#8932]
Property autoCapitalize don't work on Android in TextInput.

```
<View style={styles.dataInputRow}>
  <TextInput
    style={styles.dataInputInput}
    placeholder="Text"
    autoCorrect={false}
    keyboardType="default"
    returnKeyType="done"
    autoCapitalize="words"
    underlineColorAndroid="rgba(0, 0, 0, 0)"
  />
</View>
```

Pls fix it

**Comment by kulmajaba** [comment]
In my testing `autoCapitalize="words"` worked on both Android emulator and device, running Android 6.0 and 6.0.1, React Native version 0.28.

Please provide more info on your testing setup.

**Comment by freakinruben** [comment]
Autocapitalize also doesn't work for me on Android. I'm now running RN 0.30.0 but it has never worked since I started with RN 0.19. I'm testing on an Android 4.2 and Android 4.4 device

**Comment by Sylor73** [comment]
On Android 6.0 in Genymotion don't work
On Android 5 real device don't work

**Comment by reyesr** [comment]
I can confirm there is something fishy, as it works, or not, depending on the other attributes in the TextInput element.

I managed to create a minimal code that can reproduce the issue:

`        <TextInput
            autoCapitalize="words"
            onContentSizeChange={(event) => null}
            style={{paddingTop: 0, backgroundColor: "rgba(255,100,100,1)", color: "rgb(0,179,143)"}}
            keyboardType="default"
            multiline={false}
            onChangeText={(text) => this.setState({text})}
            value={this.state.text}
            selectionColor="#00F"
        />
`

What is weird is that if you use this snippet as is (I added it in a freshly created android react-native project), the autoCapitalize="words" and autoCapitalize="characters" are not respected and the keyboard only displays lowercase characters (ie. the bug appears). It works fine for autoCapitalize="sentences" though.

Now, remove any of the other attributes, onContentSizeChange, style, keyboardType, multiline, or selectionColor, and now it works (the keyboard displays uppercase for the first letters of words).

I reproduced it on several versions of the API (19, 22, 23), and the bug appears consistently as I described above.

**Comment by Sylor73** [comment]
Is there any update on that issue?

**Comment by Sylor73** [comment]
Bump

**Comment by lukefanning** [comment]
Chipping in with some info here, both auto-correct and auto-capitalize are not working in the app I'm working on either on Android with RN 0.33 with **some** keyboards i.e. Google keyboard. I found that Swiftkey for example always seemed to work OK. I created a fresh RN project and it did work with the Google keyboard as long as both `autoCorrect` and `autoCapitalize` were explicitly set. I then replaced my index.android.js render() function in my app with the same code and it didn't work.. I am still investigating and trying to get to the root cause of it!

**Comment by antoinerousseau** [comment]
I had to explicitly add `autoCapitalize="sentences"` to make it work like expected although the doc says it's the default value. But when added, it works well even with other attributes.

**Comment by diegoperini** [comment]
This happened when we transitioned from api level target 22 to 25. Just a letting you know.

**Comment by cooperka** [comment]
I can see that `AutoCapitalizationType` is defined at the bottom of [ReactTextInputManager.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L777) and it looks to be correct... `"sentences"` maps to [`InputType.TYPE_TEXT_FLAG_CAP_SENTENCES`](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_CAP_SENTENCES), but setting it doesn't seem to actually have any effect (as of RN v0.39).

It would be great if someone who has more experience with native bridging could weigh in about what the issue could possibly be.

**Comment by AndrewJack** [comment]
Just in case you are being caught out by this:
`autoCapitalize` only affects the phone's software keyboard capitalisation when inputting text, but typing into your pc's keyboard into your emulator will not be auto capitalised.

**Comment by cooperka** [comment]
@AndrewJack good call! I pulled up the soft keyboard on the emulator and it does seem to work. There is still a small bug as mentioned above, which is that the default seems to be `'none'` rather than `'sentences'` on Android (see [docs](https://facebook.github.io/react-native/docs/textinput.html#autocapitalize)), but it's definitely not a big deal.

**Comment by Proberts** [comment]
I have this issue and it seems connected to setting margin: or padding: in the style for TextInput. I have a repeatable example here: https://rnplay.org/apps/t32avg

If you uncomment either or both the padding: and margin: lines in the style 'input', autoCapitalize won't work.

**Comment by Proberts** [comment]
I've updated [my example](https://rnplay.org/apps/t32avg). There are now two TextInput fields. One has autoCapitalize working and the other doesn't. If you click between them you can see the Android keyboard change from caps to lower-case. The only difference between the two is the broken one has padding: set in the style.

**Comment by Proberts** [comment]
I've done a little more digging and it looks like this is also related to the keyboardType property. If keyboardType is set AND margin or padding is also set in the style property, autoCapitalize is ignored.

**Comment by SuhairZain** [comment]
Hi,
We're having this issue in one of our production app. Have anyone found any workaround for this? It'd be a great help.

**Comment by Proberts** [comment]
@SuhairZain see https://github.com/facebook/react-native/issues/11776

**Comment by SuhairZain** [comment]
@Proberts 
I do not set the keyboardType and still have this issue. Also, this is present only on some devices/OSs. For example, it works fine on Lollipop in Genymotion, but seems to be broken in JellyBean (Samsung device). I'll try and figure our the root issue and let you know.

**Comment by Proberts** [comment]
@SuhairZain At the bottom of the issue there's a PR that fixes it.

**Comment by louisdavidcc** [comment]
Remove keyboardType="default" just like @Proberts did working for me

**Comment by laurent22** [comment]
Maybe it's the doc that needs to be fixed? It says that "sentences" is the default but in my case I had to set it explicitly for it to work (in two different TextInputs with very different properties).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by joncursi** [comment]
@hramos This bug is still present in RN `0.49.1`. Can we re-open? Repro:

```js
<TextInput
  autoCapitalize="characters"
/>
```

On android, when you type, none of the characters are capitalized. Works on iOS though.

**Comment by AndrewJack** [comment]
@jonaslu was this on a real device or the Android emulator?

If the latter make sure you aren't typing on your computer's keyboard. (See https://github.com/facebook/react-native/issues/8932#issuecomment-265098801)

**Comment by joncursi** [comment]
Yeah, I tested on a Galaxy S7 physical device running Android 6.1. It happens on the stock keyboard that the phone ships with, not sure if Gboard fixes it but I believe this should be functional on the default keyboard.

**Comment by hramos** [comment]
Best way forward I think is to open a new issue that follows the template.

**Comment by lasuax** [comment]
Well, I've also came across with this error and was looking for an answer but it seems that if you use the default keyboard of the device, the setting works properly. However, when used with a 3rd party app like SwiftKey, it doesn't operate.

**Comment by tastafur** [comment]
I have been analyzing this problem and it happens when you have activated on the samsung mobile keyboard the **predictive language**

**Comment by PoliakovMaksym** [comment]
The bug is still present. All `autoCapitalize` settings are ignored except `none`.

Environment:
- RN `0.51.0`
- OS `Android 6.0 MRA58K`
- Real device: `Xiaomi Redmi Note 4`

**Comment by javadoffuad** [comment]
don't work on Android 7.0, react-native 0.52

**Comment by colinwong** [comment]
Doesn't work for me.
Android 7.0, Expo SDK 24, Samsung Galaxy S7

**Comment by PoliakovMaksym** [comment]
@colinwong 
This 'solution' isn't working in RN `0.51.0`. Just tested it.

**Comment by colinwong** [comment]
@PoliakovMaksym Hmm. I'm on Expo SDK 24, which is RN 0.51.0. Running on Android 7.0. It worked for me. Must be another issue that's affecting your app.

**Comment by kholiavko-roman** [comment]
I met this problem when `keyboardType` define on android, without it `autoCapitalize` works fine. [Here is a demo on expo](https://snack.expo.io/SJIyVtjhG).

**Comment by superandrew213** [comment]
Instead of omitting `keyboardType`, you can try adding `autoCapitalize={'sentences'}` in case you need to set `keyboardType`. It's working for me.
