### ISSUE TITLE
zIndex does not work with dynamic components on Android

### ISSUE THREAD

**Issue by madox2** [facebook/react-native#8968]
I am trying to render elements conditionally where each element has different zIndex style property.
Using folowing code in Android emulator with react-native 0.30.0.

``` javascript
import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class Demo extends Component {
  constructor(props, ctx) {
    super(props, ctx);
    this.state = {
      showGreen: true,
    };
  }
  render() {
    return (
      <View style={{flex: 1, padding: 20}}>
        <View style={[styles.item, {zIndex: 3, backgroundColor: 'red'}]}>
          <Text>zIndex: 3</Text>
        </View>
        {this.state.showGreen &&
        <View style={[styles.item, {zIndex: 2, backgroundColor: 'green'}]}>
          <Text>zIndex: 2</Text>
        </View>
        }
        <View style={[styles.item, {zIndex: 1, backgroundColor: 'blue'}]}>
          <Text>zIndex: 1</Text>
        </View>
        <View style={styles.button}>
          <Text onPress={() => this.setState({ showGreen: !this.state.showGreen })}>
            Toggle green
          </Text>
        </View>
      </View>
    );
  }

}

const styles = StyleSheet.create({
  item: {
    marginTop: -20,
    height: 50,
    paddingTop: 22,
  },
  button: {
    backgroundColor: 'gray',
    marginTop: 30,
  }
});
```

Initial screen looks like expected:

![zindex1](https://cloud.githubusercontent.com/assets/15847857/17053620/2c5b2a2c-5003-11e6-94b7-ad6892485ed7.png)

When I click 'Toggle green' button to dynamically show/hide green element it hides blue element instead and furthermore element's text is missing:

![zindex2](https://cloud.githubusercontent.com/assets/15847857/17053622/302154b0-5003-11e6-82eb-f7b8fe18676a.png)

When I click the button again, red and green elements remains visible and the toggle button jumps down.

**Comment by dagobertrenouf** [comment]
Same issue here, it seems like zindex breaks component unmounting.

**Comment by roysG** [comment]
any news?

**Comment by tioback** [comment]
Same thing happened to me, so I'll throw in some more details:
In iOS, returning `null` makes the element disappear.
In Android, you have to reduce the height to 0 and remove borders.
What is worse is that you can't stick to a single solution, because Android's workaround won't work for iOS. The element will just show up again.

Here's the code for a component that does this sort of thing:

    import React from 'react';
    
    import {
    	Image,
    	Platform,
    	StyleSheet,
    	Text,
    	TouchableOpacity,
    	View
    } from 'react-native';
    
    import { default as closeIcon } from "../img/closeIcon.png";
    
    const ReadFullArticleFloatingBox = ({visible, opacity = 0, title, onPressRead, onPressClose}) => {
    	let conditionalLayout = visible ? {} : styles.hidden;
    	return Platform.OS === "ios" && !visible ? null : (
    		<View style={[styles.container, conditionalLayout, { opacity }]}>
    			<View style={styles.leftContainer}>
    				<Text numberOfLines={1} style={styles.title}>{title}</Text>
    				<TouchableOpacity onPress={onPressRead} style={styles.readButton}>
    					<Text style={styles.readButtonText}>READ FULL ARTICLE</Text>
    				</TouchableOpacity>
    			</View>
    			<TouchableOpacity onPress={onPressClose} style={styles.icon}>
    				<Image
    						resizeMode={Image.resizeMode.contain}
    						style={styles.iconImage}
    						source={closeIcon}
    					/>
    			</TouchableOpacity>
    		</View>
    	);
    };
    
    const styles = StyleSheet.create({
    	container: {
    		height: 60,
    		position: "absolute",
    		zIndex: 2,
    		left: 0,
    		right: 0,
    		marginTop: 20,
    		paddingHorizontal: 10,
    		borderTopWidth: 1,
    		borderBottomWidth: 1,
    		borderColor: "lightgrey",
    		backgroundColor: "white",
    		flexDirection: "row",
    		alignItems: "center",
    		justifyContent: "center"
    	},
    	hidden: {
    		zIndex: -2,
    		height: 0,
    		borderTopWidth: 0,
    		borderBottomWidth: 0
    	},
    	leftContainer: {
    		flex: 1,
    		padding: 6
    	},
    	title: {
    		fontSize: 13,
    		fontFamily: "CrimsonText-Roman",
    		color: "#46474C"
    	},
    	readButton: {
    		paddingVertical: 6
    	},
    	readButtonText: {
    		fontFamily: "Roboto",
    		color: "teal",
    		fontSize: 11
    	},
    	icon: {
    		width: 40,
    		height: 40,
    		alignItems: "center",
    		justifyContent: "center",
    		padding: 10
    	},
    	iconImage: {
    		width: 20,
    		height: 20
    	}
    });
    
    export default ReadFullArticleFloatingBox;

**Comment by dmitru** [comment]
+1, happened to me in a similar situation.

**Comment by liamfd** [comment]
If it's helpful to anyone, I created a `Hideable` component to handle this:

```javascript
import React, { Component } from 'react';
import {
  View,
  StyleSheet,
  Platform
} from 'react-native';

const hideable_styles = StyleSheet.create({
  android_hidden: {
    height: 0,
    borderWidth: 0,
    paddingTop: 0,
    paddingBottom: 0,
    marginTop: 0,
    marginBottom: 0
  }
});
class Hideable extends Component {
  render(){
    const {hide, children, style = {}, ...rest_props} = this.props;

    // on ios, best way to hide is to return null
    if (hide && Platform.OS === 'ios') return null;

    // otherwise, if android, going to add in the special android hidden styles
    const conditional_layout = hide ? hideable_styles.android_hidden : {};
    const styles = [style, conditional_layout];

    return (
      <View {...rest_props} style={styles}>
        {children}
      </View>
    );
  }
}
```

Here's a simple use:

```javascript
const simpleTestHideable = ({hide = true}) => {
  return (
    <Hideable hide={hide} style={{zIndex: 1, backgroundColor: 'red', height: 100}} >
      <Text>{hide ? 'You should not see this' : 'You should see this' }</Text>
    </Hideable>
  );
}
```

Here's a more complex, interactive usage example:

```javascript
class TestHideable extends Component {
  constructor(props){
    super(props);

    this.state = { hide_content: false };

    this.toggleContent = this.toggleContent.bind(this);
  }

  toggleContent(){
    this.setState({hide_content: !this.state.hide_content});
  }

  render(){
    const { hide_content } = this.state;

    return (
      <View style={{paddingTop: 20}}>
        <Hideable
          hide={hide_content}
          anotherProp="foo"
          style={{
            padding: 10,
            height: 100,
            borderWidth: 0.5,
            borderColor: '#d6d7da',
            marginTop: 100,
            marginBottom: 100,
            backgroundColor: 'red',
            zIndex: 2
          }} >
            <Text>I am showing!</Text>
        </Hideable>
        <Text onPress={this.toggleContent}>{hide_content ? 'SHOW!' : 'HIDE!'}</Text>
      </View>
    )
  }
}

export default TestHideable;
```

You should be able to pass through whatever styles or props you'd like to `Hideable`'s `View`, make it animatable, etc.

Also, @tioback, I noticed you set a negative `zIndex`, is that something you recommend? It's worked for me without it but I wasn't sure if it was needed for certain devices or certain use cases. I also noticed that on my device I had to remove the vertical margins and padding as well, so there may be other styles to watch out for.

I'm still pretty new to React Native so, grain of salt.

**Comment by tioback** [comment]
@liamfd no, I don't recommend for, nor against it. Might be some left-over from a failed test.
Nice component, BTW.

**Comment by asgvard** [comment]
Hi,

I'm struggling with the same issue. It seems like it affects only the elements that are earlier in the array of siblings. Afaik, zIndex only reorders the Views on native, but seems that whenever the element becomes null (removed from the tree), it still overlaps all the elements before it in the array, even though they have higher zIndex (though "higher" is not really applicable here, because higher than what? null element doesn't have zIndex..).
Also this means that the element is not removed completely when it's set to null, because the green color in the initial example still stays, so does it mean that Android doesn't fully remove the view from the tree?
It's a huge problem for me, because I'm building cross-platform app and I'm trying to have as much shared code between Web and Native as possible. I'm using react-router, so I have few <Match> components as siblings. To implement animated transitions between pages I'm using react-motion, that basically sets component to "null" when it's not matched the route. Assuming that I cannot control the order of <Match> components, it causes the issue that if I go from the last page to previous one, the last one becomes "null" at the end of animation and jumps to the front layer because of this issue. All pages are absolutely positioned and fullscreen, so in result I see the full white screen, because this "null" element overlaps everything. It's not a best option for me to use workaround like <Hideable>, because it's platform agnostic, and my goal is to have this animated transitions as a shared component, as well as the react-router <Match>'es.

Here is slightly modified example using three absolutely positioned elements, each subsequent of them have lower zIndex, so red is on top (60px height), green is underneath (90px height), and the blue is underneath (120px height). When the green is removed, the expected behaviour would be that green is completely removed from subviews, the remaining two elements would have their zIndex (order) recalculated, so we would see only red and blue underneath it.
But instead the green one stays alive, and even covers the blue element with "invisible" white overlay. (The same I see in my app with the routes described above). And it occurs ONLY when dynamically remove this green element. If I initially set the flag to false, it doesn't appear which is correct.

Modified example in the fresh react-native app 0.37.0:
```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class zindex extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showGreen: true
    };
  }
  render() {
    return (
      <View style={{flex: 1}}>
        <View style={[styles.item, {zIndex: 3, backgroundColor: 'red'}]}>
          <Text>zIndex: 3</Text>
        </View>
        {this.state.showGreen ?
          <View style={[styles.item, {zIndex: 2, backgroundColor: 'green', height: 90}]}>
            <Text>zIndex: 2</Text>
          </View> : null
        }
        <View style={[styles.item, {zIndex: 1, backgroundColor: 'blue', height: 120}]}>
          <Text>zIndex: 1</Text>
        </View>
        <View style={styles.button}>
          <Text onPress={() => this.setState({ showGreen: !this.state.showGreen })}>
            Toggle green
          </Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  item: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 60
  },
  button: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: 'gray',
    top: 150,
    height: 30
  }
});

AppRegistry.registerComponent('zindex', () => zindex);
```

Starting page:
<img width="289" alt="screen shot 2016-11-10 at 20 30 19" src="https://cloud.githubusercontent.com/assets/2877657/20191476/e40045ca-a785-11e6-8a85-4cad45ca558a.png">


Result:
<img width="289" alt="screen shot 2016-11-10 at 20 30 38" src="https://cloud.githubusercontent.com/assets/2877657/20191484/ed24a86c-a785-11e6-9ca7-5dfd25e66810.png">


Expected behaviour:
<img width="289" alt="screen shot 2016-11-10 at 20 31 01" src="https://cloud.githubusercontent.com/assets/2877657/20191492/f8256e04-a785-11e6-8c19-da8316932d69.png">


Not sure how I will proceed with this issue, but I will keep posting any ideas if I find them.

**Comment by tuckerconnelly** [comment]
Yo I'm the author of that commit :)

@asgvard Thanks for the fantastic bug reporting. I think you're right, check out:

https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewGroupManager.java#L123

I think the fix is as simple as matching the `addView` method and adding:

`
  public void removeViewAt(T parent, int index) {
    parent.removeViewAt(index);
    reorderChildrenByZIndex(parent)
  }
`

I don't really have the bandwidth to PR a fix and test it right now, but you probably could :) It's a good first PR.

**Comment by asgvard** [comment]
@tuckerconnelly Hi, thanks for reply, I will read the PR guidelines and will try to do it in the nearest days.

**Comment by asgvard** [comment]
@tuckerconnelly Hey :) So today I made a try to fix this issue with simply adding the `reorderChildrenByZIndex(parent);` in `removeViewAt` for `ViewGroupManager`, but unfortunately it didn't helped. As I mentioned I'm not a Java developer, so I took some simple steps to debug this by using Logs. I added a `accessibilityLabel` to my `<View>`'s so I can easily see which one is logged in Java code with `view.getContentDescription()`.

Here is my modified JS code:
```javascript
<View accessibilityLabel="RED" style={[styles.item, {zIndex: 3, backgroundColor: 'red'}]}>
          <Text>zIndex: 3</Text>
        </View>
        {this.state.showGreen ?
          <View accessibilityLabel="GREEN" style={[styles.item, {zIndex: 2, backgroundColor: 'green', height: 90}]}>
            <Text>zIndex: 2</Text>
          </View> : null
        }
        <View accessibilityLabel="BLUE" style={[styles.item, {zIndex: 1, backgroundColor: 'blue', height: 120}]}>
          <Text>zIndex: 1</Text>
        </View>
        <View accessibilityLabel="BUTTON" style={styles.button}>
          <Text onPress={() => this.setState({ showGreen: !this.state.showGreen })}>
            Toggle green
          </Text>
        </View>
```

The result leads me to even more deep problem. From JS prospective I'm removing Green view, but in Java it actually tries to remove Blue:

```
11-14 23:31:47.591  9157  9157 I REORDER : manageChildren in NativeViewHierarchyManager...
11-14 23:31:47.591  9157  9157 I REORDER : indicesToRemove: 1
11-14 23:31:47.591  9157  9157 I REORDER : viewToRemove: BLUE
11-14 23:31:47.591  9157  9157 I REORDER : removeViewAt in ViewGroupManager invoked for index: 1
11-14 23:31:47.591  9157  9157 I REORDER : Children before removing: 
11-14 23:31:47.591  9157  9157 I REORDER : 0 child is: BUTTON
11-14 23:31:47.591  9157  9157 I REORDER : 1 child is: BLUE
11-14 23:31:47.591  9157  9157 I REORDER : 2 child is: GREEN
11-14 23:31:47.591  9157  9157 I REORDER : 3 child is: RED
11-14 23:31:47.592  9157  9157 I REORDER : Children after removing: 
11-14 23:31:47.592  9157  9157 I REORDER : 0 child is: BUTTON
11-14 23:31:47.592  9157  9157 I REORDER : 1 child is: GREEN
11-14 23:31:47.592  9157  9157 I REORDER : 2 child is: RED
11-14 23:31:47.592  9157  9157 I REORDER : Reordering started...
11-14 23:31:47.592  9157  9157 I REORDER : Queued to reorder: BUTTON
11-14 23:31:47.592  9157  9157 I REORDER : Queued to reorder: GREEN
11-14 23:31:47.593  9157  9157 I REORDER : Queued to reorder: RED
11-14 23:31:47.593  9157  9157 I REORDER : Reordering end...
11-14 23:31:47.593  9157  9157 I REORDER : view is bringed to front: BUTTON
11-14 23:31:47.593  9157  9157 I REORDER : view is bringed to front: GREEN
11-14 23:31:47.593  9157  9157 I REORDER : view is bringed to front: RED
```

It seems that after initial rendering when the Views get reordered in Java, their order is not invalidated properly, or somehow not exposed to JS, so JS doesn't know that the Green is actually with the index 2 now (while it was 1 initially), because after adding they got reordered, so instead of initial order of [RED, GREEN, BLUE, BUTTON], we have [BUTTON, BLUE, GREEN, RED], which is correct according to reordering by zIndex after all views were added. So then when the view is about to be removed, it's invoked with index 1 (it was initial index of Green), so now as we have Blue at that index, it gets removed instead.

I will try to dig more, but it gets more and more complicated for me tbh :) I would appreciate if you could give a suggestion where to proceed next. 
Cheers

**Comment by asgvard** [comment]
UPDATE:

First of all, I found out that it has nothing to do with the reorderChildrenByZIndex() at all, because we actually don't need to reorder children after we remove something, because the relative zIndex order for remaining items remain the same. The problem was exactly in that it was removing the wrong `View` by it's index in the array.

Fixed by relying on `tagsToDelete` instead of `indicesToRemove` in `manageChildren` method of `NativeViewHierarchyManager`. Because after reordering we cannot rely on the item index in the `ViewGroup`, but the `tag` seems to be reliable way of identifying the `View` anytime. I think the similar reason of using `tagsToDelete` was applied [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java#L162).

Also this issue happens when Adding views, it adds them in the wrong index :) But since after adding the views we're doing reorder again, it doesn't matter that it was added into the wrong place.

So the proposed solution is to change `manageChildren` method, so it will first make a loop by `tagsToDelete`, perform `removeView()` on all the `tagsToDelete`, then after the cleanup of all the nodes to delete, we perform a loop by `viewsToAdd` and that's it. It will remove the huge chunk of code from [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java#L326) to [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java#L377), because essentially all it's doing is `viewManager.removeViewAt(viewToManage, indexToRemove);` only in the case if the node is not animated and not in the `tagsToDelete` array. So instead we could just move this responsibility to the loop by `tagsToDelete`.

I will prepare PR soon :)

**Comment by tuckerconnelly** [comment]
@asgvard Legend! Thanks!

**Comment by asgvard** [comment]
Seems this PR brakes few unit tests (yes I should've double-checked that :) ), will investigate why it failed and prepare another one.

**Comment by asgvard** [comment]
Ok so seems initial idea of just using `tagsToDelete` instead of `indicesToRemove` wasn't good. Because actually `indicesToRemove` consists the nodes that were moved from somewhere, plus the nodes to delete completely. So instead I propagated `tagsToRemove` from UIImplementation, because it's exactly the same as `indicesToRemove`, but in our case `tag` is more reliable way to safely remove nodes.

**Comment by mvf4z7** [comment]
Any updates on this issue?

**Comment by asgvard** [comment]
@mvf4z7 Just keep track of this PR:
https://github.com/facebook/react-native/pull/10954

My local Android unit and integration tests passed. Circle and Travis CI failed for some unrelated reasons, so as soon as someone from Reviewers could have a look into this, maybe we will have it merged. I wouldn't mind to have it asap as well ;)

**Comment by bakr-baroudi** [comment]
Any updates on this issue?

**Comment by farzd** [comment]
any updates?

**Comment by franleplant** [comment]
I'm experiencing this also, `zIndex` + `position:absolute` breaks in android

**Comment by grubstarstar** [comment]
I'm still experiencing this just for the record!

**Comment by srdjanprpa** [comment]
me to, any update?

**Comment by Ycfx** [comment]
same here, `zIndex` + `position : absolute`, any update ?

**Comment by perrosnk** [comment]
any updates on this? I am also experiencing this bug,  with `zIndex` + `position : absolute` on android

**Comment by coderdave** [comment]
Created product pain: https://react-native.canny.io/feature-requests/p/zindex--positionabsolute-breaks-with-dynamic-components-on-android

If the title and/or post can be clarified, I'm all for it.

**Comment by putuyoga** [comment]
Same issue here 🤣

**Comment by rnowm** [comment]
Experiencing the same issue here, but even with position: relative.
I was able to fix this by using a Modal component, but I need the rest of the screen to be touchable, and Modals are fullscreen so I could not use that either.
Thanks!

**Comment by Gumija** [comment]
I am using Modal from react-native and when I close it (set visible to false), it makes my other components disappear one by one. First close navbar, second close a card. Both has elevation and zIndex set.

@rnowm Can you share your fix with Modal?

**Comment by SteffeyDev** [comment]
Glad I'm not the only one having issues with this (zIndex + position: absolute).  I've been trying to statically set zIndex's, but then realized I could just ditch zIndexing my absolute views and just reorder them in my render return so that they stay on top.  I know this will not fix most of the problems of those who actually need to use zIndex but hopefully it helps someone.

**Comment by rnowm** [comment]
@Gumija in my case I just needed one component with z-index (a toast) over my view, maybe that's why it worked for me. Did not tested with other elements using z-index.

**Comment by Kalyani518** [comment]
Same issue here

**Comment by jordanmkoncz** [comment]
I'm also having an issue with `zIndex` + `position: 'absolute'` on Android. I have a dropdown menu component that always displays the currently selected item, and when it is activated, it also displays a list of all of the available dropdown menu items below this. The view that this dropdown menu is used in has other components as siblings of the dropdown menu component, and they are all after the dropdown menu component, since I want the currently selected item of the dropdown menu component to be shown first.

I'm trying to use zIndex so that the list of the available dropdown menu items is shown above the other components that are rendered after the dropdown menu. I'm simply applying a `zIndex: 2` to the `<View>` that contains this list of available dropdown menu items to achieve this. The list of available dropdown menu items is rendered within a `<View>` that has `position: 'absolute'`.

This technique is working perfectly on iOS and behaves exactly as I expect/want. However, the exact same code is not working on Android; The list of available dropdown menu items is always rendered behind the other components that are rendered after the dropdown menu, and therefore is not visible. I've tried all sorts of variations of `zIndex` values for different components in the hierarchy, as well as `elevation`, and nothing seems to make this work on Android, even though it works fine on iOS.

Something must be different about how `zIndex` works in iOS vs Android, as the same code behaves differently in these two environments.

**Comment by fastmuse** [comment]
Same here.

**Comment by smiled0g** [comment]
Problem's still here

**Comment by Beelphegor** [comment]
same here.

**Comment by pengyanb** [comment]
Adding "elevation: 100" to the style solved my issue. 
credit goes to [http://stackoverflow.com/questions/39614040/how-to-give-z-index-property-in-react-native-android-app](url)

**Comment by JannesV** [comment]
Same issue here, everything works as expected without a zIndex (It just doesn't look right) Once I add a zIndex of 1 it goes to shit.

**Comment by smiled0g** [comment]
One tip that might be helpful:
You might get away with changing the rendering order instead of using zIndex. This only works on elements under the same parent though.

**Comment by nhuthuynh** [comment]
i got same issue on **android**, add loading component with absolute + zIndex. It will cause unexpected rendering on that screen (such as some components disappear or white out all screen or some components) and stop the app from working. I have tried all solution mention above such add elevation: 100 and move loading component to the last component in the view. But the issue still happens on **android**.

"react": "15.4.2",
"react-native": "0.42.0",
Genymotion: 2.9.0
Virtual Device: Google Nexus 5X 1080x1920

**Comment by nimatrueway** [comment]
Got the same problem here ! After reading the discussions and skimming through the code I realized that the root problem lies in the current implementation of `zIndex` which is basically invoking `bringToFront()` on the child views in order of their zIndex. ( It is done in `ViewGroupManager.reorderChildrenByZIndex()` method)

This method spoils the natural index of child views in their parent. Therefore `indicesToRemove` parameter in `NativeViewHierarchyManager.manageChildren` will no longer refer to the actual child.

@asgvard did a beautiful job in PRs (#10954) trying to use tag-reference instead of child-index. However @astreet suggested the problem is better be solved fundamentally by migrating to a `zIndex` implementation mechanism that doesn't mess with child-view indices (probably using `ViewGroup#getChildDrawingOrder`).

I assume almost all parent views are of type `ReactViewGroup` and implement a `zIndex` mechanism based on `ViewGroup#getChildDrawingOrder` soon.

**Comment by nhuthuynh** [comment]
actually, elevation property worked on android, just remove zIndex property on android platform and make the component with elevation property is the last component.
```
ios: {
            zIndex: 1
        },
        android: {
            elevation: 1
        },
```

it works for me! thank all!

**Comment by brkyldz** [comment]
@nhuthuynh but elevation adds shadow

**Comment by nhuthuynh** [comment]
@brkyldz : because it will affect z-order on android as it [document](http://facebook.github.io/react-native/releases/0.44/docs/scrollview.html#style) mentioned : " Sets the elevation of a view, using Android's underlying elevation API. This adds a drop shadow to the item and affects z-order for overlapping views. Only supported on Android 5.0+, has no effect on earlier versions."

**Comment by janicduplessis** [comment]
Closing this since it is now fixed (sorry for not posting here I didn't know about this issue).

This will make it in RN 0.45 (May) which should be in RC in a few days.

**Comment by tafelito** [comment]
@janicduplessis I' working on an app that is currently using RN 0.45.1 and it has a View with 3 images inside. I need left and right images to be on top of the center image, so I set a zIndex to the left image so its placed on top of the center one. It does not work. It only works when instead of using zIndex, I use elevation in Android. This way it does work, but I get the  warning error saying  ```Warning: Failed prop type: Invalid props.style key `elevation` supplied to `RCTImageView`.```

This is my code

```JS
<View
  style={{
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  }}
>
  <Image
     source={require('./image_left.png')}
     style={{ top: 60, left: 50, elevation: 1 }} // zIndex doesn't work
  />
  <Image source={require('./image_center.png')} />
  <Image
     source={require('./image_right.png')}
     style={{ top: 100, left: -65 }}
   />
</View>
```

**Comment by Noitidart** [comment]
@janicduplessis I am still having this issue. I uploaded a screencast for ios, android, and even uwp(windows). Android is funky. I was on `0.45.1` but then I ran `react-native-git-upgrade` and then `react-native start` then `react-native run-android` but I am having same issue, even though I am now at `0.46.1`. I uploaded screencasts in a stackoverflow issue here please - https://stackoverflow.com/questions/45021849/zindex-not-working-on-android-0-46-but-does-on-ios-and-even-uwp-windows

**Comment by jaredmharris** [comment]
Can confirm what others have mentioned. I added the following to my style.alert and it works on both platforms now.
```
...Platform.select({
      ios: {zIndex: 9999},
      android: {elevation: 100}
    })
```

**Comment by Noitidart** [comment]
Thanks for your case @jaredmharris. However using `elevation` is not the same as `zIndex`, as pointer-events pass through what is underneath. `eleveation` also causes a shadow to be created.

**Comment by jaycee425** [comment]
still no solution for the Zindex issue on android?

**Comment by janicduplessis** [comment]
I think the issue is that zIndex was not updated properly after the view was mounted. #15203 should fix it, let me know if you can test it and it fixes your problem.

**Comment by Noitidart** [comment]
A sincere thank you for trying your hand to fix it @janicduplessis - it is a big issue for the app I am working on.

**Comment by ali-sao** [comment]
I simply solved this very quickly by creating two identical style objects and one of them doesn't have the zIndex , I chose what style to be served through the Platform checker. 

```
<View style={platform({ ios: styles.overlayContaineriOs, android: styles.overlayContainerAndroid })} >
```

**Comment by sebringj** [comment]
# workaround with same code/style 

My solution to work around this was to give views width and height defined with absolute positioning, then moved them off screen when not in use which worked the same for both.

The container view for these layers had onLayout handler that would set width/height in state in the case "in call" or "hotspot" status made the viewable area smaller.

**Comment by rtman** [comment]
still seeing this issue, I have a listview that when triggered overlays over some other components. Everytime the listview is activated and overlays over the components then is deactivated (removing the overlay) one component dissappears each time.

**Comment by shubhnik** [comment]
I am experiencing maybe a similar zIndex related issue:

![zindex](https://user-images.githubusercontent.com/9150371/29493440-954fdf82-85b3-11e7-9559-4051279fcd1d.gif)
here is the code : [](https://github.com/shubhnik/react-native-view-photos)
the image has `zIndex:1` , i am unable to press the close button :(

**Comment by janicduplessis** [comment]
The fix has not been released yet, it will make it in the next RC release (no eta on when this will happen)

**Comment by Tom29** [comment]
After one year and this error is still exists.
I'm using `0.44.0`

If a view has `zIndex`, then a modal, after closing this modal, the view will be disappear.
This is should be mark as critical error and need to be fixed asap.

**Comment by Tom29** [comment]
@jaredmharris @Noitidart Anyway to prevent pointer-events pass through while using `elevation`?

**Comment by jaredmharris** [comment]
Fortunately I did not have to deal with pointer-events with my code. I popup an alert on the screen that disappears after a few seconds.

Are you using a Modal component? You shouldn't need to set zIndex/elevation for that. Make sure the order of your components are ordered correctly. Children components appear on top of parent components so see if you can change things up to get it to work.

**Comment by Noitidart** [comment]
@Tom29 I could not find a way to make pointer-events pass using `elevation` alone. I would have to include state senstive logic to reorganize the order of elements to make sure my element i need on top is rendered bottom most.

**Comment by Tom29** [comment]
@jaredmharris Yes, i'm using modal, then after closing it, view with `zIndex` will be disappeared.
This is so annoying bug on Android :(
Many thank, i've changed the order or view component instead of using `zIndex` until this bug fixed.

**Comment by glenn-axsy** [comment]
For anyone still stuck on the old RN here's a function I use that can be spread into your styles. It's based on the ideas presented by others above:
```
function zIndexWorkaround(val: number): Object {
    return Platform.select({
        ios: {zIndex: val},
        android: {elevation: val}
    });
}
```
Use it like this in place of e.g: `zIndex: 100`
```
...zIndexWorkaround(100)
```
Remove the Flow type checking from the function if you don't need it

**Comment by Noitidart** [comment]
@glenn-axsy and others reading his comment, just a warning: `elevation` is not a one-to-one solution for `zIndex`. For me it never worked how I needed it, I would get shadows when I didn't, and also the pointerEvents order was incorrect.

**Comment by shuaibird** [comment]
My RN version is 0.49.5 and I've encountered the same issue when setting the `position` to `absolute`. My workaround is rearranging the components, whose orders are based on the `zIndex`. This may introduce some chaos but should be a better approach than setting the `elevation`.

**Comment by cruisecoders** [comment]
My react-native version is 0.49.3 and I am still encountering this problem with the zIndex and the elevation in android. I also used the @glenn-axsy workaround but still couldn't solve the issue.
![skype_picture 1](https://user-images.githubusercontent.com/27813353/33371816-ee9f9664-d521-11e7-850b-b5ee084356da.jpeg)

In the image below I want the user icon on top of the View but it is hiding and not coming on the top as expected

**Comment by mnsrv** [comment]
Why this issue is closed? zIndex still not working on Android, and elevation is not the solution, because of mess of pointer-events.

**Comment by kumarryogeshh** [comment]
Issue exists with react-native version 0.50.3
Works fine on iOS, compatibility issues with Android.

**Comment by Fortidude** [comment]
still not working on Android :/ 

Invalid props.style key elevation supplied to Image.

**Comment by jacklovepdf** [comment]
you can finish the work without zIndex

**Comment by AugustoAleGon** [comment]
It is still not working! this is a mess. I was using zindex but not using is not the solution

**Comment by joaosilva05** [comment]
+1. Works great on ios, breaks views in android

**Comment by FarhadMahmudi1990** [comment]
@janicduplessis
any update?

**Comment by FarhadMahmudi1990** [comment]
Issue exists with react-native version 0.51.0 too

**Comment by rolignu2** [comment]
damm work great in IOS but in ANDROID crash , any update ?

**Comment by nikasvan** [comment]
It's been unresolved for too long any updates?

**Comment by Dror-Bar** [comment]
Works as expected on IOS.
On android neither zIndex nor elevation works for me.
pretty disappointing.

**Comment by VeroGA** [comment]
0.52.1
having the same issue

**Comment by aprilmintacpineda** [comment]
still occur on RN@0.52.0

**Comment by igorarkhipenko** [comment]
0.54.0
The problem still exists

**Comment by aprilmintacpineda** [comment]
please check this newly opened issue. It has a repo that reproduces the problem.

https://github.com/facebook/react-native/issues/18344

**Comment by nirpeled** [comment]
Still having this issue with v0.55.2

**Comment by RostiAP** [comment]
still

**Comment by casey-budee** [comment]
Can we just agree that this issue needs to be reopen NOW?

**Comment by tvtri96** [comment]
Still exist in v0.55.4

**Comment by SourceCipher** [comment]
Yep, having the same issue still. Even setting as absolute, the component will never render on top of the components, always will be hidden by the parent component.
