### ISSUE TITLE
Image Component will not update correctly when passing in new url

### ISSUE THREAD

**Issue by jnrepo** [facebook/react-native#9195]
So I have this basic network image component. It will probably look similar to the one in the Image Component documents. The question is that when I switch the url, for the image, the image itself will not change to the new one, although it seems to be calling the render function again.

Device: iOS
Using: Mac
React-Native: 0.26.3

```
import React from 'react'
import {
  View,
  Image
} from 'react-native'

const NetworkImage = React.createClass({
  getInitialState() {
    return {
      source: this.props.source
    }
  },
  componentWillReceiveProps(newProps) {
    if (newProps.source !== this.props.source) {
      this.setState({
        source: newProps.source
      })
    }
  },
  render() {
    console.log('source: ', this.props)
    return (
      <Image
        style={this.props.style}
        source={this.state.source}
        onLoad={() => {
          console.log('loaded image!')
        }}
        onLoadStart={() => {
          console.log('load starting')
        }}/>)
  }
})

module.exports = NetworkImage
```

**Comment by npomfret** [comment]
I've experienced that same issue.  Try adding a `key={this.state.source.uri}` property to the image

**Comment by eladgel** [comment]
@npomfret this solution works for me

**Comment by jnrepo** [comment]
@npomfret unfortunately the solution didn't work for me. What ended up working was putting a timeout around `setState` within the `componentWillReceiveProps` (not ideal) :/

Code:
```
import React from 'react'
import {
  Image
} from 'react-native'

const TimerMixin = require('react-timer-mixin')

const NetworkImage = React.createClass({
  mixins: [TimerMixin],
  getInitialState() {
    return {
      source: this.props.source
    }
  },
  componentWillReceiveProps(newProps) {
    if (newProps.source.uri !== this.props.source.uri) {
      this.setTimeout(() => {
        this.setState({
          source: newProps.source
        })
      }, 100)
    }
  },
  render() {
    return (
      <Image
        style={this.props.style}
        source={this.state.source}
        onLoad={() => {
          console.log('loaded image!')
        }}
        onLoadStart={() => {
          console.log('load starting')
        }}/>)
  }
})

module.exports = NetworkImage
```

**Comment by npomfret** [comment]
How strange!  This feels like a fairly serious bug.  Can you reproduce it?  What might be helpful is a stand alone git repo that illustrates the problem.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-component-will-not-update-correctly-when-passing-in-new-url

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by wcandillon** [comment]
@npomfret  I learned about the bug the hard way 😅 . It quite a serious one that probably should be reopened.

**Comment by charpeni** [comment]
@wcandillon done. Can you create a replication of the bug on Snack? https://snack.expo.io/

**Comment by wcandillon** [comment]
@Charpeni: I wrote a snack here: https://snack.expo.io/@wcandillon/progressive-image-loading if you use such component (where uri is in the state and we change the value of the RN Image source) on a large collection of images, sometimes it will not refresh the image (5% of the time). Using the workaround above with `key` solves the issue but to creates a flicker in the image.

The way I was able to work around this issue to to superpose the new Image component on top of the old one instead.

**Comment by prakharrke** [comment]
It is not restricted to changing the URI. Even if I change the image at the same URI, it still loads the previously placed image. I'll soon enough put reproduction steps. But if I use Googel Postman to do a simple GET request to the URI, I get the updated image. But Image component still loads the old image.

**Comment by prakharrke** [comment]
I looked into it a lot. As it turns out, React native does not even send a GET request to the server for the image. Which makes me think that it is caching the image somewhere.

**Comment by prakharrke** [comment]
I was going through react native node modules and in react-native->Libraries->Image->ImageSource.js, following is defined.
`/**

Copyright (c) 2015-present, Facebook, Inc.
All rights reserved.
This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
@providesmodule ImageSource
@flow
*/
'use strict';
// This is to sync with ImageSourcePropTypes.js.

type ImageURISource = {
uri?: string,
bundle?: string,
method?: string,
headers?: Object,
body?: string,
cache?: 'default' | 'reload' | 'force-cache' | 'only-if-cached',
width?: number,
height?: number,
scale?: number,
};

export type ImageSource = ImageURISource | number | Array;
`

Which makes me think that there is prop called 'cache', possible values to which are given above. I added to source prop like follows.
<Image source={{uri : myImage, cache: 'reload'}} />

According to its definition, it should always reload the image from the server and not the cache. But it is not working.

**Comment by shohailahm** [comment]
its a serious issue. i am facing it too

**Comment by wcandillon** [comment]
@shohailahm I discuss a workaround for this bug in the following medium story: https://hackernoon.com/5-things-to-know-about-images-react-native-69be41d2a9ee

**Comment by shohailahm** [comment]
@wcandillon without expo there isnt any workaround?

**Comment by wcandillon** [comment]
@shohailahm It might sound super hacky but the T workaround is to superpose new images on top of the "old" ones. This doesn't depend on expo. You can find a example here: https://github.com/wcandillon/react-native-expo-image-cache/blob/master/src/Image.js#L86

**Comment by silver8206** [comment]
found a solution by adapting back how the source code is handling about the loading of image, code below is for iOS as that is what I need for now, have not tried on Android as i think the source code handling loading of image different for both platform:

- If you are loading another image file from your local assets:
   Add this somewhere in your code
   >const resolveAssetSource = require('resolveAssetSource');

   Then at the point that you need to load another image using the same component, do the following:
   > let maps = [resolveAssetSource(new_local_image_name)];
   > this.refs["reference_string_to_your_image_component"].setNativeProps({source: maps});

- If you are loading another image from the network, add the following codes at the point that you need to load the image using the same component:
   > maps = [{uri: "https://network_address_to_the_image", width: image_width_int, height: image_height_int}];
   > this.refs["reference_string_to_your_image_component"].setNativeProps({source: maps});

**Comment by dantesolis** [comment]
Hey folks is this issue still open? and May I take it? Thanks

**Comment by jnrepo** [comment]
I haven't had much time to dig into this issue further, but I've been able to avoid this by using https://github.com/DylanVann/react-native-fast-image. I understand that this isn't an ideal solution either, but if you need a recommendation...

**Comment by ignacioola** [comment]
I couldn't reproduce this. Maybe it's no longer an issue?

**Comment by jsoendermann** [comment]
> I couldn't reproduce this. Maybe it's no longer an issue?

Still having this issue on 0.57.4

**Comment by maxstralka** [comment]
Still an issue. Using `key={this.state.source.uri}` fixes it though.

**Comment by kylebebak** [comment]
Woooooooowzer. I'm speechless.

**Comment by npomfret** [comment]
Yep. The image component has been broken since 2016.

**Comment by dantesolis** [comment]
I have put this on the side for a while, but will be investigating this and working on it
on the following days

**Comment by wagnermaciel** [comment]
Was this issue ever completed or is everyone just using `key={this.state.source.uri}`as a workaround?

**Comment by dopey2** [comment]
@wagnermaciel key props doesn't work in my case :/

**Comment by wagnermaciel** [comment]
In that case myself and a few friends are looking for a react-native issue to tackle. We might start working on this one as part of a semester project.

**Comment by muhammadridho** [comment]
There are some steps, to tackle this issue

1.  Adding key to Image component
`<Image key={state.imageUri} ...`

2. Convert to http into https url
 from `<Image source={{uri : "**http**://yourweb/yourprofile.png"}} />
 into `<Image source={{uri : "**http**://yourweb/yourprofile.png"}} />

3. Add Cache options
`<Image source={{uri : myImage, cache: 'reload'}} />`

**Comment by mechazod** [comment]
@wagnermaciel It works for me https://github.com/facebook/react-native/issues/12606#issuecomment-549231175 hope it helps.

**Comment by Ampemk** [comment]
I ran into the same issue when I was setting the image through state in componentDidMount. What worked for me is moving the image fetch to the render. 

I fixed my issue by calling a helper in render() to set the image path and using that image constant instead of state. Works for me, all other solutions didn't work.

**Comment by ArthurNameless** [comment]
> I've experienced that same issue. Try adding a `key={this.state.source.uri}` property to the image

Dude, I love you!!!
Thanks!

**Comment by npomfret** [comment]
I can't believe the image component has had this issue since 2016 and still isn't fixed.

**Comment by ArthurNameless** [comment]
Yeap and this is very pity situation

**Comment by RnbWd** [comment]
I've been working with this issue for over a day. I'm trying to overwrite user profile photo's, but on android, I actually need to close the app and re open it for the image to change. Changing keys doesn't even work.

**Comment by npomfret** [comment]
The RN image component has been fundamentally broken since 2016.  I don't think it's ever getting fixed.  Maybe there's an alternative implementation out there?

**Comment by Awfulnaut** [comment]
Still broken on RN 61, even after adding the key prop, cache="reload", and converting http to https.

**Comment by Razzze** [comment]
Still have the same problem, adding key, cache didn't help

**Comment by tobiasr** [comment]
I think I've been able to reproduce this issue in a new Snack, here:
https://snack.expo.io/@rundbom/image-should-update

By using lorem picsum as a source a new remote image is available on each request to the same URI.

We force the image to rerender by updating the key prop.

The image doesn't change even though `cache: 'reload'` is used.

This might be expected behaviour though?

One idea on fixing this (which I could send a PR on) would be to look have `request.cachePolicy` impact if a cached image is used in `RCTImageLoader._loadImageOrDataWithURLRequest`.

Would be glad to help out no this!

**Comment by BruceSuperProgramer** [comment]
Guys just simply assign <Image key={diffrent key} /> with a different key. Every time the screen rerendered if it found key is a new one it will rerender this component again even it has the same URL.

**Comment by tobiasr** [comment]
> Guys just simply assign <Image key={diffrent key} /> with a different key. Every time the screen rerendered if it found key is a new one it will rerender this component again even it has the same URL.

So, my example in Snack is contradicting exactly this. Given the same URL a new key will not "reload" the image (the component will be rerendered but the image won't be refetched). Tampering with the URL will reload the image. This is however in contradiction with the title of this issue, so it might be OT (the discussion have been talking about this case for a while though)?

On IOS the image component seems to have support for the `cache: 'reload'` setting. The native code doesn't seem to do anything to support that setting though. So my question was if the IOS specific code should respect the setting, or maybe if the setting should be removed or documented as not working in this case?

**Comment by BruceSuperProgramer** [comment]
@tobiasr In that case, is there any possibility to fix it by adding? new Date() right after the image URL. Something like that `https://image/image.jpg?${new Date()}`

**Comment by tobiasr** [comment]
@BruceSuperProgramer That will fix the issue.

For me, the question is regarding this documentation for IOS:
https://reactnative.dev/docs/images#cache-control-ios-only

My Snack, too me, is proving that these settings (at least `cache: 'reload'`) have no effect on the load behaviour of the data on the other side of the URI.

So either an issue should be fixed or perhaps the settings should be removed/documented as not working?

**Comment by SahanDll** [comment]
> @tobiasr In that case, is there any possibility to fix it by adding? new Date() right after the image URL. Something like that `https://image/image.jpg?${new Date()}`

Worked for me

                        source={{
                            uri: REST_ENDPOINT_BASE + "/document-view/sample.jpg?date=" + moment().valueOf()
                            cache: "reload",
                            headers: {
                                Pragma: "no-cache",
                            }

**Comment by tobiasr** [comment]
> > @tobiasr In that case, is there any possibility to fix it by adding? new Date() right after the image URL. Something like that `https://image/image.jpg?${new Date()}`
> 
> Worked for me
> 
> ```
>                     source={{
>                         uri: REST_ENDPOINT_BASE + "/document-view/sample.jpg?date=" + moment().valueOf()
>                         cache: "reload",
>                         headers: {
>                             Pragma: "no-cache",
>                         }
> ```

I think it it should work without cache: "reload" as well, right? As I've tried to explain above, that setting isn't used on the image component.

**Comment by Vivekmanu4343** [comment]
Even I'm facing this issue and any of the above solutions did not help me in any way. The Text component is printing proper URI during each render but the image still shows up the same.

```
{thumbnails.map((thumbnail) => (
                  <View>
                  <TouchableOpacity onPress={() => setSelectedThumbnail(thumbnails[index])}>
                    < Image source={{ uri: thumbnail, cache: "reload",
                        headers: {
                            Pragma: "no-cache",
                        } }} style={{ width: 30, height: 30, marginLeft: 10 }} />
                  </TouchableOpacity> 
                <Text key={thumbnail} style={{fontSize:7}}>{thumbnail}</Text>
                </View>
                  ))}
```

Please look at the image and its URI.
![image](https://user-images.githubusercontent.com/56953880/97109320-a02df900-16f8-11eb-8f37-84db576d72da.png)

Note: The image is rendering properly when i just make any small change and expo refresh the page.

**Comment by sandyvb** [comment]
Tried all of the suggestions above with no success :(

**Comment by atosh502** [comment]
> I've experienced that same issue. Try adding a `key={this.state.source.uri}` property to the image

For me it worked on I combined key with date ie. key=`${this.state.source.uri}${new Date()}`

**Comment by ashadnasim52** [comment]
> > I've experienced that same issue. Try adding a `key={this.state.source.uri}` property to the image
> 
> For me it worked on I combined key with date ie. key=`${this.state.source.uri}${new Date()}`

It worked :)

**Comment by bilal-korir** [comment]
> I've experienced that same issue. Try adding a `key={this.state.source.uri}` property to the image

Brilliant! thank you @npomfret

**Comment by Leleka14** [comment]
for me it forked to randomly assign imageIndex only once when component is mounted and if image is changed, it only takes to refresh screen, may not be the best solution, but at least image is not flickering

**Comment by vipulchakravarthy** [comment]
> I've experienced that same issue. Try adding a `key={this.state.source.uri}` property to the image

OMG!!!!!!! You really saved my day @npomfret

**Comment by VictorioMolina** [comment]
The problem still persists. Updating the image component via dynamic keys is kinda weird.

**Comment by OsidAbu-alrub** [comment]
Issue still happens, I fixed it by using conditional rendering. 

So if there's a file uploading, I remove the Image component and replace it with a loader. Then add it again once the image is uploaded successfully to the server.

**Comment by jmzaremba** [comment]
The issue happened to me. I found a fix that is similar to [OsidAbu-alrub]'s comment above, though it includes a few extra steps. You will need an imageUrl state, image state, refresh state, useEffect function.

When you want to change the image url and re-render the image component, set the imageUrl to your new value through a function call or however, then set the refresh state to true to call the useEffect function with imageUrl as a dependancy. Once this function is called, set image state to whatever component you want, i used <ActivityIndicator/> then set timeout for 150ms and change the image state back to the original Image component and it should re render with the new imageUrl. Then set Refresh to false so the user can change the picture again. Make sure you put the setTimeOut period to greater than 0ms as it didn't appear to work - try 150ms minimum.

This method works 99% of the time - code example below.

const [imageUrl, setImageUrl] = useState("https://......");
const [image, setImage] = useState(<Image style={style} source={{uri: imageUrl}} />);
const [refresh, setRefresh] = useState(false);

useEffect(() => {
  if(refresh){
    // Set image hook to ActivityIndicator or any component - To prevent resizing provide style prop with same style as image
   setImage(<ActivityIndicator size="large"/> );
  
   // After 150 seconds change the image state back to the original image component
   setTimeOut(() => {
     setImage(<Image style={style} source={{uri: imageUrl}} />);
     setRefresh(false);
   }, 150)
  }
},[imageUrl])

return(
  <View>
    {image}
  </View>
)

**Comment by ricardo42alves** [comment]
I'm still having this issue on the `"react-native": "0.70.5",`  do anyone know on witch version this was fixed?

**Comment by CalvinJamesHeath** [comment]
`<img src='yourUrl' key={Math.random()}/>`

**Comment by skyllex94** [comment]
Here's an example of how to fix it in a functional component
{list.map((path, idx) => (
<Image key={path} source={{uri: path}} />
))}
