### ISSUE TITLE
Android: Picker's dropdown arrow disappears when backgroundColor is set

### ISSUE THREAD

**Issue by mhagmajer** [facebook/react-native#9434]
The right-most dropdown arrow is invisible for picker rendered with the code below

``` jsx
<Picker
  mode="dropdown"
  style={{backgroundColor: 'beige'}}
  selectedValue={this.state.language}
  onValueChange={(lang) => this.setState({language: lang})}>
  <Picker.Item label="Java" value="java" />
  <Picker.Item label="JavaScript" value="js" />
</Picker>
```

**Comment by Jaafar-abusair** [comment]
I agree, why there is no arrow?

**Comment by littletower** [comment]
+1

**Comment by lsps9150414** [comment]
When style is provided the triangle disappears. Looking for a way to keep the triangle while styling it.

**Comment by stoufa88** [comment]
+1

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by lay-z** [comment]
+1

**Comment by BroshkovD** [comment]
+1

**Comment by vitorbaraujo** [comment]
Is there any solution to that?

**Comment by Jaafar-abusair** [comment]
just remove the background color for the picker.

**Comment by vitorbaraujo** [comment]
That works, but I was trying to make the dropdown arrow to appear and have the same color as the text. But when I set color to the picker, the text changed its color, but not the arrow

**Comment by Jaafar-abusair** [comment]
I solved it by setting the background color to white, and replace it inside a parent view after that i added icone to the view just next to the picker with absolute position above the picker like right:10. And this gave me what you looking for

**Comment by nrathi** [comment]
If you wrap the picker in a View with a background color, it works fine:

```
<View style={{backgroundColor: '#FFF'}}>
  <Picker ... />
</View>
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/android-pickers-dropdown-arrow-disappears-when-backgroundcolor-is-set

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.

**Comment by pacozaa** [comment]
@nrathi works fine but this issue is still there. 

It means you can not set `backgroundColor` in Picker

**Comment by phemonick** [comment]
it worked by simply wrapping your picker in a view:
 <View style = {styles.pick}>
                <Picker
                    mode= "dropdown"
                    selectedValue={this.state.language}
                    onValueChange={(itemValue, itemIndex) => this.setState({language: itemValue})}>
                    <Picker.Item label="language"  />
                    <Picker.Item label="French" value="French" />
                    <Picker.Item label="Spanish" value="Spanish" />
                </Picker>
</View>

**Comment by phemonick** [comment]
it worked by simply wrapping your picker in a view, then adding a background to the view

**Comment by manojbhardwaj** [comment]
How i can change drop down icon color of picker

**Comment by CristianeMayara** [comment]
I have the same problem. Does anyone know how to change the color of the dropdown icon?

**Comment by EvanSays** [comment]
Here's a way to change the dropdown icon/carrot color @manojbhardwaj @CristianeMayara,

In styles.xml...

```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
         <item name="android:colorControlNormal">#FFFFFF</item>
    </style>
</resources>
```
