### ISSUE TITLE
Text color with opacity seems calculated incorrectly

### ISSUE THREAD

**Issue by watert** [facebook/react-native#9781]
When using Text with opacity, it seems like the opacity will be applied twice and gets a much lighter color.

Demo of using ways of using different component, color and opacity
![image](https://cloud.githubusercontent.com/assets/231625/18298058/49f027a4-74e8-11e6-99fb-e5167d2f2171.png)

Demo Code: 

``` javascript
<Text style={{color:'rgb(0,0,0)', opacity:1, }}>text with rgb(0,0,0) => hsb(0,0,0)</Text>
<Text style={{color:'#000', opacity:.54}}>text with text opacity:.54 => hsb(0,0,70) </Text>
<View style={{opacity:.54}}>
  <Text style={{color:'#000', }}>text inside view opacity:.54 => hsb(0,0,45) </Text>
</View>
<View style={{backgroundColor:'rgba(0,0,0,.54)'}}>
  <Text style={{color:'#FFF'}}>view with rgba(0,0,0,.54) => hsb(0,0,45)</Text>
</View>
<View style={{backgroundColor:'rgb(0,0,0)', opacity:.54}}>
  <Text style={{color:'#FFF'}}>view with opacity:.54 => hsb(0,0,45)</Text>
</View>
```

My RN Version:  `"react-native": "^0.30.0"`

**Comment by leeight** [comment]
Looks like it was fixed in the master branch?

![image](https://cloud.githubusercontent.com/assets/104052/18300057/49c50cc6-74f8-11e6-8a46-c9d37ab7c6c3.png)

**Comment by watert** [comment]
Bug still exists in 0.32.0, tested in iPhone 6 simulator, maybe it's fine in Android?

**Comment by watert** [comment]
![image](https://cloud.githubusercontent.com/assets/231625/18309574/b03d061e-752c-11e6-8914-1f08294d2ff6.png)

master branch has this issue too... and the last row `view with opacity:.54` seems different with Android version by @leeight

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-color-with-opacity-seems-calculated-incorrectly

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by shauns** [comment]
In case anyone encounters this; still an issue in RN 0.37 / workaround is to use `rgba` on the text element's `color` style.
```jsx
<Text style={{color: rgba(0,0,0,0.87)}}>Test</Text>
```

**Comment by arribbar** [comment]
Still an issue now using this notation
```
<Text style={{color: '#ff4a4a4a' }}>Test</Text>
```
