### ISSUE TITLE
react-native cli cannot start iPhone simulator [Xcode 8]

### ISSUE THREAD

**Issue by julienvincent** [facebook/react-native#9900]
After updating my Xcode version 8 [GM], running `react-native run-ios` fails to start iPhone simulator (No errors, just nothing happens).

The terminal output is the same as always:
```
Found Xcode project <project>.xcodeproj
Launching iPhone 6 (10.0)...
Building using "xcodebuild -project <project>.xcodeproj -scheme <project> -destination id=05675D07-A893-4731-9606-1290FF7C1C9F -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = <project>/ios/build

=== BUILD TARGET RCTVibration OF PROJECT RCTVibration WITH CONFIGURATION Debug ===
```

**Comment by chrise86** [comment]
Mine won't start either, but I am getting:

```
The following build commands failed:
	CompileC /Users/chrisedwards/Apps/ReactNative/MyApp/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/Layout.o /Users/chrisedwards/Apps/ReactNative/MyApp/node_modules/react-native/React/Layout/Layout.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by miguelc1221** [comment]
I fixed it by opening up Xcode after updating it. When you open up Xcode, it will ask you to install some missing components, after you install them, you can then run ```react-native run-ios``` and it should work fine.

**Comment by julienvincent** [comment]
I'm still unable to `run-ios` event after Xcode installed its missing components.

**Comment by chrise86** [comment]
Same, I notice this amongst all the fuzz:
```
lang: error: no such file or directory: '/Users/chrisedwards/Apps/ReactNative/MyApp/node_modules/react-native/React/Layout/Layout.c'
clang: error: no input files
```
and then right at the end:
```
The following build commands failed:
	CompileC /Users/chrisedwards/Apps/ReactNative/MyApp/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/Layout.o /Users/chrisedwards/Apps/ReactNative/MyApp/node_modules/react-native/React/Layout/Layout.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by julienvincent** [comment]
@chrise86 We have different problems, I do not get compile issues - the only problem is my sim not starting. I suggest you open a new issue with your stack traces.

**Comment by julienvincent** [comment]
I have solved the problem by following the steps listed in [this stackoverflow answer](http://stackoverflow.com/questions/27338042/xcode-simulator-not-coming-up-reinstall-possible)

To summarise - I deleted all configured simulators from the Simulator devices menu, restarted and then re-added the relevant simulators. After doing this, `$ react-native run-ios` could successfully launch a sim

**Comment by sahibhussain** [comment]
if nothing works you may have to add simulator yourself by simple steps
1. click on the list of simulators (which would be empty with only 1 option i.e. generic iOS Device)
2. click on add additional simulator
3. in bottom left corner click on plus and select add simulator.
4. simply select the simulator you want.
